### ISSUE TITLE
no moving vehicles and humans 

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1006]
Hi,

I  tried the most recent released windows-binaries of CityEnviron:
https://github.com/Microsoft/AirSim/releases

But I can't find any moving vehicles and humans within.
Does the current version contain moving vehicles and humans? 

Thanks.

**Comment by allen9273** [comment]
Same problem. There are no moving vehicles and people in v1.1.9, but you can find them in v1.1.8.

**Comment by husha1993** [comment]
I can find the moving vehicles in v1.1.8 but can't find the moving people in v.1.1.8...

**Comment by allen9273** [comment]
I found people in v1.1.8 around the houses.
![img_0_0_35380800176825](https://user-images.githubusercontent.com/37375217/39234618-e9665502-48b2-11e8-859b-bee77004ef65.png)

**Comment by sytelus** [comment]
Could you please try latest release. There are bunch of pedesterians in there: https://github.com/Microsoft/AirSim/releases/tag/v1.1.10
