### ISSUE TITLE
Don't show car info on screen

### ISSUE THREAD

**Issue by NextSim** [microsoft/AirSim#1007]
How  can I turn off the data shown on the screen (accel, brake, control mode, etc)?

I looked through the settings and didn't see anything

**Comment by NextSim** [comment]
I tried adding that and it didn't affect it.  I'll try using the console, but I need to be able to have it launch that was or programatically remove it.

Here is my setting.json

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "SimMode": "Car",
  "RecordUIVisible": false,
  "LogMessagesVisible": false
}

```

**Comment by NextSim** [comment]
Is this something that is set when the project is packaged?

I have tried on a few scenarios, on City, Africa and Neighborhood the log shows, regardless of what is in the settings file.

I created a project from landscape mountains, and this project, as well as the blocks project, never shows the info, regardless of what is in the settings file.

**Comment by rajat2004** [comment]
@jonyMarino Actually this problem still exists in master, so this issue can be reopened I think

**Comment by jonyMarino** [comment]
@rajat2004 Thank you. I thought it was a duplicate of  #1583 (closed)

**Comment by rajat2004** [comment]
Yeah, that issue seems to have been closed to keep discussion here. Will try to look into this and maybe open a PR
Thanks for all the hard work you and the other maintainers have been putting in to clean up the issues!
