### ISSUE TITLE
DQNcar in PythonClient is not working (will not converge)

### ISSUE THREAD

**Issue by QiyuZ** [microsoft/AirSim#1009]
There is an example in PythonClient which applies DQN to run the car. However, I ran it for a long time and found it will not converge. Does anyone success?

**Comment by mitchellspryn** [comment]
Not sure about the tutorial on this page, but you may try ours [here](https://github.com/Microsoft/AutonomousDrivingCookbook/tree/master/DistributedRL).

**Comment by zimmy87** [comment]
Hi @QiyuZ, thank you for reporting this issue.  This script was recently removed in #3215 and replaced with a new script at \AirSim\PythonClient\reinforcement_learning\dqn_car.py that uses the new airgym module. I tested the new script locally and it runs fine for me. Can you retest with the new script and confirm whether you are still seeing this issue or not?
