### ISSUE TITLE
Windows build failure

### ISSUE THREAD

**Issue by EthanZhangYi** [Microsoft/AirSim#1012]
Error occurs when I build AirSim on Windows from source code.
System: Windows 10
Cmake: 3.11.1
VS: visual studio 2015 update 3  community version
![error](https://user-images.githubusercontent.com/13479831/39244232-ac48f8f4-48c2-11e8-8a2b-c0c6ffed7a03.PNG)

Anyone can give some help?

**Comment by BrunoXL** [comment]
Which prompt are you using to build? You should you use the `x64 Native tools command prompt`.

**Comment by sytelus** [comment]
Just fixed it. Thanks for reporting this issue.
