### ISSUE TITLE
Unable to continue with AirSim in Unreal - Windows

### ISSUE THREAD

**Issue by dileep-krishnan** [Microsoft/AirSim#1013]
Hi
I am following the instructions as given in [this YouTube video](https://www.youtube.com/watch?v=1oY8Qu5maQQ) to build AirSim in Windows. Once I copy the files as explained, when I am trying to load the project in Unreal Editor, I am getting the following error.
![epic_games_err](https://user-images.githubusercontent.com/27542113/39245020-2e8b6472-48b0-11e8-9bca-5ed9b4796678.png)

When I give the option for rebuild, an error comes as the project cannot be compiled.
![epic_games_err_2](https://user-images.githubusercontent.com/27542113/39245099-5ba0b854-48b0-11e8-9b25-4c7a784d32bd.png)

My system software is as follows.
OS: Windows 7 Pro x64
Microsoft Visual Studio Professional 2015
Unreal Engine 4.14.3

Please advice what to do next.
Thanks a lot in advance.

**Comment by sytelus** [comment]
YouTube video is bit old. Could you please make sure you are using these steps? 

https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md

**Comment by dileep-krishnan** [comment]
Thanks for the reply.
I started fresh, following the instructions given in the above github page. I am getting an error as follows.

```
Exception setting "SecurityProtocol": "Cannot convert null to type "System.Net.
SecurityProtocolType" due to invalid enumeration values. Specify one of the fol
lowing enumeration values and try again. The possible enumeration values are "S
sl3, Tls"."
At line:1 char:32
+ & { [Net.ServicePointManager]:: <<<< SecurityProtocol = [Net.SecurityProtocol
Type]::Tls12; iwr https://github.com/rpclib/rpclib/archive/v2.2.1.zip -OutFile
external\rpclib.zip }
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The term 'iwr' is not recognized as the name of a cmdlet, function, script file
, or operable program. Check the spelling of the name, or if a path was include
d, verify that the path is correct and try again.
At line:1 char:89
+ & { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]:
:Tls12; iwr <<<<  https://github.com/rpclib/rpclib/archive/v2.2.1.zip -OutFile
external\rpclib.zip }
    + CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

The term 'Expand-Archive' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:19
+ & { Expand-Archive <<<<  -Path external\rpclib.zip -DestinationPath external\
rpclib }
    + CategoryInfo          : ObjectNotFound: (Expand-Archive:String) [], Comm
   andNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
As a workaround, I am commenting out the corresponding lines  in build.cmd and manually downloading the files required.

**Comment by dileep-krishnan** [comment]
I have found a solution for the above problem. It is explained [here](https://github.com/Microsoft/AirSim/issues/1021). If possible, this details can be added in the build guide.

**Comment by sytelus** [comment]
Yes, we will update the docs. Thanks.
