### ISSUE TITLE
Api params

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AirSim#1015]
Is there any documentation on the params that are to be sent with the api command?

I know some of the api is mentioned here:

https://github.com/Microsoft/AirSim/blob/master/docs/apis.md

but it seems that using the api for requests like reset and getCarState are not as simple as sending the api command.

**Comment by sytelus** [comment]
Not sure what you mean by "sending" API command. Both of API calls are simply function calls in Python.

**Comment by NextSim** [comment]
Sending to AirSim over the tcp connection.  So data has to be serialized into the msgpack-rpc format and sent over the tcp connection to AirSim

![image](https://user-images.githubusercontent.com/38044495/39309669-9399687e-4936-11e8-8454-942fbbdcda95.png)

**Comment by NextSim** [comment]
Thanks
