### ISSUE TITLE
The question about moveByAngleZ

### ISSUE THREAD

**Issue by XLMaverick** [Microsoft/AirSim#1018]
when I use the moveByAngleZ in hellowDrone，I will meet the problems：
‘’‘’
Exception raised by the API, something went wrong.
rpclib: server could not find function 'moveByAngleZ' with argument count 5.
‘’‘’
My airsim is v1.1.10，the way of me is 
		client.moveByAngleZ(0.2f, 0.0f, z, 0.0f, duration);
		std::this_thread::sleep_for(std::chrono::duration<double>(duration));

**Comment by sytelus** [comment]
I tried this out with latest binaries and latest code and can't reproduce it. I think you are using something that is older. Please make sure to use everything from latest version.
