### ISSUE TITLE
Deactivate maximum roll and pitch rotation angles (Stabilize mode)

### ISSUE THREAD

**Issue by Domi47** [Microsoft/AirSim#1022]
This question is somehow related to my last issue #973. I need to rotate drone in roll and pitch without restrictions, and computer vision mode doesn't allow me to control velocity. My questions are:
where can I change these maximum rotation angles? is there any way to set this mode (I think its called stabilize mode) using simpleFlight?

Thanks!!

**Comment by sytelus** [comment]
See the max_limit settings in simple_flight params: https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/Params.hpp#L54
