### ISSUE TITLE
NULL in g_pWheelRumbleHandle

### ISSUE THREAD

**Issue by rohjunha** [Microsoft/AirSim#1027]
I am suffering from nullptr error of `g_pWheelRumbleHandle` in `DirectInputJoyStick.cpp` after pulling from the master branch. I guess the commit 5dd876c477f1ef49cab047e82592f61b8ef89306 might cause the problem for me. I am currently using G29 and my code was working well before pulling.

**Comment by sytelus** [comment]
This might be from Thrustmaster support added by @kissslorinc (see #979). May be @kissslorinc can help?

**Comment by sytelus** [comment]
Just checked-in potential fix. You can try out latest version and let us know if that worked.

**Comment by kissslorinc** [comment]
thanks @sytelus for the hotfix!

**Comment by rohjunha** [comment]
I guess this part should be modified as well: https://github.com/Microsoft/AirSim/blob/126900e52a54bd6ee1cc36476dc23fb22c23051b/Unreal/Plugins/AirSim/Source/SimJoyStick/DirectInputJoyStick.cpp#L83-L84
```
if (g_pAutoCenterHandle) {
			g_pAutoCenterHandle->SetParameters(&g_sAutoCenterConfig, DIEP_DIRECTION |
				DIEP_TYPESPECIFICPARAMS | DIEP_START);
		}
```

**Comment by sytelus** [comment]
Agreed and done!

PS: if you get latest, we have now also upgraded to UE 4.18 and VS 2017.

**Comment by rohjunha** [comment]
Thanks for the update. I will close this issue.
