### ISSUE TITLE
Does moveByAngleZ() API work?

### ISSUE THREAD

**Issue by Domi47** [microsoft/AirSim#1028]
As far as I understand, this API allows you to keep a constant height and move according to a roll, pitch yaw configuration you must set. But when I try to use it (let's say with client.moveByAngleZ(30,0,-15,0,15)), it has an erratic behavior, not keeping any constant Z and rotating randomly on any axis (during 15 secs in this case).
So my questions are:

How does this API work? does it allow you to keep a constant Z despite any roll, pitch yaw configuration? (how could it do like that, without disable thrust) 

Is this API actually working properly?

Thanks!!

**Comment by sytelus** [comment]
It seems to work fine. The angles are in radians and usually 30-degrees is too much for drones. If you angle too much PID controller won't be unable to keep the height.
