### ISSUE TITLE
error in ./build.sh

### ISSUE THREAD

**Issue by z2140684** [Microsoft/AirSim#1031]
when i try to build airsim,erroe occured

[ 90%] Linking CXX executable ../output/bin/HelloDrone
clang: warning: argument unused during compilation: '-nostdinc++' [-Wunused-command-line-argument]
CMakeFiles/HelloDrone.dir/home/ubuntu/airsimenv/AirSim/HelloDrone/main.cpp.o: In function `main':
/home/ubuntu/airsimenv/AirSim/HelloDrone/main.cpp:63: undefined reference to `msr::airlib::MultirotorRpcLibClient::armDisarm(bool)'
/home/ubuntu/airsimenv/AirSim/HelloDrone/main.cpp:103: undefined reference to `msr::airlib::MultirotorRpcLibClient::armDisarm(bool)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
HelloDrone/CMakeFiles/HelloDrone.dir/build.make:97: recipe for target 'output/bin/HelloDrone' failed
make[2]: *** [output/bin/HelloDrone] Error 1
CMakeFiles/Makefile2:385: recipe for target 'HelloDrone/CMakeFiles/HelloDrone.dir/all' failed
make[1]: *** [HelloDrone/CMakeFiles/HelloDrone.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by haider04** [comment]
Which windows you are using? And which visual studio and Cmake versions have you tried?
