### ISSUE TITLE
About build error, can't find the rpclib.zip

### ISSUE THREAD

**Issue by tea000001** [Microsoft/AirSim#1040]
As title,
why I run build.cmd always show that 
![image](https://user-images.githubusercontent.com/37363135/39507657-8893d7fe-4e11-11e8-919b-8957abaf7ce5.png)

**Comment by haider04** [comment]
I guess you might be using windows 7. Right? 

I had the same problem and the build problem was resolved after installing Power shell 5.1

You can give a try and i hope it will solve your problem.

**Comment by tea000001** [comment]
OK, I succeed~ 
Thank you very much
