### ISSUE TITLE
How to get pedal and wheel axis settings

### ISSUE THREAD

**Issue by haider04** [Microsoft/AirSim#1042]
Hi,

I want to map my steering wheel (SimSteering from Leobodnar) and throttle, brake pedals (fanatec) in the AirSim by making some changes in the code as i was suggested earlier. For this, i have 3 questions:

1. How can i get the axis settings of my wheels and pedals so that i can map them accordingly in the code?
2. In which code files i have to make changes? SimJoyStick.cpp or CarPawn.cpp or in which others? 
3. Should i make changes in the code by opening IDE and compiling it to check new settings, if they work?

Any help will be highly appreciated in this regard. Thank you!

Best Regards,
Haider

**Comment by sytelus** [comment]
See this discussion: https://github.com/Microsoft/AirSim/issues/974

And this PR: https://github.com/Microsoft/AirSim/pull/979

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
