### ISSUE TITLE
Does AirSim work with controller of DJI Mavic Pro?

### ISSUE THREAD

**Issue by Li-Yanzhi** [Microsoft/AirSim#105]
Or how can we make this happen? 

![dji-mavic-pro-11](https://cloud.githubusercontent.com/assets/6248137/23866153/eb11ca54-0852-11e7-808a-58cfe20fa271.jpg)

**Comment by sytelus** [comment]
No it can't. DJI only has APIs available for their big professional drones such as Matrice 100. Mavik/Phantom etc are not supported via hardware or software in loop.
