### ISSUE TITLE
[Question] Generation of custom scenarios for training/testing

### ISSUE THREAD

**Issue by saashanair** [Microsoft/AirSim#1050]
Hello,

The simulator looks really interesting, but I was wondering if it is possible to create custom scenes for training/testing using an xml file that contains information about lanes/traffic components? Or the only possibility is to use the scenario packs provided by Epic Games?

Thank you in advance.

**Comment by sytelus** [comment]
You can definitely create your own environments. You will need folks who are experienced in creating scenes in Unreal, however.

**Comment by saashanair** [comment]
Thank you for the prompt response!
