### ISSUE TITLE
What is the depth metric?

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/AirSim#1054]
I save a pfm file with ImageRequest, the ImageType is DepthPerspective and pixels_as_float is set to true. But I have no idea about the depth metric, does the value in pfm file represents meter or centimeter, or other metric ?

**Comment by sytelus** [comment]
When you get image as float, the units are in meters.

Related code: https://github.com/Microsoft/AirSim/blob/c122d2efc746857c4cc1c503584a0981a6b14cf7/Unreal/Environments/Blocks/Plugins/AirSim/Source/RenderRequest.cpp#L44

**Comment by kylelindgren** [comment]
What is the updated depth metric? It seems DepthPlanner returns depth images on a scale of 0 to 1.
