### ISSUE TITLE
Please add National University of Ireland, Galway (NUIG) to list of users

### ISSUE THREAD

**Issue by DavidLSmyth** [Microsoft/AirSim#1058]
Would it be possible to add National University of Ireland, Galway (NUIG) to the list of users please? Our data mining & machine learning group are working on an EU Horizon 2020 project called ROCSAFE (Remotely Operated CBRNe Scene Assessment & Forensic Examination) and we have been using AirSim to simulate RAVs (and also hoping to utilise the ground vehicles) in order to test our AI systems.

 We recently had a demo that uses AirSim accepted to the [IJCAI demo track](https://www.ijcai-18.org/cfd/) and another paper submitted to the [IEEE GEM conference](http://sites.ieee.org/ieeegem/) which outlines the use of Unreal Engine and AirSim in our project. I can provide more info if necessary. Thanks for all the great work on this repo!

Links: 
[ROCSAFE](http://www.rocsafe.eu/)
[Alternative ROCSAFE](http://www.nuigalway.ie/remoteforensics/)
[NUIG](http://www.nuigalway.ie/index-internal.html)

**Comment by sytelus** [comment]
Very nice and thank you! I've updated our Who is Using list.
