### ISSUE TITLE
how to access depthVis of custom pitch angle for a car ?

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/AirSim#1060]
Hi, I find that `Gimble` is only effective when `ImageType` is -1, but I want to capture in `ImageType` 3 (depthVis) with different `pitch`, `yaw` angles.
I wonder how can I do this.

**Comment by sytelus** [comment]
It should not be. Gimbal sets the camera position and all image type comes from that position.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
