### ISSUE TITLE
An interesting thing in NH environment.

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/AirSim#1062]
I downloaded the latest release assets AirSimNH and CityEnviron, I tried to capture `scene`, `depthPerspective`, `depthVis`, and `segmentation` in both environment. I used the same settings:
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "SimMode": "Car",
  "Recording": {
    "RecordOnMove": false,
    "Cameras": [
        { "CameraID": 0, 
          "ImageType": 0, 
          "PixelsAsFloat": false, 
          "Compress": true 
        },
        { "CameraID": 0, 
          "ImageType": 2, 
          "PixelsAsFloat": true, 
          "Compress": true 
        },
        { "CameraID": 0, 
          "ImageType": 3, 
          "PixelsAsFloat": false, 
          "Compress": true 
        },
        { "CameraID": 0, 
          "ImageType": 5, 
          "PixelsAsFloat": false, 
          "Compress": true 
        }
    ]
  },
  "CaptureSettings": [
    {
      "ImageType": 0,
      "FOV_Degrees": 120,
      "Width": 640,
      "Height": 480
    },
    {
      "ImageType": 2,
      "FOV_Degrees": 120,
      "Width": 640,
      "Height": 480
    },
    {
      "ImageType": 3,
      "FOV_Degrees": 120,
      "Width": 640,
      "Height": 480
    },
    {
      "ImageType": 5,
      "FOV_Degrees": 120,
      "Width": 640,
      "Height": 480
    }
  ]
}
```
Everything was Ok in City environment, while in NH environment, I found that the `scene` did not match the `segmentation`, the `depthVis` was also not correct. Can someone give me an explanation, or is it a bug ?
![image](https://user-images.githubusercontent.com/7520466/39660873-5218a004-507a-11e8-9f27-7411f3d9fb9c.png)
![image](https://user-images.githubusercontent.com/7520466/39660876-5d8f66ca-507a-11e8-8fb1-559a798e07ed.png)
![image](https://user-images.githubusercontent.com/7520466/39660878-6464fa1e-507a-11e8-9dbb-5e9e82636981.png)

**Comment by showaykerker** [comment]
Same problem here.
But in my opinion, it's not actually binary image, do np.unique then you will get something like this [  0   1   2   3   4   5   6 251 252 253 254 255]. 
It's not the correct value though, I think it's because of the transition between byte data returns by simGetImage and imdecode, but i've got no idea how to decode it into float32 or float64. 
I've already set PixelsAsFloat to true.

**Comment by sytelus** [comment]
See here for how to get floats: https://github.com/Microsoft/AirSim/blob/master/PythonClient/hello_car.py#L57

Saving and visualizing depth image as float is hard because RGB only allows up to 255.

**Comment by wujiyoung** [comment]
@sytelus Thank you for your response.
Can you give further explaination that why the `segmentation` image didn't match the `scene` image?
