### ISSUE TITLE
Radial pattern in DepthVis Images

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#1064]
Hey all! 

I have been collecting the `DepthPlanner` images at 720p resolution. Although the rendering of the images takes time, the issue I am facing is that a radial pattern is observed when I convert the pfm images into the heat map as shown here. I would like to know if this is an error due to the heatmap conversion or the `DepthPlanner` images themselves are incorrect? 

![x_000000_y_000035_z_000025_tilt_000000_pan_000000_time_002000](https://user-images.githubusercontent.com/12863862/39663196-712afa98-508c-11e8-83d6-583e46e2d916.png)

**Comment by sytelus** [comment]
It's hard to tell without debugging through your code... You might want to look at float values in depth images and see if that is the problem. Discretization somewhere in code can also be issue.

**Comment by Mayankm96** [comment]
I updated the AirSim plugin to the most recent one with VS2017 and Unreal 4.18. The issue seems to have been fixed. I'll reopen the issue if it resurfaces again. Thank you! :)

![depth heatmap_screenshot_10 05 2018](https://user-images.githubusercontent.com/12863862/39867841-8171fa50-5474-11e8-94d0-fd3ca27bf4be.png)

**Comment by Mayankm96** [comment]
I collected the depthVis images this time and observed that a radial pattern exists in them now. 

Heatmap from the depthVis images:
![heatmap_not_ok](https://user-images.githubusercontent.com/12863862/41550957-f57b08a0-7347-11e8-9d24-7fa9c701e900.png)

Heatmap from depthPlannar images:
![heatmap_ok](https://user-images.githubusercontent.com/12863862/41550933-e7b33f80-7347-11e8-89e0-3cd813ef85bd.png)

Any idea with what's the issue?

**Comment by sytelus** [comment]
DepthViz used to do cycles at every 100m distance and these rings very purposeful for visualization.

If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
