### ISSUE TITLE
Block Environment build error

### ISSUE THREAD

**Issue by EthanZhangYi** [microsoft/AirSim#1069]
I pull the latest master branch and build it. Then I follow [this instruction](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_blocks.md) to run the build-in block environment. And error occurs.
![image](https://user-images.githubusercontent.com/13479831/39693965-4b1a0406-5218-11e8-8737-be0a168b5d93.png)
Window 10
Visual studio 2017 Community Version
Unreal 4.18.3

Also, it seems that the block environment is not updated for VS2017
![image](https://user-images.githubusercontent.com/13479831/39694067-9131e88c-5218-11e8-9f7c-eb896ad1ab02.png)

**Comment by sytelus** [comment]
There was one minor error in docs which I just fixed: Please use VS 2017 (not VS2015). Then select Blocks as Startup Project by right clicking in VS.

**Comment by vinbo** [comment]
so even the name of "Block" is followed by(visual studio 2015), it should affect nothing, right?

**Comment by msb336** [comment]
This should be resolved in the current master. please re-open if you are still having issues.
