### ISSUE TITLE
Camera pixel size in Unreal Units 

### ISSUE THREAD

**Issue by nikolaid77** [Microsoft/AirSim#1071]
What is the camera pixel size in Unreal Units?

**Comment by sytelus** [comment]
Can't understand your question... camera pixel in unreal has no "size" and its not related to UU.

**Comment by nikolaid77** [comment]
@sytelus : I am novice in airsim/unreal and I respect your opinion. However, after posting the question  I have searched a bit on the topic. In the [cinecameraactor](https://docs.unrealengine.com/en-us/Engine/Sequencer/HowTo/CineCameraActors) more specifically in the filmback settings, one can select manually the sensor size (width / height) in mm. This, in combination with the sensor resolution  (width / height in pixels) implies that there is a pixel size, in mm. Let me know if I am wrong on the above. If the above are correct regarding the cine camera, then the question can be rephrased as: how can I know or calculate the pixel size in the "simple" camera.

**Comment by Zartris** [comment]
Did we ever get an answer to this?

**Comment by vyunolbek** [comment]
> @sytelus : I am novice in airsim/unreal and I respect your opinion. However, after posting the question I have searched a bit on the topic. In the [cinecameraactor](https://docs.unrealengine.com/en-us/Engine/Sequencer/HowTo/CineCameraActors) more specifically in the filmback settings, one can select manually the sensor size (width / height) in mm. This, in combination with the sensor resolution (width / height in pixels) implies that there is a pixel size, in mm. Let me know if I am wrong on the above. If the above are correct regarding the cine camera, then the question can be rephrased as: how can I know or calculate the pixel size in the "simple" camera.

Have you received an answer to your question?
