### ISSUE TITLE
mismatch between the gps localization and kinematics_true.position

### ISSUE THREAD

**Issue by husha1993** [microsoft/AirSim#1072]
I tried to transform the local NED to the geodestic location, and I use the Matlab function:
https://www.mathworks.com/help/map/ref/ned2geodetic.html
[x,y,z]=geodetic2ned(47.641889518189664,-122.1397859350692,153.76217651367188,47.641468,-122.140165,122, referenceSphere('Earth'));
x = 46.8719
y = 28.3998
z = -31.7619
I thought the (x,y,z) would equal (x_val, y_val, z_val), do I misunderstand the 'gps_location' and 'position'?

the above the drone state from the getMultirotorState():
state = client.getMultirotorState() >>> print(state) { 'collision': { 'has_collided': False, 'impact_point': { 'x_val': -0.458686500787735, 'y_val': 0.46160826086997986, 'z_val': 0.8734759092330933}, 'normal': { 'x_val': 1.2552852979297313e-08, 'y_val': -1.551507899932858e-08, 'z_val': -1.0}, 'object_id': 148, 'object_name': 'Ground_2', 'penetration_depth': 0.0, 'position': { 'x_val': -0.1347363293170929, 'y_val': 0.1346159279346466, 'z_val': 0.640691876411438}, 'time_stamp': 1524508567475629824}, 'gps_location': { 'altitude': 153.76217651367188, 'latitude': 47.641889518189664, 'longitude': -122.1397859350692}, 'kinematics_estimated': { 'angular_acceleration': { 'x_val': -1.3302257684699725e-05, 'y_val': -3.7064401112729684e-06, 'z_val': 7.244060580815165e-19}, 'angular_velocity': { 'x_val': -3.008369731105631e-08, 'y_val': -4.785919216487855e-09, 'z_val': 1.1462851290389153e-07}, 'linear_acceleration': { 'x_val': -5.6665054870563836e-08, 'y_val': 7.27874223116487e-08, 'z_val': 0.0}, 'linear_velocity': { 'x_val': -0.00013495524763129652, 'y_val': -0.0003126846277154982, 'z_val': 0.0002836277417372912}, 'orientation': { 'w_val': 0.9999710917472839, 'x_val': 3.6738694308979802e-09, 'y_val': 2.9185183159086137e-09, 'z_val': -0.007601920515298843}, 'position': { 'x_val': -9.97673225402832, 'y_val': 29.43096160888672, 'z_val': -29.742185592651367}}, 'kinematics_true': { 'angular_acceleration': { 'x_val': -1.3302257684699725e-05, 'y_val': -3.7064401112729684e-06, 'z_val': 7.244060580815165e-19}, 'angular_velocity': { 'x_val': -3.008369731105631e-08, 'y_val': -4.785919216487855e-09, 'z_val': 1.1462851290389153e-07}, 'linear_acceleration': { 'x_val': -5.6665054870563836e-08, 'y_val': 7.27874223116487e-08, 'z_val': 0.0}, 'linear_velocity': { 'x_val': -0.00013495524763129652, 'y_val': -0.0003126846277154982, 'z_val': 0.0002836277417372912}, 'orientation': { 'w_val': 0.9999710917472839, 'x_val': 3.6738694308979802e-09, 'y_val': 2.9185183159086137e-09, 'z_val': -0.007601920515298843}, 'position': { 'x_val': -9.97673225402832, 'y_val': 29.43096160888672, 'z_val': -29.742185592651367}}, 'timestamp': 1524509096467914752}

**Comment by sytelus** [comment]
We are currently looking in to other issues and won't get to this one for sometime. You can help us debug this. The relevant line of code is here assuming you are using simple_flight (i.e. default).

https://github.com/Microsoft/AirSim/blob/v1.1.10/AirLib/include/vehicles/multirotor/firmwares/simple_flight/SimpleFlightDroneController.hpp#L199

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
