### ISSUE TITLE
Unreal Editor hangs after hitting Play?

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1073]
Unreal Editor hangs after hitting play and I have to close the whole unreal editor in order to exit...

**Comment by sytelus** [comment]
Which OS, UE version? Are you running from source code? Car or drone mode? What settings you use? Please give as much as details as you can.

**Comment by husha1993** [comment]
Ubuntu 16.04,
source code,
drone mode,
default setting

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
