### ISSUE TITLE
Is it possible to modified vehicle dynamics with another UnrealPlugin --Carsim?

### ISSUE THREAD

**Issue by DrifterFun** [Microsoft/AirSim#1077]
Hi
I am wondering that is it possible to change the Vehicle dynamics equations and use a model from Carsim? (Another plugin in Unreal?)
https://www.unrealengine.com/marketplace/carsim-vehicle-dynamics
It seems that Carsim may have more accurate model because it has worked on car simulation for many years.
Thanks!

**Comment by sytelus** [comment]
You certainly can. However you will need to change CarPawn class. You can help us contribute this feature :).

**Comment by DrifterFun** [comment]
Dear Community,
I have finish the works talked above. I will later fork AirSim to my own  repository. And I will give usage in my own blog. The Link I will update here few days later.
Thanks!

**Comment by freeyyc** [comment]
> Dear Community,
> I have finish the works talked above. I will later fork AirSim to my own repository. And I will give usage in my own blog. The Link I will update here few days later.
> Thanks!

Can you share some detail with us ?
