### ISSUE TITLE
Build issues when creating unreal environment

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AirSim#1078]
I'm following the instructions to create the landscape mountains environment, I'm working with Visual Studio 2017

https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md

I downloaded and built air sim, it built without issue.

I copied the plugin folder to the LandscapeMountains folder and generated visual studio project files.

When I open the solution, set it to DebugGame Editor and Win64, it fails with the errors below.  Has anyone else had this issue?

![image](https://user-images.githubusercontent.com/38044495/39764103-e3a0448a-52ac-11e8-9f62-8b253ac47fe6.png)

**Comment by sytelus** [comment]
Are you using Unreal 4.18? Did you made sure to run clean.bat (get it from Blocks folder) and then generate project files?

**Comment by NextSim** [comment]
running clean.bat and then setting the game as the startup project looks like it worked.

Thanks!
