### ISSUE TITLE
Error at startup: Failed to load asset class

### ISSUE THREAD

**Issue by DzikiBorsuk** [Microsoft/AirSim#1080]
Hi, I downloaded AirSimNH and tried to run run.bat. After choosing the vehicle I got following error:
![2018-05-08](https://user-images.githubusercontent.com/29456009/39782679-303d5bbe-5313-11e8-9613-e2e4a9c37aa3.png)

And when I choose quadrorotor:
![2018-05-08 1](https://user-images.githubusercontent.com/29456009/39782727-55917fa8-5313-11e8-887f-1aae0865044a.png)

How can I fix it?

**Comment by sytelus** [comment]
Please use release v1.1.10. I just tested it and it works fine: https://github.com/Microsoft/AirSim/releases/tag/v1.1.10

**Comment by ZhanLiao** [comment]
the same problam!!!how to solve this problam,could you tell me?thanks you very much
