### ISSUE TITLE
I want to implement the distance sensor module myself.

### ISSUE THREAD

**Issue by xianshichi** [Microsoft/AirSim#1081]
I have implemented adding a sensor module in front of the vehicle to achieve obstacle ranging by using the ray tracing function in the blueprint.

But how do I get blueprint data in airsim?

Can someone help me solve this problem? Suggestions, guidance, experience, highly appreciated. Thank you!

**Comment by sytelus** [comment]
Please look at this:
https://github.com/Microsoft/AirSim/tree/master/AirLib/include/sensors/distance

https://github.com/Microsoft/AirSim/tree/master/Unreal/Plugins/AirSim/Source/UnrealSensors

**Comment by hesham-akmal** [comment]
xianshichi did you by any chance get to finish the module? Thank you.
