### ISSUE TITLE
Minimum Mass of drone?

### ISSUE THREAD

**Issue by jameswalmsley** [Microsoft/AirSim#1087]
SimpleFlightQuadX.hpp for params.mass (line 37).
It says:

    params.mass = 1.0f; //can be varied from 0.800 to 1.600

Whats is the restriction here? I'd like to simulate a drone of less than 0.5kg.
Is there some way I can fix the simulation to correctly work with lower masses?

Many thanks

James

**Comment by sytelus** [comment]
There is no theoretical restriction. I think the comment states that current PID settings might work in this range better. If you go out of the range, you will probably need to re-tune PID controller but you can try this out and see if it works.
