### ISSUE TITLE
”Inertia” problem in simple_flight mode?

### ISSUE THREAD

**Issue by lenghandou** [Microsoft/AirSim#1091]
hi，I have a new problem

in default settings，drone mode,I used joystick to move the drone，

When I return the joystick to zero, the drone will continue to move indefinitely in its original direction.

I hope the drone will stop moving when the joystick returns to zero

Where should I change these codes?

Thank you very much for your answer！！！

May I use RC control mode?

**Comment by sytelus** [comment]
Seems to work fine on my end. I think your joy stick might not be calibrated (i.e. center positions has offset).

**Comment by lenghandou** [comment]
Thanks for your answer, I will test my joy stick with my colleagues.
