### ISSUE TITLE
at-getter of PhysicsEngineBase.hpp missing return statement

### ISSUE THREAD

**Issue by cdyk** [microsoft/AirSim#1097]
[Line 44 of PhysicsEngineBase.hpp](https://github.com/Microsoft/AirSim/blob/361b538ac6cc306c889b48021eb8b381108cee99/AirLib/include/physics/PhysicsEngineBase.hpp#L44):

    const TUpdatableObjectPtr &at(uint index) const { members_.at(index);  }

should have the missing return statement added

    const TUpdatableObjectPtr &at(uint index) const { return members_.at(index);  }

**Comment by sytelus** [comment]
Good catch! If you can submit the PR, I can merge it right away.

**Comment by cdyk** [comment]
Fixed in PR #1109

**Comment by ironclownfish** [comment]
thanks!
