### ISSUE TITLE
How to debug AirSim efficiently with Visual Studio?

### ISSUE THREAD

**Issue by galgyeony** [Microsoft/AirSim#1098]
Does anyone know how to debug (e.g., using breakpoint, step into, etc.) with Visual Studio for AirSim?

AirSim is a plugin on UE4 and I don't know well how to debug with VS in this environment.

Thanks in advance.

**Comment by sytelus** [comment]
I usually just use Blocks environment and [this workflow](https://github.com/Microsoft/AirSim/blob/master/docs/dev_workflow.md). You can debug in VS just like any other applications.
