### ISSUE TITLE
New type of vehicle possible ? (Boat)

### ISSUE THREAD

**Issue by Fractaos** [microsoft/AirSim#1099]
I would like to use AirSim to simulate and train a water based drone, I've a water simulation with buoyancy and I manage to make the car float and change its model but can't make it move (because of the wheel which aren't in contact with anything). Another idea was to do the same with the flying drone, but this one can't float, it just fall off until it hit the floor. 

For a first shot I don't need something too realistic, just a props that can float and move. For now, I can't achieve it, mainly by lack of understanding of how the "drones" in AirSim are built and works I think. 

Thank's if you got a solution !

**Comment by TritonSailor** [comment]
@Fractaos which water simulation are you using?

**Comment by Fractaos** [comment]
Hello, @TritonSailor 

Sorry for the time without answering. I'm currently not on the project but I can still answer you, it was this one : [OceanProject](https://github.com/UE4-OceanProject/OceanProject)

Hope it could be usefull in the futur.
