### ISSUE TITLE
how to use it in a behavior research?

### ISSUE THREAD

**Issue by cwx-psyc** [Microsoft/AirSim#1102]
I would do some researches about driving behavior of human driver. So i hope to use AirSim as a driving simulator, because of it high resolution and reality. But i do not know how to add some stimulus into the city environment, such as some pedestrian, traffic light, and so on. Besides, is there any help about how to set the behaviors of other vehicles in the city environment, such as speed, distance, position. Should we need to re-create a new scene by ourselves? If it is true, it must a too hard work to do. If any researcher using have experiences on using it in behavior researches?

**Comment by sytelus** [comment]
I believe your question is how to generate scenarios for behaviour research. This would indeed require creating a scene that you need for your research. AirSim currently doesn't allow to create such scenarios using layperson's tools (no open source simulator does in my knowledge). To create such scenarios you will need knowledge of working with Unreal Editor. There is plenty of material on this and tons of YouTube videos. However, I would recommend hiring a graphic artist to do such work if your research funding allows. You might want to take this question to http://answers.unrealengine.com/.
