### ISSUE TITLE
Cars disappear in segmentation image?

### ISSUE THREAD

**Issue by wujiyoung** [Microsoft/AirSim#1104]
Hi, I was struggling to gather training data with rgb image, depth image and segmentation image, but there was something wrong with the segmentation image. I found in many cases that there was no car in segmentation image, while in the same place in rgb image and depth image there was a car. How did this happen ?

**Comment by sytelus** [comment]
We haven't seen this happening. Please give us reproducible scenario. You might want to create minimal Python code that demonstrate this bug.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
