### ISSUE TITLE
Is there way to get rotational speed for each wheel?

### ISSUE THREAD

**Issue by iquater** [microsoft/AirSim#1105]
Does anybody know is there way to get rotational speed for car wheels? 
Looks like there is no such function in client api.

**Comment by sytelus** [comment]
Yes, it is possible. I believe below is the relevant API that would need to be exposed through Python:

https://api.unrealengine.com/INT/BlueprintAPI/Game/Components/WheeledVehicleMovement/GetRotationAngle/index.html

Please feel free to contribute this feature!

**Comment by RVBldr** [comment]
@iquater Please confirm if we can close this item.

**Comment by RVBldr** [comment]
Internal VSTF 7431.

**Comment by Doodle1106** [comment]
Any progress? Has this feature been supported?
