### ISSUE TITLE
Drone Shell in linux

### ISSUE THREAD

**Issue by dileep-krishnan** [Microsoft/AirSim#1108]
Hi!
I am trying to use Drone shell to be used in linux environment. I am using PX4 in HITL mode.
Any guidance will be helpful.
Thanks in advance!!

**Comment by sytelus** [comment]
DroneShell is just sample application. I would recommend using Python APIs instead.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
