### ISSUE TITLE
Disable Shadows in CV-Mode

### ISSUE THREAD

**Issue by patrickschulte** [Microsoft/AirSim#1114]
I try to capture some images for a Deep Learning task. For this i create like in the cv_mode.py example `client = MultirotorClient()
client.confirmConnection()`

I also set the `"UsageScenario": "ComputerVision",` in the settings.json file. But i recognized that i get a shadow of the drone in the scenario, while running it. Is there a possibility to disable this behavior?

**Comment by Mayankm96** [comment]
I haven't tried it though but you can disable the cast shadow options in Unreal Engine to do so. 

Source: https://forums.unrealengine.com/development-discussion/rendering/96972-how-to-disable-shadows

**Comment by patrickschulte** [comment]
I managed to disable the shadows by opening the drone's .uasset-file (Plugins/Content/Blueprints/BP_FlyingPawn.uasset) in UE4, setting the drone itself to invisible and disabling the casting shadow option. 

Thanks to all!
