### ISSUE TITLE
Drone shell&Takeoff no response

### ISSUE THREAD

**Issue by tea000001** [Microsoft/AirSim#1118]
Hey guys,
When I open the Drones shell and write "takeoff" it will show
![image](https://user-images.githubusercontent.com/37363135/40639869-f3d3b7b6-6345-11e8-8cf9-294fb365af38.png)

I don't know it's because my Unreal Editor not connect to the client
It's not show some information in the upper right corner
![image](https://user-images.githubusercontent.com/37363135/40640007-9f963600-6346-11e8-9005-333b8831a48d.png)

And does this system need PX4?
Because I don't have it, I only have DJI controller and Logitech rocker,
can these be replaced?

Thank you very much~

**Comment by sytelus** [comment]
This works:

![image](https://user-images.githubusercontent.com/2096835/41805764-b5954b68-7664-11e8-9747-5b2a425c7386.png)
