### ISSUE TITLE
Document Fix - Sais to use 4.17, but git pulls 4.18 (Linux build)

### ISSUE THREAD

**Issue by CaptainJL** [Microsoft/AirSim#1133]
Hey all,

Can someone fix the document https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md.
It sais it can only support 4.17, but asks to download 4.18.
"Clone Unreal in your favorite folder and build it (this may take a while!). Note: We only support Unreal 4.17 at present. "

I tried downloading and installing 4.17 as it said, but AirSim is updated to work with 4.18 so it wouldn't work...

Thanks,

**Comment by sytelus** [comment]
Fixed.
