### ISSUE TITLE
API has not been given contorl

### ISSUE THREAD

**Issue by tea000001** [Microsoft/AirSim#1155]
Hi,
I open the AirsimNH and use Droneshell enter arm and takeoff,
but not thing happen,
like following picture,

![image](https://user-images.githubusercontent.com/37363135/41288765-1104ad6a-6e7a-11e8-8edc-26fd30789790.png)
![image](https://user-images.githubusercontent.com/37363135/41288803-2aea023e-6e7a-11e8-9a2a-90e5bd3ba1e6.png)

please help me, thank you very much QQ

**Comment by bertram1isu** [comment]
See #1179.  They recently updated the API and the latest source for AirSim was not compatible with the prebuilt windows binaries.  From that issue, it seems that they have possibly released new prebuilt binaries which might solve your issue?

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
