### ISSUE TITLE
Airsim co-simulation with third party tools (synchronization)

### ISSUE THREAD

**Issue by gmosem** [Microsoft/AirSim#1156]
All,

is it possible to sync Airsim/Unreal with a third party tool?
With sync I mean stopping the Unreal simulation and restarting as we like.

Our setup is the following: Airsim running on machine A and PX4 in SILT running on machine B. On one side we can freeze the execution of the machine B and perform debugging procedures on PX4. On the other side (machine A) we would like to freeze Airsim (all Unreal actually) and wait until PX4 starts running again.

Is there any way to implement this as Airsim is today?
Any hint on the code involved in this? I'll be happy to contribute with this feature.

Thanks!

**Comment by sytelus** [comment]
You might want to look at this: https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#pause-and-continue-apis
