### ISSUE TITLE
AdditionalCameras can't display in subwindows in other simulation environment

### ISSUE THREAD

**Issue by hyybuaa** [Microsoft/AirSim#1162]
In the simulation environment started by the AD_Cookbook_Start_AirSim. Ps1 command, the images of camera id5 and 6 added by multirotor cannot be displayed in the subwindows window.

**Comment by sytelus** [comment]
Please provide more details. Like which version are you using, settings, exact error message etc.

**Comment by sytelus** [comment]
We are unable to repro this issue with latest version.

If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
