### ISSUE TITLE
reset function unresolved external

### ISSUE THREAD

**Issue by jianghe01** [Microsoft/AirSim#1163]
when i want to use like this:
    msr::airlib::CarRpcLibClient client;
    client.reset();

there are two errors :
    "LNK 2019 unresolved external symbol "public: void __cdecl msr::airlib::CarRpcLibClient::reset(void)"..."
    "LNK1120 1 unresolved externals"

i have already set AirLib.lib and rpc.lib in my environment. hope anyone can help me. thx a lot !

**Comment by sytelus** [comment]
See the example code here:
https://github.com/Microsoft/AirSim/blob/master/HelloCar/main.cpp

Please note that APIs have changed in v1.2. So make sure to get everything latest.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
