### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by yumianhuli1** [Microsoft/AirSim#1164]
Install latest Airsim version,but...
error message is: CMake Error at rpclib_wrapper/CMakeLists.txt:13 (add_subdirectory):
  add_subdirectory given source
  "C:/Users/XXX/source/repos/AirSim/external/rpclib/rpclib-2.2.1"
  which is not an existing directory.

How to solve this?

**Comment by sytelus** [comment]
How are you "installing"? Do you have latest version? Try,

```
git clean -fdx
clean.bat
build
```

**Comment by sytelus** [comment]
We are unable to repro this issue with latest version.

If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
