### ISSUE TITLE
Error:  libUE4Editor-LandscapeMountains.so missing

### ISSUE THREAD

**Issue by ganeshrk95** [Microsoft/AirSim#1165]
I'm running Unreal Engine **4.19.2** with AirSim.

I am getting the following error when I try to run the Landscape Mountains environment that I built on Windows (followed the instructions). When I hit rebuild module, it fails and asks to build from source manually. Is this because I am not using 4.18?
**libUE4Editor-LandscapeMountains.so missing**

Found this in the log, but the file does exist in the mentioned location.
![image](https://user-images.githubusercontent.com/13117114/41442828-3237e126-7007-11e8-88e6-652c3be1679b.png)

The Blocks project provided in AirSim works as expected. 

I tried opening the environment on Windows. For some reason, the car spawns whereas the multi rotor doesn't. It just loads a blank environment. 

Thanks in advance.

**Comment by sytelus** [comment]
Are you copying Plugins folder to your UE projecr?

```
rsync -a --delete Unreal/Plugins path/to/MyUnrealProject
```

You should see `Plugins/AirLib/deps/MavLinkCom/lib/libMavLinkCom.a` in your UE project folder.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
