### ISSUE TITLE
Can i import another Quadrotors model into airsim?

### ISSUE THREAD

**Issue by maxlauhi** [Microsoft/AirSim#1166]
I have created an new Quadrotor and i want to imorting airsim to try it. What shall I do? thanks

---- (Remove above before filing the issue) -----

**Comment by sytelus** [comment]
Yes, you can. Please take a loot at this example: https://github.com/Microsoft/AirSim/pull/1139

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
