### ISSUE TITLE
How to close Quadrotor sim, without crashing Unreal

### ISSUE THREAD

**Issue by CaptainJL** [microsoft/AirSim#1167]
Hey all,
I am using Unreal on Ubuntu for Airsim.

Everytime i hit 'esc' or try to shut down the simulation in quadrotor mode, Unreal crashes.
This doesn't happen with car mode.

Anyone know how to kill the unreal airsim simulation while in quadrotor mode, without it crashing?

Thanks.

**Comment by nicovanduijn** [comment]
I am experiencing the same issue

**Comment by msb336** [comment]
If you run your simulation in `standalone` mode, even if the simulation crashes, the unreal editor will not crash.
