### ISSUE TITLE
How to enable steering wheel control in self-build environment?

### ISSUE THREAD

**Issue by BrianN92** [Microsoft/AirSim#1169]
Hi all, I just build a new UE4 environment by myself. The question is how can I use steering wheel to control the car in this self-build environment?

**Comment by sytelus** [comment]
Try adding this in settings.json (also search issues for steering wheel):

```
"Vehicles": {
    "PhysXCar": {
      "VehicleType": "PhysXCar",
      "RC": {
        "RemoteControlID": 0
      }
    }
}
```
