### ISSUE TITLE
drone not working 

### ISSUE THREAD

**Issue by asanthamax** [Microsoft/AirSim#117]
Hello,
I have followed all the steps described in [https://youtu.be/HNWdYrtw3f0](Walkthrough Demo)
but i having a issue whenever i try to run the project in unreal its giving error in screen saying **message length 28 doesn't match expected length 24** i have attached the preview of my gamescreen. I have no idea why its occur i would be grateful if someone can pointed me out what i am doing wrong here and also i didn't setup any hardware in my project does it must to have controller hardware to run the project? can't it run only through the API?
![errorunreal](https://cloud.githubusercontent.com/assets/16780812/24056251/320d8196-0b00-11e7-8284-11a0ea7954f1.png)

**Comment by clovett** [comment]
Can you check you have the latest bits, I g iced this yesterday...
