### ISSUE TITLE
simGetObjectPose(), is the pose returned by the function in the ue4 coordinate system or the airsim coordinate?

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1175]
Hi,

simGetObjectPose(), is the pose returned by simGetObjectPose() in the ue4 coordinate system or the airsim coordinate?
It seems that it is in the ue4 coordinate.
While I thought all the position returned by  airsim api should be in airsim coordinate.

**Comment by sytelus** [comment]
I've updated the doc: https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#common-apis

(see last bullet point)

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
