### ISSUE TITLE
Is it possible to obtain the camera intrinsic parameters from unreal engine rather than build by myself

### ISSUE THREAD

**Issue by husha1993** [microsoft/AirSim#1176]
Hi,

I have noticed that there are some discussions (https://github.com/Microsoft/AirSim/issues/269) about how to obtain the camera intrinsic parameters,
I'm wondering if it is possible to obtain the exact camera intrinsic parameters from unreal engine rather than estimating by myself?

**Comment by sytelus** [comment]
Cameras in UE only gives you horizontal FOV and resolution. Everything you need to compute by yourself. If you have a code in mind, I would be happy to work with you to integrate it in AirSim.

**Comment by RVBldr** [comment]
Internal VSTF 7425.
