### ISSUE TITLE
Gimbal using settings.json

### ISSUE THREAD

**Issue by CaptainJL** [Microsoft/AirSim#1180]
Hey all,

I am currently using UBuntu 16.04, with Airsim for Unreal 4.18.

How is the correct way to use the gimbal for the quadrotor using the settings.json file?
I currently have this, but when i tilt the quad (using px4 mavros), the camera also tilts.
```
"CaptureSettings": [
    {
      "ImageType": 0,
      "Width": 376,
      "Height": 240,
      "FOV_Degrees": 120,
      "AutoExposureSpeed": 100,
      "AutoExposureBias": 0,
      "AutoExposureMaxBrightness": 0.1,
      "AutoExposureMinBrightness": 0.1,
      "MotionBlurAmount": 0,
      "TargetGamma": 1.0,
      "ProjectionMode": "",
      "OrthoWidth": 5.12,
      "Gimble": {
        "Stabilization": 1,
        "Pitch": 0,
        "Roll": 0,
        "Yaw": 0
      }
    }
  ]
```
I tried using ImageType = -1, but it defaulted to original camera settings.

Thanks,
CaptainJL

**Comment by sytelus** [comment]
We recently did bunch of refactoring in settings.json (see [doc](https://github.com/Microsoft/AirSim/blob/master/docs/upgrade_settings.md)).

In the new scheme of things, you should use this scheme:

```
"CameraDefaults": {
    "Gimbal": {
      "Stabilization": 0,
      "Pitch": NaN, "Roll": NaN, "Yaw": NaN
    }
}
```

Also see: https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#available-settings-and-their-defaults
