### ISSUE TITLE
mismatch between response.camera_orientation and camera_info.pose.orientation

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1186]
>>> responses = client.simGetImages([airsim.ImageRequest("0", airsim.ImageType.DepthPerspective, True))
response= responses[0]
camera_info = client.simGetCameraInfo(0)

>>>response.camera_orientation
<Quaternionr> {   'w_val': 0.5403025150299072,
    'x_val': -0.0,
    'y_val': -0.0,
    'z_val': 0.8414708971977234}
>>> camera_info.pose.orientation
<Quaternionr> {   'w_val': 0.5403026342391968,
    'x_val': -0.0,
    'y_val': 0.0,
    'z_val': 0.8414707183837891}

**Comment by sytelus** [comment]
This doesn't look like big mismatch. I'm suspecting that two code paths have something slightly different or you camera moved a bit.
