### ISSUE TITLE
Some functionality is needed to accelerate the reinforcment learning time

### ISSUE THREAD

**Issue by vinbo** [Microsoft/AirSim#1194]
As a platform of developing AI algorithm, airsim seem a great choice. But if I want to develop my reinforcment learning algorithm, the tutorial showing here, https://github.com/Microsoft/AirSim/blob/master/docs/reinforcement_learning.md, and https://youtu.be/fv-oFPAqSZ4 , looks great, but the visuralization part is not necessary to show them all the time along the whole learning process. We all know that a million episodes learning process is really common in RL, but the visuralizaion part costs too much computation resources and time. So do we have some way to choose not to show the 3D animation, during the learning process, which could really accelerate the learning speed and save us so much time? 

Thanks.

**Comment by sytelus** [comment]
Look for NoDisplay ViewMode in [settings](https://github.com/Microsoft/AirSim/tree/master/docs/settingd.md). This allows you to turn off main rendering. Also look for pause and continue APIs which allows you to run simulation at max possible speed.

**Comment by vinbo** [comment]
Thanks for such quick reply on sunday. Squeeze the main window is far from what I want, I want to squeeze them all for a certain long time, which could really speed up my running time.

**Comment by vinbo** [comment]
oh, I'm so stupid, I can choose not to show the subwindows. So the problem solved,thanks

**Comment by LevineYang** [comment]
can you share the link for settings again, @sytelus . 404 pops up when I try to open it. Thank you!
