### ISSUE TITLE
default settings file is created with a different filename than will be looked for

### ISSUE THREAD

**Issue by todfrye** [Microsoft/AirSim#1195]
AirSimSettings.hpp
 line 344: 
std::string settings_filename = Settings::getUserDirectoryFullPath("settings_json.json");

SimHud.cpp
line 336:         readSettingsTextFromFile(FString(msr::airlib::Settings::Settings::getUserDirectoryFullPath("settings.json").c_str()), settingsText));

is this intentional? 
also, createDefaultSettingsFile creates: settings_json.setDouble("SettingsVersion", 1.0);

this is, as best i can tell, is from a clean build from a fresh clone.
please advise.
thank you

**Comment by sytelus** [comment]
Great catch! Just fixed this.
