### ISSUE TITLE
OriginGeopoint not working?

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AirSim#1199]
I am trying to change the starting / reset point of the car (using the blocks environment) but the car always spawns at the same location.

I've started going through the code and it looks like the coordinates are read in correctly in AirSimSetting, but in PawnSimApi::reset() the state_.start_location is always X: 5690, Y: -100, Z:202.

Changing those values changes the start location as expected

As a side note, there is an error in the documentation, where 'latitude' is used twice instead of having 'latitude' and 'longitude'

From Settings.md:

"OriginGeopoint": {
    "Latitude": 47.641468,
    "Latitude": -122.140165,
    "Altitude": 122
  },

**Comment by sytelus** [comment]
The pawn is spawned at location from settings.json ([code here](https://github.com/Microsoft/AirSim/blob/af4158390d27d24314f0e76d416f984769591004/Unreal/Environments/Blocks/Plugins/AirSim/Source/Vehicles/Multirotor/SimModeWorldMultiRotor.cpp#L94)). This location is then recorded in start_location and is never changed again. So after reset, pawn will be set to same location as specified in settings.json Vehicles element. Please note that settings.json is changed in release 1.2 and vehicle spawn location is now in "Vehicles" element's X, Y, Z elements. Is no values specified here (i.e. default) then pawn is spawned at origin (i.e. Player Start location in the environment).

**Comment by NextSim** [comment]
Thank you!
