### ISSUE TITLE
Can not Rebuild UE4Editor-AirSim.dell in Version 4.15

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/AirSim#120]
Hello All:
After i am trying use 4.15 Version to start the project.
the Project can not open ..
The issue as follows:

 
![1](https://cloud.githubusercontent.com/assets/26343300/24081565/55343f50-0d0a-11e7-9155-0865308207d7.PNG)

![2](https://cloud.githubusercontent.com/assets/26343300/24081570/85ebd252-0d0a-11e7-8d18-fe96f06d6086.PNG)

How to Rebuild it sucess? or should i come back to 4.14 version?

**Comment by Focke-Wulf** [comment]
Can someone help me to solve this problem? 
I really confuse why this happened?

**Comment by lovettchris** [comment]
To upgrade to 4.15, you might want to first right click your *.uproject file and select this option:
![image](https://cloud.githubusercontent.com/assets/18707114/24116471/26b33064-0d64-11e7-9061-f3db1b4f4bab.png)

This will allow you to switch the project to 4.15.  But I see you are using Landscape Mountains, and unfortunately, this one does not upgrade, you have to switch your default unreal version to 4.15 in the Epic Games Launcher, under the Library tab select this:
![image](https://cloud.githubusercontent.com/assets/18707114/24116524/543ea9fa-0d64-11e7-83e1-259e3b86773b.png)

Then download the landscape mountains again and re-integrate the AirSim plugin again. Then it should be good.

**Comment by Focke-Wulf** [comment]
Thanks for the help! I am now fix this problem!

**Comment by lovettchris** [comment]
Great!
