### ISSUE TITLE
Mesh segmentation for the second Car/Drone for Multi_agent

### ISSUE THREAD

**Issue by AloshkaD** [Microsoft/AirSim#1203]
I need the segmentation for the second car/multirotor. According to the image_api the mesh ID from the World Outliner in Unreal environment is needed . I tried to get the ID but the drones/cars are only added after unreal project is run and thir meshes aren't available in the environment. How can I get the segmentation for the second multirotor/car? ANy help is appreciated  @sytelus and y'all

**Comment by sytelus** [comment]
You can try simSetObjectSegmentationID with name of car as its parameter.

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
