### ISSUE TITLE
No UE4Editor in Engine/Binaries/Linux/ 

### ISSUE THREAD

**Issue by mymultiverse** [Microsoft/AirSim#1204]
I am trying to start editor but there no file name UE4Editor in Engine/Binaries/Linux/

**Comment by sytelus** [comment]
Make sure you have compiled UE. You should take this question to UE forums.

**Comment by mymultiverse** [comment]
I think it was not properly built. I rebuild it. Following once again[ these](https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md) steps.
