### ISSUE TITLE
ImportError: No module named 'msgpackrpc'

### ISSUE THREAD

**Issue by vinbo** [Microsoft/AirSim#1208]
Hi, my hello_drone.cpp works well. But not the hello_drone.py, the error info is given below:

Traceback (most recent call last):
  File "hello_car.py", line 1, in <module>
    from AirSimClient import *
  File "/home/n_li/git/AirSim_v1.1.10/AirSim/PythonClient/AirSimClient.py", line 2, in <module>
    import msgpackrpc #install as admin: pip install msgpack-rpc-python
ImportError: No module named 'msgpackrpc'

since I'm under ubuntu 16.04 lts, so i have both python 2.7 and 3.5 in the system preinstalled, and the previous default python is 2.7, i changed the default python using modifying .bashrc, alias method, and I indeed follow the steps here, https://github.com/Microsoft/AirSim/blob/v1.1.10/docs/python.md , and I'm using UE4.17 and airsim v1.1.10. 
actually, i did "find / -name smgpackrpc" the module, and found this
/home/n_li/.local/lib/python2.7/site-packages/msgpackrpc
/usr/local/lib/python2.7/dist-packages/msgpackrpc
but since i'm using python3.5 as suggested by official web of airsim, i really feel unsafe to add directory to use one of this. 
What should I do, please? Thanks.

**Comment by sytelus** [comment]
Are you using Anaconda? If not, you probably want to :). That might make switching between 2.7 and 3.5 easy. And then you can just install missing packages using pip.

**Comment by vinbo** [comment]
thanks, it worked. 
it's just, using such a huge tool just to convert the version, kind of waste...

**Comment by EricJin101** [comment]
I am now using Anaconda, but I still find the same error.
ImportError: No module named msgpackrpc
What can I do to solve this problem?
Thanks!

**Comment by sytelus** [comment]
Please see this: https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#python-quickstart
