### ISSUE TITLE
Help:the Blocks project build error

### ISSUE THREAD

**Issue by nudtgjx** [microsoft/AirSim#1209]
I pull the latest master branch and navigate to folder AirSim\Unreal\Environments\Blocks and run update_from_git.bat.  Then open Blocks.sln in Visual Studio 2017 and build configuration is set to DebugGame_Editor and Win64. Build this project and the errors as follow:

![error](https://user-images.githubusercontent.com/22051785/42038076-9c815fec-7b1c-11e8-9c79-e1cf1bc3979d.PNG)
Window 10
Visual studio 2017 Community Version
Unreal 4.18.3

**Comment by NextSim** [comment]
Did you build airsim first?

You will also need to select "Blocks" in the solution explorer of the blocks environment and set it as the startup project.

**Comment by nudtgjx** [comment]
According to your suggestiong, I build the project of Airsim. Then there is the new error as shown as the figure.
![erro2](https://user-images.githubusercontent.com/22051785/42074666-d7644a7e-7b9f-11e8-9f99-1355c56abdec.PNG)
And I igore it and continue to run the clean.bat in the Blocks environment and rebuild the blocks project as the same as before. But the previous errors still exists.

**Comment by NextSim** [comment]
Did you build through visual studio, or the VS command prompt?

Follow the instructions here:
https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md

**Comment by nudtgjx** [comment]
Yes, I just did it according to https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md. I built projects successfully except the UnrealPluginFiles project. And I build the blocks environment and the errors still occured. Thanks a lot for your help.

**Comment by sytelus** [comment]
Please copy and paste text from Output window. It's hard to see things in screenshots.

**Comment by nudtgjx** [comment]
The build enviroment as follow:
Window 10
Visual studio 2015 Community Version
Unreal 4.19
Airsim 1.1.1

**Comment by sytelus** [comment]
One possibility is unicode characters in path is throwing off some code.
