### ISSUE TITLE
Created a new ImageType, for now a duplicate of DepthPerspective material. Why is the result massively brigther?

### ISSUE THREAD

**Issue by KubaFYI** [Microsoft/AirSim#1210]
I need to create a new ImageType based on the already existing DepthPerspective. For now I literally just copied it's functionality. That included:

1. Duplicating the DepthPerspectiveCaptureComponent (in BP_PIPCamera), the DepthPerspectiveMaterial, and DepthPerspectiveMaterialFunc (all changed to a different name, of course).
2. Changed the code appropriately to be able to handle additional ImageType.

I can get the new ImageType displayed in a sub-window next to a normal depth view but for some reason the result much much brighter than the original, even though all the assets are exact duplicates of each other. At first this was hard to notice because the new ImageType simply presented me with a plain white window, but I realised that the depth information is there but much larger after I turned down the 'convert to meters' multiplication in Material Function a couple orders of magnitude.

Any idea on what's happening there?

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
