### ISSUE TITLE
AirSim projection on Cylindrical screen (Linux)

### ISSUE THREAD

**Issue by haider04** [microsoft/AirSim#1212]
Hi All,

I am projecting AirSim on a cylindrical screen through 3 BenQ projectors connected to Nvidia GPU (GeForce GTX 980) in a Linux PC. 

The problem is, the projectors are overlapped and i need to have it projected on full cylindrical screen as one seamless image. For this, i am looking for some warping and blending Linux compatible software which could warp and blend the images together. But unfortunately, i was unable to find some free Linux compatible software. 

Can anyone suggest some good warping and blending software for Linux? Thanks! 

Haider

**Comment by msb336** [comment]
It may be difficult to implement with airsim, but unreal has been hyping a new feature in their 4.21+ versions called [ndisplay](https://docs.unrealengine.com/en-US/Engine/Rendering/nDisplay/index.html) that allows you to render `n` view to `n` screens. If you can get it working with the airsim plugin, it may solve your problem.
