### ISSUE TITLE
Stop rendering everything but front camera

### ISSUE THREAD

**Issue by CaptainJL** [Microsoft/AirSim#1214]
Hey all,

I am wondering if there is a way to stop rendering everything but the front view camera of the quadrotor?

I am trying to get maximum frame rate out of airsim and all i need is the main camera.
The Unreal view window renders at 60Hz easy - i set it Unreal to max 60Hz.
But even with "NoDisplay" set (main Unreal window is off), i cant get more than 30Hz (I need 60Hz) rendering via the API.

Anyone know an answer?
I am happy to stop the rendering in the code and rebuild Airsim.

Thanks,
CaptainJL

**Comment by sytelus** [comment]
Yes, take a look at NoDisplay [view mode setting](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#viewmode).
