### ISSUE TITLE
4.15 cracked

### ISSUE THREAD

**Issue by zf223669** [Microsoft/AirSim#122]
Hi , I have updated the AirSim to Unreal 4.15. I used a new project and downloaded the newest version. When i configured all and runned the Unreal with Airsim gamemode, however, it cracked suddenly. it showed that could not find the usb com. But using the 4.14, it worked find.

**Comment by sytelus** [comment]
What you mean by "cracked"? Did you see the crash? Or error message? There is no code change for USB related stuff so it shouldn't be 4.15 specific.

**Comment by lovettchris** [comment]
please re-open when you get a chance to provide more details, thanks.
