### ISSUE TITLE
how to run airsim in headless mode 

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1224]
https://github.com/Microsoft/AutonomousDrivingCookbook/issues/34

Are there anyway I can just run my model with AirSim on a command line in Linux or windows terminal except use the binaries version mentioned in the link above?

**Comment by SweetShot** [comment]
Not sure about that but have a look ar NoDisplay setting

**Comment by madratman** [comment]
set this environment variables:
```
export SDL_VIDEODRIVER_VALUE=offscreen
export SDL_HINT_CUDA_DEVICE=0
```
If you plan to use docker, we have an headless option there as well. please see this page https://github.com/Microsoft/AirSim/blob/master/docs/docker_ubuntu.md

**Comment by mchowdhury-tft** [comment]
where do you set this "export SDL_VIDEODRIVER_VALUE=offscreen
export SDL_HINT_CUDA_DEVICE=0" variable for the headless mode ? 
Please let me know....

**Comment by ivannson** [comment]
@mchowdhury-tft just paste each command in terminal and run it

**Comment by Neabfi** [comment]
I’ve followed those steps but it is stuck on:
`[2020.01.08-01.13.53:613][  3]LogRenderer: Reallocating scene render targets to support 128x128 Format 10 NumSamples 1 (Frame:0).`
Any ideas?

**Comment by Neabfi** [comment]
@mchowdhury-tft  Did you manage to make it work?

For me it just remains frozen forever after the line:
`LogRenderer: Reallocating scene render targets to support 128x128 Format 10 NumSamples 1 (Frame:0).`

**Comment by jeffreyng99** [comment]
Hello @madratman and @Neabfi I am running the docker container headless, however I am running into the same problem as you said. Whenever I run AirSim not in headless mode, I have to click the play button to start the simulator and rpc server. How would start the simulator in headless mode?

**Comment by thomasTUK** [comment]
Also wondering the same. How to do it?
