### ISSUE TITLE
switch between levels or wrap multiple environments in a batch

### ISSUE THREAD

**Issue by husha1993** [microsoft/AirSim#1229]
Hi,

It's there any methods to switch between levels when in playing mode?
Or wrap multiple environments in a batch with one drone in each environment?

**Comment by msb336** [comment]
while there is no API to switch levels, you can do so through the console. Press the `~` key to open the console while playing a game, and enter the following command:
```
open {your level name}
```
Unreal engine will attempt to find a level in your project and plugin directories with a matching name and will open it. This means that any level you would like to switch to must be in the same project you are currently running.
