### ISSUE TITLE
VectorMath vs. VectorMathT

### ISSUE THREAD

**Issue by katetolstaya** [Microsoft/AirSim#1230]
I believe there is an issue in VectorMath.hpp , lines 503-515 should be

    static QuaternionT lookAt(Vector3T sourcePoint, Vector3T destPoint)
    {
        Vector3T toVector = (destPoint - sourcePoint);

        RealT dot = VectorMathT::front().dot(toVector);
        dot = Utils::clip<RealT>(dot, -1, 1);
        RealT ang = std::acosf(dot);

        Vector3T axis = VectorMathT::front().cross(toVector);
        if (axis == Vector3T::Zero())
            axis = VectorMathT::up();
        else
            axis = axis.normalized();

        return VectorMathT::toQuaternion(axis, ang);
    }

Due to the following error:

In file included from /home/user/AirSim/AirLib/include/common/Common.hpp:16:
/home/user/AirSim/AirLib/include/common/VectorMath.hpp:503:21: error: use of
      undeclared identifier 'VectorMath'; did you mean 'VectorMathT'?
        RealT dot = VectorMath::front().dot(toVector);
                    ^~~~~~~~~~
                    VectorMathT
/home/user/AirSim/AirLib/include/common/VectorMath.hpp:18:7: note: 
      'VectorMathT' declared here
class VectorMathT {
      ^

**Comment by linux-devil** [comment]
I am also facing same error while building this

**Comment by sytelus** [comment]
Fixed.
