### ISSUE TITLE
Where can I buy CityEnviron?

### ISSUE THREAD

**Issue by Aaron20127** [microsoft/AirSim#1231]
hello, I want to buy the CityEnviron which at [https://github.com/Microsoft/AirSim/releases](url). But I can't find the purchasing address. Could you give me a purchasing link? Thank you!

**Comment by vinbo** [comment]
How about the urban city in the marketplace?

**Comment by gusnitaa** [comment]
Here -> http://www.polypixel3d.com/downtown-3d-city-environment-models/
The best environments for Unreal are created by Polypixel

**Comment by vinbo** [comment]
great, but a littel expensive...

**Comment by Joyymoonh** [comment]
sorry but I want to check if the link http://www.polypixel3d.com/downtown-3d-city-environment-models/ 
was invalid? I can not connect to it. If so, what's the current version?
