### ISSUE TITLE
In v1.2, when model was set to hexacopter, simulation crashed on start

### ISSUE THREAD

**Issue by KeyneZzz** [microsoft/AirSim#1232]
i start ue4 and my project with vs, when click PLAY in ue4, it says something is wrong with UE4Editor-AirSim-Win64-DebugGame.dll and break.

i cannot find any obvious difference in Px4MultiRotorParams.hpp,  guess something maybe wrong with initializeRotorHexX()

**Comment by adamkeynes** [comment]
![image](https://user-images.githubusercontent.com/6895745/42405733-a70abb2c-81cd-11e8-8359-c549dc73673d.png)
this is exactly what happened

**Comment by adamkeynes** [comment]
![image](https://user-images.githubusercontent.com/6895745/42405757-235e3a46-81ce-11e8-8386-b104a29c4dff.png)

**Comment by KeyneZzz** [comment]
@sytelus can you pls check if there is any problem with hexa? and by the way check #1234  pls, thx

**Comment by linarism** [comment]
@KeyneZzz I also ran into the same issue. The iterator tries to update `rotor_speed` for all propellers, but `rotating_movements_` is only allocated for a hardcoded 4 propellers defined in `FlyingPawn.h`. Increasing the `rotor_count` value in that file will solve your problem.

**Comment by KeyneZzz** [comment]
@linarism thx a lot

**Comment by lovettchris** [comment]
Here's a hexacopter that works: https://github.com/Microsoft/AirSim/pull/1890
