### ISSUE TITLE
drone unreal pos changes, but the hil gps location not changing

### ISSUE THREAD

**Issue by KeyneZzz** [microsoft/AirSim#1234]
![gps](https://user-images.githubusercontent.com/6895745/42407024-87ea0270-81e6-11e8-9d32-c395fd22336b.gif)

tried a larger range, the gps location never change

**Comment by msb336** [comment]
This is most likely due to rounding. When moving a few meters at a time, GPS coordinates do not change enough to be visible in the first three decimal places. Try getting GPS through the api as your drone moves and comparing the full float values.
