### ISSUE TITLE
Compile Error -- Unable to find plugin 'AirSim' (referenced via Blocks.uproject). 

### ISSUE THREAD

**Issue by BrianN92** [Microsoft/AirSim#1235]
Hi all! I just downloaded the latest version AirSim1.2. I met a compile error when I tried to build it on Win10 OS. I did exactly as [the instruction](https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md) told. When I try to set up the built-in blocks environment, the compile error showed up.
![image](https://user-images.githubusercontent.com/21299740/42414299-48e23b14-8200-11e8-82b7-9bcc0f4ce568.png)

Does anyone know how to fix it?

**Comment by BrianN92** [comment]
@sytelus I have tried it once again, the error was different from last time. 
![image](https://user-images.githubusercontent.com/21299740/42973023-90ef1d22-8b7f-11e8-8bb8-ff64466a622e.png)

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
