### ISSUE TITLE
Plugin failed

### ISSUE THREAD

**Issue by mymultiverse** [Microsoft/AirSim#1236]
I run following command as mentioned [here](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_blocks.md) for Linux.
`./UE4Editor -opengl3
` 
While running editor I am getting a plugin error 'LinuxProfileSelector' failed to load because module 'LinuxProfileSelector' could not be found.

**Comment by sytelus** [comment]
This seems like UE specific issue. You might have better luck filing this issue at https://answers.unrealengine.com.
