### ISSUE TITLE
settings file deleted at startup

### ISSUE THREAD

**Issue by rhalaly** [Microsoft/AirSim#1239]
I can see that the settings.json file is deleted when the simulator starts. 
No matter what I write there, it ignores it and overwrites my file with the default file template:

> {
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0
}

**Comment by nathantsoi** [comment]
same here, any suggestions?

**Comment by allen9273** [comment]
Because your folder path including Asian characters.

**Comment by Beijingsheng** [comment]
I changed the folder path from C:\Users\日升\Documents\AirSim    to   C:\Users\risheng\Documents\AirSim, still settings_json.json will delete what I added.

**Comment by allen9273** [comment]
参考 #1066，it works for me

**Comment by Beijingsheng** [comment]
I just found that this problem only occurs to settings.json created by CityEnvironment, I can change settings.json created by AirsimNH and it won't be rewritten. Could anyone help with this?

**Comment by Beijingsheng** [comment]
Problem solved.
