### ISSUE TITLE
Can't   fly

### ISSUE THREAD

**Issue by jjy201314** [Microsoft/AirSim#124]
it  shows the errors:
![Uploading QQ截图20170321200819.png…]()

the  settings.json  is:
{
  "Pixhawk": {
    "LocalHostIp": "127.0.0.1",
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "COM3",
    "SimCompID": 42,
    "SimSysID": 142,
    "SitlIp": "127.0.0.1",
    "SitlPort": 14560,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": true,
    "VehicleCompID": 1,
    "VehicleSysID": 135
  }
}
how   can I do?

**Comment by lovettchris** [comment]
For some reason I cannot see the screen shot you tried to upload.  All I can see is:

![image](https://cloud.githubusercontent.com/assets/18707114/24221625/4bb9e9da-0f0c-11e7-8813-abe405ea3fb9.png)

Perhaps GitHub or someone is blocking it.  Can you try and share the screen shot using some other place?

**Comment by jjy201314** [comment]
thank you very much,lovettchris.  Maybe   something   wrong   happened,  I  will  try  other  ways  to  show  you   my  errors  .
