### ISSUE TITLE
PX4 SITL issues

### ISSUE THREAD

**Issue by chmi0611** [Microsoft/AirSim#1240]
Hi, I built Airsim in Windows 10 and tried to test SITL by PX4 without Pixhawk hardware device.

I can control (Arm, Disarm, Takeoff, Goto, etc.) the drone in Airsim by Qgroundcontrol but not by Droneshell which is located at Airsim\Droneshell\build\x64\Debug.

There are some errors in Droneshell when I gave some commands such as arm, disarm, pos.

Here's an example. I used 'arm' command and confirmed that it is connected.

RPC Error: rpclib: function 'armDisarm' (called with 2 arg(s)) threw an exception. The exception contained this information: Vehicle API for '' is not available. This could either because this is simulation-only API or this vehicle does not exist.

Also, in the BashonWindow, I ran PX4 firmware and connected with Airsim.

When I used 'go to' in Qgroundcontrol, It moved well but GPS was initialized after few seconds.

WARN  [ecl/EKF] EKF GPS fusion timeout - reset to GPS

Due to this error, the drone became unstable for a while and cannot go to exact position that I want.

Finally, I attached my setting.json below.

{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor",
    "Vehicles": {
        "PX4": {
            "VehicleType": "PX4Multirotor",
            "UseSerial": false
        }
    }
}

Thanks.

**Comment by lovettchris** [comment]
A bunch of fixes have been made, things should work better with latest AirSim bits and PX4 v1.8.2.
