### ISSUE TITLE
How to enable multi-vehicle capabilities in a client-server mode

### ISSUE THREAD

**Issue by galgyeony** [Microsoft/AirSim#1241]
Thanks to the nice new multi-vehicle capabilities (from v1.2), it is now possible to simulate multi-drones simultaneously. But, the new multi-vehicle capabilities work on one machine (like stand-alone mode), so there may be scalability issues as the number of drones increases (e.g., a hundred). 

Does the AirSim team have a plan to expand the multi-vehicle features to a client-server mode? 
Or anyone else does?

If not, I want to expand it by myself so that they work on multiple machines simultaneously (like client-server based network games). For that purpose, I have investigated the AirSim source code for a month, but sadly with little experience working on UE4 :(. 

Can someone share some nice and helpful information on this matter (or make it together)?
Thanks in advance.

**Comment by Jianghn-dev** [comment]
hi，
Is this question solved?
