### ISSUE TITLE
How to control other cars driving behaviors in Airsim

### ISSUE THREAD

**Issue by BrianN92** [microsoft/AirSim#1244]
I have tried the latest version of City map in Airsim. I am wondering how do you guys control the behaviors of other cars besides SUV agent. Those cars seem like they are doing like "spline follow", but they also have the ability to wait for the traffic lights, which looks so cool. Could anybody tell me how to set up other vehicle agents like that? Thank you!!

**Comment by JordanWang0223** [comment]
hello, I wonder ask you a question, how do u add another cars in the same maps?

**Comment by BrianN92** [comment]
@JordanWang0223 What I did was to create a self-built environment in UE4 and then build the AirSim with it. So I could add as many agents as I need. However, the SUV is the only agent controlled by Airsim. Therefore, I am wondering how to set up other cars like what they did in the "City map".

**Comment by Beijingsheng** [comment]
I'm also curious about this. Seems like those cars are pretty smart, I wonder if I can find their controlling code and edit them for my own use.

**Comment by Misslindalian** [comment]
Hello.Has the problem been solved? I also want to do this. Thanka a lot!

**Comment by msb336** [comment]
Cars are indeed on a spline follow in the City map. The intersection logic employed, unfortunately, is custom built for the environment and is not open source, so we are unable to provide the toolbox we used to construct this feature.
