### ISSUE TITLE
build project problem

### ISSUE THREAD

**Issue by alitarfa** [microsoft/AirSim#1257]
Hi every one i have probelm when i make the build of the project 
the problem related to rpclib @
![sans titre](https://user-images.githubusercontent.com/15462596/42898544-bd4ea1c4-8ac3-11e8-809a-143783feb62e.png)

**Comment by Besjan** [comment]
Same problem here; using latest cmake v3.12.0

**Comment by alitarfa** [comment]
i have used the lastest version but the problem is when downloading the rpclib from the github some problem happen

**Comment by lipanpeng** [comment]
@alitarfa I also met this error. Can you tell me how you solved it? Thank you!

**Comment by alitarfa** [comment]
in this case i have found auth problem during the compilation phase , that is mean when you run the file it will use the internet connection to get rpclib from github and this need some authentication steps i don't know why .
what i have done was to build the cmd file by my hand and to do this first download the rpclib library you will find the link inside the the cmd file just open it and you will find the libraries and follow the instruction inside the cmd file
