### ISSUE TITLE
How to modify third person camera settings ?

### ISSUE THREAD

**Issue by Gotfeurdom** [microsoft/AirSim#1261]
How can I modify the position of the (by default) third person camera relative to the drone ?
And how can I set the rotation of that camera fixed relative to the world (ie only follow drone's position and not its roll, yaw and pitch)

**Comment by batchku** [comment]
Has anyone discovered an answer to this question?

**Comment by jonyMarino** [comment]
https://microsoft.github.io/AirSim/settings/#external-cameras
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
