### ISSUE TITLE
Image flashes when creating new levels

### ISSUE THREAD

**Issue by Domi47** [microsoft/AirSim#1267]
Hello, my main platform is Linux and after having some issues while creating new projects for airsim on Windows following the tutorial https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md (I have created some without any problem, but i had some troubles with others maybe cause of recent changes to VS2017), I found another way that allows me to create new scenarios using only linux. 

This method is to create new levels on projects that already work with airsim plugin (for example Blocks project). In these new levels I can create the new scenario from scratch or to import a level from another project. On this way new scenarios in new levels already work with airsim.
Following this method airsim seems to work properly on new levels BUT airsim camera images taken on these new levels doesn't stop flashing. So the simulation on the scene works fine, and you dont see those flashes, but images shown on airsim subwindows are flashing all the time and also the captured images (original levels, for example the block scenario, still work fine)

I would appreciate any advice about this problem. Maybe I have to change some settings for new level?

Thanks!!

**Comment by sytelus** [comment]
Does this happen to segmentation view? I remember seeing something like this in segmentation view and the cause was that there were many layers of floor and each layer had different object ID. Due to potential bug in Unreal things changes color rapidly when you moved.

**Comment by Domi47** [comment]
Thank @sytelus for answering. Sorry maybe I didn't explain it well , the images flashing are airsim Scene type (those shown on subwindows, which are images taken by drone cameras), and not segmentation type. I meant that Unreal Scene view works fine and doesn't show these flashes. So this makes me think that is not an Unreal problem, because the Unreal simulation looks fine.

About layers of floor, I think it's not the problem. These flashes also appear on empty new levels and also when drone is not moving. So for example, you can try on the Blocks project, go to File -> New Level and choose the Default one. Then on that new level and after changing the GameMode to AirsimGameMode start a simulation with some Scene type subwindows and using the drone (by the way I'm using AdditionalCameras, not the default ones). So this scenario has only one simple floor and those images on subwindows are flashing. 

These flashes don't appear only on those subwindows, but also when they are saved and visualized again (using rviz for example)

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
