### ISSUE TITLE
Problem with moveByVelocityAsync function when parameter vz>=0

### ISSUE THREAD

**Issue by symechar** [Microsoft/AirSim#1268]
Is there a problem in MoveByVelocityAsync function when parameter vz>=0? I am using it to move a Multirotor but it seems to get stuck when vz >=0. I was using MoveByVelocity from an older version of AirSim and i didn't faced that problem back then.

**Comment by showaykerker** [comment]
Hi, I am wondering if you found an answer to this already, cause I'm in the same problem with it, thanks.
