### ISSUE TITLE
 support of DJI A3 flight controller

### ISSUE THREAD

**Issue by JohnDing1995** [Microsoft/AirSim#127]
Will the AirSim support DJI A3 flight controller in the future?

**Comment by sytelus** [comment]
DJI has different model to enable HITL simulation. We are currently working with few DJI folks to see if we can integrate this with AirSim. Stay tuned!

**Comment by IeiuniumLux** [comment]
@sytelus Any update on this?  I have one of this [Lightbridge-2](https://www.dji.com/lightbridge-2) units and I can give it a try if AirSim now supports it.

**Comment by chaitanyantr** [comment]
i am too waiting for that

**Comment by demoniusrex** [comment]
I am working on a multi-rotor API implementation for DJI Onboard-SDK  that should support M100 with a few tweaks. All I have to test on is a N3 flight controller. 

You can check out the work in progress here [AirSim-Onboard](https://github.com/demoniusrex/AirSim-Onboard) [New multi-rotor API](https://github.com/demoniusrex/AirSim-Onboard/blob/master/Rosie/linux/OnboardLib/include/vehicles/multirotor/firmwares/dji/OnboardMultirotorApi.hpp)

**Comment by ilyak93** [comment]
@sytelus, was there any success with this ?
