### ISSUE TITLE
mismatch between simGetVehiclePose() and  getMultirotorState().kinematics_estimated.position

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1271]
>>> currentposition = airsim_client.simGetVehiclePose().position
>>> print(currentposition)
<Vector3r> {   'x_val': 1.63528311252594,
    'y_val': 0.020307617262005806,
    'z_val': 14.636703491210938}

>>> currentposition = airsim_client.getMultirotorState().kinematics_estimated.position
>>> print(currentposition)
<Vector3r> {   'x_val': 21.635284423828125,
    'y_val': 20.020307540893555,
    'z_val': 34.63670349121094}

**Comment by Aaron20127** [comment]
May be you should use client.getCarState() instead，this function is right.
