### ISSUE TITLE
Please help me, Build Error.

### ISSUE THREAD

**Issue by wkvkfkeh** [Microsoft/AirSim#1273]
Hi,
i have problem when i make the build of the project.(i use the build.cmd)

![20180723_105232](https://user-images.githubusercontent.com/41557634/43053224-867fe65c-8e66-11e8-8ec6-ed54914071be.png)

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
