### ISSUE TITLE
How can I read the .mavlink files from the MavLinkTest App

### ISSUE THREAD

**Issue by TastiiVegas** [microsoft/AirSim#1276]
Dear *,
I just got the MavLinkTest App running with HITL-Mode. yeeah! 
The output is a .mavlink file.. how can I read it or convert it?

Regards,
Tastii

**Comment by lovettchris** [comment]
If you are on windows, I created a simple mavlink log viewer called [LogViewer](https://github.com/Microsoft/AirSim/tree/master/LogViewer).  On other platforms there are various other tools if you search PX4 community.

**Comment by TastiiVegas** [comment]
Thank you @lovettchris ,
I have already seen the program, but not the input possibility for the files. Overall great work so far!
