### ISSUE TITLE
WARNING:tornado.general:Connect error on fd 808: WSAECONNREFUSED

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1280]
for i in range(10):
        airsim_client = airsim.MultirotorClient()
        print('success build an airsim client')
        airsim_client.confirmConnection()
        print('success connect')
        airsim_client.enableApiControl(True)
        print('success enable api')
        airsim_client.armDisarm(True)
        print('success enable arm')

Hi, I got the warning when run the above code. 
![image](https://user-images.githubusercontent.com/21278701/43164047-ea7c5634-8f44-11e8-8e8a-a0a4e6e44ccd.png)

**Comment by AloshkaD** [comment]
You have to run the sim before the code. Have you done that?

**Comment by husha1993** [comment]
Yes.

airsim_client = airsim.MultirotorClient()
print('success build an airsim client')
airsim_client.confirmConnection()
print('success connect')
airsim_client.enableApiControl(True)
print('success enable api')
airsim_client.armDisarm(True)
print('success enable arm')

do some actions here

for i in range(10):
airsim_client = airsim.MultirotorClient()
print('success build an airsim client')
airsim_client.confirmConnection()
print('success connect')
airsim_client.enableApiControl(True)
print('success enable api')
airsim_client.armDisarm(True)
print('success enable arm')

**Comment by AloshkaD** [comment]
Hmmm, this is how I initialize and it works for me

        MultirotorClient.__init__(self)
        MultirotorClient.confirmConnection(self, vehicle_name)
        self.enableApiControl(True,vehicle_name)
        self.armDisarm(True,vehicle_name)

**Comment by Beijingsheng** [comment]
When I open AirsimNH before I run hello_car, it shows WARNING:tornado.general: Connect error on fd 464: WSAECONNREFUSED. But when I open CityEnvironment before I run hello_car, there isn't such a problem. Does anyone know how to fix it?

**Comment by slyviacassell** [comment]
That means the AirSim server does not work, but i still do not know how run AirSim with the AirSimNH. Maybe there are some other ways to solve the problem.

**Comment by sytelus** [comment]
We are unable to repro this issue with latest version.

If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.

**Comment by ArthurYdalgo** [comment]
I replied to a [similar issue](https://github.com/microsoft/AirSim/issues/1949) [what could be the solution](https://github.com/microsoft/AirSim/issues/1949#issuecomment-877612274)

**Comment by tanyaapaul** [comment]
Same issue but with : 

WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
WARNING:tornado.general:Connect error on fd 7: ECONNREFUSED
