### ISSUE TITLE
How to use Computer Vision mode in CityEnviron? 

### ISSUE THREAD

**Issue by noNameForMe1994** [Microsoft/AirSim#1283]
Hey,

I am trying to set simMode to Computer Vision in CityEnviron provided in airsim releases. The settings.json I used is as follows:

> {
> "SettingsVersion": 1.2,
> "SimMode":"ComputerVision",
>   "Recording": {
>     "RecordOnMove": true,
>     "RecordInterval": 0.01,
>     "Cameras": [
>         { "CameraName": "0", "ImageType": 0, "PixelsAsFloat": false, "Compress": true }
>     ]
>   }
> }

However, when I started the CityEnviron, an error called 
Error at startup: 
Failed to load asset class - Class'/Airsim/Blueprint/BP_ComputerVisionPawn.BP_ComputerVisionPawn_C' 
occurs. 
![image](https://user-images.githubusercontent.com/19621057/43182229-2172440e-9013-11e8-8135-e462acf3eb12.png)

Is there anyway can I use Computer Vision mode in CityEnviron?

**Comment by noNameForMe1994** [comment]
Any help would be greatly appreciated!

**Comment by sytelus** [comment]
This was fixed. Could you please try out latest?

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
