### ISSUE TITLE
How to gather IMU data ?

### ISSUE THREAD

**Issue by mbrossar** [Microsoft/AirSim#1285]
I  follow the first way to gather the data for training some algorithm by  simply pressing the record button on the lower right corner for training some machine learning  algorithms.
But I can not find more than one recored image, and I do not find any poses or IMU values. 

How can we read and write IMU and ground truth?

**Comment by sytelus** [comment]
Please post your settings.json. Also you should try our pressing R key to start/stop recording.

**Comment by madratman** [comment]
We added an IMU API here https://github.com/Microsoft/AirSim/pull/1920
