### ISSUE TITLE
Adding Custom Vehicle Blueprint as a New SimMode inside the Plugin

### ISSUE THREAD

**Issue by appmechanic** [microsoft/AirSim#1287]
Hey guys , 
I Have Created a Custom Vehicle in a blueprint , Which is kind of a drone and moves on the wall of a tank in vertical direction , it has magnetic effect which keeps the Drone attached to the Wall of the tank , Now i want this drone to use as pawn from inside the AirSimPlugin , Drone has its own Controls and Camera , I want to activate its own controls and Camera when this drone is activated from the Settings.json File.
iam looking to set this drone as  a SimMode just like Car mode . 

As of now i can set the path for my Drone from settings.json file by setting pawnpaths inside this file , For this i have reparented my blueprint with CarPawn class as parent  , which leds me to possess my drone , But controls doesnt work and camera is also not from drone blueprint setups.

please help Anyone .

**Comment by Beijingsheng** [comment]
I encountered the same problem. I have built my own vehicle and I want to set my own mode. Have you solved your problem? 
Could anyone please help?

**Comment by shaoxiang** [comment]
@appmechanic  @Beijingsheng Hello, do you have a solution now? My requirement is add differential drive robot in Airsim. But there's no official way to do it.

**Comment by YongzhengCui** [comment]
@shaoxiang Hi, I have the same requirements as you. May I ask if you have successfully added differential drive robots to Airsim?
