### ISSUE TITLE
I need Compiler project in Linux

### ISSUE THREAD

**Issue by alitarfa** [microsoft/AirSim#1288]
Hi every one .
can any one compile  the city environment to linux (.sh) extension please , for using it directly without any changes because the project in window exist and i am working on linux os , please any one have the compiled project to tell me 
Thank you

**Comment by sytelus** [comment]
City environment is released for Linux. Please give it a try! See Releases tab in GitHub.

**Comment by kylelindgren** [comment]
The releases page can be found [here](https://github.com/Microsoft/AirSim/releases)
