### ISSUE TITLE
how to set the unreal engine path when ./build.sh in Linux?

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1291]
Hi,

How to set the unreal engine path when ./build.sh in Linux since there are multiple versions of unreal engine installed and I want to build the airsim with a specified version of UE?

**Comment by sytelus** [comment]
There is no UE path dependency on AirSim. The build.sh just prepares AirSim/Plugins folder which you then copy to your own UE project. You then start UE from wherever your UE install is and then tell it to open your uproj file.
