### ISSUE TITLE
how to control two or more vehicle and control them in same environment?

### ISSUE THREAD

**Issue by JordanWang0223** [Microsoft/AirSim#1296]
hello, I'm new for AirSim, I want to control two vehicle (i.e,. ues WASD to control first vehicle and UP DOWN LEFT RIGHT to control second vehicle).
I cant figure out how to spawn a car via AirSim and control
I use UE4.17

**Comment by sytelus** [comment]
Please see https://github.com/Microsoft/AirSim/blob/master/docs/multi_vehicle.md

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
