### ISSUE TITLE
RC Controller on USB : Not detected

### ISSUE THREAD

**Issue by gp0908140113** [Microsoft/AirSim#130]

**Comment by lovettchris** [comment]
I see "No description provided" ?  But you can ignore this message if you have a real remote control connected to your Pixhawk flight controller.

**Comment by jjy201314** [comment]
@lovettchris    I  have   sent  my   problems  to  your  email  with  the  outlook mail  ,if  you   received,please  help me to  solve  it  which have bothered  me for a  long time .  thak  you  very  much .

**Comment by lovettchris** [comment]
sorry still not getting emails from you, someone is blocking them.
