### ISSUE TITLE
How can you measure the sampling rate or FPS of the camera? 

### ISSUE THREAD

**Issue by aadi-mishra** [Microsoft/AirSim#1303]
I tried using python " time.time() "function at the beginning and ending of the loop. Also the same implementation was used when i am taking an image using simGetImage(). I have also tried calling the timestamp as mentioned in the camera Api docs but it doesn't work.

**Comment by sytelus** [comment]
It's hard to understand what you are trying to do, what you mean by "FPS" and why you need it. If you just want time spent in API call, that's really super standard Python stuff and you should take those questions on Stackoverflow or something.

https://stackoverflow.com/questions/1557571/how-do-i-get-time-of-a-python-programs-execution

Also [How to Create Issue or Ask Question Effectively](https://github.com/Microsoft/AirSim/blob/master/docs/create_issue.md)

**Comment by sytelus** [comment]
If this is still a problem, please file a new issue with code, settings and clear steps to reproduce the issue.
