### ISSUE TITLE
Airsim , Pixhawk/Ardupilot Support?

### ISSUE THREAD

**Issue by swcho0330** [Microsoft/AirSim#1305]
Hi!!
pixhawk I am a developer developing a drones based. Please understand that I can not speak English. The question is, can I use Airsim that ardulpilot flight board and MAVLink instead of px4 in Airsim? Also, if possible, what should you do with the Unreal Engine and Windows combination? Please. Thank you.

**Comment by sytelus** [comment]
Currently, no. However few folks have been working on this.

**Comment by RVBldr** [comment]
Internal VSTF 7422.

**Comment by madratman** [comment]
Let's track this in #65
