### ISSUE TITLE
Left camera for car in CityEnviron

### ISSUE THREAD

**Issue by Beijingsheng** [microsoft/AirSim#1307]
I'm trying to get images of views at the left of the car when driving in the city environment. Should I just adjust the default cameras or is it better to add new cameras? I don't know how to do either of them. Need help !! Many thanks

**Comment by sytelus** [comment]
See https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#available-cameras

**Comment by jonyMarino** [comment]
@Beijingsheng did the link shared by stylus help you? if yes I would close this issue

**Comment by jonyMarino** [comment]
Closed answered and old
