### ISSUE TITLE
Compiled Project in linux

### ISSUE THREAD

**Issue by alitarfa** [Microsoft/AirSim#1311]
Hi evey one ,
any one here can give me a compiled version of airsim  in linux
Please if any one can export the project from windows for me

**Comment by micmarty** [comment]
Linux binaries would make us very happy - especially when it comes to running in headless mode `SDL_VIDEODRIVER=offscreen SDL_HINT_CUDA_DEVICE=0 ./AirsimCityEnvironmentBinary` (couldn't test it yet, due to build problems)

**Comment by madratman** [comment]
Please see https://github.com/Microsoft/AirSim/releases/tag/v1.2.0Linux
