### ISSUE TITLE
Can i get optical flow ground truth of the video?

### ISSUE THREAD

**Issue by SkyRiderMike** [Microsoft/AirSim#1313]
As the title mentioned, can i get the optical flow ground truth of the video ?

**Comment by SkyRiderMike** [comment]
I know your point, but i think that's not enough to be a groundtruth. Since there will be occlusion of some pixels. Such as, if a house is behind a fence, you will find some parts of the house is invisible cause of the fence, but can be seen in other images since the camera is moving. Some dataset  like TsukubaReader provide this data, and it is quite useful for evaluate optical flow.

**Comment by Amigoshan** [comment]
Actually, you can get the groundtruth even when some objects are occluded. 

Imaging two images Img1 and Img2, you would like to calculate ground truth optical flow with respect to Img1. For each pixel in Img1, you warp it to Img2 using depth image of Img1, and two camera poses. You can get a dense optical flow for Img1, even for those pixels that are occluded in Img2.

**Comment by Amigoshan** [comment]
This is written by my colleague. https://github.com/huyaoyu/WorkFlow. You can get the dense optical flow like this. 
![image](https://user-images.githubusercontent.com/11531951/43871332-1ccef446-9b4a-11e8-93b5-c843e4013f9c.png)
![000064_400573_rgb](https://user-images.githubusercontent.com/11531951/43871382-58329f56-9b4a-11e8-91ec-fc5ee73fb1b9.png)

**Comment by Amigoshan** [comment]
Sorry, I just found I put a wrong link for the code. Updated!!
Again here is the code calculating the optical flow https://github.com/huyaoyu/ImageFlow.

**Comment by SkyRiderMike** [comment]
Thanks ! That helps a lot

**Comment by RVBldr** [comment]
@SkyRiderMike Can we consider this issue closed?

**Comment by RVBldr** [comment]
Internal VSTF 7421.

Per e-mail from SKyRiderMike, we should consider this closed.
