### ISSUE TITLE
I changed Settings.json but it doesn't really work

### ISSUE THREAD

**Issue by Beijingsheng** [Microsoft/AirSim#1314]
I am trying to take pictures of wider FOV, so I changed FOV in settings.json, however when I ran the program, pictures taken were still of 90 degrees FOV. Here is my Settings.json. Many Thanks

{
  "SettingsVersion": 1.2,
  "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 256,
        "Height": 144,
        "FOV_Degrees": 90,
        "AutoExposureSpeed": 100,
        "MotionBlurAmount": 0
      }
    ]
  },
  "SimMode": "ComputerVision"
}

**Comment by KeyneZzz** [comment]
afaik you can set  to a larger value (maybe 150, 170) to see if your change really works. This change doesn't require a restart of Unreal. Just try it.

**Comment by Beijingsheng** [comment]
@KeyneZzz  Thanks for your reply. I changed FOV to 150 and run the Airsim.sln, still no difference.

**Comment by Amigoshan** [comment]
From my experience, Airsim config format differs with different Airsim versions. Could you try remove "CameraDefaults": {}? I mean move "CaptureSettings": [] out of "CameraDefaults".

**Comment by jinlukang1** [comment]
I want to know if you can modify the Width and the height of the recorded data, is the AirSim usable?

because when I modify my setting.json, I still get the 256*144 data.

I don't know why my setting.json doesn't work.

`{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "SimMode": "Car",
    "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 0.5,
    "Cameras": [
        { "CameraName": "0", "ImageType": 6, "PixelsAsFloat": false, "Compress": true }
    ]
	},
    "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 512,
        "Height": 288
      }
    ]
	}
}`

Can somebody help me figure it out?

Thanks a lot.

**Comment by kwea123** [comment]
@jinlukang1 Try specifying the "ImageType" in "CaptureSettings", like this:
```
"CaptureSettings": [
      { "ImageType": 6,
        "Width": 512, 
        "Height": 288
      }
]
```
It works for me.

**Comment by jinlukang1** [comment]
@kwea123 Thanks s lot!
You have solved my problem!

And have you used ComputerVision mode? When I change the mode to ComputerVision mode in setting.json, the program will always exit with an error.

**Comment by Beijingsheng** [comment]
Thanks, everyone, my problem has been solved. Besides, I found that when FOV is over 180, the picture taken get weird. Lower 180 works fine.
