### ISSUE TITLE
Changing environments that came with AirSim

### ISSUE THREAD

**Issue by BrunoXL** [microsoft/AirSim#1319]
I´m testing `warehouse environment` which came with the lastest release, however some assets in there I really don´t need.
I´d like to know whether someone can upload UE project files unziped (the UE project folder), so I can get only what I need and recreate the environment. 
That would avoid the work of modeling a  whole environment from zero since I´m lookink for a warehouse environment.

**Comment by RVBldr** [comment]
@BrunoXL - Unfortunately this is not possible. We don't distribute any of the scenery assets at this time. There are various warehouse components on Unreal Marketplace which might help speed things up for you.
