### ISSUE TITLE
Regarding Integration of NanoMaps with Airsim

### ISSUE THREAD

**Issue by ghost** [microsoft/AirSim#1322]
Right now I am working on drone automation by providing it with a bit of map data or the source and goal coordinates and then applying nanomap for FOV(Field of View) object and collision detection so as to make the drone move faster through the obstacles.

**Is it possible to Integrate NanoMaps with AirSim over a Drone ?**

**Comment by sytelus** [comment]
Yes, it should be. NanoMap's core library are ROS-free so it should be easy to integrate (except visualizer part). There is PCL dependency but someone had created PR on NanoMap's repo to remove that dependency as well.

**Comment by dicermm** [comment]
I tried searching for it but couldn't find it, if possible can you please get me the repo link of it.

**Comment by chris-aeviator** [comment]
did anybody work on this yet? I'd be interested in collaborating
