### ISSUE TITLE
UE crashed when I had changed settings.json and open run.bat

### ISSUE THREAD

**Issue by Beijingsheng** [Microsoft/AirSim#1329]
This is the example from settings.md, however, it causes a crash when I run UE4 CityEnviron. Maybe someone can explain this?
{
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "Vehicles": {
    "PhysXCar": {
      "VehicleType": "PhysXCar",
      "Cameras": {
        "front-center": {
          "CaptureSettings": [
            {
              "ImageType": 0,
              "FOV_Degrees": 120
            }
          ]
        }
      }
    }
  }
}

**Comment by Beijingsheng** [comment]
There seems to be a bug of adding keys under "cameras" in "vehicle", every time I add "mycamera" in "cameras" or use defaults cameras like "front-center", UE crashes.

**Comment by sytelus** [comment]
We can't reproduce this in our latest version. If problem still persist, please file new issue with code, settings and clear steps to reproduce it.
