### ISSUE TITLE
How to use nanomaps as a firmware in AirSim through QGroundControl ?

### ISSUE THREAD

**Issue by ghost** [Microsoft/AirSim#1335]
Hello,
I have already done the set up for AirSim over my machine. Now, please guide me how to upload Nanomaps package To QGroundControl in order to fly the drone as per the Nanomaps algorithm. Kindly help me out I am a beginner.

**Comment by madratman** [comment]
What do you mean by nanomap? I am just aware of [this](https://github.com/peteflorence/nanomap_ros).

**Comment by madratman** [comment]
closing coz of lack of response / activity
