### ISSUE TITLE
error MSB8036 when running build.cmd

### ISSUE THREAD

**Issue by jpvolt** [Microsoft/AirSim#1349]
Im getting  build failed:

> error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project> >property pages or by right-clicking the solution and selecting " Retarget solution"

but i have vs and windows sdk 8.1 installed;
i arready reinstalled vs.:
![img](https://user-images.githubusercontent.com/12127137/44614428-b3806980-a7fa-11e8-8609-6643eda4ef4b.png)

**Comment by sytelus** [comment]
We can't reproduce this in our latest version.
