### ISSUE TITLE
Cannot select Game Mode On Linux Building

### ISSUE THREAD

**Issue by mocibb** [Microsoft/AirSim#135]
I got newest version(68efe37ea56a27d0) of github, and have successful built and run AirSim after remove RosFlightQuadX dependance (MultiRotorConnector.cpp) which can cause some system error when Unreal Engine runs.
But i cannot set Game Mode to SimGameMode, it crashed when saving map.
there are backtraces i got from GDB debug.
![screenshot from 2017-03-30 11-19-28](https://cloud.githubusercontent.com/assets/18642/24490200/23bf985a-1554-11e7-8c8e-fe8abe2a8b82.png)
It seems something is wrong in the Plugin Unreal Engine. I cannot solve this problem, because I'm not familar with Unreal Engine.

**Comment by madratman** [comment]
hey @mocibb, I am facing apparently the same issue:

Can you share exactly what you changed in `MultiRotorConnector.cpp`. 
I guess you changed `vehicle_params_.reset(new msr::airlib::RosFlightQuadX());` and `        static_cast<RosFlightQuadX*>(vehicle_params_.get())->initializePhysics(&environment_, &vehicle_.getKinematics());`
but that doesn't cause any problems?

**Comment by mocibb** [comment]
I just remove something that related to RosFlightQuadX, because cause symbol not found error when I run UE.
[MultiRotorConnector.txt](https://github.com/Microsoft/AirSim/files/909503/MultiRotorConnector.txt)
Since the issue I've ran into is tracked by #112 I will close this one.
