### ISSUE TITLE
Linear_velocity from CarState.estimatedKinematics and simGetGroundTruthKinematics() is not correct.

### ISSUE THREAD

**Issue by mengxi-ascent** [microsoft/AirSim#1350]
Hi all,
I tried to get the linear_velocity of a car from `CarState.estimatedKinematics` (via `getCarState()`) and `simGetGroundTruthKinematics` when connecting the pythonClient to the airsim server of pre-built binary in Windows (CityEnviron, SimpleMaze). 

Both of the methods gave me some very big numbers even when the car was not moving, and the values were the same for both of the methods.

I would like to know why the number is not zero (or approximately zero) when the car is not moving.
I would appreciate for any help.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
