### ISSUE TITLE
Meaning of `GlobalOffset` and `LocalOffset` in NedTransform.cpp

### ISSUE THREAD

**Issue by mengxi-ascent** [Microsoft/AirSim#1352]
I am looking into the codes in `NedTransform.cpp` and try to understand the coordinate transform from UU to NED.

In my understanding, `LocalOffset` is the location of the pawn spawning place with respect to the world coordinate in Unreal Engine.
Then what does the `GlobalOffset` mean? According to the comment in `NedTransform.h: (2) Global NED: This is NED transformation of UU with origin set to 0,0,0`, should the `GlobalOffset` be (0, 0, 0)?

I will appreciate a lot if someone can help to clarify the question.

**Comment by sytelus** [comment]
There are, 

1. Unreal global frame - this is UU coordinates
2.  We create our NED global frame with origin at Player Start component.
3. Each vehicle creates its own NED local frame with origin set to its start location.

So the global offset determines origin of global NED frame. The local offset determines origin of local NED frame wrt to global NED frame.
