### ISSUE TITLE
Data Logging Code

### ISSUE THREAD

**Issue by SoumiDas** [Microsoft/AirSim#1360]
Hi,

I'm new to AirSim and I wish to obtain some information. I am using City Environment and want to manually drive the car and record the images in different ImageTypes viz. Scene , Segmentation. Which is the file I should be playing around with for manually driving i.e after recording and obtaining the different types of images.

Thanks!

**Comment by thias15** [comment]
Set up the settings file with the cameras you wish to record according to docs. Then hit R to start/stop recording. (Or the big red button)

**Comment by SoumiDas** [comment]
Thanks a lot.

So can we record the steering, throttle and speed values too via the
settings.json file? I checked with the hello_car.py code and we can fetch
those control values but is it possible through only the settings file?

**Comment by sytelus** [comment]
Take a look at this: https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#recording

**Comment by madratman** [comment]
@SoumiDas did that answer your question?
