### ISSUE TITLE
How to control Multirotor through Python in an AirSim + PX4 SITL Setup

### ISSUE THREAD

**Issue by janmlr** [Microsoft/AirSim#1361]
Hey,
i managed to get AirSim (prebuild binary) running with the latest stable Software-In-The-Loop Version of PX4. After setting up the specified parameters for the PX4 config and the AirSim settings.json, i am able to connect PX4 with AirSim and monitor the Quadrocopter with QGroundControl. So the setup is basically working, but i am having problems with the control through the Python-API. I did import AirSim, created a MultirotorClient and enabled the API control. And it somehow works, when i call client.takeoffAsync(), the simulated UAV starts taking off and the PX4 console logs "Takeoff detected", but the drone won't stop getting higher and higher. QGroundControl doesn't seem to receive the right altitude information, since it displays an altitude of 2.5 meters, when in AirSim the drone is about 50 meters high. 
Furthermore other API-Calls like moveToPositionAsync, moveToZAsync or rotateByYawRateAsync won't do anything.
Are there any additional settings i need to configure to get this working?

**Comment by lovettchris** [comment]
This issue has been fixed.
