### ISSUE TITLE
ImageRequest difference

### ISSUE THREAD

**Issue by Gaduu** [Microsoft/AirSim#1362]
Quick question regarding getting data from AirSim in Python. So I've noticed throughout several tutorials that obviously people tent to get the data differently, I'm talking about the last two bool arguments in ImageRequest(...,...,pixels_as_float, compress). I was wondering what are the pros/cons of retrieving the data in different ways?

Cheers,

**Comment by thias15** [comment]
The flag pixels_as_float is meant for depth and disparity if you need the raw values. Similary, if you want the raw data for images set compress=False. Otherwise, if you want to save them directly to disk set compress=True.
