### ISSUE TITLE
Has anyone used airsim with Unreal 4.20.2?

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AirSim#1363]
Wondering if anyone has tried running airsim with the latest release (4.20.2) of unreal.  I will play around with it, but I know there is a lot of functionality that others may hit that I miss.

**Comment by madave91** [comment]
https://github.com/Microsoft/AirSim/issues/1295

**Comment by madave91** [comment]
I just want to try if it's working, but I found an issue, maybe it helps you out:
https://github.com/Microsoft/AirSim/issues/1295

**Comment by NextSim** [comment]
Great thanks
