### ISSUE TITLE
Is there any way to interrupt current movement command?

### ISSUE THREAD

**Issue by whxru** [Microsoft/AirSim#1366]
According to [document](http://python.dronekit.io/develop/best_practice.html) of DroneKit (SDK for Pixhawk), the movement command will be interrupted by another command, so is it possible to decide the priority of (movement) commands?

**Comment by sytelus** [comment]
If you issue new command it interrupts the current async command being executed.

**Comment by whxru** [comment]
@sytelus Thanks for your answer
