### ISSUE TITLE
Car orientation

### ISSUE THREAD

**Issue by hxlee309** [Microsoft/AirSim#1369]
When I use the following python script to read the car orientation in ipython3:

import airsim
client = airsim.CarClient()
car_state = client.getCarState()
car_state.kinematics_estimated.orientation

It returns 

<Quaternionr> {   'w_val': 0.7071067094802856,
    'x_val': -0.0001394362043356523,
    'y_val': -2.7409907488618046e-05,
    'z_val': 0.7071068286895752}

I am wondering what's the physical meaning of "w_val" and how to convert this 4d vector into roll, pitch, yaw angles?

Thanks,

Ethan

**Comment by thias15** [comment]
It's a quaternion. Check out this link:
https://en.m.wikipedia.org/wiki/Conversion_between_quaternions_and_Euler_angles
