### ISSUE TITLE
How to install the "cmake" on Windows

### ISSUE THREAD

**Issue by Mzhouyi** [Microsoft/AirSim#137]
I have download the "cmake-3.8.0-rc4-win64-x64.msi" and install it on my computer, but when I Run `build.cmd` from the command line, it show that "cmake was not found! First install the latest version from https://cmake.org/."how  can I install the cmake and build the rpclib? please

**Comment by lovettchris** [comment]
Make sure the path to your cmake installation bin folder is added to your System Control panel, Advanced System Settings, Environment Variables, Path, like this:

![image](https://cloud.githubusercontent.com/assets/18707114/24562101/622e964a-15fe-11e7-8f9c-ba2444f2ce43.png)

**Comment by lovettchris** [comment]
Please re-open this if this was not the issue, thanks.
