### ISSUE TITLE
build failed in windows

### ISSUE THREAD

**Issue by JohnSnowball** [Microsoft/AirSim#1372]
Hi I got a problem when executing build.cmd.
Using Vs 2017 community, while building, it shows:

![default](https://user-images.githubusercontent.com/18409502/45077327-7633aa00-b11f-11e8-9292-e975f685fd0c.PNG)

From double to const float error.I tried to modify the source code however it doesn't work.
Could anyone tell me how to fix it?

**Comment by sytelus** [comment]
It's interesting that only you have encountered this so far :). I've added a fix.
