### ISSUE TITLE
How to call APIs without RPC?

### ISSUE THREAD

**Issue by JloveU** [Microsoft/AirSim#1373]
The RPC requests network connections, which is sometimes fragile and inefficient.
So I am looking for anothor way to export the AirSim APIs.
For example, create a dll exporting the APIs.
Then load the dll in python and call the APIs to simulate the environment in console or Unreal GUI.
Is this feasible?
Thanks!

**Comment by sytelus** [comment]
You can just use C++ APIs: https://github.com/Microsoft/AirSim/blob/master/docs/apis_cpp.md

You can always wrap these C++ API with Python bindings using tools like [swig](http://www.swig.org/).

However I suspect this may or may not solve your issue. You haven't gave more info on what you are trying to do but you might just have bottleneck on transferring too much data over RPC. In that case, you might want to write your client code just within Unreal app itself (this modifies AirSim code for your custom needs).
