### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by zaddan** [Microsoft/AirSim#1375]
I have installed visual studio '17 and cloned the AirSim repo. However I get the following error when running build.cmd (in x64 Native Tools Command Prompt for VS 2017)
c1xx : fatal error C1083: Cannot open source file: 'common_utils\FileSystem.cpp': No such file or directory [C:\AirSim\MavLinkCom\MavLinkCom.vcxproj]

PS: I get plenty of errors similar to the above one complaining the compiler can not find the files.

**Comment by zaddan** [comment]
This issue is resolved. I am not sure why this fixes the issue but if I clone using the "Bash on Ubuntu on Windows" app, this issue will occur but if I use "x64 Native Tools Command Prompt for VS 2017" to clone the repo, I won't have to deal with it.

**Comment by sytelus** [comment]
Could you please tell us what is the sequence of command line you used?
