### ISSUE TITLE
Is there any way to run the simulator in pure console (not based on Unreal)?

### ISSUE THREAD

**Issue by JloveU** [Microsoft/AirSim#1379]
Is there any way to run the simulator in pure console (not based on Unreal)?
Thanks.

**Comment by sytelus** [comment]
Yes you can instantiate drone without Unreal. Obviously then you don't have Unreal environment so no collisions etc.

Here's the example code: https://github.com/Microsoft/AirSim/blob/master/AirLibUnitTests/SimpleFlightTest.hpp
