### ISSUE TITLE
Allow multirotors coexist with cars

### ISSUE THREAD

**Issue by whxru** [Microsoft/AirSim#1382]
I'm now working on the network of UAV-UGV, so maybe a new mode like "Both" in repo of @kshitiz38 could be added to allow multirotors coexist with cars.

**Comment by RVBldr** [comment]
Internal VSTF 7419

**Comment by whxru** [comment]
@RVBldr What does “Internal VSTF 7419” mean?

**Comment by TritonSailor** [comment]
@RVBldr You're spamming the list every time when you reply with Internal VSTF 7419

**Comment by madratman** [comment]
let's track this on #506. Closing this to avoid duplicates. Looks like @kshitiz38 has been able to get this done on that thread

**Comment by FL2316** [comment]
I follow your advice, but there are some mistakes that can't be solved. I don't know what to do...seg fault,
Can anybody help me?thanks alot
