### ISSUE TITLE
Can I control two cars separately via keyboard?

### ISSUE THREAD

**Issue by WadeWuu** [Microsoft/AirSim#1384]
Can I control two cars separately via keyboard?
I have change the RC of two cars, but when I use the keyboard to control, they move at the same time.

**Comment by sytelus** [comment]
Currently no. Each car needs at least 6 keys and it gets too complicated to control multiple car using same keyboard. But you can set [RC/RemoreControlID](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#common-vehicle-setting) setting to assign defferent remote controllers to each car.
