### ISSUE TITLE
"IsFpvVehicle" setting not working for multirotor

### ISSUE THREAD

**Issue by TritonSailor** [microsoft/AirSim#1392]
Setting which vehicles are controlled manually with the "IsFpvVehicle" setting for PhysXCar vehicles in car sim mode is working fine.  However for SimpleFlight vehicles in multirotor sim mode, the "IsFpvVehicle" setting isn't respected, all spawned vehicles are controlled manually.

I could only find a few references to fpv_vehicle in AirSimSettings.hpp and SimModeBase.cpp.  I was unable to find anything it the code that would account for this behavior.

**Comment by jonyMarino** [comment]
@TritonSailor I repeat RVBldr question

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
