### ISSUE TITLE
Question: drone starts to shake if the altitude is over 50m

### ISSUE THREAD

**Issue by xiahaa** [microsoft/AirSim#1394]
Hi, 
Version: Airsim 1.2.0, binary.
Control: call moveOnPathSync with default setting but assigned waypoints.
Problem: looks fine if the altitude is lower than 50m. However, if I tried to fly along the same path with an altitude over 60m, the drone started to shake. Does anyone have an idea about this abnormal phenomenon?

**Comment by xiahaa** [comment]
> I faced the same problem with moveToPositionAsync() when the drone flies over or around a certain height. But I have no idea about this.

It seems quite strange. Could the aerial dynamics constraints be the reason?
I added gimbal, so the footage you will get is ok. But the drone's attitude is a mass...

**Comment by sytelus** [comment]
Could you please provide the sample code to reproduce this? I'm guessing your speed is too high.

**Comment by xiahaa** [comment]
> Could you please provide the sample code to reproduce this? I'm guessing your speed is too high.

```
sss
```

**Comment by madratman** [comment]
@xiahaa can you please try the branch [bug_fixes/z_controller](https://github.com/Microsoft/AirSim/tree/bug_fixes/z_controller) and get back to us?

**Comment by xiahaa** [comment]
> @xiahaa can you please try the branch [bug_fixes/z_controller](https://github.com/Microsoft/AirSim/tree/bug_fixes/z_controller) and get back to us?

Sure~

**Comment by madratman** [comment]
@xiahaa any news?

**Comment by hoangtranngoc** [comment]
Hi @madratman! 
In my case, the error is still there. The drone is still shaking. 
You can see my recorded video here https://youtu.be/VOaxnu0XI_s

**Comment by xiahaa** [comment]
> @xiahaa any news?

Sorry for the delay.
I have tried with the branch you provided. The behavior is even more wired, from what I have seen~
I made a gif that you can see the behaviors.

![airsim1](https://user-images.githubusercontent.com/36867143/51075337-5c384400-168a-11e9-81c5-17e93fb8ed41.gif)

**Comment by stavBodik** [comment]
Any solution for this ? Its looks like Weather : Wind bug.

**Comment by ACLeighner** [comment]
Still getting this bug in the latest AirSimNH environment

**Comment by ACLeighner** [comment]
Ok, I think I found a short term fix, although looking at the code it looks like someone had something more elegant planned but it never got finished.

In MultirotorAPIBase.cpp I changed some code in the moveToPathPosition 
 Function:

Replace
```c++
//send commands
//try to maintain altitude if path was in XY plan only, velocity based control is not as good
    if (std::abs(cur.z() - dest.z()) <= 1) //for paths in XY plan current code leaves z untouched, so we can compare with strict equality
        moveByVelocityZInternal(velocity_vect.x(), velocity_vect.y(), dest.z(), yaw_mode);
    else
        moveByVelocityInternal(velocity_vect.x(), velocity_vect.y(), velocity_vect.z(), yaw_mode);```

with

```c++
//send commands
moveByVelocityInternal(velocity_vect.x(), velocity_vect.y(), velocity_vect.z(), yaw_mode);```

**Comment by fawadahm** [comment]
This did not help at higher altitudes. We still see a lot of jitter/vibrations at 70m/80m heights. @madratman, are there any other fixes we can try?

**Comment by ACLeighner** [comment]
Huh, you rebuilt with that change and no luck?  I just tried flying at 90m and didnt have any issues...If someone else wants to try, it looks like the issue is is moveByVelocityZInternal, which causes the drone to very quickly change its zvelocity  at the target altitude.  So it is essentially stuck oscillating (shaking) at that altitude.

**Comment by ACLeighner** [comment]
OK! I realize now that my earlier solution doesn't work at higher velocity...Edited my earlier comment with a new change that seems to be working

**Comment by fawadahm** [comment]
This works. Thank you!

**Comment by lucafei** [comment]
i have alse met this problem? do you guys have any solution for that?

**Comment by nethtrick** [comment]
Can you verify this is not an artifact of the Blocks environment? I believe at one point there was an invisible "ceiling" in that level,
