### ISSUE TITLE
 Aisrim Px4 SITL + python  - critical navigation failure - check sensor calibration

### ISSUE THREAD

**Issue by geevargs** [microsoft/AirSim#1396]
![screenshot from 2018-09-14 15-16-52](https://user-images.githubusercontent.com/29235421/45577604-9fe08580-b831-11e8-83fe-67c865a50f36.png)
Linux 16.04 using unreal engine 4.18 
I followed the instruction for the SITL to the dot but I keep getting 
critical navigation failure - check sensor calibration everytime I run any python api command other than Takeoff and Landing.

**Comment by asimukaye** [comment]
I am facing a similar error. Specifically, the following is the description of the error(s):
1. The baro and GPS altitude does not change after takeoff. This is causing the client.takeoffAsync() call to make the multirotor to go up infinitely.
2. The GPS location gets reset to the home location after a few seconds of manual flight.
3. This problem takes place in both HILS and SITL mode (with the corresponding settings as prescribed in settings.json)
4. I cannot fly the multirotor in position or mission modes as a result as it returns a critical navigation failure error.
Note: This problem did not occur with Airsim 1.1.10; 
Note the baro and GPS altitudes in the two screenshots; one on ground and the other in flight.
<img width="910" alt="ground-airsim" src="https://user-images.githubusercontent.com/19420436/45736462-a93e6900-bc08-11e8-8554-c0c09e03eb2e.PNG">
<img width="920" alt="inflight-airsim" src="https://user-images.githubusercontent.com/19420436/45736465-a93e6900-bc08-11e8-804f-949937ac5308.PNG">

**Comment by HoaPham2711** [comment]
I am facing this problem too.

**Comment by HoaPham2711** [comment]
I was able to fix this problem. Please re-clone PX4 Firmware (https://github.com/PX4/Firmware.git)
then **checkout tags/v1.7.0** using 

> git checkout tags/v1.7.0 && git submodule update --init --recursive

**Comment by HoaPham2711** [comment]
Sorry, my solution is not radical. The drone still takes off to infinity :(

**Comment by mohammedshafeeqet** [comment]
@lovettchris Some help here, please.

**Comment by geevargs** [comment]
I was able to get it working...using unreal 4.17.2 and Airsim unreal4.16...with pixhawk firmware 1.6.3

**Comment by mohammedshafeeqet** [comment]
@geevargs Can you please confirm if it is Airsim v1.2 with Unreal 4.17.2?

**Comment by ericamoroso** [comment]
Had the same issue. Looks like the "Environment" class isn't getting properly handled between UE4 and AirLib. A hack "solution" for Airsim v1.2 is to uncomment lines 115 and 116 within AirLib/include/physics/PhysicsBody.hpp.

**Comment by HoaPham2711** [comment]
Thank you @ericamoroso . Your solution worked for me

**Comment by geevargs** [comment]
@mohammedshafeeqet  https://github.com/Microsoft/AirSim/tree/Unreal4.16...is what I used

**Comment by asimukaye** [comment]
Thanks @ericamoroso , your solution works for me as well

**Comment by lovettchris** [comment]
A bunch of bugs have been fixed in AirSim and PX4 SITL model should work a lot better now.

**Comment by Planche95** [comment]
I had that problem on release v1.2.1 - Windows, but when I build AirSim from actual master branch everything worked fine.

**Comment by lovettchris** [comment]
great to hear, thanks for trying it.

**Comment by Zachmoist** [comment]
Hello, I'm currently having the same issue, i'm using Windows 10 and Airsim 1.2.0, PX4 1.8.2, QGroundcontrol v3.4.3 and Python 3.6

My settings.json:
`{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor",
    "Vehicles": {
        "PX4": {
            "VehicleType": "PX4Multirotor",
            "UseSerial": false
        }
    }
}`

When use QGC and make a move to position i get the navigation error.
![Capture1](https://user-images.githubusercontent.com/28161879/65045991-28f33680-d936-11e9-89cf-af78819d5d70.PNG)

If i don't use QGC and use 'commander arm' and 'commander takeoff' the drone starts to fly in an orbit until it starts collisioning to the ground, i try to get the home position but the 'pos' command doesn't work for me, i get a "INFO [gps] not running" message.

Also, i never get the home position log message, i start the PX4 and wait for around 15 seconds but the most i get is this:
![Capture](https://user-images.githubusercontent.com/28161879/65046086-517b3080-d936-11e9-924c-2200a1bca2df.PNG)

**Comment by ironclownfish** [comment]
This appears to behave better with AirSim v1.2.1 and newer. @Zachomist please try updating beyond v1.2.0 and open a new issue if the problem persists for you (since that would imply it's not actually fixed in newer versions as Planche95 suggests.) Thanks
