### ISSUE TITLE
Build error - Utils.hpp and UpdatableObject.hpp not found

### ISSUE THREAD

**Issue by jediMasterMindTrick** [Microsoft/AirSim#14]
I've tried to add the plugin to different projects with different maps, but no luck.  Anyone have any ideas?

![image](https://cloud.githubusercontent.com/assets/1563067/23088626/303373ea-f54c-11e6-9acf-4b7781f88952.png)

**Comment by lovettchris** [comment]
I just tried a fresh test with new Unreal project, and it works, can you check the setup setups in [this video](https://www.youtube.com/watch?v=HNWdYrtw3f0&feature=youtu.be)? Thanks.

**Comment by sytelus** [comment]
Plugin is dependent on setting up include and library paths. You might want to make sure your new project has same settings for these as our projects.

**Comment by jediMasterMindTrick** [comment]
> I just tried a fresh test with new Unreal project, and it works, can you check the setup setups in this video? Thanks.

Do I need to have my hardware connected when I'm compiling the Unreal project with the AirSim library?

> Plugin is dependent on setting up include and library paths. You might want to make sure your new project has same settings for these as our projects.

I followed the instructions in the image below and was able to get the AirSim library to compile, but once added to an Unreal project, I cannot get the project itself to compile.  Are there other things I need to include or add path variables for?
![image](https://cloud.githubusercontent.com/assets/1563067/23145316/6f1a2602-f79b-11e6-8661-55f07a0a03ab.png)

**Comment by lovettchris** [comment]
Did you right click and re-"generate visual studio project files" after adding the Plugin folder?  We have some build instructions that need to be picked up by the unreal generation process.

**Comment by netpearce** [comment]
I had the same issue -- essentially AirLib includes etc weren't copied into the Unreal\Plugins folder (along with some library objects for linking) when I compiled the main AirLib code.

When I first installed I somehow skipped the step to run build.cmd and compiled directly via the solution file 

Going back and following this step solved the issue.

**Comment by sytelus** [comment]
Please reopen if issue still exists. I've verified steps as [documented here](https://github.com/Microsoft/AirSim/blob/master/docs/build.md) and they work on fresh install as long as [prerequisites](https://github.com/Microsoft/AirSim/blob/master/docs/prereq.md) are met.
