### ISSUE TITLE
PositionController does not support yaw axis i.e. 3

### ISSUE THREAD

**Issue by elgeom** [Microsoft/AirSim#1400]
Hello, I have an error on reset() with latest AirSim:

Exception occurred while updating world: PositionController does not support yaw axis i.e. 3
Exception occurred while updating world: reset() must be called first before update()
Exception occurred while updating world: reset() must be called first before update()
Exception occurred while updating world: reset() must be called first before update()

**Comment by sytelus** [comment]
Could you please provide more details, example code etc? Are you using drone or car or CV mode? I don't see this error with default installation.

**Comment by madratman** [comment]
closing coz of lack of activity

**Comment by jinkman** [comment]
Has the problem been solved？
