### ISSUE TITLE
Compilation Error: build.cmd fails to build when path too long [bug] [fix proposed]

### ISSUE THREAD

**Issue by vincedjango** [Microsoft/AirSim#1409]
I was cloning Airsim where the path was about 100 characters long and when executing _build.cmd_  it was always failing with errors such as:

`airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory`

What I did is that in a _x64 Native Tools Command Prompt for VS 2017_, I ran the following command located at line 127 of the script:
`move AirLib\deps\eigen* AirLib\deps\del_eigen`

The result returned is:
```
The filename or extension is too long.
        0 dir(s) moved.
```

What I did is that I cloned the repot to C:/Tmp/Airsim/ and the script was executed successfully.

What I propose would be to change the line:
`move AirLib\deps\eigen* AirLib\deps\del_eigen`
to the powershell move
`Move-Item -Path AirLib\deps\eigen*  -Destination AirLib\deps\del_eigen`

The powershell move worked, it seems to be more flexible about the length of the path.

Obviously, there are probably more lines that are not executed correctly when the path is too long, they will have to be fixed as well.

**Comment by sytelus** [comment]
I've pushed this change. Thanks for the suggestion.
