### ISSUE TITLE
cannot see the airsim blueprint in the content browser built with unreal engine 4.19 on ubuntu

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#1411]
Hi,

Since I need to change the scale of the body mesh of the drone in linux unreal engine, I need to find the airsim blueprint under the content browser. But I cannot see the airsim blueprint in the content browser built with unreal engine 4.19 on Linux.

While in the windows airsim built with unreal engine 4.19, I  can find the BP_FlyingPawn under the content browser and successfully change its scale.

Is it an issue related about airsim and the version of unreal engine 4.19 in Linux?

**Comment by sytelus** [comment]
Could you please post screenshot?
