### ISSUE TITLE
Blocks env fails: NullSourceCodeAcessor not found

### ISSUE THREAD

**Issue by stratomaster31** [microsoft/AirSim#1413]
When I try to open the blocks project from the UE4editor i get this prompt error messahe:

![screenshot from 2018-09-21 13-25-17](https://user-images.githubusercontent.com/22171434/45878598-ef7b0000-bda1-11e8-9b47-2120d7955be9.png)

Any help? Thx in advance

**Comment by anphunl** [comment]
Same issue here.

![screenshot from 2018-10-10 03-46-50](https://user-images.githubusercontent.com/11812805/46697584-29bc1c80-cc3f-11e8-9927-a03077bad695.png)


Operating System: Ubuntu 16.04 64bit
CPU: Intel Core i5 8400
GPU: Nvidia GTX 1080 Ti
RAM: 32 GB
Flight Controller: None
Remote Control: None

**Comment by sytelus** [comment]
I think there is an issue with your install. See here: https://answers.unrealengine.com/questions/562619/unreal-engine-414-linux-no-compiler-was-found.html

**Comment by RVBldr** [comment]
@stratomaster31 Is your issue resolved?

**Comment by ssokhey** [comment]
@stratomaster31 @anphunl @RVBldr 
There are multiple things you have to check to make it work for example your clang version, plugins folder etc.

Better to use newly released blocks binary. [https://github.com/Microsoft/AirSim/releases](url)

**Comment by jonyMarino** [comment]
closed due to age
