### ISSUE TITLE
Custom AirSim version for research purposes

### ISSUE THREAD

**Issue by eds89** [Microsoft/AirSim#1416]
Hello,
As part of a research project, I plan to extend AirSim. Do I need to license a map (e.g. Neighbourhood) in order to include it on a custom distribution? The extended version will be not for profit and purely for research purposes. The API features already included may not be sufficient, hence the need for changing its source directly.

**Comment by eds89** [comment]
Where and how did you find the Neighbourhood map? I could not find it on
the Unreal Marketplace. Also, where do the car models come from?

**Comment by TritonSailor** [comment]
I think this is the starting point for the Neighborhood environment.

https://www.unrealengine.com/marketplace/modular-neighborhood-pack

Car models can be either props (static meshes) that don't move, or rigged vehicles (skeletal meshes) that can be setup as car pawns.  You can find both types on the marketplace, or make your own.

**Comment by eds89** [comment]
Did the AirSim project buy these packs?

**Comment by RVBldr** [comment]
In most cases those content packs come with a demo map which replicates the UE store images, but you also get the individual assets to create your own scene. As Triton stated, most royalty free licensing provides for binary distribution but no source distribution; make sure you read the various licensing models for purchased content.

**Comment by eds89** [comment]
So, there's no way to change AirSim's source, which is available free of
charge, compile it again on an existing map (e.g. Neighbourhood)?

I'd like to add a camera effect, similar to Semantic Segmentation, which is
modelled through a PostProcessMaterial (I believe).

**Comment by TritonSailor** [comment]
That's exactly what you do. Use any version of AirSim you want, and compile
it with your project that has your custom environment.
