### ISSUE TITLE
Is that possible create my own vehicle?

### ISSUE THREAD

**Issue by HereIsPatrick** [Microsoft/AirSim#1422]
Hi,
Is that possible create my own vehicle and features as below?
And I'd like to redesign turn signal and head light.
I want control signal and head light via API.

Br,
Patrick
label:"new feature"

**Comment by RVBldr** [comment]
Yes it is. See Pawn Paths at https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#pawnpaths for some guidance on selecting your own pawn actor. You'll need to do your own development effort on the vehicle but you can then use this in AirSim.

**Comment by HereIsPatrick** [comment]
Hi RVBldr,
  I'm glad to hear this, Thanks.
  I'll try it. 


> Yes it is. See Pawn Paths at https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#pawnpaths for some guidance on selecting your own pawn actor. You'll need to do your own development effort on the vehicle but you can then use this in AirSim. You may also need to do some API work to open the controls to UE4 from AirSim for lights and blinkers.
