### ISSUE TITLE
How to load my own map by the Airsim

### ISSUE THREAD

**Issue by chengjinjack** [Microsoft/AirSim#1423]

**Comment by MaximStrnad** [comment]
You have to crate your own ureal engine project, then inject or create a map into it. Then you install the AirSim as plugin into the unreal engine and change the world game settings to AirSim game (something like that). Maybe you will need to delete all player "cameras" so if you start the game with only one player camera the airsim will automatically sign into it. There is a video on youtube explaining the full process, there is little to now comentary but if you slow it down you should be copy the moves. I hope that helps

**Comment by NextSim** [comment]
https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md
