### ISSUE TITLE
Is this possible to use VR?

### ISSUE THREAD

**Issue by HereIsPatrick** [Microsoft/AirSim#1426]
I check this issues of new feature.
#571 mention about will have a VR Build in last year.
Has anyone build it with VR successfully?

**Comment by DavidLSmyth** [comment]
I managed to package it and get it running with an oculus rift, I can give you the package configuration if you'd like. It was from the UE4.16 version

**Comment by HereIsPatrick** [comment]
It's great. 
I'd like to try it. How can I get it? size large or small? 
Thank you.

**Comment by linarism** [comment]
Funny enough AirSim works with VR natively. I use it with an Oculus Rift without any problems. Just add "`-vr`" argument for the executable. Easy to do when you make a shortcut that has the following target.
