### ISSUE TITLE
How to access data of camera_position and camera_orientation in ImageResponse

### ISSUE THREAD

**Issue by taotsi** [Microsoft/AirSim#1427]
Sorry I didn't find any description about camera_position and camera_orientation. How to access x, y and z in `camera_position` and w, x, y, z in `camera_orientation`?

I've tried `auto x = response.camera_position[0]` and `auto x = response.camera_position.x()` and got the save value. It seems correct. And I assume that `auto quat_w = response.camera_orientation.w();` is also correct, am I right?

**Comment by sytelus** [comment]
[Here's declaration](https://github.com/Microsoft/AirSim/blob/a4fcf568e75b6d675d5d127754757d673ce33ecb/PythonClient/airsim/types.py#L171) of ImageResponse object that you get. It returns [Vector3r](https://github.com/Microsoft/AirSim/blob/a4fcf568e75b6d675d5d127754757d673ce33ecb/PythonClient/airsim/types.py#L40).

So basically use, `response.camera_position.x_val`.

**Comment by taotsi** [comment]
thanks!
