### ISSUE TITLE
Lat accel or yaw rate?

### ISSUE THREAD

**Issue by NextSim** [Microsoft/AirSim#1429]
Are either of these values available internally?

I looked and did not see references to them in PhysX, but wasn't sure if they might be in a different part of the system.

**Comment by sytelus** [comment]
[getCarState ](https://github.com/Microsoft/AirSim/blob/a4fcf568e75b6d675d5d127754757d673ce33ecb/docs/apis.md#apis-for-car) gives you kinematics which has these quantities.
