### ISSUE TITLE
name mismatch

### ISSUE THREAD

**Issue by maddin200** [Microsoft/AirSim#143]
declaration:
MavLinkFtpClientImpl(int local_system_id, int local_component_id);

definition:
MavLinkFtpClientImpl::MavLinkFtpClientImpl(int system_id, int component_id)
	: MavLinkNodeImpl(system_id, component_id)
{
}

**Comment by lovettchris** [comment]
[Fixed](https://github.com/Microsoft/AirSim/commit/071def8428cf77aeb3e5b12f4cbacb463eba003b), thanks.
