### ISSUE TITLE
Sensors on AirSim

### ISSUE THREAD

**Issue by BrunoXL** [Microsoft/AirSim#1436]
I´m planning to map a 3D indoor environment, which sensors are now implemented on AirSim?

**Comment by sytelus** [comment]
There is vision sensor (mono or stereo). Lidar is also implemented by @bmalhigh and config for it coming soon.

**Comment by kvenux** [comment]
> There is vision sensor (mono or stereo). Lidar is also implemented by @bmalhigh and config for it coming soon.

Lidar is not available yet?
