### ISSUE TITLE
Using XBOX one Controller with AirSim

### ISSUE THREAD

**Issue by shad7867** [Microsoft/AirSim#1437]
Hi
How do you get the maps such as CiryEnviron etc. working with XBOX one Controller.
I have the controller connected in to USB of my computer. I have reviewed other posts and they do not seem relevant.
When connected the car only turns one way or the other, no backwards or forwards.
Shad

**Comment by sytelus** [comment]
Try this out: https://github.com/Microsoft/AirSim/blob/a4fcf568e75b6d675d5d127754757d673ce33ecb/docs/xbox_controller.md

**Comment by shad7867** [comment]
thank you much, have what i need now
