### ISSUE TITLE
Airsim crashes when pressing PLAY using SITL mode

### ISSUE THREAD

**Issue by tklinterg** [Microsoft/AirSim#144]
Hi, I have a similar issue, but the difference is that I get the crashing when trying use the SITL mode (but it never gets this far).

When I hit the play button in the unreal game editor then Unreal stops wokring for some unknow reason.

The process stops working at line 247 in a xthtread file

![image](https://cloud.githubusercontent.com/assets/26778152/24682259/029831c0-1999-11e7-8252-3df82b195fa2.png)

Please let me know if more information is needed.

Best regards

**Comment by lovettchris** [comment]
Hopefully you are using Unreal 4.15.  Can you provide details about which operating system you are using, and which build script you used to build it?  For examploe, if you are on Linux we recommend you use clang 3.9...

**Comment by tklinterg** [comment]
Hi and thanks for the swift replay.
I'm currently trying to run the Airsim using a windows 10 OS. The Airsim is run through the Unreal 4.15 physics motor. I'm using the build scripts that is in the folder when downloading the git project under the build for Windows 10. Somehow I'm suspecting that the STIL PX4 flight controller is not communicating correctly with the unreal simulator.

Let me know if I can provide more information.

Thanks again for the patience and the help.

Best regards

**Comment by lovettchris** [comment]
I checked in some fixes that will check your SITL setup and report a new error if the Unreal app is not talking to SITL.  These are the settings you will need in ~/Documents/AirSim/settings.json:

{
  "Pixhawk": {
    "LocalHostIp": "127.0.0.1",
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "LogViewerSendPort": 14389,
    "Model": "Flamewheel",
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "SimCompID": 42,
    "SimSysID": 142,
    "SitlIp": "127.0.0.1",
    "SitlPort": 14556,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": false,
    "VehicleCompID": 1,
    "VehicleSysID": 135
  }
}

**Comment by a610402863** [comment]
I  can't  make "make posix_sitl_default",it shows " command not found",I don't  know  what   can  i   do?

**Comment by lovettchris** [comment]
See [PX4 development](https://github.com/Microsoft/AirSim/blob/master/docs/px4.md).

**Comment by tklinterg** [comment]
Hi chris 


Tried with the new settings file. Strange this is that when trying to hit the play button in the Unreal editor, the same error still remains. 

I still see that there seems to be no connection between the SITL mode in px4 and the Unreal engine, as px4 is still waiting for the required input from the engine (or vice versa)



![image](https://cloud.githubusercontent.com/assets/26778152/24884244/d1cf1ffe-1e48-11e7-93dc-9f1d0345d346.png)
.


I'm sorry to say, but I'm rather a noob in this area, is there a way to generate a more through report then the pictures that I'm attaching to further pin point the problem ? 


Thanks in advance. 


Best regards

**Comment by lovettchris** [comment]
Did you do step 6. of [SITL](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md) ?

namely: Now edit [settings file ](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md) with UdpIp address 127.0.0.1 and UdpPort 14560, set UseSerial to false and set SitlIp to 127.0.0.1 and SitlPort to 14556.

**Comment by lovettchris** [comment]
Also, did you get past the crash you reported at the beginning of this thread?

**Comment by tklinterg** [comment]
Hi Chris, 

Unfortunately I've not succeed in going pass the initial crash. The last step has also been included in the modification of the settings file. The crash happens in the exact same place that is in line 247 in the xthtread file.

Best regards

**Comment by lovettchris** [comment]
Since you are on Windows 10, can you try this [pre-built binary](https://1drv.ms/f/s!AoS-ymEfLuCLpeRlqa8O5GF0pzgjog)?
The see the "Cooked" folder for the pre-built executable.  Let me know if this works, or not, thanks.

**Comment by lovettchris** [comment]
I checked in a possible workaround for the crash.  See [commit 43baa4f](https://github.com/Microsoft/AirSim/commit/43baa4f8f514c09fd0b38ff484006d4d408daf74).
This disables the RPC server via settings.json.  This seems to to be a workaround for the crash.

**Comment by tklinterg** [comment]
Hi Chris,


I downloaded the new version of the project and the work around seems to
work. I'm now able to get the drone when hitting play as well as the small
communications messages in the bash command prompt.

Thank you so much for all the help.

Best regards

**Comment by lovettchris** [comment]
awesome, thanks for trying it.
