### ISSUE TITLE
Make drone smaller in Linux

### ISSUE THREAD

**Issue by Bill1235813** [Microsoft/AirSim#1440]
I want to make drone smaller in Linux so I changed parameters in SimpleFlightQuadX mentioned in #798.

``std::vector<real_T> arm_lengths(params.rotor_count, 0.002275f);``
``params.body_box.x() = 0.0018f; params.body_box.y() = 0.0011f; params.body_box.z() = 0.0004f;``

I scaled the parameters above and rebuilded airsim, but still the drone model looked the same size. I wonder how should I change the parameters to make it work?

**Comment by sytelus** [comment]
To make drone visually smaller you need to change mesh. Above will only change its physics parameters.

**Comment by Bill1235813** [comment]
Already fixed.
