### ISSUE TITLE
Increasing clockspeed

### ISSUE THREAD

**Issue by tvturnhout** [microsoft/AirSim#1447]
After some research I have read mixed results about speeding up the clockspeed of the drone simulation. Some say they get issues with clockspeed > 2 while @sytelus (https://github.com/Microsoft/AirSim/issues/901)  mentioned stable results simulating at 100X clockspeed. 

We seem to have mixed results when even slightly increasing clockspeed on powerful desktop machines. Would some of you mind to share their findings and maybe suggest a solution to speed things up while keeping simulation stable?

**Comment by sytelus** [comment]
How are you testing this? The clock speed setting seem to be working as expected.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
