### ISSUE TITLE
V1.2 bug

### ISSUE THREAD

**Issue by Zangpuzhuo** [Microsoft/AirSim#1450]
I want to try QGC&px4&AirSim to achieve Mission mode together, but the AirSim of V1.2 does not have GPS  information（GPS value is not updated）. And the Altitude-rel in QGC is different in AirSim.Please tell me how to do it.

**Comment by sytelus** [comment]
This is very likely related to this: https://github.com/Microsoft/AirSim/pull/1387/files#diff-ccb74b14ff5d8ec7eac93c765826556bR105

**Comment by Zangpuzhuo** [comment]
ok，thanks
