### ISSUE TITLE
Manipulating characterObject (PhysX car) from within UE4

### ISSUE THREAD

**Issue by baaaze** [Microsoft/AirSim#1451]
Hey,

I've been looking around for a while and I can't seem to find how I can call the character object (The PhysX car). I want to be able to manipulate it to follow a spline when ordered, in order to fake Autonomous driving. Appreciate all the insights I can get!

Thank you!

**Comment by hesham-akmal** [comment]
Have you tried opening "AirSimAssets" in the "Content Broswer" and selecting "Edit SuvCarPawn" in the "World Outliner"

**Comment by baaaze** [comment]
> Have you tried opening "AirSimAssets" from the "Content Browser" and selecting "Edit SuvCarPawn" from the "World Outliner"

That would be awesome! :-) But I can't even see that. All I have is Assets and Maps from the standard Landscape Mountain stuff. Do I need to manually import the Airsim asset aside from loading the plugin?

**Comment by hesham-akmal** [comment]
oh I assumed you're on the Blocks level. Okay try this, in the "View Options" in the Content Browser, there's an option to show plugin content, check it, you'll be able to navigate to the plugin content.

**Comment by baaaze** [comment]
> oh I assumed you're on the Blocks level. Okay try this, in the "View Options" in the Content Browser, there's an option to show plugin content, check it, you'll be able to navigate to the plugin content.

Dude! You are awesome! Thank you for saving me from tons of headaches!

**Comment by hesham-akmal** [comment]
Anytime! Good luck with your project

**Comment by sytelus** [comment]
If you want a fake car to follow spine, you can just do some bluescripting in UE on a car mesh. You can't control PhysX based car to follow spine precisely.
