### ISSUE TITLE
Airsim RPC in UE4

### ISSUE THREAD

**Issue by hesham-akmal** [microsoft/AirSim#1452]
I want to use Airsim RPC in a blueprint, if that's possible, to send info to the python client / create new functions to be called by the client. I've taken a look at the c++ classes and it's not easy.
I'm fairly new to UE4 but not to game engines. Thanks for reading.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
