### ISSUE TITLE
GIS data with Unreal Terraform plugin and Airsim?

### ISSUE THREAD

**Issue by abe-mart** [microsoft/AirSim#1458]
I just came across this neat plugin called TerraForm that lets you bring georeferenced GIS data in to Unreal to replicate real environments.  It seems like it would be an ideal companion to AirSim for simulating in real-world locations.   However, I'm not sure if it would break some of the pseudo-GPS things AirSim has going on.  Has anyone tried this yet?

https://terraformpro.com/tools/

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
