### ISSUE TITLE
import OpenDrive HDMap into UE4?

### ISSUE THREAD

**Issue by hdy117** [microsoft/AirSim#1459]
Brilliant work.
In autonomous driving car, a HDMap is needed. Now OpenDrive format hdmap is popular. can you write a tools, so we can import opendrive format map into UE4.
Again, thank you for your work

**Comment by ThrashAbaddon** [comment]
@hdy117 Hi, what do you mean when you say HDMap? OpenDrive is just a xml description of road network as far as I know.

**Comment by hdy117** [comment]
company uses opendrive to describe road network in their autonomous driving car system, for planning, localization etc.
