### ISSUE TITLE
Airsim with Bluetooth

### ISSUE THREAD

**Issue by quddnr7201** [Microsoft/AirSim#1460]
Hi, I'm new to Airsim and I want to build a program to control quadcopter using bluetooth serial.
Is it possible connect Airsim with bluetooth serial? Are there any documents I can refer to?

**Comment by sytelus** [comment]
Currently, no. We support PX4 and ArduPilot over MavLink.

**Comment by quddnr7201** [comment]
Thx

**Comment by Yurail** [comment]
Ah quddnr7201 is my team .
And our team solve this problem by using putty to detour data flow.
Bluetooth(PC) > Putty > Server > Anaconda > Airsim
(You can replace server as txt file.)

**Comment by Yurail** [comment]
> Thx

너 thanks 치기 귀찮아서 3글자 친거지...
