### ISSUE TITLE
Blocks Build Error building failes

### ISSUE THREAD

**Issue by juanjuanfire** [Microsoft/AirSim#1461]
Whille trying to open block i get an error saying that libUE4Editor-Blocks.so is missing and so is the libUE4Editor-AirSim.so 

Here is my console log
Running Mono...

~/UnrealEngine/Engine ~/UnrealEngine
Using 'git status' to determine working set for adaptive non-unity build.
@progress push 5%
@progress 'Generating code...' 0%
@progress 'Generating code...' 67%
@progress 'Generating code...' 100%
@progress pop
Performing 4 actions (4 in parallel)
@progress 'Compiling C++ source code...' 0%
[2/4] Compile Module.AirSim.cpp
[1/4] Compile Module.AirSim.gen.cpp
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.gen.cpp:6:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AirSim/CameraDirector.gen.cpp:8:
In file included from ../../../AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/CameraDirector.h:4:
In file included from ../../../AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/PawnSimApi.h:18:
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api/VehicleApiBase.hpp:89:29: error: 
      default initialization of an object of const type 'const
      msr::airlib::RCData' without a user-provided default constructor
        static const RCData invalid_rc_data;
                            ^
                                           {}
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:4:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/src/api/RpcLibServerBase.cpp:10:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api/RpcLibServerBase.hpp:9:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api/ApiProvider.hpp:7:
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/api/VehicleApiBase.hpp:89:29: error: 
      default initialization of an object of const type 'const
      msr::airlib::RCData' without a user-provided default constructor
        static const RCData invalid_rc_data;
                            ^
                                           {}
1 error generated.
@progress 'Compiling C++ source code...' 20%
@progress 'Compiling C++ source code...' 40%
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:2:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp:4:
In file included from ../../../AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.h:20:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/AirSimSettings.hpp:12:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/CommonStructs.hpp:7:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/Common.hpp:16:
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/VectorMath.hpp:188:46: error: 
      conditional expression is ambiguous; 'const Quaternion<[...], 2>' can
      be converted to 'Quaternion<[...], (default) AutoAlign aka 0>' and
      vice versa
        QuaternionT ref_n = assume_unit_quat ? ref : ref.normalized();
                                             ^ ~~~   ~~~~~~~~~~~~~~~~
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.cpp:110:52: note: 
      in instantiation of member function
      'msr::airlib::VectorMathT<Eigen::Matrix<float, 3, 1, 0, 3, 1>,
      Eigen::Quaternion<float, 2>, float>::rotateQuaternion' requested here
    msr::airlib::Quaternionr ray_q_b = VectorMath::rotateQuaternion(ray_...
                                                   ^
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:2:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp:4:
In file included from ../../../AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.h:20:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/AirSimSettings.hpp:11:
In file included from /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/Settings.hpp:7:
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/common_utils//Utils.hpp:138:20: error: 
      returning reference to local temporary object
      [-Werror,-Wreturn-stack-address]
            return default_val;
                   ^~~~~~~~~~~
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/WorldSimApi.cpp:204:36: note: 
      in instantiation of function template specialization
      'common_utils::Utils::findOrDefault<map, std::__1::basic_string<char>,
      AAirSimCharacter *, std::__1::less<std::__1::basic_string<char> >,
      std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>,
      AAirSimCharacter *> > >' requested here
            : common_utils::Utils::findOrDefault(chars_, character_name);
                                   ^
/home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/common_utils//Utils.hpp:134:109: note: 
      binding reference variable 'default_val' here
  ...TVal, Args...>& m, TKey const& key, const TVal& default_val = TVal())
                                                     ^             ~~~~~~
3 errors generated.
@progress 'Compiling C++ source code...' 80%
ERROR: UBT ERROR: Failed to produce item: /home/juan/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so
Total build time: 112.27 seconds (Local executor: 0.00 seconds)
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/UObjectPlugin/Binaries/Linux/libUE4Editor-UObjectPlugin.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/PerforceSourceControl/Binaries/Linux/libUE4Editor-PerforceSourceControl.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/VisualStudioCodeSourceCodeAccess/Binaries/Linux/libUE4Editor-VisualStudioCodeSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/GitSourceControl/Binaries/Linux/libUE4Editor-GitSourceControl.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/CodeLiteSourceCodeAccess/Binaries/Linux/libUE4Editor-CodeLiteSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/KDevelopSourceCodeAccess/Binaries/Linux/libUE4Editor-KDevelopSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/NullSourceCodeAccess/Binaries/Linux/libUE4Editor-NullSourceCodeAccess.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Developer/SubversionSourceControl/Binaries/Linux/libUE4Editor-SubversionSourceControl.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/MovieScene/LevelSequenceEditor/Binaries/Linux/libUE4Editor-LevelSequenceEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/MovieScene/ActorSequence/Binaries/Linux/libUE4Editor-ActorSequence.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/MovieScene/MatineeToLevelSequence/Binaries/Linux/libUE4Editor-MatineeToLevelSequence.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/PluginBrowser/Binaries/Linux/libUE4Editor-PluginBrowser.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/SpeedTreeImporter/Binaries/Linux/libUE4Editor-SpeedTreeImporter.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/MobileLauncherProfileWizard/Binaries/Linux/libUE4Editor-MobileLauncherProfileWizard.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/FacialAnimation/Binaries/Linux/libUE4Editor-FacialAnimation.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/FacialAnimation/Binaries/Linux/libUE4Editor-FacialAnimationEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/AssetManagerEditor/Binaries/Linux/libUE4Editor-AssetManagerEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Editor/GameplayTagsEditor/Binaries/Linux/libUE4Editor-GameplayTagsEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Blendables/LightPropagationVolume/Binaries/Linux/libUE4Editor-LightPropagationVolumeRuntime.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Blendables/LightPropagationVolume/Binaries/Linux/libUE4Editor-LightPropagationVolumeEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Experimental/CharacterAI/Binaries/Linux/libUE4Editor-CharacterAI.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/ImgMedia/Binaries/Linux/libUE4Editor-ImgMedia.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/ImgMedia/Binaries/Linux/libUE4Editor-ImgMediaEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/ImgMedia/Binaries/Linux/libUE4Editor-ImgMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/ImgMedia/Binaries/Linux/libUE4Editor-ImgMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/MediaPlayerEditor/Binaries/Linux/libUE4Editor-MediaPlayerEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/WmfMedia/Binaries/Linux/libUE4Editor-WmfMediaEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/WmfMedia/Binaries/Linux/libUE4Editor-WmfMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/WmfMedia/Binaries/Linux/libUE4Editor-WmfMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/MediaCompositing/Binaries/Linux/libUE4Editor-MediaCompositing.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/MediaCompositing/Binaries/Linux/libUE4Editor-MediaCompositingEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/AndroidMedia/Binaries/Linux/libUE4Editor-AndroidMediaEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/AndroidMedia/Binaries/Linux/libUE4Editor-AndroidMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/AvfMedia/Binaries/Linux/libUE4Editor-AvfMediaEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/AvfMedia/Binaries/Linux/libUE4Editor-AvfMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Media/AvfMedia/Binaries/Linux/libUE4Editor-AvfMediaFactory.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/RuntimePhysXCooking/Binaries/Linux/libUE4Editor-RuntimePhysXCooking.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/LinuxDeviceProfileSelector/Binaries/Linux/libUE4Editor-LinuxDeviceProfileSelector.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/AndroidDeviceProfileSelector/Binaries/Linux/libUE4Editor-AndroidDeviceProfileSelector.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ProceduralMeshComponent/Binaries/Linux/libUE4Editor-ProceduralMeshComponent.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ProceduralMeshComponent/Binaries/Linux/libUE4Editor-ProceduralMeshComponentEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/PhysXVehicles/Binaries/Linux/libUE4Editor-PhysXVehicles.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/PhysXVehicles/Binaries/Linux/libUE4Editor-PhysXVehiclesEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/CableComponent/Binaries/Linux/libUE4Editor-CableComponent.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/MobilePatchingUtils/Binaries/Linux/libUE4Editor-MobilePatchingUtils.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ExampleDeviceProfileSelector/Binaries/Linux/libUE4Editor-ExampleDeviceProfileSelector.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/CustomMeshComponent/Binaries/Linux/libUE4Editor-CustomMeshComponent.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/AndroidPermission/Binaries/Linux/libUE4Editor-AndroidPermission.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ArchVisCharacter/Binaries/Linux/libUE4Editor-ArchVisCharacter.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/Steam/SteamVR/Binaries/Linux/libUE4Editor-SteamVR.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/Steam/SteamVR/Binaries/Linux/libUE4Editor-SteamVRController.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ImmediatePhysics/Binaries/Linux/libUE4Editor-ImmediatePhysics.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/ImmediatePhysics/Binaries/Linux/libUE4Editor-ImmediatePhysicsEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Runtime/LocationServicesBPLibrary/Binaries/Linux/libUE4Editor-LocationServicesBPLibrary.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Messaging/TcpMessaging/Binaries/Linux/libUE4Editor-TcpMessaging.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Messaging/UdpMessaging/Binaries/Linux/libUE4Editor-UdpMessaging.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Online/OnlineSubsystem/Binaries/Linux/libUE4Editor-OnlineSubsystem.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Online/OnlineSubsystemNull/Binaries/Linux/libUE4Editor-OnlineSubsystemNull.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Online/OnlineSubsystemUtils/Binaries/Linux/libUE4Editor-OnlineSubsystemUtils.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/Online/OnlineSubsystemUtils/Binaries/Linux/libUE4Editor-OnlineBlueprintSupport.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/2D/Paper2D/Binaries/Linux/libUE4Editor-Paper2D.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/2D/Paper2D/Binaries/Linux/libUE4Editor-Paper2DEditor.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/2D/Paper2D/Binaries/Linux/libUE4Editor-PaperSpriteSheetImporter.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/2D/Paper2D/Binaries/Linux/libUE4Editor-PaperTiledImporter.so (API version 0).
LogModuleManager: Display: Found up-to-date module file ../../../Engine/Plugins/2D/Paper2D/Binaries/Linux/libUE4Editor-SmartSnapping.so (API version 0).
LogInit: Warning: Still incompatible or missing module: libUE4Editor-Blocks.so
LogInit: Warning: Still incompatible or missing module: libUE4Editor-AirSim.so

**Comment by deksprime** [comment]
Having the same problem while building

```
In file included from /home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:2:
In file included from /home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp:4:
In file included from ../../../AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.h:20:
In file included from /home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/AirSimSettings.hpp:12:
In file included from /home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/CommonStructs.hpp:7:
In file included from /home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/Common.hpp:16:
/home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/VectorMath.hpp:188:46: error: 
      conditional expression is ambiguous; 'const Quaternion<[...], 2>' can
      be converted to 'Quaternion<[...], (default) AutoAlign aka 0>' and
      vice versa
        QuaternionT ref_n = assume_unit_quat ? ref : ref.normalized();
                                             ^ ~~~   ~~~~~~~~~~~~~~~~
/home/x/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/UnrealSensors/UnrealLidarSensor.cpp:110:52: note: 
      in instantiation of member function
      'msr::airlib::VectorMathT<Eigen::Matrix<float, 3, 1, 0, 3, 1>,
      Eigen::Quaternion<float, 2>, float>::rotateQuaternion' requested here
    msr::airlib::Quaternionr ray_q_b = VectorMath::rotateQuaternion(ray_...
                                                   ^
1 error generated.
```

Anyone?

**Comment by ChanganVR** [comment]
I met the same problem...

**Comment by BrunoXL** [comment]
Me too, did anyone found a solution?

**Comment by ChanganVR** [comment]
Rewriting the code as below could temporarily fix the issue.
`        QuaternionT ref_n, ref_n_i;
    	if (assume_unit_quat) {
	    ref_n = ref;
            ref_n_i =  ref.conjugate();
		}
    	else{
            ref_n = ref.normalized();
            ref_n_i =  ref.inverse();
        }
//        QuaternionT ref_n = assume_unit_quat ? ref : ref.normalized();
//        QuaternionT ref_n_i = assume_unit_quat ? ref.conjugate() : ref.inverse();`

**Comment by ivannson** [comment]
@ChanganVR which file is this code in?

**Comment by ChanganVR** [comment]
@ivannson The file is AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/common/VectorMath.hpp

**Comment by sytelus** [comment]
This change is now merged to master.
