### ISSUE TITLE
plugin folder path error

### ISSUE THREAD

**Issue by hdy117** [Microsoft/AirSim#1462]
1. liadr sensor folder:
~/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/sensors/lidar
2. but in UnrealLidarSensor.h, at line 4. it is using 

#include "sensors/Lidar/LidarSimple.hpp"

should be changed to 

#include "sensors/lidar/LidarSimple.hpp"

ie: lidar not Lidar

**Comment by bmalhigh** [comment]
This has been fixed with https://github.com/Microsoft/AirSim/pull/1454 

Thanks.
