### ISSUE TITLE
How to modify the position of the camera

### ISSUE THREAD

**Issue by liyisecond339** [microsoft/AirSim#1467]
Hi:
I used the recording feature to get all of the camera image of the vehicle. the environment i used is 
"Warehouse", below is my config in setting.json
{
  "SettingsVersion": 1.2,
  "SimMode": "",
  "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 0.05,
    "Cameras": [
      {
        "CameraName": "front_center",
        "Compress": true,
        "ImageType": 0,
        "PixelsAsFloat": false
      },
      {
        "CameraName": "front_right",
        "Compress": true,
        "ImageType": 0,
        "PixelsAsFloat": false
      },
      {
        "CameraName": "front_left",
        "Compress": true,
        "ImageType": 0,
        "PixelsAsFloat": false
      },
      {
        "CameraName": "fpv",
        "Compress": true,
        "ImageType": 0,
        "PixelsAsFloat": false
      },
      {
        "CameraName": "back_center",
        "Compress": true,
        "ImageType": 0,
        "PixelsAsFloat": false
      }
    ]
  }
}
The picture i got like below:
front_left:
![image](https://user-images.githubusercontent.com/11594848/47005452-61a6f080-d166-11e8-9af5-b75f39779818.png)
front_right:
![image](https://user-images.githubusercontent.com/11594848/47005463-67043b00-d166-11e8-8519-2a50bf3bfcaa.png)

my question is, from the image, the left and right image is quite same, it is possible to change the cameras directions?

another question is, it is possible to get the frame at the same time? the time stamp is nano seconds？

**Comment by sytelus** [comment]
Looks like you are old version of settings.json schema. In AirSim V1.2, the "Cameras" section is moved under "Vehicles".

**Comment by liyisecond339** [comment]
thanks a lot!
you mean is like below?
  "Vehicles": {
    "SimpleFlight": {
      "VehicleType": "SimpleFlight",
      "DefaultVehicleState": "Armed",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "AllowAPIAlways": true,
      "RC": {
        "RemoteControlID": 0,
        "AllowAPIWhenDisconnected": false
      },
      **"Cameras": {   
        //same elements as CameraDefaults above, key as name
      },**
}
as my understanding the define will cover the CameraDefaults settings. but in the CameraDefualts element i did not find the where to define the camera`s direction.

**Comment by RVBldr** [comment]
@liyisecond339 Is this issue resolved?

**Comment by orangelx** [comment]
"Vehicles": {
    "Drone1": {
      "VehicleType": "SimpleFlight",
      "Cameras": {
        "MyCamera1": {
          "CaptureSettings": [
            {
              "ImageType": 0,
              "Width": 640,
              "Height": 320,
              "FOV_Degrees": 100
            }
          ],
          "X": -0.1,
          "Y": 0,
          "Z": -0.4,
          "Pitch": 0,
          "Roll": 0,
          "Yaw": 0
        }
}
      "X": 0,
      "Y": 0,
      "Z": 0,
      "Pitch": 0,
      "Roll": 0,
      "Yaw": 0
}
}

**Comment by jonyMarino** [comment]
@orangelx did you reproduce the issue with that values?
