### ISSUE TITLE
PX4 SITKL build eror

### ISSUE THREAD

**Issue by liyisecond339** [Microsoft/AirSim#1474]
Hi:
I try to use PX4 SITL, the step is flow the doc "px4_build.md".
when I run the command: sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
got the error information like below:
  Connection failed [IP: 91.189.91.23 80]
Get:22 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 manpages-dev all 4.15-1 [2,217 kB]
Get:22 http://us.archive.ubuntu.com/ubuntu bionic/main amd64 manpages-dev all 4.15-1 [2,217 kB]
Fetched 18.3 MB in 6min 25s (47.5 kB/s)                                       
E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dev_2.27-3ubuntu1_amd64.deb  Connection failed [IP: 91.189.91.23 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

what should I do?

**Comment by lovettchris** [comment]
Assuming you are on Ubuntu 16 or 18 you could do this to get latest version of cmake:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get -y update
sudo apt-get install cmake
```
