### ISSUE TITLE
Blueprint method or API document

### ISSUE THREAD

**Issue by Yurail** [Microsoft/AirSim#1476]
I want to fix view point of user(who control the drone in airsim).

Is there any docs for explaining Blueprint function? or example code?
(I saw below link, but this file has no explanation of blueprint. or can't find or can't understand)
https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/CameraDirector.cpp

(If not I think I have to set every blueprint in environment using Unreal program)

**Comment by RVBldr** [comment]
@Yurail Have you found an answer to your issue? If not, can you add detail to the issue? What are you trying to accomplish? Change the AirSim blueprint in your own environment?
