### ISSUE TITLE
Error compiling uproject on Win10

### ISSUE THREAD

**Issue by sufhy** [Microsoft/AirSim#1482]
When I compiling the demo project by VS2017,it occured:

1>Demo.cpp
1>MyClass.cpp
1>[8/11] Link UE4Editor-Demo-3110-Win64-DebugGame.lib
1>  Creating library D:\EPIC\Unreal Projects\LandScape\Demo\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Demo-3110-Win64-DebugGame.lib and object D:\EPIC\Unreal Projects\LandScape\Demo\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-Demo-3110-Win64-DebugGame.exp
1>D:\EPIC\Unreal Projects\LandScape\Demo\Plugins\AirSim\Source\AirLib\include\vehicles/multirotor/firmwares/mavlink/MavLinkMultirotorApi.hpp(7): fatal error C1083: Unable to open include file: “MavLinkVehicle.hpp”: No such file or directory
1>ERROR : UBT error : Failed to produce item: D:\EPIC\Unreal Projects\LandScape\Demo\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\DebugGame\UE4Editor-AirSim-4617-Win64-DebugGame.lib
1>Total build time: 45.65 seconds (Local executor: 0.00 seconds)
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: 命令“"D:\EPIC\Epic Games\UE_4.18\Engine\Build\BatchFiles\Build.bat" DemoEditor Win64 DebugGame "D:\EPIC\Unreal Projects\LandScape\Demo\Demo.uproject" -waitmutex”Have withdrawn，code is 5.
Please verify that you have sufficient permission to run this command.
1>Completed generation project“Demo.vcxproj”'sOperation - failed。
========== Generation: 0 success, 1 failures, the latest 0, skipping 0.==========

How to deal with this ? Thanks a lot!

**Comment by madratman** [comment]
Hi. not sure if you were able to resolve this already, but did you run `AirSim\Unreal\Environments\Blocks\update_from_git.bat`?
