### ISSUE TITLE
Is it possible to add custom objects to the environment such as traffic cones?

### ISSUE THREAD

**Issue by bsridatta** [Microsoft/AirSim#1486]
Is it possible to add custom objects to the environment such as traffic cones?

**Comment by TritonSailor** [comment]
Yes, in the editor, if you get the downtown environment it already has traffic cones.  You can move them wherever you want in the editor, or spawn them with blueprints, or use the traffic cone meshes in another environment.  

You can also change the collision to physics actors and  traffic cones will bounce properly off the vehicle if you adjust the physical material settings.

**Comment by bsridatta** [comment]
Awesome!  thanks :)
