### ISSUE TITLE
How the map or scene is defined

### ISSUE THREAD

**Issue by wmpang** [microsoft/AirSim#1497]
I wonder how AirSim defines the map or scene? If training process is incorporated, we need to know whether our vehicle is navigated correctly or not (e.g. whether on the lane, or whether is hit something). Or everything are relied on the Unreal Engine? 
Moreover, how about dynamic objects? Are dynamic objects supported in AirSim?

**Comment by GuangTongLiu1** [comment]
As far as I know , UE4 cannot support to import map.So we cannot get the information of car in the road (e.g., which lane the car is in).
I am also confused how to use dynamic object to train my own car algorithm.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
