### ISSUE TITLE
cannot update airsim by VS 2017 community 

### ISSUE THREAD

**Issue by GuangTongLiu1** [Microsoft/AirSim#1502]
Hi, when I want to update Airsim by VS 2017 community, a message pop up(look at the following picture).
what all i have down is to press button "pull". Is anything wrong here ? what should i do to update Airsim ?
Thanks a lot.
![error](https://user-images.githubusercontent.com/43978497/47612270-53d06400-dab2-11e8-93d1-437a5661f8fa.png)

**Comment by thias15** [comment]
You made changes. Therefore you need to commit first so GitHub can merge when you pull.

**Comment by GuangTongLiu1** [comment]
I have fixed it according to what you said！ Thanks！
