### ISSUE TITLE
[Landscape Mountains env] BP_Sky_sphere was not found?

### ISSUE THREAD

**Issue by lhlong** [microsoft/AirSim#1508]
When I enable TimeOfDay on settings.json. Landscape Mountains Environment (https://github.com/Microsoft/AirSim/releases/download/v1.2.0/LandscapeMountains.zip) ignored it.
And I see the red error: "BP_Sky_sphere was not found."
![image](https://user-images.githubusercontent.com/4710986/47765826-6d65eb80-dcfe-11e8-9cf2-2d7777a89d1c.png)

Anyone had same problem? 
Wait for add the BP_Sky_sphere on .uproject Unreal.

**Comment by madratman** [comment]
This is more of an unreal issue than an airsim issue. 
Can you try what the following link suggests and get back? 
https://answers.unrealengine.com/questions/301170/bp-sky-shpere-not-found.html

**Comment by lhlong** [comment]
> This is more of an unreal issue than an airsim issue.
> Can you try what the following link suggests and get back?
> https://answers.unrealengine.com/questions/301170/bp-sky-shpere-not-found.html

@madratman I see that, but we can not open Landscape Mountains env in unreal engine. We don't have *.uproject file.

**Comment by RVBldr** [comment]
Internal VSTF 7694

**Comment by lhlong** [comment]
> Internal VSTF 7694

Sorry @RVBIdr, what do you mean?

**Comment by RVBldr** [comment]
That's our internal tracking number for visual studio.

**Comment by madratman** [comment]
@bmalhigh any ideas?

**Comment by Fardad92** [comment]
Hi there,

I've just found out that this problem is related to the [Landscape Mountains env] only. I had this problem with it, and then once I tested the cityenv, I didn't see any error and TimeOfDay parameters worked well.
