### ISSUE TITLE
Engine crash after press the play button in Ubuntu system

### ISSUE THREAD

**Issue by qhl722** [Microsoft/AirSim#151]
Hi,

I have successfully integrated the Airsim plugin. The project starts normally and I can change the mode into simGamemode by Airsim. However, engine crashed after press the Play button. My system is ubuntu 16.04. Any suggestion is welcomed.

![screenshot from 2017-04-09 18-23-51](https://cloud.githubusercontent.com/assets/6612741/24836607/b6395e62-1ce5-11e7-89a1-5ee717d3be00.png)

**Comment by AlexandreBorowczyk** [comment]
We we are having the same issue, we are discussing it in https://github.com/Microsoft/AirSim/issues/112

**Comment by lovettchris** [comment]
closing old issue, please reopen if you are still seeing crashes.
