### ISSUE TITLE
No lidar with name LidarSensor1 exist on vehicle.

### ISSUE THREAD

**Issue by oppne** [Microsoft/AirSim#1518]
Hi, been trying to use python for starting lidar and use it, but as it seems i get this error code

`RPCError                                  Traceback (most recent call last)
<ipython-input-26-8acd3dc7a6bb> in <module>()
----> 1 d = client.getLidarData(lidar_name="LidarSensor1", vehicle_name= "Drone1")
      2 print(len(d.point_cloud))

~\Anaconda3\lib\site-packages\airsim\client.py in getLidarData(self, lidar_name, vehicle_name)
    133     # lidar APIs
    134     def getLidarData(self, lidar_name = '', vehicle_name = ''):
--> 135         return LidarData.from_msgpack(self.client.call('getLidarData', lidar_name, vehicle_name))
    136 
    137     #----------- APIs to control ACharacter in scene ----------/

~\Anaconda3\lib\site-packages\msgpackrpc\session.py in call(self, method, *args)
     39 
     40     def call(self, method, *args):
---> 41         return self.send_request(method, args).get()
     42 
     43     def call_async(self, method, *args):

~\Anaconda3\lib\site-packages\msgpackrpc\future.py in get(self)
     43                         raise self._error
     44                     else:
---> 45                         raise error.RPCError(self._error)
     46             else:
     47                 return self._result

RPCError: rpclib: function 'getLidarData' (called with 2 arg(s)) threw an exception. The exception contained this information: No lidar with name LidarSensor1 exist on vehicle.`

And my settings.json looks like this

`{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "Vehicles": {

    "Drone1": {
      "VehicleType": "Simpleflight",
      "AutoCreate": true,
      "Sensors": {
        "LidarSensor1": {
          "SensorType": 6,
          "Enabled": true,
          "NumberOfChannels": 16,
          "PointsPerSecond": 10000,
          "X": 0,
          "Y": 0,
          "Z": -1,
          "DrawDebugPoints": true
        },
        "MyLidar2": {
          "SensorType": 6,
          "Enabled": true,
          "NumberOfChannels": 4,
          "PointsPerSecond": 10000,
          "X": 0,
          "Y": 0,
          "Z": -1,
          "DrawDebugPoints": true
        }
      }
    }
  }
}`

**Comment by oppne** [comment]
We did logmessage with number of sensors from the UAirblueprintlib to the find number of lidars on the drone, and we get an output = 0 from count_lidars

**Comment by bmalhigh** [comment]
Investigating.

**Comment by dahewujiang** [comment]
Is there any project with lidar running normally?

**Comment by bmalhigh** [comment]
I am unable to repro this. I copied the exact settings that is referred above and couldn't repro the issue.

@oppne -- are you sure you have the updated plugin bits in your project? My suspicion is that the plug-ins bits you are using are old and those are not reading the sensor list from the settings json.

Meanwhile, I will see somebody in my team can repro this issue.

**Comment by bmalhigh** [comment]
Mahir, the base lidar functionality was added first and then the config support was added later (and some more changes in lidar will be coming soon).

If you pulled source-code from git and you are trying to use some new functionality, you would need to make sure that the plugs-in inside your uprojects are updated with what you pulled and built on your machine.

For lidar, in the short-term, I would recommend keeping the plugs-in updated as we fix reported issues.

**Comment by oppne** [comment]
I updated the project, found out some of the sensor and camera settings were outdated, now it works like a charm! :)
