### ISSUE TITLE
Can i move the Drone without Drone Server?

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/AirSim#152]
Hello: 
      My project is to use reinforcement learning to find an optimal action for the Drone in game..
      I am not familiar with the Unreal Engine... So..is that possible to get (pos)  directly from engine?
      and can i just send command to the drone directly through a simple program?

**Comment by lovettchris** [comment]
[HelloDrone ](https://github.com/Microsoft/AirSim/tree/master/HelloDrone) gives you an example of what you can do in a simple program.
