### ISSUE TITLE
is there a plan to develop ultrasonic sensor and millimeter-wave radar?

### ISSUE THREAD

**Issue by dahewujiang** [Microsoft/AirSim#1523]
hi, i think that the types of sensor model in airsim is too less to develop algorithms for auto driving. I think the ultrasonic sensor and millimeter-wave radar is necessary.But it too complex for me to model sensor. is there any plan to develop those sensors ?

**Comment by Cocco17** [comment]
+1

**Comment by RVBldr** [comment]
We'll add that to our internal feature list.

**Comment by flynneva** [comment]
was this completed already?

**Comment by JuanshuB2** [comment]
Hi! I think it is interesting to mention this project to simulate a FMCW radar in Unity. It generates the raw data that can be further processed:  https://github.com/chstetco/virtualradar. However, it is not available in Unreal Engine, so I am wondering how challenging can it be.
