### ISSUE TITLE
Get annotation images

### ISSUE THREAD

**Issue by Maxfashko** [Microsoft/AirSim#153]
Hello!
How can I get annotated images? What steps should I take to set up the annotation camera?

**Comment by lovettchris** [comment]
Do you want ground truth, or are you looking to test an image recognition engine?  There is currently no built in support for automatic annotation.  One idea is to take the images produced by AirSim and send them to your favorite image recognition service, like the [Microsoft computer vision api](https://www.microsoft.com/cognitive-services/en-us/computer-vision-api), which finds what is in the image like this:

![image](https://cloud.githubusercontent.com/assets/18707114/24883358/62fa2564-1df9-11e7-8a26-f6ca67d9d6eb.png)

or if you like the google vision api:

![image](https://cloud.githubusercontent.com/assets/18707114/24883415/a28f981c-1df9-11e7-911a-82083858e011.png)

**Comment by Maxfashko** [comment]
#lovettchris, Microsoft computer vision api оnly provides a text label for the class. I need segmentation images

**Comment by sytelus** [comment]
Here's some background on how ground truth segmentation in AirSim works. Each environment in Unreal contains lots of meshes representing objects in that environment like car, houses, trees etc. We assign each mesh in Unreal environment is assigned value from 0 to 255 and that value is mapped to some color. If you want to focus on certain objects like trees, you can assign specific integer value for those meshes. Right now, by default we just assign random values to each mesh. To change this, currently you have to change code. In future, we will enable API for this task. Below are some details on how to do this.

These 0-255 number assigned to each mesh is called stencil IDs. The code for setting stencil IDs is in FlyingPawn.cpp in function `AFlyingPawn::setStencilIDs`. If you look at this 10 lines of code, what it does is to find all the components in the environment and then assign a random 0-255 stencil ID. Now lets say you if you are interested only in trees and you want to paint them as red. Then one way to achieve this is just remove the code in `AFlyingPawn::setStencilIDs` (i.e. make it empty function. Then go to Unreal editor and search for tree in World Outliner. You will 28 different types of trees available there. You can select the one that interests you and then go to Details tab, Rendering section, enable "Render CustomDepth Pass" and set "CustomDepth Stencil Value" to say 1. Below is the screenshot:

![image](https://cloud.githubusercontent.com/assets/2096835/25195826/a66b44a8-24f3-11e7-9479-86eec472e818.png)

**Comment by Maxfashko** [comment]
Hi, @sytelus. Was it developed api for this procedure?

**Comment by abhay-venkatesh** [comment]
FlyingPawn.cpp is now gone from the unreal/plugins folder? 

Furthermore, on building the plugins from scratch, I cannot get any segmentation at all, I get a blank image.

**Comment by sytelus** [comment]
There has been lots of refactoring. FlyingPwn got moved in vehicles/multirotor folder. If you get latest, rebuild things should work fine. If you see issue, delete your settings.json as it might have some bad settings.

**Comment by wujiyoung** [comment]
@sytelus Is it able to access the segmentation label in the latest releases CityEnviron (for example) ? I can archive a segmentation image by `ImageRequest(0, ImageType::Segmentation)`, but I can not define the label class of it.

**Comment by PatrickUtz** [comment]
@sytelus, does this imply that you can only label a max of 255 meshes/objects per frame?
