### ISSUE TITLE
How to record image depth (not normailzed and clipped) using airsim?

### ISSUE THREAD

**Issue by Bill1235813** [microsoft/AirSim#1531]
As you mentioned in #459, the DepthPerspective and DepthPlanner Mode is used to request floating point image. Later I find the value of floating point depth image is from 0 to 1, I am not sure if it is clipped or normalized? How can we get the real depth of the image using airsim Python API?

**Comment by gbusillo** [comment]
@Bill1235813  Did you find a solution to this? Is there a preferred method?

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
