### ISSUE TITLE
how to interpret the response from imagetype = depthperspective

### ISSUE THREAD

**Issue by husha1993** [microsoft/AirSim#1533]
I want to obtain the real distance between camera and  a projection ray that hits that pixel.,
thus I need the response from :  
responses = airsim_client.simGetImages([
    airsim.ImageRequest("0", airsim.ImageType.DepthPerspective, pixels_as_float = True)
    ])
The data from this api are seems all normalized to 0-1, but I cannot find any documents about the post processing parameters and method.

**Comment by madratman** [comment]
I think you're looking for [this part](https://github.com/Microsoft/AirSim/blob/42d4d91e7a7a7f037036c98c31b7537989f2a6e6/docs/image_apis.md#what-does-pixel-values-mean-in-different-image-types). 
This can be found if you search for `DepthPerspective` in the github search bar at the top

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
