### ISSUE TITLE
Multiple drones in AirSim Unity?

### ISSUE THREAD

**Issue by yashkaushal** [microsoft/AirSim#1540]
Hi,

Does Unity AirSim beta support multiple drones? 
I tried settings.json for multiple drones and got error window saying `Problem in starting AirSim server - please check logs for more information`

I checked the logs and this looked like the reason: `Error at startup:  VehicleSetting for vehicle name SimpleFlight was requested but not found Vehicle=SimpleFlight`

Below is the complete log file.
[Editor log.zip](https://github.com/Microsoft/AirSim/files/2580751/Editor.log.zip)

Thanks,
Yash Kaushal

**Comment by josedeo** [comment]
Hi Yash
Thanks for raising this point! 
AirSim on Unity doesn't support multiple drones in its current implementation. 
Please consider contributing on this feature! We'd love some community help!
Thanks!
--- Jose

**Comment by MelSoS** [comment]
Is this still an issue, or is there already a solution to the multi-drone problem?
Thank you and BR

**Comment by sousheel** [comment]
Hi @MelSoS and @josedeo , I am working on the problem right now. Let me know if you have any pointers. My fork is at https://github.com/cohrint/AirSim.

**Comment by MelSoS** [comment]
@sousheel nice to here that - we are getting more!
Unfortunately, there is no update yet (as far as I now), let's inform each other in this regard. 
Best,

**Comment by jasonhbartlett** [comment]
I suspect this is partly related to this issue I submitted #1696 where I believe the structs located in AirSim/Unity/UnityDemo/Assets/AirSimAssets/Scripts/Utilities/AirSimSettings.cs script need to be updated to be able to read the "Vehicles" data structure.

**Comment by jonyMarino** [comment]
Fixed with #3128
