### ISSUE TITLE
2 Drones operating different Deep Reinforcement Learning(DRL) models

### ISSUE THREAD

**Issue by Endf22** [Microsoft/AirSim#1547]
Hello,

First of all, I appreciate all comments you will make for this, it will help me anyway.

Before, I was using AirSim to train and test DRL models for just 1 drone.  However, I want to test different DRL models at the same time by using multiple drones. For example one drone will operate CNN model, and the other drone will have a different kind of model at the same time. I wonder that is it possible to use one workstation to do that or should I use multiple workstations. I am asking this because when I use only one drone, it will use almost 90% of GPU. What if I have multiple drones? 

Thank you very much.

AirSim version: 1.2
Multirotor
Spyder, python 3.6

**Comment by madratman** [comment]
Well, the answer is "it depends". I guess this is something you'll know (or already have figured out by now?) by playing with. I'd try decreasing the batch size and / or the model size of my network so it uses less GPU percentage. 
I am not sure which deep learning library you're using, but there's an option to allocate max gpu usage per model in some of them (which you can find by an appropriate google search).  
Please comment or re-open the issue if this does not answer your question.
