### ISSUE TITLE
can you please release binary version under linux ? 

### ISSUE THREAD

**Issue by XiaoZzai** [microsoft/AirSim#1548]
as titled

**Comment by sytelus** [comment]
Try this out: https://github.com/Microsoft/AirSim/releases/tag/v1.2.0Linux

**Comment by 18605973470** [comment]
@sytelus 

I get this error : 
error while loading shared libraries: libopenvr_api.so: cannot open shared object file: No such file or directory.

I am new to UE4. So how can I solve this problem ?
Thanks a lot .

**Comment by 18605973470** [comment]
Hi @sytelus 
Do you have version 1.2.1 ? Maybe I need "no display" mode.

**Comment by 1453042287** [comment]
@18605973470 can you extract the CityEnviron.zip?

**Comment by 18605973470** [comment]
Hi @1453042287 

Yes. I use 7zip as suggested.

**Comment by 1453042287** [comment]
@18605973470 sorry to bother again, did you run the linux version successfully?

**Comment by 18605973470** [comment]
You should extract engine.zip and add corresponding path to LD path

**Comment by 1453042287** [comment]
@18605973470 em...i come back again, i download the CityEnviron.zip and extract it successfully, and i also add the path of .so in engine.zip to LD path, but when i run the CityEnviron.sh i still have the Segmentation fault (core dumped) error, is there something i missed?

**Comment by jonyMarino** [comment]
treated on #1567
