### ISSUE TITLE
How to run new environments like AirSimNH in linux. Please provide the instructions...

### ISSUE THREAD

**Issue by Vinay545** [Microsoft/AirSim#1552]
Is AirSimNH unreal engine project. I do not find any uproject files in it. How to launch the environment. When I executed AirSimNH.sh file, it is showing the below error
**error while loading shared libraries: libopenvr_api.so: cannot open shared object file: No such file or directory**
How to launch this environment? I have using built unreal engine. Do i need to install it? 

I copied engine files in AirSimNH. Still it is showing the same error.

**Comment by damien022** [comment]
You need to modify the launch script to point to where the libraries are. You can find them in the Engine zip file.
In the bash script to launch the Environment, do
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libopenvr_api:/path/to/libopenal.so`

**Comment by luqiang21** [comment]
@damien022 Hi thank you for the answer, but where can I find the libraries. I didn't find those two files on my computer.

**Comment by Endf22** [comment]
Hello,

I had the same issue but finally, I have managed to open AirSimNH environment by following these steps:

1) Add Engine files to AirSimNH directory
2) Execute  AirSim.sh file in terminal (chmod +x AirSimNH.sh or sudo ./AirSimNH.sh)
2) Run AirSimNH  (AirSimNH/Binaries/Linux/AirSimNH)   

I hope it helps,

**Comment by Vinay545** [comment]
@Endf22 Thank you. Its working now. 
@damien022  Thank you

**Comment by ssokhey** [comment]
@Endf22 
Hi,

What exactly I have to do in Step 1. ?
I just can't figure out can you please explain.

**Comment by madratman** [comment]
Hey, just updated AirSimNH and added a blocks binary. 
`Engine/`. `libopenar.so`, `libopenvr.so` should be all in there. 
Please check updated instructions at https://github.com/Microsoft/AirSim/releases/tag/v1.2.0Linux

**Comment by alonyomtov123** [comment]
Where are the files that should be moved?
How are they called and to where?
Also, is there a way to use PythonClient in AirSimNH like in Airsim?
Thank You
