### ISSUE TITLE
can not extract the CityEnviron.zip

### ISSUE THREAD

**Issue by 1453042287** [Microsoft/AirSim#1553]
like the title, when i use the 7zip to extract the CityEnviron.zip.001 for linux, it report errors:
Path = CityEnviron.zip
Type = zip
ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
Physical Size = 3117932051
Tail Size = 30606
ERROR: Data Error : CityEnviron/Content/Paks/CityEnviron-LinuxNoEditor.pak
Sub items Errors: 1
Archives with Errors: 1
Warnings: 1
Open Errors: 1
Sub items Errors: 1

**Comment by luqiang21** [comment]
I encountered similar problem. When I extract it, it is requiring password.

**Comment by 1453042287** [comment]
i can't extract the file when i use a ubuntu environment but when i use the windows it works fine!

**Comment by nighthb2019** [comment]
Hey , I followed the operation, but still can't extract the CityEnviron.zip. I am running under WIN10. 
Does anyone know this reason?
