### ISSUE TITLE
In windows, airsim start normally but immediately crash

### ISSUE THREAD

**Issue by qhl722** [Microsoft/AirSim#156]
Setup the windows environment follow the demo successfully, but the unreal crashed after load in the airsim plugin. Is it because did not connect to the px4 controller? Is the flight controller connection mandatory?

![capture](https://cloud.githubusercontent.com/assets/6612741/25033584/e80fa5ce-2111-11e7-976e-32254bcf7409.JPG)

**Comment by athersec** [comment]
My project also crash when I run ".exe". However, it works in the UE Editor. And I don't know why.

**Comment by WorldEditors** [comment]
I have the similar problem,  it runs ok with other game mode, but immediately crush in "SimGameMode", it did not even show the drone, but crash right after I clicked the button

**Comment by lovettchris** [comment]
Yes, there is a problem and I've been trying to debug it too, but it seems to only work if you select the build configuration "DebugGame Editor", in VS:
![image](https://cloud.githubusercontent.com/assets/18707114/25051116/ea0b600a-20ff-11e7-9332-e079ad914d5d.png)

Then use F5 to launch the Unreal Editor under debugger, then make Unreal Editor use the same build configuration by selecting it here:

![image](https://cloud.githubusercontent.com/assets/18707114/25051274/ad5ced44-2100-11e7-94c3-7a2c52661d54.png)

**Comment by qhl722** [comment]
OK, problem solved by selecting the build configuration "DebugGame Editor". Can close now
