### ISSUE TITLE
one of the drones stuck in a position (not moving forward) when the other drone collided with something

### ISSUE THREAD

**Issue by Endthere** [microsoft/AirSim#1564]
Hello,

I train and test the drones with DRL models. I am having problems when I try to use multiple drones in AirSimNH environment. For example, One drone collides with something such as road, but the other drone doesn't collide. However this drone couldnt move forward, just trying to go forward but it seems it is not able to and then going up slowly. 

I am using this settings in settings.json file.
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  
  "Vehicles": {
		"Drone1": {
		  "VehicleType": "SimpleFlight",
		  "X": 0, "Y": -14, "Z": -3,
		"EnableCollisionPassthrogh": false,
                "EnableCollisions": true
		},
		"Drone2": {
		  "VehicleType": "SimpleFlight",
		  "X": 4, "Y": -14, "Z": -3,
		"EnableCollisionPassthrogh": false,
                "EnableCollisions": true
		}
    }
}

Thank you for your comments.

**Comment by RVBldr** [comment]
Do you have a copy of your python script you're using?

**Comment by Baldins** [comment]
Did you solve it? I have the same problem.

**Comment by Endthere** [comment]
The new version of Airsim solved the problem.
