### ISSUE TITLE
pausing the game bug: vehicle velocity/acceleration/RPM are not constant when paused

### ISSUE THREAD

**Issue by Lotjeotje** [microsoft/AirSim#1584]
When using the pause function in SimModeCar.cpp (line 32 - 40), the clock speed is set to 0 properly. But when I check the debug messages toggled by ';' when playing in pause mode, only my position and orientation are fixed. The lin/ang acceleration and velocity are still varying and RPM is slowing decreasing/increasing depending on throttle input.

```
void ASimModeCar::pause(bool is_paused)
{
    if (is_paused)
        current_clockspeed_ = 0;
    else
        current_clockspeed_ = getSettings().clock_speed;

    UAirBlueprintLib::setUnrealClockSpeed(this, current_clockspeed_);
}
```
In unreal, the view pauses properly and when setting clock speed to 1 again, the car starts driving properly as well. But I am using the vehicle's state information for running a motion base so I need the velocity and acceleration to be constant when paused.

Should I make something such that the kinematics are not updated when clock speed = 0?

**Comment by zimmy87** [comment]
Tested for this in the v1.7.0 release and can no longer reproduce this issue.
