### ISSUE TITLE
AirSim Plugin Not building against UE 4.21+

### ISSUE THREAD

**Issue by AshishKumar4** [Microsoft/AirSim#1586]
I have been able to successfully compile and build AirSim against Unreal Engine 4.20.3 (also built from source) in the past, and have used the plugin as it was supposed to be. Blocks compiled hassle free. But in recent times, I have been building UE4.21, and currently 4.21.1 from the source, the same way I built earlier versions. But I have been noticing probable API conflicts maybe or idk, errors while compiling Blocks.
My System -> 
Debian x64 GCC 8.2.0 Linux 4.18 kernel Vulkan sdk built and installed + Nvidia 4.10 proprietary drivers.
Along with 2 possible API conflits, also,
The warnings have been set to produce errors in the arguments, But i am just not able to figure out where the $(ARGS) passed in the makefile is set. Help me in finding how to change the UnrealHeaderTool build arguments 
[errors.txt](https://github.com/Microsoft/AirSim/files/2624880/errors.txt)

**Comment by bmalhigh** [comment]
@AshishKumar4 -- Currently we have tested the plugin only with UE 4.18.

Happy to get community help on figuring out issues with UE 4.21. Let us know what you find out.
