### ISSUE TITLE
Debugging AirSim on Linux

### ISSUE THREAD

**Issue by EliaTarasov** [Microsoft/AirSim#159]
Hello.

System config:
OS: Ubuntu 16.04 LTS
Unreal code branch: release
AirSim code branch: master
Qt Creator with Qt 5.5.1 for GCC

Current situation:
1. Unreal and AirSim are both successfully build and test project ~/Unreal Projects/MyProject/MyProject.uproject has been created. 
2. AirSim is successfully loaded as plugin into MyProject.uproject.
3. ./GeberateProjectFiles.sh successfully created MyProject.pro file.

The question:
How to setup this MyProject.pro for clang toolchain? The problem is that to build MyProject.pro file i have to use qmake build system which in turns require Qt to be used, so i have to rebuild my current Qt installation for clang instead of gcc.
Is that correct or not?

**Comment by AlexandreBorowczyk** [comment]
The *.pro file should be good to go. All you need is to setup the Kit as shown in the video:  https://www.youtube.com/watch?v=RnINgMbJx5Q.
Then, to select the compiler in QtCreator, navigate to Tools > Options > Build & Run > Compilers
Add select the compiler you what.
