### ISSUE TITLE
Question about 2D Lidar: Channel missing

### ISSUE THREAD

**Issue by edualvarado** [Microsoft/AirSim#1591]
OS: Ubuntu 16.04
AirSim 1.2

I am currently adding a Lidar sensor to my vehicle. I need a 2D Lidar, but when I change the number of channels to 1 in the `settings.json` file, the sensor won't show any points. Only when the number of channels are 2 or more it works.

The position with respect to the vehicle seems fine to me. As I said, it works perfectly for 2 or more channels, being the points shown where I want.

This is my current configuration for the Lidar:

      "Lidar1": {
         "SensorType": 6,
         "Enabled" : true,
         "NumberOfChannels": 1,
         "RotationsPerSecond": 10,
         "PointsPerSecond": 10000,
         "X": 0, "Y": 0, "Z": -0.15,
         "Roll": 0, "Pitch": 0, "Yaw" : 0,
         "VerticalFOVUpper": 0,
         "VerticalFOVLower": 0,
         "HorizontalFOVStart": 0,
         "HorizontalFOVEnd": 0,
         "DrawDebugPoints": true
       }

Am I maybe missing something? Thanks!

**Comment by bmalhigh** [comment]
Investigating.

**Comment by bmalhigh** [comment]
@edualvarado -- Thanks much for reporting the issue. It is fixed now.
