### ISSUE TITLE
Support for official docker files

### ISSUE THREAD

**Issue by varun19299** [Microsoft/AirSim#1596]
* Python Version : 3.5 
* Ubuntu 16.04
* UE 4.18 (tried UE 4.19, works)

Can AirSim support a dockerfile as a part of its builds? This makes reproducibility far easier on Linux.

Also, a look at CARLA's docker file release could be helpful (also uses UE, UE 4.19). Link [here](https://github.com/carla-simulator/carla/blob/master/Util/Docker/Release.Dockerfile).

There are a few unofficial ones: 

* [AirSim](https://github.com/abhay-agarwal/airsim-docker-quickstart)

There's also an excellent docker file repo for UE (4.19+), [here](https://github.com/adamrehn/ue4-docker).

I plan on using this to setup a docker file for AirSim. Would a pull request be acceptable?

**Comment by JihunPark** [comment]
I agree. It was quite easy to run Airsim on the host machine, but I failed to run Airsim on a docker container.. Please consider providing an official docker file.

**Comment by madratman** [comment]
Added support for binaries here https://github.com/Microsoft/AirSim/pull/1868 
I am looking in to building from source as well.
