### ISSUE TITLE
error compiling airsim on win10 

### ISSUE THREAD

**Issue by dong03** [Microsoft/AirSim#1597]
Can anyone help? Thanks in advance!
something 'Redefinition of kinematics' and convert parameter. I have no idea...

“D:\airsim\AirSim-master\AirSim.sln”(默认目标) (1) ->
“D:\airsim\AirSim-master\Examples\Examples.vcxproj”(默认目标) (8) ->
(ClCompile 目标) ->
  d:\airsim\airsim-master\airlib\include\physics\debugphysicsbody.hpp(45): error C2082: 形参“kinematics”的重定义 [D:\airsim\AirSim-master\Examples\Examples.vcxproj]
  d:\airsim\airsim-master\examples\standalonephysics.hpp(27): error C2664: “void msr::airlib::DebugPhysicsBody::initialize(msr::airlib::Kinematics *,msr::airlib::Environment *)”: Unable to convert parameter 1 from "MSR ::airlib::Pose" to“msr::airlib::Kinematics *” [D:\airsim\AirSim-master\Examples\Examples.vcxproj]

“D:\airsim\AirSim-master\AirSim.sln”(默认目标) (1) ->
“D:\airsim\AirSim-master\AirLibUnitTests\AirLibUnitTests.vcxproj”(默认目标) (11) ->
  d:\airsim\airsim-master\airlibunittests\simpleflighttest.hpp(31): error C2664: “msr::airlib::MultiRotor::MultiRotor(const msr::airlib::MultiRotor &)”: Unable to convert parameter 3 from "MSR ::airlib::Pose" to“msr::airlib::Kinematics *” [D:\airsim\AirSim-master\AirLibUnitTests\AirLibUnitTests.vcxproj]

**Comment by madratman** [comment]
This seems to be related with recent commits https://github.com/Microsoft/AirSim/commit/3a3cd2b452a2696f3357352f623b3f0c209c39cd and https://github.com/Microsoft/AirSim/commit/b945c64570cb9b6ae6c06ef00ebe667b339765d1. 
Can you try a git pull and building again? CC @sytelus
