### ISSUE TITLE
Unable to edit UnrealEngine Project File 

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1598]
I am Unable to edit the UnrealEngine project file, As I edit he fie and add Airsim Dependencies and plugins it just hides the project in the unreal engine and is not able to show it what could be the issue and how to resolve it

**Comment by RVBldr** [comment]
What specifically are you trying to do? Are you setting up your own project ot trying to edit one of the pre-baked binaries?

**Comment by Ahmad5112** [comment]
I have sorted the issue there was the error in Unreal engine file dependencies were not added properly
