### ISSUE TITLE
SITL setup instructions in documentation

### ISSUE THREAD

**Issue by yashkaushal** [Microsoft/AirSim#1600]
Hi,

I tried following the steps given in the [px4 setup page](https://github.com/Microsoft/AirSim/blob/master/docs/px4_sitl.md) updated in [commit](https://github.com/Microsoft/AirSim/commit/1294446db63ee24462e66fcc917e4636a3600dcb) and got the directory does not exist error, after exploring more I found that the below steps are working to build and run PX4 SITL and tested it with AirSim in unreal as well.
```
1. mkdir -p PX4
2. cd PX4
3. git clone https://github.com/PX4/Firmware.git
4. cd Firmware
5. git tag -l
6. git checkout <desired version>
7. git branch -D master
8. git checkout -b master
9. git submodule update --init --recursive
10. make posix_sitl_default none_iris
```
I tested it with version 1.8.1 of PX4 on bash on windows and ubuntu 16.04

Please tell me if my method is correct and/or update the method given in documentation.

Thanks,
Yash Kaushal

**Comment by jasonhbartlett** [comment]
Hi @yashkaushal 
That looks good!  As a possible 10.a and 10.b ..

10a. make list_config_targets (Will show a list of possible targets)
10b. make posix_sitl_default none_iris  (As and example)

I believe that page should be updated.  One thing I don't know is if it's necessary to install all the NuttX developer stuff if you just want to run PX4 in SITL?

**Comment by jasonhbartlett** [comment]
IDK cause I'm pretty new to this but there are several sitl options when I run 'make list_config_targets':
posix_sitl_broadcast
posix_sitl_default
posix_sitl_ekf2
posix_sitl_inav
posix_sitl_lpe
posix_sitl_replay
posix_sitl_rtps
posix_sitl_shell
posix_sitl_test
I went with posix_sitl_ekf2 and none_iris.. And that worked. 
Don't exactly know if using ekf2 for state estimation is better than default (or maybe that is the default)?  Can't find the docs for that.  Also IDK if using iris as a model will mean I'm limited to a specific UAV system if I'm using simulator and want to try out larger or smaller UAV bodies with unique physics attributes?  As I said I'm pretty new to this.  Need to do a bunch more reading.  LOL.
