### ISSUE TITLE
Settings.json accessing Error

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1604]
I have gone through all the required steps but when I run the simulation it shows an error that" There is no compatible vehicle chosen in json setting" how can i get out of it

**Comment by BrunoXL** [comment]
Your settings is not correct. Paste it here, so others can have a look at it.

**Comment by madratman** [comment]
@Ahmad5112 can you share your settings.json? Or if this was resolved, let us know
