### ISSUE TITLE
Need help related to settings .json file

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1607]
I need to write a setting, json file for my setting, in which I need to use a lidar with a drone and want to fly it from a point to another where can I find the example file.
Also, I am having an issue that even though I have setting .json file but in unreal engine, I am unable to see drone moving while everything is working properly

**Comment by msb336** [comment]
[lidar settings.json documentation](https://github.com/Microsoft/AirSim/blob/master/docs/lidar.md)
