### ISSUE TITLE
Allow setting external forces (e.g. wind)

### ISSUE THREAD

**Issue by kshahar** [Microsoft/AirSim#161]
I would like to suggest adding an option to set external forces that act on the vehicle. This could be useful for simulating environmental conditions such as winds and gusts, or vehicle-specific mechanisms such as parachutes.

An initial implementation could include a single (global) external forces vector in the `Environment` class, set by the user (e.g. in the UE4 plugin). Another option would be to set such vector per vehicle.

Thank you!

**Comment by sytelus** [comment]
Yes, this is in plan. We are planning add model for winds and thermals very soon!

**Comment by mmwing** [comment]
Is this promised wind & thermal model already implemented?
