### ISSUE TITLE
Do the provided ROS wrappers work on Windows with AirSim and UNITY?

### ISSUE THREAD

**Issue by Spiraseven** [Microsoft/AirSim#1612]
I saw here: https://github.com/Microsoft/AirSim/blob/master/docs/ros.md
that ROS was implemented with Unreal and AirSim. 

I was wondering if this same implementation works with Unity on Windows? Are there any guidelines on setting this up?

**Comment by BrunoXL** [comment]
ROS has no support for Windons. 
`ROS 2`  is under development so far and support for Windows instead.
I think ROS is not related to any of engines ( it has it own simulator). So, you can pick what fits better for you.

**Comment by madratman** [comment]
please re-open or comment if you have more questions
