### ISSUE TITLE
Radial offset while orbiting

### ISSUE THREAD

**Issue by delphifissure** [microsoft/AirSim#1619]
I'm running a clean version of orbit.py over PX4 for a photogrammetry project. It's important that I'm able to capture images at fairly precise distances so as to control the proportion of the object within the drone's FOV.

However, the drone never settles on the specified radius. When the drone starts its orbit, actual_radius is precisely the correct amount but quickly increases and settles at a radius wider than specified.

I've tried numerous speeds (incl. very slow), both large (10m) and small radii (1m), and even after numerous (10+) orbits, the amount settled on is not the selected one.

However, the drone is indeed capable of orbiting at any radius you want, except of course small radii at high speeds. I just measure the actual_radius performed given my selected amount, measure the average delta, and just adjust self.radius to compensate. For example, I'm using radius of 0.823 with a speed of 1m/sec to hit actual radius of 1m. 

It would be phenomenal if the selected radius was consistently matched without this high-touch process given that the drone is definitely capable of achieving said radius with a little hand-holding.

**Comment by ironclownfish** [comment]
Can you give simSetObjectPose() a try and let us know if it meets your requirement?
It'll just teleport any object (drone in your case) to a precise location. It sounds like you have no need of actually simulating the flight of the drone as proper flight.

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
