### ISSUE TITLE
The password of Environment?

### ISSUE THREAD

**Issue by EricJin101** [Microsoft/AirSim#1623]
when I extract CityEnviron.zip.001 and CityEnviron.zip.002, it needs password

**Comment by EricJin101** [comment]
![aa](https://user-images.githubusercontent.com/26600982/49862278-cdd96400-fe38-11e8-8ac6-56eb6530b519.JPG)

**Comment by RVBldr** [comment]
@EricJin101 - Have you tried this again and is it still occurring? This shouldn't be password protected.

**Comment by mondejar** [comment]
Hi, I have the same problem. Any solution?

**Comment by RVBldr** [comment]
We'll take a look.

**Comment by csuwp** [comment]
I have the same problem

**Comment by ElMonfo00** [comment]
Has anyone solved this issue? @EricJin101
