### ISSUE TITLE
How to use GPU graphic card in Ubuntu16.04 with release binaries

### ISSUE THREAD

**Issue by zhangfuyang** [microsoft/AirSim#1625]
my system is Ubuntu16.04 with 1060 GPU. When I run the AirSimNH.zip in release v1.2.0, I find my GPU is not used. So I wonder if there is a config file that I can turn on using GPU.

Another guess. My Nvidia driver's version is 390.67. Is it because the Binaries are incompatible with the driver?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
