### ISSUE TITLE
Specifying default camera locations for the drones

### ISSUE THREAD

**Issue by zsfVishnu** [Microsoft/AirSim#1637]
I wanted to translate the camera from its initial position(front side of the drone) to either sides of the drones. Changing camera orientation doesn't achieve this. I need a way to translate it. I saw the code for specifying the camera positions in the care but couldn't find it for the drone,

**Comment by jasonhbartlett** [comment]
@zsfVishnu Did you perhaps make a mistake in posting this issue?  You only posted the issue template.  If so please close or correct this issue posting.  Thanks!

**Comment by zsfVishnu** [comment]
@jasonhbartlett , yea srry abt that!!! Updated the issue, do look into it and provide a solution if possible.

**Comment by madratman** [comment]
@zsfVishnu sorry for the delayed reply, but please see my comment here https://github.com/Microsoft/AirSim/issues/1770#issuecomment-462949223
you can do it via the flying pawn blueprint, we'll update the docs
