### ISSUE TITLE
Is there any way to get distance and displacement travelled by drone from python client?

### ISSUE THREAD

**Issue by koriavinash1** [Microsoft/AirSim#1640]
Are there any python API's which returns the distance and displacement traveled by the drone just by using IMU data (by twice integration of acceleration, obtained from IMU sensor)? or any ROS-AirSim integration for the same ...

**Comment by madratman** [comment]
We added an IMU API here https://github.com/Microsoft/AirSim/pull/1920  There's an IMU API here. which you can integrate on the client side 
A ROS integration is just around the corner in https://github.com/Microsoft/AirSim/pull/1911
