### ISSUE TITLE
Incorrect behavior of MoveToPositionAsync

### ISSUE THREAD

**Issue by majouda7** [Microsoft/AirSim#1643]
Hello,

I am using Python Client API (move* API) to build a path planner algorithm. I am having an issue with moveToPosition API call, after giving the command to move to a certain position I am noticing a huge offset in the drone location in unreal engine. For instance, if I send the drone to the waypoint (-5, 0, -3) (client.moveToPositionAsync(-5, 0, -3, 5).join()) with a velocity of 5m/s, the drone actually goes to (-10, 0, -4) in unreal environment (Ned frame of the drone). I have also noticed that the error increases with velocity and it is a kind of random (not always the same offset for the same waypoint). Moreover, it seems that AirSim is not aware about this offset in unreal because when I call client.simGetVehiclePose().position it returns exactly the same position I requested at the beginning (-5, 0, -3). This is very undesirable especially in a path planning context where a reasonable precision in the environment is required to avoid obstacles. Is there a way to fix that ?
PS: The figures 1 and 2 show the drone at the starting point (0,0) and at the arriving point respectively.
Thanks,

![starting_point](https://user-images.githubusercontent.com/13359373/50194448-9539fe80-0300-11e9-9c7f-cf3888e11d36.png)

![arriving_point](https://user-images.githubusercontent.com/13359373/50194461-a1be5700-0300-11e9-8144-18b29c88853c.png)

**Comment by saihv** [comment]
I think I have the same problem. I am trying to control multiple SimpleFlight drones with the Python API, and I am encountering errors in how MoveToPositionAsync actually moves the drones. For instance, this is a set of commands I gave the drone:

```
f1 = client.moveToPositionAsync(5, 0, -8, 3, vehicle_name="Drone1")
f1 = client.moveToPositionAsync(-5, 0, -8, 3, vehicle_name="Drone1")
f1 = client.moveToPositionAsync(-5, -10, -8, 3, vehicle_name="Drone1")
f1 = client.moveToPositionAsync(5, -10, -8, 3, vehicle_name="Drone1")
f1 = client.moveToPositionAsync(5, 0, -8, 3, vehicle_name="Drone1")
```

My world is properly aligned, so this should make the drone fly in a perfect square. Instead, this is what the drone does (plotted from the airsim_rec log):

![image](https://user-images.githubusercontent.com/2274262/51157893-897e2100-1847-11e9-8ed4-f07600d8833a.png)

Unless I am doing/understanding something wrong, this seems to be a pretty major issue.

**Comment by madratman** [comment]
let's track this in 1685
