### ISSUE TITLE
Missing Step in: Docs » Get AirSim » Build on Windows

### ISSUE THREAD

**Issue by mmwing** [Microsoft/AirSim#1647]
In the documentation following Step is missing:

**Build AirSim**
- Install Visual Studio 2017. 
Make sure to select VC++ and Windows SDK 8.1 while installing VS 2017.
->ALSO MAKE SURE TO SELECT "Git for Windows" and/or "GitHub-Extensiosn for Visual Studio" while installing VS 2017 .<-

Furthermore 

- Start x64 Native Tools Command Prompt for VS 2017 ->"AS ADMINISTRATOR"<-

**Comment by madratman** [comment]
I don't think running as an admin is required. 
Installing git for windows is something we can add, we just assumed that's something people will do if they build from source. github for vs2017 again is not required
