### ISSUE TITLE
Using imitation learning to replicate specific movement trajectories

### ISSUE THREAD

**Issue by karthikm-0** [microsoft/AirSim#1648]
Hi,

I have been using the imitation learning scripts to play around with training a car to drive itself. My question is more of a use case that I'd like to ask about as opposed to an issue I'm facing. I was wondering if imitation learning (as provided in AirSim) can be used to replicate short patterns of movement. For instance, I would like to train my vehicle to swerve around while heading from point A to B and stopping at an intersection really quickly (versus slowly). I'd like this exact pattern to be replicated assuming the car is positioned at A and I'm using the drive_model script. Is imitation learning the right technique for this? Or is the technique suitable for training a vehicle how to drive and stay on a road (instead of replicating an exact pattern of movement).

Thanks!

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
