### ISSUE TITLE
Landscape Mountains environment not working with AirSim

### ISSUE THREAD

**Issue by samby707** [microsoft/AirSim#1650]
I am trying to build airsim using unreal engine and following the steps to use landscape mountains to setup airsim from scratch.
https://www.youtube.com/watch?v=1oY8Qu5maQQ&feature=youtu.be

I am using airsim version 4.18 with vs 2017 15.8.9.

When I am trying to build the project after adding the asset files and changing the config files, I get the error that, 
![image](https://user-images.githubusercontent.com/29973201/50275623-cda71d00-0465-11e9-91f4-91ba297f4718.png)

When i click on yes, i get this error.
![image](https://user-images.githubusercontent.com/29973201/50275654-e57ea100-0465-11e9-8b8d-056dbbffce38.png)

I even tried building the project using the sln file from VS 2017 but to no avail.

**Comment by samby707** [comment]
When I'm running build.cmd from x64 native tools visual studio command prompt for AirSim library, it is getting built successfully but the Airsim.uplugin file is not getting generated.

**Comment by sbkybhy** [comment]
Hello, I have the same problem. How did you solve this problem
