### ISSUE TITLE
Slight collisions make the drone fly far away

### ISSUE THREAD

**Issue by KeyneZzz** [Microsoft/AirSim#1653]
Hi everyone,
When I control my drone to land softly, it will sometimes collide the ground slightly, and then suddenly fly far away with rolling rapidly. Tried to set the restitution of physical material, but not working. 
Seems like it's more related to UE4 itself, can anyone help? Thanks.

**Comment by msb336** [comment]
@KeyneZzz 
That sounds exciting...
Are you using a custom environment, or one of the AirSim binaries?
Please also post your API script and settings.json file.

**Comment by KeyneZzz** [comment]
the problem only happened in ver 1.1.x, I have updated to ver1.2 and not appearing. So maybe the right method is to upgrade and close the issue
