### ISSUE TITLE
Multi-Agent Support for autonomous driving car

### ISSUE THREAD

**Issue by AlenUbuntu** [Microsoft/AirSim#1655]
Dear Sir or Madam:
I am just wondering if AirSim has supported mult-agent RL for autonomous driving?

**Comment by madratman** [comment]
There is a python example for multiple cars [here](https://github.com/Microsoft/AirSim/blob/master/PythonClient/car/multi_agent_car.py), and a single agent DQN example [here](https://github.com/Microsoft/AirSim/blob/master/PythonClient/car/DQNcar.py). Might be good starting points
