### ISSUE TITLE
AirSim on Unity installation error

### ISSUE THREAD

**Issue by AlenUbuntu** [Microsoft/AirSim#1656]
Hello, everyone:
When I tried to run ./build.sh in the AirSim/Unity/build.sh, the following error is raised:

./build.sh: line 14: cmake: command not found
make: *** No targets specified and no makefile found.  Stop.
cp: cannot stat 'libAirsimWrapper.so': No such file or directory

The previous steps works pretty fine. Does anyone know the solution?

[OS]
Ubuntu 18.04

**Comment by msb336** [comment]
@AlenUbuntu 
This error is indicating that you do not have cmake on your system. Were you able to successfully run ./setup.sh and ./build.sh from the main AirSim directory?

**Comment by msb336** [comment]
@AlenUbuntu 
On second look, build.sh is calling the global cmake command, not the one downloaded by airsim's `setup.sh` command. I'll submit a PR now, but in the meantime, you can either install cmake globally:
```
sudo apt-get install cmake
```

or replace the `cmake` command in `Unity/build.sh` with the following:
```
CMAKE="$(readlink -f ../../cmake_build/bin/cmake)"
"$CMAKE" ../../cmake ../AirLibWrapper/AirsimWrapper;
```

**Comment by qZhang88** [comment]
Still some build error here, if cmake version is ok, then setup.sh there will create cmake_build directory.

I use 'apt remove cmake', and rerun setup.sh for a temp fix

```bash
#download cmake - v3.10.2 is not out of box in Ubuntu 16.04
if version_less_than_equal_to $cmake_ver $MIN_CMAKE_VERSION; then
    if [[ ! -d "cmake_build/bin" ]]; then
        echo "Downloading cmake..."
        wget https://cmake.org/files/v3.10/cmake-3.10.2.tar.gz \
            -O cmake.tar.gz
        tar -xzf cmake.tar.gz
        rm cmake.tar.gz
        rm -rf ./cmake_build
        mv ./cmake-3.10.2 ./cmake_build
        pushd cmake_build
        ./bootstrap
        make
        popd
    fi
else
    echo "Already have good version of cmake: $cmake_ver"
fi
```

**Comment by rajat2004** [comment]
There's an open PR right now to fix several issues with the Unity build - https://github.com/microsoft/AirSim/pull/2328
