### ISSUE TITLE
INFO  [simulator] Waiting for simulator to connect on TCP port 4560

### ISSUE THREAD

**Issue by karanmartian** [Microsoft/AirSim#1661]
Hi,

When I checkout PX4 from the latest master HEAD branch and start PX4 SITL or any of the launch scripts I am getting "INFO  [simulator] Waiting for simulator to connect on TCP port 4560". Then if I start AirSim its not able to connect to SITL. But if I checkout a stable branch  e.g. of 1.8.2 and launch SITL then it shows me waiting to connect on UDP port 14560 and then I am able to connect AirSim properly.

How do I get SITL to listen on UDP port 14560 in the latest master HEAD branch?

**Comment by clovett** [comment]
I believe it is set as a parameter in the "iris" drone startup script, search for this:
```
param set SITL_UDP_PRT 14560
```
this script lives here: “build/posix_sitl_ekf2/tmp/posix-configs/SITL/init/ekf2/iris”, and if the drone you are using doesn't have this parameter, try adding it.
