### ISSUE TITLE
When the handle is connected to the computer through usb, in simple flight mode, when the throttle is at 0.5 position, what do I want it not to land automatically?I'm stuck here.

### ISSUE THREAD

**Issue by love-mj** [Microsoft/AirSim#1663]
When the handle is connected to the computer through usb, in simple flight mode, when the throttle is at 0.5 position, what do I want it not to land automatically?

**Comment by love-mj** [comment]
have already been solved

**Comment by gniwon** [comment]
how did you solve it?
Would you please tell me how you solved it?
