### ISSUE TITLE
Why does the UAV always shift randomly after takeoff in hardware-in-loop mode?

### ISSUE THREAD

**Issue by love-mj** [Microsoft/AirSim#1664]
Why does the UAV always shift randomly after takeoff in hardware-in-loop mode?

**Comment by clovett** [comment]
is it related to [this bug](https://github.com/Microsoft/AirSim/issues/1340)?

**Comment by love-mj** [comment]
Yes, it's mostly one-sided. I follow the video tutorial step by step. I don't know why.

**Comment by love-mj** [comment]
[](url)

**Comment by love-mj** [comment]
@clovett no, Not much to do with。I don't do anything，I want him to hover, but it always drifts.

**Comment by love-mj** [comment]
![image](https://user-images.githubusercontent.com/37679671/50474347-91426680-09fb-11e9-8505-68a210d7fb89.png)这个是手柄油门在0.5的时候，我用的是pxhawk2.4.8

**Comment by love-mj** [comment]
![20181227_172936](https://user-images.githubusercontent.com/37679671/50475350-635f2100-09ff-11e9-8ecf-94d157f0bfd8.gif)

**Comment by love-mj** [comment]
have already been solved
