### ISSUE TITLE
How to use the pre-compiled binaries for setting up the city environment with airsim using that released for linux? Can someone please explain how to use the pre-compiled binaries for the city environment using linux machine.

### ISSUE THREAD

**Issue by UmaArunachalam8** [microsoft/AirSim#1668]

**Comment by ssokhey** [comment]
@UmaArunachalam8 Just download the latest binaries (updated 11 days ago) and follow the updated instructions.

[https://github.com/Microsoft/AirSim/releases](url)

**Comment by madratman** [comment]
Hey. the city environment is corrupt yes. I'll try to update it by EOD.

**Comment by kylelindgren** [comment]
@madratman have you had a chance to fix the city environment binaries?

**Comment by viniciusguigo** [comment]
I'm also interested and could not extract the files. Thank you!

**Comment by MrDadaGuy** [comment]
$ 7z x CityEnviron.zip.001

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,48 CPUs Intel(R) Xeon(R) CPU E5-2687W v4 @ 3.00GHz (406F1),ASM,AES-NI)

Scanning the drive for archives:
1 file, 1782579200 bytes (1700 MiB)

Extracting archive: CityEnviron.zip.001
           
CityEnviron.zip
ERRORS:
Headers Error
Unconfirmed start of archive


CityEnviron.zip
WARNINGS:
There are data after the end of archive

--
Path = CityEnviron.zip.001
Type = Split
Physical Size = 1782579200
Volumes = 2
Total Physical Size = 3117962657
----
Path = CityEnviron.zip
Size = 3117962657
--
Path = CityEnviron.zip
Type = zip
ERRORS:
Headers Error
Unconfirmed start of archive
WARNINGS:
There are data after the end of archive
Physical Size = 3117932051
Tail Size = 30606

    
Would you like to replace the existing file:
  Path:     ./CityEnviron.sh
  Size:     261 bytes (1 KiB)
  Modified: 2018-08-15 14:34:38
with the file from archive:
  Path:     CityEnviron.sh
  Size:     261 bytes (1 KiB)
  Modified: 2018-08-15 14:34:38
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? A

ERROR: Data Error : CityEnviron/Content/Paks/CityEnviron-LinuxNoEditor.pak
                                                               
Sub items Errors: 1

Archives with Errors: 1

Warnings: 1

Open Errors: 1

Sub items Errors: 1

**Comment by zhangzhen886** [comment]
I also have same problem...

**Comment by luxiangnk** [comment]
I got the same problem.. Thanks!

**Comment by yerzhik** [comment]
Same problem. Hopefully can be fixed soon...

**Comment by sebLopezCot** [comment]
Same issues.

**Comment by gonzaloaguilarjimenez** [comment]
Same problem

**Comment by bozcani** [comment]
Same problem. Still unsolved

**Comment by jonyMarino** [comment]
Treated in #2407

**Comment by JohnVorwald** [comment]
I don't see the solution in #2407.
