### ISSUE TITLE
In C++ how to get the value of  Collision Count:

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/AirSim#167]
Hello All:
When i am testing the Drone, i am trying to program a simple AI which can control the Drone ignore the Collision with the walls.

I find Plugins already show the Collision Count value which like if the Drone crash and it will be counted.

is any possible for me to get the Collision Count function in my program? 

Thanks for the help!

**Comment by Focke-Wulf** [comment]
I am trying to edit based on HelloDrone.  the problem is that in HelloDrone, can we get function of Collision?

Thanks..

**Comment by lovettchris** [comment]
This information is currently not being sent via the DroneControlBase API, but it could be added easily enough.

**Comment by Focke-Wulf** [comment]
Thanks for the reply! .  I find DroneControlBase API
However I am not familiar with C++ code.... so i still have some problems.


and i find an example here  which from VehiclePawnBase.ccp

![1](https://cloud.githubusercontent.com/assets/26343300/25329194/1a151220-291e-11e7-961b-711140583fd8.PNG)


and i also find the code fro DroneControlBase API Which is 
![2](https://cloud.githubusercontent.com/assets/26343300/25329293/874a22fe-291e-11e7-80e1-52a311a0e6a0.PNG)


i am starting to test those code but in DroneControllerBase.cpp, i cann't find the function [getPosistion() ] auto show up ... but the original code works with that...
![fd24ed52d10d5a17b15bfd5a5cd5af83](https://cloud.githubusercontent.com/assets/26343300/25329703/406e38aa-2920-11e7-8128-fc576fa03753.jpg)

So i am trying to edit this file like this...
![4](https://cloud.githubusercontent.com/assets/26343300/25329718/552ad6b8-2920-11e7-8c04-e1a296792812.png)

Am i at the right way????

If it is right.. do i need to rebuild the Plugins in AirSim ? 

or i could just add these code in the Plugins file which already in my UE4 project???

Thanks for the HElP!!!!!!!!!

**Comment by sytelus** [comment]
Search for AVehiclePawnBase::NotifyHit to see the current code that counts collisions. 

If you don't want collisons then search for below statement and set it to true.

```
bool EnablePassthroughOnCollisons = false; 
```

**Comment by Focke-Wulf** [comment]
Hello: 
       Thanks for the reply... What i want is to transfer the collisons info back to the server..
       which is like we can use getPosition() at server side....
