### ISSUE TITLE
rotateToYawAsync() does nothing 

### ISSUE THREAD

**Issue by Spiraseven** [microsoft/AirSim#1682]
Hopefully I am just using this wrong, but when trying to rotate using rotateToYawAsync() nothing happens to the drone. I simply take off then call the rotate method.

client.rotateToYawAsync(90,5,1)

Has anyone had any luck using this. Is there a better way to have a drone turn in place? Is that possible?

**Comment by gurpreetss** [comment]
Please try with client.rotateToYawAsync(90,5,1).join()

**Comment by Spiraseven** [comment]
Yea nothing happens with adding join either. I am not seeing any errors. Maybe the function is just not hooked up? I have not gone through all the source code

**Comment by gurpreetss** [comment]
I tried the function today and it worked, though there were some glitches.
Is it possible to share a code snippet?

**Comment by Spiraseven** [comment]
I forgot to mention I was using the python api and I am on ubuntu as well working off of the master branch from December. Here is the code

`
import setup_path
import airsim
import numpy as np
import os
import tempfile
import pprint
import cv2
from PIL import Image
from array import array
import time

client = airsim.MultirotorClient()
client.confirmConnection()
client.enableApiControl(True)
client.armDisarm(True)

airsim.wait_key('Press any key to takeoff')
client.takeoffAsync().join()

airsim.wait_key('Press any key to rotate')
client.rotateToYawAsync(90,5,1).join()
`

**Comment by chaitanyantr** [comment]
Yes...!for me too its same,

The 4th param of rotateToYawAsync() expecting vehicle name...don''t know what to fill

 **def rotateToYawAsync(self, yaw, timeout_sec = 3e+38, margin = 5, vehicle_name = ''):
        return self.client.call_async('rotateToYaw', yaw, timeout_sec, margin, vehicle_name)**


had given the command like.....

airsim.wait_key('Press any key to rotate')
client.rotateToYawAsync(90,5,1).join()

(Airsim version -  1.2)

**Comment by whatseven** [comment]
I have the same problems. I test with `rotateByYawRateAsync`. It rotates. But when change it to `rotateToYawAsync` it fails and does nothing.

**Comment by abhimanyuchadha96** [comment]
Has this been fixed?

**Comment by alexander-hamme** [comment]
I am also experiencing this issue on Ubuntu 16. Has this been patched?

**Comment by dimikout3** [comment]
I can use the rotateToYawAsync() but after a number of ratations the vehicles does not respond ...
