### ISSUE TITLE
Can I run this on a Azure vm ,as I dont have a good system.

### ISSUE THREAD

**Issue by Abhi001vj** [microsoft/AirSim#169]

**Comment by lovettchris** [comment]
We have not done it yet, but you would need [Azure VM with a good GPU](https://azure.microsoft.com/en-us/resources/videos/build-2016-introduction-to-nvidia-gpus-in-azure/). And you would need to figure out how to configure Unreal Engine to run in headless mode, and this part doesn't seem to have good answers yet on the unrealengine forums.

**Comment by Abhi001vj** [comment]
Thank you .

**Comment by sytelus** [comment]
Azure recently added NC and NV series for VMs that should be able to run AirSim. Check below link for details and let us know how it goes!

https://azure.microsoft.com/en-us/pricing/details/virtual-machines/windows/  (check for NV12 or NC12).

**Comment by jkuruzovich** [comment]
I gave this a try on a Windows 10 Pro machine on Azure.  I kept running into an issue indicating DX11 feature level 10.0 is require to run the engine.   
<img width="320" alt="screenshot 2017-12-09 15 35 12" src="https://user-images.githubusercontent.com/409274/33799422-594a2ba8-dcf9-11e7-8d1c-3b133b0b821f.png">

**Comment by PHRABAL** [comment]
@jkuruzovich I have the same problem on an AWS Windows Server 2016 instance. Did you solve this?

**Comment by ByronDev121** [comment]
Is there a solution for this?

I get the same error. "DX11 feature level 10.0 is require to run the engine."

I'm trying run AirSim on a Windows server 2019 VM on Google Cloud Platform. The VM configuration is setup with the n1-standard-2 (2 vCPUs, 7.5 GB memory) and Nvidia Tesla K80 GPU.

The latest drivers are installed for the GPUI:

![image](https://user-images.githubusercontent.com/35214618/79331515-8c206800-7f1b-11ea-95af-01067e53965e.png)

I also have direct X 12 installed (as I understand it, this should be backwards compatible with 11):

![image](https://user-images.githubusercontent.com/35214618/79331653-d0136d00-7f1b-11ea-9e7d-fd33e57ce947.png)

![image](https://user-images.githubusercontent.com/35214618/79331744-f89b6700-7f1b-11ea-8a8c-d403269f3c16.png)

 I've tried a number of potential solutions but nothing has worked so far.

**Comment by guadacasuso** [comment]
Please check this https://microsoft.github.io/AirSim/azure/
