### ISSUE TITLE
Can't extract the CityEnviron.zip in win10

### ISSUE THREAD

**Issue by nighthb2019** [Microsoft/AirSim#1690]
Hi , I've been downloaded the CityEnviron.zip.001 and the CityEnviron.zip.002 for ubuntu16.04 . And I  used 7zip to extract them, but still can't extract the CityEnviron.zip , it reportd errors. 
I decompressed in the WIN10 environment.
Does anyone know this reason?
Thanks.

**Comment by madratman** [comment]
Just use the 7zip Gui and seleect the zip.001 file

**Comment by nighthb2019** [comment]
Hi,

I used the 7ZIP GUI to extract the 001.ZIP file, but I still get an error. What should I do?






-----原始邮件-----
发件人:"Ratnesh Madaan" <notifications@github.com>
发送时间:2019-01-16 05:43:38 (星期三)
收件人: Microsoft/AirSim <AirSim@noreply.github.com>
抄送: nighthb2019 <hb_2016@stu.xjtu.edu.cn>, Author <author@noreply.github.com>
主题: Re: [Microsoft/AirSim] Can't extract the CityEnviron.zip in win10 (#1690)



Just use the 7zip Gui and seleect the zip.001 file

**Comment by madratman** [comment]
this was closed prematurely, we're working on updating the city binary soon

**Comment by 2016CS112** [comment]
@madratman , sir city binary updated or not?

**Comment by 2016CS112** [comment]
![Capture](https://user-images.githubusercontent.com/38519481/60381214-84fe9b00-9a6a-11e9-960a-24475b3dec00.PNG)

How to Extract this assets?
