### ISSUE TITLE
How to Get the Signal Value of Px4 Handle Channel？

### ISSUE THREAD

**Issue by love-mj** [Microsoft/AirSim#1691]
![image](https://user-images.githubusercontent.com/37679671/51018054-2ffcc480-15b1-11e9-996a-419a39163acd.png)
![image](https://user-images.githubusercontent.com/37679671/51018153-84a03f80-15b1-11e9-9e22-969ff57fe72a.png)
What function to get the button channel？Getting values in red boxes like simpleflight？

**Comment by lovettchris** [comment]
See https://docs.px4.io/en/getting_started/rc_transmitter_receiver.html

**Comment by love-mj** [comment]
![360截图176610148910593](https://user-images.githubusercontent.com/37679671/55769142-403e1600-5ab2-11e9-8e43-f29418a55d94.png)

GetRCChannal () is the access handle channel, but the value obtained is incorrect.

rebootVehicle () is to restart pixhawk, but pixhawk will be out of control after restart.
setupAirframePage () is a change in rack type, but it doesn't work.

**Comment by love-mj** [comment]
获取通道信号已解决
