### ISSUE TITLE
How to get started with airSim?

### ISSUE THREAD

**Issue by Supaple-x** [Microsoft/AirSim#1693]
Hey guys!

I have 3d-model of environment and 3d-model of drone.

How can I use it in sim now? Is here step-by-step sequence how to behavior in the beginning to achieve the result?

Thanks a lot...

**Comment by jasonhbartlett** [comment]
My suggestion would be to read the documentation contained in this repo perhaps starting with https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md if your platform is PC otherwise https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md if your platform is Linux.

**Comment by Supaple-x** [comment]
Thanks, Jason,

but after I follow theese steps I'm getting error.
I've opened [another issue for that](https://github.com/Microsoft/AirSim/issues/1705)
