### ISSUE TITLE
API for collision Alert

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1699]
I am trying to find a way in AirSim to get Alerted before the collision. Is there any API for this purpose, built in example or any method to Apply as it is an important part of collision avoidance algorithms to implement

**Comment by madratman** [comment]
No, we only have `simGetCollisionInfo`, as explained [here](https://microsoft.github.io/AirSim/docs/apis/#collision-api) and [here](https://github.com/Microsoft/AirSim/blob/123bbd6d6416bbe98e775101ba8ebcb5ccbf8501/PythonClient/car/car_collision.py)
