### ISSUE TITLE
Aircraft can't takeoff with new version of PX4(after ver:1.4.4)

### ISSUE THREAD

**Issue by liuli2008212** [Microsoft/AirSim#170]
I used the new version of PX4(after ver:1.4.4),my aircraft can't takeoff when I play. The aircraft is Keep rolling . But it is running normally by the version of 1.4.4 . I have tried the UE_4.15 and UE_4.14.  
My aircraft can't takeoff,the error is following:
==||=> arm
==||=> takeoff
RPC Error: rpclib: function 'takeoff' (called with 1 arg(s)) threw an exception.
 The exception contained this information: Drone hasn't came to expected z of -3
.000000 within time 15.000000 sec within error margin 0.500000 (current z = 159.
326767).

Thank you for your help.

**Comment by lovettchris** [comment]
Definitely need UE_4.15.  But can you try this version of the PX4 firmware? 
[px4fmu-v2_default.zip](https://github.com/Microsoft/AirSim/files/950543/px4fmu-v2_default.zip)
And make sure you set RpcEnabled to true in your ~/Documents/AirSim/settings.json file.

**Comment by liuli2008212** [comment]
HI lovettchris,
Thank you for your help. I tried your version of px4fmu-v2_default.zip . My aircraft can fly within UE_4.14.Your version is 1.6.0,ok? But aircraft can't fly when I try this version of v1.6.0rc1 the PX4 firmware. What did you change at this version of v1.6.0 the PX4 firmware?

**Comment by liuli2008212** [comment]
I git this version v1.6.0rc1 of the PX4 firmware.I make and upload,it's ok. But this version of https://github.com/PX4/Firmware/releases/download/v1.6.0rc1/Firmware.zip  can't fly,I don't know why,so I will use this git version.
Thank you for your help and patience.

**Comment by lovettchris** [comment]
My version is using latest bits from PX4 master branch, so it is slightly newer. Hopefully the official builds will catch up soon and we won't have this problem.  Glad you are unblocked now.  Can we close this issue?

**Comment by liuli2008212** [comment]
Yes,you can close it .Thank you very much.
