### ISSUE TITLE
Does AirSim support Taranis X7?

### ISSUE THREAD

**Issue by donfung** [microsoft/AirSim#1700]
I see that there is support for the X9D, but was wondering what the case is for the X7? I connected my X7 to my computer (windows 10) via USB but could not fly the drone in the simulator. Was wondering if i needed to edit certain files or if i missed something else important.

**Comment by delphifissure** [comment]
Yes the X7 definitely works, but I tested it in HITL mode with a FrSky X8R receiver connected to Pixhawk, and then USB from Pixhawk to computer.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
