### ISSUE TITLE
lidar point cloud

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1701]
Is there any method in AirSim to get point cloud using lidar if so, how can we get it and trace map from it

**Comment by showaykerker** [comment]
check this
https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#lidar-apis

**Comment by msb336** [comment]
Hi @Ahmad5112 
You can find instructions on how to use lidar in the docs [here](https://github.com/Microsoft/AirSim/blob/master/docs/lidar.md)

There are lots of useful instructions in the docs!
