### ISSUE TITLE
Error: Blocks could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by Supaple-x** [Microsoft/AirSim#1705]
Hey guys! 

While I'm following [these steps](https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md) I get an error **Blocks could not be compiled. Try rebuilding from source manually.**  in [recomendation mentioned above](https://github.com/Microsoft/AirSim/issues/1693).

How can I fix it to move next with AirSim?

**Comment by madratman** [comment]
any updates @Supaple-x ?
