### ISSUE TITLE
There is something wrong with \AirSim\PythonClient\car\DQNcar.py

### ISSUE THREAD

**Issue by CaoYongshengcys** [microsoft/AirSim#1710]
My error is as follows, anyone can help me ?

(base) D:\Unreal Projects\AirSim\PythonClient\car>python DQNcar.py
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Selected CPU as the process wide default device.
Traceback (most recent call last):
  File "DQNcar.py", line 536, in <module>
    current_state = transform_input(responses)
  File "DQNcar.py", line 434, in transform_input
    img2d = np.reshape(img1d, (responses[0].height, responses[0].width))
  File "D:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 257, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "D:\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py", line 52, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (0,0)

**Comment by srivatsankrishnan** [comment]
I am also running into the same issue but with my own example. Also it happens pretty randomly.
My stack trace is same as soon as it hits numpy call:
```
img2d = np.reshape(img1d, (responses[0].height, responses[0].width))
  File "/home/wxxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/wxxx/.local/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 1 into shape (0,0)
```

**Comment by srivatsankrishnan** [comment]
I think its a bug in Airsim client.simGetImages API. The issue is the responses[0].height and responses[0].width returns 0. So the numpy reshape errors out once it encounters that.

The workaround I have is to check for the condition where the responses[0].width and responses[0].height is "0" and once that condition occurs, I pass dummy image ( all 1's) and then reset airsim so it doesn't crash simulation.

**Comment by Ahmad5112** [comment]
@CaoYongshengcys did you resolve the issue? If so how did you resolved

**Comment by CaoYongshengcys** [comment]
> @CaoYongshengcys did you resolve the issue? If so how did you resolved

I did not solve this problem

**Comment by annisanazi** [comment]
did anyone resolve this issue?

**Comment by TomAvrech** [comment]
Getting the same problem :(

**Comment by zimmy87** [comment]
possibly related to #1009

**Comment by zimmy87** [comment]
Hi, thank you for reporting this issue.  This script was recently removed in #3215 and replaced with a new script at \AirSim\PythonClient\reinforcement_learning\dqn_car.py that uses the new airgym module. I tested the new script locally and it runs for me. Can you retest with the new script and report back if you see any issues?
