### ISSUE TITLE
Adding several random spawnpoints to blocks project

### ISSUE THREAD

**Issue by pr151571** [microsoft/AirSim#1716]
Hello there beautiful people from Airsim's GitHub.

I am currently trying to build (as a school project) a training ground for a reinforced learning based car-driving AI and I was planing to re-use the blocks env' to modify it in a track that can be reproduced easily in real life (to embark the trained AI in a model car and make it ace the race of the first try (that's at least the point I'm hopping to achieve)). Here's a screen of the first version of the said training track : 
![image](https://user-images.githubusercontent.com/26407987/51326213-e0b20a80-1a6e-11e9-93c0-cf0fbdd389fa.png)

It is working like a charm (goal is to reproduce this with colored tape on a grey floor) the thing is that I would like to set different spawns for the car selected at random (or in a sequence) for each reset, this way the car could manage to drive independantly from it's spawn point.

I was wondering of the best way to do this, is it through AirSim plugin code modification (I've done that before to include slightly missplaced camera sensors to reproduce real model potential missplacement), settings.json modification (I'd like to avoid that so I can avoid to relaunch the simulation each time) or in the unreal environnement.

My wish would be to spawn in a random or sequenced (preestablished) spawn point each time I hit backspace with the simulation running.

Thank you for your time.

(It's my first time filling an issue so not sure if I did everything the right way)

**Comment by hesham-akmal** [comment]
You can do that by using ue4 blueprints, use SetActorLocation and set the target to the Suv actor
