### ISSUE TITLE
depth image related query

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1717]
I need to know how can I use depth image to estimate  the collision risk how can I set some threshold distances to avoid collision

**Comment by madratman** [comment]
Please look at the different types of depth images [here](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#what-does-pixel-values-mean-in-different-image-types). 
Use either `DepthPlanner` and `DepthPerspective` (the above link explains what they mean) and then simply threshold the array. The float values returned are in meters.  If your question is how to threshold a numpy array, please google that. what do you mean by "collision risk" - it's something you as a user can define according to your needs I think, for example, as a linearly / quadratically increasing cost as depth of an object crosses a "safety limit" you define (it could be infinity as well) till some "minimum acceptable depth" - say 0.3 meters which you can consider as collision.
