### ISSUE TITLE
Need help related to reinforcement learning implementation

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1721]
I want to implement a reinforcement learning based Collision avoidance Algorithm in AirSim But I am Unable to understand How should I divide movement of Quadcopter from one point to another point in "n" number of steps where I can make my computation please anybody who worked on reinforcement learning guide me in this Aspect

**Comment by madratman** [comment]
well, it is up to you. essentially, you're asking "what is a good action space for the markov decision process to get a quadcopter to do X with RL", here X is collision avoidance. 

Is your goal just to avoid things, or is it to avoid thing WHILE/ADD moving to a goal pose. 

Now, if you're using the moveToPosition API you can set up a simple action space of move right, left, up, down, forward. back by a small distance,  and finally a stop or hover action to begin with. Afai understand your question, you're asking what is a good number? well, no one knows! It depends on your application, your environment size, and perhaps your obstacle sizes. 

You can think about it in terms of what's a safe stopping distance given the speed I'm moving at using the moveToPosition api and that should answer your question. 

you can also learn a policy in velocity space (and yaw) space, where you apply an action (velocity command) for a small duration (say 0.05 seconds).
