### ISSUE TITLE
Need Guidance  related to Example code

### ISSUE THREAD

**Issue by Ahmad5112** [Microsoft/AirSim#1728]
`top = np.vsplit(gray, 2)[0]
        print(top)

        # now look at 4 horizontal bands (far left, left, right, far right) and see which is most open.
        # the depth map uses black for far away (0) and white for very close (255), so we invert that
        # to get an estimate of distance.
        bands = np.hsplit(top, [50,100,150,200]);
        print(bands)
        maxes = [np.max(x) for x in bands]
        print(maxes)
        min = np.argmin(maxes)    
        distance = 255 - maxes[min]`
I need to understand what does "Distance "in the above mentioned code is 
is it the distance of object from the client?

**Comment by msb336** [comment]
Yes, it is the distance to whatever object is farthest away from the agent in each of the four band directions that you are looking at.
