### ISSUE TITLE
How to run Linux binaries in low resolution?

### ISSUE THREAD

**Issue by ssokhey** [Microsoft/AirSim#1730]
Hi,

I would like to know if there is way to run the newly released Linux binaries in low resolution. Like in windows we do,

`start CityEnviron -ResX=640 -ResY=480 -windowed`  in `run.bat` file.

Is there any Linux equivalent?

**Comment by msb336** [comment]
Yep, there is! It's more or less the exact same syntax too. Run the bash file that is stored in the main binary directory with the following terminal command:
`./CityEnviron.sh -ResX=640 -ResY=480 -windowed`
