### ISSUE TITLE
Hardware Requirements in Linux System 

### ISSUE THREAD

**Issue by alitarfa** [Microsoft/AirSim#1733]
Hello every 
Could you please tell me the requirements of Airsim,
GPU?
RAM? 
CPU? 
Thanks

**Comment by DavidLSmyth** [comment]
See #17 and docs/dev_workflow

**Comment by madratman** [comment]
thanks @DavidLSmyth. here's the link https://microsoft.github.io/AirSim/docs/dev_workflow/
