### ISSUE TITLE
Global Planner PX4 with AirSim and Lidar

### ISSUE THREAD

**Issue by karanmartian** [microsoft/AirSim#1735]
I am trying to run the PX4 obstacle avoidance global and local planner which they have currently documented only for Gazebo. How do you go about running them on a drone equipped with Lidar in AirSim? What kind of changes would be required to the px4 launch files and other parts of the code?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
