### ISSUE TITLE
Unreal Vehicle Content in CityEnviron

### ISSUE THREAD

**Issue by DTChuck** [microsoft/AirSim#1740]
I am working towards creating a customized environment that is like the CityEnviron environment, but with some specific requirements about the vehicles. Is there any information on the asset packs and vehicle/pedestrian AI that I can access to expedite my environment creation?

Using Unreal 4.18, Windows 10.

**Comment by msb336** [comment]
@RVBldr is there documentation about which packages are getting used for different environments?

**Comment by jonyMarino** [comment]
See comment on the latest release please
