### ISSUE TITLE
Using Multiple cameras for detection

### ISSUE THREAD

**Issue by Ahmad5112** [microsoft/AirSim#1744]
I want to use multiple cameras for capturing the image and based on the depth image being captured by the cameras I want to make an array of distances and based on that array I want to run a learning algorithm .is it possible to do it so how can I do it

**Comment by AloshkaD** [comment]
Yes, it is possible but your question is really broad. Try to start with a simple example, then implement it. Break down what you need to accomplish into algorithms and build the architecture then build the components and put them together. What you are asking to do is a big project that consists of too many components and no one can really show you how to do everything like that.

**Comment by Ahmad5112** [comment]
yes you are right but in the meantime, my question is how can I implement multiple cameras and based on distance how can i make Array of distance using depth image

**Comment by madratman** [comment]
@Ahmad5112, please take @AloshkaD's comment seriously. Please keep your issues to the point.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
