### ISSUE TITLE
Racer quad flight dynamics

### ISSUE THREAD

**Issue by alexanderkoumis** [microsoft/AirSim#1747]
Has anyone successfully modified the quad physics parameters in `Px4MultiRotorParams.hpp` to make the quad feel more like a racing drone? The stock drone feels very "floaty" and even with QGroundControl acro mode cannot perform quick maneuvers like in Velocidrone, DRL Simulator, FPV Freerider, etc (see https://www.youtube.com/watch?v=nnTDor69M4Y).

I have tried changing the specs in `Px4MultiRotorParams.hpp` to match those of a generic 250 racing quad but it is still sluggish and often becomes unstable. Has anyone had better luck? The end goal is to use AirSim to train a model based on quick acrobatic flight.

Thanks.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
