### ISSUE TITLE
How to run HelloDrone Program

### ISSUE THREAD

**Issue by zywOwO** [Microsoft/AirSim#175]
I am new to unreal engine and c++, so please forgive if this question was asked before.

Following the setup video, I can successfully control the drone under "SimGameMode" and now I want to do programmatical control. Where should I run the HelloDrone program or where should I insert that piece of code?

**Comment by lovettchris** [comment]
Easiest way to run HelloDrone is on the same machine as the unreal simulation.  The SimGameMode creates the RpcServer which talks to HelloDrone over TCP sockets.  Be sure to first Go to Unreal Editor, Edit/Editor Preferences, select "All Settings" and type "CPU" in the sarch box. It should find the setting titled "Use Less CPU when in Background", and you want to uncheck this checkbox, as per our [FAQ](https://github.com/Microsoft/AirSim/blob/master/docs/faq.md).

**Comment by zywOwO** [comment]
I still have a problem connecting the hellodrone.cpp with the unreal project.
I tried to run the .exe file and it prints "Waiting for drone to get a GPS position...".
Then I clicked play in unreal editor. It fails to control the drone by program.
What did I do wrong?

**Comment by clovett** [comment]
Try starting unreal "play" before running hellodrone.

**Comment by SaiVineethJ** [comment]
@zywOwO   How did you run the code??
I am getting this error while compiling main.cpp: 
"fatal error: common/common_utils/StrictMode.hpp: No such file or directory
 #include "common/common_utils/StrictMode.hpp""

How to remove this error or is there any other way of running the code??
