### ISSUE TITLE
Airsim Build error: Cmake Windows

### ISSUE THREAD

**Issue by ethbond** [microsoft/AirSim#1753]
Attempting to build Airsim, error reading what version cmake I have.
did cmake --version to check installed version (see screen cap), seems to be fine any ideas? 

[
![capture](https://user-images.githubusercontent.com/33580212/51995462-a69f2a80-24aa-11e9-9ab4-213c3eba1fcf.PNG)
](url)

**Comment by samuelgarcia321** [comment]
try install module C++ In Microsoft Visual Studio.
its worked for me.

**Comment by arian-amador** [comment]
Initially looking at this it seems like an issue with `find` or `cmake` but then noticed that you cloned the AirSim repo into your `c:\Windows\System32` directory AND you're also running the Native Tools CLI as an admin?

I recommend you try and start the native tools as a normal user and clone the AirSim repo into another non-system directory. Example: `c:\AirSim\`

**Comment by ethbond** [comment]
@samuelgarcia321 So I verified that the C++ module was installed (see images) also included a list of the individual components perhaps I have missed something?
![capture2](https://user-images.githubusercontent.com/33580212/52047962-13b1cf00-2542-11e9-891c-03be9af79cda.PNG)
![capture3](https://user-images.githubusercontent.com/33580212/52047964-14e2fc00-2542-11e9-928a-c640700d4dfe.PNG)



@arian-amador Moved it to my D: drive, ran as a normal user rather than admin, same problem.
![capture1](https://user-images.githubusercontent.com/33580212/52047958-10b6de80-2542-11e9-8abe-b150159f6d1a.PNG)

**Comment by madratman** [comment]
@ethbond, were you able to compile it? 
can you try reinstalling cmake >=3.9 from here https://cmake.org/download/

**Comment by ethbond** [comment]
I managed to compile it, but by doing a workaround. The cmake install is fine. The problem seems to be with Check_cmake.bat, failing to find the cmake version, or writing the version it finds to the "cmake_version" variable. My workaround was to just type in my version into line 8 of Check_cmake.bat:

 set "cmake_version=    3.     13"

Saved the .bat, ran the build again and it worked fine.

**Comment by madratman** [comment]
@ethbond thanks for getting back quickly 
hmm. that's weird, I haven't seen any other issue in which cmake wasn't found..
ok, I did a quick hunt again in old issues, and this comment seems related https://github.com/Microsoft/AirSim/issues/755#issuecomment-423298213

The issue seems to be this line https://github.com/Microsoft/AirSim/blob/master/check_cmake.bat#L12
`'cmake --version ^| find "cmake version"'`

Can you please share the output of `where Find.exe` on your machine? Maybe you and @vincedjango had similar causes. 

In my machine, I don't have cygwin, so it's simply:
```
C:\Users\ramadaan>where Find.exe
C:\Windows\System32\find.exe
```

**Comment by ibadrather** [comment]
> @madratman
> 
> I managed to compile it, but by doing a workaround. The cmake install is fine. The problem seems to be with Check_cmake.bat, failing to find the cmake version, or writing the version it finds to the "cmake_version" variable. My workaround was to just type in my version into line 8 of Check_cmake.bat:
> 
> set "cmake_version= 3. 13"
> 
> Saved the .bat, ran the build again and it worked fine.

Thank you for your solution. Worked for me too.
