### ISSUE TITLE
CarClient Linear Velocity

### ISSUE THREAD

**Issue by ElliotHYLee** [microsoft/AirSim#1760]
From version 1.2.0, for the release versions, the car mode's linear velocity is not [0,0,0] at beginning when the car is still. It seems the velocities differ by the environment package. However, the MultirotorClient's linear velocity are all [0,0,0] at the beginning.

What's causing this? By simply subtracting the initial velocity, can this be usable?

![capture](https://user-images.githubusercontent.com/7537835/52158146-4a333b00-2663-11e9-88f9-609f7188f7d7.PNG)

The setting is:
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  
  "CameraDefaults": {
	"CaptureSettings": [
	  {
		"ImageType": 0,
		"Width": 720,
		"Height": 360,
		"TargetGamma": 3.0
	  }
	]
  }
}

**Comment by dawgster** [comment]
I'm having the same issue. Is this a bug or a feature I don't understand yet? In the blocks environment, a value for linear_velocity.x_val of around -59 shows when in standstill.

**Comment by ironclownfish** [comment]
After PR 2705 is merged, you can safely do this to achieve true pause.
![image](https://user-images.githubusercontent.com/6217407/82500575-749f4680-9aa8-11ea-8f81-cea30af669e3.png)
