### ISSUE TITLE
Question: Multiple vehicles of different SimMode

### ISSUE THREAD

**Issue by pramodak** [Microsoft/AirSim#1777]
Is there a plan to support multiple vehicles of different SimModes (e.g. one car and two quads) in the same scene?

**Comment by chaitanyantr** [comment]
as of now no.there is already discussion on this in issues.please find the same.

**Comment by pramodak** [comment]
Thank you. Please provide a reference link for the discussion.

**Comment by chaitanyantr** [comment]
FYI

https://github.com/Microsoft/AirSim/issues/506

**Comment by pramodak** [comment]
Thank you for the reference.

**Comment by FL2316** [comment]
I follow your advice, but there are some mistakes that can't be solved. I don't know what to do...seg fault,
Can anybody help me?thanks alot
