### ISSUE TITLE
Error building Blocks on Ubuntu 

### ISSUE THREAD

**Issue by Benji15150** [Microsoft/AirSim#1778]
Hello, I am attempting to build a airsim project on Unreal. I successfully ran both set up files for AirSim and Unreal. However, when I tried to open the project, it gave the error that I need to install Null Source Code Accessor. Any suggestions on how to solve it? (The link unreal gave was some link to wikepedia)

**Comment by Benji15150** [comment]
On the side note, I have recently recloned airsim, and the older version of airsim without multi-vehicle attribute opened just fine without that warning. I am not sure what is causing missing compiler error for this version of block.uproject.

**Comment by msb336** [comment]
Try cleaning out your repository and rebuilding. The first step would be to run ```./clean.sh``` inside the blocks project directory, and then trying to open the environment again. If that doesn't work, you can clear out the entire repo by running ```git clean -fdx```. Be warned, this will remove every file not commited to the repository, so if you have any personal work in the repo, make sure it is either committed to your fork or saved somewhere else on your machine.

**Comment by msb336** [comment]
If you are still having a problem related to this issue, please re-open it
