### ISSUE TITLE
[Question] GetLidarData UU Coordinate 

### ISSUE THREAD

**Issue by thomasvolpato** [microsoft/AirSim#1779]
I am using the GetLidarData in C++ and Unreal.
I did not get how to get (or convert) the Lidar Data Position to the UU coordinate.

I got the example code inside the file **SimModeBase.cpp** in the function **drawLidarDebugPoints**.
The local/global offset are used to set the new location. But I do not know how to access this information from the client. How do I get this offset only using the MultirotorRpcLibClient?

I am using the following code:

```c++
msr::airlib::MultirotorRpcLibClient client_;
msr::airlib::LidarData lidar_;

client_.confirmConnection();
lidar_ = client_.getLidarData();

for (int j = 0; j < lidar_.point_cloud.size(); j = j + 3) {
		FVector point(lidar_.point_cloud[j],
			lidar_.point_cloud[j + 1],
			lidar_.point_cloud[j + 2]);
}

DrawDebugPoint(
			this->GetWorld(),
			uu_point,
			5,              //size
			FColor::Purple,
			true,           //persistent (never goes away)
			0.1             //point leaves a trail on moving object
		);
```

**Comment by ironclownfish** [comment]
The UU coordinates can be found by multiplying Z in Airsim's ned frame by -1, multiplying all the coordinates by a constant factor (1000 I believe) and adding a constant origin offset vector (which you'll have to solve for). I assume you're doing something custom with your map, if you're interested in unreal units.
