### ISSUE TITLE
What's about a Mac OS X version???

### ISSUE THREAD

**Issue by MadMacMad** [Microsoft/AirSim#1780]
can not find a Mac OS X version for Unity3d nor UE4...

1. WHY?
2. How can i make it work on Mac ?

hope someone can make it work.... many thx
respect
S.

**Comment by msb336** [comment]
[instructions for installing unreal engine for mac](https://github.com/EpicGames/UnrealEngine#mac)

[download link for unity](https://store.unity.com/download), just switch from windows to mac on the download option tab.

Currently, there is no official support for airsim on mac, but the community has put in enough work that I believe it is operating as a somewhat functional beta. For the time being, there are no plans for an official release of airsim on osx.
