### ISSUE TITLE
Unreal Engine Stops during Simulation

### ISSUE THREAD

**Issue by Ahmad5112** [microsoft/AirSim#1782]
I am trying to run a simulation of DQN training while after performing more then 20000 steps unreal engine stop responding like it hangs only way i have to is to restart the unreal engine and therefore i am unable to complete trainig

**Comment by madratman** [comment]
@Ahmad5112  can you share the output of the log files in a [github gist](https://help.github.com/articles/creating-gists/)?
they should be in `PROJECTDIR\Saved\Logs`

**Comment by ironclownfish** [comment]
This will probably be fixed by PR #1970
