### ISSUE TITLE
How to get "only" left and right RGB images of a stereo camera in Airsim, I want to train(ML) with those images.

### ISSUE THREAD

**Issue by chaitanyantr** [Microsoft/AirSim#1786]
I am able to get the images with 

"client.simGetImages(airsim.ImageRequest("0", airsim.ImageType.DepthVis))"---(i am believing that this use the stereo camera of 20 cm base line)

How can i get the only left and only right RGB images of one stereo camera in Multi-rotor.?

----------------------------------------------edit-1-----------------------

As for as i know there are 0,1,2,3,4 camera ID's ,in Multi-rotor  front_center, front_right, front_left, bottom_center and back_center.

Are these cameras all stereo or monocular?

if monocular how i am getting depth by only one camera lets say "0".
if the cameras are stereo how to get only left only right that camera.?

**Comment by madratman** [comment]
Q. `Are these cameras all stereo or monocular?`:    
- Please see my comment here https://github.com/Microsoft/AirSim/issues/1787#issuecomment-464250107

Q. `How to get "only" left and right RGB images of a stereo camera in Airsim`   
- In Python, 
```Python
response = client.simGetImages([
   airsim.ImageRequest("front_left", airsim.ImageType.Scene, False, False),
   airsim.ImageRequest("front_right", airsim.ImageType.Scene, False, False)
])

img_left_temp = np.fromstring(response[0].image_data_uint8, dtype=np.uint8)
img_left_rgba = img_left_temp.reshape(response[0].height, response[0].width, 4)

img_right_temp = np.fromstring(response[1].image_data_uint8, dtype=np.uint8)
img_right_rgba = img_right_temp.reshape(response[1].height, response[1].width, 4)
```

In C++, you can do a:
```cpp
msr::airlib::MultirotorRpcLibClient client;
typedef msr::airlib::ImageCaptureBase::ImageRequest ImageRequest;
typedef msr::airlib::ImageCaptureBase::ImageResponse ImageResponse;
typedef msr::airlib::ImageCaptureBase::ImageType ImageType;

std::vector<ImageRequest> request = { 
        ImageRequest("front_left", ImageType::Scene, false, false), 
        ImageRequest("front_right", ImageType::Scene, false, false) 
    };
const std::vector<ImageResponse>& response = client.simGetImages(request);
```


Q. `i am believing that this use the stereo camera of 20 cm base line`   
- If you want to change the baseline, please see my comment here https://github.com/Microsoft/AirSim/issues/1770#issuecomment-462949223

**Comment by hightao** [comment]
If you want to get only RGB pic, instead of RGBA, you can code like this:

- Python
```     responses = self.simGetImages([airsim.ImageRequest("3", AirSimImageType.Scene)])
        png_image = np.fromstring(responses[0].image_data_uint8, dtype=np.uint8)
        im = cv2.imdecode(png_image,cv2.IMREAD_COLOR)
        cv2.imshow("img", im)
        cv2.waitKey(0) 
```
other para, please refer to doc.
