### ISSUE TITLE
How i am  getting the depth images,info?

### ISSUE THREAD

**Issue by chaitanyantr** [Microsoft/AirSim#1787]
In Multi-rotor there are **front_center, front_right, front_left, bottom_center and back_center** cameras .

How am i getting depth if all are monocular cameras.?

**Comment by madratman** [comment]
hey @chaitanyantr, each camera is a monocular, as well as a depth camera. 
In fact, these are all possible returns possible from each of the 5 cameras you mentioned: https://github.com/microsoft/airsim/blob/master/docs/image_apis.md#available-imagetype-values

Depth is implemented specifically as material functions. You can inspect these by going to unreal engine->content browser -> airsim content -> HUDAssets -> Material functions, as shown in the following images

![bla](https://user-images.githubusercontent.com/6305323/52890252-a5bbf900-3138-11e9-91a5-4ad0206e7873.PNG)
![bla2](https://user-images.githubusercontent.com/6305323/52890255-a6ed2600-3138-11e9-9685-22dd77eaf09d.PNG)
