### ISSUE TITLE
How to run car with autopilot mode?

### ISSUE THREAD

**Issue by backer777** [microsoft/AirSim#1792]
How to run car with autopilot mode?
I want to drive the car randomly on the map without manual intervention, similar to CARLA's autopilot function.

**Comment by douglas125** [comment]
That would indeed be useful.
Is it possible to expose ground truth information of roads and vehicles? That could simplify the task of writing an autopilot agent considerably.

**Comment by msb336** [comment]
There is no built in autopilot in airsim. You can however obtain ground truth data about the environment by using `simGetObjectPose` and `simListSceneObjects` in conjunction to find ground truth positions of objects in the world.
