### ISSUE TITLE
Newest builds / migrating released environments to new version

### ISSUE THREAD

**Issue by lysektomas** [Microsoft/AirSim#1794]
Hi,
thank you for your great work on AirSim!

I want to use new features like Weather API, Time of Day API, in builded environments from [your release page](https://github.com/Microsoft/AirSim/releases) I am particularly interested in landscape scenes like "Mountain Landscape", "ZhangJiaJie", "Forest", "Plains", "Africa", "TrapCam", ... nearly every scene :).

But when I am trying to run `PythonClient/computer_vision/weather.py` I am seeing this error

```
msgpackrpc.error.RPCError: rpclib: server could not find function 'simEnableWeather' with argument count 1.

```

If I understand this error corectly it is problem with airsim version of builded environments - 1.21 - and airsim version with weather api. 

I know that I could build specific environment and I will definitely do that for Landscape Mountains envrionment, but every other environment is not possible to get from unreal engine for free.

Is it possible to somehow migrate builded environment to newer version? 

Or when could we expect new release of every environment? 

Third question: Is it possible to send me those scenes I will build them and send them back for official release?

Thanks a lot!
Tom

**Comment by msb336** [comment]
@lysektomas 
You are correct, our binaries in our release tab are a little outdated. We're in the process of updating them now.

Unfortunately, those binaries use non-open source resources, so we can't distribute the unreal editor versions freely, but thank you for the offer!

Keep an eye out for new releases in the near future
