### ISSUE TITLE
Can I collect and save the data of Logitech G920?

### ISSUE THREAD

**Issue by lotus-cqu** [microsoft/AirSim#1799]
I want to collect the data when i use my G920 to drive a car so that i can use it to train my model. So what should i do to save the data?

**Comment by JamesDD12** [comment]
Hi Lotus,
I am looking to do the same as you are. Have you found away to do the above?

**Comment by lotus-cqu** [comment]
> Hi Lotus,
> I am looking to do the same as you are. Have you found away to do the above?

Nope

**Comment by rajat2004** [comment]
`getCarControls()` API or using the Recording feature (press R or recording APIs) should give the values sent by the wheel
