### ISSUE TITLE
Using VirtualBox Ubuntu

### ISSUE THREAD

**Issue by fmzhu** [Microsoft/AirSim#180]
hello,
I'm using VirtualBox Ubuntu as Software-In-Loop Simulation.  I change the UdpIp and SitlIp to the ip address of my virtual machine, but it could not connect to remote host at "IP:14560". So anybody ever met the same problems? Thank you for your attention!

**Comment by lovettchris** [comment]
What I do is communicate with the virtual machine using it's real IP address.  This means you also need to set the LocalHostIp to your host computer's real IP address, like this:

    "LocalHostIp": "10.137.62.126",
    "SitlIp": "10.137.63.61",
    "SitlPort": 14556,
    "UdpIp": "10.137.63.61",
    "UdpPort": 14560,

If that doesn't work then check your: [virtual box guest network access](https://askubuntu.com/questions/232876/how-to-let-a-virtualbox-guest-running-windows-access-the-internet).  Mine works using the Bridged Adapter.

PS: I think there is a way to get virtualbox to share "localhost" with the host computer, but it's complicated...
