### ISSUE TITLE
I have encountered some problems with the Ladar FOV.

### ISSUE THREAD

**Issue by mariomister** [microsoft/AirSim#1802]
When I use the preset scene AirSimNH，I found that the scope of pointcloud has changed when my car turned a certain angle, The image below shows my profile and the situation I encountered.

my question is : Whether the fov in the configuration file is relative to the vehicle.
How can I configure parameters to solve this problem?

Best regards,
KinMario

![bt3_2l j23b2lb 7tf1_sp](https://user-images.githubusercontent.com/38120206/53175212-76b8f200-3626-11e9-8b4f-21f65ab51fe0.png)

![8y3 6s8enl cijegv_ q9](https://user-images.githubusercontent.com/38120206/53174793-969be600-3625-11e9-9338-11c58787478b.png)
![d7f cr qetxjd0bwzina4q](https://user-images.githubusercontent.com/38120206/53174803-9dc2f400-3625-11e9-993f-d01364373c40.png)

**Comment by RVBldr** [comment]
Sorry for delay, you may want to include start and stop for each FOV:
"VerticalFOVUpper": x,
"VerticalFOVLower": y,
"HorizontalFOVStart": a,
"HorizontalFOVEND": b, 

Where x/y and a/b are the start and stop degrees up/down or left/right of center. Note for instance, if you use a -a to +b set at -10 -> 10, you'll get a spread of 20 degrees and that should be relative to vehicle. If you do 10 -> -10, you'll end up with gap in front and run the coverage 340 degrees starting at 10.
