### ISSUE TITLE
How to use Lidar sensor in Ubuntu16.04 Unity?

### ISSUE THREAD

**Issue by littleredhat1997** [Microsoft/AirSim#1810]
Such as the problem, how to use Lidar sensor in Ubuntu16.04 Unity?

**Comment by msb336** [comment]
@littleredhat1997 as per this [list of supported APIs](https://github.com/Microsoft/AirSim/blob/master/docs/unity_api_support.md), getting lidar data is not yet supported in unity

**Comment by littleredhat1997** [comment]
@msb336 ok, thank you.
