### ISSUE TITLE
How to get a depth map accurately?

### ISSUE THREAD

**Issue by Ironteen** [microsoft/AirSim#1812]
I obtain my depth maps from the AirSimNH by run the following code：

`       responses = client.simGetImages([airsim.ImageRequest(0, airsim.ImageType.DepthPlanner, pixels_as_float=True)])

        response = responses[0]

        img1d = np.array(response.image_data_float, dtype=np.float)

        img1d = img1d*3.5+30 

        img1d[img1d>255] = 255

        img2d = np.reshape(img1d, (responses[0].height, responses[0].width))

        depth = np.array(img2d,dtype=np.uint8)`

but the depth map I get is as following: 
![depth_00001](https://user-images.githubusercontent.com/29378746/53488753-30eaa680-3aca-11e9-82af-1bdc90c679ee.png)

The screenshot of UE4 system:
![1](https://user-images.githubusercontent.com/29378746/53488789-4bbd1b00-3aca-11e9-81a7-8c87b6a2f056.png)

They have some differences, although not particularly obvious. So how I obtain a depth map accurately?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
