### ISSUE TITLE
Obtaining lidar data during vehicle motion

### ISSUE THREAD

**Issue by JWDu** [microsoft/AirSim#1815]
Hello everyone, I find that the Lidar in the Airsim rotates a week to return a packet of data，if my car is moving， When collecting the first column of point clouds and the last column of point clouds, the position and attitude of these two moments of the vehicle has changed. Will it cause errors?

**Comment by msb336** [comment]
It will not cause errors.

The lidar sensor in airsim works by estimating how far it will sweep at each frame, so the synchronicity of the lidar data and the vehicle position is directly related to the framerate that your simulation is running (i.e. the faster your framerate, the more accurate your lidar data will be with respect to what you would expect from real world data)
