### ISSUE TITLE
Improve image capture speed

### ISSUE THREAD

**Issue by tiax615** [microsoft/AirSim#1818]
Hi community，I think I may have found a way to improve the speed of image capture.
Modify the code in PIPCamera.cpp, updateCaptureComponentSetting()，
change
`render_target->InitAutoFormat(setting.width, setting.height);`
to
`render_target->InitCustomFormat(setting.width, setting.height, PF_B8G8R8A8, true);`

AirSim use SceneCaptureComponent2D SceneCapture mode is LDR, using RGBA8 is enough, may not need to use RGBA16f, which is supporting HDR mode. The Format of RenderTarget initialized by InitAutoFormat() is RGBA16f, which takes up resources. You can customize the Format by using InitCustomFormat(). So screenshots might become more efficient.

Thank you for reading！

**Comment by tiax615** [comment]
By the way, I used the Victory plugin by Rama to take screenshots and the frame rate was up to 20fps!
I think it's also possible to write methods in C++ code without blueprints
![_20190301200638](https://user-images.githubusercontent.com/39846986/53637321-ca968d00-3c5d-11e9-94f4-a3d28128180c.png)

**Comment by pengjili** [comment]
@tiax615 Really appreciate your sharing. I've tried your first way(didn't try 2nd yet), it did save a lot of time. But can I ask what's your image's resolution? Mine is 1280x800, and even using viewMode: "NoDisplay",  but it still costs about 250ms. I'd also like to put my frame rate up to 20fps, is there any other way to reduce time on saving images? Thanks so much again

**Comment by tiax615** [comment]
> @tiax615 Really appreciate your sharing. I've tried your first way(didn't try 2nd yet), it did save a lot of time. But can I ask what's your image's resolution? Mine is 1280x800, and even using viewMode: "NoDisplay", but it still costs about 250ms each frame. I'd also like to put my frame rate up to 20fps, is there any other way to reduce time on saving images? Thanks so much again

Hi, My image resolution is 1280x720. And I'm looking for a faster way to do it, like video live. OBS?
