### ISSUE TITLE
is gtx 1070 enough for this simulator?

### ISSUE THREAD

**Issue by idoan** [Microsoft/AirSim#182]
In the FAQ I read you recommend gtx 1080, but since 1070 also has 8gb ram, I wonder if 1070 would be sufficient for this simulator. Does any of you have any experience with 1070 and what is its performance? I intend to buy a graphic card solely for running this simulator, airsim, so if 1070 is enough, I wouldn't want to spend more money. 

Thanks.

**Comment by sytelus** [comment]
Yes, should be good for most environments. We recently saw issue in Unreal 4.15 that causes frame rates to drop dramatically if you have all 3 sub-views open. I would suggest to press "0" to turn them off. We will probably make this as default soon.
