### ISSUE TITLE
Linux binaries crashed when using ComputerVision SimMod

### ISSUE THREAD

**Issue by songjin321** [Microsoft/AirSim#1820]
### I edit settings.json file to use ComputerVision SimMode 
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "ComputerVision"
}
```
### Then I want use Neighborhood enviorment , I run AirSimNH.sh in a terminal, but unfortunately, I get an error as shown below.
![image](https://user-images.githubusercontent.com/15363101/53690291-aee8cf00-3da2-11e9-9337-4c3c08d1eac7.png)

**Comment by msb336** [comment]
@RVBldr This may be an error with the executable file. Unreal can be a bit tricky about including all of the necessary assets from airsim. If that's the case we'll recompile the binary and release the new one as soon as we can.

**Comment by howard-mahe** [comment]
I'm facing the same error as well.

**Comment by msb336** [comment]
@songjin321 

Just released the updated binary. Please close if your issue has been solved.

**Comment by songjin321** [comment]
The updated binary solved the problem, Thank you!
