### ISSUE TITLE
declare a airsim client  ,  error ???

### ISSUE THREAD

**Issue by koalamaster** [Microsoft/AirSim#1821]
//this is my code
msr::airlib::MultirotorRpcLibClient* client = new msr::airlib::MultirotorRpcLibClient("192.168.0.100", 41451, 60000);

but after I catkin_make the ros workspace:

CMakeFiles/airsim_imgPublisher.dir/src/imgPublisher.cpp.o: In function `_GLOBAL__sub_I_client':
imgPublisher.cpp:(.text.startup+0x9d8): undefined reference to `msr::airlib::MultirotorRpcLibClient::MultirotorRpcLibClient(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned short, float)'
collect2: error: ld returned 1 exit status

**Comment by hipforth** [comment]
hello, Did you solve this problem？
