### ISSUE TITLE
Did real-world quadrotor in the experiment of paper fly in the same city( Simulated one)?

### ISSUE THREAD

**Issue by ConnLiu** [microsoft/AirSim#1822]
hello,
I have some questions about the paper: https://arxiv.org/pdf/1705.05065.pdf
1. I haven't see any information about where the real-world quadrotor flies, so I am confused if the real-world and the simulated quadrotor are flying in the different city( the air pressure and magnetic field intensity must are different, but you compare these in the paper without mention whether in the same city)?
<img width="967" alt="image" src="https://user-images.githubusercontent.com/15926859/53740407-1308b180-3ecf-11e9-95a7-c2b1686dd9b4.png">

2. In the Hardware Platform of the Experiments, “We configured the simulated quadrotor in AirSim using the measured physical parameters and simulated sensor models configured using sensor data sheets. ” And what's the specific meaning of the "sensor data sheets". sensor data sheets means the data collected in the real-world?

Sorry for my poor English!

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
