### ISSUE TITLE
How do I get IMU data by python client?

### ISSUE THREAD

**Issue by didwjdrl12** [Microsoft/AirSim#1826]
Hi, I want to get IMU data by python client.
APIs (simGetVehiclePose(), getMultirotorState(), etc) just show ground truth position and attitude values, not IMU sensor data (noisy ,biased angular velocity and acceleration).

I know there is IMU sensor in airlib.
How do I get IMU sensor data by python client?

**Comment by tejaswid** [comment]
Please refer to #1909

**Comment by madratman** [comment]
See soon to be merged https://github.com/Microsoft/AirSim/pull/1920 and yes #1909 discussion
