### ISSUE TITLE
Using simGetObjectPose in Unity

### ISSUE THREAD

**Issue by SanjayJohn21358** [microsoft/AirSim#1828]
Hi,

I'm trying to use simGetObjectPose() in Unity, but with no luck. The python script goes into a loop, and nothing gets returned. I've tried naming the object directly and calling that object in the script, say 'Truck'. I've tried adding a 'Truck' tag to the object. I've seen that using setSegmentationID as well has troubles in referring to objects in Unity. I know that simGetObjectPose() seems to be supported from the docs, so I was wondering if I was doing something wrong. Thanks for your help!

**Comment by msb336** [comment]
There's no reference to simGetObjectPose in the unity wrapper source code, so I think listing that API as available was a mistake. We're working on getting our Unity side up to speed, but there is a lot yet to be done! Sorry for any headaches this may have caused you.
