### ISSUE TITLE
Where to find the scene in your demo (city/street scene)

### ISSUE THREAD

**Issue by cca2016** [Microsoft/AirSim#183]
I have just downloaded the demo called LandscapeMountains, but found it not suitable for my work.
Where to find the scene in your demo (the city/street scene, denser than LandscapeMountains)
Can it be found in Epic Games? What is the name of it?

**Comment by AlexandreBorowczyk** [comment]
[Here](https://www.unrealengine.com/marketplace/modular-neighborhood-pack) but prepare your credit card. However, you can always find [other](https://www.unrealengine.com/marketplace/profile/Epic%20Games) free stuff

**Comment by cca2016** [comment]
@AlexandreBorowczyk I have downloaded it and added to my landscape map project. But how to use it ? As i click play, there is no drone in the scene and the scene is just like a demo movie. What should i do?

**Comment by AlexandreBorowczyk** [comment]
did you follow the instruction of the demo?

**Comment by lovettchris** [comment]
Specifically, if you skip to minute 4 in this [walkthrough video ](https://www.youtube.com/watch?v=HNWdYrtw3f0&feature=youtu.be) it shows you how to add AirSim to existing environment:
