### ISSUE TITLE
How to run Airsim Unity in Ubuntu 18.04?

### ISSUE THREAD

**Issue by FPSychotic** [microsoft/AirSim#1832]
in the guide, in usage section I can read in the first point:
-Start Unity and click Open project..

how I start Unity?, what comand?, from what folder etc, I cant figure out how to do it.

**Comment by msb336** [comment]
@FPSychotic I think unity typically installs itself in the home folder. There should be a folder called `Unity-{your version}` 

Inside there you should find the unity executable
