### ISSUE TITLE
How to simulate wind in UE4

### ISSUE THREAD

**Issue by a11196690** [microsoft/AirSim#1835]
I want to add wind to UE4 in order to simulate the impact of wind on drones. How can I do it? Is there an interface implementation in AirSim?

**Comment by TritonSailor** [comment]
I would suggest buying the Ambient Wind System from Epic marketplace to use in your own environment.

**Comment by a11196690** [comment]
@TritonSailor  First, thank you very much for your answer. Is there no interface for wind in AirSim?

**Comment by msb336** [comment]
Airsim has a wind system, but it is purely visual. You will need to develop the physical effects of wind on your own
