### ISSUE TITLE
Can't fly stability in HITL simulation.

### ISSUE THREAD

**Issue by machenxiang** [microsoft/AirSim#1841]
Hello, guys. I'm new here. why my drone can't fly stability in HITL(as shown in the video  https://www.youtube.com/watch?v=IHyahbyg0Qc&feature=youtu.be&fbclid=IwAR1P4VNxI2Q29_qF62IhZN-3pDOkjRghaMswX_pxofPC9qUqeTT5U60SWLo )So i want to ask few questions. First, does airsim HITL simulation need a specific version of airsim and the firmware of PX4? Secondly, do we need to do any setting in PX4 at QGroundControl.Third Must we use RC in HITL simulation?

**Comment by machenxiang** [comment]
my arisim is 1.2.1 ue4 is 4.18.3. below is my json file.
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor",

      "LogViewerHostIp": "127.0.0.1",
      "LogViewerPort": 14388,
      "OffboardCompID": 1,
      "OffboardSysID": 134,
      "QgcHostIp": "127.0.0.1",
      "QgcPort": 14550,
      "SerialBaudRate": 115200,
      "SerialPort": "*",
      "SimCompID": 42,
      "SimSysID": 142,
      "SitlIp": "127.0.0.1",
      "SitlPort": 14556,
      "UdpIp": "127.0.0.1",
      "UdpPort": 14560,
      "UseSerial": true,
      "VehicleCompID": 1,
      "VehicleSysID": 135,
      "Model": "Generic",
      "LocalHostIp": "127.0.0.1"
    }
  }
}

**Comment by machenxiang** [comment]
#303 i have the same question with this

**Comment by lovettchris** [comment]
I am investigating...

**Comment by machenxiang** [comment]
@lovettchris  Hi Chris，thanks for your reply. I'm very looking forward to your result. At the same, I use the latest version of airsim and many kinds of the firmware of PX4(1.8.2 1.4.4 1.5.5 .......) and UE 4.18.3. When we use the 1.4.4and 1.5.5 the drone can successfully but the drone can't fly stable. However, in PX41.8.2 the drone can't takeoff at all.

**Comment by KeyneZzz** [comment]
afaik, if running Airsim, opening QGC at same time would cause unstability of the craft. Thought it may caused by limited bandwidth of the data link between PC and Pixhawk.

**Comment by machenxiang** [comment]
thanks for your reply @KeyneZzz .  but it seems not this problem. I try again in your way, but it seems still didn't work at all.  when I use PX4 1.8.2 it still can't takeoff, PX4 1.5.5 the drone still crazy and in PX4 1.4.4 the drone still crazy and occur this.
![捕获](https://user-images.githubusercontent.com/18185943/55121863-7802a080-5137-11e9-82c2-9471f32e7990.PNG)

**Comment by lovettchris** [comment]
I found the problem with PX4 1.8.2, they removed a module that is needed for HITL mode to work, namely, "pwm_sim_out" and so I built a new version of the v1.8.2 with this module included and takeoff and normally flying works again.  See [OneDrive download](https://1drv.ms/f/s!AoS-ymEfLuCLqudxN4NCgYtf0f3WPQ)
