### ISSUE TITLE
ImageRequest is slow in my Ubuntu machine

### ISSUE THREAD

**Issue by HilmiK** [microsoft/AirSim#1842]
Hello,

In my 1080ti desktop, I am getting 10 fps with 1920*1080 resolution using numpy(uncompressed RGBA images) and python. And I wonder that if it is related with the distribution such as Ubuntu or Windows, or is that normal ?

Thanks.

**Comment by tiax615** [comment]
Hi, also slow in Windows~

**Comment by stavBodik** [comment]
same here ):

**Comment by msb336** [comment]
Image request is unfortunately slow, as rendering in UE4 is single-threaded. It is an issue we are looking into, but will have no major improvements in the near future.
