### ISSUE TITLE
Image sampling interval is not fixed

### ISSUE THREAD

**Issue by JWDu** [microsoft/AirSim#1845]
Hi，everyone，when I collect images using REC button or the python API，the time interval is not fixed from the timestamp of the photo. For my computer, each image will cost about 95 ms to 105 ms, can I make the sampling rate stable such as fixed 100 ms?

**Comment by tiax615** [comment]
Maybe you can decrease clockspeed to cover this issue?
for example, set clockspeed=0.1 in Setting.json. It looks like better.

**Comment by jaymefosa** [comment]
Setting clockspeed = .1 for me throws a Json error "unexpected ."

**Comment by jaymefosa** [comment]
Ah this needs to be 0.1, but it only affects the physics engine apparently, not animations for propellers or other things.

**Comment by ironclownfish** [comment]
This should be done with a timer client-side. Make sure you leave enough time for each capture that your computer can capture each frame that quickly given the level performance.
