### ISSUE TITLE
Hello Drone (simple_flight firmware) with Mission Planner

### ISSUE THREAD

**Issue by ganscool86** [microsoft/AirSim#1846]
Hi,

Is it possible to run the commands in Hello Drone using a GUI based Mission planner like Mission Planner, QGC, etc., when using the Simple_Flight firmware? I am interested in specifying takeoff, land commands through the GUI Mission planner while using the simple_flight firmware. Has anyone worked on it before or can give any tips on how to proceed? Thanks.

**Comment by jonyMarino** [comment]
Hi! Of course it is posible. take a look at [this](https://microsoft.github.io/AirSim/px4_sitl/).
Closing due to age
