### ISSUE TITLE
Question about how to define a new  vehicle

### ISSUE THREAD

**Issue by xindong324** [microsoft/AirSim#1853]
Hello:
I'm now focusing on the reinforcement learning control of helicopter, and i want to use airsim as my simulator. Is that possible for me to define a helicopter model base on the code? how can i do this? Thanks!

**Comment by FL2316** [comment]
老哥整出来了吗

**Comment by ironclownfish** [comment]
@xindong324 please check out this issue about the same thing. Sytelus replies and explains how to do this.
https://github.com/Microsoft/AirSim/issues/838
