### ISSUE TITLE
Compilation errors: C2100 andC2679 illegal indirection and  '+=': no operator found 

### ISSUE THREAD

**Issue by FlyingRobotITU** [Microsoft/AirSim#186]
I am using Visual Studio 2015 update 1 and upon building having following errors. This comes after CLcompile.

- `c:\airsim\airsim\airlib\include\common\common_utils\json.hpp(886): error C2100: illegal indirection[C:\AirSim\AirSim\AirLib\AirLib.vcxproj]`

- `c:\program files (x86)\microsoft visual studio 14.0\vc\include\chrono(769): error C2679: binary '+=': no operator found which takes a right-hand operand of type 'const std::chrono::duration<double,std::ratio<1,1>>' (or there is no acceptable conversion) [C:\AirSim\AirSim\AirLib\AirLib.vcxproj]`

Total errors 7 of similar type

**Complete file containing all the command line errors**
[Build error.txt](https://github.com/Microsoft/AirSim/files/961938/Build.error.txt)
<img width="942" alt="capture" src="https://cloud.githubusercontent.com/assets/28104661/25488890/159f326a-2b1d-11e7-9478-d64525218709.PNG">

**Comment by lovettchris** [comment]
I'm using Update 3, I wonder if they fixed some C++ compiler bugs in Update 3 ?

**Comment by sytelus** [comment]
Update 1 is not supported. I also doubt if it can compile rpclib even if you go past these error.s
