### ISSUE TITLE
Car Path Follow with constant velocity

### ISSUE THREAD

**Issue by Benji15150** [Microsoft/AirSim#1871]
Hello, 

I want the car to move in constant velocity, following the path given by set of waypoints. What would be the easiest way to implement this as car doesn’t seem to have function like moveToPosition? 

Thanks

**Comment by msb336** [comment]
@Benji15150 There is no waypoint following protocol built for carsim, so you will need to implement your own.

The car throttle parameter is tied to the car's acceleration, so you will need to build some form of velocity controller to keep your car moving at a constant velocity. PID would be simplest.

**Comment by TritonSailor** [comment]
You can try using the UE4 pawn function Set Physics Linear Velocity.
