### ISSUE TITLE
Camera Position Change

### ISSUE THREAD

**Issue by MTarekShaaban** [Microsoft/AirSim#1874]
I need to put the camera on a certain height in the car simulator without rebuilding the source code again, anyone can please help?

**Comment by msb336** [comment]
You can place cameras on your vehicle at user-defined locations through your settings.json file. See docs [here](https://microsoft.github.io/AirSim/docs/settings/#airsim-settings)

**Comment by madratman** [comment]
you can also see an example here https://github.com/Microsoft/AirSim/issues/1732#issue-402292365
