### ISSUE TITLE
How to use DQNcar.py?

### ISSUE THREAD

**Issue by Spatialghost** [Microsoft/AirSim#1875]
Hi, im new in AirSim. I have some question, how to use DQNcar.py, how to collect data, how to train it?

Thank you!

**Comment by msb336** [comment]
You can find some documentation on how the DQN car script works [here](https://microsoft.github.io/AirSim/docs/reinforcement_learning/#rl-with-car)

**Comment by eliork** [comment]
@msb336 The link is broken
