### ISSUE TITLE
How to get ground truth for LiDAR data?

### ISSUE THREAD

**Issue by orangeccc** [microsoft/AirSim#1878]
I want to know how to get the ground truth labels for each LiDAR point through Python Client.Thanks.

**Comment by madratman** [comment]
You mean the object label associated with each lidar point?

**Comment by orangeccc** [comment]
> You mean the object label associated with each lidar point?

yes.

**Comment by orangeccc** [comment]
@madratman  yes.

**Comment by vishal-prgmr** [comment]
@orangeccc, Just fixing issues and debugging this at the moment. Once done, I will submit a PR which will return the **labels** as a fourth variable in the LIDAR struct for review on Monday.

**Comment by orangeccc** [comment]
@vishal-prgmr Thanks !
