### ISSUE TITLE
ReadMe suggestion

### ISSUE THREAD

**Issue by coldwarrior5** [microsoft/AirSim#1882]
I have written a complete step by step guide how to get AirSim going in UE 4.21.
You may or may not want to adjust the poorly written documentation so this is for everybody that might have issues following the documentation.
[https://www65.zippyshare.com/v/eNSuAWwF/file.html](
https://www65.zippyshare.com/v/eNSuAWwF/file.html)

**Comment by love-mj** [comment]
Can Airsim Run Normally at ue4.21 ？

**Comment by coldwarrior5** [comment]
For me at least it worked, thus I wrote the steps I took to make it work.

**Comment by love-mj** [comment]
Thank you. I just tried it and it works.

**Comment by msb336** [comment]
please commit a pr with the changes to the readme you would like to incorporate

**Comment by jonyMarino** [comment]
I suggest closing this issue because the current documentation is for UE 4.24
