### ISSUE TITLE
New Wind Feature Only a Visualization or Really Adds a Force?

### ISSUE THREAD

**Issue by ardianumam** [Microsoft/AirSim#1883]
There is a "Wind" feature in [here](https://microsoft.github.io/AirSim/#weather-effects). Is this: (i) only a visualization of the environment, or (ii) really adding a force to the vehicle (so that the vehicle may be moved or dragged due to the wind)? I'd like to have a wind to represent a disturbance as in a real scenario.

> My env:
> 
> UnrealEngine ver. 4.18, AirSim master branch (update 2019/04/9), python 3.5, Ubuntu 16.04 64-bit.

Thanks.

**Comment by msb336** [comment]
@ardianumam wind is currently only aesthetic and does not apply any forces to the vehicles in the scene.
