### ISSUE TITLE
Problem with tracing, in Computer Vision Mode

### ISSUE THREAD

**Issue by JunzheJosephZhu** [microsoft/AirSim#1885]
When using computer vision mode, I used sin(t) for x and cos(t) for y coordinates. But sometimes unreal just breaks and VIsual Studio tells me there's something wrong with tracing. What's the problem?

**Comment by msb336** [comment]
@JunzheJosephZhu can you provide a little more information?

When you say you used sin(t) for x and cos(t) for y, what API are you using, and what is your intended functionality?

Also, please attach the full error message to this thread.

**Comment by jonyMarino** [comment]
@JunzheJosephZhu  Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
