### ISSUE TITLE
Windshield reflections

### ISSUE THREAD

**Issue by douglas125** [microsoft/AirSim#1887]
Is it possible to simulate reflection of the environment in the windshield?

Sometimes these reflections are a problem for object detection algorithms and it would be useful to be able to create them in the simulated environment,

**Comment by gurkanctn** [comment]
This would likely require modeling the inside of the vehicle, together with the windshield, and the chassis (body), to allow for sunlight-shade effects, that would be captured by the camera.

**Comment by msb336** [comment]
This is not a feature in development, but please feel free to contribute and open a PR!
