### ISSUE TITLE
Precompiled binaries storage

### ISSUE THREAD

**Issue by jeyvison** [Microsoft/AirSim#189]
Hey guys, i'd like to suggest the binaries to be in github. I know.... ,i know...,  git wasn't made for that. But it works and comparing to other forms of storage we have today(which is **none**) it would be really helpfull for us whom doesn't want to compile the code.

I may suggest amazon S3 too. it's a cheap kind of storage but would involve some costs. maybe some open source mirror  would help too but i dont know exactly how it works.

Well, thanks for the amazing tool :smile:

**Comment by lovettchris** [comment]
Yeah, git is not a great place for that, but I did put a copy of LanscapeMountains up on [OneDrive](https://1drv.ms/f/s!AoS-ymEfLuCLo-Vl5wVsj_yv7pcCuA).  But the real trick is getting those bits to be maintained.  What we really need is a build system that spits out new cooked binaries every day...

**Comment by sytelus** [comment]
As @lovettchris has suggested, we are exploring various options and planning to release official binaries soon!

**Comment by jeyvison** [comment]
Got it! I'd  suggest to maybe use travis and OneDrive(or google drive) API to host the binaries too.  If you need a hand on it, let me know.

**Comment by clovett** [comment]
Yeah, I wonder if Travis supports google api already...  We have Travis running and a checked in .travis.yml file...

**Comment by jeyvison** [comment]
[dpl](https://github.com/travis-ci/dpl/) has some providers for deployment. One of them is Github releases. Maybe it worths a shot. if not ,then we could think on write a custom provider.
