### ISSUE TITLE
No module named '__main__.client'; '__main__' is not a package

### ISSUE THREAD

**Issue by petervlad** [Microsoft/AirSim#1895]
When I try to run PythonClient I get this error message in airsim/__init__.py
No module named '__main__.client'; '__main__' is not a package
<img width="517" alt="Capture" src="https://user-images.githubusercontent.com/32743023/56305837-b04f3a80-6149-11e9-9b9e-742274ca80e3.PNG">

**Comment by madratman** [comment]
Did you do `pip install airsim`
Alternatively, do a `cd AirSim\PythonClient`, followed by `python setup.py install`
