### ISSUE TITLE
Can I Use This Wind Plugin to Add Wind Disturbance to The Vehicle?

### ISSUE THREAD

**Issue by ardianumam** [Microsoft/AirSim#1899]
Hi,
So far, there is no wind disturbance option in AirSim applied to the vehicle. The Unreal Engine's native wind object "Wind directional source" will only affect apex cloth and speedtree objects. I find a commercial wind system plugin [here](https://www.unrealengine.com/marketplace/en-US/slug/ambient-wind-system) that works for all possible objecs, including: (i) physics, (ii) apex cloth, (iii) Speedtree, (iv) particle effects and (v) simple grass vertex shader. Is the vehicle in AirSim built using one of them (maybe physics?) so that I can use this plugin to apply a wind disturbance? It's a blueprint plugin. The video demo can be seen [here](https://www.youtube.com/watch?v=bo3eCEii10g&list=PL4UXbXvzKxGL6-fLyT4u5VxM7XWmvE9dv&index=3&t=240s).

Thanks.

**Comment by msb336** [comment]
@ardianumam the wind in the current weather api is purely aesthetic.
