### ISSUE TITLE
throttle, brake value range?

### ISSUE THREAD

**Issue by beomsik-landingai** [microsoft/AirSim#1900]
Per this code, it sounds like throttle and brake range is 1 to -1. 

    struct CarControls {
        float throttle = 0; /* 1 to -1 */
        float steering = 0; /* 1 to -1 */
        float brake = 0;    /* 1 to -1 */
        ...
    }

But from my testing, it seems it just take absolute value from throttle and brake. I couldn't see any difference when I applied 0.5 or -0.5 for both values. Did I test something wrong or are they really just used with absolute value? 

Also, from this code, 

        void set_throttle(float throttle_val, bool forward)
        {
            if (forward) {
                is_manual_gear = false;
                manual_gear = 0;
                throttle = std::abs(throttle_val);
            }
            else {
                is_manual_gear = false;
                manual_gear = -1;
                throttle = - std::abs(throttle_val);
            }
        }

I was under the impression that throttle with negative value means going reverse, is it not true? also if the ranges are indeed 1 to -1, what -1 for brake input means?

**Comment by msb336** [comment]
It is subtle, but throttle values between 0 and 1 do affect max speed and acceleration. When I have a free moment I'll build some step response graphs at different throttles and post them. The sign of throttle input only matters if you are not using the manual gear option. (negative putting you into -1) and forward putting you into 0.

I suspect the -1 in the brake range is an oversight, and should actually be a 0.
