### ISSUE TITLE
moveByVelocityAsync Duration not working

### ISSUE THREAD

**Issue by stavBodik** [microsoft/AirSim#1902]
Trying to rotate drone 180 degrees slowly,
No matter what duration I am using, it is moving with same speed :

float duration = 100000.0f;
client.moveByVelocityAsync(0, 0, 0, duration, DrivetrainType::MaxDegreeOfFreedom, YawMode(false, 180));

std::this_thread::sleep_for(std::chrono::duration(duration));

Edit0 : 
After reading your code I understand that the duration value is for "TimeOut" like move until timeout occurred .

So how do I rotate the drone Yaw angle in certain speed ? 

Edit1 :
Think I found it, will try this function : client.rotateToYawAsync()

. . .

**Comment by jonyMarino** [comment]
@stavBodik were you avle to solve the issue?
