### ISSUE TITLE
How to set roi?

### ISSUE THREAD

**Issue by Spatialghost** [Microsoft/AirSim#1903]
Hi, how to set roi for PythonClient\imitation_learning\train_model.py?

**Comment by msb336** [comment]
ROI gets set in these two lines here:

https://github.com/Microsoft/AirSim/blob/1fd6a3fc311c704bbbb0b2b6b245e8fa0ba26c8b/PythonClient/imitation_learning/train_model.py#L51-L54

you can modify the values to fit your needs accordingly.
