### ISSUE TITLE
https://microsoft.github.io/AirSim/docs/docker_ubuntu is broken

### ISSUE THREAD

**Issue by desireB** [Microsoft/AirSim#1904]
The link https://microsoft.github.io/AirSim/docs/docker_ubuntu about the instructions for docker is broken.

Thank you.

**Comment by madratman** [comment]
ah yes, sorry about that! The mkdocs part is not in our travis CI yet. We'll fix it. 
Till then, that link points to this markdown file [https://github.com/Microsoft/AirSim/blob/master/docs/docker_ubuntu.md](url)
and the docker folder is here https://github.com/Microsoft/AirSim/tree/master/docker

**Comment by desireB** [comment]
Thank you!
