### ISSUE TITLE
Visual Studio Shared Memory Exception

### ISSUE THREAD

**Issue by nibill** [Microsoft/AirSim#191]
Maybe I should mention that I have zero experience with drones whatsoever, so I apologize for silly questions.

Setup:
Intel Xeon CPU E5-2620 v4 @2.10GHz
64GB RAM
NVIDIA GeForce 1080
Windows Server 2016 Datacenter (I really hope that's not what causes all the problems).

When I build the project in VS or after the build when I click "play" in the engine, I get the following error:
![vs_exception](https://cloud.githubusercontent.com/assets/6297916/25566860/ab3798c2-2de2-11e7-96db-d77d69732303.jpg)
When I click "continue" the project still loads fine though (at least as far as I can tell.

Any idea?

**Comment by lovettchris** [comment]
I get this too, but only when I have asked VS to show me ALL C++ exceptions.  It is safe to clear "Break when this exception type is thrown" and ignore it.
