### ISSUE TITLE
Semantic labels of Point Cloud 

### ISSUE THREAD

**Issue by vishal-prgmr** [Microsoft/AirSim#1917]
Hi Community,

I am interested in associating the point cloud with the semantic labels. I was digging into the UnrealLidarSensor.hpp to see if I can tap out the associated actor from the ray tracing function.

Has anyone else done this? Any heads up ? 

Thank You

**Comment by vishal-prgmr** [comment]
Will submit a PR now for you guys to review it.

**Comment by CharlieRuan0130** [comment]
> Will submit a PR now for you guys to review it.



> Hi Community,
> 
> I am interested in associating the point cloud with the semantic labels. I was digging into the UnrealLidarSensor.hpp to see if I can tap out the associated actor from the ray tracing function.
> 
> Has anyone else done this? Any heads up ?
> 
> Thank You

Hi v-prgmr, I am also looking into giving point cloud data labels. I am wondering if you have achieved it. If so, could you provide some insights on how to do that? Thank you!
