### ISSUE TITLE
无法执行VS

### ISSUE THREAD

**Issue by HelenWang224** [Microsoft/AirSim#1918]
<img width="728" alt="1" src="https://user-images.githubusercontent.com/49124304/56807022-36f9cb00-6860-11e9-8bba-cc4776c1c78b.PNG">
what’s the problem?

**Comment by vishal-prgmr** [comment]
I cannot understand. Could you describe more. @HelenWang224

**Comment by HelenWang224** [comment]
I can't use "build.cmd" order
