### ISSUE TITLE
QGroundControl/DroneShell problem

### ISSUE THREAD

**Issue by nibill** [Microsoft/AirSim#192]
As these problems are totally different than the other, I thought it is ok to open a new issue.

I should mention that I have zero drone experience. No RC used.

Setup:
Intel Xeon CPU E5-2620 v4 @2.10GHz
64GB RAM
NVIDIA GeForce 1080
Windows Server 2016 Datacenter (I really hope that's not what causes all the problems).
Pixhawk PX4 -  Firmware 1.5.5

In the QGroundControl-application I have the following error: 
![qgroundcontrol_error2](https://cloud.githubusercontent.com/assets/6297916/25590210/d390a0de-2eaf-11e7-8a38-9c7763aa66cc.jpg)

As for the airframe I have selected the Simulation HIL Quadcopter X as mentioned in the video. My pixhawk is blinking blue and updated to the newest firmware. No logs available in QGroundControl.

When I click play in the engine, it looks like this:
![engine_error2](https://cloud.githubusercontent.com/assets/6297916/25589970/e8a3f968-2eae-11e7-869c-7c7f6b13e2af.jpg)

The drone shell:
![droneshell_error](https://cloud.githubusercontent.com/assets/6297916/25590075/49ecb58e-2eaf-11e7-984e-d826c55ea2a7.jpg)

The Pixhawk changes to white/purple-ish blinking, in case that matters. Might be something little, but I really have no clue.

Thanks!

**Comment by lovettchris** [comment]
yes, I just found a bug in our gps code, it is not sending enough gps messages to PX4, we are working on a fix, stay tuned.

**Comment by nibill** [comment]
alright, thanks. I'll wait for a fix then.

As for the QGroundControl, do I even have to care about having some red? I only use the simulations...

And should I worry that I don't see a green "Loading settings from..." after I click play in the engine?

Thank you

**Comment by lovettchris** [comment]
For QGC you need to select this airframe, that will stop it complaining about uncalibrated sensors:
![image](https://cloud.githubusercontent.com/assets/18707114/25594090/18687e84-2e74-11e7-8856-4c78bde5c8fd.png)

**Comment by lovettchris** [comment]
The [issue with gps messages ](https://github.com/Microsoft/AirSim/commit/7c18f3548e1b025c29f8b174764993c7665c6619) is now fixed.  Please try again and reopen this issue if you still have a problem, thanks.

**Comment by nibill** [comment]
Thanks for the quick fix. I've created a whole new project, but now I'm stuck here:
![droneshellerror2](https://cloud.githubusercontent.com/assets/6297916/25675233/f4a60e82-303d-11e7-8b04-cb95acc98396.jpg)

In the engine it's fine now, I'd say
![engineerror3](https://cloud.githubusercontent.com/assets/6297916/25675238/fd54431e-303d-11e7-9194-3263416036a2.jpg)

As for QGroundControl, I have selected the correct airframe, but it still complains about Radio and Flight Mode
![qgroundcontrollerror3](https://cloud.githubusercontent.com/assets/6297916/25675273/22ce9bc6-303e-11e7-9259-7eb7e1667d31.jpg)

Any ideas`? Thank you

**Comment by lovettchris** [comment]
So this time I see DroneShell is not getting past "Contacting DroneServer" this is probably because you need to start DroneShell AFTER you start DroneServer (in this case the server is in the Unreal app).    Unfortunately, it currently does not have any retry logic, so if it doesn't find the server it gets stuck, that is on the list of things to fix, but for now just restart DroneShell.    So this means every time you click Stop/Start in the Unreal Editor you need to restart the DroneShell app.

**Comment by lovettchris** [comment]
As for the Radio calibration step, if you plan to use a Remote Control radio as I show in [this video](https://www.youtube.com/watch?v=HNWdYrtw3f0&feature=youtu.be), then you should calibrate the radio with your pixhawk using QGroundControl.  You can also set some handy flight modes using a switch on your radio.  But you can use AirSim without a radio and ignore the above red dots in QGC.

**Comment by nibill** [comment]
I fixed it now.
In case anyone having the same/similar problem: I used to have my project split up over two partitions. AirSim.sln was on C:\ while my project was on D:\. I guess they couldn't see each other. I created a new project on C:\, and now I can reach the DroneServer. That's all I've changed.
