### ISSUE TITLE
Building AirSim on Win7 + VS2017 is possible!

### ISSUE THREAD

**Issue by jaymefosa** [microsoft/AirSim#1921]
All of the issue threads that I looked at were already closed and after spending 2.5 days piecing everything together, it seems like a waste not to provide hope to others. The final working config is on Win7 + Unreal 4.18.3 + VS2017 + AirSim git from this date.

I ran into many errors while trying different things to run build.cmd, such as:
 
- Expected *.h to be first header included.
- Fatal error C1083: Cannot open include file: 'Eigen/Dense': No such file or directory
- Fatal error C1083: Cannot open include file: 'corecrt.h': No such file or directory 
- LNK1181: cannot open input file 
- Winsock2.h not found
- No CMAKE_C_COMPILER could be found
- LNK1104 cannot open file 'ucrtd.lib' 
- LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
- LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL'
- The following modules are missing or built with a different engine version: UE4Editor-AirSim.dll

The worst part was that under some configurations it would build but then I would get that last error when trying to open the project with Unreal.

The No CMAKE_C_COMPILER error was particularly frustrating at one point. I thought I solved it. I uninstalled VS2017 completely and reinstalled it. Then I tried to run build.cmd and it found the compiler and crashed out on a different error. But then I tried to install some SDK or something, and then the no CMAKE_C_COMPILER error popped up again. 

So here are the steps that worked for me for installing:

1) Complete Uninstall of all VCredists and all SDKs
2) Installing VS2017 community with the following packages:

![image](https://user-images.githubusercontent.com/92468/56858680-31fc5f00-69b9-11e9-813a-071b49a3cd4b.png)

![image](https://user-images.githubusercontent.com/92468/56858684-40e31180-69b9-11e9-8124-fc4a036e8814.png)

![image](https://user-images.githubusercontent.com/92468/56858687-4d676a00-69b9-11e9-9ccb-96e25b66d47a.png)

It was actually a Chinese blog that put me on to a couple of these. As you can see, this is using Win8.1 SDK instead of Win10.

Further, I didn't use the CMAKE tools provided by Visual Studio, and none of Windows 10SDKs are installed. I used Cmake 3.9 downloaded manually from their site.

FURTHER: Win SDK 8.1 had to be uninstalled and reinstalled using the 'winsdk' tool, also downloaded manually from Microsoft. The folder size grew by a few hundred MB after doing this.

Finally: Using the _regular_ windows cmd prompt, locate the VisualStudio2017\Common7\Tools\VsDevCmd.bat (Associated with Developer Command Prompt for VS 2017) and run it with the arguments -arch=amd64 -winsdk=8.1

Then navigate to the git cloned AirSim directory, run clean_rebuild.bat, and it was able to build..

But, I still got the "The following modules are missing or built with a different engine version: UE4Editor-AirSim.dll" error when trying to open the project directly with Unreal. However, building and running from Visual Studio worked. I now have my quad copter sitting and ready to.. actually get to work.

It does raise the specter of a question, when it built successfully on some other random configuration, would it have helped to try to just run the project from Visual Studio as opposed to opening it via Unreal?

Good luck to others and thanks to the many people who posted their error reports before.

**Comment by saihv** [comment]
Thanks for the detailed description! If you are interested, please feel free to submit a PR to extend our existing documentation.

> It does raise the specter of a question, when it built successfully on some other random configuration, would it have helped to try to just run the project from Visual Studio as opposed to opening it via Unreal?

Typically on Windows, we recommend building from Visual Studio instead of letting UE build it directly.
