### ISSUE TITLE
UE 4.18 reduces quality of the mesh!! why? how to manage it?

### ISSUE THREAD

**Issue by Supaple-x** [microsoft/AirSim#1923]
Hi guys, 
I fly a lot. and after drone survey and successfully built model (beautiful and high qualified) I try to put a map into AirSim and...
UE wastes all my work! It makes mesh simple. And unbelievable ugly :(
Is there way to mange this?

thanks

**Comment by RVBldr** [comment]
It would be great to see some screen shots as well as what that environment looks like in the UE editor.

**Comment by msb336** [comment]
Unreal might be [auto-LODing](https://docs.unrealengine.com/en-US/Engine/Content/Types/StaticMeshes/HowTo/AutomaticLODGeneration/index.html) your mesh. This issue seems isolated to the Unreal Engine, so you may want to post your issue on [unreal's forums](https://forums.unrealengine.com/)

**Comment by Supaple-x** [comment]
Thanks guys! I've found auto-LODing. It seems that I had not enough resources on my notebook.
I bought powerful station and now it works perfect!
