### ISSUE TITLE
Editing pre-built environments for own projects

### ISSUE THREAD

**Issue by eds89** [microsoft/AirSim#1946]
Hello. I'd like to edit the Neighbourhood environment for my own custom project. Where can I find its source code? Should I try to reverse-engineer it from the binary?

**Comment by msb336** [comment]
@eds89 Unfortunately, the Neighborhood environment contains non open-source content, so we can't make the source code available to our users. You are more than welcome to construct your own custom environments (and share the binaries with all your pals at AirSim!)

**Comment by eds89** [comment]
How much would it cost to acquire a license for the neighborhood
environment? By the way, is there any environment available with exception
of the 'Blocks' environment?

**Comment by msb336** [comment]
@eds89 we do not distribute licenses our environments. Blocks is the only environment users have full access to.

If you are looking to add noise to sensor data or simulate an adversarial attack, doing so to the sensor data after it has been received by the client will be your path of least resistance.

**Comment by eds89** [comment]
Hi. If I change the sensor data after it has been received by the client,
how can I assess how the DNN behaves. The way I modelled the adversarial
attacks are through computer-graphics effects (which are implemented as
post-processing materials in Unreal).
