### ISSUE TITLE
I'd like to change the model of the unmanned vehicle into an unmanned ship. Is that all right?

### ISSUE THREAD

**Issue by makeisbad** [microsoft/AirSim#1947]
# Read This First

## If you are reporting a bug
* Make sure to write **all reproduction steps**
* Include full error message in text form
* Search issues for error message before filing issue
* Attach screenshot if applicable
* Include code to run if applicable

## If you have question
* Add clear and concise title
* Add OS, AirSim version, Python version, Unreal version if applicable
* Include context on what you are trying to achieve
* Include details of what you already did to find answers

**What's better than filing issue? Filing a pull request :).**

------------------------------------ (Remove above before filing the issue) ------------------------------------

**Comment by msb336** [comment]
By unmanned ship, do you mean a water-based vehicle? if so, it will take some work for you to simulate the physics of a vehicle in water. If you mean to just replace the SUV mesh with a custom mesh, you are able to do that as well. You can see more on custom vehicles and pawn paths [here](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#pawnpaths)
