### ISSUE TITLE
UE4 Build Error after windows 10 update...

### ISSUE THREAD

**Issue by Focke-Wulf** [Microsoft/AirSim#195]
Hello guys:
This problem is just happened after windows 10 update.. it works well before and after it shows this error..

![capture](https://cloud.githubusercontent.com/assets/26343300/25648366/5da8ce4a-300e-11e7-90d3-d0e50f4c82c3.PNG)

the Error at mixer.hpp
![capture1](https://cloud.githubusercontent.com/assets/26343300/25648368/60a0ea1a-300e-11e7-847a-b0c9099256c2.PNG)

currently i am using VC++ 2017..

**Comment by lovettchris** [comment]
We've been using VS 2015 Update 3.  But when updating airsim bits, it is often good to run this script to "clean" your unreal project binaries, update AirSim bits, then regenerate the Visual Studio project from the *.uproject.  I put this in a script called "update_airsim.cmd":

`
pushd %~dp0
set AIRSIM=D:\git\AirSim

echo Cleaning old binaries...
rd /s/q Binaries
rd /s/q Intermediate
rd /s/q Saved
rd /s/q Plugins\AirSim\Binaries
rd /s/q Plugins\AirSim\Intermediate
rd /s/q Plugins\AirSim\Saved

echo Updating Airsim bits...
if NOT exist %AIRSIM%\Unreal\Plugins\AirSim goto :nobits
if not exist Plugins\AirSim mkdir Plugins\AirSim
robocopy /MIR %AIRSIM%\Unreal\Plugins\AirSim Plugins\AirSim 

echo Regenerating Visual Studio projects..
"D:/Program Files/Epic Games/UE_4.15/Engine/Binaries/DotNET/UnrealBuildTool.exe"  -projectfiles -project="D:/UnrealProjects/4.15/AirSimNHTest/AirSimNHTest.uproject" -game -rocket -progress

pause
goto :end

:nobits
echo Could not find %AIRSIM%\AirSim\Unreal\Plugins\AirSim
echo Please run build.cmd in the AirSim directory.

:end
popd
`
