### ISSUE TITLE
HITL - Best flight controller and remote controller combination?

### ISSUE THREAD

**Issue by kovar-ursa** [microsoft/AirSim#1950]
We are working on using PX4 flight controllers to generate log files for off-board analysis. We would like to do both:
1) HITL Pixhawk
2) HITL Pixhawk and HITL remote controller

The recommended Pixhawk FC is no longer (easily) available. What is a good FC that can be mounted on a board and run via AC power?

We would like to directly connect the remote controller to the flight controller via a cable and avoid the RF link. Are there any FC/RC combinations that are known to support this?

I've read a fair number of posts and found a lot of out of date information or pointers to hardware that suggests that you can connect the USB port on a TARANIS X9D PLUS to a FC but wasn't any more specific than that.

Thank you very much.
-David

**Comment by kovar-ursa** [comment]
We are working on using PX4 flight controllers to generate log files for off-board analysis. We would like to do both:
1) HITL Pixhawk
2) HITL Pixhawk and HITL remote controller

The recommended Pixhawk FC is no longer (easily) available. What is a good FC that can be mounted on a board and run via AC power?

We would like to directly connect the remote controller to the flight controller via a cable and avoid the RF link. Are there any FC/RC combinations that are known to support this?

I've read a fair number of posts and found a lot of out of date information or pointers to hardware that suggests that you can connect the USB port on a TARANIS X9D PLUS to a FC but wasn't any more specific than that.

Thank you very much.
-David

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
