### ISSUE TITLE
How can I build Airsim in Ubuntu16.04？I can‘t find where to download UE4,its page show 404.

### ISSUE THREAD

**Issue by machenxiang** [microsoft/AirSim#1952]
![QQ截图20190510112114](https://user-images.githubusercontent.com/18185943/57500356-b3d37d00-7315-11e9-912c-0d034f9ccac6.png)
UE4 page show 404

**Comment by msb336** [comment]
You can find instructions for building [here](https://microsoft.github.io/AirSim/docs/build_linux/).

In order to pull Unreal Engine, you need to be [registered with Epic Games](https://docs.unrealengine.com/latest/INT/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/1/index.html)
