### ISSUE TITLE
I have same issue also in `DQNdrone.py`

### ISSUE THREAD

**Issue by mish1102** [microsoft/AirSim#1968]
I have same issue also in `DQNdrone.py`

Got the following error while running DQNdrone.py for RL 

Traceback (most recent call last):
  File "DQNdrone.py", line 511, in <module>
    agent = DeepQAgent((NumBufferFrames, SizeRows, SizeCols), NumActions, monitor=True)
  File "DQNdrone.py", line 270, in __init__
    self._memory = ReplayMemory(memory_size, input_shape[1:], 4)
  File "DQNdrone.py", line 35, in __init__
    self._states = np.zeros((size,) + sample_shape, dtype=np.float32)
MemoryError

_Originally posted by @subinlab in https://github.com/microsoft/AirSim/issues/1525#issuecomment-491571769_

**Comment by msb336** [comment]
lets track this issue in #1525
