### ISSUE TITLE
Multi drone examples: reaction on collision

### ISSUE THREAD

**Issue by MelSoS** [microsoft/AirSim#1969]
Dear all, 

I'd like to implement a multi drone example, where all of them move on random directions and random duration. 

I would use smth. like 

- `client.moveByVelocityZAsync(....)` or
- `client.moveToPositionAsync(...)`

Now I have two questions: 

1. How is it possible to react on a collision for the drone during movement to a position or during movement with a certain velocity?
2. Is it possible for the drone to move as long as a collision happens? Is there something where I can avoid it (internal collision avoidance algorithm)?

Thank you and best regards, 
MelSoS

**Comment by msb336** [comment]
@MelSoS there are no pre-baked collision avoidance algorithms in our code, but there are plenty of research examples out there worth taking a look at. As far as collision detection is concerned, there is an API call `client.has_collided()` which returns a boolean based on the current state of the agent. You can use this call to trigger reactions between colliding drones.
