### ISSUE TITLE
Generate map by using camera's images

### ISSUE THREAD

**Issue by viet2411** [microsoft/AirSim#1971]
Deal all,
I'm working on making a car in Airsim that can generate a 2D map using only camera's images(generally adding objects to map by camera's information). Can any body suggest a method to generate a small map in Airsim?
Thank you and best regards.

**Comment by gurkanctn** [comment]
check out the following key words: "visual odometry slam"

Here's a link to several links related to visual slam:
[Awesome list of Visual SLAM](https://github.com/tzutalin/awesome-visual-slam)

Doing it in Airsim requires you to handle the images and running your Visual SLAM algorithm.
