### ISSUE TITLE
github repository for UnrealEngine unavailable

### ISSUE THREAD

**Issue by galgyeony** [microsoft/AirSim#1972]
The github repository(i.e., https://github.com/EpicGames/UnrealEngine) for cloning UnrealEngine seems no longer available.

What is the available repository for linux build?

Thanks in advance.

**Comment by msb336** [comment]
Follow the steps listed [here](https://microsoft.github.io/AirSim/docs/build_linux/) to build airsim on linux. Notice that the first step is to [register with epicgames](https://docs.unrealengine.com/latest/INT/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/1/index.html). This is required to get access to the UnrealEngine repository.
