### ISSUE TITLE
Error when ./build.sh

### ISSUE THREAD

**Issue by DrDumbenstein** [microsoft/AirSim#1974]
[  4%] Building CXX object MavLinkCom/CMakeFiles/MavLinkCom.dir/home/drdumbenstein/Git_Projects_Clones/AirSim/MavLinkCom/src/AdHocConnection.cpp.o
clang: error: no such file or directory: 'Projects'
clang: error: no such file or directory: 'Clones/AirSim/llvm-build/output/include/c++/v1'
clang: error: no such file or directory: 'Projects'
clang: error: no such file or directory: 'Clones/AirSim/llvm-build/output/include/c++/v1'
MavLinkCom/CMakeFiles/MavLinkCom.dir/build.make:62: recipe for target 'MavLinkCom/CMakeFiles/MavLinkCom.dir/home/drdumbenstein/Git_Projects_Clones/AirSim/MavLinkCom/common_utils/FileSystem.cpp.o' failed
make[2]: *** [MavLinkCom/CMakeFiles/MavLinkCom.dir/home/drdumbenstein/Git_Projects_Clones/AirSim/MavLinkCom/common_utils/FileSystem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
clang: error: no such file or directory: 'Projects'
![60483522_1208952645932278_1213363256513527808_n](https://user-images.githubusercontent.com/40032759/58016407-70d38f80-7af5-11e9-8b09-5e033e6ce476.j

**Comment by msb336** [comment]
@DrDumbenstein try:
- cleaning out your repo completely `git clean fdx`  **This is will delete any local files**
- updating your branch to the latest available (if on AirSim/master `git pull`)
- rebuilding with `./build.sh`
