### ISSUE TITLE
Update Blocks Project With New AirSim

### ISSUE THREAD

**Issue by Spiraseven** [microsoft/AirSim#1977]
Hi All, I have modified an older version of the Blocks project, probably 5-6 months old . I recently pulled down from master the current version of AirSim. I rebuilt it using the setup and build scripts and then copied my old Blocks project into the Unreal/Environment folder. I then replaced the Plugins folder in my Blocks project with the new Plugins folder from the newly built AirSim. I though this was all I had to do but when I try to use the new getImuData() method I get a error:

rpclib: server could not find function getImuData with argument count 2

My guess is that I have not updated my project with the newly built AirSim properly. Any thoughts?

**Comment by msb336** [comment]
That issue looks like it has to do with an outdated airsim plugin. Have you cleared out all of the `Intermediate` and `Binaries` folders in the `project` and `plugin` directories? Unreal will try to use whatever files it finds in those folders before it attempts to rebuild the plugin or project.
