### ISSUE TITLE
Changing Resolution on the fly

### ISSUE THREAD

**Issue by petergerten** [microsoft/AirSim#1978]
Is there a way to change the image resolution on the fly?
I would like to get images in 1280x720 resolution and process them as a video stream and from time to time take a "still image" with the camera using a much higher resolution (5472x3648).

**Comment by msb336** [comment]
@petergerten you can do this by creating more than one camera in settings.json (https://github.com/microsoft/AirSim/blob/master/docs/settings.md#available-settings-and-their-defaults), and specifying the resolution of each camera separately. You can call your desired camera using `simGetImage("{desired camera},", {desired image type})`
