### ISSUE TITLE
How to use lookAt() in pythonclient

### ISSUE THREAD

**Issue by Lylist** [microsoft/AirSim#1982]
use airsim on windows10,and Ue4.18, i want to make drone always look at a point. And i find a funtion in vectormath.hpp is lootAt() , but how to use it in pythonclient?

**Comment by madratman** [comment]
That function is not exposed to the python client. You'll have to re-implement it in python. Here's a tutorial - https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/lookat-function
