### ISSUE TITLE
some question about the camera Simulator

### ISSUE THREAD

**Issue by mariomister** [microsoft/AirSim#1987]
Hello everyone：
  I want to know how the camera simulator is implemented. But I did not find the relevant instructions，Where can I find relevant information?

The most sincere gratitude

**Comment by msb336** [comment]
[here is the documentation on image apis](https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md#image-apis)

**Comment by ironclownfish** [comment]
Hi, do you need any further help with the camera simulator?
