### ISSUE TITLE
vehicle %s was not initialized

### ISSUE THREAD

**Issue by PeixinLiu** [microsoft/AirSim#1988]
Hello everyone:
 I'm trying to use HIL and a Joystick controller .but it shows that "vehicle %s was not initialized" ,as follows:
![QQ截图20190528182521](https://user-images.githubusercontent.com/23660848/58471371-4bd6c080-8176-11e9-86e0-57492af267a9.png)

And this is my settings:
    {
      "WindowID": 2,
      "ImageType": 6,
      "CameraName": "4",
      "Visible": true
    }
  ],
  "SimMode": "Multirotor",
  "DefaultVehicleConfig": "PX4",
  "Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor",
      "LogViewerHostIp": "127.0.0.1",
      "LogViewerPort": 14388,
      "OffboardCompID": 1,
      "OffboardSysID": 134,
      "QgcHostIp": "127.0.0.1",
      "QgcPort": 14550,
      "SerialBaudRate": 115200,
      "SerialPort": "*",
      "SimCompID": 42,
      "SimSysID": 142,
      "SitlIp": "127.0.0.1",
      "SitlPort": 14556,
      "UdpIp": "127.0.0.1",
      "UdpPort": 14560,
      "UseSerial": true,
      "VehicleCompID": 1,
      "VehicleSysID": 135,
      "Model": "Generic",
      "LocalHostIp": "127.0.0.1"
    }
  }
}

The most gratitude

**Comment by xiaolin360** [comment]
I encounter the same problem as you when i plug in the Pixhawk 4 hardware, but this problem disappears when i plug in the Pixhawk 2.4.8 hardware.
And this is my settings:
{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor"
    }
  }
}
I don't know how to solve this problem and am seeking for more help.

**Comment by heleidsn** [comment]
Hi, you need to close your Qgroundcontrol after the initial setup. Then you can try to connect the Pixhawk and restart your UE project.

Hope it can help you.

**Comment by kaioforte** [comment]
There is another solution? Even when I close Qgroundcontrol after the initial setup, the problem persists "vehicle %s was not initialized". This happens on Windows, if I test on Linux it says "connected to px4" but Unreal engine freezes and crashes. I use a pixhawk 4 mini with a firmware version of 1.8.2. I've tried with the 1.9.2 (latest stable version) but it is the same.
I saw this issue https://github.com/microsoft/AirSim/issues/1841 where @lovettchris fixes a missing module in version 1.8.2. It works, but that build is for fmu-v2 and I think it is not supported by pixhawk 4 (fmu-v5). Do you think it is a similar problem? And you could take a look in it or tell me how to do that?
Ps: I use the same settings as xiaolin360.

**Comment by cnun02** [comment]
Airsim with PX4 #2246
I had the same problem. But now it is neatly solved.

**Comment by Rufio-Boj** [comment]
I found a way of making it work with PX4 v5, see #2246

**Comment by PeixinLiu** [comment]
> Hi, you need to close your Qgroundcontrol after the initial setup. Then you can try to connect the Pixhawk and restart your UE project.
> 
> Hope it can help you.

thanks for your help,I will try it

**Comment by PeixinLiu** [comment]
> Airsim with PX4 #2246
> I had the same problem. But now it is neatly solved.

ok thanks ,I will try again

**Comment by PeixinLiu** [comment]
> I found a way of making it work with PX4 v5, see #2246

ok thanks ,I will try again

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
