### ISSUE TITLE
How to install Airsim on Ubuntu 16.04? I can't find where to download UE4.

### ISSUE THREAD

**Issue by machenxiang** [microsoft/AirSim#2000]
![image](https://user-images.githubusercontent.com/18185943/59003906-5a923700-884a-11e9-9453-bbf98acfd609.png)
![image](https://user-images.githubusercontent.com/18185943/59003915-6251db80-884a-11e9-8b14-aea68f17b108.png)

**Comment by msb336** [comment]
Accept the invitation to join Epic Games, and you will have access to the UnrealEngine repo. After that, you can follow the [steps illustrated here](https://microsoft.github.io/AirSim/docs/build_linux/) to complete your setup of airsim.

Note: Please read carefully step one of **Install and Build**
