### ISSUE TITLE
Drone seems too big in Unity DroneDemo

### ISSUE THREAD

**Issue by ckyun777** [microsoft/AirSim#2002]
I test DroneDemo in Unity.
I find drone size is too big. It is bigger than 1m in height and width.
So it is safe to just scale the drone down?
or are there any reasons for this?

![drone_size](https://user-images.githubusercontent.com/361695/59053253-ed26ea80-88cb-11e9-8c79-f8103b18e958.PNG)

Additionally I found its weight is also set too heavy. It is set as 15 kg.
Unity use mks unit. It means 1 in size is 1m and 1 in weight is 1kg and 1 in time means 1 second.

**Comment by msb336** [comment]
@ckyun777 it is not a problem to scale the drone to your satisfaction. Everything in Unity is open-source, so you have full access to the Drone assets if you wish to change them
