### ISSUE TITLE
Quadrotor not responding to keyboard actions

### ISSUE THREAD

**Issue by SkyFaller32** [microsoft/AirSim#2008]
Using the Unreal Engine version the quadrotor is not responding to keyboard actions for movement (Page Up/ Down and WASD). The car has no issue at all for steering but I get nothing from the quadrotor. Any help would be much appreciated!

**Comment by msb336** [comment]
At the moment, there are no keybindings for quadrotor control. If you'd like, you can bind client side API calls to keypresses. In Python, there are a number of modules to help accomplish this:
[prompt](https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/key_bindings.html)
[tkinter](https://effbot.org/tkinterbook/tkinter-events-and-bindings.htm)
[keyboard](https://pypi.org/project/keyboard/)
