### ISSUE TITLE
Failsafe enabled: no RC and no offboard. Failsafe mode enabled

### ISSUE THREAD

**Issue by lxgen** [Microsoft/AirSim#201]
When I run Droneshell demo and type a command such as 'MoveToZ' , it always causes a problem that the drone make self adjustment and then lose control flying indiscriminately. Is there any problem with my settings? Thank you.
<img width="202" alt="2222" src="https://cloud.githubusercontent.com/assets/18264666/25745522/d61b9ef6-31d1-11e7-8442-97e3514612a3.PNG">

**Comment by lovettchris** [comment]
Try setting this property on your PX4: "NAV_RCL_ACT=0", this will stop the fail safe behavior due to having no RC.
