### ISSUE TITLE
A problem puzzles me when running DQNdrone.py.

### ISSUE THREAD

**Issue by aoltonen** [microsoft/AirSim#2012]
When  I was running the DQNdrone.py in  Windows, I met a problem. The drone collides with some object ( Like a wire or iron tower) after hundreds of steps and it just stagnates there and won't go back to the initial postion. No error is reported and the runing process pauses. I wonder how to solve the problem and make the drone go on training.

**Comment by zimmy87** [comment]
There is a new script that has replaced DQNdrone.py at \AirSim\PythonClient\reinforcement_learning\dqn_drone.py. Please retest with the new script and report back if you see any issues.
