### ISSUE TITLE
Save Video as Mp4 file instead of set of png files

### ISSUE THREAD

**Issue by bwassim** [microsoft/AirSim#2014]
Hi, 
I have a general question. I would like to save the camera view on Unreal environement as one single video file instead of a set of png file. Is this possible?
Thank you for your help

------------------------------------

**Comment by mahieyin-rahmun** [comment]
You may write a script using cv2.VideoWriter() to take the pngs and save them as a mp4 file. You can delete the png files afterwards to save space if you need to.

**Comment by bwassim** [comment]
Thanks @mahieyin-rahmun. You can also use ffmpeg
