### ISSUE TITLE
I want to know the distance from drone to tree, building from the depth image?

### ISSUE THREAD

**Issue by machenxiang** [microsoft/AirSim#2017]
![37942029-bec2362a-31a3-11e8-89a7-c0896c32bebd](https://user-images.githubusercontent.com/18185943/59400091-d51e0200-8dc8-11e9-8783-69f168a07374.png)
Hello every one.I want to know the distance from drone to tree, building,...
What do these gray values represent the true distance? Thanks in advance.

**Comment by Hezzzzzy** [comment]
you should use the float value from pfm file

**Comment by machenxiang** [comment]
> you should use the float value from pfm file

Do you mean the pixel value of pfm file represent the distance between the drone and the tree?

**Comment by Hezzzzzy** [comment]
> > you should use the float value from pfm file
> 
> Do you mean the pixel value of pfm file represent the distance between the drone and the tree?

yes

**Comment by machenxiang** [comment]
> > > you should use the float value from pfm file
> > 
> > 
> > Do you mean the pixel value of pfm file represent the distance between the drone and the tree?
> 
> yes
Thank you very much.

**Comment by msb336** [comment]
Closing thread because it looks like your issue has been solved. If you are still having problems related to this issue, please reopen the thread.
