### ISSUE TITLE
build.cmd error, MSBUILD : error MSB1009: Project file does not exist. Switch: AirLibWrapper\AirsimWrapper.sln

### ISSUE THREAD

**Issue by Shwethakrishnaa** [microsoft/AirSim#2019]
C:\Users\SMURAKR\Desktop\Unity\AirSim-master>REM //---------- copy binaries and include for MavLinkCom in deps ----------

C:\Users\SMURAKR\Desktop\Unity\AirSim-master>msbuild AirLibWrapper\AirsimWrapper.sln /target:Clean /target:Build /property:Configuration=Release /property:Platform=x64
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: AirLibWrapper\AirsimWrapper.sln

C:\Users\SMURAKR\Desktop\Unity\AirSim-master>if ERRORLEVEL 1 goto :buildfailed

C:\Users\SMURAKR\Desktop\Unity\AirSim-master>echo(

C:\Users\SMURAKR\Desktop\Unity\AirSim-master>echo #### Build failed - see messages above. 1>&2

Build failed - see messages above.
C:\Users\SMURAKR\Desktop\Unity\AirSim-master>exit /b 1

I use windows 10, Visual studio 2017. I have set the environment path for MSBuild.exe
I am having this error for a long time, can someone help me with this?

**Comment by buvnswrn** [comment]
Hi @Shwethakrishnaa, could you please let me know what you did to solve this issue as I am having the same
