### ISSUE TITLE
About the Drone Shell

### ISSUE THREAD

**Issue by genglintong** [Microsoft/AirSim#202]
Hello lovettchris:

If i have no Xbox or Pixhawk, do i need to be able to use this Drone Shell control plane?

**Comment by lovettchris** [comment]
Yes, there are now two ways you can fly the drone without XBox controller or Pixhawk.

1) build [sitl mode ](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md) pixhawk (which runs the pixhawk firmware as an app on your PC).
2) use the built in ROSFlight controller

Then DroneShell can be used to fly these, [like this](https://github.com/Microsoft/AirSim/wiki/moveOnPath-demo).

**Comment by genglintong** [comment]
Thank you, I have completed the steps you gave me. And I've seen a great result. It's cool!!!
