### ISSUE TITLE
"both" SimMode always crash

### ISSUE THREAD

**Issue by FL2316** [microsoft/AirSim#2023]
I want to put UAVs and UGVs in the same scene , so maybe a new mode like "Both" in repo of @kshitiz38 could be added to allow multirotors coexist with cars. But the simulation environment always crashes. like this:
![捕获2](https://user-images.githubusercontent.com/32088613/59646569-1851e980-91aa-11e9-97f4-335effe034a2.PNG)
![捕获](https://user-images.githubusercontent.com/32088613/59646570-18ea8000-91aa-11e9-8f9c-fe3083db6b7b.PNG)
![捕获1](https://user-images.githubusercontent.com/32088613/59646571-18ea8000-91aa-11e9-8f0c-dd334203bc0f.PNG)
 Is there anything that can help me? thanks

**Comment by msb336** [comment]
At this time, we don't support different vehicles in the same sim. This is because the underlying physics engines are different and incompatible during runtime.
