### ISSUE TITLE
It's a bug? about the RPM and torque curve

### ISSUE THREAD

**Issue by Hezzzzzy** [microsoft/AirSim#2030]
hi guys,
I want to get the faster acc and speed, but airsim did not provide the api, so I read the code and found this :
`movement->EngineSetup.MaxRPM = 5700.0f; `
`movement->EngineSetup.TorqueCurve.GetRichCurve()->Reset();`
`movement->EngineSetup.TorqueCurve.GetRichCurve()->AddKey(0.0f, 400.0f);`
`movement->EngineSetup.TorqueCurve.GetRichCurve()->AddKey(1890.0f, 500.0f);`
`movement->EngineSetup.TorqueCurve.GetRichCurve()->AddKey(5730.0f, 400.0f);`

and whatever change the MAXRPM or torque curve, the car's max rpm always be 7500,
and acc also not changed,

is there anything wrong?

and I have recompiled the airsim, replace the Plugins folder,  uesless 
 
anyone can help me? thx a lot

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
