### ISSUE TITLE
Different segmentation for different foliage 

### ISSUE THREAD

**Issue by eiriksfa** [microsoft/AirSim#2031]
It seems like all foliage created in Unreal Engine (with the foliage painter) is put under a single 'InstancedFoliageActor_0' mesh, giving them all the same label. 
Is there a way to split them up?
E.g. put all trees under another mesh, without having to manually place every single tree in the scene?

**Comment by msb336** [comment]
I dont think there is a way to split the foliage once you have created it, so in order to segment foliage as you would like to, you would need to manually create each object separately.
