### ISSUE TITLE
Creating a line visible in the segmentation, but not the rendered image

### ISSUE THREAD

**Issue by machampagne1** [microsoft/AirSim#2033]
hi, I'm trying to create a visible line in the segmentation, but I need this line to *not* be visible in the normal render of the scene. 

My idea was to put down a cube and give it a transparent texture, but AirSim won't see it !

How do I fix this ?

Thanks !

**Comment by saihv** [comment]
The segmentation image uses Unreal object IDs as the means to generate a 'palette' of colors. If you are able to create a line with a transparent texture, perhaps you can try using `simSetSegmentationID` on that particular object to give it a specific color. Please see PythonClient/computer_vision/segmentation.py for better insight.

**Comment by chickenbestlover** [comment]
I have tried @saihv's suggestion and found out that Airsim API does not create any segmentation label for transparent meshes.
