### ISSUE TITLE
Contents in City Environment

### ISSUE THREAD

**Issue by viet2411** [microsoft/AirSim#2034]
Hi everyone,
I'm making my own customized environment, and I really want to use the contents in City Environment(Cars/Pedestrians). Can anyone give me the informations about the packages  used in creating City Environment?
Thank you and best regards.

**Comment by RVBldr** [comment]
Those were from Autodesk Character Creator, so you'll have to become familiar with that work flow. Cars can be sourced from almost any 3D art clearing house. The biggest challenge you'll face is creating the movement splines and possibly associated blueprints in UE to control those NPCs.
