### ISSUE TITLE
Calculating battery consumption of the drone

### ISSUE THREAD

**Issue by carnotbraun** [microsoft/AirSim#2042]
Hi, I was trying to calculate battery consumption of the drone, following the tip given by "sytelus" in this other [issue](https://github.com/microsoft/AirSim/issues/672#issuecomment-350904172). I could not find a way to access in code the info required to the calculations (torque, angular velocity) present in this [file](https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/Rotor.hpp#L115) using the API or any other method.

Does anyone have a solution for this problem?

**Comment by msb336** [comment]
Closing because this appears to be a duplicate issue. To follow up with this request, please continue posting in [the original thread](https://github.com/microsoft/AirSim/issues/672)
