### ISSUE TITLE
failsafe mode jumped every time and Local position(0,0,0) when offboard control 

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2049]
with offboard control, I got failsafe mode always, even with the following params set in  Qgroundcontrol.
param set NAV_RCL_ACT 0
param set NAV_DLL_ACT 0
param set COM_OBL_ACT 1
param set COM_OBL_RC_ACT 5

and another problem I noticed that, my local position is always 0,0,0, Is there any problem here.
==||=> Local position: x=0, y=0, z=0
Global position: lat=47.642, lon=-122.14, alt=123.179

I find that the failsafe problem has last for about two years in issues, Is there a solution for it?
I am using px4fmu-v3_default.px4

**Comment by jonyMarino** [comment]
Hi! this was solved in [the latest version (1.5.0)](https://github.com/microsoft/AirSim/releases)
