### ISSUE TITLE
DllNotFoundException: AirsimWrapper

### ISSUE THREAD

**Issue by Shwethakrishnaa** [microsoft/AirSim#2051]
Follow the airsim for windows build , the error is below!
And I can not control the car by using WASD or arrow, the car is not moving

DllNotFoundException: AirsimWrapper
AirSimUnity.VehicleCompanion.InitDelegators () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:85)
AirSimUnity.VehicleCompanion..cctor () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'AirSimUnity.VehicleCompanion' threw an exception.
AirSimUnity.Vehicle.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:58)
AirSimUnity.Car.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Car/Car.cs:25)

windows 10.
I also tried cloning git repo and started the step from the beginning. Still getting this error.
![airsimerror](https://user-images.githubusercontent.com/43069989/60493223-b8c90300-9cac-11e9-81fd-364d1e9efb75.PNG)

**Comment by msolive1985** [comment]
I have the same error. Did you have any success?

**Comment by Shwethakrishnaa** [comment]
Nope

**Comment by mattkelsey** [comment]
Same issue, running on Arch Linux
