### ISSUE TITLE
how to accelerate the RL training it's so slow

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2054]
how to accelerate the RL training it's so slow
is there any way to increase the frequency or sth else?

**Comment by vxgu86** [comment]
In unity there is a way to copy and paste many agents to do the training at the same time and maybe at a high frenquency. can we do this in unreal?

**Comment by AloshkaD** [comment]
I don't think any of that is possible in Unreal. It's a physics engine limitation.

**Comment by saihv** [comment]
Perhaps the headless mode will be helpful? - https://github.com/microsoft/AirSim/blob/master/docs/docker_ubuntu.md#running-an-unreal-binary-inside-a-docker-container

(search for headless)
