### ISSUE TITLE
what is the size of the multirotor in unreal

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2059]
I made a cylinder with radius 1 m in top view, and I found that the multirotor is almost about 1 meter length, should it be 450 or so?
and I have been thinking about this for a long time, what is the metric standard of unreal by 1m ? did it have any relation with airsim?

**Comment by vxgu86** [comment]
sorry to add one question
I found that the debug view has a position parameter, which  shows like this:
position (98.201) (90.211,78.225,-256)
is this the global position for the multirotor or  the local position?
and what is the first (98.201) means?

**Comment by bwassim** [comment]
It also appears to me that the size of the multirotor is 1mx1m

**Comment by madratman** [comment]
1) Open `Quadrotor1` mesh 
![image](https://user-images.githubusercontent.com/6305323/89911879-cab2f000-dba6-11ea-83a6-ea06f882509f.png)

2) Change view to Top / Left, and enable "show bounds" (this will show a grid of 1cm along with the mesh bounds). 
The size is already mentioned in the top left (98x98x29 cm). 
![image](https://user-images.githubusercontent.com/6305323/89912207-21202e80-dba7-11ea-94ec-9d60330ebc11.png)

3) Top view: (see the edges of the blue rectangle)
![image](https://user-images.githubusercontent.com/6305323/89912223-2a110000-dba7-11ea-8ad6-704299deeec4.png)
![image](https://user-images.githubusercontent.com/6305323/89912239-2e3d1d80-dba7-11ea-9e90-bfb6cbd7ea06.png)

4) Left view: (see the edges of the blue rectangle)
![image](https://user-images.githubusercontent.com/6305323/89912272-385f1c00-dba7-11ea-8316-85f238a3bdbd.png)
