### ISSUE TITLE
How get the mask for moving objects (car, pedestrian, etc.) in City Environment?

### ISSUE THREAD

**Issue by gjy3035** [microsoft/AirSim#2064]
How get the mask for moving objects (car, pedestrian, etc.) in City Environment?
![TIM图片20190709160142](https://user-images.githubusercontent.com/7986462/60870178-ee4c8e00-a262-11e9-97f8-03673d160a8f.jpg)

**Comment by PatrickUtz** [comment]
From what I understand, the "mask" you are talking about are segmented images using the `simSetSegmentationObjectID` function in the Images API. Check it out here: https://microsoft.github.io/AirSim/docs/image_apis/#camera-apis

**Comment by gjy3035** [comment]
@PatrickUtz Thanks a lot! I will have a try.
