### ISSUE TITLE
Python Support

### ISSUE THREAD

**Issue by devangsrammohan** [Microsoft/AirSim#207]
Hi!

The simulation looks great. I had a quick question though. You mentioned in the APIs documentation that you are working on enabling a python client to consume the data and control the drone. I think this would be fantastic as a lot of the algorithms that you mentioned would be easier to implement in python. I was wondering what sort of timeline was anticipated for this and whether there was a beta version that I could play around with.

**Comment by lovettchris** [comment]
Done ! 

See [Python support](https://github.com/Microsoft/AirSim/blob/master/docs/python.md).
