### ISSUE TITLE
How to slow down a drone

### ISSUE THREAD

**Issue by ayalakevin** [microsoft/AirSim#2070]
Hi Everyone,

I have a simple setup where two drones are to move in an X direction to end up colliding with each other. I have calculated the distance between them and I want use that distance to avoid collision by slowing one down while the other passes and vice versa. However, I can’t get moveByVelocity to work in this case and when I call moveByVelocity, where do I identify that I want Drone1 to slow down or Drone2. Any help is greatly appreciated, thank you in advance.

**Comment by mahieyin-rahmun** [comment]
https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py#L284

if you look at the code you can see that there's a keyword arg called "vehicle_name". While calling the function you can set vehicle_name='Drone1' to control Drone1.

**Comment by ayalakevin** [comment]
Thank you mahieyin-rahmun!

Didn't know the master existed, great help!
