### ISSUE TITLE
Change of coordinates in Landscape environment

### ISSUE THREAD

**Issue by Baldins** [microsoft/AirSim#2074]
Hi, 

When I want to fly the drone in the Mountain Landspace environment, the drone starts randomly from different points.
 Is there a way to fix the starting origin to a specific point? 

Additionally, every time I start the project I noted that the coordinate of my desired origin changes. My guess is that everything is relative to the actual position of the drone. 
Is there a way to move to a specific point in absolute coordinate? 

I tried to save the absolute coordinate of the drone and change the origin in the setting, but I keep having the same problem over and over. 

If someone can help me with it, it would be really appreciated! 

Thanks!

**Comment by PatrickUtz** [comment]
I had the same issue and figured out that AirSim was using the coordinates set in my `settings.json` file. I would recommend not using the Unreal Editor coordinates pane and instead modify the `"X": 4, "Y": 0, "Z": -9` section of `settings.json` as shown here:
![coordsettings](https://user-images.githubusercontent.com/30327204/61245245-0c5e3680-a71a-11e9-91f4-98396e205f00.png)

Note that if you are using Linux, the `settings.json` file is located under `/home/<yourusername>/Documents/AirSim`

**Comment by Baldins** [comment]
Thank you for replying! 
I tried what you suggested but I keep having the same problem. Every time I restart, the initial position of the drone changes. Do you have any idea of why is this happening? 
Thank you very much for your help!

**Comment by Baldins** [comment]
Never mind! I needed to restart! It is starting from the same point now ! Thank you very much for the tip!!!
