### ISSUE TITLE
UAV / UGV multiple vehicle usage

### ISSUE THREAD

**Issue by jasonbeach** [microsoft/AirSim#2076]
From the documentation here:
https://microsoft.github.io/AirSim/docs/multi_vehicle/#multiple-vehicles-in-airsim

it seems you can do multiple multirotors or multiple cars, but not a mixture of multirotors and cars (1 car + 1 multirotor).  

Is there a way to do this?  I'm thinking maybe using computer vision mode, but am not sure if it's possible to have two independently controlled camera and be able to stream their output at higher rates (20 fps).

**Comment by msb336** [comment]
Unfortunately, this is limitation in the architecture of airsim. Different vehicle types in the same sim are not supported at this time.
