### ISSUE TITLE
How to Set Segmentation ID For PlayerStart Components

### ISSUE THREAD

**Issue by PatrickUtz** [microsoft/AirSim#2077]
I am wondering if it is possible to set the segmentation ID for the PlayerStart component(s). According to the [camera api docs](https://microsoft.github.io/AirSim/docs/image_apis/#camera-apis), the `simSetSegmentationObjectID()` function works for `UStaticMeshComponent` or `ALandscapeProxy` meshes. As seen below, I am able to segment (using the infrared setting) regular _static_ meshes like so:

**Regular (Scene) Image:**
![scene0](https://user-images.githubusercontent.com/30327204/61244567-87bee880-a718-11e9-893c-542920becf55.png)
**Segmented (Infrared) Image -> each object is clearly segmented:**
![infra0](https://user-images.githubusercontent.com/30327204/61244571-8ab9d900-a718-11e9-80dc-081c0e69b458.png)

Yet I am unable to do so for PlayerStart_2 (Drone2 in my case) as seen below:

**Regular (Scene) Image:**
![scene0](https://user-images.githubusercontent.com/30327204/61244605-a02f0300-a718-11e9-8e29-4128e7533904.png)
**Segmented (Infrared) Image -> the drone is not shown...only the ice plane surface is shown:**
![infra0](https://user-images.githubusercontent.com/30327204/61244619-a7eea780-a718-11e9-8742-fb4a895c9be7.png)

Any form of help would be greatly appreciated. Thank you.

**Comment by machampagne1** [comment]
Hello !
I'm currently looking into giving the object a segmention from python (I can't atm) but if you want to give a blueprint (say the drone) it's own segmentation, you can add these 2 nodes somewhere in the event graph or in the construction script : 
![image](https://user-images.githubusercontent.com/51203484/62054354-67e2f680-b1e7-11e9-8653-9ab9892fc528.png)

You need to _get_ the static mesh and use this as the target. the value will determine the color of the segmentation (just make sure it's different than from your floor)

**Comment by PatrickUtz** [comment]
Fantastic, will give this a shot. Thank you!

**Comment by msb336** [comment]
I do not think `PlayerStart` objects have any visible properties. If you are attempting to view drones, they are defined as  `BP_FlyingPawn{instance}`
