### ISSUE TITLE
Do you Think Possible to Add wind like This?

### ISSUE THREAD

**Issue by prid1129** [microsoft/AirSim#2081]
Hi guys, I'm Trying to add wind force to Airsim UAV, but I thought it is too complicated to Follow #284 .

Instead, I'm trying to use AddForce function of UE4 to FlyingPawn.cpp/h . which is in the Plugin.

So my question is, is it possible? I'm not sure about this manner cause I'm just a beginner both c++ and UE4.

Thx :)

**Comment by jonyMarino** [comment]
Treated in #284
