### ISSUE TITLE
PX4 not found on your SerialPort, or it is not available

### ISSUE THREAD

**Issue by genglintong** [Microsoft/AirSim#209]
Hi~ lovettchris:
I can already use DroneShell to control the UAV, but I have some problems when I try to use XBOX to control the UAV.

When I run MavLinkTest.exe -serial:*,115200 -proxy:127.0.0.1:14550 -server:127.0.0.1:14570,It's wrong!!!
![image](https://cloud.githubusercontent.com/assets/15643640/25890999/16598310-35a2-11e7-9489-ec4a05a1934f.png)
And I add some Output
Like this:
![image](https://cloud.githubusercontent.com/assets/15643640/25891086/5f77c5a2-35a2-11e7-87db-fe8324b9db15.png)

And I found no serial port available.
![image](https://cloud.githubusercontent.com/assets/15643640/25891157/93e6a542-35a2-11e7-84b8-a50128d60ecf.png)

And my settings.json
{
  "LocalHostIp": "127.0.0.1",
  "Pixhawk": {
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "LogViewerSendPort": 14389,
    "Model": "Generic",
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "SimCompID": 42,
    "SimSysID": 142,
    "SitlIp": "127.0.0.1",
    "SitlPort": 14556,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": false,
    "VehicleCompID": 1,
    "VehicleSysID": 135
  }
}

Can you help me !!!

**Comment by lovettchris** [comment]
Make sure any other app that is running is not using the same serial port, like QGroundControl.  You can also find the right COM port using DeviceManager, here I see that the PX4 COM port on my machine is COM4:

![image](https://cloud.githubusercontent.com/assets/18707114/25912423/0fe7200e-356c-11e7-86e0-6fb4e36a4567.png)

So I can connect to this using:

`MavLinkTest.exe -serial:COM4,115200 
`
