### ISSUE TITLE
Attitude - GPS mode when using SITL simulation

### ISSUE THREAD

**Issue by Timebutt** [Microsoft/AirSim#210]
I went looking through the documentation, but can't find how the AirSim drone flight mode can be set to either Attitude or GPS. When I start the _AirSimGameMode_ in Unreal, it defaults to an Attitude mode that does not maintain height (so no altitude mode either). Guess this is the default PX4/posix configuration.

So basically two issues:

- How can I switch the default Attitude mode to a GPS mode in a SITL situation? I'm currently using a Phantom 2 controller connected to the posix simulation using QGroundControl. Is there a manual switch I can control in QGroundControl, seeing as I have only one button available to map to a command (being 'arm the drone' right now)?

- How can I have the drone hover in place and maintain altitude when I let go of the throttle stick? I have tried adjusting the tuning in QGroundControl (as suggested [here](https://github.com/Microsoft/AirSim/blob/a935a1967be43ede3814cd292cdf890a2b5f381d/docs/prereq.md#using-the-remote-control)) with no luck. The moment I let the stick go back to its center position, the AirSim drone loses height immediately.

Thanks!

**Comment by lovettchris** [comment]
I normally wire that to a switch on my RC remote, but you can do it programmatically if you look inside the MavLinkDroneController.cpp, you will see a mav_vehicle_ object of type MavLinkVehicle.  MavLinkVehicle already has setPositionHoldMode(), but you want setAltitudeHold, which would look like this:

```
AsyncResult<bool>  MavLinkVehicleImpl::setAltitudeHoldMode()
{
    return setMode(static_cast<int>(MAV_MODE_FLAG::MAV_MODE_FLAG_CUSTOM_MODE_ENABLED),
        static_cast<int>(PX4_CUSTOM_MAIN_MODE_ALTCTL));
}

If you add this method then you could call it from MavLinkDroneController when you want to enable that.

**Comment by Timebutt** [comment]
Perfect! Thank you for the suggestion, will implement this method and programmatically set it. No other way, as my controller limits the options.

**Comment by lovettchris** [comment]
Great, please include it in a pull request too :-)

**Comment by andre-nguyen** [comment]
![image](https://cloud.githubusercontent.com/assets/6036318/26017490/c27184c2-3737-11e7-9409-6c59b0a29eb7.png)

@Timebutt See where it says "Manual" in the top middle of the image? If you click that it becomes a dropdown menu where you can select the modes your autopilot supports.
