### ISSUE TITLE
two Error when run unity demo

### ISSUE THREAD

**Issue by Amin-Tgz** [microsoft/AirSim#2101]
![image](https://user-images.githubusercontent.com/19725851/61899378-8d92a600-af30-11e9-8df3-a82e127f1a5c.png)

first one:

> NullReferenceException: Object reference not set to an instance of an object
AirSimUnity.Vehicle.OnApplicationQuit () (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:162)

and second one:

> DllNotFoundException: AirsimWrapper
AirSimUnity.VehicleCompanion.InitDelegators () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:85)
AirSimUnity.VehicleCompanion..cctor () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'AirSimUnity.VehicleCompanion' threw an exception.
AirSimUnity.Vehicle.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:58)
AirSimUnity.Car.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Car/Car.cs:25)

car and drone dont move with arrow key or WASD

thanks

**Comment by msb336** [comment]
This looks like the demo cannot find the AirLibWrapper shared library. Did you follow the [unity build instructions](https://github.com/microsoft/AirSim/tree/master/Unity)?

**Comment by Amin-Tgz** [comment]
> 
> 
> This looks like the demo cannot find the AirLibWrapper shared library. Did you follow the [unity build instructions](https://github.com/microsoft/AirSim/tree/master/Unity)?

Yes, My OS is Windows (x64),
and all instruction has done successfully.
Is there another way to check install AirlibWrapper correctly?

**Comment by shijianjian** [comment]
@Amin-Tgz can you post your solution here?
