### ISSUE TITLE
Can I add some obstacles in the block environment? 

### ISSUE THREAD

**Issue by Hoshea7** [microsoft/AirSim#2104]
Hi everyone,

I am using reinforcement learning in the block environment to do the navigation test, so in the binary documents of the block environment, I would like to add some obstacles in it. does it possible to add? if yes, could anyone kindly provide the method of it? 

thanks a lot

**Comment by msb336** [comment]
You have full access to the blocks project in editor. To add content to the environment, there are many demos / instructional videos out there. Here's a good place to start:

https://www.youtube.com/watch?v=_FgedJWInL0

**Comment by Hoshea7** [comment]
Thanks a lot, I solved this issue
