### ISSUE TITLE
moveByVelocityAsync did not stop even after the duriation,should stop when another command come ?

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2114]
moveByVelocityAsync did not stop even after the duriation,should stop when another command come ?
the code below make the drone just move along x with no stop

moveByVelocityAsync(vx = 0.2 ,
                      vy = 0 ,
                      vz = 0,
                      duration = duration + 1,
                      drivetrain = drivetrain,
                      yaw_mode = yaw_mode).join()

**Comment by msb336** [comment]
This is a known bug. Unless you are traveling towards the ground, there are no stop commands after the duration of moveByVelocityAsync() is complete. To stop your drone, you will need to do something like the following:

```
moveByVelocityAsync(vx,vy,vz,duration).join()
moveByVelocityAsync(0,0,0,1)
```

**Comment by vxgu86** [comment]
got it,thanks.

**Comment by Rutsow** [comment]
> This is a known bug. Unless you are traveling towards the ground, there are no stop commands after the duration of moveByVelocityAsync() is complete. To stop your drone, you will need to do something like the following:
> 
> ```
> moveByVelocityAsync(vx,vy,vz,duration).join()
> moveByVelocityAsync(0,0,0,1)
> ```

I test the solution, and I then call the getvelocity(), I find that the velocity is still [vx, vy, vz] not [0,0,0]. Is taht right?
