### ISSUE TITLE
Is it possible to customize environment ?

### ISSUE THREAD

**Issue by Himanshu032000** [microsoft/AirSim#2116]
I want to create environment in which random objects are moving in any direction in 3D while i controlling drone so Is it possible to do that ?

**Comment by AloshkaD** [comment]
You should post this question in the Unreal community. Airsim will put a drone for you in virtually any env. and let you control it. What's in the env is something you bring from unreal/unity.

**Comment by msb336** [comment]
Aloshka is correct, AirSim is a plugin, but it is up to you to create custom environments. Luckily, there are tons of resources on how to do just this! [Here](https://www.youtube.com/watch?v=QJpfLkEsoek) is a good place to get started.
