### ISSUE TITLE
NameError: name 'DistanceSensorData' is not defined

### ISSUE THREAD

**Issue by rajatthosar** [microsoft/AirSim#2117]
I tried to implement the getDistanceSensorData(lidar_name, vehicle_name) method but I received the following error.

NameError: name 'DistanceSensorData' is not defined

Trace:
_Traceback (most recent call last):
  File "Path/to/my/project.py", line 399, in <module>
    handlerObj.main()
  File "Path/to/my/project.py", line 351, in main
    print(airSimObj.getDistanceSensorData(client=drone_client, vehicle_name=vehicles[0]))
  File "Path/to/my/project.py", line 291, in getDistanceSensorData
    client.getDistanceSensorData()
  File "C:\Program Files\Python36\lib\site-packages\airsim\client.py", line 157, in getDistanceSensorData
    return DistanceSensorData.from_msgpack(self.client.call('getDistanceSensorData', distance_sensor_name, vehicle_name))
NameError: name 'DistanceSensorData' is not defined_

I tried to find the DistanceSensorData class but couldn't find it. Has anyone faced a similar issue? And if so, how did you resolve it?
Any help is much appreciated

**Comment by rajatthosar** [comment]
Is there any update on this issue?

**Comment by ACLeighner** [comment]
I was able to fix this by adding the following code the the types file.

AirSim\PythonClient\airsim\types.py

class DistanceSensorData(MsgpackMixin):
    time_stamp = np.uint64(0)
    distance = Quaternionr()
    min_distance = `Quaternionr()`
    max_distance = Quaternionr()
    relative_pose = Pose()

**Comment by saihv** [comment]
@ACLeighner please feel free to submit a PR!
