### ISSUE TITLE
How to bind coordinate system (lat long alt) to scene in AirSim?

### ISSUE THREAD

**Issue by Supaple-x** [microsoft/AirSim#2120]
Hi!

I have custom scene to simulate in.
In other words, I have scan an environment in 3D.
How can I bind it to coordinate system and scale it in accordance with its real geoposition?

Thanks for any help!

**Comment by msb336** [comment]
Scaling your scan properly is a task that must be done in Unreal Editor. Editor's base unit is cm, you can scale your environment accordingly in the x,y, and z directions.

To set the geoposition origin, you and add the following to your settings.json file:
```
  "OriginGeopoint": {
    "Latitude": [your latitude],
    "Longitude": [your longitude]
    "Altitude": [your altitude]
  }
```

see more [here](https://github.com/microsoft/AirSim/blob/master/docs/settings.md#available-settings-and-their-defaults)
