### ISSUE TITLE
Dji Matrice 100 with N1 Flight Controller not working with Airsim

### ISSUE THREAD

**Issue by TouHouPolice** [microsoft/AirSim#2122]
My OS is Windows 10, I tried both Unreal 4.16 and 4.18 with corresponding Airsim but neither of them worked. Previously I was working on a drone with pixhawk and I set the settings to PX4 and the simulation worked fine.
When I tried the new drone, which was the Matrice 100 with N1 flight controller, I deleted the settings and expected it to use default simple_flight mode. However it only told me "RC is not connected" despite the drone was successfully connected to the PC with a USB cable. (The lite simulator in DJI Assistant 2 was working properly)
Am I missing something, or do I have to use ROS? Do I have to make use of DJI OSDK? How do I establish a connection between the Matrice 100 and Airsim? I am a newbie and I am very confused.

**Comment by crisscrosskao** [comment]
I think this is a very good question. I too am developing on the Matrice 100 with N1 flight controller and would like to know how I might be able to test waypoint algorithms in the simulator. I will update this thread if I get any insights.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
