### ISSUE TITLE
Where to buy more drones?

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#213]
Hey all!

I am interested to use AirSim for a project however instead of Air Drone, I need to have a model for hexacopter or octocopter. I believe it was advertised that we could buy the models the Marketplace in Epic Games Launcher but I have been unable to do that. 

Kindly let me know if there is a link or something to the place where these things can be purchased and used with AirSim. Thank you for your help!

**Comment by lovettchris** [comment]
See [building a hexacopter](https://github.com/Microsoft/AirSim/wiki/hexacopter)
