### ISSUE TITLE
Strange starting position for the car in LandscapeMountains

### ISSUE THREAD

**Issue by yfshe** [microsoft/AirSim#2130]
Hello
Why is the car starting here? I can't find where I should drive next.
This position seems to be the position of a quadrotor.
<img width="801" alt="捕获" src="https://user-images.githubusercontent.com/10218573/62770360-77a6e880-bacd-11e9-8ab8-1d22cc4b06ce.PNG">
The LandscapeMountains environment version I use is [v1.2.2 - Windows](https://github.com/microsoft/AirSim/releases/tag/v.1.2.2).

In version [v1.1.7 - Windows](https://github.com/microsoft/AirSim/releases/tag/v1.1.7), however, it seems to start with the normal road location:
<img width="801" alt="捕获2" src="https://user-images.githubusercontent.com/10218573/62770887-8cd04700-bace-11e9-8000-4cf7a6f518be.PNG">

**Comment by msb336** [comment]
You can change your car's starting position to anywhere you would like by adding your vehicle setting to the `settings.json` file and modifying the X Y Z position:
```
  "Vehicles": {
    "PhysXCar": {
      "VehicleType": "PhysXCar",
      "X": NaN, "Y": NaN, "Z": NaN,
      "Pitch": NaN, "Roll": NaN, "Yaw": NaN      
    }
  }
```
