### ISSUE TITLE
How to change the publishing rate of airsim_node ?

### ISSUE THREAD

**Issue by jzstudent** [microsoft/AirSim#2131]
------------------------------------
Hi,
when I used the ros package ( airsim_ros_pkgs ) to publish the image or depth image, I found that the rate is only 0.6! How to improve it?
I have already changed the publish_to_ros in .json, but it seems to be useless. Maybe the reason is that simgetImage() is slow, how can I slove it?

**Comment by saihv** [comment]
What image resolution are you using?

**Comment by Omar-Elmofty** [comment]
I have the same question, was anyone able to figure out how to change the publishing rate?

**Comment by GimpelZhang** [comment]
> I have the same question, was anyone able to figure out how to change the publishing rate?

First please check if the "update_airsim_img_response_every_n_sec" parameter has been tuned. 

If the publishing rate is limited by the computer performance, maybe changing the ClockSpeed setting to a less than one number is a solution. 

I have tested that slower simulation would produce denser image response.

**Comment by jzstudent** [comment]
> I have the same question, was anyone able to figure out how to change the publishing rate?

Hi, I've tried to set "ViewMode": "NoDisplay" in .json, it makes the rate improve and I 've already slove it.

**Comment by Omar-Elmofty** [comment]
Thanks! The NoDisplay mode helped a lot, also slowing down the simulation helps.
