### ISSUE TITLE
Cars can't cross the bridge in LandscapeMountains

### ISSUE THREAD

**Issue by yfshe** [microsoft/AirSim#2133]
The LandscapeMountains environment version I use is [v1.2.2 - Windows](https://github.com/microsoft/AirSim/releases/tag/v.1.2.2).
As shown in the figure, the car can't cross the bridge:
<img width="801" alt="桥" src="https://user-images.githubusercontent.com/10218573/62849211-546c7b00-bd11-11e9-8a76-5cee07988805.PNG">

**Comment by lanyua** [comment]
地图问题  桥上面看起来是空的  实际上桥面和栏杆一样高

**Comment by jonyMarino** [comment]
This is not an AirSim issue. You would need to modificate the LandscapeMountains bridges to be at ground level
