### ISSUE TITLE
[Question] simSetVehiclePose - Car flies through map

### ISSUE THREAD

**Issue by MoritzGa** [microsoft/AirSim#2137]
Dear community,

I'm using AirSim in Unreal Engine for research purposes concering deep reinforcement learning. For that purpose I want to **reset my car to random positions on the track** to get a more diverse set of experience than by only resetting it every time to same home point.

As of right now I'm calling the reset() method, computing the position and calling the simSetVehiclePose() method only supplying Pose not Orientation. While it works pretty well most of the time there are some cases where the vehicle flies through the map rotating around its axes. 

Is there a better way to do this?

Right now the respective code looks like this:
```python
client.reset()
time.sleep(1.0)

# [...] Code getting the next starting point

client.simSetVehiclePose(airsim.Pose(airsim.Vector3r(starting_point[0], starting_point[1], starting_point[2])), True)
```

**Comment by msb336** [comment]
The car is flying through the map in the cases where it's teleported position eclipses with objects in the environment. To prevent this, limit your starting point sample area to a zone in which the car does not eclipse any objects.
