### ISSUE TITLE
how to add a visualization of the camera view area like a horizon cone?

### ISSUE THREAD

**Issue by vxgu86** [microsoft/AirSim#2141]
I want to add a visualization of the camera view area like a horizon cone on the camera, like a Flashlight， I tried to add a collision box to simulate this, but the effect and visualization is not satisfied.
did anyone try this before?

**Comment by vxgu86** [comment]
could anyone please help me...
problem still not solved.

**Comment by msb336** [comment]
here is a demo of a similar application:
https://answers.unrealengine.com/questions/670624/how-to-make-line-of-sight-visible-and-blocked-by-w.html

This will require a decent understanding of how cameras work, as well as a decent amount of development work in engine.
