### ISSUE TITLE
Compiler Error-- How to fix it?

### ISSUE THREAD

**Issue by CPS-zhangX** [microsoft/AirSim#2151]
When compile the build.cmd, I meet the following Error. How can I fix it? Many THanks!

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\AirSim\AirSim.sln" (default target) (1) ->
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\AirSim\AirLibUnitTests\AirLibUnitTests.vcxproj" (default
 target) (11) ->
(ClCompile target) ->
  c:\program files (x86)\microsoft visual studio\2017\community\airsim\airlib\include\vehicles\multirotor\firmwares\ard
ucopter\arducopterapi.hpp(184): error C2220: warning treated as error - no 'object' file generated [C:\Program Files (x
86)\Microsoft Visual Studio\2017\Community\AirSim\AirLibUnitTests\AirLibUnitTests.vcxproj]

    20 Warning(s)
    1 Error(s)

**Comment by rajat2004** [comment]
Please update to the latest master, https://github.com/microsoft/AirSim/pull/2150 has been merged which fixes the errors
Sorry for the problems caused!
