### ISSUE TITLE
can I add UAV sounds?

### ISSUE THREAD

**Issue by weiLiangHare** [microsoft/AirSim#2153]
I want to listen to UAV sounds。can I? how to do ?
OS:widows   
airsim version: commit id 2d53a79
UE version:4.18.3
Thanks

**Comment by msb336** [comment]
We don't have any in house support for UAV sounds. You can add sounds to UE4 blueprints by following the steps in [this link](https://answers.unrealengine.com/questions/324950/playing-a-sound-from-blueprint.html)
