### ISSUE TITLE
Airsim environment freezes during training

### ISSUE THREAD

**Issue by asimhirji** [microsoft/AirSim#2156]
Hi,

I am currently training a model in the landscape environment. After a certain amount of time/certain amount of episodes of training, the environment freezes where the rotors on the multirotor are misplaced and the only way to continue training is to press the back button to manually reset the simulation. I've tried running Landscape Mountains through creating a new unreal engine project as well as using the Landscape Mountains environment provided in the AirSim GitHub pages. However, both seem to cause the same issues described before. I've also written an automatic reset when no movement is taken, but that hasn't fixed the issue. I also tried deleting the log files and tried to make sure log files don't get added, but I haven't found a solution yet. Any help will be appreciated!

**Comment by msb336** [comment]
I believe [this PR](https://github.com/microsoft/AirSim/pull/2146) solves your issue. Try updating to current master and rebuilding.
