### ISSUE TITLE
Getting the attitude(pitch yaw roll) of UAV model 

### ISSUE THREAD

**Issue by jonweili** [Microsoft/AirSim#216]
Hello, I have trouble to get the attitude(pitch roll yaw) via API provided by Airsim. Could someone else share the methods?

**Comment by lovettchris** [comment]
For others, the answer is DroneControlBase::getOrientation() which returns a Quaternionr, which you can then pass to VectorMath::toEulerianAngle(...) to get roll pitch and yaw.

**Comment by jonweili** [comment]
Thanks very much! What you said is very helpful for me!
