### ISSUE TITLE
Multirotor follow path algorithm

### ISSUE THREAD

**Issue by YumaTheCompanion** [microsoft/AirSim#2162]
It is possible to follow a predetermined path using `moveOnPathAsync`.

I've tried and tested it, it works as expected. However, the yaw angle does not change, the multirotor is facing the same direction from start.

**Is it possible to make the drone face the direction it is moving, (as in car simulation) ?**

**If not, I'm willing to add such a functionality. Is anyone also interested in such a thing?**

**Comment by vinbo** [comment]
of course possible, it's up to you to implement it, too simple to add such functionality

**Comment by YumaTheCompanion** [comment]
I meant as in; is it possible in core functionality, without implementing it ?

As of now, I've created a wrapper function that uses a combination of `moveOnPathAsync` and `moveByVelocityZAsync` functions to direct heading before moving onto a particular location. This is because I need the drone to move slow, and also turn slow, because I'm taking camera snapshots and framerate is slower if drone moves fast.

However, I was thinking of adding it to core AirSim, instead of using available tools and implementing it myself.

For example, commonly used flight controllers (mostly forks of ardupilot) accept `waypoint`s in mission mode, and they turn drone heading, before approaching the target. Something to that extent.

Anyone is interested ? Or shall I pass ?

**Comment by msb336** [comment]
you can control the drone's heading by inputting [`DrivetrainType`](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/types.py#L32) in [moveOnPathAsync](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py#L291) to `FowardOnly`

**Comment by YumaTheCompanion** [comment]
Thanks, this is correct, no need to implement anything special.
