### ISSUE TITLE
Unreal Engine Crashing

### ISSUE THREAD

**Issue by lloydrayner** [microsoft/AirSim#2171]
Hi, 

I am repeatedly experiencing Unreal crashing during run. It happens randomly and I am presented with the below error message.

Any suggestions on how I can stop this?

`Caught signal

simple_flight::VelocityController::reset() Address = 0x169788de3 [/Users/lrayner/PycharmProjects/T1.V1/UnrealEngine/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/AngleLevelController.hpp, line 55] [in UE4Editor-AirSim.dylib]
simple_flight::Firmware::reset() Address = 0x169785a1c [/Users/lrayner/PycharmProjects/T1.V1/UnrealEngine/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirLib/include/vehicles/multirotor/firmwares/simple_flight/firmware/Firmware.hpp, line 47] [in UE4Editor-AirSim.dylib]
MultirotorPawnSimApi::reset() Address = 0x16974069e [/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/memory, line 2617] [in UE4Editor-AirSim.dylib]
UE4Function_Private::TFunctionRefCaller<ASimModeWorldBase::reset()::$_83, void ()>::Call(void*) Address = 0x1697e8ee8 [/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/iterator, line 1372] [in UE4Editor-AirSim.dylib]
ASimModeWorldBase::reset() Address = 0x1697300d1 [/Users/Shared/Epic Games/UE_4.22/Engine/Source/Runtime/Core/Public/Templates/Function.h, line 619] [in UE4Editor-AirSim.dylib]
UE4Function_Private::TFunctionRefCaller<WorldSimApi::reset()::$_88, void ()>::Call(void*) Address = 0x1697ebaa7 [/Users/lrayner/PycharmProjects/T1.V1/UnrealEngine/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/WorldSimApi.cpp, line 19] [in UE4Editor-AirSim.dylib]
TGraphTask<FFunctionGraphTask>::ExecuteTask(TArray<FBaseGraphTask*, FDefaultAllocator>&, ENamedThreads::Type) Address = 0x169747a6c [/Users/Shared/Epic Games/UE_4.22/Engine/Source/Runtime/Core/Public/Templates/Function.h, line 619] [in UE4Editor-AirSim.dylib]
FNamedTaskThread::ProcessTasksNamedThread(int, bool) Address = 0x10d241f7c (filename not found) [in UE4Editor-Core.dylib]
FNamedTaskThread::ProcessTasksUntilQuit(int) Address = 0x10d241113 (filename not found) [in UE4Editor-Core.dylib]
FTaskGraphImplementation::WaitUntilTasksComplete(TArray<TRefCountPtr<FGraphEvent>, TInlineAllocator<4u, FDefaultAllocator> > const&, ENamedThreads::Type) Address = 0x10d23eaef (filename not found) [in UE4Editor-Core.dylib]
FTickTaskSequencer::ReleaseTickGroup(ETickingGroup, bool) Address = 0x10fb6c1ee (filename not found) [in UE4Editor-Engine.dylib]
FTickTaskManager::RunTickGroup(ETickingGroup, bool) Address = 0x10fb65918 (filename not found) [in UE4Editor-Engine.dylib]
UWorld::Tick(ELevelTick, float) Address = 0x10f2452d7 (filename not found) [in UE4Editor-Engine.dylib]
UEditorEngine::Tick(float, bool) Address = 0x115fd46e7 (filename not found) [in UE4Editor-UnrealEd.dylib]
UUnrealEdEngine::Tick(float, bool) Address = 0x1169cb298 (filename not found) [in UE4Editor-UnrealEd.dylib]
FEngineLoop::Tick() Address = 0x10d13ed54 (filename not found) [in UE4Editor]
GuardedMain(wchar_t const*) Address = 0x10d148b48 (filename not found) [in UE4Editor]
-[UE4AppDelegate runGameThread:] Address = 0x10d152c8e (filename not found) [in UE4Editor]
-[FCocoaGameThread main] Address = 0x10d3ba801 (filename not found) [in UE4Editor-Core.dylib]
Unknown() Address = 0x7fff544dc5c2 (filename not found) [in Foundation]
_pthread_body Address = 0x7fff7e3cc2eb (filename not found) [in libsystem_pthread.dylib]
_pthread_start Address = 0x7fff7e3cf249 (filename not found) [in libsystem_pthread.dylib]
thread_start Address = 0x7fff7e3cb40d (filename not found) [in libsystem_pthread.dylib]`

**Comment by msb336** [comment]
I believe [this PR](https://github.com/microsoft/AirSim/pull/2146) might solve your problems. Try updating to current master and rebuilding.
