### ISSUE TITLE
What am I doing wrong while entering "build"? I installed 'CodeBlocks' as well, and have given it some authorithy over some Unix files/projects. Not sure if that has anything to do with this. These are the results I am getting:

### ISSUE THREAD

**Issue by CarlCornelio** [microsoft/AirSim#2178]
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.15
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional>cd..

C:\Program Files (x86)\Microsoft Visual Studio\2017>cd..                                                                                                                                                                                        C:\Program Files (x86)\Microsoft Visual Studio>cd..                                                                                                                                                                                             C:\Program Files (x86)>cd..
C:\>cd "C:\Users\[Username]\Desktop\AirSim"

C:\Users\Carl_\Desktop\AirSim>ls
AUTHORS.md           DroneShell         README.md                          build_docs.bat     external
AirLib               Examples           SGM                                check_cmake.bat    install_run_all.sh
AirLibUnitTests      HelloCar           SUPPORT.md                         clean.cmd          install_unreal.sh
AirSim.props         HelloDrone         Unity                              clean.sh           llvm-build
AirSim.sln           ISSUE_TEMPLATE.md  Unreal                             clean_rebuild.bat  llvm-source-50
AirSim.sln.vlconfig  LICENSE            UnrealPluginFiles.vcxproj          clean_rebuild.sh   ros
CHANGELOG.md         LogViewer          UnrealPluginFiles.vcxproj.filters  cmake              setup.sh
CONTRIBUTING.md      MavLinkCom         build.cmd                          docker             tools
DroneServer          PythonClient       build.sh                           docs

C:\Users\[Username]\Desktop\AirSim>build
Found cmake version: 3.14.5

*****************************************************************************************
Downloading rpclib
*****************************************************************************************
Starting cmake to build rpclib...
CMake Error: Could not create named generator Visual Studio 15 2017 Win64

Generators
* Unix Makefiles               = Generates standard UNIX makefiles.
  Ninja                        = Generates build.ninja files.
  CodeBlocks - Ninja           = Generates CodeBlocks project files.
  CodeBlocks - Unix Makefiles  = Generates CodeBlocks project files.
  CodeLite - Ninja             = Generates CodeLite project files.
  CodeLite - Unix Makefiles    = Generates CodeLite project files.
  Sublime Text 2 - Ninja       = Generates Sublime Text 2 project files.
  Sublime Text 2 - Unix Makefiles
                               = Generates Sublime Text 2 project files.
  Kate - Ninja                 = Generates Kate project files.
  Kate - Unix Makefiles        = Generates Kate project files.
  Eclipse CDT4 - Ninja         = Generates Eclipse CDT 4.0 project files.
  Eclipse CDT4 - Unix Makefiles= Generates Eclipse CDT 4.0 project files.

Error: could not load cache
Error: could not load cache

#### Build failed - see messages above.

C:\Users\[Username]\Desktop\AirSim>

______________________________________________________________________________________________________

Screenshot:
![AirSim Issue ScreenShot](https://user-images.githubusercontent.com/54554807/64479316-26991b80-d183-11e9-8779-61d17102c282.png)

**Comment by saihv** [comment]
Looks like the cmake version on your system (3.14.5) has been configured independent of Visual Studio, and is unable to find the VS generators. You could probably tryconfiguring it manually, or removing it and letting AirSim download cmake.
