### ISSUE TITLE
How to modify sensor implementations to add noise?

### ISSUE THREAD

**Issue by akurumunda0805** [microsoft/AirSim#2184]
I would like to know how to set a seed for different sensor parameters (i.e. IMU, GPS …) where I can run multiple runs and make those runs repeatable. This is analogues to running Monte Carlo sets in AirSim.

Any help would be greatly appreciated!
UE 4.18.3, Python 3.7.4

**Comment by ironclownfish** [comment]
Sensor implementations don't currently have built-in noise options.
Our thinking is that people can relatively easily add custom noise to sensor data after retrieving it on the client side.
