### ISSUE TITLE
Drone movement unstable when using PX4 SITL with QGroundControl

### ISSUE THREAD

**Issue by Zachmoist** [microsoft/AirSim#2187]
Hello, 
I'm currently trying to use AirSim in Multirotor mode using QGroundController to execute a fly plan, i defined a plan inside QGC and at moment of execution i get the failsafe mode on message. I read the docs and applied the **No remote control** section, set the parameters
```
param set NAV_RCL_ACT 0
param set NAV_DLL_ACT 0
```
And when in flight, the failsafe mode still activates and the drone doesn't follow the path.
![Capture](https://user-images.githubusercontent.com/28161879/64820929-e1605980-d587-11e9-9d08-161343ed51e4.PNG)
I'm using AirSim v.1.2.2, Unreal Engine 4.18.3 in Windows 10 and PX4 in a Docker container with Ubuntu image.

Is there something i'm currently missing? I can answer any other question.

**Comment by Jaeyoung-Lim** [comment]
Which version of px4 are you running?

**Comment by Zachmoist** [comment]
I use px4 1.8.2 but it is fine, the problem was a hardware limitation, the same test in a more powerful hardware worked fine.
