### ISSUE TITLE
build is broken on windows

### ISSUE THREAD

**Issue by Sohojoe** [microsoft/AirSim#2190]
I am using AirSim for the first time. I was unable to get it to build using the latest commit https://github.com/microsoft/AirSim/commit/fead8f7dbecf6b200f5d34db2488be67b61987e2

 This slightly older commit did build for me  'Fix Windows build error (unused params) (#2150)' / https://github.com/microsoft/AirSim/commit/3cb403dd36a4b743cfe368da0ac2b954b6e5a146

**Comment by msb336** [comment]
https://github.com/microsoft/AirSim/pull/2193 this PR should allow you to build successfully again

**Comment by Jack2563** [comment]
have the same problem even after having the change corrected already

**Comment by Jack2563** [comment]
this is the error  :
"C:\Windows\System32\AirSim\AirSim.sln" (default target) (1) ->
       "C:\Windows\System32\AirSim\AirLib\AirLib.vcxproj" (default target) (8) ->
       (ClCompile target) ->
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\BooleanRedux.h(111,6): error C2220: the following warning is treated as an error [C:\Wi
       ndows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]
         C:\Windows\System32\AirSim\AirLib\include\Eigen\src\Core\CoreEvaluators.h(219,9): error C2220: the following warning is treated as an error [C:\
       Windows\System32\AirSim\AirLib\AirLib.vcxproj]

    104 Warning(s)
    8 Error(s)
