### ISSUE TITLE
Build error due to Airsim setting

### ISSUE THREAD

**Issue by 02yogesh16** [microsoft/AirSim#2191]
Hi,

I am trying to build Airsim using VisualStudio 2017 on Windows 10. There I am getting the following error, please help me out of this. I have attached a screenshot of the error messages.

![Screenshot (8)](https://user-images.githubusercontent.com/11498835/64843048-9e52c480-d621-11e9-9b44-66ad1a71e73d.png)

Following are the errors I am getting:

** Warnings

"D:\Softwares\AirSim\AirSim.sln" (default target) (1) ->
"D:\Softwares\AirSim\DroneShell\DroneShell.vcxproj" (default target) (2) ->
"D:\Softwares\AirSim\AirLib\AirLib.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): warning C4244: '=': conversion from 'int' to 'uint
16_t', possible loss of data [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): warning C4244: '=': conversion from 'int' to 'uint
16_t', possible loss of data [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): warning C4244: '=': conversion from 'int' to 'uint
16_t', possible loss of data [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): warning C4244: '=': conversion from 'int' to 'uint
16_t', possible loss of data [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]

*Errors:

"D:\Softwares\AirSim\AirSim.sln" (default target) (1) ->
"D:\Softwares\AirSim\DroneShell\DroneShell.vcxproj" (default target) (2) ->
"D:\Softwares\AirSim\AirLib\AirLib.vcxproj" (default target) (3) ->
(ClCompile target) ->
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): error C2220: warning treated as error - no 'object
' file generated [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): error C2220: warning treated as error - no 'object
' file generated [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): error C2220: warning treated as error - no 'object
' file generated [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]
  d:\softwares\airsim\airlib\include\common\airsimsettings.hpp(992): error C2220: warning treated as error - no 'object
' file generated [D:\Softwares\AirSim\AirLib\AirLib.vcxproj]

    4 Warning(s)
    4 Error(s)

Time Elapsed 00:00:39.22

**Comment by Sohojoe** [comment]
@02yogesh16 see temp workaround / commit that builds: https://github.com/microsoft/AirSim/issues/2190

**Comment by msb336** [comment]
https://github.com/microsoft/AirSim/pull/2193 this PR should allow you to build successfully again

**Comment by 02yogesh16** [comment]
Thanks Sohojoe and madratman.
