### ISSUE TITLE
AirSim SITL gps not starting, can't get home position

### ISSUE THREAD

**Issue by SusejLav** [microsoft/AirSim#2195]
Hello,

I'm trying to get SITL to work with AirSim + QGC + PX4 but when i start px4 and the sim no matter which command i do the drone behaves incorrectly. Reading through the issues i can only identify that my problem may be with the gps in px4.
When started, i never get the home position log message and can't check it with the 'pos' command, only 'commander status'.
I'm using Windows 10, Airsim 1.2.0, PX4 1.8.2 and QGroundcontrol v3.4.3

![image](https://user-images.githubusercontent.com/50989975/65048450-812c3780-d93a-11e9-817e-22ca97867034.png)

**Comment by Jaeyoung-Lim** [comment]
I am using Linux 18.04, but the behavior is correct for me. Have you tried updating Airsim to a more recent version?

**Comment by SusejLav** [comment]
At the end it was due to specs, when running in another machine everything went smooth.
