### ISSUE TITLE
nuget : boost 1.63.0 & Eigen 3.2.9

### ISSUE THREAD

**Issue by MENUT** [Microsoft/AirSim#22]
Hello, 
I use VS2015 to compile the solution.
Can we import boost 1.63.0 & Eigen 3.2.9 from nuget.org?
I have included this two packages into the various projects and remove Target Conditions without success during link of DroneServer project.
Regards.
Fred

**Comment by sytelus** [comment]
Unfortunately this won't work cross platform. Also, if folks already have these on their machine then we rather not duplicate these files.
