### ISSUE TITLE
DQNdrone.py

### ISSUE THREAD

**Issue by oooohhhhhhh** [microsoft/AirSim#2205]
When i run this code on spyder , it says No module named 'setup_path' , i wonder what "setup_path" meaning in this code

appreciate

**Comment by msb336** [comment]
setup path is included in both the `PythonClient/multirotor` and `PythonClient/car` folders. [here is a link](https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/setup_path.py)

`import setup_path` is the first module to be imported in all of our PythonClient scripts, as it ensures that the airsim python module to be loaded is the version defined in the repo.

If you installed airsim globally (`pip install airsim`), you can remove this line:
```
import setup_path
```
and your script should run without issue.

**Comment by oooohhhhhhh** [comment]
thank you very much
