### ISSUE TITLE
How to modify the vehicle physics engine

### ISSUE THREAD

**Issue by freeyyc** [microsoft/AirSim#2206]
in the issue #932, I have found the method to modify the multirotor physics engine.
Is there a similar way to modify the vehicle physics engine?

**Comment by msb336** [comment]
[this issue](https://github.com/microsoft/AirSim/issues/627) will show you how to modify the behavior of the car, but the underlying physics engine is the same. to modify the physics engine itself, as explained in #932, would require a great deal of development work.
