### ISSUE TITLE
vehicle cannot be armed via API because API has not been given control

### ISSUE THREAD

**Issue by tjb89** [microsoft/AirSim#2208]
Hi! I'm just learning to use it, here is the question.
The Blocks example works well, and the Droneshell connects to the server, I can type command in the Droneshell.
When I type in Arm command, the Log shows "vehicle cannot be armed via API because API has not been given control", is there anything wrong with my settings.json, as follow

{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "AllowAPIAlways": true,
  "RpcEnabled": true
}

Thanks!

**Comment by msb336** [comment]
Although it would make sense for `AllowAPIAlways` to mean that `api_enabled` is toggled to true at construction, this is not the case. In order to control your drone, you must call `enableApiControl(True, vehicle_name="{your vehicle name}")` before sending API commands.
