### ISSUE TITLE
How do I grab images from all the views simultaneously ?

### ISSUE THREAD

**Issue by bypatel** [Microsoft/AirSim#221]
With record button in UE editor, I can save one image type at a time by modifying EPIPCameraType in
ReadPixelsNonBlocking. How do I save them all to be used later for groundtruthing purposes ?

EDIT : I created another FRecordingThread but having trouble with synchronization. Need to match the scene and depth images. any ideas ?

**Comment by ChaceYoung** [comment]
Same question here.

**Comment by saihv** [comment]
Definitely not the greatest solution, but if you're not too concerned about the frequency of logging, I guess you could just add an argument to ReadPixelsNonBlocking with the EPIPCameraType, and call it three times within Run()?

**Comment by lukaszdworako** [comment]
If you are still having issues, the easiest way to "sync" various video feeds would be to create an event that is common between them i.e. a block falling and hitting something would be the first thing that comes to mind since you could sync them up fairly easily based on when the objects hits the ground.

**Comment by Mayankm96** [comment]
Any updates @bypatel ?

**Comment by lovettchris** [comment]
You can fetch all 3 views using Python (see PythonClient/camera.py).  But there are [performance implications](https://github.com/Microsoft/AirSim/blob/master/docs/camera_views.md#performance).

**Comment by sytelus** [comment]
Please see [new APIs](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md) that allows you to do this!

**Comment by sytelus** [comment]
The feature to record images from multiple cameras simultaneously is now available. You can, for example, record scene and depth images simultaneously. 

Please see the doc: https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#recording
