### ISSUE TITLE
airsim.Pose default constructor initializes to shared position/orientation objects

### ISSUE THREAD

**Issue by psmeyer** [microsoft/AirSim#2211]
When initializing new airsim.Pose objects with no input variables, the position and orientation attributes are initialized to a common object throughout the class. This results in changes to any instances initialized this way changing all instances. This is a common issue when using mutable types as default parameters.

OS: Windows
Python Version: 3.7.3

Simple code to reproduce:

```python
>>> import airsim
>>> a = airsim.Pose()
>>> b = airsim.Pose()
>>> a.position.x_val
0.0
>>> b.position.x_val = 3.0
>>> a.position.x_val
3.0
```

Similar issues happen with adjusting the orientation values.

**Comment by msb336** [comment]
thanks for catching this, PR #2215  fixes this problem.
