### ISSUE TITLE
Does Airsim support Phantom 4pro remote control in addition to Phantom 2?

### ISSUE THREAD

**Issue by love-mj** [microsoft/AirSim#2213]
Using Phantom 2 DJI Controller in AirSim After following the steps in this article, I couldn't use Phantom 3 DJI Controller.

**Comment by love-mj** [comment]
Using Phantom 2 DJI Controller in AirSim This article does not use Phantom 3 DJI Controller after step-by-step operation.

**Comment by ironclownfish** [comment]
Sorry, no support for this currently!

**Comment by love-mj** [comment]
Thanks
