### ISSUE TITLE
Can not find example_model.h5

### ISSUE THREAD

**Issue by nikunjbharatbhai** [microsoft/AirSim#2216]
I am trying to simulate this drive_model.py from AirSim library. In that file, there is a path of a mode, that i cant seem to find. it is written that path of this model is "./models/example_model.h5". but there is no file in this airsim library.

**Comment by msb336** [comment]
There is no publicly available model on our site. You will need to train your own model using [train_model.py](https://github.com/microsoft/AirSim/blob/123bbd6d6416bbe98e775101ba8ebcb5ccbf8501/PythonClient/imitation_learning/train_model.py)
