### ISSUE TITLE
Select "Generate Visual Studio Project Files" ,but do not generate ".sln" files

### ISSUE THREAD

**Issue by sbkybhy** [microsoft/AirSim#2217]
Follow the tutorial，I installed "Landscape Mountains", created "New C++ class",and copy “Unreal\Plugins”,too.I also changed the "LandscapeMountains uproject". However, after executing "Generate Visual Studio Project Files", the .sln file will not be generated. Using the "Unreal Editor" open "LandscapeMountains. Uproject", it will display what is shown in the figure below. How to solve this problem?
![image](https://user-images.githubusercontent.com/48812520/65748619-f667eb80-e136-11e9-859d-cb6926800924.png)
![image](https://user-images.githubusercontent.com/48812520/65748626-f8ca4580-e136-11e9-9566-9682d751418d.png)
![image](https://user-images.githubusercontent.com/48812520/65748631-fbc53600-e136-11e9-8b52-ccbc80b1e677.png)

**Comment by msb336** [comment]
The log from attempting to open your project will provide more information as to why this failed. Can you add it to this thread?
It is located here: `{your project}/Saved/Logs/`

**Comment by sbkybhy** [comment]
The file in the attachment is the latest log record. Thank you so much！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"msb336"<notifications@github.com&gt;;
发送时间:&nbsp;2019年9月27日(星期五) 晚上11:44
收件人:&nbsp;"microsoft/AirSim"<AirSim@noreply.github.com&gt;;
抄送:&nbsp;"YONGBUTINGXI"<2936776123@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/AirSim] Select "Generate Visual Studio Project Files" ,but do not generate ".sln" files (#2217)




The log from attempting to open your project will provide more information as to why this failed. Can you add it to this thread?
 It is located here: {your project}/Saved/Logs/

**Comment by Re-Ell** [comment]
I was getting a similar issue but couldn't find a proper solution. I tried building with all other versions but I doesn't seem to solve the error.

**Comment by bmalhigh** [comment]
I am not seeing the any file attachment here. Where is the log file?

BTW, can you try running the explorer window as an Administrator and then retry?

**Comment by sbkybhy** [comment]
[TaiYangShenMiao.log](https://github.com/microsoft/AirSim/files/3684292/TaiYangShenMiao.log)
[TaiYangShenMiao-backup-2019.10.03-11.06.56.log](https://github.com/microsoft/AirSim/files/3684293/TaiYangShenMiao-backup-2019.10.03-11.06.56.log)

The above file is the log file. And I used administrator mode

**Comment by rajat2004** [comment]
@sbkybhy Is the default Blocks environment working properly? If not, then that's the first problem which needs to be fixed before moving to custom environments.

You can try some more things such as running `clean_rebuild.bat` and then starting over,
The problems from the log file seem to be this - 
```
LogWindows: Failed to load 'aqProf.dll' (GetLastError=126)
LogWindows: File 'aqProf.dll' does not exist
LogWindows: Failed to load 'VtuneApi.dll' (GetLastError=126)
LogWindows: File 'VtuneApi.dll' does not exist
LogWindows: Failed to load 'VtuneApi32e.dll' (GetLastError=126)
LogWindows: File 'VtuneApi32e.dll' does not exist
```
Also -
```
LogInit: Warning: Incompatible or missing module: UE4Editor-TaiYangShenMiao.dll
LogInit: Warning: Incompatible or missing module: UE4Editor-AirSim.dll
Running D:/EpicGames/ue18/UE_4.18/Engine/Binaries/DotNET/UnrealBuildTool.exe taiyangshenmiao Development Win64 -project="D:/Epic/taiyangshenmiao/taiyangshenmiao.uproject" -editorrecompile -progress -NoHotReloadFromIDE
Creating makefile for taiyangshenmiao (no existing makefile)
ERROR: Expecting to find a type to be declared in a target rules named 'taiyangshenmiaoTarget'.  This type must derive from the 'TargetRules' type defined by Unreal Build Tool.
```

Can you share the edited `.uproject` file? The error about the missing `.dll` files seems to be a widespread one in Unreal, with variety of possibilities, removing the `Intermediate` and `Binaries` folder and trying again might work

Hope this helps!

**Comment by sbkybhy** [comment]
I solved my problem. After running "clean_rebuild. Bat", I added "Windows SDK8.1" to vs2017 by reading log file. Thank you for your help！

**Comment by rajat2004** [comment]
@sbkybhy Great!

**Comment by kaushikankur** [comment]
Install windows sdk 8.1 , then run clean.bat and again run update_from_git.bat
