### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by oooohhhhhhh** [microsoft/AirSim#2226]
I tried to run DQNdrone.py 
(https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/DQNdrone.py), and i competed setting the point to fly, but it got error
(MemoryError: Unable to allocate array with shape (500000, 84, 84) and data type float32).
I wonder if you can tell me what mean it is.

appreciate

**Comment by rajat2004** [comment]
A quick calculation shows it's trying to allocate roughly 13 GB of memory, possibly RAM size is smaller.
```
>>> (1.0 * 500000 * 84 * 84 * 32) / (8 * 1024 * 1024 * 1024)
13.142824172973633
```

Try modifying the values here  - https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/DQNdrone.py#L254

I haven't actually ran this till now, so just a suggestion, hope it helps!

**Comment by oooohhhhhhh** [comment]
Thank you i will try it later
