### ISSUE TITLE
Is there a way to Airsim as an OpenAI or gym enviornment?

### ISSUE THREAD

**Issue by Ujwal2910** [microsoft/AirSim#2231]
It would really be very convenient if we could use AirSim environments as gym envs since that would really help in the reusability of many RL algorithms from different baselines and frameworks.
Is there a method to use them as a gym API call or make use of gym. make to get state, reward and other necessary information while training instead of calling a lot of APIs?

**Comment by MoritzGa** [comment]
Yes you can build a wrapper class around AirSim on your own. Only fallback seems to be that you don't have a fixed timestep as in the other gym environments...
