### ISSUE TITLE
libAirsimWrapper.so undefined symbol error

### ISSUE THREAD

**Issue by mrichards0** [microsoft/AirSim#2233]
OS: Ubuntu 18.04
AirSim (latest pull from master branch)
Python 2.7.15+
Unity: 2018.2.7f1 (I also tried 2018.3.0f2)

I followed the instructions for building the Unity version of AirSim (copy/paste style).  It built successfully and there is a Unity/linux-build/libAirsimWrapper.so executable.  Opening the project in Unity_2018.2.7f1 complains that the project was a Unity_2018.2.14 project, but I continued anyway.  I followed the instructions to open Assets/Scenes and only added SimModeSelector to the project.  The libAirsimWrapper library is in Assets/Plugins.  Clicking play and selecting the car mode returns the following error (drone mode has a similar error):

Plugins: Couldn't open Assets/Plugins/libAirsimWrapper.so, error: Assets/Plugins/libAirsimWrapper.so: undefined symbol: _ZN10mavlinkcom9UdpSocket4recvEPvmj
AirSimUnity.VehicleCompanion:.cctor() (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:30)
AirSimUnity.Vehicle:Start() (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:58)
AirSimUnity.Car:Start() (at Assets/AirSimAssets/Scripts/Vehicles/Car/Car.cs:25)

Plugins: Couldn't open Assets/Plugins/libAirsimWrapper.so, error: Assets/Plugins/libAirsimWrapper.so: undefined symbol: _ZN10mavlinkcom9UdpSocket4recvEPvmj
AirSimUnity.VehicleCompanion:InitDelegators() (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:85)
AirSimUnity.VehicleCompanion:.cctor() (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:30)
AirSimUnity.Vehicle:Start() (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:58)
AirSimUnity.Car:Start() (at Assets/AirSimAssets/Scripts/Vehicles/Car/Car.cs:25)

DllNotFoundException: AirsimWrapper
AirSimUnity.VehicleCompanion.InitDelegators () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:85)
AirSimUnity.VehicleCompanion..cctor () (at Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs:30)
Rethrow as TypeInitializationException: The type initializer for 'AirSimUnity.VehicleCompanion' threw an exception.
AirSimUnity.Vehicle.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:58)
AirSimUnity.Car.Start () (at Assets/AirSimAssets/Scripts/Vehicles/Car/Car.cs:25)

NullReferenceException: Object reference not set to an instance of an object
AirSimUnity.Vehicle.OnApplicationQuit () (at Assets/AirSimAssets/Scripts/Vehicles/Vehicle.cs:162)

**Comment by rajat2004** [comment]
@mrichards0 Thanks for reporting this! I had actually noticed it earlier while working on a different PR but had then forgotten about it
https://github.com/microsoft/AirSim/pull/2234 should fix this problem
