### ISSUE TITLE
PX4 VTOL model support

### ISSUE THREAD

**Issue by sunnyroad** [microsoft/AirSim#2240]
Hi, 

Does AirSim currently support  PX4 VTOL model ?

If not, would you help add and support PX4 VTOL model such as "HIL Standard VTOL QuadPlane" and "Generic Quadplane VTOL" ?

**Comment by petergerten** [comment]
I am also very interested in VTOL support. Did you get further with this yet?

**Comment by sunnyroad** [comment]
> I am also very interested in VTOL support. Did you get further with this yet?

No. Can any guys help support this?

**Comment by petergerten** [comment]
I wonder if anyone at least tried this.
The original paper mentions 

> "By allowing the movements of these vertices during the flight it is possible to simulate the vehicles with capabilities such as Vertical Take-Off and Landing  (VTOL) and other recent quadrotors that change their configuration in flight."

**Comment by petergerten** [comment]
Hopefully the work here https://github.com/microsoft/AirSim/issues/2955 can be helpful for VTOL as well.

**Comment by jonyMarino** [comment]
See: https://github.com/AOS55/Fixedwing-Airsim
and continue in #2955 please
