### ISSUE TITLE
Airsim with PX4

### ISSUE THREAD

**Issue by cnun02** [microsoft/AirSim#2246]
my "Setting.json" file.,
```
> {
>   "SettingsVersion": 1.2,
>   "SimMode": "Multirotor",
>   "Vehicles": {
>     "PX4": {
>       "VehicleType": "PX4Multirotor",
>       "UdpIp": "127.0.0.1",
>       "UdpPort": 14560,
>       "UseSerial": false,
>       "LocalHostIp": "192.168.0.4"
>     }
>   }
> }
```
and my Qgc settings.
![rrooe](https://user-images.githubusercontent.com/52391517/66663315-7177e880-ec85-11e9-9d4a-f9b5f051b872.PNG)

I try to HIL Simulation this environment
PX4 v5
UE4 4.18 + airsim
Qgc v3.5.4
and I used wireless Lan,

problem 1.
![connectingerror](https://user-images.githubusercontent.com/52391517/66623552-25965680-ec27-11e9-8aa3-ae5cdc179aa0.PNG)

problem 2.
![capture](https://user-images.githubusercontent.com/52391517/66663489-cca9db00-ec85-11e9-8614-5d837cdafc0c.PNG)

- I changed obviously but didn't change.

![2](https://user-images.githubusercontent.com/52391517/66663467-c1ef4600-ec85-11e9-99ad-6e4706746970.PNG)

-------------------
I do not know how to set IPs in the settings.json...

**Comment by rajat2004** [comment]
Your settings are for SITL, rather than for HITL
For HITL, you'll have to set `UseSerial` to false

**Comment by cnun02** [comment]
thanks..

**Comment by cnun02** [comment]
> Your settings are for SITL, rather than for HITL
> For HITL, you'll have to set `UseSerial` to true

Thanks...I'll try it

**Comment by cnun02** [comment]
> Your settings are for SITL, rather than for HITL
> For HITL, you'll have to set `UseSerial` to true


![tq](https://user-images.githubusercontent.com/52391517/66664405-6cb43400-ec87-11e9-8e75-e7daea26d739.PNG)

Now I have new error..

**Comment by cnun02** [comment]
This problem was solve!
1. Change PX4 v5 -> PX4 v2
2. QgroundControl must off.
3. not change the 'settings.json'

**Comment by Rufio-Boj** [comment]
I had the same problem as you guys and found a way of making it work with PX4 v5 using Windows without the need to change to v2.
In the settings.json file, I changed _"SerialBaudRate":11520_ to **"SerialBaudRate": 921600**  and "SerialPort="*" to the actual port that my computer is using (Look it up in the Device Administrator). In my case, for example, it was **"SerialPort"=COM4.**

Hope this helps!

**Comment by cnun02** [comment]
Thank you, Friend!!!
it does work!!!!!!!

**Comment by Rufio-Boj** [comment]
Glad to help! :)
