### ISSUE TITLE
Documents\Airsim\settings.json not being created, How to change to computervision mode

### ISSUE THREAD

**Issue by DerekvdVen** [microsoft/AirSim#2248]
Hey guys, 

I'm trying to run an adapted cv_capture script to take pictures using drone in an unreal environment, and wanted to change the resolution to 512x512 pixels. I tried to edit the settings.json file in the Airsim directory but I only find two that are in docker or .vscode. Changing settings in these does nothing. I think I'm missing the settings.json file in the Airsim directory, so maybe something is going wrong with the building? 

I want to put the settings like this:
{
  "SettingsVersion": 1.2,
  "CameraDefaults": {
      "CaptureSettings": [
        {
          "ImageType": 0,
          "Width": 512,
          "Height": 512,
          "FOV_Degrees": 90,
          "AutoExposureSpeed": 100,
          "MotionBlurAmount": 0
        }
    ]
  },
  "SimMode": "ComputerVision"
}

I'm using windows 10, AirSim version 1.2, Python 3.7, and Unreal 4.18.3. Have found some related issues, but they are often either outdated, or haven't helped. 

I'm very thankful for any help!

**Comment by rajat2004** [comment]
>  I tried to edit the settings.json file in the Airsim directory but I only find two that are in docker or .vscode. Changing settings in these does nothing. I think I'm missing the settings.json file in the Airsim directory

The `settings.json` file isn't stored in the AirSim directoy, it's created in the normal `Documents` folder present in Windows and Linux

**Comment by DerekvdVen** [comment]
Thank you!
