### ISSUE TITLE
getLidarData() error

### ISSUE THREAD

**Issue by chriscreber** [microsoft/AirSim#2250]
{
	"SettingsVersion": 1.2,
	"SimMode": "Car",
	"Vehicles": {
		"Car4001": {
		  "VehicleType": "PhysXCar",
		  "X": 0, "Y": 0, "Z": -2,
			"Yaw": 0,
			"Sensors": {
				"MyLidar4001": {
					"SensorType": 6,
					"Enabled": true,
					"NumberOfChannels": 16,
					"PointsPerSecond": 10000,
					"X": 0, "Y": 0, "Z": -2,
					"DrawDebugPoints": true
				}
			}
		}
  }
}
Is what my settings.json looks like, but when I call:

LidarData lidar;
msr::airlib::lidar = client.getLidarData("MyLidar4001");

In C++ I get:

rpclib: function 'getLidarData' (called with 2 arg(s)) threw an exception. The exception contained this information: No lidar with name MyLidar4001 exist on vehicle.

And when I run the car_lidar.py I get:

raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: function 'getLidarData' (called with 2 arg(s)) threw an exception. The exception contained this information: No lidar with name MyLidar4001 exist on vehicle.

Does anyone know why it is saying that it doesn't exist on the vehicle when it clearly does?

**Comment by msb336** [comment]
@chriscreber 
What environment are you using, and on what operating system?
