### ISSUE TITLE
how to set a goal

### ISSUE THREAD

**Issue by oooohhhhhhh** [microsoft/AirSim#2253]
Hi, there.
I try to run DQNdrone.py
(https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/DQNdrone.py),
I want to set a point as my goal, and train the multimotor to achieve it, then stop.
I wonder if you can tell me how to modify this code to achieve my goal.
Also, i wonder, what mean is for line 464.
(pts = [np.array([-.55265, -31.9786, -19.0225]), np.array([48.59735, -63.3286, -60.07256]), np.array([193.5974, -55.0786, -46.32256]), np.array([369.2474, 35.32137, -62.5725]), np.array([541.3474, 143.6714, -32.07256])])

**Comment by MoritzGa** [comment]
For your second question: I guess _pts_ describes your desired trajectory. Then you probably penalize or reward your agent for being close to the trajectory or not.

Answering your first question: You either can give negative reward proportional to your distance to your goal or you define a trajectory of points as they did in the example code with the last point being your goal.
