### ISSUE TITLE
Error at startup: Failed to load asset class 

### ISSUE THREAD

**Issue by ZhanLiao** [microsoft/AirSim#2257]
hello everyone,,when i press F5 to run LandscapeMountains.sln, this will start the Unreal Editor.then ,PlayerStart object. something have wrong in following: Error at startup: Failed to load asset class - Class'/AirSim/VehicleAdv/SUV/SuvCarPawn.SuvCarPawn_C'

**Comment by rajat2004** [comment]
Is the default Blocks environment working correctly? If not, then that would be the first thing to fix.
Are you using Windows or Linux? 

Try rebuilding after using `clean.sh` or `clean.cmd`, if that doesn't work, then run `clean_rebuild.sh` which will clean out everything and redownload the assets, which I think should fix the problem
Hope this helps!

**Comment by ZhanLiao** [comment]
default Blocks environment working wrongly，when run block.sln, this displays：can't find UE4.exe

**Comment by ZhanLiao** [comment]
> Is the default Blocks environment working correctly? If not, then that would be the first thing to fix.
> Are you using Windows or Linux?
> 
> Try rebuilding after using `clean.sh` or `clean.cmd`, if that doesn't work, then run `clean_rebuild.sh` which will clean out everything and redownload the assets, which I think should fix the problem
> Hope this helps!

**Comment by dongya-bit** [comment]
> 大家好，当我按F5键运行LandscapeMountains.sln时，这将启动Unreal Editor.then，PlayerStart对象。以下内容有误：启动时出现错误：无法加载资产类-类'/AirSim/VehicleAdv/SUV/SuvCarPawn.SuvCarPawn_C'

I have the same problem. Have you solved your problem

**Comment by huolongguoc** [comment]
I've met the same problem, I tried to delete C:/Users/Document/AirSim/settings.json and started the project again then it worked.
