### ISSUE TITLE
High resolution images

### ISSUE THREAD

**Issue by MoritzGa** [microsoft/AirSim#2258]
Hello community,

I'm wondering how one can take high resolution images from the scenery. Essentially turning everything up concerning quality and than take an image. Is there a setting for that? 

Much appreciated!

**Comment by saihv** [comment]
The UE4 way to capture high res screenshots is to press ~ (console) and type `HighResShot`.

More info at https://docs.unrealengine.com/en-US/Engine/Basics/Screenshots/index.html
