### ISSUE TITLE
Load Custom 3D-Model Of A Quad into AirSim

### ISSUE THREAD

**Issue by EliaTarasov** [Microsoft/AirSim#226]
Does anybody have an idea or an experience how to load custom 3D Unreal quad model into AirSim?
Within plugin's Content directory there are many .uasset files, but there are no references to these files into the code itself. So i suppose these files are used by Unreal itself. 
However it's not clear how to add custom files to the AirSim to be able to use them.

Also, there is second default model supplied: MiniQuadCopter. 
I would like to investigate how to load it, maybe it would help before try to load completely new custom 3D-model.

Thanks!

**Comment by lovettchris** [comment]
This page on [building custom hexacopter ](https://github.com/Microsoft/AirSim/wiki/hexacopter) might help give you what you need.

**Comment by EliaTarasov** [comment]
Thanks, yesterday i figure out where i should begin and the page you mentined is also very helpful. 
I followed instructions and it worked ok.
