### ISSUE TITLE
Error: You Need to Install NullSourceCodeAccessor

### ISSUE THREAD

**Issue by farhanhubble** [microsoft/AirSim#2263]
I am building AirSim on Fedora 28. I had to compile clang-5.0 from source and then used it to compile Unreal, following the steps here: https://microsoft.github.io/AirSim/docs/build_linux/. I then built AirSim. When I launch Unreal Editor and browse the Blocks environment to open it, I get an error: 
```
To open this project you must first install NullSourceCodeAccessor. Would you like to install it now?
```
![image](https://user-images.githubusercontent.com/761785/67146155-bb745600-f2a5-11e9-936d-95803e2869dc.png)

I followed the instructions on the Unreal engine Wiki [here](https://wiki.unrealengine.com/Running_On_Linux#Source_Code_Accessors) and changed this line in `UnrealEngine/Engine/Config/Linux/LinuxEngine.ini`
```
[/Script/SourceCodeAccess.SourceCodeAccessSettings]
PreferredAccessor=NullSourceCodeAccessor
```
to 
```
[/Script/SourceCodeAccess.SourceCodeAccessSettings]
PreferredAccessor=SensibleEditorSourceCodeAccessor
```
which should have picked up Vim as the editor but I keep getting the error, despite having even relaunched UE4Editor time and again.

**Comment by rajat2004** [comment]
This might help you - https://github.com/fire/SensibleEditorSourceCodeAccess
Source - https://answers.unrealengine.com/questions/262589/it-only-shows-vs-for-a-source-code-editor.html 

Also, it's mentioned on the next line in the section for Vim in the Unreal Engine Wiki-

If you are running an engine version that does not have this code accessor built in, run:
```
cd Engine/Plugins/Developer && git clone https://github.com/fire/SensibleEditorSourceCodeAccess
```

**Comment by farhanhubble** [comment]
Thanks Rajat! However, after cloning the plugin, I get another error, right at load time, that says that the plugin could not be loaded because the relevant module was not found.

![image](https://user-images.githubusercontent.com/761785/67146812-49ebd600-f2ac-11e9-9e71-1122f405be6d.png)

I will close this issue though because this is definitely an Unreal issue.

**Comment by rajat2004** [comment]
Did you build Unreal Engine again after cloning the plugin? It's mentioned in the GitHub repo readme

**Comment by farhanhubble** [comment]
Oops! I hadn't. After I rebuilt UE4Editor, the missing plugin error is also gone. Thanks a ton @rajat2004 . I am now getting a different error `/usr/bin/ld: cannot find -lsupc++` for which I'll open a ticket if I cannot  fix it myself.

**Comment by aslepov01** [comment]
I have a similiar problem. After clonning https://github.com/fire/SensibleEditorSourceCodeAccess, patching Engine/Config/Linux/LinuxEngine.ini and rebuilding UE4Editor, I still have message "You Need to Install NullSourceCodeAccessor" while trying to open Blocks project. What  am I doing wrong?

**Comment by fangchaooo** [comment]
because The 'Developer' module type has been deprecated in 4.24

**Comment by fangchaooo** [comment]
because The 'Developer' module type has been deprecated in 4.24
