### ISSUE TITLE
Baro #0 fail: STALE!

### ISSUE THREAD

**Issue by Timebutt** [Microsoft/AirSim#227]
Hi,

I'm getting a lot of `Baro #0 fail: STALE!` errors lately, actually every flight I do seems affected. I don't seem to find anything in the recent commits that might cause this sensor error. Am I missing something, or is something else going on?

![baro_fail](https://cloud.githubusercontent.com/assets/10674081/26355328/86053580-3fc8-11e7-9e33-c315201b8dfc.png)

![bar_fail2](https://cloud.githubusercontent.com/assets/10674081/26355397/c9976a02-3fc8-11e7-8401-9a80302008af.PNG)

Addendum: I also always get an error message saying the system is not receiving anything from the HIL, which makes perfect sense as I don't have a HIL but SITL situtation. Shouldn't these checks be omitted when a SITL simulation is ongoing?

**Comment by lovettchris** [comment]
Yeah I've seen that too, try playing with the [barometer noise ](https://github.com/Microsoft/AirSim/commit/f78f11774055fa7381c9cdf6dc08265c93864226)...

**Comment by sytelus** [comment]
Did commenting out those line solved the baro STALE issue? May be we should look at PX4 code to see what this message means...

**Comment by Timebutt** [comment]
I haven't had the chance to test yet. Will have access to my machine at work earliest on monday, will let you know!

**Comment by Timebutt** [comment]
The recent commit fixed the issue at hand!
