### ISSUE TITLE
rviz.launch as referenced in ros/airsim_ros_pkgs/README.md doesn't exist

### ISSUE THREAD

**Issue by brendan-cleveland** [microsoft/AirSim#2275]
Attempting to follow the ros/airsim_tutorial_pkgs/readme.md tutorial, and running the command
`roslaunch airsim_ros_pkgs rviz.launch` 
causes 
`[rviz.launch] is neither a launch file in package [airsim_ros_pkgs] nor is [airsim_ros_pkgs] a launch file name
The traceback for the exception was written to the log file`
it appears that the file rviz.launch doesn't exist anywhere in the airsim_ros_pkgs, unless I installed something wrong? Should this file be added, or should the tutorial for both packages be changed?

**Comment by madratman** [comment]
fixed: https://github.com/microsoft/AirSim/pull/2295
