### ISSUE TITLE
Map to FBX file

### ISSUE THREAD

**Issue by alonyomtov123** [microsoft/AirSim#2287]
Is there a way to download the environment and then convert it to a FBX file?
Also is there a way to control the multimotor by python code like in airsim?
Thank you

**Comment by saihv** [comment]
This might be helpful:

https://docs.unrealengine.com/en-US/Engine/Sequencer/Workflow/ImportExport/index.html

The multirotor API doc is at https://github.com/microsoft/AirSim/blob/master/docs/apis.md#hello-drone
