### ISSUE TITLE
build.cmd running into problems..

### ISSUE THREAD

**Issue by potBagMeat** [microsoft/AirSim#2288]
I use windows 10 and cmake version was 3.10.2.
My visual studio 2017 also intalled  Windows 8.1 SDK and Visual Studio C++, but when I ran the build.cmd command, this happened.
`C:\Windows\System32\AirSim>build.cmd
Found cmake version: 3.10.2
Starting cmake to build rpclib...
-- Selecting Windows SDK version  to target Windows 10.0.17763.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    E:/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
    Copyright (C) Microsoft Corporation. All rights reserved.

    MSBUILD : error MSB1009: Project file does not exist.
    Switch: VCTargetsPath.vcxproj

  Exit code: 1

-- Configuring incomplete, errors occurred!
See also "C:/Windows/System32/AirSim/external/rpclib/rpclib-2.2.1/build/CMakeFiles/CMakeOutput.log".
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: ALL_BUILD.vcxproj

#### Build failed - see messages above.`
I don't know why, can anyone help me?
Thanks in advance!

**Comment by ArielLopes888** [comment]
Olá! Qual foi a solução?

**Comment by dianzizs** [comment]
Hello, can you share the way that you address this problem? Thanks a lot
