### ISSUE TITLE
Error when launching the project.

### ISSUE THREAD

**Issue by doriand1122** [Microsoft/AirSim#229]
I'm following this video tutorial about AirSim: https://www.youtube.com/watch?v=1oY8Qu5maQQ
Hovewer I get an error when launching the project: The following modules are missing or built with a different engine version: UE4Editor-AirSim.dll. Would you like to rebuild them now?
If I choose Yes, there's another error: MyProject could not be compiled. Try rebuilding from source manually.
If I choose No, nothing happens.
Can anyone help me and point what can be wrong and how to solve this issue? My Unreal version is 4.15.2. I'm using AirSim from repo: https://github.com/Microsoft/AirSim
Thanks.

**Comment by lovettchris** [comment]
What is the specific error?  Perhaps you forgot to set EIGEN_ROOT ?
