### ISSUE TITLE
"Edit on GitHub" links are broken

### ISSUE THREAD

**Issue by lovettchris** [microsoft/AirSim#2305]
At all the pages have an "Edit on GitHub" link, but clicking that link leads to 404 from github.

For example, this page:
https://microsoft.github.io/AirSim/docs/px4_sitl/

Gives this broken link:
https://github.com/microsoft/airsim/edit/master/docs/docs/px4_sitl.md

**Comment by rajat2004** [comment]
I've opened #2313 for fixing this

**Comment by jonyMarino** [comment]
Being treated in #2313

**Comment by rajat2004** [comment]
This can be closed actually, `Edit on Github` button's working

**Comment by jonyMarino** [comment]
I wasn't sure because the links on the first post are not working. But may be they are not on the documents any more
