### ISSUE TITLE
HELP! Where to get PFM image data redirected into another path? 

### ISSUE THREAD

**Issue by jquitgra** [microsoft/AirSim#2307]
# Read This First
I am developing a deep-reinforcement learning algorithm for AI testing with a team, and need a neural network for classification of the PFM images on the quadcopter camera. We see that once we hit record, the images go to our Documents/Airsim directory. However, we are trying to understand where in the scripts provided in Airsim are these images getting directed to our documents folder, so we can get the most recent folder that holds the most recent frame images for further processing.

**Comment by saihv** [comment]
https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/Recording/RecordingFile.cpp#L114
