### ISSUE TITLE
How to display the video effects of three drones at the same time in UE4

### ISSUE THREAD

**Issue by heyz1234** [microsoft/AirSim#2308]
# Read This First

## If you are reporting a bug
* Make sure to write **all reproduction steps**
* Include full error message in text form
* Search issues for error message before filing issue
* Attach screenshot if applicable
* Include code to run if applicable

## If you have question
* Add clear and concise title
* Add OS, AirSim version, Python version, Unreal version if applicable
* Include context on what you are trying to achieve
* Include details of what you already did to find answers

**What's better than filing issue? Filing a pull request :).**

------------------------------------ (Remove above before filing the issue) ------------------------------------

**Comment by heyz1234** [comment]
How to display the video effects of three drones at the same time in UE4

**Comment by saihv** [comment]
Can you tell us what you mean by video effects? Do you want to visualize the onboard camera views of 3 drones simultaneously?

**Comment by jonyMarino** [comment]
Closed due to age and incompleteness
