### ISSUE TITLE
HItL, "Could not open the serial port" "error=5"

### ISSUE THREAD

**Issue by Dynode** [Microsoft/AirSim#231]
Windows 10. Running HITL with Pixhawk PX4 and QGroundControl. QGC sees the device. Windows Device mgr shows the Pixhawk on COM3, looks good. Arming works in QGC.

QGC is run with "Simulation HIL Quadcopter X":
![image](https://cloud.githubusercontent.com/assets/17575688/26377624/5195956c-4011-11e7-9601-85a5dd253c70.png)

Upon starting AirSim I get the following message shown in the attached pic:
![image](https://cloud.githubusercontent.com/assets/17575688/26377295/f9ea100a-400f-11e7-8ed4-7be616ae583c.png)

AirSim build is dated 20170516.

Please; Does someone recognize the error? (I only found seemingly irrelevant hits on Google.)

Thanks. :')

**Comment by lovettchris** [comment]
"and QGroundControl" ? Perhaps QGroundControl has locked the serial port.  Try closing QGroundControl.  Run AirSim, click Play, let it connect, then you can launch QGroundControl and it will connect via the UDP port published by AirSim.  In otherwords, AirSim can also act as a proxy from Pixhawk to QGroundControl.

**Comment by Dynode** [comment]
Ah, of course. That was it. Launched QGC last, works now.

Thanks.
