### ISSUE TITLE
Airsim & Pixhawk v1.9

### ISSUE THREAD

**Issue by Sho412** [microsoft/AirSim#2318]
I try to connect Airsim to Pixhawk v1.9.

Conditions:
A)I use AirSim and Unity on Windows 10 since the combination on Linux is unstable in my environment.
B)I can't execute Pixhawk v1.9 SITL on WSL in Windows 10.
So I try to connect Airsim&Unity on Windows 10 and Pixhawk v1.9 SITL on Ubuntu 16.04.

Points
Change the port number/format suitable for v1.9
-AirSim setting
-Px4 setting
Coment out bind() to work evenif SITL IP address is NOT local.

1)Airsim script (settings.json)
port information is changed between v1.8.2 and v1.9
https://dev.px4.io/v1.8.2/en/simulation/ 
https://dev.px4.io/v1.9.0/en/simulation/
port 14556(UDP)->port 14570(UDP)
port 14560(UDP)-> port 4560(TCP) 
So, I need to add setting information to settins.json
"SitlIp": "xxx.xxx.xxx..xxx",　
"SitlPort": 14570,　
"UdpIp": "xxx.xxx.xxx.xxx",　
"UdpPort": 14560

2) Px4 script for SITL
./ROMFS/px4fmu_common/init.d-posix/rcS 
I modify 3 lines 

original: mavlink start -x -u $udp_gcs_port_local -r 4000000
modify:mavlink start -x -u $udp_gcs_port_local -t xxx.xxx.xxx..xxx -r 4000000

original:simulator_tcp_port=$((4560+px4_instance))
modify:simulator_tcp_port=$((14560+px4_instance))

original:simulator start -s -c $simulator_tcp_port
modify:simulator start -s -u $simulator_tcp_port

3)Modify AirSim code
Target file AirSim\MavLinkCom\src\serial_com\UdpClientPort.cpp
comment out bind()

// int rc = bind(sock, reinterpret_cast<sockaddr*>(&localaddr), addrlen);

Also comment out if(){}

//if (rc < 0){}

Redefine rc

int rc;

4)Rebuild Airsim
>build.cmd

5)execute px4
>make px4_sitl_default none

Enjoy.

**Comment by saihv** [comment]
Integration with PX4 1.9 has been introduced in https://github.com/microsoft/AirSim/pull/2310, please try the new code.
