### ISSUE TITLE
UAV equipped with binocular camera parameters

### ISSUE THREAD

**Issue by surongkai** [microsoft/AirSim#2321]
UAV equipped with binocular camera parameters
windows, AirSim version 1.2, pycharm2017.3.3, Unreal version 18.04
What is the internal reference fx fy cx cy of the camera when using the depth map obtained by the camera in the drone HIL process? How to set it?

------------------------------------ (Remove above before filing the issue) ------------------------------------

**Comment by orangelx** [comment]
I also want to how to get the camera intrinsics in Airsim....the API "simGetCameraInfo" can get the 'proj_mat', but the 'proj_mat' is wrong..    
Here is the :
'proj_mat': <ProjectionMatrix> {   'matrix': [   [   -4.371138828673793e-08,
                      0.0,
                      0.0,
                      0.0],
                  [   0.0,
                      -7.770913157401083e-08,
                      0.0,
                      0.0],
                  [   0.0,
                      0.0,
                      0.0,
                      1.0],
                  [   0.0,
                      0.0,
                      10.0,
                      0.0]]}

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
