### ISSUE TITLE
SITL failure with PX4 in ubuntu 

### ISSUE THREAD

**Issue by xlong0513** [microsoft/AirSim#2323]
Hi, Ubuntu here. i use launch/px4.launch to start  SITL, but it cannot connect to the AirSim. It keeps waiting for the port as the following image shows:
![图片](https://user-images.githubusercontent.com/35829321/69429008-8a3be980-0d6d-11ea-84c1-be181154d1b8.png)

 And the QGroundControl cannot be connected either.
![图片](https://user-images.githubusercontent.com/35829321/69429074-b48da700-0d6d-11ea-8aae-6a367f8815a8.png)

But when i launch the "launch/posix_sitl.launch" with gazebo, it works well.

What's the problem?

**Comment by Sho412** [comment]
How the version of Px4 is? v1.9.x?

**Comment by xlong0513** [comment]
@Sho412   Checkout to 1.8.2, it;s ok now. But how to connect it with ros or mavros? Do u know that? Appreciate it.

**Comment by Sho412** [comment]
Sorry I don't know. Also interested in your question.
P.S. If you'd like to use v 1.9, see #2318

**Comment by xlong0513** [comment]
OK! Thanks for the reply.

**Comment by marufino** [comment]
@xlong0513 you should be able to run px4.launch from the default mavros ros package, with the `fcu_url` changed to `<arg name="fcu_url" default="udp://:14540@127.0.0.1:14557" />`
