### ISSUE TITLE
Apply Maximum Speed Constraint to Car

### ISSUE THREAD

**Issue by moritzgarl** [microsoft/AirSim#2327]
Hello everyone,

I am wondering whether there is a way to put an **additional constraint on the maximum reachable velocity** on the car?

I want to test the performance of a trained reinforcement learning agent on lower speed as I trained the agent to maximize its velocity.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
