### ISSUE TITLE
HItL, quadrotors (BP_FlyingPawn) are unstable after takeoff (default & custom models)

### ISSUE THREAD

**Issue by Dynode** [Microsoft/AirSim#233]
I experience unstable behavior with the default drone model even in a clean AirSim build. I suspect I'm missing something critical about how AirSim works with the Pixhawk -- does the latter need to be tuned in Px4, or does AirSim take care of that? AirSim simulates sensor data, yes?

I've attached a screenshot with sensor data on the right (view is FPV with a 2nd cam underneath):
![image](https://cloud.githubusercontent.com/assets/17575688/26422147/f3c785a4-40c8-11e7-91d2-a17c5a1062dd.png)

The drone is not armed in this picture. Upon taking of, it begins to oscillate violently, spin and drift uncontrollably, or drift and crash (depending on weight params set in Px4MultiRotor::setupFrameGenericQuad). Any idea what the source of this is?

**Comment by Dynode** [comment]
Update: When the physical constants for the drone model is ok, it seems this is an issue only when the RC is not connected, like when running the "takeoff" command in DroneShell. When the constants are way off, the drone get unstable. That's my thought anyways.

**Comment by sytelus** [comment]
Which physical constants? Rotors or drones? Could you please post example values that produces bad behavior?

**Comment by Dynode** [comment]
Alright, I edited the previous post, can't reset the to the bad consts atm, will do tomorrow but iirc, bad oscillations happened in manual flight (RC connected) with default RotorParams values and too small motor_assembly_weight in Px4MultiRotor.hpp::setupFrameGenericQuad() after adjusting arm length to about 70 cm. I'm sorry I can't be more specific atm but I'm pretty sure at this time that some of my troubles are due to bad calibration and just plain wrong params. :')

**Comment by sytelus** [comment]
Closing this as this was issue to specific setup.
