### ISSUE TITLE
Eigen dependency download broken

### ISSUE THREAD

**Issue by petergerten** [microsoft/AirSim#2331]
Downloading the Eigen dependency (in setup.sh) does not work anymore.

`wget http://bitbucket.org/eigen/eigen/get/3.3.2.zip`

results in

```
HTTP request sent, awaiting response... 401 Unauthorized
Username/Password Authentication Failed.
```

**Comment by petergerten** [comment]
The github mirror works:
https://github.com/eigenteam/eigen-git-mirror/archive/3.3.2.zip

**Comment by saihv** [comment]
Works for me on Ubuntu 18.04. Perhaps something was up with your network temporarily.. could you try again?

**Comment by asherikov** [comment]
Eigen is migrating to GitLab, they have already updated download links on their website. It is not clear how long the downloads will be available from bitbucket. github mirror is scheduled for removal as well. 
Please update your scripts.

**Comment by saihv** [comment]
@asherikov Good catch, thanks for letting us know. I'll update the URLs to gitlab
