### ISSUE TITLE
how to control the attitude of car or multi-rotor

### ISSUE THREAD

**Issue by zhanghouxin07** [microsoft/AirSim#2338]
Hello,
now, I can control the car or multi-rotor by Airsim. 
Taking the drone as an example, I found that I can directly control the speed of the drone in the xyz three-axis direction through the c ++ api. But I want to know if I can directly set the attitude of the drone and ignore the mathematical model. For example, I want the drone to stop at a pitch and roll angle of 0 and a yaw angle of 50 degrees.

I guess there should be no fixed functional interface like this. Therefore, I want to know if I can modify the source code to directly set the position and attitude.
if the answer is 'yes', I want to figure out， What is the workload of this modification?

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
