### ISSUE TITLE
Custom quadrotor model physics problem, won't stand upright

### ISSUE THREAD

**Issue by Dynode** [Microsoft/AirSim#234]
EDIT: See my post from 20170525 for how this was handled.
---------
I've imported a custom model (Gryphon Dyn. X8, long legs), the rotors are set accordingly as per instructions / the default quadrotor BP_FlyingPawn. The frame and rotors are a bit larger than the default model / pawn. Model origo is such that the rotors are about the same height / offset as on the default setup in UE4 (I have yet to understand line 57 - 59 in Px4MultiRotor.cpp, "set up dimensions of core body box or abdomen (not including arms)").

The models just plain refuses to stand upright; it slowly tips over and slowly spins randomly while the collision count constantly increases. There is clearly something going on with the physics sim part on this model.

-- Is there anything that has to be done in UE4, or does AirSim detect model boundaries? Any precautions we need to take when making new 3D models?

Thanks again.

EDIT: An older model of the same quadrotor frame stands upright as expected, it has close to the same offset from the zero plane (when BP_FlyingPawn is viewed in the Viewport tab).
Screenshot:
![image](https://cloud.githubusercontent.com/assets/17575688/26423850/7bb358fc-40cf-11e7-99cc-fa2610c4e99b.png)

The unstable model just has a canopy and fewer polygons (reduced in MeshLab). To say I'm confused is an understatement. I imported both models in UE4.

**Comment by lovettchris** [comment]
> The models just plain refuses to stand upright; it slowly tips over and slowly spins randomly while the collision count constantly increases

I had the same problem with my hexacopter model, something to do with the long legs, and ground contract not working properly.  This is a physics bug of some sort, we are looking into it...   In the meantime you should be able to take off before this starts happening and fly ok, at least that's what I could do with my hexacopter model.

**Comment by Dynode** [comment]
@lovettchris Thanks, I'll try to look into it as well, compare our two models.

**Comment by sytelus** [comment]
I think there is a problem with ground detection code... Right now I'm travelling but hope to experiment with potential fix around 15th June after I get back...

**Comment by Dynode** [comment]
Solved this to the point where starting AirSim and resetting the drone is stable in almost all cases. Now what happens is the height at which the model comes to rest at on the ground varies a little.
