### ISSUE TITLE
normalizedForce is compared to normalizedGravity, is not a physical nonsense?

### ISSUE THREAD

**Issue by marcociara379** [microsoft/AirSim#2341]
Hello everyone.
Looking at [FastPhysicsEngine.hpp](https://github.com/microsoft/AirSim/blob/master/AirLib/include/physics/FastPhysicsEngine.hpp#L330) it is possible to see that the aircraft is set to not grounded (`body.setGrounded(false)`) whenever the normalizedForce (squared norm of body_wrench.force) is greater or equal the normalizedGravity. Why is that? They are different physical quantities. Should not it be something like 
```
if (normalizedForce/body.getMass()/body.getMass() >= normalizedGravity)
[...]
```

Thanks,
Marco

**Comment by madratman** [comment]
https://github.com/microsoft/AirSim/pull/2473
