### ISSUE TITLE
AirSim - Automatic takeoff and landing training with wind and external forces using neural networks

### ISSUE THREAD

**Issue by xabierolaz** [microsoft/AirSim#2342]
Hi, I'm new to AirSim and would like to know where should I begin my research. I'd like to train drones inside AirSim using deep learning, so it can learn how to optimize landings and takeoffs with adverse climate (mainly wind), so we can then transfer all this data to the real drone.

Any hint about where to start would be greatly appreciated, thanks for your time!

**Comment by xabierolaz** [comment]
bump

**Comment by aiaarif** [comment]
Maybe you can take a look here on how to add wind. ->  #284

**Comment by petergerten** [comment]
@xabierolaz did you get further with your project?

**Comment by xabierolaz** [comment]
> 
> 
> @xabierolaz did you get further with your project?

No, had to switch to gazebo and openAI
