### ISSUE TITLE
Require password  when extract CityEnviron.zip.001!

### ISSUE THREAD

**Issue by csuwp** [microsoft/AirSim#2343]
![image](https://user-images.githubusercontent.com/27015842/70633143-05a50280-1c6b-11ea-8d06-ddc173057102.png)

**Comment by jonyMarino** [comment]
Not happening on latest version. Please refer version and platform.
Please feel free to open a new issue if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing issue
*Attach screenshot if applicable
*Include code to run if applicable

Thanks!
