### ISSUE TITLE
Drone Shell GPS Lock

### ISSUE THREAD

**Issue by eanmikale** [Microsoft/AirSim#235]
Having issues getting the Drone Shell to gain a GPS lock. I've made sure that QGround Control is not open. The simulator is running, and when I execute the DroneShell and wait for the GPS to lock, it will not do so no matter how long I wait. Any ideas on troubleshooting? Thanks again.

**Comment by lovettchris** [comment]
Are you using HITL mode with Pixhawk hardware or SITL mode ?  If HIL mode did you select the "HIL Quadrocopter X" AirFrame using QGroundControl?

**Comment by eanmikale** [comment]
Yes. I am using HITL mode with Pixhawk hardware (IRIS+). In HIL I have selected the "HIL Quadcopter X" Airframe using QGroundControl. In QGroundControl I still do not see a GPS Lock. When first close QGroundControl, and then open up Unreal Engine, and open up the landscape mountains project, or the Modular Neighborhood project, press play, and then go back into the AirSim folder and select DroneShell, it continues to read "Waitinf for drone to report a valid GPS location." I wonder if two functions are utilizing the same port, not allowing the GPS to be read by the either QGroundControl or DroneShell. Hopefully, you have some thoughts on this. Once we get past this challenge, we'll be home free as far as what we need. Thank you for your hard work again.

**Comment by eanmikale** [comment]
I also read somewhere that it may be the local proxy? If internet connect has anything to do with it, our office internet has some hoops to jump through. Just a thought.

**Comment by clovett** [comment]
Sounds like you are doing everything correctly.  It should work.  It would help if you could provide some logs, as per [logging](https://github.com/Microsoft/AirSim/blob/master/docs/logging.md).  You can also look at the hilgps messages being sent by AirSim using [LogViewer](https://github.com/Microsoft/AirSim/blob/master/docs/log_viewer.md).

**Comment by eanmikale** [comment]
I found the issue. One of the port numbers was off by 1. Everything works beautifully. Thank you.

**Comment by lovettchris** [comment]
great!

**Comment by eanmikale** [comment]
Chris,
We'd like to discuss a potential partnership in the education space as we release a commercial product to place nice with AirSim. Please let us know how to connect. More soon. 

Warm Regards,

Ean Mikale, J.D.

Chief Innovation Officer

Infinite 8 Institute, L3C

ean@infinite8institute.com

www.infinite8institute.com





U.S. Federal Contractor




---- On Fri, 02 Jun 2017 16:40:41 -0500 notifications@github.com wrote ----



Are you using HITL mode with Pixhawk hardware or SITL mode ? If HIL mode did you select the "HIL Quadrocopter X" AirFrame using QGroundControl?
