### ISSUE TITLE
Semantic Segmentation with Multi-Component Prefab

### ISSUE THREAD

**Issue by RaiMunoz** [microsoft/AirSim#2352]
OS: Windows/Ubuntu
Airsim: Latest, Unreal : 4.22

When running airsim, the semantic segmentation only shows prefab buildings as building id including details such as windows, or water basins that should have a separate id. Is it possible to create an individual label for these objects in the prefab? If so, how?

Currently, I've tried editing the AirBlueprintLib in initializing the stencil id's but to no luck, as well as tried setting it separately on the python api, but to no luck.

Thank you for your understanding and consideration.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
