### ISSUE TITLE
How to stop game when running command？

### ISSUE THREAD

**Issue by jinkman** [microsoft/AirSim#2354]
If I close the game when the command is running, the game will wait for the command to be executed. How can I make the RPC thread end when the game is finished? It's in pie mode.

like this command:
client.moveToPositionAsync(0, 0, -20, 1.0, 50.0,DrivetrainType::MaxDegreeOfFreedom,YawMode(true,90),-1.0,1.0,"Drone2")->waitOnLastTask();

**Comment by saihv** [comment]
I am bit unclear as to what you mean by "if I close the game" - are you saying the background process is not being killed?

**Comment by ironclownfish** [comment]
You need to halt the rpc call on your client. I recommend using a timeout.
