### ISSUE TITLE
Semantic segmentation colours not in the seg_rgbs.txt

### ISSUE THREAD

**Issue by ivannson** [microsoft/AirSim#2358]
I am collecting some segmentation images, but upon displaying them, I found that the colours in my segmentation image do not correspond to any colours specified in `seg_rgbs.txt`. 

This is the image produced:
<img width="206" alt="Screenshot 2019-12-25 at 17 22 23" src="https://user-images.githubusercontent.com/42695412/71448798-78b97900-2741-11ea-96f7-8702d3ecd050.png">

Data collection code snippet: 
```python 
responses = client.simGetImages([
            airsim.ImageRequest("2", airsim.ImageType.DepthPerspective, compress = False, pixels_as_float = True),  #depth visualization image
            airsim.ImageRequest("0", airsim.ImageType.Scene, compress = False), #png format
            airsim.ImageRequest("0", airsim.ImageType.Segmentation, False, False)])

filename = 'images/segmentation/' + 'segmentation' + str(file_sequence)
        img1d = np.fromstring(responses[2].image_data_uint8, dtype=np.uint8) #get numpy array
        img_rgb = img1d.reshape(responses[2].height, responses[2].width, 3) #reshape array to 4 channel image array H X W X 3
        img_rgb = np.flipud(img_rgb) #original image is fliped vertically

        np.save(filename, img_rgb)
```

By looking at the colours, for example top left quadrant with a building in dark yellow, I get `[203 174  42]` as the rgb values, however this colour doesn't seem to correspond to any label `seg_rgbs.txt`.

**Comment by TDYbrownrc** [comment]
I am having similar issues. What version of Unreal engine are you using? I have seen this behavior on 4.19 and 4.23.

**Comment by ivannson** [comment]
@TDYbrownrc I'm using 4.22. 

The work around that I'm using right now is using infrared camera instead of segmentation view.

**Comment by averyehorvath** [comment]
I pulled in the latest changes of Airsim and updated to Unreal 4.24 and that fixed it for me

**Comment by jonyMarino** [comment]
@ivannson could you check?

**Comment by rajat2004** [comment]
https://github.com/microsoft/AirSim/pull/2845 fixed this problem

**Comment by lucafei** [comment]
hello, @ivannson do you have checked the workaround #2845? For me i have also met this problem that colors in my segmentation image are not same with the RGB value specified in seg_rgbs.txt.
