### ISSUE TITLE
Follow object flight error

### ISSUE THREAD

**Issue by jinkman** [microsoft/AirSim#2359]
My goal is for the drone to follow the object。
But there was a mistake：
LogTemp: Error: Exception occurred while updating world: PositionController does not support yaw axis i.e. 3
LogTemp: Error: Exception occurred while updating world: reset() must be called first before update()
My idea is to get the target's position in each frame, and then let the Multirotor fly to the destination.
i get the destination at MultirotorPawnSimApi::pawnTick.
code like this:
`void MultirotorPawnSimApi::pawnTick(float dt)
{
    unused(dt);
    //calls to update* are handled by physics engine and in SimModeWorldBase
	//static float total_time = 0.0;
	//total_time += dt;

	if (enable_follow )
	{
		FVector follow_pos;
		Cast<AFlyingPawn>(getPawn())->getFollowPos(followName, follow_pos);

		NedTransform ned_transform = getNedTransform(); 
		const auto& move_ned_pos = ned_transform.toLocalNed(follow_pos);
		getVehicleApi()->setFollowPos(move_ned_pos);
	}

}`

getFollowPos(const std::string& name,FVector& follow_pos); can get the follow_pos by name;
setFollowPos(move_ned_pos) can set the value of MultirotorApiBase::follow_position;
And then there's the logic to follow：
`bool MultirotorApiBase::followingTarget(float during_time)
{
	SingleTaskCall lock(this);

	if (during_time <= 0)
		return false;
	follow_position = getPosition();
	float speed = 10.0;

	return waitForFunction([&]() {
		// adjust the speed
		follow_position += Vector3r(0.0, 0.0, -5.0);
		Vector3r move_dir = follow_position - getPosition();
		float follow_dis = move_dir.norm();
		move_dir = move_dir.normalized();

		speed = follow_dis * 1.2;
		if (speed > 10.0)
		{
			speed = 10.0;
		}
		move_dir *= speed;

		if (follow_dis>0.2)
		{
			moveToPosition(follow_position.x(),
				follow_position.y(), follow_position.z(),
				speed, 0.2, DrivetrainType::ForwardOnly, YawMode(false, 0.0), -1, 1);
		}
		return false; //keep moving until timeout
	}, during_time).isTimeout();
}`

MultirotorRpcLibServer.cpp add this:
`(static_cast<rpc::server*>(getServer()))->
		bind("followingTarget", [&](const std::string& follow_name,float during_time, const std::string& vehicle_name) -> bool {
		getVehicleSimApi(vehicle_name)->enableFollow(true, follow_name);
		bool res = getVehicleApi(vehicle_name)->followingTarget(during_time);
		getVehicleSimApi(vehicle_name)->enableFollow(false, "");
		return res;
	});`

I don't know why it happened, but it doesn't happen every time. Is it a multi-threaded problem? Please help me.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
