### ISSUE TITLE
How to add drones by command?

### ISSUE THREAD

**Issue by jinkman** [microsoft/AirSim#2360]
How to add drones by command? i wana to create a command to add drones During program operation. who can give me some advance suggestion？

**Comment by obitodaitu** [comment]
write json  in setting.json to add drones.

**Comment by jinkman** [comment]
> write json in setting.json to add drones.

I want to build it when the program is running, not at the beginning. Use the command on the client.

**Comment by jinkman** [comment]
[the answer](https://github.com/microsoft/AirSim/pull/1937/commits/dc8fc2cbae4c9224604472f1ede353587eec9100)
