### ISSUE TITLE
Drone Speed

### ISSUE THREAD

**Issue by MohamedAfifii** [microsoft/AirSim#2363]
I am using `moveByVelocityAsync`. When I give it a target `vx` of 50 m/s, it can achieve only 28 m/s. Can I do anything to change the limitations on the linear speed?

**Comment by saihv** [comment]
Are you using simple flight or PX4?

**Comment by MohamedAfifii** [comment]
I am using simple flight. I tried to change the `VehicleType` to `PX4Multirotor` from `settings.json` but I wasn't able to use functions like `moveOnPathAsync` or `moveByVelocityAsync`.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
