### ISSUE TITLE
PositionController does not support  yaw axis i.e. 3

### ISSUE THREAD

**Issue by jinkman** [microsoft/AirSim#2364]
[Spawn vehicle via rpc](https://github.com/microsoft/AirSim/pull/1937/commits/dc8fc2cbae4c9224604472f1ede353587eec9100),
I made a follow this link to generate the vehicle's command, this command did a good job, 
but I use the client. The moveToPositionAsync (10, 10, 10, 10, 10, DrivetrainType: : ForwardOnly, YawMode (false, 0.0), 1.0, 1.0, "My") - > waitOnLastTask ();",
there will be mistakes. Like This:
![image](https://user-images.githubusercontent.com/50129609/71584448-90cc3680-2b4d-11ea-80f5-e75b4d70d68a.png)
The vehicle generated from the.json file is fine.I'd like to know which circumstances led to the error.The error seems to be related to the length of time.My game mode is sampleflight

**Comment by jinkman** [comment]
LogTemp: Error: Exception occurred while updating world: PositionController does not support yaw axis i.e. 3
LogTemp: Error: Exception occurred while updating world: reset() must be called first before update()
LogTemp: Error: Exception occurred while updating world: reset() must be called first before update()
LogTemp: Error: Exception occurred while updating world: reset() must be called first before update()

**Comment by jonyMarino** [comment]
treated on new PR #2390. Look there
