### ISSUE TITLE
Airsim community survey 

### ISSUE THREAD

**Issue by guadacasuso** [microsoft/AirSim#2366]
Hi everyone
The AirSim team is trying to get a better understanding of how AirSim and other simulation engines are being used across the community. If you have a couple minutes, please take a look and respond to the AirSim survey as it does have an impact on features and direction of the platform:

[Survey link](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4J_69QtqUREtdPd5aLYTsFUQkZMMVE2S1FXVkVUM1JNUUxPRDNZVDlDVS4u)

**Comment by ibrahim0v** [comment]
Done :) keep it up guys
