### ISSUE TITLE
Texture Streaming Pool error, screens black

### ISSUE THREAD

**Issue by Dynode** [Microsoft/AirSim#237]
Was flying around in our env, crashed & reset position a few times, crashed again and then the following result:

![image](https://cloud.githubusercontent.com/assets/17575688/26498494/864da996-422f-11e7-8a51-afe6f2d3b282.png)

Anyone knows?

EDIT: This is with the current changes which have been in place in several flight tests in AirSim with no problems: https://github.com/Microsoft/AirSim/issues/219 (last post)

**Comment by lovettchris** [comment]
Please check latest bits, there was an uninitialized variable that might have corrupted memory.
