### ISSUE TITLE
AirSim Python: rpclib: server could not find function 'getCarControls' with argument count 1

### ISSUE THREAD

**Issue by christian-vorhemus** [microsoft/AirSim#2372]
Versions:
python 3.6.8
airsim 1.2.5
msgpack-rpc-python 0.4.1

I've seen there was a `getCarControls()` function added to the CarClient class in one of the latest airsim Python modules. However, when I try to call it

```
client = airsim.CarClient()
client.confirmConnection()
car_controls = client.getCarControls()
```

I get

`msgpackrpc.error.RPCError: rpclib: server could not find function 'getCarControls' with argument count 1.`

I've tested "Neighborhood" from the latest precompiled binaries from [here](https://github.com/microsoft/AirSim/releases/tag/v.1.2.2). I've seen the API [is in the source](https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/Vehicles/Car/CarPawnApi.cpp#L38) - are the precompiled binaries from an older code base?

Probably also related to #2245

**Comment by rajat2004** [comment]
> are the precompiled binaries from an older code base?

Yes, commit https://github.com/microsoft/AirSim/commit/f1bb14c2f7d3c86252882a02ec4e65c193c24487 which added the `getCarControls` API was done after the release. It's working correctly in master right now
