### ISSUE TITLE
Unable to use any of the prebuilt Unreal enviornments with ROS on Linux

### ISSUE THREAD

**Issue by jstestsuite** [microsoft/AirSim#2374]
When trying to run the prebuild Unreal environments following the ROS tutorial: `https://github.com/microsoft/AirSim/tree/master/ros/src/airsim_tutorial_pkgs`

The following error occurs:
`Exception raised by the API:
rpclib: server could not find function 'getImuData' with argument count 2.
error`

**Comment by rajat2004** [comment]
Prebuilt environments for Linux are quite old (a year ago now). The API was probably added after the release, it'll be better to build AirSim from source and use
