### ISSUE TITLE
Using `gzserver` (Gazebo backend) with Airsim

### ISSUE THREAD

**Issue by karanchawla** [microsoft/AirSim#2380]
**What I'm trying to do**: I'm trying to use Airsim only as a frontend visualization tool and use Gazebo backend for modeling and physics. (reason being I've a lot of custom plugins developed in Gazebo at the moment) 

**Question**: Is there a way to achieve this in Airsim? If yes, how would one go about interfacing gazebo data with Airsim?

**Comment by rajat2004** [comment]
AirSim is a physics plugin, using Unreal Engine or Unity for the graphics. AFAIK, there's no way to disconnect the physics and graphics, and even if there is, will be quite a difficult task.
But will leave it up to the main developers for their opinions on the matter
