### ISSUE TITLE
PX4 Log Viewer wont connect to AirSim ¿How can I get Quadcopter's 4-rotors log during a takeoff?

### ISSUE THREAD

**Issue by xabierolaz** [microsoft/AirSim#2382]
Using:
Unreal 4.18
PX4 Log Viewer
SITL: simpleflight

PX4 Log Viewer wont connect to AirSim, followed instructions but quadcopter inside PX4 Log Viewer wont get any input while entering some simpleflight commands in AirSim.

EDIT: Tried using a RC controller too, quad flies correctly but Log Viewer wont receive any data

![log](https://user-images.githubusercontent.com/31626226/72515028-8dc08e00-384f-11ea-94c2-97ada3a9bd1a.JPG)

settings.json is as follows:
{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor",
    "Vehicles": {
        "PX4": {
            "VehicleType": "PX4Multirotor",
            "UseSerial": false,
            "UseTcp": true,
            "TcpPort": 4560,
            "ControlPort": 14580,
            "LogViewerHostIp": "127.0.0.1",
            "LogViewerPort": 14388,
            "params": {
                "NAV_RCL_ACT": 0,
                "NAV_DLL_ACT": 0,
                "LPE_LAT": 47.641468,
                "LPE_LON": -122.140165,
                "COM_OBL_ACT": 1
            }
        }
    }
}

**Comment by xabierolaz** [comment]
any ideas?

**Comment by xabierolaz** [comment]
Did anyone get this?

**Comment by jonyMarino** [comment]
Hi @xabierolaz! LogViewer was recently fixed!
