### ISSUE TITLE
Lidar offset in the 'Setting.h doesn't' mean the 'relative' position to the drone body frame

### ISSUE THREAD

**Issue by didwjdrl12** [microsoft/AirSim#2385]
Hi, I'm Jeonggi Yang in Republic of Korea. 
We developed some simulators by using AirSim. Thanks you.
Recently, we found some bugs of Lidar offset function.

As you mention, 

X Y Z | Position of the lidar relative to the vehicle (in NED, in   meters)

in settings.h file.

But the lidar position is not moved when I set the X:5 and rotated the drone in the yaw directions

![x1](https://user-images.githubusercontent.com/31721955/72508953-f2004380-3889-11ea-8f90-1f41259a86a2.PNG)
![x2](https://user-images.githubusercontent.com/31721955/72508957-f3317080-3889-11ea-954d-247d41662164.PNG)

And in the code, Ray starting point is not affected with Drone's attitude.
Please, fix this phenomenon.

Thank you.

**Comment by rajat2004** [comment]
Hi, is this the behaviour with the latest master? https://github.com/microsoft/AirSim/pull/2143 has been merged which I think fixed this problem

**Comment by didwjdrl12** [comment]
Hi,
We developed some projects on old version. We didn't know that It was solved lately.
I think It is okay to close the issue.
 
Thank you.
-----Original Message-----
