### ISSUE TITLE
Unreal engine crash with SITL simulation

### ISSUE THREAD

**Issue by Mzhouyi** [Microsoft/AirSim#239]
Hello,
I am trying to launch the simulation using Unreal engine with SITL. But unreal engine crashed when pressing the play button for simulation. Gamemode is set to SimGamemode.
Can someone help to resolve this?

setup:

Airsim and Unrealengine are built and created the test project: MyProject.uproject
Airsim plugin is loaded in the test project.
Selected the gamemode as SimGameMode from WorldSettings
Press the play button for simulation.
Did i miss anything here?

![54](https://cloud.githubusercontent.com/assets/26813115/26519500/934b2554-42f4-11e7-9dd8-033aca009015.PNG)

**Comment by lukaszdworako** [comment]
If you are starting directly from unreal engine (meaning you start the unreal project directly) I had the same problem. Solution was to open the .sln project after generating the relevant code from the .uproject directory, opening the .sln project in visual studio set to debug game mode, run from there then run the Unreal engine project. TLDR; Start unreal using the .sln project files then run from there
