### ISSUE TITLE
unable to run Sitl and Airsim on different devices on same network

### ISSUE THREAD

**Issue by tahameg** [microsoft/AirSim#2393]
It is pretty much self-explanatory actually. I have been working on this for almost one week and could not find a way for this. Steps I have tried so far:

- Changing the localHostIp to ip of Sitl device which didn't work. Than i have realized the initiation port is started by simulation device not the Sitl device. 
- I have routed sitl tcp port 4560 to port 4560 of simulation device via ssh tunneling and it worked. Now simulation sees the Sitl but presumably cannot get and send sensor and motor data with it.

**Comment by jonyMarino** [comment]
Look at latest MavlinkCom updates.
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
