### ISSUE TITLE
I want to know how to make a stable hover by RC in simple flight mode

### ISSUE THREAD

**Issue by gniwon** [microsoft/AirSim#2398]
It's hard to hover when I'm manipulating drones with RC.

I want to know how to do it.

**Comment by rajat2004** [comment]
SimpleFlight, as the name suggests, is a simple firmware, designed to integrate easily with Airsim. AFAIK, it doesn't have any special flight modes as such, which make it easier to fly using RC, such as assisted flight modes in PX4. For this, you'll have to use other firmwares such PX4 or ArduPilot
Just my thoughts, would love to know if I'm wrong
