### ISSUE TITLE
Control of each individual rotor

### ISSUE THREAD

**Issue by devangsrammohan** [Microsoft/AirSim#240]
Hi,

Quick question. I was going through the python client that is provided and noticed that enables me to `moveByVelocity`, `moveByVelocityZ` etc. I was wondering whether control of each rotor individually and details pertaining to its current state were going to be exposed going forward. 

The reason I ask is that, while the APIs themselves are quite exhaustive to collect training data for any agent we wish to develop to control the drone, it might also be of interest to develop an algorithm to learn "How to Fly" (i.e, learn to hover, fly in a straight line etc.) from scratch, rather than just using the functions provided. This would then also open up the scope of getting them to learn how to fly with additional load or under inclement weather.

**Comment by lovettchris** [comment]
The closest you can get to that is moveByAngle.  This will power the rotors to tilt the drone to the specified angle.  But direct control of individual rotors is not possible using our api.  For that you would need to also modify the px4 firmware.  But I would caution that this would be tricky.  Typically attitude control loop on the drone round at high frequency (1000 hz).
