### ISSUE TITLE
simGetLidarSegmentation() do not match getLidarData().point_cloud

### ISSUE THREAD

**Issue by xiaoaoran** [microsoft/AirSim#2409]
I tried to get segmentation ground truth via `client.simGetLidarSegmentation()`:

`lidarData = self.client.getLidarData()`
`lidarSeg = self.client.simGetLidarSegmentation()`

`print(len(lidarData.point_cloud))`
`>>>3858`
`print(len(lidarSeg))`
`>>>1336`
So the number of lidar point in `lidarData` should be 3858/3=1286, which is not equal to the number of ground truth points in `lidarSeg `

but @ironclownfish  said 

> api function: simGetLidarSegmentation().
Returns the segmentation of each lidar point's collided object in the last lidar update. i.e. the segmentation IDs align with getLidarData().point_cloud
[https://github.com/microsoft/AirSim/pull/2011#issue-286773742](url)

Anyone could tell me why? Thanks!

**Comment by xiaoaoran** [comment]
Please help me with this problem

**Comment by xiaoaoran** [comment]
Hello?

**Comment by TheFloe1995** [comment]
I also stumbled across this issue. It seems that you have to call both functions _right after each other_. 

In a quick experiment I called both functions directly after each other at 10 FPS while moving. Most of the time the number of points was equal in both lists. But in 7/300 cases they were different. 

Seems to be timing dependent which is quite inconvenient in my opinion. Are there any plans to change that behaviour, e.g. having a single function call to get the point cloud + segmentation IDs?

**Comment by rajat2004** [comment]
I've opened #2810 which combines segmentation data into `LidarData` struct fetched using `getLidarData`
