### ISSUE TITLE
Question: Adding cable suspended payload to Airsim multirotor

### ISSUE THREAD

**Issue by aiaarif** [microsoft/AirSim#2411]
I am trying to simulate a cable-suspended payload with Airsim. I can't seem to find any resources in Airsim documentation/elsewhere that will help me get started. After going through some resources available from the Unreal engine community, I am able to suspend a payload, enable physical constraints and physics on the payload. 

On the surface, things look fine in terms of payload simulation. However, the force doesn't translate to the multirotor. No matter what size/weight the payload is, the multirotor flight characteristic is not affected at all. 

Can someone tell me what I might be doing wrong? Or, point me to the right resources for this?

**Comment by aiaarif** [comment]
bump

**Comment by ironclownfish** [comment]
This would be nontrivial to achieve, since the multirotor physics are separate from the engine physics. Your best bet is to compute the forces yourself and apply them to the multirotor in code. Take a look at physics_engine_ in SimModeWorldBase.h
