### ISSUE TITLE
Unreal SUV is Shaking

### ISSUE THREAD

**Issue by ITali21** [microsoft/AirSim#2412]
I'm use unreal engine 4.18 and airsim 1.2.0 versions. When I start driving SUV, the SUV and the camera start to shaking extremely. I didn't change the SUV settings. I don't found problem reason.

Video of problem:
https://drive.google.com/file/d/1IEeAgwM2I3kzpKS2-FRIo6CTARADADQV/view?usp=sharing

Anyone could tell me why? and can i solve this problem. Thanks!

**Comment by ironclownfish** [comment]
I'm guessing this has to do with the collision detection with the ground. Does your ground have bumps or small holes in it? Can you try putting one of Unreal's default plane objects in the scene and driving on it, and see if the issue occurs in that case? (The default plane is definitely perfectly flat)

**Comment by jonyMarino** [comment]
closed due to lack of response
