### ISSUE TITLE
Missing pom.xml

### ISSUE THREAD

**Issue by charbelmansour** [microsoft/AirSim#2414]
Hello,
We followed these steps:
1) git clone https://github.com/alexandrelombard/airsim-jvm-api

2) cd airsim-jvm-api

3) mvn clean install

When we reached step 3 we obtained the following error:

![image1](https://user-images.githubusercontent.com/60031311/74262446-9056bc00-4d05-11ea-8581-b215aded5c49.png)

Can you please give us advice about this issue.
The pom.xml is missing from the project.
Thank you for your help
Best Regards,

**Comment by rajat2004** [comment]
Since this is a problem with the other repository and not the main AirSim one, maybe open an issue there?

**Comment by charbelmansour** [comment]
Yes, thank you. We opened an issue in the other repository
