### ISSUE TITLE
Cars in Airsim - Force Shifters support?

### ISSUE THREAD

**Issue by elgalu** [microsoft/AirSim#2420]
[Logitech G920 Steering Wheel](https://microsoft.github.io/AirSim/docs/steering_wheel_installation/) is supported

What about [Logitech Driving Force Shifter for G920](https://www.amazon.de/dp/B00ZWOUH4S/) ?

**Comment by ironclownfish** [comment]
Our car doesn't currently model transmission, but you could emulate this behavior client-side to some degree by making the speed of the car (via the API) a function of this thing's gear setting.
