### ISSUE TITLE
Question about fps of simGetImage()

### ISSUE THREAD

**Issue by Beniko95J** [microsoft/AirSim#2425]
Hi, I succeeded to run AirSim on my notebook, and now I am trying to obtain rgb images and IMU measurements from AirSim to create a dataset for the use of testing a visual-inertial SLAM algorithm. I am expecting to obtain IMU measurements at 200Hz and images at 20Hz.

I have succeeded to obtain IMU measurements at 200Hz with calling **getImuData()** every 0.005 second and the frequency is quite stable. However, I can only obtain images up to 3Hz while I call **simGetImages()** every 0.05 second. I have tried the below:
1. resolution : 144x256, scene : Block  ---> 3Hz
2. resolution : 288x512, scene : Block ---> 3Hz
3. resolution : 576x1024, scene : block ---> 1.5Hz
4. resolution : 144x256, scene : Landscape  ---> 3Hz
5. resolution : 288x512, scene : Landscape ---> 3Hz
6. resolution : 576x1024, scene : Landscape ---> 1.5Hz

Does this have anything to do with the spec of the computer (I am using a notetbook) or something restricted the fps？

Os : macOs Catalina 10.15.3
Unreal version : 4.21.2
Python version : 3.7.6
AirSim version : latest

**Comment by ironclownfish** [comment]
Improved image capture speed is by far the most requested feature in airsim.
Capture frequency is coupled with frame rate to some extent, so having a higher-spec computer can help. You should definitely set your max framerate to 999999 in the console. (Press ~, then enter t.MaxFrameRate 99999999)

But it's also bottle-necked by concurrency issues and by the fact that images are compressed and sent over RPC individually.

We have some marginal improvements to image capture internally planned for integration soon.
