### ISSUE TITLE
Mixing drones and cars in one simulation ?

### ISSUE THREAD

**Issue by MaJeg** [microsoft/AirSim#2429]
Hello,

I would like to know if it was possible to mix car and drone in one simulation. In the settings file, there is a SimMode config element that can have either the "Multirotor" or "Car" value. Does it mean that we can't have both car and drone in the same simulator ? I would like to do ground target tracking and using a car controlled using the airsim API as a ground target could help me implement this scenario.

Best regards,

Mathieu

**Comment by ironclownfish** [comment]
Indeed, the simulation will only spawn the vehicle whose type matches SimMode. However, if you add a car actor as part of the scene, you could move it around via the API simSetObjectPose("name_of_car_actor", new_pose). It just won't have rotating wheels or driving physics.
