### ISSUE TITLE
Is it possible to increase or decrease the simulation speed?

### ISSUE THREAD

**Issue by galgyeony** [Microsoft/AirSim#243]
Hello,
I have read the technical report (Aerial Informatics and Robotics Platform) and found out that adjusting the rapid rate is possible to save simulation time (e.g., hundreads of seconds of real-world can be simulated in one second).
However, I couldn't find any API or method to do that.
It it really possible in AirSim? If possible, how to configure?

Thanks in advance.

**Comment by lovettchris** [comment]
The paper didn't mean to imply that we could speed up the simulation clock by orders of magnitude, it was simply referring to how long it takes to plan and organize a real drone flight compared to doing flights in the simulator.   But the clock time can be speed up only by the amount of spare CPU that you have available after rendering frames and running physics model.  On powerful machines there is some head room for speeding up the clock, but not a lot.   So the other way you can get lots more from simulator compared to the real world is to scale your tests out across a server farm.
