### ISSUE TITLE
When is a new linux release planned?

### ISSUE THREAD

**Issue by Neabfi** [microsoft/AirSim#2430]
The only way I managed to get AirSim to work is by using the 1.2.0 release. However, lots of new features are missing such as the weather API.

When is a new linux release planned?

Thank you!

**Comment by theold190** [comment]
A similar question was asked in https://github.com/microsoft/AirSim/issues/2477. And there were some answers and details on a new linux release.

@Neabfi, does that answer your quetion? Is there anything else you expect to be answered/provided in this issue?
