### ISSUE TITLE
Can CarClient communicate over UDP?

### ISSUE THREAD

**Issue by ivannson** [microsoft/AirSim#2431]
As far as I'm aware `airsim.CarClien(ip = '123.45.678')` uses TCP. Is it possible to use UDP instead?

**Comment by ironclownfish** [comment]
Alas, we only support our API over RPC for now. Perhaps in the future UDP would be useful for things such as retrieving video streams from the vehicle.

**Comment by ivannson** [comment]
@ironclownfish Thanks for the reply. Quick question, what are the capabilities of RPC? Is it only able to send the control commands, but not retrieve the data?

**Comment by usef1370** [comment]
@ironclownfish I want to create a rpcs server in unity or unreal using Python client to control simulated vehicles like airsim how can i do? help me please
