### ISSUE TITLE
Low level move api question : commandPosition, commandVelocityZ etc...

### ISSUE THREAD

**Issue by HelloEgg** [microsoft/AirSim#2435]
Hi.

I'm trying to modify quadrotor dynamics model.

From code review of AirLib/src/vehicles/multirotor/api/MultirotorApiBase.cpp,

I noticed that eventually drone is moved with following functions :

    virtual void commandRollPitchZ(float pitch, float roll, float z, float yaw) = 0;
    virtual void commandRollPitchThrottle(float pitch, float roll, float throttle, float yaw_rate) = 0;
    virtual void commandVelocity(float vx, float vy, float vz, const YawMode& yaw_mode) = 0;
    virtual void commandVelocityZ(float vx, float vy, float z, const YawMode& yaw_mode) = 0;
    virtual void commandPosition(float x, float y, float z, const YawMode& yaw_mode) = 0;

which are found in AirLib/include/vehicles/multirotor/api/MultirotorApiBase.hpp.

Where are these functions defined? I couldn't find its reference within Airsim repo.

Thank you!

**Comment by rajat2004** [comment]
Hi,
These functions are implemented separately on a firmware-by-firmware basis. For example, in SimpleFlight, the implementation can be seen here - https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/firmwares/simple_flight/SimpleFlightApi.hpp#L198

Going to the other firmware directories such as Mavlink(PX4) or ArduCopter, the files ending with API inherit from the MultiRotorApiBase class and implement these functions
PX4 implementation sends specific mavlink commands to the PX4 firmware running, while ArduPilot currently doesn't support AirSim's Movement APIs and does nothing in them
