### ISSUE TITLE
Airsim Suddenly stops responding to Python API

### ISSUE THREAD

**Issue by caesar84** [microsoft/AirSim#2437]
hi.
I am facing a problem that Airsim started suddenly to not responding to Python APIs. I was testing some of the functions and parameters effects on the flying mode and everything was fine. Out of nowhere, the drone is not responding to any API whether it was from the ones shipped with the package or a customized API. I tried to restart Unreal, AirSim, and Python but nothing worked. running a 'Takeoff.py' for instance give me the screen in attached image 1, when forcing the script to stop I get the error in image 2. I, running the recent version of Airsim on VS 2017, Unreal 4.18 and windows 10. the error is happening with the Blocks environment and AirSimNH that is available to download. I thought there is something wrong with the connection so I tried to ping 127.0.0.1 and from python and there is a reply.
I would appreciate it if someone can help 

thanks
![AirSim1](https://user-images.githubusercontent.com/16879951/75618242-64d82c00-5b63-11ea-9825-60bd9e6aae7b.jpg)
![Airsim2](https://user-images.githubusercontent.com/16879951/75618246-6ace0d00-5b63-11ea-8d38-8d5d8b134001.jpg)

**Comment by ironclownfish** [comment]
It looks like you might have a zombie Unreal process running that is consuming the API commands. If you kill the process (or reboot) it will probably help. This happens to me fairly often.
