### ISSUE TITLE
Inconsistent mesh names in binaries

### ISSUE THREAD

**Issue by BenediktKol** [microsoft/AirSim#2439]
I am trying to get ground truth segmentation images in the "Neighborhood" environment using the v1.2.0 - Linux binary. 

The specific issue I am facing is getting the segmentation of power lines / wires separately (i.e. the wires should be a different colour compared to other objects such as poles and ground). 

For some of the power lines it is easy, the following code works well:

```
# Changes the colour of the wires only and not the poles.  
success = client.simSetSegmentationObjectID("power_line_cable[\w]*", 100, True)
```

However, for most of the power lines this does not work. That is because they have a different mesh name. For some reason these power lines are grouped with other meshes such as the poles and also some ground elements. The following code can change the colour of the wires but it also changes the colour of additional objects which I do not want:

```
# Changes the colour of wires, poles and other ground objects  
success = client.simSetSegmentationObjectID("landscape_0", 100, True)
```
&nbsp;

To try to fix this problem I changed the mesh naming method in the settings.json file as follows:
`"SegmentationSettings": { "MeshNamingMethod": "StaticMeshName" }`

This is better but not perfect. As before, the colour of some wires can be changed independently using the same code as before:
```
# Changes the colour of the wires only and not the poles.  
success = client.simSetSegmentationObjectID("power_line_cable[\w]*", 100, True)
```
The segmentation colour for the remaining wires in the environment can be changed but they are still grouped with the poles.
```
# Changes the colour of wires and poles 
success = client.simSetSegmentationObjectID("power_line_complete_01", 100, True)
```

&nbsp;

Is it possible to split the "power_line_complete_01" mesh in the same way as the other wires and poles in the environment?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
