### ISSUE TITLE
I want to use the function of Playing Logs in MavLinkTest,but it didn't work

### ISSUE THREAD

**Issue by dreamerlang** [microsoft/AirSim#2443]
I want to use the *.mavlink log file to make Multirotor fly in airsim simulator by following the flight path of a real drone. But it didn't work, I don't know if something is wrong with my “settings.json”. 
here is the screenshot of console window:
![image](https://user-images.githubusercontent.com/37436344/75959234-c6e4b880-5ef8-11ea-995e-c378ed99197c.png)
here is my settings.json:
![image](https://user-images.githubusercontent.com/37436344/75959311-f1367600-5ef8-11ea-93cb-89e2ebd40e93.png)
And i followed this instruction:
https://microsoft.github.io/AirSim/docs/playback/

**Comment by rajat2004** [comment]
Mavlink log files only work with PX4, default firmware is SimpleFlight which you're using currently
