### ISSUE TITLE
Change buildings' texture images

### ISSUE THREAD

**Issue by TomAvrech** [microsoft/AirSim#2445]
I want to simply change the images that appear on everything, for example on buildings.
How can this be done ?

Thanks.

**Comment by rajat2004** [comment]
You'll probably have to customize the Unreal environment yourself for such a usecase
Could have a look at https://github.com/microsoft/AirSim/pull/2296, might be helpful

**Comment by ironclownfish** [comment]
> Could have a look at #2296, might be helpful

rajat2004 is correct. This feature is available on my fork of airsim; please take a look at the linked PR.
