### ISSUE TITLE
is Airsim still maintained?

### ISSUE THREAD

**Issue by marcociara379** [microsoft/AirSim#2448]
Hello,
it looks lie AirSim is not maintained anymore. Can we have some clarification?

Thanks

**Comment by theold190** [comment]
Checking https://github.com/microsoft/AirSim/commits/master I can see number of recent commits in April 2020. There are bug fixes, improvements, code refactoring that comes from at least 4-5 developers. So, it looks like project is still worked on.

It seems that there were few weeks without commits in February and March 2020. Checking https://github.com/microsoft/AirSim/graphs/contributors (the contribution graph during a year) you can see that there are ups and downs in repository activity. So, I guess it is a normal situation.

@marcociara379, does that answer your question? Or did you mean something else?

**Comment by marcociara379** [comment]
@theold190 yes, last month was much more active than the beginning of the current year. 
Thanks!
