### ISSUE TITLE
How to connect pixhawk with QGround control while the simulator is running.

### ISSUE THREAD

**Issue by Sneha-hub115** [microsoft/AirSim#2450]
Hi,
I’m using ubuntu18.04 to build the px4 code for gazebo and jmavsim. I’m stuck with the following issues:
1. How to connect pixhawk with QGround control while the simulator(jMAVSim,Gazebo) is running.
2.  How to connect pixhawk with QGround control while the drone is flying.

Thank you

**Comment by rajat2004** [comment]
This issue isn't related to AirSim and should be closed. Try posting on PX4 or QGC repo or their forums
