### ISSUE TITLE
How to get out of full screen in QGround control

### ISSUE THREAD

**Issue by Sneha-hub115** [microsoft/AirSim#2451]
Hi,
I’m using ubuntu 18.04 to build the px4 code for gazebo and jmavsim using QGround control. I’m stuck with the following issue:

1. How to get out of full screen in QGround control.

Thank you

**Comment by rajat2004** [comment]
There is a minimize button on the top-right corner, if that doesn't work, could try going to some other application's window using Alt+Tab or something
The issue isn't connected to AirSim, and should be closed here. Try posting on QGC's repo or their forums
