### ISSUE TITLE
Zooming or changing camera FOV

### ISSUE THREAD

**Issue by Dynode** [Microsoft/AirSim#247]
I know BP_PIPCamera in UE4 has a FOV parameter that affects all cams, but can we "zoom" just the main view or the PIPs? That would be nice. I've been unable to pinpoint relevant code for this.

**Comment by lovettchris** [comment]
The field of view is configured using unreal editor, open the AirSim BluePrint PIP_Camera, open the camera component, and the details panel will show you the camera settings.  When we get the [UCameraComponent ](https://docs.unrealengine.com/latest/INT/API/Runtime/Engine/Camera/UCameraComponent/index.html) in code, you can also modify these settings at runtime, perhaps using AdditiveFOVOffset.

![image](https://cloud.githubusercontent.com/assets/18707114/26712585/32df6f4a-479a-11e7-95eb-6a200face845.png)

**Comment by Dynode** [comment]
Alright, thanks. Fingers crossed for getting access to UCameraComponent in code, then.

**Comment by sytelus** [comment]
We have added new settings for camera now including FOV: https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#changing-resolution-and-camera-parameters
