### ISSUE TITLE
Can't enable fog or dust 

### ISSUE THREAD

**Issue by ivannson** [microsoft/AirSim#2470]
I'm trying to enable different weather using the API, but I don't seem to be able to use either fog or dust. 

This is the command that I'm running:
```python
client.simSetWeatherParameter(airsim.WeatherParameter.Fog, 0.50)
```

I tried using `weather.py` script, and they don't work there either. 

I can't use weather in editor since I'm using a remote desktop to access Unreal Editor and my F10 key doesn't work there.

**Comment by ironclownfish** [comment]
Weather is implemented on a per-level basis, so these affects won't always be applicable.
And don't forget you'll want to call simEnableWeather(True) before anything else.

**Comment by ivannson** [comment]
Thanks @ironclownfish , I checked, and the `simEnableWeather(True)` is enabled, and I can control rain/snow/leaves. What I find weird is that a) fog/dust works on Windows b) on Linux fog and dust don't work even in the Blocks environment (other weather effects still do). 

For reference, I'm running Ubuntu 18.04, Unreal 4.22

**Comment by kochsebastian** [comment]
Same problem for me. I used fog just the other day but now it's not working anymore and I didn't change anything that should affect fog

**Comment by lucafei** [comment]
> Same problem for me. I used fog just the other day but now it's not working anymore and I didn't change anything that should affect fog

maybe you can try the weather window in simulation, check if it works?

**Comment by kochsebastian** [comment]
After some experimenting I know what the problem was: I used to render the Engine with OpenGL, because it consumes less processing power. But only when you use Vulcan you can model fog or dust.
Vulcan is the default of course.

**Comment by ivannson** [comment]
@kochsebastian Yes, that must be it! In my case it didn't work in Linux where OpenGL is the default.

**Comment by fu1199** [comment]
@ivannson I am beginning to develop maps with airsim plugin in UE. Can you give me an advice how to enable vulkan for UE 4.25 under Linux?

Thanks a lot!
