### ISSUE TITLE
Dynamically Change Physical Properties through API

### ISSUE THREAD

**Issue by Travestie** [microsoft/AirSim#2476]
Would it be possible to add API calls to change the parameters of the vehicle?
I am looking to dynamically change Drag, Mass, Max Thrust etc. for some optimization development. 
I have tried following the trail on their calls, but I have not been able to find an end.

**Comment by rajat2004** [comment]
I'm not sure, but I don't think it's possible to dynamically change the physical parameters of the vehicle. Could be wrong, in that case would love to know more about it
You could have a look at the new APIs for setting the PID gains, etc. of the vehicle, which might be of use here

**Comment by Travestie** [comment]
Saw those, yes they are interesting and very helpful for tuning. I am more interested in the design of a quad copter. Restarting and tweaking code instead of an optimization  function and a for loop would take a significant amount of time for the flight envelope to appear. Even with the optimization function, it would still probably take a weekend or longer.

I did manage to compile a significant amount of code revealing the physical properties to the API. Untested right now, but will get back with an answer.

**Comment by jonyMarino** [comment]
@Travestie How did you go?

**Comment by geniusyko** [comment]
@Travestie How is the progress so far?

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
