### ISSUE TITLE
Is it necessary to install a GPS module when I run HITL?

### ISSUE THREAD

**Issue by home26** [microsoft/AirSim#2480]
Hi

My computer was not equipped with a GPS module and there is no GPS module in pixhawk too. I cannot control drone to take off both in QGC and Airsim.(see picture below) So is it necessary to install a GPS module in my computer or pixhawk if I want to run HITL?

Thank you in advance!
![pic1](https://user-images.githubusercontent.com/45549502/77549358-1bd77700-6e86-11ea-9c40-5942763354f1.png)

**Comment by rajat2004** [comment]
Shouldn't be, GPS messages are generated by AirSim and sent to Pixhawk in HITL. If you have specified sensors in your `settings.json`, check if GPS is present in them

**Comment by home26** [comment]
Got it, Thank you so much!

**Comment by rajat2004** [comment]
@home26 If the problem has been solved, please do close the issue :)
