### ISSUE TITLE
How to Load an Environment with the Python API?

### ISSUE THREAD

**Issue by flolu** [microsoft/AirSim#2484]
How is it possible to load a specific environment vai the Python API? I remember seeing a function like `simLoadLevel()` but I can't find anything like this.

**Comment by madratman** [comment]
Hi @flolu, you saw that in the Game of Drones competition repo here https://github.com/microsoft/AirSim-Neurips2019-drone-racing#loading-unreal-engine-environments
We're working towards porting `simLoadLevel` to this repo, it's a bit tricky with the number of environments in the main public repo and some environments misbehaving when tried to be `pak`ed. But we're hoping to get that done soon.

**Comment by flolu** [comment]
@madratman Ok, that feature would be really handy. Thanks for the fast response :)
