### ISSUE TITLE
Changing dynamics of the quadrotor

### ISSUE THREAD

**Issue by mayanksjha** [microsoft/AirSim#2491]
Hi all, I need to vary the dynamics in the existing model, such as variation in the resistance of the motor , or friction coefficient of the joints. so my question is , would I able to vary the existing dynamics on this platform?? and then use it in conjunction with al other funcitonalities? ..If so, how? ..kindly direct me towards some links. Regards, mayank

**Comment by jonyMarino** [comment]
Take a look at the FastPhysics code. You can also connect to a Gazebo model.
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
