### ISSUE TITLE
Compilation error in latest release

### ISSUE THREAD

**Issue by songxiaocheng** [microsoft/AirSim#2496]
The Blocks project in AirSim v1.3.0 have compilation errors with UE 4.18:
```
1><path-ro-airsim>\Unreal\Environments\Blocks\Plugins\AirSim\Source\WorldSimApi.cpp(211): error C2660: 'DrawDebugString': function does not take 8 arguments
1>C:\Program Files\Epic Games\UE_4.18\Engine\Source\Runtime\Engine\Public\DrawDebugHelpers.h(47): note: see declaration of 'DrawDebugString'
1><path-ro-airsim>\Unreal\Environments\Blocks\Plugins\AirSim\Source\WorldSimApi.cpp(230): error C2660: 'DrawDebugString': function does not take 8 arguments
1>C:\Program Files\Epic Games\UE_4.18\Engine\Source\Runtime\Engine\Public\DrawDebugHelpers.h(47): note: see declaration of 'DrawDebugString'
```
https://github.com/microsoft/AirSim/blob/03d239b3377b7ff34a5a0bcc58372f7c8d0db2fd/Unreal/Plugins/AirSim/Source/WorldSimApi.cpp#L211
https://github.com/microsoft/AirSim/blob/03d239b3377b7ff34a5a0bcc58372f7c8d0db2fd/Unreal/Plugins/AirSim/Source/WorldSimApi.cpp#L230

It is because `DrawDebugString` in UE 4.18 was declared to have only 7 arguments. The last argument is missing. This is fixed by UE later (it seems form UE 4.20, see [this commit](https://github.com/EpicGames/UnrealEngine/commit/d90da4ab1af73942ea27ce8261e5c3520103550b#diff-575f4a0024b1974a4e441f35259c5942)). However, the "empty versions" of this function still not changed but it seems irrelevant to this Airsim issue (I am not familiar with UE's implementation but there is a UE issue mentioned this, see [here](https://issues.unrealengine.com/issue/UE-71998)).

But the Airsim documentation still recommends UE 4.18. I think systematically upgrading UE to newer versions is a good way to fix this problem. Temporarily, I have to delete the last argument of `DrawDebugString` in `WorldSimApi.cpp`.

**Comment by rajat2004** [comment]
Yes, the documentation needs to be updated. I believe from this release AirSim will require UE>=4.22 (or maybe even 4.24). Some more PRs in the line (https://github.com/microsoft/AirSim/pull/2482, https://github.com/microsoft/AirSim/pull/2472) will require the newer UE versions

**Comment by madratman** [comment]
Updated the docs https://microsoft.github.io/AirSim/build_windows/ 
Current master works on UE>=4.22, but we do recommend 4.24.
