### ISSUE TITLE
Framerate drop when UE4 window out of focus

### ISSUE THREAD

**Issue by thias15** [Microsoft/AirSim#25]
When trying to control the UAV through the command line, the simulator becomes extremely slow. It seems in general whenever the window is out of focus, the simulator drops a lot of frames. Is there a workaround for that?

**Comment by sytelus** [comment]
I think you are facing this issue:

https://answers.unrealengine.com/questions/145958/huge-framerate-drop-when-game-window-unfocused-454.html

Please let us know if that resolved it.

**Comment by thias15** [comment]
Resolved.
