### ISSUE TITLE
Windows，Lidar question. 

### ISSUE THREAD

**Issue by hi123jack** [microsoft/AirSim#2503]
lidar can be set Vertical step by number of channels,but how to set Horizon step ?

**Comment by hi123jack** [comment]
please help

**Comment by marufino** [comment]
see https://github.com/microsoft/AirSim/blob/master/docs/lidar.md
Points per second in combination with rotations per second allows you to define the Horizontal resolution.
ex: The following
NumberOfChannels: 64
PointsPerSecond: 655360
RotationsPerSecond: 10

would effectively result in 1024 (655360 / 10 / 64) points per rotation, and a horizontal resolution of ~0.35 degrees
