### ISSUE TITLE
getCarControls() throwing error

### ISSUE THREAD

**Issue by omarsamyb** [microsoft/AirSim#2528]
Hello everyone, i am trying to record data for a deep learning purpose while driving the car manually. When i try to call getCarControls() to get the steering , throttle values etc.. it throws this error in console
msgpackrpc.error.RPCError: rpclib: server could not find function 'getCarControls' with argument count 1.
although getCarState works just fine.
I'm on Windows 10 using python 3.7 and airsim 1.2.7 package.
I tried searching this issue but found minimal results with no answers to them.
TIA

**Comment by rajat2004** [comment]
Hi, 
`getCarControls()` is working correctly for me on Linux with the latest AirSim master as well as the release. Are you using a release binary, or built from source? If it's a release, please try the latest v1.3.0

**Comment by omarsamyb** [comment]
> Hi,
> `getCarControls()` is working correctly for me on Linux with the latest AirSim master as well as the release. Are you using a release binary, or built from source? If it's a release, please try the latest v1.3.0

Hi sorry for late reply, i am using binary release from here [https://github.com/microsoft/AirSim/releases/tag/v.1.2.2](url)
using the CityEnviron environment and the latest airsim package 1.2.7 from pip, i noticed that the CityEnviron is under v1.2.2 release , could this be causing the problem like getCarControls() is not compatible in this?

**Comment by rajat2004** [comment]
Yes, commit f1bb14c which added the getCarControls API was done after the 1.2.2 release. It's working correctly in master and the latest release

**Comment by omarsamyb** [comment]
> Yes, commit [f1bb14c](https://github.com/microsoft/AirSim/commit/f1bb14c2f7d3c86252882a02ec4e65c193c24487) which added the getCarControls API was done after the 1.2.2 release. It's working correctly in master and the latest release

ok thank you, is it possible that any time soon to have the city environment binary posted in the latest release?
