### ISSUE TITLE
request ApiControl() must be called before using API control

### ISSUE THREAD

**Issue by johan606303** [microsoft/AirSim#2530]
Hi. Can someone please wrtite a detailed explanation of how to solve this issue ? I'm new with airsim, and when I tried to follow one of tutorial video, I got this issue when I tried to manualy control a quadcopter.

Thanks.

**Comment by rajat2004** [comment]
Don't see what's unclear about the statement, `enableAPIcontrol()` should be called before using any APIs to control the movement
https://github.com/microsoft/AirSim/blob/master/docs/apis.md#common-apis
See the examples in PythonClient/multirotor for exmaples

**Comment by johan606303** [comment]
And where am I supposed to write those commands ? When I launched the Blocks, Airsim.sln, DroneShell.exe ?

**Comment by rajat2004** [comment]
The video you're following seems to be quite an old one, don't know if Droneshell is being actively maintained or used. I haven't myself used it ever
These are Python or C++ APIs, for Python, can be run from a python terminal with the `airsim` package installed. There are ready-made examples in the PythonClient folder to experiment and use the APIs

**Comment by johan606303** [comment]
DroneShell works, just need to write "requestcontrol" first.

**Comment by johan606303** [comment]
Then is it possible to pose an another question here, a bit different, not about manual control anymore ?

**Comment by majingchunn** [comment]
> DroneShell 可以工作，只需要先写“requestcontrol”即可。

我不太理解，请问有具体操作嘛？在哪里写requestcontrol？
