### ISSUE TITLE
try to control the drone by using api

### ISSUE THREAD

**Issue by dreamerlang** [microsoft/AirSim#2546]
I try to control the drone by using api with PX4 SITL, but it failed. 
when I try to call the function client.armDisarm, it occurred that msgpackrpc.error.RPCError: rpclib: function 'armDisarm' (called with 2 arg(s)) threw an exception. The exception contained this information: **Vehicle does not have a valid GPS home location.**

Here is my setting.json file:
{
  "SettingsVersion": 1.2,
  "ClockSpeed": 1.0,
  "SimMode": "Multirotor",
  "Vehicles": {
    "PX4": {
      "LocalHostIp": "x.x.x.x",
      "UdpIp": "x.x.x.x",
      "UdpPort": 14560,
      "ControlIp": "x.x.x.x",
      "ControlPort": 14560,
      "VehicleType": "PX4Multirotor",
      "UseSerial": false,
      "UseTcp": false,

      "params": {
        "NAV_RCL_ACT": 0,
        "NAV_DLL_ACT": 0,
        "LPE_LAT": 47.641468,
        "LPE_LON": -122.140165,
        "COM_OBL_ACT": 1
      },
      "X": 0,
      "Y": -16,
      "Z": 0
 
    }

  }
}
Here is the python script:
client = airsim.MultirotorClient()
client.confirmConnection()

client.enableApiControl(True, vehicle_name="PX4")
client.armDisarm(True,vehicle_name="PX4")
client.moveToPositionAsync(2,2,-2,2,vehicle_name="PX4").join()

**Comment by rajat2004** [comment]
You seem to have modified the default settings for PX4, along with the port numbers. Try changing it back to the default TCP and port numbers and see if happens, I think the latest PX4 requires TCP for Lockstep scheduling

**Comment by madratman** [comment]
```json
{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "Vehicles": {
      "PX4": {
          "VehicleType": "PX4Multirotor",
          "UseSerial": false,
          "UseTcp": true,
          "TcpPort": 4560,
          "ControlPort": 14580,
          "params": {
              "NAV_RCL_ACT": 0,
              "NAV_DLL_ACT": 0,
              "LPE_LAT": 47.641468,
              "LPE_LON": -122.140165,
              "COM_OBL_ACT": 1
          }
      }
  }
}
```
px4 v1.10.1 should work
https://microsoft.github.io/AirSim/px4_sitl/
