### ISSUE TITLE
Environment generation issue

### ISSUE THREAD

**Issue by johan606303** [microsoft/AirSim#2550]
Hi. I successfully created environments for Blocks, by following tutorial. But when I try to create my own environment, for example the basic "blank", when I execute .sln file, I have build errors.
Nevertheless I added plugins to the project and I changed .uproject where I added :
			"AdditionalDependencies": [
				"AirSim"
			]
to the Module field and 
	"Plugins": [
		{
			"Name": "AirSim",
			"Enabled": true
		}
	]
I don't understand what is wrong.
I use Windows 10, for UE4 --> engine 4.24.3, VS2019 and I just try to create Blank environment where I would simulate a multirotor.

Thanks for help.

**Comment by rajat2004** [comment]
Can you post the compilation errors which you're getting?

**Comment by johan606303** [comment]
Well here it is. Sorry for the wait.
![errors](https://user-images.githubusercontent.com/62846458/78812998-a4006500-79cc-11ea-8b8b-49d86a3ebaa1.PNG)

**Comment by rajat2004** [comment]
#2526 has been merged which should fix this error

**Comment by johan606303** [comment]
Thank you, I will try.

**Comment by johan606303** [comment]
OK. Thank you.

**Comment by rajat2004** [comment]
The problem has been fixed, issue can be closed now
