### ISSUE TITLE
Implement off-road tracked vehicle model 

### ISSUE THREAD

**Issue by jvr-nava** [microsoft/AirSim#2557]
I'm trying to implement my own off-road vehicle into AirSim. This tracked vehicle modeled was previously developed without AirSim in mind, it has custom physics (it has it's own physics pre-tick, tick and post tick). As well as some custom code for advanced track friction and spring-damper elements). My course of action is to modify AirSim's CarPawn class by disabling the unneeded code while extending the functions to match my own TrackedVehiclePawn class (including the custom tick events) are there any special considerations to this kind of implementation. I already looked at the PawnPaths methods but this is not quite what I need since the tracks need some custom functions for physics and animation.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
