### ISSUE TITLE
Error in python API to takeoff

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#256]
I am running the python API script for takeoff (`takeoff.py`) and I am getting the following error: 
```
Waiting for home GPS location to be set...
Home lat=47.6415, lon=-122.14, alt=121.326
Traceback (most recent call last):
  File "takeoff.py", line 22, in <module>
    if (client.getLandedState() == LandedState.Landed):
  File "C:\Users\xam\Desktop\AirSim\PythonClient\PythonClient.py", line 61, in getLandedState
    return self.client.call('getLandedState')
  File "C:\Python27\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\Python27\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: server could not find function 'getLandedState' with argument count 0.
```

Is anyone else also having the same problem?

**Comment by lovettchris** [comment]
This would mean you need to rebuild, some boys are your of date.  I use build.cmd to ensure correct bits, followed by an xcooy to my unreal environment, then a clean rebuild of my unreal project.   see the unreal/environment/blocks/update_from_git.bat.  You should do this every time you update airsim code.

**Comment by Mayankm96** [comment]
Seems like it's working now. I'll keep the rebuilding tip in mind.

**Comment by yongwon2** [comment]
I don't know how to build to build.cmd
