### ISSUE TITLE
Distance sensor problem

### ISSUE THREAD

**Issue by nfirbas** [microsoft/AirSim#2562]
When i call function `getDistanceSensorData(distance_sensor_name="Distance", vehicle_name="PhysXCar")` i get error 

`msgpackrpc.error.RPCError: rpclib: function 'getDistanceSensorData' (called with 2 arg(s)) threw an exception. The exception contained this information: No distance sensor with name Distance exist on vehicle.`

my settings.json:
`{
  "SimMode" : "Car", 
  "SettingsVersion" : 1.2, 
  "SeeDocsAt" : "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "Vehicles": {
     "PhysXCar": {
         "VehicleType": "PhysXCar",
         "AutoCreate": true,
         "Sensors": {
             "Barometer": {
                 "SensorType": 1,
                 "Enabled" : true
                },
            "Imu": {
                 "SensorType": 2,
                 "Enabled" : true
                },
            "Gps": {
                 "SensorType": 3,
                 "Enabled" : true
                },
            "Magnetometer": {
                 "SensorType": 4,
                 "Enabled" : true
                },
            "Distance": {
                 "SensorType": 5,
                 "Enabled" : true
                }
            }
         }
     }
 }

**Comment by EdwinMeriaux** [comment]
Hey did you ever solve this?
