### ISSUE TITLE
Missing Documentation Issue

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#2568]
Hi,

So a week ago I found the documentation for ROS with Airsim:https://github.com/microsoft/AirSim/blob/master/docs/ros.md

But since then it was removed. (if you try to go to link now you just get the 404 error)

Was it accidentally deleted and if no where would the documentation now be found?

**Comment by rajat2004** [comment]
I believe the specific page was incomplete and had misleading/not-working details
Current details can be found at [airsim_ros_pkgs.md](https://github.com/microsoft/AirSim/blob/master/docs/airsim_ros_pkgs.md) && [airsim_tutorial_pkgs.md](https://github.com/microsoft/AirSim/blob/master/docs/airsim_tutorial_pkgs.md)

**Comment by EdwinMeriaux** [comment]
Thank you!
