### ISSUE TITLE
Connect AirSim with Taranis QX7

### ISSUE THREAD

**Issue by randjamarko** [microsoft/AirSim#2576]
Hi.

I'm trying to connect my Taranis QX7 transmitter with AirSim in Unity (we must use it and are not allowed to use any other software like Unreal engine etc). The problem is, it can't restore the given binary file and even if I try to connect it via HID mode and install it manually, the drone does not move. I know it's not the transmitter, bcs it uses the same software as Taranis X9D (OpenTX). 
Can anyone help me please?

Tnx,
MRR

**Comment by rajat2004** [comment]
AFAIK, RC support is only there in Unreal and not Unity

**Comment by randjamarko** [comment]
Ok, so, I've switched to Unreal Engine. But the problem is still there.
Can anyone help please?
