### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by blacknaki** [microsoft/AirSim#2577]
![image](https://user-images.githubusercontent.com/52971334/79250879-0ef7e300-7e88-11ea-9647-e3644a0bbb90.png) 

I get these errors when building in AirSim on windows 10 and visual studio 2019.

**Comment by rajat2004** [comment]
Eigen is missing, maybe th download failed. Re-Run `clean.cmd` & `build.cmd`

**Comment by blacknaki** [comment]
I did clean.cmd and build.cmd after but I have the same errors

**Comment by rajat2004** [comment]
Try deleting the `eigen3` folder in `AirLib/deps`, Eigen should be donwloaded again then
