### ISSUE TITLE
Error when launching the project. 

### ISSUE THREAD

**Issue by doriand1122** [Microsoft/AirSim#258]
Hello,
I'm following this video tutorial about AirSim: https://www.youtube.com/watch?v=1oY8Qu5maQQ
Hovewer I get an error when launching the project: The following modules are missing or built with a different engine version: UE4Editor-AirSim.dll. Would you like to rebuild them now?
If I choose Yes, there's another error: MyProject could not be compiled. Try rebuilding from source manually.
If I choose No, nothing happens.
Can anyone help me and point what can be wrong and how to solve this issue? My Unreal version is 4.15.2. I'm using AirSim from repo: https://github.com/Microsoft/AirSim
Thanks.

**Comment by lukaszdworako** [comment]
Can you tell me what files are present in the Plugins/Airsim folder that you put in the project file?

**Comment by ethanyqc** [comment]
I encounter the same problem, the files are Content, Dependencies, Source and AirSim.uplugin

**Comment by doriand1122** [comment]
I present screens.
![1](https://user-images.githubusercontent.com/28903903/26843413-6e6ef0a4-4af0-11e7-9309-63fe656081aa.PNG)
![2](https://user-images.githubusercontent.com/28903903/26843414-6e71b136-4af0-11e7-915e-a12a631d31d3.PNG)
![3](https://user-images.githubusercontent.com/28903903/26843415-6e8703ce-4af0-11e7-87d9-6a58694f94fa.PNG)
![4](https://user-images.githubusercontent.com/28903903/26843416-6e8fe304-4af0-11e7-9849-4bca871929e3.PNG)

**Comment by wang19940601** [comment]
I encounter the same problem！

**Comment by lukaszdworako** [comment]
I see we are getting the same issue for different reasons then, I receive this issue since the build was incomplete/ not all files were present.

**Comment by Mayankm96** [comment]
My project is building when I launch it through the UE4Editor. However, when I run the simulation, the application is crashing.

**Comment by Mayankm96** [comment]
I tried doing everything from the start, but now I get a new error on starting the project:

![issue](https://user-images.githubusercontent.com/12863862/26890794-b19669da-4b67-11e7-9eb9-41361f65a6b0.PNG)

**Comment by lukaszdworako** [comment]
This is odd, just pulled latest build and tried again and it worked. Can't give any advice since this seems to have just been some sort of anomaly.

**Comment by lovettchris** [comment]
perhaps it was GitHub, they were down yesterday... which was rather shocking.

**Comment by Mayankm96** [comment]
I am still receiving the second error I shared regarding the COOKED and UNCOOKED version. The following is what I did:
1. Delete the existing repository
2. Clones the git repo again
3. Build the AirSim plugin using VS Commmand Prompt (Build successful)
4. Copied the folder to my project
5. Open the project `.sln` file on VS2015 and ran it. 
 
These steps always worked before. I am not sure where I am going wrong now.

**Comment by Mayankm96** [comment]
Oh well I suppose the correct steps to build the plugin is:
1. Clone the git repo
2. Run `clean.cmd`
3. Run the two scripts in `Unreal/Environment/Blocks` i.e. `clean_build.cmd` and `update_from_build.cmd`
4. Run the `build.cmd`
5. Copy the plugin folder to your project

The above worked for me at least. I hope this is the suggested way as well. @lovettchris

**Comment by wang19940601** [comment]
Hello, somebody can send me a copy of the Plugins/Airsim. my email address is wangshubo@cau.edu.cn, thank you very much

**Comment by lovettchris** [comment]
after running build.cmd, ~\unreal\plugins\airsim will be populated.

**Comment by QiuMingZS** [comment]
I also met this problem using Unreal Engine 4.24.0, so I changed it to 4.18.1, the problem was then solved.
