### ISSUE TITLE
How to capture external camera (i.e. what you are looking at on the screen)

### ISSUE THREAD

**Issue by weavermech** [microsoft/AirSim#2580]
I'm running Airsim on Windows and when I start to record, I'd like to capture the external camera, what is seen in the viewport, specifically the view when I've pressed F2.

 I've tried setting up a camera with an image type of -1 to record from but that crashes, is there any other way?

Many thanks!

 W

p.s. I'm using Landscape Mountains and referring to the view in the editor

**Comment by lovettchris** [comment]
See [PixelStreaming demo](https://github.com/microsoft/AirSim/wiki/Capturing-video-using-Unreal-PixelStreamer).
