### ISSUE TITLE
mavros_msgs issue

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#2586]
hello,

So in the set up for airsim with ros (https://github.com/microsoft/AirSim/blob/master/docs/airsim_ros_pkgs.md)

I am using ubuntu 18.04

on the step where you do 

catkin_make

I get this:

Base path: /home/edwin-pcp/AirSim/ros
Source space: /home/edwin-pcp/AirSim/ros/src
Build space: /home/edwin-pcp/AirSim/ros/build
Devel space: /home/edwin-pcp/AirSim/ros/devel
Install space: /home/edwin-pcp/AirSim/ros/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/edwin-pcp/AirSim/ros/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/melodic
-- This workspace overlays: /opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/edwin-pcp/AirSim/ros/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - airsim_ros_pkgs
-- ~~  - airsim_tutorial_pkgs
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'airsim_ros_pkgs'
-- ==> add_subdirectory(airsim_ros_pkgs)
-- Running CommonSetup...
-- found AIRSIM_ROOT=/home/edwin-pcp/AirSim/ros/src/airsim_ros_pkgs/../../../../AirSim/
-- Running CommonSetup...
-- found AIRSIM_ROOT=/home/edwin-pcp/AirSim/ros/src/airsim_ros_pkgs/../../../../AirSim/
-- Running CommonSetup...
-- found AIRSIM_ROOT=/home/edwin-pcp/AirSim/ros/src/airsim_ros_pkgs/../../../../AirSim/
-- Running CommonSetup...
-- found AIRSIM_ROOT=/home/edwin-pcp/AirSim/ros/src/airsim_ros_pkgs/../../../../AirSim/
-- found RPC_LIB_INCLUDES= /home/edwin-pcp/AirSim/ros/src/airsim_ros_pkgs/../../../../AirSim//external/rpclib/rpclib-2.2.1/include
-- Boost version: 1.65.1
-- Could NOT find mavros_msgs (missing: mavros_msgs_DIR)
-- Could not find the required component 'mavros_msgs'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "mavros_msgs" with
  any of the following names:

    mavros_msgsConfig.cmake
    mavros_msgs-config.cmake

  Add the installation prefix of "mavros_msgs" to CMAKE_PREFIX_PATH or set
  "mavros_msgs_DIR" to a directory containing one of the above files.  If
  "mavros_msgs" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  airsim_ros_pkgs/CMakeLists.txt:26 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/edwin-pcp/AirSim/ros/build/CMakeFiles/CMakeOutput.log".
See also "/home/edwin-pcp/AirSim/ros/build/CMakeFiles/CMakeError.log".

Was mavros pkgs already supposed to be here? Is there an issue with the set up process or did I mess up something? I apologize I just goofed something in the previous steps up but I repeated the steps 3 times and keep getting this.

**Comment by madratman** [comment]
`sudo apt-get install ros-melodic-mavros*`
