### ISSUE TITLE
Not able to package Airsim with custom environment

### ISSUE THREAD

**Issue by plushpluto** [microsoft/AirSim#2593]
Trying to package Airsim (for HTML5) with UE4-4.23 in windows. Getting a lot of exception handling errors. 

error: cannot use 'throw' with exceptions disabled

Please help.

**Comment by rajat2004** [comment]
You could try settings `bForceEnableExceptions = true` in [AirSim.Build.cs](https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/AirSim.Build.cs)
Though it already has [`bEnableExceptions = true`](https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/AirSim.Build.cs#L79), maybe they are different? Or the latter one was changed to the first one?

**Comment by plushpluto** [comment]
It says
The name 'bForceEnableExceptions' does not exist in the current context

bEnableExceptions = true is already present.

**Comment by abhishekvermaairbus** [comment]
Any solution to this?
