### ISSUE TITLE
Ue4 GetActorPosition() is not the position in moveToPositionAsync().

### ISSUE THREAD

**Issue by obitodaitu** [microsoft/AirSim#2597]
Ue4 GetActorPosition() is not the position in moveToPositionAsync().How to convert it to Airsim's Position.

**Comment by rajat2004** [comment]
Have you tried https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#coordinate-system?

**Comment by obitodaitu** [comment]
@rajat2004  thanks,i solve this problem

**Comment by rajat2004** [comment]
Great! If the problem has been fixed, could you close the issue?

**Comment by obitodaitu** [comment]
ii

**Comment by obitodaitu** [comment]
ok
