### ISSUE TITLE
no ‘object' file generated

### ISSUE THREAD

**Issue by LeadgerLee** [Microsoft/AirSim#26]
Hello, everyone. When I build the AirSim project, it displayed some errors while compiling. As follow, 
----------------------------------------------------------------------------------------------------------------
  d:\code\eigen3\eigen\src/Core/arch/CUDA/Half.h : error C2220: warning treated as error - no 'object' file generated
[D:\GitHub\repo\AirSim\AirLib\AirLib.vcxproj]
  d:\code\eigen3\eigen\src/Core/arch/CUDA/Half.h : error C2220: warning treated as error - no 'object' file generated
... etc...
-----------------------------------------------------------------------------------------------------------------

Should I change the option "Treat warning as error" from "Yes(/WX)" to "No(/WX-)" in the property page of project?
Thank you very much.

**Comment by sytelus** [comment]
Which OS are you using? Are you compiling using build command? Also please post more error details.

**Comment by jy723** [comment]
I've got the same problem.My raphics card is NVDIA GeForce GTX745.

**Comment by fmzhu** [comment]
I've got the same problem. My OS ist Windows10 and the Visual Studio is 2015. I compile use build command.

**Comment by jy723** [comment]
error message: half.h : warning C4819: error936
The file eigen3\Eigen\src\Core\arch\CUDA\half.h is saves as Unicode－1200,the warnings disapperance;

**Comment by fmzhu** [comment]
@jy723 thank you very much. The problem is fixed.

**Comment by LeadgerLee** [comment]
@jy723 Thank you very much. The problem is fixed.

**Comment by spencerh-b** [comment]
@LeadgerLee can you explain what exactly you did to fix this?

**Comment by Jackyjae** [comment]
@jy723 I met the same problem today. How can I fix it?

**Comment by bys1123** [comment]
How is this happen? Everyone have this issue? Is this file can be fixed? @jy723

**Comment by kingium** [comment]
I get nine C2220 errors with `/deps/eigen3/eigen/src/core/arch/cuda/half.h`, each at:
-  `RpcLibClientBase.cpp`
-  `RpcLibServerBase.cpp`
-  `MultirotorApiBase.cpp`
-  `ObstacleMap.cpp`
-  `SafetyEval.cpp`
-  `CarRpcLibClient.cpp`
-  `CarRpcLibServer.cpp`
-  `MultirotorRpcLibClient.cpp`
-  `MultirotorRpcLibServer.cpp`
