### ISSUE TITLE
Can't find API Documentation

### ISSUE THREAD

**Issue by xtream111** [microsoft/AirSim#2603]
Hi everyone, I am quite new to Airsim and programming in general. I am doing a school project using Airsim and Python to simulate a drone and controlling it automatically.

However, I can't find any detailed list of all the Python commands to control the drone. Is there something available?

Thanks in advance

**Comment by rajat2004** [comment]
https://microsoft.github.io/AirSim/apis/ and other API pages should be helpful, along with the example scripts in the PythonClient folder
These might not be upto date with the latest APIs, there is a PR https://github.com/microsoft/AirSim/pull/2565 open right now to generate HTML page with all the APIs, but till then, the [client.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py) file contains all the APIs available
