### ISSUE TITLE
Meet issue in Spyder but ok in IDLE

### ISSUE THREAD

**Issue by alexzc231** [microsoft/AirSim#2605]
When I'm using Python api, I meet a issue.
When my script  finished its running, and return the python-console to a input line status,  I could not enter anything in this console.
![图片1](https://user-images.githubusercontent.com/28727119/79733345-836ad000-8327-11ea-9270-4e491556e80f.png)
![图片2](https://user-images.githubusercontent.com/28727119/79733348-8796ed80-8327-11ea-9ff3-789bdcdff957.png)
The 1st picture shows the status when my script finished his running.
The 2nd picture shows that, I can type something into the console input line, but the ENTER key is invalid. Nothing happened when pressed enter.

When I change Spyder to IDLE.exe , the basic python environment, everything is OK.

**Comment by jonyMarino** [comment]
Does not seem like an AirSim issue.
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
