### ISSUE TITLE
Memory overflow in Unreal Editor when running blocks environment - Lidar shouldn't render all points by default

### ISSUE THREAD

**Issue by nightduck** [microsoft/AirSim#2608]
This bug is caused by running code entirely in Airsim's repo. I started the sample blocks environment and executed all [the steps to run the tutorial ros packages](https://github.com/microsoft/AirSim/blob/master/docs/airsim_tutorial_pkgs.md)

The end result is that UnrealEditor begins gobbling up ram, until I kill it or it crashes (sometimes taking my machine down with it, if it resorts to swap space).

Poking around suggests this is a graphics issue. I'm using a GTX 1080 running Nvidia's proprietary 435 drivers on a fresh-ish install of Ubuntu 18.04. ("fresh-ish" = /home directory is recycled from an old build)

**Comment by rajat2004** [comment]
Hmm, sounds strange, does this happen without running the ROS package, ie. just the Editor? Also, which version of UE are you using, 4.24?
You could also try using OpenGL instead of the Vulkan drivers which UE now uses by default. Vulkan does take up more memory right now, but hopefully, some of the memory issues might be fixed in UE 4.25
For using OpenGL, just use the `-opengl4` option while launching Editor from the terminal

**Comment by nightduck** [comment]
If I run the blocks simulation totally as is, it'll run fine. When I copy over the `front_stereo_and_center_mono.json` into `Documents/Airsim/settings.json` and the lidar dots show up, that's when the problem appears. At first, it appeared to be a low frame-rate issue, but the fix discussed in issue #1185 did nothing.

Yes, UE 4.24

I wasn't aware openGL was an option. Before I had vulkan installed, UE complained it couldn't use openGL, but I'll try that flag.

**Comment by rajat2004** [comment]
Yes, sorry forgot to mention, follow the first comment in https://www.reddit.com/r/unrealengine/comments/e4i7ny/cannot_start_unreal_engine_4_in_linux/

**Comment by nightduck** [comment]
Unclear on how to delete cameras

**Comment by rajat2004** [comment]
Just remove from the settings if not required

**Comment by nightduck** [comment]
The fix was to go into settings.json and set `DrawDebugPoints` to false. The debug points cumulatively add up and bog down Unreal Engine.

Consider this issue now a feature request: Lidar, by default, doesn't not render all points ever captured, only recent ones, say from the last frame.

**Comment by rajat2004** [comment]
This problem didn't occur with me when I was using Lidar. But it could be the case that I just didn't leave it on that much
Now that I think about it, I haven't actually used it on UE 4.24, so it might be different. How much time did it take to hog up the memory and crash the system?

**Comment by nightduck** [comment]
It would take about 5-10 seconds for the framerate to drop to rock bottom. The render time for each frame increases linearly, so the fps has a 1/x relationship. Once it gets down to 2-3fps, it gobbles up a gig of ram every 3-4 seconds or so. If your system doesn't have swap space, only UE will crash, not the OS. Either way, it's directly related to memory usage.

And [both](https://github.com/microsoft/AirSim/blob/266cd4333a8a1aa3abc5f189917c53808392b123/ros/src/airsim_tutorial_pkgs/settings/front_stereo_and_center_mono.json#L31) the [settings](https://github.com/microsoft/AirSim/blob/266cd4333a8a1aa3abc5f189917c53808392b123/ros/src/airsim_tutorial_pkgs/settings/two_drones_camera_lidar_imu.json#L25) files that specify DrawDebugPoints default it to true.

Which version of UE are you using? I can build that and test it on my system. I know that [UE switched to Vulkan in 4.21](https://www.phoronix.com/scan.php?page=news_item&px=Unreal-Engine-4.21-Debuts). Anything earlier would use OpenGL, which doesn't have the memory bug, only low frame rates.

**Comment by rajat2004** [comment]
#2614 has been merged, so I think this issue can be closed

**Comment by nightduck** [comment]
Agreed
