### ISSUE TITLE
Quadcopter collision detection issue in Unity build (Flies through the ground)

### ISSUE THREAD

**Issue by n8powe** [microsoft/AirSim#2615]
Has any fixed the quadcopter collision detection issue when using the Unity build? I have everything in the Windridge city and AirSim assets built on Windows 10, using the most recent Airsim Unity version, and Unity version 2018.16f. But when I fly the quadcopter it goes through all the objects without detecting collisions. I know this has been brought up before, but I haven't seen a solution. 

My best guess is that the rigid body isn't working as expected, since as I change the values for it in the inspector it doesn't influence the quad at all. (I am a novice at C#, so sorry if there should be an easy or obvious solution).

If anyone has fixed this or has any ideas it would be much appreciated. The code is not throwing any errors, so I don't have to report here.

**Comment by jonyMarino** [comment]
treated in #2349
