### ISSUE TITLE
Confusion in the workflow

### ISSUE THREAD

**Issue by plushpluto** [microsoft/AirSim#2627]
Sorry guys, had to post it here since I am really confused on the basics. Few questions!!!

1. I am trying to test the workflow of the SITLs available mainly using MAVSDK/Dronekit/MAVROS and understand the robustness of them. Dronekit --> PX4/ArduPilot --> Airsim API --> UnrealEngine. 
Is my understanding of the workflow correct? Is there any way to temporarily bypass Airsim?

2. Can I disable any sensor using the Airsim client during the flight? If not, is there any way to do it other than the settings.json file?

**Comment by rajat2004** [comment]
The workflow of SITL seems correct. Not sure as to what you mean by bypassing Airsim, any UE specific tasks such as adding new actors, or changing the environment can be done as usual in UE

AFAIK, there's no way to disable sensors at runtime, maybe you could add an API for such a task, though will need to look into how it can be done

**Comment by plushpluto** [comment]
Got it. Workflow seems clear to me now. Thanks.
I am working on a webgl based project for Airsim. I need to figure out a way to use Airsim as a separate service not an integrated one with the UE. Let UE be based out on MAVLink. It would be better if the workflow is Airsim --> MAVLink --> UE. Just a thought. I don't know. I may be wrong.

Ah! man. Sad to know that there is no way to disable the sensors!
