### ISSUE TITLE
Serial port opened with 1.5 stop bits in Windows

### ISSUE THREAD

**Issue by gamoreno** [Microsoft/AirSim#263]
The serial port to communicate with the FCU (e.g., Pixhawk) is opened with 1.5 stop bits instead of 1.

The attribute for stop bits is initialized as:
StopBits sb = StopBits::StopBits_10;
(see https://github.com/Microsoft/AirSim/blob/master/MavLinkCom/src/serial_com/SerialPort.cpp#L41)

This constant is defined as StopBits_10 = (0x0001) in https://github.com/Microsoft/AirSim/blob/master/MavLinkCom/src/serial_com/SerialPort.hpp#L20

However, in Windows, the constant for 1 stop bit, ONESTOPBIT, is defined as 0 (whereas the value 1 is assigned to ONE5STOPBITS) (see https://msdn.microsoft.com/en-us/library/windows/desktop/aa363214(v=vs.85).aspx )

When used with a Pixhawk, this wrong configuration does not affect the communication. However, when running PX4 on a Raspberry Pi with a navio2 board, the serial communication does not work unless it's configured properly.

**Comment by lovettchris** [comment]
Thanks for the bug report.  You are looking at #ifdef WIN32 implementation of SerialPort.  The #else Linux code in SerialPort.cpp probably makes more sense on Raspberry Pi unless you are using the windows IOT build for Raspberry Pi...

I submitted [this fix](https://github.com/Microsoft/AirSim/commit/ce8e49320b8f3cea85b5cc702afcce0a073da8fe).
