### ISSUE TITLE
Running simulations with a time multiplier

### ISSUE THREAD

**Issue by vguillet** [microsoft/AirSim#2630]
OS: Windows
Python: 3.7

I am planning on using AirSim for reinforcement learning as part of a university project. Through reading the documentation, I saw that it was possible to run simulations without rendering, which provides a significant boost in performance, but I was wondering if it was possible to also run sped up simulations (at x2 speeds for example and preferably more). This would allow for much more iterations to be performed in much less time, and as a result significantly speed up training.

Is this already a feature and I missed the documentation? And if not is there plans for it?

Cheers!

**Comment by rajat2004** [comment]
`ClockSpeed` might be what you're looking for - https://github.com/microsoft/AirSim/blob/master/docs/settings.md#clockspeed

**Comment by vguillet** [comment]
Yep, thats exactly what I was looking for, thank you!
