### ISSUE TITLE
Car in UnityDemo Project does not move using PythonClient scripts

### ISSUE THREAD

**Issue by sebastian-ruiz** [microsoft/AirSim#2631]
I am running PR #2328 to avoid the Unity CarDemo project from crashing on startup.

On Windows10 , running Unity 2019.2.17f1.
I am running the `UnityDemo` project.
I get 100s of logs in the unity console log:

```
Control Mode:  Keyboard Vehicle=PhysXCar
UnityEngine.Debug:Log(Object)
```
None of the python scripts in the `PythonClient/car` folder make the car in the Unity demo project move. I can however move the car using the WASD keys and the arrow keys.

When running a Python script, I get the following messages in Unity repeatedly:

```
Control Mode:  Keyboard Vehicle=PhysXCar
Control Mode:  API Vehicle=PhysXCar
Control Mode:  Keyboard Vehicle=PhysXCar
Control Mode:  API Vehicle=PhysXCar
...
```

When I try and run hello_car.py and running the Unity demo, the python script reports 'connected', however the car doesn't move. The same happens with the `drive_straight.py` script.

**Comment by higho51420** [comment]
i meet the same problem. do you solve it ?

**Comment by ruzicam** [comment]
Did someone solved it?

**Comment by higho51420** [comment]
I didn't solve it. I don't use latest version, i use airsim 1.2.1,unity 2018.2.14.  no problem.  I have no idea to solve it.

**Comment by weigangwen** [comment]
> I didn't solve it. I don't use latest version, i use airsim 1.2.1,unity 2018.2.14. no problem. I have no idea to solve it.

What version of vs do you use，please

**Comment by HackBrettHB** [comment]
Any update?
