### ISSUE TITLE
Visual_Studio issue.

### ISSUE THREAD

**Issue by johan606303** [microsoft/AirSim#2633]
Hi.

Before al was more or less ok. I worked on my project with Spyder to code on Python (Conda environment).
Then I tried to work with Jupyter Notebook. Then I got the following issue.

![vs_issue](https://user-images.githubusercontent.com/62846458/80538824-a7bd5100-89a6-11ea-899a-fc2f9f0ac62b.PNG)

Now it's the case with VS2019. I uninstalled and re-installed, but issues remain.

Thanks for help.

**Comment by rajat2004** [comment]
This is a known issue with Jupyter and `msgpack-rpc-python` having conflicting Tornado version dependency. Best way would be to create a virtual env with just the libraries needed

**Comment by johan606303** [comment]
Thank you, it works well now.

**Comment by rajat2004** [comment]
Please do close the issue if the problem has been solved

**Comment by lovettchris** [comment]
perhaps we should put this in an FAQ somewhere.

**Comment by rajat2004** [comment]
@lovettchris This info is there in the docs - https://microsoft.github.io/AirSim/apis/#typeerror-unsupported-operand-types-for-asyncioloop-and-float
Though the placement can be improved
