### ISSUE TITLE
ROS topic rates are very very low

### ISSUE THREAD

**Issue by BritskNguyen** [microsoft/AirSim#2638]
Hi all,

I am trying to run the first [AirSim tutorial](https://microsoft.github.io/AirSim/airsim_tutorial_pkgs/#single-drone-with-monocular-and-depth-cameras-and-lidar) and is encountering very low topic rates.

My setup is as follows:
+Ubuntu 18.04
+Intel® Core™ i7-9750H CPU @ 2.60GHz × 12 
+GeForce RTX 2080 with Max-Q Design/PCIe/SSE2
+nvidia-driver-440
+Linux 5.3.0-51-generic
+ROS melodic

So after starting the _Blocks_ binary I launched the ros node and found that all topics have very low rates for all of the topics. Below is a screenshot of the terminal when I run `rostopic hz /airsim_node/drone_1/lidar/LidarCustom`:

![Screenshot from 2020-04-30 10-26-31](https://user-images.githubusercontent.com/13504903/80667242-31693d80-8ad1-11ea-866a-53e994bf0bd9.png)

The CPU usage is pretty normal, please see below:
![image](https://user-images.githubusercontent.com/13504903/80667581-295dcd80-8ad2-11ea-8202-dee1328a1a37.png)

I wonder where the issue is? Could it be because of the setup? Should I downgrade to Ubuntu 16.04 or use docker?

Thanks in advance!

**Comment by rajat2004** [comment]
There's currently a bug in the release in Lidar where `DrawDebugPoints` if True will drop the FPS like anything. A fix (https://github.com/microsoft/AirSim/pull/2614) has been merged in master
Try setting DrawDebugPoints to False in the settings and see if it improves

**Comment by BritskNguyen** [comment]
Thanks after setting the parameter to false I can get 5Hz of img, 25Hz of lidar and 30Hz of IMU. I think the issue can be closed. Will check (#2369) for customizing the rate.
