### ISSUE TITLE
Unstable Behavior on Podium after simResetRace

### ISSUE THREAD

**Issue by AlessandroSaviolo** [microsoft/AirSim#2639]
Hello,

I want to run multiple Airsim races **sequentially**. After the drone reaches a certain gate, I reset the race and start a new one. But, after restarting the race, the drone has a very unstable behavior on the podium. Is there a way to stabilize it? 

To start the race I use:

1. simSetVehiclePose (to make sure that the drone is exactly in the correct starting position in every race)
2. enableApiControl
3. arm
4. simStartRace

To stop/reset the race I use:

1. disarm
2. disableApiControl
3. _wait 2 seconds_
4. simResetRace

I have tried to search in the issues about a similar problem but I could not find anything about this.

I have upload a short demonstration of such behavior:
https://drive.google.com/open?id=1vZLWgBUMCc99zVI3QoveJ8dEH4EjNtUx

Thanks in advance!!

**Comment by rajat2004** [comment]
This seems to be in connection with https://github.com/microsoft/AirSim-NeurIPS2019-Drone-Racing, and the issue should be opened on that repo
