### ISSUE TITLE
DroneShell/GUI

### ISSUE THREAD

**Issue by eanmikale** [Microsoft/AirSim#264]
Chris, 
Is it possible to integrate a GUI with the DroneShell CLI? And any insight into creating new commands in DroneShell? Also, HelloDrone continues to crash. Any assistance is appreciated. 

Regards, 

EM

**Comment by lovettchris** [comment]
See [DroneShell/src/main.cpp](https://github.com/Microsoft/AirSim/blob/master/DroneShell/src/main.cpp).  You can add whatever new commands you want and GUI too.  It is just C++ code... so not sure what kind of assistance you are asking for.

**Comment by eanmikale** [comment]
Chris, 
That's all the information I needed. Thanks again!
