### ISSUE TITLE
Cannot find airsim module (AirSim)

### ISSUE THREAD

**Issue by AngelTang190** [microsoft/AirSim#2640]
I tried to make the quadcopter in AirSim fly. I used Anaconda Prompt (anaconda3) and I had my unreal engine opened with the quadcopter simualtion running. I went to the directory AirSim\PythonClient\multirotor and ran python hello_drone.py and it gave me this error:

(base) C:\code\AirSim\PythonClient\multirotor>python hello_drone.py
Traceback (most recent call last):
  File "hello_drone.py", line 2, in <module>
    import airsim
ModuleNotFoundError: No module named 'airsim'

Can someone please help? Thanks!

**Comment by rajat2004** [comment]
Did you run `pip install airsim`?

**Comment by AngelTang190** [comment]
> Did you run `pip install airsim`?
I've previously build airsim using developer command prompt for VS 2019. Should run pip install airsim again?

**Comment by rajat2004** [comment]
That builds the AirSim module, you need to install the `airsim` python package to use the Apis

**Comment by AngelTang190** [comment]
After I run pip install airsim and run python hello_drone.py again, nothing happens and the Anaconda is not responding as well.

**Comment by rajat2004** [comment]
Simulation might not be running
Else if there are any errors or crashes, please post the entire steps to reproduce the issue

**Comment by AngelTang190** [comment]
First, I started unreal engine and opened my project, Then, I hit play and chose quadcopter as my vehicle. Then, I opened Anaconda prompt and I typed in 

cd\code\AirSim\PythonClient\multirotor\

After that, I typed in 

python hello_drone.py

These are all the steps.

There are no errors shown on Anaconda prompt.

**Comment by AngelTang190** [comment]
![image](https://user-images.githubusercontent.com/54227914/80702298-6e562400-8b13-11ea-9a96-34bb04c9b1ea.png)

**Comment by AngelTang190** [comment]
![image](https://user-images.githubusercontent.com/54227914/80702368-89c12f00-8b13-11ea-922b-a7d53cf88933.png)

**Comment by rajat2004** [comment]
Seems pretty strange, I can't reproduce though I am on Linux. And there would be a lot more issues if something like this is happening
Try running the Blocks env and see if it's occurring in that as well

**Comment by AngelTang190** [comment]
Do you mean Blocks.uproject?
