### ISSUE TITLE
Importing an OpenDRIVE (.xodr) file

### ISSUE THREAD

**Issue by Mechatrnk** [microsoft/AirSim#2641]
Hello, I am considering starting working with AirSim but I need to know before I start whether it is possible to import OpenDRIVE (.xodr) files into the AirSim.

Because I have an OpenDRIVE file and I need to visualize it, unfortunately, if AirSim does not support this then I cannot use AirSim.

Thank you very much for any response

**Comment by rajat2004** [comment]
AirSim is just a plugin, which can work on various environments in Unreal Engine & Unity
If you're able to import your files into either of these, then it's likely that you can use AirSim with them
