### ISSUE TITLE
How to update custom Unity environment to latest version of AirSim?

### ISSUE THREAD

**Issue by mateusk** [microsoft/AirSim#2643]
Hi,

First of all, thanks for maintaining this great open source project!

I have a custom Unity environment and I wonder what would be the recommended steps to update AirSim to the latest version. I tried simply to replace the "AirsimWrapper.dll" but I ran into similar issues as in [#2629](https://github.com/microsoft/AirSim/issues/2629). 

I'm on Windows 10 1909, using Unity 2019.3.12f1.

Thanks!

**Comment by rajat2004** [comment]
Updating your local repo with the PR fixes as mentioned in the issue, rebuilding and then following the steps for custom Unity env should work

**Comment by mateusk** [comment]
Ok, thanks, I believe that worked. Is it absolutely needed to copy `/ProjectSettings` as well?

**Comment by jonyMarino** [comment]
@mateusk did you try not copying them? I would like to close this issue
