### ISSUE TITLE
Is it possible to use Car and Multirotor at the same time?

### ISSUE THREAD

**Issue by kminoda** [microsoft/AirSim#2655]
Is it possible to use Car and Multirotor at the same time?

Now I am using AirSim on Ubuntu 18.04 with UE4.24.

What I want to do is to move car and UAV at the same time. 
It seems that in settings.json (document [here](https://github.com/microsoft/AirSim/blob/master/docs/settings.md)), you can select "SimMode" as "Car", "Multirotor", "ComputerVision" or "", but I couldn't figure out how to use them at the same time.

If possible, how can I do that?

Thank you in advance.

**Comment by rajat2004** [comment]
Currently, it hasn't been implemented, but you can have a look at other issues in the repo for info about this
