### ISSUE TITLE
how can i use accelerator mode when i use learning ?

### ISSUE THREAD

**Issue by kimwin2** [microsoft/AirSim#2656]
I'm just trying to find self-driving car simulator which is similar as AirSim.
Can i use boost mode or parallel learning process while using AirSim?
I have a plan to use Reinforcement learning so that it will take thousands of times.

Thanks for your reply.

**Comment by rajat2004** [comment]
I think you mean faster simulation time than real world, see https://github.com/microsoft/AirSim/blob/master/docs/settings.md#clockspeed
