### ISSUE TITLE
What will be the best version of unreal engine to use with AirSim plugin? What is the process to install Unreal engine with AirSim plugin?

### ISSUE THREAD

**Issue by ashish210111** [microsoft/AirSim#2657]
# Read This First

## If you are reporting a bug
* Make sure to write **all reproduction steps**
* Include full error message in text form
* Search issues for error message before filing issue
* Attach screenshot if applicable
* Include code to run if applicable

## If you have question
* Add clear and concise title
* Add OS, AirSim version, Python version, Unreal version if applicable
* Include context on what you are trying to achieve
* Include details of what you already did to find answers

**What's better than filing issue? Filing a pull request :).**

------------------------------------ (Remove above before filing the issue) ------------------------------------

**Comment by rajat2004** [comment]
Please don't put the entire question in the title, and remove the issue template lines before opening issue
As to your question, read the documentation - https://microsoft.github.io/AirSim/#how-to-get-it
Open issues for specific bugs, problems or questions after going through the docs
