### ISSUE TITLE
Coverage Algorithm for Drone over the map

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#266]
I am trying to write a script using the python APIs to have the drone just hover and move over the entire map region similar to a coverage algorithm like the lawn mower motion pattern. I wish to be able to change the altitude to collect data from different heights and create the dataset. 

I am having trouble in defining waypoints for it to move along in the map as the scale of the map seems rahter unclear. Does any one has any idea on how to do this?

**Comment by lovettchris** [comment]
one way to get the scale would be to fly manually with remote control to the corners of the map then use the "getPosition" function to find out where that is in local coordinates, or use DroneShell "pos" command.

**Comment by Mayankm96** [comment]
Yeah that seems to have worked for me. Thanks @lovettchris!

In case there are people who wish to implement the same thing, the code can be found [here](https://github.com/Mayankm96/ais-work/blob/master/airsim-python/ais-sim.py).

**Comment by Ramshandilya** [comment]
Hey @Mayankm96, I'm looking implement a similar feature where the drone moves like a lawn mower on top of the region selected. Can you share the algorithm if possible?

**Comment by Mayankm96** [comment]
Hi @Ramshandilya! I had written the script but since I am flying the drone in `computer_vision` mode now instead of`simple_flight` mode, I haven't really updated it to the latest python APIs. You could find the file [here](https://gist.github.com/Mayankm96/a0c304023b2993269b74eeb7f5b39875).

It would be nice if you could make the corrections on it in case any are required. :)
