### ISSUE TITLE
Problem of AirSim Plugin with Landscape Mountains project

### ISSUE THREAD

**Issue by ashish210111** [microsoft/AirSim#2661]
I have installed Unreal Engine 4.24, and have build the AirSim plugins as mentioned here https://microsoft.github.io/AirSim/build_windows/

but when I adding this plugins to the  Landscape Mountains project then I am getting this error
![image](https://user-images.githubusercontent.com/64783760/81060098-68838880-8eef-11ea-96a9-3503de0fce87.png)

 and when I am pressing yes then getting this 
![image](https://user-images.githubusercontent.com/64783760/81060161-85b85700-8eef-11ea-8c10-24f3ed4b2a0d.png)

and after pressing ok nothing is happening.

**Comment by rajat2004** [comment]
Check the logs under Saved/Logs folder, else right click on the uproject file, Genereate Visual Studio files, open .sln file in VS 2019 and build from there to see the error
