### ISSUE TITLE
Problem in running DQNdrone.py

### ISSUE THREAD

**Issue by ashish210111** [microsoft/AirSim#2674]
I am using AirSim and Unreal Engine 4.24 with windows 10 and anaconda. I am able to run the PythonClients folder's  example files. But I am facing some issue in running DQNdrone.py file.
**ModuleNotFoundError: No module named 'cntk'**
![image](https://user-images.githubusercontent.com/64783760/81411666-50667000-9160-11ea-8daa-a0815d3d8165.png)

**Comment by AllenIverSunn** [comment]
Hi, I think you need to install CNTK first. Try to google around for how to install it.
