### ISSUE TITLE
yaw right control trigger RTL(return to launch) 

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [Microsoft/AirSim#268]
I'm using TGFG-tutaba Ratio, all the others control work on the simulator except the yaw right controll, which triggered RTL like this:
![bug](https://user-images.githubusercontent.com/25046619/26967317-5bfec81c-4d30-11e7-9481-363e49dbf5b8.png)

**Comment by lovettchris** [comment]
it is very unlikely that controlling yaw with a stick would trigger RTL.  The RTL setup can be shown in QGroundControl, the reasons for RTL are listed under the Safety tab, these are my settings, notice for simulation I disable RC loss failsafe and data link loss failsafe, but I wouldn't do that on a real drone.

![image](https://user-images.githubusercontent.com/18707114/26969572-11de45d4-4cbb-11e7-9965-002f750091a2.png)

**Comment by TomorrowIsAnOtherDay** [comment]
thanks for your reply.After resetting the flight control and calibrate the ratio and flight mode, It worked.

**Comment by lovettchris** [comment]
congrats and welcome to the club :-)
