### ISSUE TITLE
overriding the default input settings

### ISSUE THREAD

**Issue by avivazran** [microsoft/AirSim#2680]
Is there a possibility to reconfig\add input keys from within Unreal?
or can you direct me to the file containing the keyboard/Xbox controller input settings?

**Comment by rajat2004** [comment]
Details are given in https://github.com/microsoft/AirSim/blob/master/docs/remote_control.md
Settings are defined in [SimJoystick.cpp](https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/SimJoyStick/SimJoyStick.cpp) I think
