### ISSUE TITLE
Error: No module named 'AirSimClient'

### ISSUE THREAD

**Issue by ashish210111** [microsoft/AirSim#2681]
I am using UE 4.24, AirSim with anaconda/spyder. I am able to run sample codes  for drones given in PythonCLient folder. But when i am trying to run some different code then i am having this error

**ModuleNotFoundError: No module named 'AirSimClient'**

runfile('C:/Users/ashish/Desktop/sar-deep/airsimapi.py', wdir='C:/Users/ashish/Desktop/sar-deep')
Traceback (most recent call last):

  File "C:\Users\ashish\Desktop\sar-deep\airsimapi.py", line 8, in <module>
    from AirSimClient import *

ModuleNotFoundError: No module named 'AirSimClient'

**Comment by ndalton12** [comment]
As far as I know, there is no AirSimClient module, but you can use `import airsim`.
