### ISSUE TITLE
Documentation: ArduPilot support

### ISSUE THREAD

**Issue by auturgy** [microsoft/AirSim#2686]
Docs don't mention ArduPilot support.
https://microsoft.github.io/AirSim/search.html?q=ardupilot returns no results.
Linked issue: https://github.com/ArduPilot/ardupilot_wiki/issues/2739

**Comment by rajat2004** [comment]
I've opened a PR which updates the docs - https://github.com/microsoft/AirSim/pull/2658

**Comment by auturgy** [comment]
Cool, thanks Rajat. Would you prefer I close this issue, or wait for it to be closed by your pr?

**Comment by rajat2004** [comment]
I've marked that the PR closes this
