### ISSUE TITLE
rpclib:server could not find function "getSeverVersion"with argument count 0

### ISSUE THREAD

**Issue by JoeAnzio** [microsoft/AirSim#2687]
![image](https://user-images.githubusercontent.com/44342617/81533245-71190a80-9398-11ea-996d-6843fdb541bf.png)

**Comment by madratman** [comment]
Please provide more context. What API raised this error? 
getServerVersion does work in general. Seems like a setup issue on your machine

**Comment by jonyMarino** [comment]
Please reopen if you still have the issue
