### ISSUE TITLE
UE4 Online C/S mode support

### ISSUE THREAD

**Issue by Jianghn-dev** [microsoft/AirSim#2691]
hi，
I wonder if airsim supports the UE4 online mode so far. 
Looking forward to your reply

**Comment by rajat2004** [comment]
No, it doesn't. You'll have to run it locally, either build it from source or download the binaries

**Comment by madratman** [comment]
If you mean this - https://docs.unrealengine.com/en-US/Gameplay/Networking/Server/index.html - by "unreal engine online" mode, then you'll have to build airsim from source. 

As AirSim is a UE4 plugin, any feature supported by UE4 (such as Pixel Streaming, NDisplay) is technically supported by AirSim, but you'd have to follow UE4's documentation for such features.
