### ISSUE TITLE
Does AirSim support Apollo or Autoware?!

### ISSUE THREAD

**Issue by k1majd** [microsoft/AirSim#2693]
I just have a general question. I wonder if AirSim supports integration with Apollo or Autoware!?

**Comment by rajat2004** [comment]
Currently it doesn't have support for them. Any contributions would be very much welcome!

**Comment by k1majd** [comment]
Thanks for your response. So what open-source self-driving repositories do you support?

**Comment by madratman** [comment]
We only provide client level set control and get sensor data APIs in the car mode.

**Comment by bimadrd** [comment]
> We only provide client level set control and get sensor data APIs in the car mode.

how i could to modify level set control client, where is it?
and how i could get sensor data APIs of the car, could you give some step please?
