### ISSUE TITLE
Unable to use SITL with Airsim on Unreal Engine

### ISSUE THREAD

**Issue by clev0910** [microsoft/AirSim#2699]
I have setup AirSim with the landscape mountains environment and have also set up SITL using Cygwin. However, when I attempt to run SITL in order to move the quadcopter around on unreal engine, while I do get MAVlink, the map and the console to open, any commands that I type into the MAVlink have no effect on the quadcopter; it does not arm nor takeoff or do anything after that. I do receive a message as I attempt to start SITL, an image of which I've attached below. I've also attached the settings I've used in the .json settings folder for the Unreal Project. Is there any change that needs to be made to the settings/SITL set up?
[
<img width="960" alt="2020-05-19" src="https://user-images.githubusercontent.com/64508879/82338073-cbb50500-9a2f-11ea-931a-ca7a468a0c43.png">

<img width="960" alt="2020-05-20 (2)" src="https://user-images.githubusercontent.com/64508879/82338269-0880fc00-9a30-11ea-812e-81f85f680113.png">

](url)

**Comment by agentfeux** [comment]
I don't know if its gonna help but i personally do on the console: `sim_vehicle.py -v ArduCopter -f airsim-copter`

Then on another tab: `./Engine/Binaries/Linux/UE4Editor ~/AirSim/Unreal/Environments/Blocks/Blocks.uproject`

I use QgroundControl for the map and stuff.

**Comment by rajat2004** [comment]
Try using WSL instead of Cygwin for running ArduPilot, both WSL 1 & 2 have been tested to be working with AP+Airsim
Cygwin has some strange networking issues, you could try using `0.0.0.0` for IP addresses as instead of `127.0.0.1` as described [here](https://ardupilot.org/dev/docs/sitl-with-airsim.html#run-on-different-machines)

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.

**Comment by AhmedSaleh627** [comment]
Iam facing the same issue
