### ISSUE TITLE
Customize depth image resolution

### ISSUE THREAD

**Issue by ShukuiZhang** [Microsoft/AirSim#270]
Is there a way to customize resolution for recorded depth image, such that it has same resolution as scene images?

**Comment by lovettchris** [comment]
You would have to change the resolution of the DepthRenderTarget asset under AirSim Content/HUDAssets:
![image](https://user-images.githubusercontent.com/18707114/26995783-9e52edd6-4d23-11e7-8093-7ebe6368fa5e.png)

**Comment by ShukuiZhang** [comment]
Got it work. Thanks! @lovettchris
