### ISSUE TITLE
AirSim crashes when running multi_agent_drone.py

### ISSUE THREAD

**Issue by AngelTang190** [microsoft/AirSim#2701]
I opened AirSim and hit the Play button. After that, I used anaconda3 and typed in the following:

(base) C:\Users\ASUS>cd\

(base) C:>cd AirSim\PythonClient\multirotor\

(base) C:\AirSim\PythonClient\multirotor>python multi_agent_drone.py

And I hit enter.

Then anaconda gave me this:
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Press any key to takeoff

I pressed enter. After that Unreal Engine closes abruptly and gave me this summary :

LoginId:5690cc664b1c5fda56b6afa9e10052bb
EpicAccountId:935f49a690214f7e949826002d647237

Unhandled Exception: 0xe06d7363

msvcp140
UE4Editor_AirSim!<lambda_69f58446dda213d70a34b34d463075c6>::operator()() [C:\Users\ASUS\Documents\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\RenderRequest.cpp:72]
UE4Editor_AirSim!TBaseFunctorDelegateInstance<void __cdecl(void),<lambda_69f58446dda213d70a34b34d463075c6> >::ExecuteIfSafe() [C:\Program Files\Epic Games\UE_4.24\Engine\Source\Runtime\Core\Public\Delegates\DelegateInstancesImpl.h:1002]
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

Can I know what is wrong and how to fix this?

**Comment by rajat2004** [comment]
The problem is not reproducible on Linux with master as well as the latest binary, needs investigation on Windows

**Comment by AngelTang190** [comment]
How can I fix my Unreal Engine so that it does not crash?

**Comment by rajat2004** [comment]
I have no idea what's the problem here, Windows releases are also working fine. No changes have been made to master which could cause this effect. Only difference I can think of is system resources, but that's very unlikely

**Comment by AngelTang190** [comment]
I tried to run multi_agent_drone.py in my Blocks Environment and Landscape Mountains environment. Both of them can only run hello_drone.py but not multi_agent_drone.py

**Comment by AngelTang190** [comment]
Can I record the coordinates of both of the drones when I run multi_drone_agent.py?
