### ISSUE TITLE
Performance issue with Unbuntu 18.04.4

### ISSUE THREAD

**Issue by agentfeux** [microsoft/AirSim#2711]
Hi,
I am using a PC with an Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz , GeForce RTX 2070 with 32gb of ram and i got a lot of performance issues. I'm running the STL with like 15 fps and event lower when i start to record.

Can this be Unreal that isn't optimized for Ubuntu ?
What are the difference Ubuntu Vs Windows in term of performance ?

Thanks for helping me :)

**Comment by rajat2004** [comment]
I think you're getting low FPS while trying to record images correct? Or is in the viewport itself?
One basic thing to confirm will be o make sure that `Use Less CPU in background` is unchecked.
Can't say much about the performance difference of Windows vs Ubuntu.
 
One of the main bottlenecks I think with recording images is transfer of data from GPU to CPU, it's going to be slow I guess, there's an open PR #2472 to improve the capture speed
Binaries are generally faster than running inside Editor, you could try running the binary releases, or if it's a custom env or one which hasn't been released, you could compile the binary yourself.

Other options could be switching to `NoDisplay` Mode if viewport isn't important, could also try reducing the resolution of rendering
