### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'AsyncIOLoop' and 'float' 

### ISSUE THREAD

**Issue by avivazran** [microsoft/AirSim#2718]
The Python API documentation states a case where you get
```python
TypeError: unsupported operand type(s) for *: 'AsyncIOLoop' and 'float'
```

This error happens if you install Jupyter, which somehow breaks the msgpackrpc library. Create a new python environment which the minimal required packages.

apparently this is caused by updating `tornado` package to a higher version.
it is probably better to state the required `tornado` package version to assure a working API.

**Comment by ArciAndres** [comment]
All the above is correct. The quick fix to me was
```
pip uninstall airsim
pip install airsim
```
