### ISSUE TITLE
Workflow for adding functionality implemented in blueprint

### ISSUE THREAD

**Issue by avivazran** [microsoft/AirSim#2722]
I'm trying to understand how to extend AirSim to do something like this:
user enter command to python console:
```python
played = client.simPlaySoundInLocation(x,y,z)
```
this will trigger a function which plays some sound and is implemented in a blueprint class i created.
the function returns bool if sound played successfully.

I can't understand the workflow for adding this feature.
I have the blueprint class and the function inside it, but I don't understand how to enable the Python API call and specifically, how to trigger the blueprint class function.

Can someone provide some tutorial on how to do it?

Thanks

**Comment by rajat2004** [comment]
You can see this commit for an example as mentioned in the docs - https://github.com/Microsoft/AirSim/commit/f0e83c29e7685e1021185e3c95bfdaffb6cb85dc
Or for some more recent examples, see https://github.com/microsoft/AirSim/pull/2561, or even https://github.com/microsoft/AirSim/pull/2651 which has lots of new things, but also adds or modifies assets
