### ISSUE TITLE
Visualizing sensors data in Client side (Unreal)

### ISSUE THREAD

**Issue by springyuniverse** [microsoft/AirSim#2723]
I am trying to visualise sensors data (Distance and Lidar sensors data ) in unreal engine, what the right way to approach this

**Comment by rajat2004** [comment]
Lidar has a field `DrawDebugPoints` which when set to `true` will visualize the points. Note that enabling that in the current release can slowdown and cause a crash due to excessive memory usage. This issue has been fixed in master

**Comment by springyuniverse** [comment]
Thanks, what about the distance sensor?

**Comment by rajat2004** [comment]
Don't think that functionality is there in Distance sensor, but a possibly quick way could be to use the Plotting APIs
Some transformation would probably be required, else could try to modify the codebase, should be somewhat similar to Lidar sensor visualization, except less complex https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py#L559

**Comment by springyuniverse** [comment]
Should I also edit the codebase for also speed and height  of the drone?

**Comment by springyuniverse** [comment]
![يتتيتي](https://user-images.githubusercontent.com/16544087/83023011-a5452a00-a02c-11ea-8018-094dd737f045.png)
I mean logging the sensor data in the area as shown in the image

**Comment by rajat2004** [comment]
[`simPrintLogMessage`](https://github.com/microsoft/AirSim/blob/master/docs/apis.md#common-apis) can be used to print stuff there, else could modify in codebase also
See [Multirotor APIs](https://github.com/microsoft/AirSim/blob/master/docs/apis.md#getmultirotorstate) on how to get various quantities related to drone state
