### ISSUE TITLE
Build Errors LNK2019

### ISSUE THREAD

**Issue by 00george** [microsoft/AirSim#2732]
I am trying to build the latest version of AirSim on windows using visual studio 2019. I have windows SDK version 10.0.19041.0 but when I go to build the plugin I get 73 errors and 5 warnings.  The errors all seem to be LNK2019: unresolved external symbol. 

As the build failed errors are long I have put them into a file.
[BuildErrors.txt](https://github.com/microsoft/AirSim/files/4692565/BuildErrors.txt)

**Comment by rajat2004** [comment]
Were all the steps in https://github.com/microsoft/AirSim/blob/master/docs/build_windows.md#how-to-use-airsim done? Specifically, Develop Editor & x64?

**Comment by 00george** [comment]
This is before using airsim and is when trying to build it. The errors are when running build.cmd in Developer Command Prompt for VS 2019

**Comment by madratman** [comment]
You are definitely missing a step in the setup. Please re-open if you're still facing issues with current master.
