### ISSUE TITLE
How can I record more data using release binary of AirSim (Blocks.sln) to be saved in excel file or csv file?

### ISSUE THREAD

**Issue by AngelTang190** [microsoft/AirSim#2733]
I am currently doing a research of multirotor and I am using a release binary Blocks.uproject because my Unreal Engine crashed when I tried to run multi_agent_drone.py but it runs perfectly fine in the release binary.  I would like to gather data on yaw, pitch, speed, angular velocity and the like, if possible all the outputs printed in the console. Is it possible to adjust the recorded data in released binary? Another thing is that what data are represented by Q_X, Q_Y and Q_Z recorded from AirSim?

**Comment by BrightSoulXYHY** [comment]
you can using python  api to get datat ans save them in csv or other format

**Comment by AngelTang190** [comment]
Alright, thanks!
