### ISSUE TITLE
Is there any way to import NVIDIA Isaac's robot model into airsim？

### ISSUE THREAD

**Issue by shaoxiang** [microsoft/AirSim#2734]
NVIDIA's Isaac has two cool robots in unity3d (carter and kaya robot). I want to import them into airsim for robot simulation, but I don't know how to do it. Do you have any good suggestions? Thank you.
IsaacSim Unity3D：
https://docs.nvidia.com/isaac/isaac/doc/simulation/unity3d.html
![carter](https://user-images.githubusercontent.com/9045298/83215768-4dc4cc80-a19a-11ea-9707-9b77b7586080.jpg)
![kaya_robot](https://user-images.githubusercontent.com/9045298/83215779-55847100-a19a-11ea-8445-f90cbfaf8c10.jpg)

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
