### ISSUE TITLE
problem of importing City environment into UE 4.24

### ISSUE THREAD

**Issue by frankzwang** [microsoft/AirSim#2735]
Hi, I was trying to import the city environment downloaded from the city asset provided on github. AND I tried to follow this video from AirSim team to import the city enviroment. https://www.microsoft.com/en-us/research/video/importing-3rd-party-environments-in-unreal-engine-for-airsim/
However, I did not find any fbx files as shown in above video thus I was not able to import the city env. Can anyone tell me how to import it into Unreal Engine 4.24? Thanks a lot! - Frank

**Comment by rajat2004** [comment]
I think the video is more meant for importing standalone assets into an existing env. Try following https://github.com/microsoft/AirSim/blob/master/docs/unreal_custenv.md for adding AirSim plugin in a custom env
