### ISSUE TITLE
Is PX4 SITL v1.8.2  avaible after update to v1.10.1?

### ISSUE THREAD

**Issue by BrightSoulXYHY** [microsoft/AirSim#2738]
In some old realse before PX4 SITL in v1.8.2, the connection between SITL and AirSim like below

![](https://dev.px4.io/v1.8.2/assets/simulation/px4_sitl_overview.png)
and my setting like this, it works well in some old realease for v1.8.2
but in master it dosen't work
```
"Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor",
      "QgcHostIp": "127.0.0.1",
      "QgcPort": 14550,
      "SitlIp": "127.0.0.1",
      "SitlPort": 14556,
      "UdpIp": "127.0.0.1",
      "UdpPort": 14560,
      "UseSerial": false

    }
}

```

SITL using udp port and AirSim simulator using random port

but in PX4 SITL in v1.10.1 connection like below
![](https://dev.px4.io/master/assets/simulation/px4_sitl_overview.png)

I can hardly read AirSim source code, is PX4 SITL in v1.8.2 avaiable after update  to v1.10.1 ?

**Comment by rajat2004** [comment]
The latest AirSim releases and master likely won't work with PX4 1.8.2 but you can try, might have to play with the settings to use UDP, etc. Release 1.2.2 would mostly work with 1.8.2, but still, might need to play around
Instructions and settings for old release could be found by going through the history of the doc
