### ISSUE TITLE
Resetting trace using Python api

### ISSUE THREAD

**Issue by vguillet** [microsoft/AirSim#2740]
Good afternoon,

I was wondering if it was possible to reset the trace left by a drone through the python api?
Thank you!

**Comment by rajat2004** [comment]
Try using [`simFlushPersistentMarkers`](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py#L553)

**Comment by vguillet** [comment]
Yep, thats exactly what I was looking for, thank you!!
