### ISSUE TITLE
Running scripts from jupyter lab

### ISSUE THREAD

**Issue by avivazran** [microsoft/AirSim#2741]
So currently it seems that using jupyter notebook or jupyter lab to run airsim scripts isn't an option due to AirSim's `tornado 4.5.3` requirement, colliding with jupyter's `tornado 6.0.4` requirement.

is there some way to make it work? it'll be nice to be able to run commands from jupyter lab

**Comment by rajat2004** [comment]
The older `tornado` version is a requirement by [`rpclib`](https://github.com/rpclib/rpclib) which is no longer under active development. Switching to newer version will require patches to rpclib or shift to a different RPC library
