### ISSUE TITLE
Unable to view the Reinforcement Learning tutorial by Ashish Kapoor

### ISSUE THREAD

**Issue by amaalo2** [microsoft/AirSim#2745]
Hello, 

I was trying to view the RL tutorial by Ashish Kapoor using the following link:
https://microsoft.github.io/AirSim/docs/reinforcement_learning

However, the page seems empty. Is this the intended behavior? 

![Screenshot from 2020-06-03 18-54-28](https://user-images.githubusercontent.com/25960643/83696950-b6151300-a5cb-11ea-9ca3-3d48d09388f4.png)

**Comment by rajat2004** [comment]
`docs` shouldn't be there in the link - https://microsoft.github.io/AirSim/reinforcement_learning/
![image](https://user-images.githubusercontent.com/37938604/83711354-94a23e80-a640-11ea-82b8-7f3c98ad100f.png)

**Comment by amaalo2** [comment]
Ok, so the link on the main website points to the wrong place. 
![image](https://user-images.githubusercontent.com/25960643/83713098-3ac85700-a5f5-11ea-90d2-760e9934a2fd.png)
