### ISSUE TITLE
Scene image and Depth image not synchronized?

### ISSUE THREAD

**Issue by ShukuiZhang** [Microsoft/AirSim#275]
I obtain the scene image and the depth image using python API, with the following code (modified from camera.py):

```
while True:
    result2 = client.getImageForCamera(0, AirSimImageType.Depth)
    result1 = client.getImageForCamera(0, AirSimImageType.Scene)
    if (result1 == "\0" or result2 == "\0"):
        if (not help):
            help = True
            print("Please press '1' in the AirSim view to enable the Depth camera view")
    else:
        rawImage = np.fromstring(result1, np.int8)
        png = cv2.imdecode(rawImage, cv2.IMREAD_UNCHANGED)
        
        depthImage = np.fromstring(result2, np.int8)
        depthpng = cv2.imdecode(depthImage, cv2.IMREAD_UNCHANGED)
        
        cv2.imshow("Depth", png)
        cv2.imshow("Raw", depthpng)
        cv2.imwrite(os.path.join(DATA_PATH ,"img_" + str(frameCount) + ".png"), png)
        cv2.imwrite(os.path.join(DATA_PATH, "depth_" + str(frameCount) + ".png"), depthpng)
```

However, the recorded scene image and the depth image seems not synchronized. As shown in the following: 
![depth_34](https://user-images.githubusercontent.com/25192948/27060205-13454850-4f90-11e7-95e0-b5675c74eb26.png)
![img_34](https://user-images.githubusercontent.com/25192948/27060207-1a848acc-4f90-11e7-8417-bb45210ab00d.png)
Is there any solution to reduce the drift besides slowing down the drone? I mean, is there a way to improve synchronization performance by tuning the code? Thanks.

**Comment by lovettchris** [comment]
Right they are rendered when you ask for them, which means they will not be perfectly synchronized, Sai Vemprala wrote a handy script that captures the images via screen capture so they are in sync. See his post on [issue#244](https://github.com/Microsoft/AirSim/issues/244).

**Comment by ShukuiZhang** [comment]
Thanks. I will close this one and switch to that thread.
