### ISSUE TITLE
Open Blocks.uproject error

### ISSUE THREAD

**Issue by blyspyder** [microsoft/AirSim#2750]
os : ubuntu18.04
python version : 3.7
airsim version : v1.2.8
Unreal version: 4.18.3
When I open the "Blocks.uproject", I got the error message:
![image](https://user-images.githubusercontent.com/30999511/83853926-93f4cf80-a748-11ea-8822-1374db5fa332.png)
What can I do for this.

**Comment by rajat2004** [comment]
Press Yes to build, it's a common one due tk UE version difference
Note that UE 4.18 mostly won't work with the latest AirSim master, minimum is 4.22 and recommend is 4.24

**Comment by blyspyder** [comment]
> Press Yes to build, it's a common one due tk UE version difference
> Note that UE 4.18 mostly won't work with the latest AirSim master, minimum is 4.22 and recommend is 4.24
I press yes and get the error

**Comment by blyspyder** [comment]
> Press Yes to build, it's a common one due tk UE version difference
> Note that UE 4.18 mostly won't work with the latest AirSim master, minimum is 4.22 and recommend is 4.24
When I press yes I got this error
![image](https://user-images.githubusercontent.com/30999511/83857078-07004500-a74d-11ea-8b58-d57de21a9947.png)

**Comment by rajat2004** [comment]
As mentioned, 4.18 is no longer supported, you'll need to upgrade to 4.22 or 4.24
If you want to use 4.18, then checkout an older commit in master

**Comment by blyspyder** [comment]
> Press Yes to build, it's a common one due tk UE version difference
> Note that UE 4.18 mostly won't work with the latest AirSim master, minimum is 4.22 and recommend is 4.24

How can I update my UE version in ubuntu18.04. I can't find any information about it.

**Comment by rajat2004** [comment]
Follow the steps in https://github.com/microsoft/AirSim/blob/master/docs/build_linux.md to install 4.24

**Comment by blyspyder** [comment]
> Follow the steps in https://github.com/microsoft/AirSim/blob/master/docs/build_linux.md to install 4.24

Thank you very much, I will try it now.
