### ISSUE TITLE
Changing trace color using python

### ISSUE THREAD

**Issue by vguillet** [microsoft/AirSim#2751]
Good afternoon, I was wondering if there was a way to adjust the trace color mid run using python

Cheers! Loving airsim so far!

**Comment by rajat2004** [comment]
Try using [`simSetTraceLine`](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/client.py#L305)

**Comment by vguillet** [comment]
Thanks for the swift reply! As a follow up, do I call it on client? It doesnt seem to appear in the class definition? (Also, what parameter is used to adjust the color?)

**Comment by rajat2004** [comment]
All methods are to be called using a client if that's what you're asking - `client.simSetTraceLine(...)`
Seems like this was added after the current latest `airsim` package was released (`1.2.8`)
You can put your code in one of the folders like `Pythonclient/multirotor` and add `import setup_path` before doing `import airsim` to use the master branch APIs

Also see [set_trace_line.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/set_trace_line.py) for usage

**Comment by vguillet** [comment]
Great, thank you!
