### ISSUE TITLE
Propellers render outside MultiRotor #784，how to solve it?

### ISSUE THREAD

**Issue by love-mj** [microsoft/AirSim#2758]
if I leave it running long enough, the propellers end up outside of the MultiRotor. Exact placement of the rotor varies but they move outside of the frame. When I have run overnight I have seen this issue consistently, but I do not have an exact time to failure.
![35744104-76347e28-080d-11e8-8f67-7ff43888fede](https://user-images.githubusercontent.com/37679671/84003783-22618f00-a99d-11ea-8468-e6382f497e32.png)

**Comment by jonyMarino** [comment]
Treated in #784
