### ISSUE TITLE
Unity Build Issue v1.2.2

### ISSUE THREAD

**Issue by dion26** [microsoft/AirSim#2761]
Really the same like [#1964](https://github.com/microsoft/AirSim/issues/1964#issue-444625833) and [#2513](https://github.com/microsoft/AirSim/issues/2513) . I've tried those answers but got no luck.

I nee to install the old Version from airsim (1.2.2 or 1.3.0) but get the error while Building Unity.

`"C:\Users\diond\Documents\Code\AirSim-1.3.0-vanilla\Unity\AirLibWrapper\AirsimWrapper.sln" (Clean;Build Ziel) (1) ->
"C:\Users\diond\Documents\Code\AirSim-1.3.0-vanilla\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (
Standardziel) (2:2) ->
"C:\Users\diond\Documents\Code\AirSim-1.3.0-vanilla\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj" (Standardz
iel) (5:2) ->
(ClCompile Ziel) ->
  c:\users\diond\documents\code\airsim-1.3.0-vanilla\unity\airlibwrapper\airsimwrapper\source\simmode\simmodebase.cpp(1
8): error C2259: "WorldSimApi": Instanz von abstrakter Klasse kann nicht erstellt werden [C:\Users\diond\Documents\Code
\AirSim-1.3.0-vanilla\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj]`

I am using:
- Windows 10
- Visual Studio Community 2017 (15.9.23)
- Win SDK 8.1

which solution does actually works for Airsim 1.2.2 Version?

**Comment by rajat2004** [comment]
Older version of AirSim might not compile, especially for Unity. Even 1.3.0 tag might not work, it's best to try the latest master version for Unity since some fixes for compilation and crashes have gone in since 1.3.0
