### ISSUE TITLE
Addition of Teledyne Scientific to "Who is Using AirSim" page

### ISSUE THREAD

**Issue by TDYbrownrc** [microsoft/AirSim#2763]
I would like to request that Teledyne Scientific be added to the groups on the "Who is Using AirSim" page. We are currently engaged in research focused on lifelong learning AI as well as human-AI teaming research. We use AirSim drones as embodied AI agents that continuously learn through interacting with their environment. We also have developed a capability to engage in human-AI teaming experiments with humans and AirSim drones interacting together in the same UE4 environment. 

The preferred link that we would like to use is a link to our paper on lifelong learning machines that leverages AirSim to provide an embodied classification agent that can move in the environment to improve its ability to classify objects as well as learn novel objects it encounters. 

Paper link: [https://doi.org/10.1016/j.neunet.2019.09.011](https://doi.org/10.1016/j.neunet.2019.09.011)

**Comment by madratman** [comment]
arXiv: https://arxiv.org/abs/2001.09822
