### ISSUE TITLE
how can i get Environments source code?

### ISSUE THREAD

**Issue by kimwin2** [microsoft/AirSim#2767]
Hi.
I'm trying to use Airsim to apply autonomous car environment. 
i just downloaded release environment such as blocks, cities which is binarized version. 
I have a question that how can i get a source code version? Is it possible to get it?

thanks.

**Comment by rajat2004** [comment]
Blocks source code included in the repo, and is the default env for testing
Envs can be downloaded from Marketplace - [Neighbourhood](https://www.unrealengine.com/marketplace/en-US/product/modular-neighborhood-pack), [City](https://www.unrealengine.com/marketplace/en-US/product/downtown)  and lot's more

**Comment by madratman** [comment]
Apart from the above, the envs are closed source.
