### ISSUE TITLE
block mavlink messages from sensors library

### ISSUE THREAD

**Issue by limzhanfeng** [Microsoft/AirSim#277]
Hi, I am trying send my own messages and would like to stop the current sensors library form sending out Mavlink message to the connection and updating the drone controller. How do I block these messages?

**Comment by lovettchris** [comment]
See [intercepting mavlink](https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages).

**Comment by limzhanfeng** [comment]
Thanks!

**Comment by nickylimjj** [comment]
Hi, I have just read [intercepting mavlink](https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages) and tried to run mavlink test and run airsim after modifying `settings.json` as specified. However, i get the following error 

> not receiving any messages from HIL, please restart your HIL node and try again

Any clues what it may be?
