### ISSUE TITLE
Add resistance to the drone

### ISSUE THREAD

**Issue by pengzhi1998** [microsoft/AirSim#2780]
Hi everyone.
I'm trying to use AirSim to simulate the underwater environments. One of the most important difference comes from the resistance of water and air. Is there a way to add resistance?

**Comment by nicocarb** [comment]
Drag forces already exist within the Physics Engine although it already assumes air. Perhaps you can look into modifying some of the density parameters within the existing framework to test it out? Try out Environment.hpp and RotorActuator.hpp in the AirLib library.
