### ISSUE TITLE
AirSim ROS wrapper with Python API

### ISSUE THREAD

**Issue by pengzhi1998** [microsoft/AirSim#2785]
Hi everyone, is there a convenient way to use ROS wrapper with Python API for Airsim on the drones? May I use it with Melodic and Ubuntu 18.04?
Thanks for the help!

**Comment by pengzhi1998** [comment]
I found this [code](https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/kinect_publisher.py#L134) a good example. It imports rospy and AirSim at the same time. However, if I didn't remember wrong, ROS uses Python 2 while AirSim should use Python 3. Is there a way to fix that? And will Melodic be applicable?

**Comment by EdwinMeriaux** [comment]
Wait are you just trying to use ROS and Airsim together? Did you do the Airsim ROS wrapper set up?

**Comment by pengzhi1998** [comment]
Thank you for your reply!
Sorry, I'm new on this topic. But I found that the AirSim ROS wrapper can only use C++ API. But I need to use Python API with Ubuntu 18.04. Do you know how to deal with that?

**Comment by EdwinMeriaux** [comment]
Yeah you can just use python with that wrapper (at least from what I have used so far it works):

https://microsoft.github.io/AirSim/airsim_ros_pkgs/
follow these steps

**Comment by thejeshk** [comment]
Hi @pengzhi1998 @EdwinMeriaux 


I have posted my query here -> https://github.com/microsoft/AirSim/issues/2796#issue-643951496

Can you confirm if this is valid for Car ?

**Comment by EdwinMeriaux** [comment]
@thejeshk Sorry if what is valid for Car? Could you please clarify?

**Comment by thejeshk** [comment]
Hi @EdwinMeriaux 

Thank you for your reply. 

I am using Airsim car not Multirotor. 

My question is: Is there a ROS wrapper for Car? 

I could only find the tutorials for drones https://microsoft.github.io/AirSim/airsim_tutorial_pkgs/

**Comment by EdwinMeriaux** [comment]
I have never used the a car in airsim. But I would assume that you could write a similar one for the car.
What do you want to do the the car and ros?

**Comment by madratman** [comment]
PR https://github.com/microsoft/AirSim/pull/2743 added this. This was also answered here https://github.com/microsoft/AirSim/issues/2796#issuecomment-650674502
