### ISSUE TITLE
Are multi vehicles synchronized their states？

### ISSUE THREAD

**Issue by sandyUni** [microsoft/AirSim#2791]
I am developing Airsim to measure the distance between two vehicles. I am worried about the states of the vehicles reported by the API are not synchronized. Are multi vehicles synchronized their states？ Or are there some tolerable clock differences among different vehicles?

**Comment by jonyMarino** [comment]
They are synchronized. It could happen that they have just one step of difference (3ms) when calling the API, that would be not the general rule.
