### ISSUE TITLE
Broken link in the wiki

### ISSUE THREAD

**Issue by siddhantrao23** [microsoft/AirSim#2794]
Just found out that you can't make a pull request on the wiki, but in the [Drone Survey Script](https://github.com/microsoft/AirSim/wiki/Implementing-a-Drone-Survey-script) the link to the actual code is wrong.

How can this be fixed?

**Comment by rajat2004** [comment]
Opened #2803 which moves the Wiki page to the AirSim docs and fixes the link
Will be moving some other pages as well

**Comment by siddhantrao23** [comment]
Thanks!
