### ISSUE TITLE
How to get collision info that return "True" or "False"

### ISSUE THREAD

**Issue by 4iue0** [microsoft/AirSim#2818]
My English skill is poor so it may be difficult to read it.

API of getCollisionInfo get 'has_collided' but it returns lots of info.
if i can get collision info return only True or False, plz tell me how.

**Comment by rajat2004** [comment]
You're pretty close
```
collision_info = client.simGetCollisionInfo()
if collision_info.has_collided:
    // Vehicle has collided
else:
    // No collision
```

**Comment by 4iue0** [comment]
Thank you for your advise.
my problem solved
