### ISSUE TITLE
Get distance sensor data is not defined

### ISSUE THREAD

**Issue by Homesliggidy** [microsoft/AirSim#2820]
Hello, I am new to AirSim

I wanted to use the distance sensor on a drone, but I'm having an issue

Here's the line trying to access the data:
`Distance = getDistanceSensorData("Distance", "Drone1")`

Error:
`Traceback (most recent call last):
  File "trial1.py", line 33, in <module>
    Distance = getDistanceSensorData("Distance", "Drone1")
NameError: name 'getDistanceSensorData' is not defined`

Here is what I have in my JSON file:

`{
	"SettingsVersion": 1.2,
	"SimMode": "Multirotor",
	"Vehicles": {
		"Drone1": {
			"DefaultSensors": {
			    "Barometer": {
			         "SensorType": 1,
			         "Enabled" : true
			    },
			    "Imu": {
			         "SensorType": 2,
			         "Enabled" : true
			    },
			    "Gps": {
			         "SensorType": 3,
			         "Enabled" : true
			    },
			    "Magnetometer": {
			         "SensorType": 4,
			         "Enabled" : true
			    },
			    "Distance": {
			         "SensorType": 5,
			         "Enabled" : true
			    },
			    "Lidar2": {
			         "SensorType": 6,
			         "Enabled" : true,
			         "NumberOfChannels": 4,
			         "PointsPerSecond": 10000
			    }
			},
			"VehicleType": "SimpleFlight",
			"X": -50, "Y": 0, "Z": -2
		}
	}
}`

**Comment by rajat2004** [comment]
API should be used as follows - `distance_sensor_data = client.getDistanceSensorData("Distance", "Drone1")`
As to the settings, inside the vehicle, the sensors should be specified in `Sensors`, not `DefaultSensors`, see https://github.com/microsoft/airsim/blob/master/docs/sensors.md#configuring-vehicle-specific-sensor-list
