### ISSUE TITLE
I would like to see the three cameras in my unreal environment

### ISSUE THREAD

**Issue by Jean-MichMich** [microsoft/AirSim#2822]
Hi everyone,

I've a little problem in my unreal environment. I builded Airsim and I created a custom map with the Airsim plugin, but when I press play, I can see the drone of course but I can't see the three cameras attached to it...

I searched a lot of solutions on internet but it didn't work each time. 

Thanks in advance for all your responses ! :)

**Comment by LSBOSS** [comment]
Hi @Jean-MichMich ,

here are three things you can check: 

* Make sure the GameMode of your custom map ist set to AirSim. See World Settings for details:
![image](https://user-images.githubusercontent.com/7292257/86224669-75d49080-bb89-11ea-8f32-e2fdc7ee6fd8.png)

* After pressing play, and flying around with your drone, try pressing 1, 2 and 3 on your keyboard to see depth, segmentation and rgb sub windows (they are configured by default)

* If you have attached your own virtual cameras to your drone you need to configure the corresponding SubWindow entry in your settings.json: 
```json
"SubWindows": [
    {"WindowID": 0, "MyFirstCustomCamera": "0", "ImageType": 0, "Visible": true},
    {"WindowID": 1, "MySecondCustomCamera": "0", "ImageType": 0, "Visible": true},
    {"WindowID": 2, "MyThirdCustomCamera": "0", "ImageType": 0, "Visible": true}
  ],
```

More details here: https://github.com/microsoft/AirSim/blob/master/docs/settings.md#subwindows

**Comment by Jean-MichMich** [comment]
Hi @LSBOSS !

Thank you so much it worked for me ! i just forgot to update my settings.json !! ^^'
