### ISSUE TITLE
"DisparityNormalized" is always black image

### ISSUE THREAD

**Issue by 4iue0** [microsoft/AirSim#2828]
My English skill is poor, so it may be difficult to read it.

I use client.simGetImages to get DisparityNormalized image.
However I always get just black  #image.
![1](https://user-images.githubusercontent.com/67323712/86512886-abef6a00-be40-11ea-8887-ca15401622b4.png)

I use this python code
`client.simGetImages([
    airsim.ImageRequest("1", airsim.ImageType.DisparityNormalized)]) `

**Comment by EdwinMeriaux** [comment]
@4iue0 
Hello!
I am not very familiar with the disparity normalized images but I I've used the image API a lot recently so I may be able to help.
So are you not trying to set the pixels_as_float = true in your code. I checked on the API docs:
https://github.com/microsoft/AirSim/blob/master/docs/image_apis.md

"You normally want to retrieve disparity image as float (i.e. set pixels_as_float = true"


(I'm not 100% sure)I think there is an example of that here:
https://github.com/microsoft/AirSim/blob/master/Examples/DataCollection/StereoImageGenerator.hpp

on line 66:
"ImageRequest("1", ImageType::DisparityNormalized, true)"

**Comment by 4iue0** [comment]
@EdwinMeriaux 
Thank you for your advise !
My problem was solved.

**Comment by EdwinMeriaux** [comment]
@4iue0 

Awesome!
Was what I said the solution?
