### ISSUE TITLE
executing mavlinktest as a proxy relay

### ISSUE THREAD

**Issue by nickylimjj** [Microsoft/AirSim#283]
Hi, I have just read [intercepting mavlink](https://github.com/Microsoft/AirSim/wiki/Intercepting-MavLink-messages) from #277 and tried to run mavlink test and airsim after modifying `settings.json` as specified. However, i get the following error 

> not receiving any messages from HIL, please restart your HIL node and try again

Any clues what it may be?

**Comment by nickylimjj** [comment]
I have tried investigating further and when i run the command as shared `MavLinkTest.exe -serial -proxy:127.0.0.1:14560` and looked at my machine's networks using `netstat -abnp udp` i notice that port 14560 isn't in use, but mavlinktest.exe is is using `49722`. What should i do?

**Comment by flyingsilverfin** [comment]
A month late but I noticed this can be solved by using -server instead of -proxy :)

**Comment by enesvta** [comment]
> Bir ay geç oldu ama bunun -proxy yerine -server kullanılarak çözülebileceğini fark ettim :)



> A month late but I noticed this can be solved by using -server instead of -proxy :)

How did you?
