### ISSUE TITLE
How do I simulate a ZED camera (stereo vision) on Airsim

### ISSUE THREAD

**Issue by Deepakgthomas** [microsoft/AirSim#2830]
I'm training my reinforcement learning algorithm that'll be later implemented on a real UAV. In order for the transfer to be successful, I'd like to simulate a ZED camera first and train the RL vision portion with it. How should I go about simulating a ZED stereo camera on Airsim?

I did come across a couple of similar questions, however, they do not help much, for they only talk about changing the baseline - 
1) https://github.com/microsoft/AirSim/issues/1770
2) https://github.com/microsoft/AirSim/issues/1790

Apologies if this question sounds naive, I'm new at this :)

**Comment by rajat2004** [comment]
https://github.com/microsoft/AirSim/issues/1790#issuecomment-471779112 should give you the cameras required, and the images can be fetched using something like -
```
responses = client.simGetImages([
    airsim.ImageRequest("front-left", airsim.ImageType.Scene),
    airsim.ImageRequest("front-right", airsim.ImageType.Scene)])
```

If you want, you can add the cameras as subwindows (to be toggled using 1,2,3) - https://microsoft.github.io/AirSim/settings/#subwindows
