### ISSUE TITLE
Can multirotor fly in modes other than linear straight line? (AirSim)

### ISSUE THREAD

**Issue by AngelTang190** [microsoft/AirSim#2831]
I only know that multirotors can be programmed to fly from one coordinate to another coodinate in a linear straight line, However, is there anyway that multirotors can be programmed to fly from one coordinate to another coordinate in more complex modes, for example circular motion?

**Comment by madratman** [comment]
https://github.com/microsoft/AirSim/blob/master/PythonClient/multirotor/orbit.py
