### ISSUE TITLE
Record images using API instead of Button

### ISSUE THREAD

**Issue by sourabhlal** [microsoft/AirSim#2832]
I am working with a script that runs several simulations with AirSim, and I would like to automate the clicking of the Record button. Is there anyway I could do this using the Python API?

**Comment by rajat2004** [comment]
Oh, so you're launching the simulation from scripts themselves? You could use the APIs to fetch the data and store it in the desired format, but if the Recording option gives what is required, then makes sense to use that directly(also might be faster)

There isn't any such API right now, but should be starighforward to add it, you can have a look at https://microsoft.github.io/AirSim/apis/#adding-new-apis-to-airsim which links an example commit. Or might give it a shot myself

**Comment by rajat2004** [comment]
I've opened #2834 which adds the APIs

**Comment by jeffreyng99** [comment]
@sourabhlal For you scripts, do you run them after you start the simulation by pressing play? I'm trying to figure out how to start the simulation without having to do it manually. I'm working in Linux which may be different than Windows.

**Comment by rajat2004** [comment]
@jeffreyng99 If you have set `SimMode`, then AirSim should start without the prompt to select the vehicle. If you're talking about running in the Editor, then yeah, you'll have to press Play in that.
