### ISSUE TITLE
How to use API getGpsData()

### ISSUE THREAD

**Issue by johan606303** [microsoft/AirSim#2833]
Hi.
I don't understand how to use gps coordinates.

I simulate a Multirotor on SimpleFlight.
I generated the following code to convert recieved coordinates from gps to cartesians.

![coordinates3](https://user-images.githubusercontent.com/62846458/86769067-d1ea5980-c04e-11ea-8acd-99abe3d6d0cd.PNG)

To test it, I first moved the Mulirotor on position (0,0,-2) with the moveToZAsync() API.
Then I sent the drone to position (10,0,-2) and then I calculated the distance between those 2 positions.
The algorithm returned 0.020012902165323553.

Then I made an experiment by moving the drone from (0,0,-2) to (20,0,-2).
The algortithm returned 0.019863271520453352.

I would like to controle several drone, to controle the distance between them, move to position, by manipulating cartesian and gps coordinates. Or was just the function formula wrong ?

**Comment by madratman** [comment]
If you want to get x, y, z coordinates, please use getMultirotorState() instead
The NED <-> Geodetic conversions are handled in C++ here https://github.com/microsoft/AirSim/blob/master/AirLib/include/common/EarthUtils.hpp#L288
You'd have to either port them to python or just use the cartesian state via getMultirotorState
