### ISSUE TITLE
Multi-Vehicle Subwindows

### ISSUE THREAD

**Issue by mhl787156** [microsoft/AirSim#2838]
Hi, I am wanting to live display a camera from each of the drones I have created. Currently in the settings.json, we add the subwindows like so: 
> "SubWindows": [
>    {"WindowID": 0, "ImageType": 0, "CameraName": "3", "Visible": true},
>  {"WindowID": 1, "ImageType": 3, "CameraName": "0", "Visible": true},
>   {"WindowID": 2, "ImageType": 6, "CameraName": "4", "Visible": true}
>  ]

Am I correct in saying that CameraName can only refer to cameras of the 'first' drone? Is there a way to an updated way to display other drones's cameras in the subwindows?

As far as I can find, there have only been two previous issues on this problem in particular: #1172 and #133. #1172 presents a possible solution that someone else has implemented, but their changes no longer work as the api has changed. 

Pulled from master branch about a week ago. Perhaps adding a 'VehicleName' parameter to the Subwindow entries might allow this feature? 

Many Thanks!

**Comment by rajat2004** [comment]
I've opened #2841 which adds `Vehicle` option to the Subwindows settings

**Comment by mhl787156** [comment]
Amazing thank you!
