### ISSUE TITLE
Merging the Pull Requests! 

### ISSUE THREAD

**Issue by mhl787156** [microsoft/AirSim#2843]
Hi All,

Apologies if this does not count as an issue, feel free to remove!

Just wanted to ask if the maintainers of the project are still around! There are a whole bunch of awesome Pull Requests (Thanks @rajat2004!) with really useful features that are sat around ready but unmerged! 

Any ideas if the merging will happen any time soon?

**Comment by madratman** [comment]
We've merged a few PRs, and will be merging more soon.
