### ISSUE TITLE
[UE4] simGetSegmentationObjectID will always return -1 

### ISSUE THREAD

**Issue by LSBOSS** [microsoft/AirSim#2854]
### Intro
Depending on the MeshNamingMethod in SegmentationSettings in AirSim's settings.json custom IDs will be assigned either based on a name of a StaticMesh/SkelletalMesh or the name of its owner. 

For that reason `UAirBlueprintLib::GetMeshName `is being used during initialization of IDs to find out the correct name and also taking the different nature of above MeshComponents into account. 

### Problem
However, calling `simGetSegmentationObjectID `from Python ultimately leads to the call of `UAirBlueprintLib::GetMeshStencilID` which is NOT using above GetMeshName method but rather is just comparing the actual name of a MeshComponent (e.g. "StaticMeshComponent0") with the passed search parameter (e.g. "ground") . This ultimately fails and thus this function is returning -1.

### Example
I added two log outputs. One in `UAirBlueprintLib::GetMeshStencilID` to output every name this function is comparing to the passed search parameter + corresponding custom ID. A second log has been inserted into `UAirBlueprintLib::InitializeObjectStencilID` to output its name handling + corresponding custom IDs 

From the Block environment I chose 4 objects for comparison and then called `print(client.simGetSegmentationObjectID("ground")) ` from Python which returns -1.

**UAirBlueprintLib::InitializeObjectStencilID:**
```
LogTemp: [name --> id]
LogTemp: cylinder2 --> 95
LogTemp: ground --> 148
LogTemp: templatecube_rounded_10 --> 241
LogTemp: orangeball --> 28
```

**UAirBlueprintLib::GetMeshStencilID:**
```
LogTemp: [name --> id]
LogTemp: StaticMeshComponent0 --> 95
LogTemp: StaticMeshComponent0 --> 148
LogTemp: StaticMeshComponent0 --> 241
LogTemp: StaticMeshComponent0 --> 28
```

GetMeshStencilID is comparing the passed parameter "ground" with all the StaticMeshComponent0 it can find which in the end fails.

### Fix proposal
*  In UAirBlueprintLib::GetMeshStencilID:
    * Make use of GetMeshName instead of the component name 
    * Iterate over StaticMeshComponents and SkinnedMeshComponents separately as done in InitializeMeshStencilIDs

### Sofware and Versions 
Unreal Engine: 4.24.2
AirSim Plugin build from commit: Mon Jun 1 10:30:23 2020 +0530
AirSim Python library: 1.2.8
Python: 3.7.2 32bit

**Comment by chongjeelee** [comment]
hi,everyone,i found a helpful method to set or get segmentation id.the mesh name you can find it in the GUI details(Static Mesh),like below:
![screenshot-20220124-162412](https://user-images.githubusercontent.com/30140969/150747085-ed6850c3-9871-4a2a-bf39-a47205063010.png)
---------
you can use client.simSetSegmentationObjectID("Air_Balloon_Set[\w]*",0,True)  to set air_ballon_set object color,also you can use client.simSetSegmentationObjectID("SM_hang_glider[\w]*",255,True).
Be careful with [\w]*,this is regex.
if you want to set what you want to set ,pls set all objectID the same color before,like this,client.simSetSegmentationObjectID("[\w]*",0,True).
when you find objectID always return  -1,this is a good idea!
hahaha ,i think so.
