### ISSUE TITLE
Scaling down the default SUV to 1:10 size

### ISSUE THREAD

**Issue by shortstheory** [microsoft/AirSim#2869]
Hi! I am working on an application using AirSim that involves mapping an indoor environment with a ground robot. The default SUV is a decent starting point for what we need, but it's too large to fit in the indoor environments which we want to map. Is there a way I can modify the SUV's model and parameters to make it 1:10 of its current size?

* OS: Windows/Linux
* Python Version: 3.7.6
* AirSim Version: 1.3.1
* Unreal Version: 4.24

**Comment by madratman** [comment]
![image](https://user-images.githubusercontent.com/6305323/88766006-2ce20e80-d12c-11ea-9272-32af36c3fa68.png)
![image](https://user-images.githubusercontent.com/6305323/88766027-35d2e000-d12c-11ea-9bb7-102faa37e70c.png)

Follow the screenshots above and change the scale of the SUV pawn to 0.1, 0.1, 0.1 for x, y, z
