### ISSUE TITLE
Tilt Rotoring Quadcopter in SITL

### ISSUE THREAD

**Issue by clev0910** [microsoft/AirSim#2871]
Hello everyone! I'm trying to run a tilt rotoring quadcopter with SITL using airsim on unreal engine. The quadcopter is able to have the tilt rotoring mechanism in real life, but I'm unable to do this using SITL after changing the parameters on Mission Planner. I'm not too sure, but I think this is because the software doesn't know where the servos are located. Is there anyway of implementing tilt rotoring on AirSim?

**Comment by madratman** [comment]
The configuration of the multirotor is determined by the MultirotorParams class which is initialized here - https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotorParamsFactory.hpp

You'd have to specify a custom normal vector for each rotor in the RotorPose struct (https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotorParams.hpp#L20)

See initializeRotorQuadX to see how rotor poses are used https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotorParams.hpp#L108
