### ISSUE TITLE
Unable to run the demo in  Setup Blocks Environment for AirSim

### ISSUE THREAD

**Issue by manjusha1691** [microsoft/AirSim#2879]
I followed **[https://microsoft.github.io/AirSim/build_windows/]** to install AirSim and Unreal 4.25. I am able generate .sln file in the blocks folder and when I am trying to launch it using VS2019 on a Windows10 machine . The following screen is loading. 
![3](https://user-images.githubusercontent.com/54560778/88465273-aad5b980-ce8f-11ea-9cd1-fbd0cc769ebd.JPG)

According to instructions in Step 5 in ["**Setup Blocks Environment for AirSim**"](https://microsoft.github.io/AirSim/unreal_blocks/#setup-blocks-environment-for-airsim) , once the Unreal editor loads, It will allow me to press the play button so that I can see the demo video but the above image is how it is loading for me. 
All the steps while installing Unreal and AirSim appeared to execute correctly. I have no clue how to run that demo. 
However, I am suspecting the issue could be with running update_from_git.bat on the blocks folder. The following is the output when I ran the command.
![1](https://user-images.githubusercontent.com/54560778/88465376-8af2c580-ce90-11ea-8dff-4f81baca515e.JPG)
![2](https://user-images.githubusercontent.com/54560778/88465378-8b8b5c00-ce90-11ea-8d3f-099ac4c1296a.JPG)

Despite this above error, the .sln file has been created fine. However, I am not able to play the demo.

**Comment by madratman** [comment]
Please restart Epic Games launcher and click on "associate project file extension with unreal engine", and try again.
