### ISSUE TITLE
Custom Quads

### ISSUE THREAD

**Issue by eanmikale** [Microsoft/AirSim#288]
Chris, 
I know there was talk about creating the capability to utilize the DJI M100. We are interested in utilizing the M100, but are even more concerning the DJI Mavic Pro. Is this a possibility in the near future for either? Thank you in advance. 

EM

**Comment by andre-nguyen** [comment]
Why not just add it in yourself by following the tutorial and using the official CAD?

https://github.com/Microsoft/AirSim/wiki/hexacopter
http://download.dji-innovations.com/downloads/dev/Matrice/M100_Airframe__CAD.STEP

**Comment by eanmikale** [comment]
Thank you!

**Comment by chaitanyantr** [comment]
hey @eanmikale ,

any luck on matric 100 in airsim??

**Comment by eanmikale** [comment]
Yes, we just dropped it in as an asset. I know we are able to add our own custom hardware designs. However, we have inquiries concerning commercial hardware we are developing, which we would like to be an easy integration into the AirSim ecosystem. Is there anyone internally we can discuss our project with? Funny you mention the Matrix 100. Our projects seeks to replace it with an American made, truly open-source upgrade. Any assistance would be great. Support for the CrazyFlie swarms would be awesome as well. Thanks again. 

Regards,

Ean Mikale, J.D.

Chief Innovation Officer

Infinite 8 Institute, L3C

ean@infinite8institute.com

www.infinite8institute.com





U.S. Federal Contractor




---- On Fri, 08 Feb 2019 06:42:41 -0600 notifications@github.com wrote ----



hey @eanmikale ,

any luck on matric 100 in airsim??

**Comment by demoniusrex** [comment]
I am working on a multi-rotor API implementation for DJI Onboard-SDK  that should support M100 with a few tweaks. All I have to test on is a N3 flight controller. 

You can check out the work in progress here [AirSim-Onboard](https://github.com/demoniusrex/AirSim-Onboard) (New multi-rotor API)[https://github.com/demoniusrex/AirSim-Onboard/blob/master/Rosie/linux/OnboardLib/include/vehicles/multirotor/firmwares/dji/OnboardMultirotorApi.hpp]
