### ISSUE TITLE
Random seed and trajectories (recorded positions in airsim_rec.txt) 

### ISSUE THREAD

**Issue by lmsstate** [microsoft/AirSim#2895]
AirSim : v1.3.1 - Windows 
OS: Windows 10
Python Version : 3.7.2 +
Unreal Version : 4.25
We are conducting a drone risk analysis by analyzing thousands of trajectories flying the same waypoints. We find we could get trajectories in recorded positions in airsim_rec.txt. We would like to know:
1.	If there are any random number seeds, we can change so each time when we simulate the same flight, the trajectory will be changed.
2.	If the answer in 1 is yes, then where is the exact place, we can find and can use different random number seeds each time.
3.	How the random number affect the trajectory exactly? For example, by polling different drone cruise speed curve? How the underline distribution of the cruise speed curve is generated? cruise speed is just an example, basically what are underline parameters that affect trajectories will be affected by random number and how the distributions of the parameters are generated?
Any hints and replies will be greatly appreciated!

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
