### ISSUE TITLE
detecting collisions through python api

### ISSUE THREAD

**Issue by abdelrahman-t** [Microsoft/AirSim#290]
Hey, 

how should i go about detecting collisions using the python api ?, which places should i look at in the code to try and add this functionality (and then later to the python api)?, and how should i go about resetting the environment programmatically( get drone in the starting position ) and reset SITL ?

thank you,

regards

**Comment by sytelus** [comment]
I just implemented getCollisionInfo() API which should now be available in Python.

https://github.com/Microsoft/AirSim/blob/master/AirLib/include/rpc/RpcLibClient.hpp#L46

**Comment by abdelrahman-t** [comment]
thanks Shital 😄
