### ISSUE TITLE
How can I convert depth planner into NED coordinate?

### ISSUE THREAD

**Issue by yemx21** [microsoft/AirSim#2900]

**Comment by Aku02** [comment]
AirSim uses NED (North-East-Down) frame, and the front camera has EDN 
`Tw = np.array([T[:,2], T[:,0], T[:,1]]).T` 

I hope this helps

**Comment by yemx21** [comment]
> AirSim uses NED (North-East-Down) frame, and the front camera has EDN
> `Tw = np.array([T[:,2], T[:,0], T[:,1]]).T`
> 
> I hope this helps

Do you know how to convert the depth image into pointcloud with NED coordinate?
