### ISSUE TITLE
Multiplayer, having a drone and an entirely different player pawn in the same game session

### ISSUE THREAD

**Issue by Maxilos** [microsoft/AirSim#2903]
What I am trying to achieve is the following: the ability to have a session with one client (or server) controlling the drone, and the other client controlling an entirely different spectartor pawn, that has nothing to do with airsim as a whole. 
In order to create a server/connect to it, I am using a different level with a gamemode override (basically, different from AirSimGameMode) and a widget with two button, tied to creating/connceting to server and loading the actual AirSim level, nothing special. The idea is that the server should possess the AirSim pawn, and the client should possess the spectator pawn. 
Now, without AirSim this works perfectly fine, however, when it comes to the airsim project, something goes wrong. The server  starts the level perfectly fine, possesses the AirSimPawn, however whenever the client tries to connect, it throws 

"Error at startup: VehicleSetting for vehicle name BP_FlyingPawn_C_0 was requested but not found"

The crash reporter then points to 
UE4Editor_AirSim_0003!ASimModeWorldBase::Tick() [F:\UVSProject-1.3\Plugins\AirSim\Source\SimMode\SimModeWorldBase.cpp:110] , 

which is this line:

 physics_world_->lock();

Can someone please point me in the right direction to solve this?

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
