### ISSUE TITLE
Bug on Multirotor "moveOnPath"

### ISSUE THREAD

**Issue by ppueyor** [microsoft/AirSim#2917]
We discovered a bug in moveOnPath. The last segment of the path was not taken into account, so the drone didn't move to the last position on the segment list. We fixed it in our private repository.

The file that needs to be fixed is "MultirotorApiBase.cpp". 

Should we upload the new file here or we just need to indicate the lines and fixes done?

**Comment by rajat2004** [comment]
A PR if possible would probably be the best way!

**Comment by zimmy87** [comment]
This issue is by design; see my comment [here](https://github.com/microsoft/AirSim/pull/2919#issuecomment-738271735).
