### ISSUE TITLE
Airsim crashes if you run px4 and close airsim before 2 seconds.

### ISSUE THREAD

**Issue by EivindYN** [microsoft/AirSim#2924]
Reproducing steps:
* Run PX4
* Run and exit AirSim before 2 seconds passes

Errors (and fixes):
MavLinkMultirotorApi.hpp
![image](https://user-images.githubusercontent.com/31821339/89871679-1b7f1480-dbb8-11ea-92de-74d32ea40958.png)
Then after fixing this error with the commented out line you get this:
![image](https://user-images.githubusercontent.com/31821339/89872405-2c7c5580-dbb9-11ea-8413-9ef300dbcdc7.png)
The error is actually at the connect part. This naturally happens as mav_vehicle = nullptr after disconnecting, so using the commented out lines fixes this too.

**Comment by lovettchris** [comment]
I may have fixed this bug in this pull request:
https://github.com/microsoft/AirSim/pull/3757

**Comment by zimmy87** [comment]
This issue doesn't repro for me w/ AirSim master connecting with PX4 master running over WSL2 and PX4 v1.11.3 running over cygwin. This is before I applied the fix in #3757.
