### ISSUE TITLE
Want to customize rotor directions

### ISSUE THREAD

**Issue by limzhanfeng** [Microsoft/AirSim#293]
Hello I would like to customize my own vehicle. I find the parameters for the dimensions and other things in rotors, multirotors and px4multirotor, but can't find where the normal directions of the rotors are set. How should I go about changing these settings?

**Comment by lukaszdworako** [comment]
I believe the variable name is rotor_z set in fast physics engine but I need to double check

**Comment by lukaszdworako** [comment]
Not in fast physics engine, I would double check in wherever the rotor parameters are for the previously mentioned variable

**Comment by limzhanfeng** [comment]
I found rotor_z as one of the local parameters in initializeRotors, part of MultiRotorParams.hpp. However I can't find where initializeRotors is being called.

**Comment by limzhanfeng** [comment]
Rotor_z is a real_T, not a vector. It seems that it describes the height of the rotors above/below the COG of the copter rather than the directions which they point in.

**Comment by lukaszdworako** [comment]
My apologies the variable is located in MultiRotorParams.hpp and is named unit_z. It follows the XYZ plane and is going to be which direction the thrust is pointed. Again sorry about the confusion.

**Comment by sytelus** [comment]
Here is the relevant line:

https://github.com/Microsoft/AirSim/blob/master/AirLib/include/vehicles/MultiRotorParams.hpp#L130
