### ISSUE TITLE
Accuracy of simulation with higher ClockSpeed

### ISSUE THREAD

**Issue by kobymallah** [microsoft/AirSim#2930]
Hi, I'm using airsim on linux and I was wondering how increasing the ClockSpeed in the settings.json affects the accuracy of the simulator and therefore affects the data received after executing the function getMultirotorState. I need to know what is the sweet spot in which I can run the simulation with a higher ClockSpeed and the simulator will still be accurate. In addition, will running the simulation with "NoDisplay" option for ViewMode in the settings help this?

I am currently running the simulation in the blocks environment with 4 drones (will probably increase the number of drones in the future). I am using RTX 2080 and my OS is Ubuntu.

**Comment by jonyMarino** [comment]
I have created this discussion for this question: #4374
