### ISSUE TITLE
How to set a trajectory and the pitch to 15 degree at the same time when flying a multirotor.

### ISSUE THREAD

**Issue by Doris1039** [microsoft/AirSim#2941]
I‘m using Python API to control the multirotor. I have the trajectory with multiple coordinates and want to fly the multirotor with a pitch of 15 degrees. Or to set the camera pose with a pitch of 15 degrees. 

Does AirSim provide this code to do that?

Thanks in advance.

**Comment by jonyMarino** [comment]
Read the docs.
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
