### ISSUE TITLE
Save and reload exact state (location and speed) of the player

### ISSUE THREAD

**Issue by zoharri** [microsoft/AirSim#2943]
Hello,
I am trying to implement a certain motion planning algorithm for drones navigation within AirSim.
In order to implement this algorithm, I need the ability to save and load exact states of the drone (position and speed).
Is it possible to do so using AirSim python API? (obviously, the saving process is easy, but I was wondering about the reloading process)
I saw that there is an option to fly the player to a specific location, but this will not result in the wanted speed and will take time. I want to initiate the player in a particular location.

Thanks!

**Comment by jonyMarino** [comment]
simGetGroundTruthKinematics & simSetKinematics.
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
