### ISSUE TITLE
the multirotor crashed under AirSim-Drone-Racing-Lab environment

### ISSUE THREAD

**Issue by WayneHsiao0225** [microsoft/AirSim#2947]
hi, I ran the code (AirSim/PythonClient/multirotor/path.py) under AirSim-Drone-Racing-Lab( 
https://github.com/microsoft/AirSim-Drone-Racing-Lab). The map was "soccer field _easy ".
Initially, the multirotor was in the box. I pressed backspace on keyboard  to reset the position of multirotor. (picture1)
But, my problem is that the multirotor crashed before it landed.(picture 2). Would be nice if someone answer it.

Thanks you !

![start](https://user-images.githubusercontent.com/45175782/90465678-74aff080-e142-11ea-8175-f39d4b3acc9e.png)
(picture1)
![螢幕快照_2020-08-18_10-16-16](https://user-images.githubusercontent.com/45175782/90465704-7f6a8580-e142-11ea-8b9b-465aec224b8c.png)
(picture2)

os: ubuntu20.04.1
airsim 1.3.1
unreal lastest

**Comment by rajat2004** [comment]
Issue should probably be opened against that repository itself
