### ISSUE TITLE
How to get the collision point of ray-tracing ?

### ISSUE THREAD

**Issue by TomAvrech** [microsoft/AirSim#2949]
I want to get all the 3D points' locations of all the lines that start from all the pixels and hit surfaces.

What I mean by that: I have a RGB image, and for each pixel I start ray-tracing, until the rays hit surfaces, then, I want to get the 3D points of where the rays hit the surfaces.

It's like a shooter game, you shoot a gun, and I want to find out the location of where the bullet hit the wall.

How can this be done ?

Thanks.

**Comment by jonyMarino** [comment]
with the lidar sensor?

**Comment by TomAvrech** [comment]
> 
> 
> with the lidar sensor?

With a simple camera, but maybe there is a way with Lidar ?
