### ISSUE TITLE
Build Error in cpp file

### ISSUE THREAD

**Issue by smadnani** [microsoft/AirSim#2950]
<img width="1217" alt="“ps4-1” 2020-08-19 at 11 31 36 AM" src="https://user-images.githubusercontent.com/13782408/90655432-8ca17600-e20f-11ea-8930-47725e721c8b.png">

I perform the following steps to build AirSim:
git clone -b 4.24 https://github.com/EpicGames/UnrealEngine.git
cd UnrealEngine
./Setup.sh
./GenerateProjectFiles.sh
make
git clone https://github.com/Microsoft/AirSim.git
cd AirSim

Then I manually execute all steps in ./setup.sh (since I dont have root privileges) and create a build.CentOS.sh script. Get the following error on execution: 

./build.CentOS.sh 
+ debug=false
+ [[ 0 -gt 0 ]]
+ '[' '!' -d ./external/rpclib/rpclib-2.2.1 ']'
+ '[' -d ./cmake_build ']'
++ which cmake
+ CMAKE=/usr/bin/cmake
+ false
+ build_dir=build_release
++ uname
+ '[' Linux == Darwin ']'
+ export CC=gcc
+ CC=gcc
+ export CXX=g++
+ CXX=g++
+ [[ -d ./AirLib/deps/eigen3/Eigen ]]
+ echo 'putting build in build_release folder, to clean, just delete the directory...'
putting build in build_release folder, to clean, just delete the directory...
+ [[ -f ./cmake/CMakeCache.txt ]]
+ [[ -d ./cmake/CMakeFiles ]]
+ folder_name=
+ [[ ! -d build_release ]]
+ pushd build_release
++ nproc
+ make -j24
[ 42%] Built target MavLinkCom
[ 48%] Built target MavLinkTest
[ 69%] Built target rpc
[ 85%] Built target AirLib
[ 88%] Built target DroneServer
[ 92%] Building CXX object DroneShell/CMakeFiles/DroneShell.dir/data/users/smadnani/AN/AirSim/AirSim/DroneShell/src/main.cpp.o
[ 92%] Built target HelloDrone
[ 95%] Built target AirLibUnitTests
[ 98%] Built target HelloCar
In file included from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/stl_iterator.h:66:0,
                 from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/stl_algobase.h:67,
                 from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/char_traits.h:39,
                 from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/ios:40,
                 from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/ostream:38,
                 from /cm/local/apps/gcc/7.2.0/include/c++/7.2.0/iostream:39,
                 from /data/users/smadnani/AN/AirSim/AirSim/DroneShell/src/main.cpp:4:
/cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/ptr_traits.h: In substitution of ‘template<class _Tp> template<class _Up> using rebind = _Up* [with _Up = msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&; _Tp = std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>, true>]’:
/cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/ptr_traits.h:147:77:   required by substitution of ‘template<class _Ptr, class _Tp> using __ptr_rebind = typename std::pointer_traits::rebind<_Tp> [with _Ptr = std::allocator_traits<std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>, true> > >::pointer; _Tp = msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&]’
/cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/node_handle.h:203:69:   required by substitution of ‘template<class _Key, class _Value, class _NodeAlloc> template<class _Tp> using __pointer = std::__ptr_rebind<typename std::allocator_traits<_NodeAlloc>::pointer, _Tp> [with _Tp = std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>::second_type; _Key = std::__cxx11::basic_string<char>; _Value = std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>, true> >]’
/cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/node_handle.h:206:60:   required from ‘class std::_Node_handle<std::__cxx11::basic_string<char>, std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>, std::allocator<std::__detail::_Hash_node<std::pair<const std::__cxx11::basic_string<char>, msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&>, true> > >’
/data/users/smadnani/AN/AirSim/AirSim/DroneShell/include/SimpleShell.hpp:421:9:   required from ‘void msr::airlib::SimpleShell<ExecContext>::addCommand(msr::airlib::SimpleShell<ExecContext>::ShellCommand&) [with ExecContext = msr::airlib::CommandContext]’
/data/users/smadnani/AN/AirSim/AirSim/DroneShell/src/main.cpp:1425:25:   required from here
/cm/local/apps/gcc/7.2.0/include/c++/7.2.0/bits/ptr_traits.h:133:28: error: forming pointer to reference type ‘msr::airlib::SimpleShell<msr::airlib::CommandContext>::ShellCommand&’
         using rebind = _Up*;
                            ^
make[2]: *** [DroneShell/CMakeFiles/DroneShell.dir/data/users/smadnani/AN/AirSim/AirSim/DroneShell/src/main.cpp.o] Error 1
make[1]: *** [DroneShell/CMakeFiles/DroneShell.dir/all] Error 2
make: *** [all] Error 2

**Comment by rajat2004** [comment]
AirSim uses `clang-8` as the compiler, not `gcc`. If you don't have root access, you could probably download Clang binaries and replace `clang-8`, etc with the location of the downloaded binaries in `build.sh`
