### ISSUE TITLE
Orientation and position of Lidar/Camera attached to the Car

### ISSUE THREAD

**Issue by thejeshk** [microsoft/AirSim#2951]
Hello AirSim Community, 

Can we change the orientation and position of the Lidar sensor or Camera attached to the Vehicle (Car)

Thank you 
TK

**Comment by rajat2004** [comment]
See the documentation - https://microsoft.github.io/AirSim/lidar/, https://microsoft.github.io/AirSim/settings/
They both take X,Y,Z & Roll,Pitch,Yaw as parameters in settings

**Comment by riyadfebrian** [comment]
is there any explanation to set X, Y, Z for dummies ?

**Comment by jonyMarino** [comment]
Hi Riyad! read the docs please: https://microsoft.github.io/AirSim/lidar.html#lidar-configuration

**Comment by riyadfebrian** [comment]
Thanks, Mr. JonyMarino. but what I mean is basic knowledge about X Y Z in 3d Environment AirSim. I know its out of coverage documentation, but if the documentation has some reference about it, I think it'll very useful especially for beginners.

or is there any example setting up position of sensor ? 

i.e distance sensor in right side of vehicle , set X=0, Y=1, Z=-1

**Comment by jonyMarino** [comment]
We use NED always:
https://microsoft.github.io/AirSim/apis.html#coordinate-system
