### ISSUE TITLE
how to use stereo camera?

### ISSUE THREAD

**Issue by lahyeon** [Microsoft/AirSim#296]
I want to use stereo camera with quadcopter.
where is setting stereo camera or multiple camera?
@lovettchris   I will appreciate your help

**Comment by sytelus** [comment]
There are two cameras on FlyingPawn mesh. However currently only one of them is active and used and available through APIs. In near future, we will enable both of these cameras.

**Comment by lahyeon** [comment]
Thanks for the answer. I hope that the stereo camera api will be supported soon.
