### ISSUE TITLE
How to run AirSim docker image headless?

### ISSUE THREAD

**Issue by jeffreyng99** [microsoft/AirSim#2966]
How do I start the simulation in headless mode within docker container? I follow these instructions at https://microsoft.github.io/AirSim/docker_ubuntu/#build-unreal-engine-inside-docker line for line up until "Start unreal engine inside the container:
ue4@HOSTMACHINE:~$ /home/ue4/UnrealEngine/Engine/Binaries/Linux/UE4Editor"

When running without the -- headless flag, the editor opens up, and I'm able to start the simulator normally. However, with the flag enabled, the logs just stops at:

...
[2020.08.24-21.57.28:756][546]LogShaderCompilers: Display: Shaders left to compile 14
[2020.08.24-21.57.29:003][570]LogShaderCompilers: Display: Shaders left to compile 4
[2020.08.24-21.57.33:372][ 73]LogRenderer: Reallocating scene render targets to support 128x128 Format 10 NumSamples 1 (Frame:0).

I suspect that the simulator is not started yet because when trying to running a python script in the same container I get an RPC error. This happens normally when the simulator is not started yet meaning the RPC server is not started as well.
```docker exec -it "container_id" bash``` 

Do I fix this by configuring the settings.json to start automatically? Has anyone successfully ran UE4Editor in headless mode? Thanks in advance.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
