### ISSUE TITLE
how to set airsim start point in unreal engine and get pose of drone in unreal engine

### ISSUE THREAD

**Issue by lucafei** [microsoft/AirSim#2968]
my configuration: windows 10, unreal engine 4.24, airsim 1.3, Multirotor mode

i want to get the start pose of drone in unreal engine, sothat i can tranform the coordinate of ue into NED of airsim, moreover i want to set the start pose of drone, with which the PlayerStart is placed, sothat i can customly define the home position of drone not the default home position consistent with PlayerStart. Do you know how to achieve this, because the API simgetpose and simsetpose only are used for computervision mode as i known. 
Thank you in advance

**Comment by Aku02** [comment]
You can take a look at `settings.json` file [here](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md) this file in default is found in `C:\Users\Admin\Documents\AirSim` 
Once you have set the positions you can restart your engine and proceed.
Hope this helps
