### ISSUE TITLE
GPS Accuracy

### ISSUE THREAD

**Issue by petergerten** [Microsoft/AirSim#297]
What kind of accuracy can I expect from the simulated GPS? Does it behave with similar error like a consumer GPS receiver?

**Comment by sytelus** [comment]
It has simulated initial time delay but afterwards it acts like perfect GPS. We haven't yet implemented adding ray tracing to simulate accuracy changes.

**Comment by petergerten** [comment]
Ok, while ray tracing to simulate accuracy changes sounds awesome, it is probably overkill for a lot of use cases. I am more interested in some simple "random" error so that I do not have perfect accuracy and can test visual odometry solutions (fused with GPS).
