### ISSUE TITLE
How to control one car1 with steering and have another car2 move in a definite path

### ISSUE THREAD

**Issue by Josepharol** [microsoft/AirSim#2973]
Question : I am using the blocks environment. I already have a car1 like the in built one where I can access it using the [G920](https://microsoft.github.io/AirSim/steering_wheel_installation/) Steering wheel. Now, I would like to add another car2 in the blocks environment. Adding another car2 by making changes from [this](https://microsoft.github.io/AirSim/multi_vehicle/) works. But the steering input is reflected on both cars-car1 & car2. I would like to have a car2 which can be programmed to travel in a specific path. So that, I can drive the car1 controlled by steering and record it's response to the other car2's behavior. I am currently trying to add a spline in unreal and move the car2 along a specific path. I would like to know if there is an alternate way of creating one path following car2 with just coding instead of creating spline paths on unreal engine. Any help would be appreciated. Thanks

: I am using airsim 1.2 on unreal 4.24 with python 3.7 on Windows 10

@lovettchris

**Comment by sbyebss** [comment]
I am also curious about what you are wondering

> I am currently trying to add a spline in unreal and move the car2 along a specific path. I would like to know if there is an alternate way of creating one path following car2 with just coding instead of creating spline paths on unreal engine. 

From what I found, there is carrot algorithm for the multirotor to follow specific positions in AirSim API. And it doesn't provide car actor version.

Then vehicle has this algorithm to help driving autonomously but I guess it requires much time training. https://github.com/microsoft/AirSim/tree/master/PythonClient/imitation_learning

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
