### ISSUE TITLE
Incorrect FOV in simGetCameraInfo call

### ISSUE THREAD

**Issue by clintlombard** [microsoft/AirSim#2977]
Using the Python API, changing the `FOV_Degrees` field in `settings.json` or using `simSetCameraFov()` to set a cameras FOV works. However, when querying the camera information with `simGetCameraInfo()`, it always returns a `CameraInfo.fov = 90`. Could this be incorrectly reporting the vertical FOV, or is it not being updated with the new horizontal FOV changes?

Python: 3.6.9
AirSim Plugin: commit bd8ee6be4183c28d402e4c34cce114312da46358 (latest on master at the time)
AirSim Python API: 1.2.8
UE: 4.25.3 (also tested in 4.24.3)
OS: Ubuntu 18.04 (docker container)

**Comment by VC86** [comment]
I confirm the issue on 
Python 3.6
AirSim built on Windows from latest master commit: bd8ee6be4183c28d402e4c34cce114312da46358
UE: 4.24.3
OS: Windows 10

**Comment by MoBaT** [comment]
Also seeing this issue on:

AirSim Plugin: commit f36efa6f3ed0b496cc8f551f2b20349d164f51bb
UE: 4.25.3
OS: Ubuntu 18.04

**Comment by rajat2004** [comment]
Will be great if someone can test #3278 and see if it fixes the problem

**Comment by desireB** [comment]
Hi Clint,

Would you mind sharing your settings.json ?

Thank you.

**Comment by rajat2004** [comment]
@desireB #3573 might be useful for some examples of settings

**Comment by desireB** [comment]
Thanks, @rajat2004 !

**Comment by Shromm-Gaind** [comment]
I posted this issue on unrealcv, however, I am not sure if it is maintained or checked. Can someone please explain to me which format of the projection matrix does AirSim generate? Currently, I am getting;  
[   0.0, 1.0,  0.0,   0.0],
[   0.0, 0.0, -1.8,   0.0],
[   0.0, 0.0,  0.0, 10.0],
[  -1.0, 0.0,  0.0,   0.0]
But I am not sure about this...It seems wrong. I was expecting to get;
![image](https://user-images.githubusercontent.com/55825273/207054783-eccc872d-7ceb-4093-b3f3-91188ad6863b.png)
