### ISSUE TITLE
Header filename typo

### ISSUE THREAD

**Issue by BossKwei** [Microsoft/AirSim#298]
[`https://github.com/Microsoft/AirSim/blob/master/AirLib/include/controllers/simple_flight/SimpleFlightDroneController.hpp#L16`](https://github.com/Microsoft/AirSim/blob/master/AirLib/include/controllers/simple_flight/SimpleFlightDroneController.hpp#L16)

Please change 'firmware.hpp' to 'Firmware.hpp', which cause 'File not found' on Linux.

Thanks

**Comment by sytelus** [comment]
Thanks for catching this. I've committed this change.
