### ISSUE TITLE
Neighborhood Sim Minimizes Off-Focus

### ISSUE THREAD

**Issue by DamianRivas** [microsoft/AirSim#2987]
OS: Ubuntu 20.04
Release: Neighborhood v1.3.1

To reproduce the issue:
1. Run the neighborhoods.sh sim
2. Click on another window to go out of focus
3. The simulation "minimizes" or hides from view.

I am running the Neighborhood Simulation on a multi-monitor setup and I can't work on anything and view the simulation at the same time because the window minimizes every time it goes off focus. Is there a way to prevent this behavior?

There doesn't seem to be any other open nor closed issues on this.

**Comment by rajat2004** [comment]
Not exactly sure what's happening, maybe a quirk of multi-monitor? If you are running the binary with the `-windowed` argument, maybe try without it.
Is something like below what you're looking for?
![Screenshot from 2020-08-29 21-59-29](https://user-images.githubusercontent.com/37938604/91641565-e4778280-ea42-11ea-8c25-2643370b2e51.png)

**Comment by DamianRivas** [comment]
Hmm actually I'm not using the `-windowed` argument and perhaps that's what I need. I'll give that a try and see how it goes.

**Comment by DamianRivas** [comment]
Forgot to report back but running the sim in windowed mode prevents the behavior. Good enough for me!
