### ISSUE TITLE
Question: What are the columns in the text file that is generated after clicking "rec" in Airsim?

### ISSUE THREAD

**Issue by vatsagandhi** [Microsoft/AirSim#299]
We are curious as to what the columns in the text file airsim_rec represent.

**Comment by saihv** [comment]
See https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/RecordingThread.cpp#L73.

The columns contain timestamp, position and orientation of the drone.

**Comment by vatsagandhi** [comment]
Thank you for the quick response

**Comment by vatsagandhi** [comment]
Sorry is there a way to reduce the frequency of the recording thread and add for ex. lat,lon,alt into the text file as well?

**Comment by saihv** [comment]
I haven't tried it, but it should be possible. AirLib has the method [getGpsLocation()](https://github.com/Microsoft/AirSim/blob/681b79d6946fdb5be141e835915c42f9b0bfbf47/AirLib/include/controllers/DroneControllerCancelable.hpp#L212) that might be useful to you: although invoking this from the recording thread might mean you'll have to figure out the right call namespace-wise etc. Perhaps the devs can give a better response

**Comment by vatsagandhi** [comment]
Thank you
