### ISSUE TITLE
How to Connect Linux PC which runs AirSim server with ROS wrapper with WIndows PC (AirSin Client)

### ISSUE THREAD

**Issue by thejeshk** [microsoft/AirSim#2997]
Hello AirSim COmmunity, 

I've seen docs/issues talking about running a simulation on Windows and running Python API on a Linux machine.

1. The documentation say that the ROS Wrapper is built on the C++ API provided by the client. That way could I even connect from Windows to ROS on Nvidia Jetson. Or ROS running on VMware(Linux)

Or 

2. Just to check, in theory, to connect between the two, I do the following:

On Windows, running Python API, set the IP address of the rendering machine (Linux)
On Linux, running Unreal/Airsim with ROS wrapper, specify the IP address of the rendering machine (so itself) in settings.json in the LocalHostIP field

Is there anything else that needs to be done?

Please let me know how can I achieve the connection between two

**Comment by nabeelsherazi** [comment]
This sounds right. You may want to specify a static IP connection on your router so that the IP of the server machine does not change unexpectedly.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
