### ISSUE TITLE
Bug: Plotting using simPlotPoints (and simPlotLineList) places the points in wrong positions

### ISSUE THREAD

**Issue by TomAvrech** [microsoft/AirSim#2999]
Delete please

**Comment by TomAvrech** [comment]
And K_Inv is given:
<img width="629" alt="Annotation 2020-09-03 162612" src="https://user-images.githubusercontent.com/19329110/92120873-426ce700-ee02-11ea-841c-f21c3088fdf6.png">

**Comment by RoyAmoyal** [comment]
I actually have the same problem.. In unreal I visualize an item at x,y,z location. when I try to plot something next to it using the simPlotPoints,simPlotLines etc, it plot them in other location.. 

What am I missing?

thanks
