### ISSUE TITLE
How to expose GeoLocation to blueprint?

### ISSUE THREAD

**Issue by Maxilos** [microsoft/AirSim#3003]
OS: Windows 10;
Airsim version: 1.3.1
UE4 version: 4.24.3
I'd want to be able to expose lat,lon,alt to blueprint, but am not sure, how to get a reference to them in AirBlupprintLib.cpp, would really appreciate if someone would point me in the right direction.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
