### ISSUE TITLE
Cannot connect to PX4

### ISSUE THREAD

**Issue by BreederBai** [microsoft/AirSim#3016]
airsim version: 1.3.1
OS version: windows 10 2004
UE version: 4.24.3

![image](https://user-images.githubusercontent.com/27894314/92990793-e137c880-f511-11ea-9103-d29cccfe13b3.png)

**Comment by clintlombard** [comment]
Which version of PX4 are you running? The latest release `v1.11.0` does not work with AirSim yet, try `v1.10.2`. Possibly related #2477.

**Comment by jonyMarino** [comment]
Please continue in #2477. Regards
