### ISSUE TITLE
Quadrotor model glitch

### ISSUE THREAD

**Issue by agentfeux** [microsoft/AirSim#3017]
Hi,
I'm getting wierd texture glitch after a while when training. The rotor just move from their initial position like this:
![Screenshot from 2020-09-12 15-14-09](https://user-images.githubusercontent.com/40972980/93003304-7e433300-f50b-11ea-90ed-4933a1bdf66c.png)
![dronewierd](https://user-images.githubusercontent.com/40972980/93003317-a6cb2d00-f50b-11ea-9f43-a64150067f82.png)

When training, after each episode i am mostly using `client.reset()` and `client.simSetVehiclePose(pose,False)` from the API.

**Comment by jonyMarino** [comment]
Hi, this is a dup. of #784. Thank you for the feedback
