### ISSUE TITLE
What is the unit of magnetometer and gyroscope?

### ISSUE THREAD

**Issue by swapnilsayansaha** [microsoft/AirSim#3022]
Could some tell me the units of the values returned by the magnetometer (e.g. nT, uT, gauss etc.) and gyroscope (part of IMU) (e.g. d/s, r/s, rpm etc.)?

**Comment by xxEoD2242** [comment]
For the magnetometer, the units are Gauss.

<img width="578" alt="Screen Shot 2020-09-16 at 7 01 08 AM" src="https://user-images.githubusercontent.com/32143517/93328973-7f65b000-f7ea-11ea-9bd9-9dfc8ea6aa3b.png">

That's in [MagnetometerBase.hpp](https://github.com/microsoft/AirSim/blob/18b36c7e3ea3d1e705c3938a7b8462d44bd81297/AirLib/include/sensors/magnetometer/MagnetometerBase.hpp)

For the gyro, the units are radians/sec, which are the SI unit for angular velocity. Couldn't find it in the code.

**Comment by swapnilsayansaha** [comment]
Thanks.
