### ISSUE TITLE
Cannot figure out the right subwindow setting(settings.json) for multiple drones equipped with camera

### ISSUE THREAD

**Issue by skykim0609** [microsoft/AirSim#3026]
Hello. I am currently using AirSim 1.3 with Unreal 4.24 in Ubuntu 18.04 LTS version. I am trying to control 3 quadrotors in AirSim, and view the camera outputs through the subwindow. Following is the current settings.json file.

## 
{
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "Vehicles": {
      "Drone_1": {
          "VehicleType": "SimpleFlight",    
          "DefaultVehicleState":"Armed",        
          "X": 10, "Y":10.0, "Z":-20,
          "Yaw":0,
    "Cameras": {
              "camera1": {
                "CaptureSettings": [
                  {
                    "PublishToRos": 1,
                    "ImageType": 0,
                    "Width": 640,
                    "Height": 480,
                    "FOV_Degrees": 86,
                    "TargetGamma": 1.5
                  }
                ],
                "X": 0.50, "Y": 0, "Z": -0.10, 
                "Pitch": 0, "Roll": 0, "Yaw": 180
              }
          }
        },
"Drone_2": {
          "VehicleType": "SimpleFlight",  
          "DefaultVehicleState":"Armed",          
          "X": 20, "Y":10.0, "Z":-20,
          "Yaw":0,
    "Cameras": {
              "camera2": {
                "CaptureSettings": [
                  {
                    "PublishToRos": 1,
                    "ImageType": 0,
                    "Width": 640,
                    "Height": 480,
                    "FOV_Degrees": 86,
                    "TargetGamma": 1.5
                  }
                ],
                "X": 0.50, "Y": 0, "Z": -0.10, 
                "Pitch": 0, "Roll": 0, "Yaw": 180
              }
          }
        },
"Drone_3": {
          "VehicleType": "SimpleFlight",      
          "DefaultVehicleState":"Armed",    
          "X": 35, "Y":10.0, "Z":-20,
          "Yaw":0,
    "Cameras": {
              "camera3": {
                "CaptureSettings": [
                  {
                    "PublishToRos": 1,
                    "ImageType": 0,
                    "Width": 640,
                    "Height": 480,
                    "FOV_Degrees": 86,
                    "TargetGamma": 1.5
                  }
                ],
                "X": 0.50, "Y": 0, "Z": -0.10, 
                "Pitch": 0, "Roll": 0, "Yaw": 180
            }
      }
    }
},
"SubWindows": [
      {"WindowID": 0, "ImageType": 0, "CameraName": "camera1", "VehicleName": "Drone_1", "Visible": true},
      {"WindowID": 1, "ImageType": 0, "CameraName": "camera2", "VehicleName": "Drone_2", "Visible": true},
      {"WindowID": 2, "ImageType": 0, "CameraName": "camera3", "VehicleName": "Drone_3", "Visible": true}
    ]
}

##

I played this setting in the default given "blocks" environment. Following screenshot is the result.
![image](https://user-images.githubusercontent.com/45422505/93496696-81468500-f94a-11ea-875b-35aa56efc922.png)

The later 2 images displayed on the subwindows 1, 2 are apparently not the image from cameras on drone_2, drone_3.
I get "CameraID in <SubWindows> element in settings.json is invalid" error message, but I cannot figure out what is wrong with this setting.
Is there any way to fix this error?

**Comment by rajat2004** [comment]
Probably should have added this in the docs, but the `VehicleName` element in the Subwindow settings is only there in master right now, and not in the latest release binaries

**Comment by skykim0609** [comment]
> Probably should have added this in the docs, but the `VehicleName` element in the Subwindow settings is only there in master right now, and not in the latest release binaries

Thank you for reply. So for now, there isn't any way of displaying camera views from multiple drones in subwindows, right?

**Comment by rajat2004** [comment]
Yup, not without building AirSim from source atleast. If needed, you could build binaries yourself after that

**Comment by skykim0609** [comment]
I don't know what it takes to build my binaries so I'd rather consider other ways to deal with this problem. Thank you anyway.
