### ISSUE TITLE
Propeller physics - simulation of thrust/lift?

### ISSUE THREAD

**Issue by lkoelman** [microsoft/AirSim#3044]
I am trying to find out how the propellor rotation is linked to the drone's movement/kinematics inside the Unreal engine.

It's not clear for me from the code (MultiRotor cpp classes) and BP_FlyingPawn blueprint how the propellor thrust vectors are passed on to the unreal engine. I see some code related to the calculation and storage of thrust/kinematic parameters in the following classes:

- MultiRotorPawnSimApi
- MultiRotorParams.hpp
- RotorActuator.hpp

However, I can't find the 'communication stage' between the internal physics model and the unreal engine. Or could it be that thrust is calculated through Unreal physics simulation based on the movement of the realistically shaped propellors?

**Comment by rajat2004** [comment]
AFAIK, the Unreal Engine copter model isn't associated with the physics, the model is used for the rendering of the copter, props, etc but the physics is all handled inside FastPhysicsEngine only.
In Car vehicle, the physics is handled inside UE using PhysX

**Comment by EdwinMeriaux** [comment]
@rajat2004 
So when designing our own custom drone is there anything to modify in the FastPhysicsEngine?
