### ISSUE TITLE
Error at startup: VehicleSetting for vehicle name BP_FlyingPawn_5 was requested but not found

### ISSUE THREAD

**Issue by PeterParkerLogic** [microsoft/AirSim#3050]
I followed the tutorial ( 9:27 in https://www.youtube.com/watch?v=1oY8Qu5maQQ&feature=youtu.be) to create a drone by myself. 
But it turned out "Error at startup: VehicleSetting for vehicle name BP_FlyingPawn_5 was requested but not found".
I followed the method below, but it still not works.
https://www.gitmemory.com/issue/Microsoft/AirSim/1506/489733160

Please help me, Thanks

**Comment by jonyMarino** [comment]
Hi! Do you get that error when tapping on play? My problem with that video is that I don't see that parameters on my Details menu

**Comment by PeterParkerLogic** [comment]
Yes, I got this error, "VehicleSetting for vehicle name BP_FlyingPawn_5 was requested but not found", when I tapped on play.

**Comment by jonyMarino** [comment]
I confirm this is happening on master (d59ceb7)

**Comment by jonyMarino** [comment]
This PR #3146 fixed this issue!
