### ISSUE TITLE
AirSim build failed

### ISSUE THREAD

**Issue by bridambuwir** [microsoft/AirSim#3054]
I tried installing AirSim on windows 10 following the steps in https://microsoft.github.io/AirSim/build_windows/ . I succesfully installed unreal engine, installed visual studio 2019. However, when i run build.cmd, i get the error below:

**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.7.5
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community>d:

D:\>cd AirSim

D:\AirSim>build.cmd
'where' is not recognized as an internal or external command,
operable program or batch file.
cmake was not found in path.
Press any key to download and install cmake (make sure to add it in path in install options)
'msiexec.exe' is not recognized as an internal or external command,
operable program or batch file.
'where' is not recognized as an internal or external command,
operable program or batch file.
cmake was not found in path.
Press any key to download and install cmake (make sure to add it in path in install options)
'msiexec.exe' is not recognized as an internal or external command,
operable program or batch file.

ERROR: cmake was not installed correctly, we tried.

#### Build failed - see messages above.

![desktop_development_with_c++_installed](https://user-images.githubusercontent.com/68272502/94845978-bf4ea900-0420-11eb-9a3d-3fcc63e7c1cf.PNG)
![error](https://user-images.githubusercontent.com/68272502/94845982-c07fd600-0420-11eb-8f99-4c342fa6b475.PNG)

I have uninstalled and installed visual studio, and restarted pc multiple times but not able to solve this issue.

Thank you for your assistance.

**Comment by jonyMarino** [comment]
Hi! From the errors it seems that you have to add C:\WINDOWS\SYSTEM32 to the PATH env in windows.
tell me how it was!

**Comment by lucafei** [comment]
you should run command build.cmd in Developer Command Prompt for VS 2019. Did you try this?

**Comment by bridambuwir** [comment]
> Hi! From the errors it seems that you have to add C:\WINDOWS\SYSTEM32 to the PATH env in windows.
> tell me how it went!

Thank you! This was indeed the issue. All sorted now.
