### ISSUE TITLE
server couldn't find function 'simSetCameraPose' with argument count 3

### ISSUE THREAD

**Issue by lucafei** [microsoft/AirSim#3059]
hello, i met a problem at calling function simSetCameraPose. the error can be seen in following:

![error at running gettraindata](https://user-images.githubusercontent.com/29920326/95085754-ef978f80-071f-11eb-85bb-237753c6efa4.PNG)

ii have already checked the function simSetCameraPose is right and i built airsim in latest version. Do you know where is the problem? Thank you in advance.

**Comment by ningzian** [comment]
I have got the same problem, and solved it by update airsim. You can try with https://microsoft.github.io/AirSim/unreal_custenv/#updating-your-environment-to-latest-version-of-airsim

**Comment by jonyMarino** [comment]
@lucafei, can we close this?

**Comment by lucafei** [comment]
yes, i closed this issue
