### ISSUE TITLE
DroneShell

### ISSUE THREAD

**Issue by eanmikale** [Microsoft/AirSim#306]
When conducting missions, the input works fine, but after a few seconds the simulator reads "Fail Safe Mode Enabled," and "Fail Safe Mode No Offboard Control". How do we keep the simulator from going into this fail safe mode so that the quad completes the mission? Thanks again.

**Comment by FabianKratzer** [comment]
set the following parameters in the PX4-console:
**param set NAV_RCL_ACT 0
param set NAV_DLL_ACT 0**
see:
https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md
other usefull params, see:
https://github.com/Microsoft/AirSim/blob/master/docs/px4.md
