### ISSUE TITLE
vibration of multirotor happend at flying

### ISSUE THREAD

**Issue by lucafei** [microsoft/AirSim#3063]
hello, guys, i met a problem at flying multirotor. When i set a goal position to multirotor and run the airsim to fly. The multirotor will begin to vibrate at flying. This cause finally in programm stopping. I recorded this case and you can clearly see the problem in following
![vibration at running airsim2](https://user-images.githubusercontent.com/29920326/95316841-9dc44600-0894-11eb-8b3e-8e80351e0a03.gif)
does anyone have some ideas for this, how to fix this or it is a issues in airsim?

**Comment by jonyMarino** [comment]
Thank you @lucafei for the record. dup of #1394?
