### ISSUE TITLE
City environment, where are these moving vehicles?

### ISSUE THREAD

**Issue by Kacper777777** [microsoft/AirSim#3066]
I downloaded binaries for "City" environment for AirSim from here https://github.com/Microsoft/AirSim/releases and I am able to run this. But in the city there are no moving vehicles. I want to collect data while driving in the city where there is some traffic. But there is no traffic. And when I press F1 to see help I can only see some options to change weather and cameras.

**Comment by Kacper777777** [comment]
There are no vehicles in the newest 1.3.1 version

**Comment by nightduck** [comment]
Nor in 1.4.0. Duplicate of #3267. (Or rather, that is a duplicate of this, but this is closed)
