### ISSUE TITLE
I want to use stereo camera!

### ISSUE THREAD

**Issue by fhggty2005** [Microsoft/AirSim#307]
When exactly will the stereo camera API be implemented?
Can I create a stereo camera with the currently implemented API?

**Comment by sytelus** [comment]
I've added new APIs that answers 3 out of 4 questions :). The API simGetImages() allows you to get left, right and depth images simultaneously. The API return value is a struct that contains camera position, orientation and time stamp. [This code](https://github.com/Microsoft/AirSim/blob/master/Examples/StereoImageGenerator.hpp) has example of doing many of this things.
