### ISSUE TITLE
PX4 v1.11.1 don't work with AirSim

### ISSUE THREAD

**Issue by EivindYN** [microsoft/AirSim#3076]
How to reproduce:
* Clone PX4/Firmware tag v1.11.1 (9fcbf18)
* Clone Microsoft/AirSim v1.3.1 (d59ceb7)
* Go to the Firmware folder and run "make px4_sitl_default none_iris"
* Change your Documents/settings.json to:
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor",
  "Vehicles": {
    "PX4": {
      "VehicleType": "PX4Multirotor",
      "UseSerial": false,
      "UseTcp": true,
      "TcpPort": 4560,
      "ControlPort": 14580
    }
  }
}
```
* Go to AirSim/Unreal/Environment/Blocks and then:
  * Run update_from_git.bat
  * Run GenerateProjectFiles.bat
  * Open Blocks.sln and set Blocks as startup project, and click Play
  * Click Play in Unreal
* Open QGroundControl. The drone will be able to arm, but taking off is impossible.

Some "Accel #0 fail: TIMEOUT!" pops out in the terminal and in Airsim this occurs:
![image](https://user-images.githubusercontent.com/31821339/95734679-13108c00-0c84-11eb-8ded-cb43ee911bb4.png)

I tested it with v1.11.0 too, and that did not work either.

**Comment by jonyMarino** [comment]
Thank you for your detailed post. We are dealing with this here: https://github.com/microsoft/AirSim/issues/2477#issuecomment-688772216
please continue there!
