### ISSUE TITLE
Understanding AirLib S/W Architecture

### ISSUE THREAD

**Issue by vaasudEva** [Microsoft/AirSim#308]
Dear AirSim team, this is not an issue as such; rather I am curious to know about design of AirLib.
I've few questions about the same. Please correct me if I am wrong.

DroneServer does below things:
- Creates a Mavlink drone controller instance and leverages its services to cater Apps like HelloDrone
- Hosts RpLibServer for providing Drone services.

HelloDrone app makes requests via RpcClient interface to DroneServer and waits for response.

- What's the fundamental reason behind having DroneServer ? Why not HelloDrone use AirLib interface which connects directly to Vehicle ? Is this done to have a common local server for multiple apps that use AirLib ?
- If my client want to control both Mavlink and Non-Mavlink vehicles, do I have to spawn multiple instances of DroneServer ? Or how is it?

Please share your thoughts. :)
Thank you.

**Comment by sytelus** [comment]
The idea is that you should be able to run your code that uses AirSim APIs in simulator as well as real-world without any changes. The only way to talk to AirSim from outside is via RPC APIs The DroneServer can be deployed on on-board computer and can expose same RPC APIs. So your client code works without change against simulator or actual drone. 

Yes, we need to modify DroneServer so it works for any drone. This is in our TODO list..
