### ISSUE TITLE
Missing PATH_TO/AirSim/ros/devel 

### ISSUE THREAD

**Issue by yx0123** [microsoft/AirSim#3090]
I'm following the AirSim ROS tutorial https://microsoft.github.io/AirSim/airsim_ros_pkgs/. After running `catkin build -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8` , there is no PATH_TO/AirSim/ros/devel  directory generated and thus I am unable to proceed with the next step `source devel/setup.bash`. What am I doing wrong?

**Comment by GimpelZhang** [comment]
What's the output of your "catkin build" command? 

And have you tried the "catkin_make" instead?

**Comment by yx0123** [comment]
Fixed after doing catkin clean and rebuilding
