### ISSUE TITLE
where can we find function: "commandRollPitchYawrateThrottle()"

### ISSUE THREAD

**Issue by Handsome-cp** [microsoft/AirSim#3096]
where can we find function: "commandRollPitchYawrateThrottle()" used in AirLib abount multirotor API, thank you!

**Comment by jonyMarino** [comment]
I'm not sure what you are looking for. Different firmwares/controls implement that method. You can find them with a search here in GitHub. But if what you want is to call that method, that is done through the moveByRollPitchYawrateThrottleAsync() API method.
