### ISSUE TITLE
how to set the color of segmentation image

### ISSUE THREAD

**Issue by lucafei** [microsoft/AirSim#3099]
i want to get and set the color of segmentation image. Do you know how to set the color of segmentation parts and get the color of  segmentation, because now the image api don't provide function to deal with this. It seems like the color to segmenation is random selected.

**Comment by GimpelZhang** [comment]
Haven't tried, but it seems that there is a part in the introduction document about this:

[Segmentation](https://microsoft.github.io/AirSim/image_apis/#segmentation)

**Comment by jonyMarino** [comment]
Hi @lucafei! do you think that the color assigned by seg_rgbs.txt is not enough? (I know you've posted an issue about that)

**Comment by lucafei** [comment]
> Hi @lucafei! do you think that the color assigned by seg_rgbs.txt is not enough? (I know you've posted an issue about that)

you can get and set segmentation color using https://github.com/microsoft/AirSim/blob/d59ceb7f63878f5e087ea802d603ba0fd282ff56/PythonClient/airsim/client.py#L425
and https://github.com/microsoft/AirSim/blob/d59ceb7f63878f5e087ea802d603ba0fd282ff56/PythonClient/airsim/client.py#L443. 
but you have to download the lastest version of airsim. Although it works to set and get the segmenation color, it has problem at  outputing color. I find when i get the output segementation image, this image has different color from what you get or set using API, which even doesn't exit in seg_rgbs.txt.

**Comment by jonyMarino** [comment]
Thanks for your explanation.
So let's continue with #3103 alone.
