### ISSUE TITLE
EKF baro hgt timeout in SITL

### ISSUE THREAD

**Issue by RodgerLuo** [Microsoft/AirSim#310]
I was trying to set the Unreal with SITL, and I got this warning message below after I started PX4: 

![image](https://user-images.githubusercontent.com/10570608/27713752-fb8c1b3a-5ce1-11e7-93c4-9555e18bab7d.png)

The DroneShell could not return GPS information. And I set the longitude and latitude information as suggested:

![image](https://user-images.githubusercontent.com/10570608/27713817-4b9f8b20-5ce2-11e7-90bd-cbe451c8e27c.png)

And my settings.json is as below:

![image](https://user-images.githubusercontent.com/10570608/27713835-6471c28a-5ce2-11e7-96ac-bd7db4f1c9e0.png)

Please let me know what might be the reason to cause this warning. Thank you!

**Comment by FabianKratzer** [comment]
Hi,
I ran into the EKF BARO HGT problem, too.
Without the correct altitude only manual control works properly.

PX4 SITL output:
![error_hgt_timeout2](https://user-images.githubusercontent.com/6681643/27867873-4039dafc-619b-11e7-9021-2858470dbe34.png)

In HIL-mode UE4 reports takeoff, freefall, landing, too.

settings.json:
![settings](https://user-images.githubusercontent.com/6681643/27867886-49322ba0-619b-11e7-8e44-3bd42390a4d8.png)

In older versions of AirSim and PX4 firmware the problem didn't occur.
So I think that recent changes, may on PX4 side, cause this problem.
(see: https://github.com/PX4/Firmware/commits/master)

Another question to the position:
Why is it important to set the PlayerStart to a specific position?
(see: https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md)
...I can't feel any difference setting the PlayerStart somewhere else...

**Comment by sytelus** [comment]
PX4 firmware after release 1.5.5 has issue. See https://github.com/Microsoft/AirSim/issues/316#issuecomment-313218436.
