### ISSUE TITLE
Question : I wanna get energy consumption

### ISSUE THREAD

**Issue by 4iue0** [microsoft/AirSim#3107]
https://github.com/srivatsankrishnan/AirSim-1

I found it to get energy consumption in 'getTripStats()'.
But I cannot execute hello_drone.py with this error code.

WARNING:tornado.general:Connect error on fd 320: WSAETIMEDOUT

Plz, tell me how to use getTripStats().

**Comment by rajat2004** [comment]
Maybe AirSim hasn't been started before running the script, or might be firewall or IP issues if running on different systems, etc.
Also, the issue should be opened against that repository

**Comment by 4iue0** [comment]
Thank you for answering.
I will try it.
Sorry, I wanna open issue in that repository, but its item of issue was close by owner.
I can only open issue here.

**Comment by jonyMarino** [comment]
Hi @4iue0! How did it go?
