### ISSUE TITLE
send the data to another computer

### ISSUE THREAD

**Issue by fhggty2005** [Microsoft/AirSim#311]
I want to send the data to another computer.(windows -> ubuntu)
I installed ROS on Windows and tried to transfer the data, but it's difficult.
Is there a way to transfer data to another computer in AirSim?

**Comment by sytelus** [comment]
I don't know what you mean. If you mean how you can connect to AirSim on another computer then I guess it depends on your client. Usually you provide IP address to client and connect. Search for networking basic on Internet.
