### ISSUE TITLE
Can AirSim be used to test a new drone before physically flying it?

### ISSUE THREAD

**Issue by tschomb78** [microsoft/AirSim#3110]
I am really not super code-savvy, the fact that I have managed to get airsim working with unreal, and then run PX4 SITL (Though I can't seem to re-launch it after the first make command) and connect to QGC and fly around is astonishing to me. I have a new drone and am looking to tweak its parameters via the simulation before risking it in the real world. Before I invest more time into learning all of these programs/systems, is it possible to import a custom model that more accurately represents the frame I'm using? And is this a valid way of "testing" a new drone out if so?

**Comment by rajat2004** [comment]
AirSim currently doesn't depend on the Unreal model for the physics, and from what I understand its only being used fro visual purpose, and physics is completely separate. You would have to modify the physical paramters which is not a trivial task, and its not a very exact physics model. Personally, I wouldn't recommend using AirSim for very accurate physics model, but maybe go for something like say RealFlight, or others, but this is just my opinion.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
