### ISSUE TITLE
I want to know how to record without imageFile.

### ISSUE THREAD

**Issue by kensuke1921** [microsoft/AirSim#3123]
I use record button in AirSim because I want to record speed of the car and car position. 
However, record button ain AirSim also record the ImegeFile. So processing while driving is heavy.  
Please teach me how to record without imageFile.

**Comment by tharindurmt** [comment]
You have to remove any elements under tag "recording" in the settings.json file.
Ex: I have the following section in my settings file. If I remove the it, AirSim will no longer record the images. 

```"Recording": {
    "RecordOnMove": true,
    "RecordInterval": 1,
    "Cameras": [
      {
        "CameraName": "FrontLeftCam",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      },
      {
        "CameraName": "FrontRightCam",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      },
      {
        "CameraName": "FrontCentreCam",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      },
      {
        "CameraName": "RearCentreCam",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      }
    ]
  }```

**Comment by kensuke1921** [comment]
Thank you for advice.
It means like this picture？
Originally no code was written in settings.json.
So I wrote "recording".
But recording with imageFile is continuing...
Please teach me...
![スクリーンショット (6)](https://user-images.githubusercontent.com/73044629/99122266-570afe00-2641-11eb-8186-f1f9220ce1c1.png)

**Comment by tharindurmt** [comment]
Try removing the  `Recording` tag altogether.
Do you have any content in your AirSim plugin? (I'm referring to any image recording code)

**Comment by kensuke1921** [comment]
I removed the Recording tag altogether like this.
But recording with imageFile is continuing....
I think RecordingFile.cpp is seems to be related to this problem.

![スクリーンショット (7)](https://user-images.githubusercontent.com/73044629/99359050-cd358c00-28f1-11eb-83d3-20045326d810.png)

**Comment by tharindurmt** [comment]
Yeah, this seems to be the default behaviour. Sorry for not catching it before.
What you can do is to comment out [these lines](https://github.com/microsoft/AirSim/blob/37a0aaebc171c5c7fa3be739edb74c1ae8e06807/Unreal/Plugins/AirSim/Source/Recording/RecordingThread.cpp#L121-#L124), so that the images are not captured. I haven't tried this myself. But commenting out these line should stop recording the images, if that's what you want. However, you'll most probably have to do some extra modifications to the /Unreal/Plugins/AirSim/Source/Recording/RecordingFile.cpp file by removing statements related to image capture, such as below.
```        std::stringstream image_file_name;
        image_file_name << "img_" << response.camera_name << "_" <<
            common_utils::Utils::toNumeric(response.image_type) << "_" <<
            common_utils::Utils::getTimeSinceEpochNanos() << 
            (response.pixels_as_float ? ".pfm" : ".png");```

**Comment by kensuke1921** [comment]
Thank you for advice.
I comment out the line you specified.
But, all items are no longer recorded. For example, car position, car speed.
I want to know how to record except for only imageFile. 
Sorry.......

**Comment by tharindurmt** [comment]
Can you paste the code you changed here?
Unfortunately, I won't have enough time to test this myself.

**Comment by kensuke1921** [comment]
Thank you for reply.
I comment out the line you specified.
I only did it.
I can't understand how to change the other code.
Sorry..
![スクリーンショット (43)](https://user-images.githubusercontent.com/73044629/99840213-7a88f800-2baf-11eb-805a-ad7087c3bc15.png)
![スクリーンショット (44)](https://user-images.githubusercontent.com/73044629/99840219-7ceb5200-2baf-11eb-86e0-609f576fbea0.png)

**Comment by tharindurmt** [comment]
Sorry, missed the email notification.
Did it throw any errors? Any log messages?

**Comment by kensuke1921** [comment]
It didn't throw any errors and log message is nothing.

**Comment by tharindurmt** [comment]
I'll try this myself. But will need some time as I'm in the middle of developing another AirSim application.

**Comment by kensuke1921** [comment]
Thank you so much!
