### ISSUE TITLE
Airsim on Marketplace environments

### ISSUE THREAD

**Issue by kharyal** [microsoft/AirSim#3129]
While trying to run AirSim on environments from the Unreal Marketplace, I am facing the following issue in getting correct segmentation images
![28_scene](https://user-images.githubusercontent.com/33199820/98181909-72cc2100-1f2a-11eb-9b94-d4550af111e7.png)
![28_seg](https://user-images.githubusercontent.com/33199820/98181905-719af400-1f2a-11eb-989d-e9bcc6edc6c7.png)

I want separate segmentation for road and believe that the above issue is happening because the meshes are stored in a Blueprint Class Actor. Is there any way to penetrate through the BP to get correct segmentation?

TIA

**Comment by jonyMarino** [comment]
Hi! This is a dup of #3024. Post there, please
