### ISSUE TITLE
fatal error: 'common/AirSimSettings.hpp' file not found

### ISSUE THREAD

**Issue by sugawaradaisuke** [microsoft/AirSim#3131]
My environments is ubuntu 20.04(NVIDIA Corporation GP107GL [Quadro P620] (rev a1)).
Unreal Engine is 4.24.3.
I built `airsim` and `Unreal Engine` according to [here](https://microsoft.github.io/AirSim/build_linux/).
And I copy `Plugins/AirSim` to `Blocks` directory.
Following error occur when I open `Blocks` on Unreal Engine.

`[In file included from /home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:2:
In file included from /home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.cpp:4:
/home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.h:24:10: fatal error: '~/AirSim/AirLib/include/common/AirSimSettings.hpp' file not found
#include "~/AirSim/AirLib/include/common/AirSimSettings.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.gen.cpp:2:
In file included from /home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Inc/AirSim/AirBlueprintLib.gen.cpp:8:
/home/d/AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/AirBlueprintLib.h:24:10: fatal error: '~/AirSim/AirLib/include/common/AirSimSettings.hpp' file not found
#include "~/AirSim/AirLib/include/common/AirSimSettings.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
LogInit: Warning: Still incompatible or missing module: Blocks
LogInit: Warning: Still incompatible or missing module: AirSim](url)`

I can find `AirSimSettings.hpp` at `(AirSim Path)/AirLib/include/common`. How do I fix it ?

**Comment by rajat2004** [comment]
There isn't any need to copy the Plugins directory when using the Blocks environment
Try running clean_rebuild.sh, and then do the steps again, just using the scripts and see if that works

**Comment by jonyMarino** [comment]
Hi @sugawaradaisuke! And Welcome! Rajat answer is correct so let us know if you still have any issue.
