### ISSUE TITLE
Issue running QGC missions

### ISSUE THREAD

**Issue by Agm2104** [microsoft/AirSim#3137]
I'm trying to flight a drone and get LIDAR data by using PX4 with Airsim as SITL. I try to launch a mission in QGC without the sensors enabled and I have no problem, but the moment I enable LIDAR I get 2 issues:

1. When I try to launch my 'default' mission after opening QGC, the drone seems to arm but never takes off and the mission ends.

2. When try to load/upload a different mission, I get the 'mission transfer failed' issue.

I have checked the loss rates (seems to be 0) and the messages on the console logging and I get the following:

![image](https://user-images.githubusercontent.com/74015104/99085142-233fc200-25c8-11eb-9dad-a644992f68c6.png)

Any idea of what the problem could be?
Here are screenshots of the settings.json file, which seems to be the problem, but I don't see how those parameters affect QGC

Works::
![image](https://user-images.githubusercontent.com/74015104/99085742-dc9e9780-25c8-11eb-912a-857818fce723.png)

Doesn't work:
![image](https://user-images.githubusercontent.com/74015104/99085596-acef8f80-25c8-11eb-99ed-7ac958e0b4c7.png)

Any input would be very welcome :)
Thanks in advance!

**Comment by ahmed-elsaharti** [comment]
Hi @Agm2104 ,
I ran a couple of tests and was able to replicate your error while using the settings.json that has the sensors by:
1. Launching PX4 SITL
2. Launching the UE4 environment
3. Launching QGC
4. Uploading the mission file which resulted in `mission transfer failed`

The error seemed to go away when launching the simulation in this order:
1. Launch QGC
2. Start PX4 SITL
3. Star the UE4 environment.
4. Upload the mission file and start mission:
![image](https://user-images.githubusercontent.com/49626509/99474401-201f3b80-2912-11eb-80af-af0ac7deb121.png)
![image](https://user-images.githubusercontent.com/49626509/99474413-257c8600-2912-11eb-85f8-a9eadec252d2.png)

Hope this helps.

**Comment by Agm2104** [comment]
Hey @ahmed-elsaharti, sorry for late answer! Yeah, apparently the error came from a compatibility issue, which was resolved in #3130. Everything seems to run properly now.

Thank you very much for the help!
