### ISSUE TITLE
No horizontal movement API in drone's x, y, z axes

### ISSUE THREAD

**Issue by ICYPOLE** [microsoft/AirSim#3138]
OS: Win10
AirSim: v1.3.1
Python: v3.6.12

I am currently writing a PC keyboard controller in Python for controlling drone. When trying to control the drone for horizontal movement, I found that all of the APIs, such as `moveByVelocityAsync`, `setVelocityControllerGains`, are implemented for world x, y, z axes. 

I wonder if there is any possible solution to move the drone horizontally in the drone's x, y, z axes, which is more intuitive.

**Comment by rlalpha** [comment]
same problem here too.
Try to connect my remote controller: which have format rc: x_velocity, y_velocity, z_velocity, rotate_velocity

**Comment by ahmed-elsaharti** [comment]
You could create a function that uses the pitch, roll and yaw of the vehicle (from `simGetVehiclePose`) to break a velocity vector in the Drone's x,y,z axes to components in the world x,y,z axes and then use `moveByVelocityAsync` to execute those components which would result in an overall motion equivalent to the drone vector you wanted.

Here's a quick 2D example to show what I mean
![image](https://user-images.githubusercontent.com/49626509/99477807-e00f8700-2918-11eb-8924-0dafb52b8720.png)

**Comment by jonyMarino** [comment]
Hey @ICYPOLE! That would be very handy. Want to submit a PR for a new `moveByLocalVelocityAsync` and `setLocalVelocityControllerGainsLocal` with Ahmed's approach?

**Comment by jonyMarino** [comment]
Thanks, @ahmed-elsaharti, for your PR! Just for curiosity, what tool are you using to make your graphics?

**Comment by ahmed-elsaharti** [comment]
@jonyMarino I generally use [Microsoft Onenote](https://www.onenote.com/) along with my [graphics tablet ](https://www.huion.com/pen_tablet/Huion/NEW_1060PLUS.html) 😃
