### ISSUE TITLE
How can I get camera intrinsic parameters?

### ISSUE THREAD

**Issue by Nickvot** [Microsoft/AirSim#314]
Hi, I'm trying to find camera intrinsic matrix.
In the depth map, closer is brighter, so it may be a disparity map I think.
I read some issues that I can find it in point_cloud.py, and the Q matrix in that file is 
```
projectionMatrix = np.array([[-0.501202762, 0.000000000, 0.000000000, 0.000000000],
                              [0.000000000, -0.501202762, 0.000000000, 0.000000000],
                              [0.000000000, 0.000000000, 10.00000000, 100.00000000],
                              [0.000000000, 0.000000000, -10.0000000, 0.000000000]])
...
Image3D = cv2.reprojectImageTo3D(gray, projectionMatrix)
```
...yeah.
However, the format of Q must be like below,

```
Q=[[1, 0, 0, -cx],
      [0, 1, 0, -cy],
      [0, 0, 0, f],
      [0, 0, -1/B, (cx - cx')/B]]
```
Where cx' is cx of the right cam, B is the baseline.
How can I get the f, cx, cy, and the B?

**Comment by sytelus** [comment]
You need to first convert depth in to camera plan and then build matrix using camera FOV = 90. See the [discussion here](https://github.com/unrealcv/unrealcv/issues/14).

**Comment by badabook** [comment]
k

**Comment by stavBodik** [comment]
@Nickvot

CameraMatrix = IntrinsicMatrix * ExtrinsicMatrix

Where ExtrinsicMatrix = RotationMatrix*TranslationMatrix(aKa position)

For C++ users :

`ProjectionMatrix projMatrix = client.simGetCameraInfo("0").proj_mat;
VectorMath::Matrix3x3f rotationMatrix = client.simGetCameraInfo("0").pose.orientation.toRotationMatrix();
VectorMath::Vector3f cameraPosition = client.simGetCameraInfo("0").pose.position;
 `

**Comment by orangelx** [comment]
Did you solve this problem?  like this  #1198

**Comment by stavBodik** [comment]
@orangelx 

Please read here :

https://github.com/unrealcv/unrealcv/issues/14#issuecomment-487346581
