### ISSUE TITLE
Multi-vehicles with QGC

### ISSUE THREAD

**Issue by eggbread** [microsoft/AirSim#3153]
I want to use the AirSim for my swarm drone project. 
![image](https://user-images.githubusercontent.com/38123162/99665616-39102400-2aad-11eb-8a97-27c8960bada5.png)
Can I connect multi drones with QGC like above picture? I already know I can connect one drone and QGC.
My ultimate goal is QGC + AirSim and run with Python Script.
Thank you for you help in advance!

**Comment by ahmed-elsaharti** [comment]
Hi @eggbread , have a look at #1599 and #2084
