### ISSUE TITLE
LNK 2019/1120 when using an old version of Airsim

### ISSUE THREAD

**Issue by guicha-t** [microsoft/AirSim#3159]
Hello,

I am currently working on an Unreal Engine project using Airsim functionality. Until today I was working with a recent version of Airsim and all were working fine.
I then want to use the Airsim plugin from another project, modified to meet certain needs, but when I move it, clean and regenerate the files, I have the following errors while building the project in VS2019:

```
1>PIPCamera.cpp.obj : error LNK2019: unresolved external symbol "public: static class UCineCameraComponent * __cdecl UAirBlueprintLib::GetActorComponent<class UCineCameraComponent>(class AActor *,class FString)" (??$GetActorComponent@VUCineCameraComponent@@@UAirBlueprintLib@@SAPEAVUCineCameraComponent@@PEAVAActor@@VFString@@@Z) referenced in function "public: virtual void __cdecl APIPCamera::PostInitializeComponents(void)" (?PostInitializeComponents@APIPCamera@@UEAAXXZ)

1>AirsimMaster.cpp.obj : error LNK2019: unresolved external symbol "public: enum msr::airlib::RpcLibClientBase::ConnectionState __cdecl msr::airlib::RpcLibClientBase::getConnectionState(void)" (?getConnectionState@RpcLibClientBase@airlib@msr@@QEAA?AW4ConnectionState@123@XZ) referenced in function "public: void __cdecl AirsimMaster_SimGetImages::DoWork(void)" (?DoWork@AirsimMaster_SimGetImages@@QEAAXXZ)

1>AirsimMaster.cpp.obj : error LNK2019: unresolved external symbol "public: class std::vector<struct msr::airlib::ImageCaptureBase::ImageResponse,class std::allocator<struct msr::airlib::ImageCaptureBase::ImageResponse> > __cdecl msr::airlib::RpcLibClientBase::simGetImages(class std::vector<struct msr::airlib::ImageCaptureBase::ImageRequest,class std::allocator<struct msr::airlib::ImageCaptureBase::ImageRequest> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?simGetImages@RpcLibClientBase@airlib@msr@@QEAA?AV?$vector@UImageResponse@ImageCaptureBase@airlib@msr@@V?$allocator@UImageResponse@ImageCaptureBase@airlib@msr@@@std@@@std@@V?$vector@UImageRequest@ImageCaptureBase@airlib@msr@@V?$allocator@UImageRequest@ImageCaptureBase@airlib@msr@@@std@@@5@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@5@@Z) referenced in function "public: void __cdecl AirsimMaster_SimGetImages::DoWork(void)" (?DoWork@AirsimMaster_SimGetImages@@QEAAXXZ)

1>AirsimMaster.cpp.obj : error LNK2019: unresolved external symbol "public: __cdecl msr::airlib::MultirotorRpcLibClient::MultirotorRpcLibClient(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,unsigned short,float)" (??0MultirotorRpcLibClient@airlib@msr@@QEAA@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@GM@Z) referenced in function "public: void __cdecl AirsimMaster_SimGetImages::DoWork(void)" (?DoWork@AirsimMaster_SimGetImages@@QEAAXXZ)

1>AirsimMaster.cpp.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl msr::airlib::MultirotorRpcLibClient::~MultirotorRpcLibClient(void)" (??1MultirotorRpcLibClient@airlib@msr@@UEAA@XZ) referenced in function "public: void __cdecl AirsimMaster_SimGetImages::DoWork(void)" (?DoWork@AirsimMaster_SimGetImages@@QEAAXXZ)

1>D:\Users\guich\Documents\UE4\clone\flight-model-in-ue4\FlightModelSimulator\Binaries\Win64\UE4Editor-FlightModelSimulator-Win64-DebugGame.dll : fatal error LNK1120: 4 unresolved externals
```

Can you tell me if it is possible to import an older and modified version of Airsim and if so how is it possible to make the correct library links.

For information and reproduce the errors: From my working project, I delete the Airsim folder (version 1.3.1) in Plugins, I copy / paste the Airsim folder from another project (version 1.2), I run clean .sh and GenerateProjectFiles.sh, and build my project. Note also that the two projects are launching perfectly with their own Airsim plugins and under VS2019.

Is there a possibility that this is happening because the many modified files are listed in the "Adaptive unity build"?

`1>[Adaptive unity build] Excluded from AirSim unity file: AirBlueprintLib.cpp, RpcLibClientBase.cpp, RpcLibServerBase.cpp, FileSystem.cpp, ObstacleMap.cpp, SafetyEval.cpp, MultirotorApiBase.cpp, AirSim.cpp, CameraDirector.cpp, ManualPoseController.cpp, NedTransform.cpp, PawnSimApi.cpp, PIPCamera.cpp, SimHUD.cpp, SimJoyStick.cpp, SimModeBase.cpp, SimModeWorldBase.cpp, UnrealImageCapture.cpp, FlyingPawn.cpp, MultirotorPawnSimApi.cpp, WorldSimApi.cpp`

EDIT: 
It seems that the Airlib lib folder containing the lib files is not generated. I have it on the Airsim version 1.3.2 plugin but not on the April 2020 one. This is what I noticed, I continue to look for a solution.

**Comment by ahmed-elsaharti** [comment]
@guicha-t I've had a similar error pop up when trying to change the code within AirLib and rebuilding the blocks environment. This ended up being fixed by cleaning the blocks project, rebuilding the Airlib project in the main airsim solution (it builds both Airlib and Mavlinkcom) using VS2019, Building the entire repo again using the build.cmd to apply changes and then using the update_from_git script with the blocks environment. A similar combination of steps might work for your issue
