### ISSUE TITLE
I want to increase the speed of the car.

### ISSUE THREAD

**Issue by kensuke1921** [microsoft/AirSim#3164]
The maximum speed of my car is only about 60 km / h.
I want to drive the car faster.
I think I have to change the program of AirSim but I can't understand how to change.
Please help me....

**Comment by ahmed-elsaharti** [comment]
Hi @kensuke1921 , do you mean 60m/s? thats ~214km/h
![image](https://user-images.githubusercontent.com/49626509/100524126-1ea80b80-317b-11eb-8b84-24edce128fef.png)

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
