### ISSUE TITLE
bring Airsim Unreal Project file from Windows to Linux

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3168]
Hi!

So I set up the basic Airsim Uproject mountains example Airsim for windows.
I then copied the folder with the Uproject into my Airsim that runs on Linux. 

The first error I get is:

"This project was made with a different version of the Unreal Engine. Converting to this version will rebuild your code projects.

New features and improvements sometimes cause API changes, which may require you to modify your code before it compiles. Content saved with newer versions of the editor will not open in older versions.

We recommend you open a copy of your project to avoid damaging the original."

I click "Open a copy"

Then the next issue is:
"the project could not be compiled would you like to open it in Null Source Code Access?

The project could not be compiled. Would you like to open it in Null Source Code Access?

Running /home/edwin/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Linux -Project="/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/LandscapeMountains.uproject" -TargetType=Editor -Progress -NoHotReloadFromIDE
Scale at X=1920.000000, Y=0.000000: 1.000000 (monitor=#0, HDPI=96.000000 (horz scale: 1.000000), VDPI=96.000000 (vert scale: 1.000000))
Scale at X=2944.000000, Y=640.000000: 1.000000 (monitor=#0, HDPI=96.000000 (horz scale: 1.000000), VDPI=96.000000 (vert scale: 1.000000))

Running Mono...

Fixing inconsistent case in filenames.
Setting up Mono
~/UnrealEngine/Engine ~/UnrealEngine/Engine/Binaries/Linux
Using 'git status' to determine working set for adaptive non-unity build (/home/edwin/UnrealEngine).
Creating makefile for LandscapeMountainsEditor (no existing makefile)
WARNING: Library 'stdc++' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
WARNING: Library 'supc++' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
WARNING: Library '/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/deps/MavLinkCom/lib/libMavLinkCom.a' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
WARNING: Library '/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/lib/libAirLib.a' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
WARNING: Library '/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a' was not resolvable to a file when used in Module 'AirSim', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
@progress push 5%
Creating makefile for UnrealHeaderTool (no existing makefile)
@progress push 5%
@progress pop
------- Build details --------
Using toolchain located at '/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu'.
Using clang (/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++) version '8.0.1' (string), 8 (major), 0 (minor), 1 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar : /home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar
Using fast way to relink  circularly dependent libraries (no FixDeps).
------------------------------
Parsing headers for LandscapeMountainsEditor
  Running UnrealHeaderTool "/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/LandscapeMountains.uproject" "/home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Intermediate/Build/Linux/B4D820EA/LandscapeMountainsEditor/Development/LandscapeMountainsEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors
Reflection code generated for LandscapeMountainsEditor in 3.8822479 seconds
@progress pop
------- Build details --------
Using toolchain located at '/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu'.
Using clang (/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++) version '8.0.1' (string), 8 (major), 0 (minor), 1 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar : /home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar
Using fast way to relink  circularly dependent libraries (no FixDeps).
------------------------------
Building LandscapeMountainsEditor...
Performing 7 actions (10 in parallel)
[2/7] Compile Module.AirSim.gen.cpp
[3/7] Compile LandscapeMountains.cpp
[1/7] Compile Module.AirSim.cpp
[4/7] Compile MyClass.cpp
[5/7] Link (ld) libUE4Editor-AirSim.so
/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: cannot find /home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/deps/MavLinkCom/lib/libMavLinkCom.a: No such file or directory
/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: cannot find /home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/lib/libAirLib.a: No such file or directory
/home/edwin/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v15_clang-8.0.1-centos7/x86_64-unknown-linux-gnu/bin/x86_64-unknown-linux-gnu-ld: cannot find /home/edwin/AirSim/Unreal/Environments/LandscapeMountains 4.24/Plugins/AirSim/Source/AirLib/deps/rpclib/lib/librpc.a: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)"

I then click the Uproject again:

And the second to final error is:

"The following modules are missing or built with a different engine version (I built in Unreal 4.24 for windows and the Linux system has Unreal 4.24 aswell)

LandscapeMountains
Airsim

would you like to rebuild them now?"

I click yes

and then I get 
"LandscapeMountains could not be compiled. try rebuilding from source manually?"

Would anyone know why?

**Comment by GimpelZhang** [comment]
Hi,
I guess #3101 is a similar issue.

**Comment by EdwinMeriaux** [comment]
THANKS!
