### ISSUE TITLE
Vehicle not spawning at PlayerStart

### ISSUE THREAD

**Issue by hazevedosa** [microsoft/AirSim#3170]
OS: Windows 10, AirSim version: 1.3.1, Unreal Version: 4.24

I followed the installation tutorial steps to get the Blocks environment running. However, when I hit "Play" in UE, the vehicle spawns at a completely different position. I can even control the car and hit the obstacles but I can't see them -- It looks like all the assets are there, but the map visualization is displaced.
![Presentation1](https://user-images.githubusercontent.com/48081446/100381631-5f6f1b80-2fe7-11eb-82d9-760bdf52d44b.png)

**Comment by ahmed-elsaharti** [comment]
Hi @hazevedosa, could you show us your settings.json file? It might shed some light on why this is happening

**Comment by hazevedosa** [comment]
I used the minimal settings...:

{
  "SettingsVersion": 1.2,
  "SimMode": "Car"
}

**Comment by ahmed-elsaharti** [comment]
@hazevedosa I've done some testing but was not able to replicate your results using the stock start position (i did move the start position up in the Z direction just to make sure it matches the screenshot you posted) and the minimal settings:
![Capture](https://user-images.githubusercontent.com/49626509/100388500-68b0b600-2ff0-11eb-94a4-554cc7b38db8.JPG)
![Capture2](https://user-images.githubusercontent.com/49626509/100388506-6b131000-2ff0-11eb-95d4-1f2a8805fc91.JPG)
![Capture3](https://user-images.githubusercontent.com/49626509/100388507-6cdcd380-2ff0-11eb-84d1-893376b16720.JPG)

I was however able to replicate the start position seen in your screenshots when placing playerstart at 0,0,0:
![Capture4](https://user-images.githubusercontent.com/49626509/100388513-6fd7c400-2ff0-11eb-803a-daf9c75f31c3.JPG)
and did get some strange behavior when the car is dropped from a relatively high start point.
Have you done any changes to the code and/or the start position? Also, are you using the latest repo?
I suggest going back to the start and recloning the repo in another directory then testing the blocks environment without any changes.

**Comment by hazevedosa** [comment]
I am using the latest repo, but I haven't changed the code. 

I can see that when I hit play the PlayerStart Transform immediately changes to (0.0, 0.0, 0.0)... That does not happen when I use AirSim 1.2 in UE 4.18 (I also have those installed).

**Comment by ahmed-elsaharti** [comment]
@hazevedosa The transformation to 0,0,0 in the new repo is probably due to #3147. However, that should not change where the player spawns relative to the assets, It only changes the origin of the world to where the player is and re-grabs the player's new location relative to that new origin (which should be 0,0,0 since they're the same point now).

Have you tried redoing the entire process of cloning and building? The reason I'm suggesting redo-ing everything is to make sure this issue is happening because of AirSim and not the clone/build process or anything in between since I'm not able to replicate the results (even though I just recloned and built the latest repo **and** a branch from ~a week ago).

If you do redo everything and end up with the same results, try including what the steps you followed were exactly so that we could try to replicate your results and go from there.

**Comment by hazevedosa** [comment]
Ok, @ahmed-elsaharti. I just re-cloned and rebuilt following these steps:

1. Cloned the repo with git clone https://github.com/Microsoft/AirSim.git
2. Got into AirSim folder and ran build.cmd from the command line.
3. Navigated to folder AirSim\Unreal\Environments\Blocks and ran update_from_git.bat.
4. Opened Blocks.sln in Visual Studio 2019 and built with build DebugGame_Editor / Win64 configuration.
5. Pressed the Play button in Unreal Editor. 

Same problem happens -- the car is dropped under the ground.

**Comment by hazevedosa** [comment]
So... for now I am using an older version. I downloaded the binaries for 1.3.0 and they work just fine.

**Comment by ahmed-elsaharti** [comment]
I realized I was using UE4.25 while trying to replicate this which might make a difference. I'll install 4.24, reclone/rebuild and try to replicate the issue again.
@jonyMarino any ideas?

**Comment by ahmed-elsaharti** [comment]
I repeated the test with UE4.24 and was still not able to replicate the problem.

**Comment by jonyMarino** [comment]
Hi @hazevedosa! And welcome! When you reported that you were using airsim 1.3.1, you were really using that release or just the latest commit?

**Comment by hazevedosa** [comment]
Probably the last commit, as I cloned the repo.

**Comment by jonyMarino** [comment]
And what happens if you change the player start position? Does it still spawn at the same place?

**Comment by hazevedosa** [comment]
Visually, yes. However, when I change playerStart position, start running and move around, I can realize the car was indeed spawned elsewhere. Just because I can hit different obstacles.
