### ISSUE TITLE
subt envi for windows and linux

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3173]
hi!

So I was trying to use the windows subt envi and I was able to launch it.
https://github.com/microsoft/AirSim/releases/tag/v.1.2.2
But I am confused. Is there no .sln file for this?
Is there any reason why most of the files that came with the standard blocks example come with the subt envi? For example no plugin folder etc... 

So for the linux version similar question.

I got it to launch.
I am just confused why most of the normal folders aren't there

For example,
How would I import a new drone?

**Comment by jonyMarino** [comment]
Hi @EdwinMeriaux! That releases are not open source. They are generated from environments that are private. The idea is to use them as they are for simulation. You can still use the API to connect to the simulation.

To what do you refer with "How would I import a new drone?" ? Do you have another blueprint for the drone?
