### ISSUE TITLE
getCarControls api in Unity

### ISSUE THREAD

**Issue by weigangwen** [microsoft/AirSim#3175]
I want to use getCarControls api to collect steering information when driving a car in Unity by keyboards. But the steering angle always returns 0.
Is there any way  to get steering angle by api in Unity

environment：
Windows 10
Unity 2019.3.12
Airsim [1.3.1]

------------------------------------ (Remove above before filing the issue) ------------------------------------

**Comment by rajat2004** [comment]
This is a preexisting bug in the Unity I think, and seems to be related to https://github.com/microsoft/AirSim/pull/2937, at least based on my older description
