### ISSUE TITLE
ArduRoverApi.hpp can not be compiled

### ISSUE THREAD

**Issue by liang-tang** [microsoft/AirSim#3179]
I want to send brake control to AirSim while ardupilot rover simulating.
and i modified ArduRoverApi.hpp to receive brake message, but seems never received. so made the test below
1.execute clean.cmd to clean first compile.
2.delete ArduRoverApi.hpp.
3.run build.cmd to compile airsim
but the compile sitll can be finished.
someone can tell me how to compile it? thanks

**Comment by rajat2004** [comment]
The unmodified file compiles and after making the changes, it's compiling, is that so?
You'll have to post atleast the error messages and mostly the modified code also (in a branch) for someone to help you in figuring out the problems

**Comment by liang-tang** [comment]
> The unmodified file compiles and after making the changes, it's compiling, is that so?
> You'll have to post atleast the error messages and mostly the modified code also (in a branch) for someone to help you in figuring out the problems
As you can see, some file already been deleted, but when ran build.cmd no error occur.
Why i did this test, I want to modify the Api of ArduRover.
![image](https://user-images.githubusercontent.com/16251761/101233439-dbf2b000-36f3-11eb-9ace-cefc8866414c.png)

**Comment by liang-tang** [comment]
> The unmodified file compiles and after making the changes, it's compiling, is that so?
> You'll have to post atleast the error messages and mostly the modified code also (in a branch) for someone to help you in figuring out the problems

OK, now i know the whole development workflow, build.bat will copy some files(i.e ArduRoverApi.hpp) to Plugins AirSim folder, and compile it when compile Blocks project.
Also thanks for your reply. @rajat2004
