### ISSUE TITLE
IF NOT EXIST external\rpclib\build mkdir external\rpclib\build cd external\rpclib\build cmake -G"Visual Studio 14 2015 Win64" ..

### ISSUE THREAD

**Issue by hanfengsunshine** [Microsoft/AirSim#318]
![image](https://user-images.githubusercontent.com/14012055/27834139-4eb2910c-6108-11e7-9f3c-e552e6a1b217.png)

**Comment by sytelus** [comment]
Check your cmake version and installation and please describe problem in detail. The build.cmd works fine in our setups.
