### ISSUE TITLE
-D CMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by hanfengsunshine** [Microsoft/AirSim#320]
![image](https://user-images.githubusercontent.com/14012055/27834611-2e6b3dd4-610a-11e7-8e65-a84d84a6a61d.png)

**Comment by sytelus** [comment]
Are you saying you get recursive calls in build? Please describe the problem. You also need to check your cmake version. We use this build script on travis (https://travis-ci.org/Microsoft/AirSim/) and things look fine so likely issue in your setup (if I'm guessing right about your issue).
