### ISSUE TITLE
Question: Increasing the frequency of recording thread?

### ISSUE THREAD

**Issue by vatsagandhi** [Microsoft/AirSim#321]
We would like to capture images at a higher frequency and would like to know how/where we can adjust the frequency of the recording thread.

**Comment by vatsagandhi** [comment]
Additionally how can we extract vga images not 720p.

**Comment by sytelus** [comment]
Currently recording thread captures images continuously one after another without any intermediate delay. If you want to capture images faster then we have to do some more optimization (for example, do file I/O on separate thread using producer/consumer model). The relevant code can be found here:

https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/RecordingThread.cpp#L34
