### ISSUE TITLE
getImageForCamera Function

### ISSUE THREAD

**Issue by yti1993** [Microsoft/AirSim#322]
I got image info that was captured at Unreal-Engine world by using "AirSim/PythonClient/camera.py".  

## My process summary
**First**, I execute Unreal Engine & Airsim.

**Second**, I add  `print (rawimage[0:1000])` at "camera.py" ,  [this line](https://github.com/Microsoft/AirSim/blob/master/PythonClient/camera.py#L45) because I want to get Depth information.

**Third**, I execute "camera.py" on cmd screen (Windows 10)

**finally**, I got matrix about depth_image on cmd screen. 

I watch matrix that is filled many numbers. that matrix and captured Depth image are below.
![capture1](https://user-images.githubusercontent.com/19484948/27913595-9d040c48-629b-11e7-84d8-06d829478ba6.PNG)
![capture2](https://user-images.githubusercontent.com/19484948/27913612-abe1cf84-629b-11e7-8158-3146fb62be63.PNG)

I wonder that matrix numbers what means.... 
they are Depth_info?
they are Disparity_info?

p.s I slice matrix [0:1000], because this image matrix size is very big, huge. so data is omitted.

**Comment by ShukuiZhang** [comment]
I'm pretty sure they are disparity images coming from stereo cameras. @yti1993

**Comment by yti1993** [comment]
@ShukuiZhang 
Thank you for comment!

I guess.. if that numbers mean 'disparity', range of numbers was 0~255.
but, values on screen are not...

Do you share some evidence of your thinking _"they are disparity images"_  to me?

Have a nice day @ShukuiZhang !

**Comment by ShukuiZhang** [comment]
Because the closer the point, the brighter (larger pixel value) it is in the image, which can not be a depth map. @yti1993  I don't know why the numbers are not 0~255, in my case it is. The disparity image comes in rgb (3 channel but same value for each channel), I'm not sure if this is your problem.

**Comment by sytelus** [comment]
The disparity and depth image generation had major overhaul: https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md
