### ISSUE TITLE
 AirSim Python APIs documentation 

### ISSUE THREAD

**Issue by heisenberg898** [microsoft/AirSim#3223]
where can i find AirSim Python APIs documentation 

and i am trying do draw  a polygon and some other shape i cant able to make it correct way 
kindly do the support

More Info
More information on AirSim Python APIs can be found at: https://github.com/Microsoft/AirSim/blob/master/docs/python.md

if i go to the link its page not found

**Comment by GimpelZhang** [comment]
Hi, here are some hints:

[Core APIs](https://microsoft.github.io/AirSim/apis/)
