### ISSUE TITLE
Anyone can confirm Camera Drone relative pose?

### ISSUE THREAD

**Issue by ShukuiZhang** [Microsoft/AirSim#323]
I've been searching for the drone and camera relative pose for a while, which is useful to create my data set. This is because (I think) what I get from getOrientation() or getPosition() are orientation and position for the drone rather than the camera and I need those for the camera too. I find a line of code [here](https://github.com/Microsoft/AirSim/blob/92a3f516cb1d72c75b711853839c906c9e290f38/Unreal/Plugins/AirSim/Source/SimMode/SimModeWorldMultiRotor.cpp#L47). I think this is the actual relative pose definition between camera and the drone, can anyone confirm that? @lovettchris @sytelus From this line, I can infer that they are of same orientation and a relative position of [-300, 0, 200] in drones' frame. Am I correct? Is the unit for relative position mm? Thanks!

**Comment by sytelus** [comment]
Relative orientation is unity quaternion (i.e. same for both). Relative pose for right camera is x = 46cm, y = -7cm and for left its right camera is x = 46cm, y = +7cm. You can view this by opening up FlyingPawn blueprint in Unreal editor. BTW, I'm revamping camera system as we speak :). I'll update this thread with more info after I'm done.

**Comment by ShukuiZhang** [comment]
That is really great! @sytelus So the baseline for the stereo is simply 14cm. Things look much better now.
