### ISSUE TITLE
 make px4_sitl_default none_iris

### ISSUE THREAD

**Issue by AIKUUM** [microsoft/AirSim#3234]
### Include details of what you already did to find answers
Below is my system details:
https://user-images.githubusercontent.com/72294070/102069277-90db4a00-3e23-11eb-8f71-d14e10181433.PNG

AirSim version (1.3.1)
Unreal version(4.25)
python version (3.8.3)

Im trying to setup PX4 in SITL for AirSim simulator.
But I'm getting error as in the screenshot:
![image](https://user-images.githubusercontent.com/72294070/102683409-d074ae00-41f6-11eb-879e-2a28f197c033.png)

Can some one please help me or give me a hint on how to resolve the issue?

**Comment by ahmed-elsaharti** [comment]
Hi @AIKUUM, If you're using PX4 1.10.1 as recommended [here](https://microsoft.github.io/AirSim/px4_sitl/) try uninstalling Cygwin 0.9 and installing Cygwin 0.8.
I've submitted #3222 to mention this version in the documentation since lots of people seem to run into this issue.
