### ISSUE TITLE
UE4 Engine Version clarification (minimum and suggested)

### ISSUE THREAD

**Issue by petergerten** [microsoft/AirSim#3235]
Is there a definite place that clarifies the minimum and recommended engine version to be used with AirSim?
I have been using UE4.24.3 for example and it stopped working due to new uasset files that are not downward 
compatible anymore. But I don't know what the new minimum engine version is.

Example:
https://github.com/microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Content/HUDAssets/CameraDistortion.uasset
does not work with 4.24.3 anymore.

**Comment by saihv** [comment]
This information is maintained in https://github.com/microsoft/AirSim/blob/master/docs/build_windows.md and https://github.com/microsoft/AirSim/blob/master/docs/build_linux.md. We have recently updated the docs to reflect the change to 4.25 as the minimum requirement.

**Comment by b0b023** [comment]
@saihv great, thanks! Sorry I missed that particular doc.

**Comment by petergerten** [comment]
@saihv thanks. I just tried to upgrade to 4.25.4-release - but it seems this version does not work for different reasons. See https://github.com/microsoft/AirSim/issues/3200

Maybe it would be good to be more specific in the recommended version?

**Comment by saihv** [comment]
Please see discussion at #3200

**Comment by dromero12** [comment]
> This information is maintained in https://github.com/microsoft/AirSim/blob/master/docs/build_windows.md and https://github.com/microsoft/AirSim/blob/master/docs/build_linux.md. We have [recently](https://github.com/microsoft/AirSim/commit/23985cb3ca57128c990eb402ae78a2ca71c8ccb9) updated the docs to reflect the change to 4.25 as the minimum requirement.

It means 4.25.0?, what about 4.25.4, same problems than the commented previously. Is AirSim upgradable? UE 4.27.1 is the current version.

**Comment by jonyMarino** [comment]
Hi @dromero12! Yes, 4.25.4 is fine. We haven't tested with 4.27.1, but we should support it also.
