### ISSUE TITLE
error:cdo Constructor(PIPcamera):failed to find Material'AirSim/HUDAssets/CameraDistortion.CameraDistortion' 

### ISSUE THREAD

**Issue by Yannisxm** [microsoft/AirSim#3237]
error:cdo Constructor(PIPcamera):failed to find Material'AirSim/HUDAssets/CameraDistortion.CameraDistortion' 
![image](https://user-images.githubusercontent.com/40320349/102750273-7e6f8c00-43a0-11eb-8f33-ee997919bc3e.png)

**Comment by jonyMarino** [comment]
dup #3238
