### ISSUE TITLE
NedTransform::toVector3r why not apply - to y?

### ISSUE THREAD

**Issue by litingzhen** [microsoft/AirSim#3249]
### What's your question?

Unreal World  Coordinate system: x is right of the screen，y is down of the screen, z is towards to user. 
Global NED: x is right of the screen, y is up of the screen, z is back to user.
so (x,y,z) from UU to Global NED is (x,-y,-z).
why the code NedTransform::toVector3r not apply - to y?

**Comment by ahmed-elsaharti** [comment]
Hi @litingzhen , Firstly, the Unreal World Coordinate system you described is a standard [left-handed](https://www.evl.uic.edu/ralph/508S98/coordinates.html) coordinate system and the directions of the axes depend on how your viewport is oriented (although their directions relative to eachother are the same):
![image](https://user-images.githubusercontent.com/49626509/103177935-30e19c00-4844-11eb-8b71-cd8420e34135.png)
![image](https://user-images.githubusercontent.com/49626509/103177951-48b92000-4844-11eb-87a6-d8a6187e8bc6.png)

Now, if you look at the map from the top view without any rotation, X will point upwards, Y will point right and Z will point towards the camera:
![image](https://user-images.githubusercontent.com/49626509/103178029-f5939d00-4844-11eb-9deb-aca95e20afd3.png)
From what I remember (and from your description), the UAV's coordinate system is a [right-handed coordinate system](https://www.evl.uic.edu/ralph/508S98/coordinates.html). Where from the top view (with the drone pointing up in the view), the drone's X will be pointing upwards, Y will point right and Z will point AWAY from the camera. To convert from a right handed coordinate system to a left-handed one you'll need to multiply Z by -1 
![image](https://user-images.githubusercontent.com/49626509/103178149-e19c6b00-4845-11eb-9e77-e34854dbd64b.png)

**Comment by litingzhen** [comment]
Thank you very much.
