### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by xiaolin360** [Microsoft/AirSim#325]
I have install the Airsim environment in windows 10 in Microsoft visual studio 2015, but i always meet the error, i can't solve it, please help me. My error as follows. 

“H:\WorkSpace\Airsim\AirSim.sln”(默认目标) (1) ->
“H:\WorkSpace\Airsim\DroneShell\DroneShell.vcxproj”(默认目标) (2) ->
“H:\WorkSpace\Airsim\AirLib\AirLib.vcxproj”(默认目标) (3) ->
(ClCompile 目标) ->
  c:\program files (x86)\microsoft visual studio 14.0\vc\include\chrono(769): error C2679: 二进制“+=”: 没有找到接受“const std::c
hrono::duration<double,std::ratio<1,1>>”类型的右操作数的运算符(或没有可接受的转换) [H:\WorkSpace\Airsim\AirLib\AirLib.vcxproj]
  c:\program files (x86)\microsoft visual studio 14.0\vc\include\chrono(769): error C2679: 二进制“+=”: 没有找到接受“const std::c
hrono::duration<double,std::ratio<1,1>>”类型的右操作数的运算符(或没有可接受的转换) [H:\WorkSpace\Airsim\AirLib\AirLib.vcxproj]
  h:\workspace\airsim\airlib\include\common\common_utils\json.hpp(886): error C2100: 非法的间接寻址 [H:\WorkSpace\Airsim\AirLi
b\AirLib.vcxproj]
  c:\program files (x86)\microsoft visual studio 14.0\vc\include\chrono(769): error C2679: 二进制“+=”: 没有找到接受“const std::c
hrono::duration<double,std::ratio<1,1>>”类型的右操作数的运算符(或没有可接受的转换) [H:\WorkSpace\Airsim\AirLib\AirLib.vcxproj]
  c:\program files (x86)\microsoft visual studio 14.0\vc\include\chrono(769): error C2679: 二进制“+=”: 没有找到接受“const std::c
hrono::duration<double,std::ratio<1,1>>”类型的右操作数的运算符(或没有可接受的转换) [H:\WorkSpace\Airsim\AirLib\AirLib.vcxproj]

“H:\WorkSpace\Airsim\AirSim.sln”(默认目标) (1) ->
“H:\WorkSpace\Airsim\MavLinkCom\MavLinkTest\MavLinkTest.vcxproj”(默认目标) (7) ->
  h:\workspace\airsim\mavlinkcom\common_utils\json.hpp(886): error C2100: 非法的间接寻址 [H:\WorkSpace\Airsim\MavLinkCom\MavLi
nkTest\MavLinkTest.vcxproj]
  h:\workspace\airsim\mavlinkcom\common_utils\json.hpp(886): error C2100: 非法的间接寻址 [H:\WorkSpace\Airsim\MavLinkCom\MavLi
nkTest\MavLinkTest.vcxproj]

    0 个警告
    7 个错误

已用时间 00:00:14.24
#### Build failed

**Comment by sytelus** [comment]
I'm sorry I don't understand error messages in Chinese. Either you might have to translate it for us or install the english version and see how that works,
