### ISSUE TITLE
help needed! compiling error occurred during build.cmd under Unity directory 

### ISSUE THREAD

**Issue by eminem1984** [microsoft/AirSim#3254]
Hi, i am wondering if anyone can help me on this issue - I pretty stuck in the building process of AirSim,  I am now inside of the Unity directory and tried to build the project, but then this error pops up: 

> LINK : fatal error LNK1181: cannot open input file 'MavLinkCom.lib' [C:\AirSim\Unity\AirLibWrapper\AirsimWrapper\Airsim

Wrapper.vcxproj]

I tried to manually add the MavLinkCom.lib to the VS project as additional dependencies, but still got the same error. What have I missed?  Thanks a lot. 

For your information - i am using windows10, VS2019 and Unity2019.

**Comment by rajat2004** [comment]
Is this happening when running `build.cmd` from the Unity directory? That would be strange, since it seems to working correctly on the Github Actions CI
Could you post the entire output? The above message would happen if there was a compilation failure earlier and hence it wasn't able to generate the library. Update AirSim to the latest master and try again

**Comment by jonyMarino** [comment]
Hi @eminem1984, and welcome!
Please, next time, fill the issue template.
It seems that you are trying to compile AirsimWrapper.sln. Can you use `build.cmd`  from the Unity directory only?

**Comment by RoonLoe** [comment]
Hi @eminem1984 can you tell me where you found MavLinkCom.lib. I am running into, perhaps, a similar issue, but I cannot find even find the file. 
![image](https://user-images.githubusercontent.com/62959431/105004230-8135bf00-59e8-11eb-96fa-26e7d3ddb692.png)

**Comment by jonyMarino** [comment]
@eminem1984, are you still having this issue?

**Comment by eminem1984** [comment]
> @eminem1984, are you still having this issue?

many thanks for the replies, just got overwhelmed by other stuff and didn't get time to look into this anymore, so better to close the issue for now.
