### ISSUE TITLE
Is there a way of setting the Position of a vehicle while the simulator is running?

### ISSUE THREAD

**Issue by MarvinKlemp** [microsoft/AirSim#3255]
### What's your question?
Is there a way of setting the GPS Position while the simulator is running?

### Include context on what you are trying to achieve
I'm trying to set a vehicle to different positions while the simulator is running. I did not find a method to set the position of the car other than restarting with a different settings.json (requires to restart the simulator each time).

### Include details of what you already did to find answers
Search the repository. But could not really find a solution.

**Comment by rajat2004** [comment]
[`simSetVehiclePose`](https://microsoft.github.io/AirSim/api_docs/html/#airsim.client.VehicleClient.simSetVehiclePose) might be what you're looking for, you can move the vehicle as required in the environment, and the GPS position will change accordingly.
The other interpretation of your issue would be to change just the GPS values, and not the position in the environment itself, which doesn't make much sense

**Comment by MarvinKlemp** [comment]
Thanks that's exactly what I was looking for
