### ISSUE TITLE
How to enable Roadwetness, RoadSnow and RoadLeaf in a Custom Unreal Environment?

### ISSUE THREAD

**Issue by GilmarCorreia** [microsoft/AirSim#3256]
### What's your question?

 How to enable Roadwetness, RoadSnow, and RoadLeaf in a Custom Unreal Environment?

### Include context on what you are trying to achieve

Hello developers community,

I'm trying to create a Custom Unreal Environment, it is working pretty well, but when I'm trying to enable Roadwetness, RoadSnow, or even RoadLeaf it doesn't seem to work. Is there any prop that should I put in Unreal to enable these features?

#### Context details
OS: Windows 10
AirSim: 1.3
Python:  3.8.5
Unreal: 4.24

### Include details of what you already did to find answers
N/A

**Comment by ahmed-elsaharti** [comment]
@GilmarCorreia were you able to get weather effects to work with the blocks environment or any of the binaries?

I've tested adding weather effects to multiple of the pre-built binaries (and a blocks binary built a week ago) but the F10 button doesn't bring up the weather menu anymore. 
The weather menu shows up when running the sim using the UE editor but is blank:
![image](https://user-images.githubusercontent.com/49626509/103241451-e716b580-4918-11eb-97b1-c47342b802b7.png)
I also did receive a couple of compilation errors for the BP responsible for that menu:
![image](https://user-images.githubusercontent.com/49626509/103241507-0a416500-4919-11eb-9819-58554db33ec5.png)
![image](https://user-images.githubusercontent.com/49626509/103241522-162d2700-4919-11eb-9f07-e1c1c83f5475.png)

@jonyMarino @zimmy87 any ideas?

**Comment by GilmarCorreia** [comment]
Hello @ahmed-elsaharti, I'm facing the same problem. It seems that the weather widgets for UI are disabled and not showing when you hit F10. To enable it I'm using a python client to set the configurations for each weather parameter.

**Comment by saihv** [comment]
@ahmed-elsaharti That is likely because there was an error in the options menu blueprint, which #3240 was trying to fix. Could you perhaps try with the latest master?

**Comment by ahmed-elsaharti** [comment]
@saihv Oh wow! My apologies, I did NOT see that PR. (I had a feeling I was going to regret not testing the latest master earlier 😅) 
On testing with the latest master and UE 4.25 (within the UE Editor):
![image](https://user-images.githubusercontent.com/49626509/103261207-40590600-4966-11eb-810a-15285fe04b75.png)

**Comment by saihv** [comment]
@ahmed-elsaharti Thanks for checking!

@GilmarCorrea To answer your original question, enabling Road-related
weather features for custom worlds is actually a bit involved and would
have to be done for each map. The concept generally involves using an
additional material over the texture of the road (example: white layer for
snow) and dynamically adjusting the blending of this material with the road
through the weather parameter. Similarly, road wetness can be done through
a water-like material and adjusting the roughness and specular properties
to get the right reflection. You might be able to find some Unreal Engine
tutorials online that talk about how to blend materials that way.

In the prebuilt binaries, Neighborhood is the only map (IIRC) that allows
users to change these options and see the related change visually appear.
Down the line, it might be possible to do this in a more level-agnostic
fashion but it hasn't been explored yet.

**Comment by GilmarCorreia** [comment]
Hello @saihv!

Thank you for your explanation, after rebuilding my project with the unreal engine 4.25 the F10 menu is now showing. I will study more about blending material in road assets. 

Thank you!
