### ISSUE TITLE
Want to access segmentation layer

### ISSUE THREAD

**Issue by kylegiddens** [Microsoft/AirSim#326]
Hi I want to be able to pull just segmentation layer and the corresponding images. Does anyone know how to do this? 
Thanks in advance :)
I believe around here may help but I'm not sure: 

1
--
for arg in sys.argv[1:]:
14 | cameraType = arg.lower()
15 |  
16 | cameraTypeMap = {
… |  
19 | "seg": AirSimImageType.Segmentation,
20 | "scene": AirSimImageType.Scene,

**Comment by sytelus** [comment]
You can use,
```
vector<uint8_t> image = client.simGetImage(0, DroneControlBase::ImageType::Segmentation);
```

See the [docs](https://github.com/Microsoft/AirSim/blob/master/docs/apis.md).
