### ISSUE TITLE
Communication model and OS model for drones in AirSim

### ISSUE THREAD

**Issue by AIKUUM** [microsoft/AirSim#3266]
### Overview:

I can see almost all features in AirSim, but AirSim lacks a communication model for communication between 'n' number of drones and OS related data for drones during a simulation. 

### Smaller Details: 

A communication model can be built in python for communication between 2 drones in AirSim. For example after drone 1 captures 'n' number of images, those images can be sent to drone 2 by using some efficient communication protocol. Also analysis of efficiency of communication can be done by varying the displacement between 2 drones. An OS model can also be built in Python for Drones which would show details of "Drone i" like total storage capacity of "Drone i", RAM of "Drone i" etc in AirSim.

### Nature of Request:  
- Addition

## Why would this feature be useful?
If the above mentioned features are built in AirSim, then it would be more like a real time drone experiment with real time communication which would take into account RAM, storage capacity, IP address, port number, system ID etc of drones.

**Comment by jonyMarino** [comment]
Hi @AIKUUM! This is out of the project scope. AirSim is a simulator that aims to simulate the drone's perception (cameras and sensors). All the things you are asking for can be accomplished on the client-side. Incorporating them into AirSim would be just an example of how to use it. I think you should delve into ROS more and ask in that community how to simulate RAM and communication in a drone-like way.
