### ISSUE TITLE
Build environment error :  LNK1181: cannot open input file 'rpc.lib' (VS2019, Unity)

### ISSUE THREAD

**Issue by david9705** [microsoft/AirSim#3294]
## Bug report 

- AirSim Version/#commit:  Latest Version AirSim download for github
- UE/Unity version: Unity 2019.4
- autopilot version: N/A
- OS Version: Windows 10
- Visual Studio 2019 Community

### What's the issue you encountered?

build environment error 
I follow the following website suggestion and fix all the bug except the last bug (**cannot open “rpc.lib”**) 

https://blog.csdn.net/yldmkx/article/details/108694287?fbclid=IwAR2mj22YrcQCJasPrEb-Y5LlnivKeYpJxpU6A4NyArAjUh_GaxHQupeOy6A

but I think the real problem is that rpc.lib is not put the correct path because I have generated the **rpc.lib** by CMAKE successfully.

Please tell me the correct path.

Thanks. 
   

<br><br>
Error Message 

<img width="960" alt="rpc" src="https://user-images.githubusercontent.com/26639927/104230685-d887dc80-5488-11eb-9aa0-a9e3fe7b13d3.png">
<br>

Path of rpc.lib

<img width="578" alt="path1" src="https://user-images.githubusercontent.com/26639927/104230819-0a00a800-5489-11eb-95c4-df0e76283c53.png">
 
<br>
Other file path

<img width="581" alt="path2" src="https://user-images.githubusercontent.com/26639927/104230878-1dac0e80-5489-11eb-9388-08a9fe979a62.png">

**Comment by rajat2004** [comment]
I believe you need to use the Developer Command Prompt instead of the x86 Native Tools one

**Comment by david9705** [comment]
@rajat2004  Developer Command Prompt cannot solve the problem. Thanks

**Comment by rajat2004** [comment]
That's pretty strange, Unity build is working on Github Actions CI atleast, which is using the Developer Command Prompt
The error is occuring when running `build.cmd` correct? Could you post the entire output in text format if possible? 
I'll also try it out when back on a Windows machine

**Comment by david9705** [comment]
Yes, the error is occuring when running `build.cmd`
<br> the follow is entire output and  use **x86 Native Tools** 

<br><br> <br>





C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>build.cmd

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>REM //---------- copy binaries and include for MavLinkCom in deps ----------

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>msbuild AirLibWrapper\AirsimWrapper.sln  /target:Clean /target:Build  /property:Configuration=Release /property:Platform=x64
Microsoft (R) Build Engine for .NET Framework 16.8.2+25e4d540b 版
Copyright (C) Microsoft Corporation. 著作權所有，並保留一切權利。

在此解決方案中一次建置一個專案。若要啟用平行建置，請新增 "-m" 參數。
已經開始建置於 2021/1/12 下午 05:54:41。
節點 1 (Clean;Build 目標) 上的專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper.sln"。
ValidateSolutionConfiguration:
  建置方案組態 "Release|x64"。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper.sln" (1) 正在節點 1 (Clean 目標) 上建置 "C:\Program Files (x86)\Micros
oft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (2)。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (2) 正在節點 1 (Clean 目標) 上建置 "C:
\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (3)。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (3) 正在節點 1 (Clean 目標) 上建置 "C:\Program Files (x86)\Microsoft Visual Studi
o\2019\Community\AirSim\MavLinkCom\MavLinkCom.vcxproj" (4)。
_PrepareForClean:
  正在刪除檔案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.tlog\MavLinkCom.lastbuildstate"。
CoreClean:
  正在刪除檔案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\lib\Win32\Debug\MavLinkCom.pdb"。
  正在刪除檔案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.pdb"。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\MavLinkCom.vcxproj" (Clean 目標) 建置完成。

專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (Clean 目標) 建置完成。

專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (Clean 目標) 建置完成。

專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper.sln" (1) 正在節點 1 (預設目標) 上建置 "C:\Program Files (x86)\Microsoft
Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (2:2)。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (2:2) 正在節點 1 (預設目標) 上建置 "C:\P
rogram Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (3:4)。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (3:4) 正在節點 1 (預設目標) 上建置 "C:\Program Files (x86)\Microsoft Visual Studio\
2019\Community\AirSim\MavLinkCom\MavLinkCom.vcxproj" (4:2)。
InitializeBuildStatus:
  由於指定了 "AlwaysCreate"，因此正在建立 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.tlog\unsuccessfulb
  uild"。
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\CL.exe /c /Icommon_utils /Iinclude /ZI /JMC /nologo /W3 /WX /d
  iagnostics:column /Od /Oy- /D _WIN32_WINNT=0x0600 /D _WIN32 /D WIN32 /D _SCL_SECURE_NO_WARNINGS /D _CRT_SECURE_NO_WARNINGS /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /G
  m- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom
  \temp\MavLinkCom\Win32\Debug\\" /Fd"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.pdb" /FR"C:
  \Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\\" /Gd /TP /analyze- /FC /errorReport:queue common_utils\Fil
  eSystem.cpp common_utils\ThreadUtils.cpp src\UdpSocket.cpp src\impl\UdpSocketImpl.cpp src\AdHocConnection.cpp src\impl\AdHocConnectionImpl.cpp src\impl\MavLinkFtpClie
  ntImpl.cpp src\impl\MavLinkNodeImpl.cpp src\impl\MavLinkTcpServerImpl.cpp src\impl\onecore\OneCoreFindSerialPorts.cpp src\impl\windows\WindowsFindSerialPorts.cpp src\
  MavLinkFtpClient.cpp src\MavLinkLog.cpp src\MavLinkMessageBase.cpp src\MavLinkMessages.cpp src\MavLinkNode.cpp src\Semaphore.cpp src\MavLinkTcpServer.cpp src\MavLinkV
  ehicle.cpp src\impl\MavLinkVehicleImpl.cpp src\MavLinkConnection.cpp src\impl\MavLinkConnectionImpl.cpp src\MavLinkVideoStream.cpp src\impl\MavLinkVideoStreamImpl.cpp
   src\serial_com\SerialPort.cpp src\serial_com\SocketInit.cpp src\serial_com\TcpClientPort.cpp src\serial_com\UdpClientPort.cpp src\serial_com\wifi.cpp
  FileSystem.cpp
  ThreadUtils.cpp
  UdpSocket.cpp
  UdpSocketImpl.cpp
  AdHocConnection.cpp
  AdHocConnectionImpl.cpp
  MavLinkFtpClientImpl.cpp
  MavLinkNodeImpl.cpp
  MavLinkTcpServerImpl.cpp
  OneCoreFindSerialPorts.cpp
  WindowsFindSerialPorts.cpp
  MavLinkFtpClient.cpp
  MavLinkLog.cpp
  MavLinkMessageBase.cpp
  MavLinkMessages.cpp
  MavLinkNode.cpp
  Semaphore.cpp
  MavLinkTcpServer.cpp
  MavLinkVehicle.cpp
  MavLinkVehicleImpl.cpp
  正在產生程式碼...
  正在編譯...
  MavLinkConnection.cpp
  MavLinkConnectionImpl.cpp
  MavLinkVideoStream.cpp
  MavLinkVideoStreamImpl.cpp
  SerialPort.cpp
  SocketInit.cpp
  TcpClientPort.cpp
  UdpClientPort.cpp
  wifi.cpp
  正在產生程式碼...
Lib:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\Lib.exe /OUT:"C:\Program Files (x86)\Microsoft Visual Studio\2
  019\Community\AirSim\MavLinkCom\lib\Win32\Debug\MavLinkCom.lib" /LIBPATH:\stage\lib /NOLOGO /MACHINE:X86 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Communit
  y\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\FileSystem.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\ThreadUtils.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpSocket.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpSocketImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\AdHocConnection.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\AdHocConnectionImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkFtpClientImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkNodeImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkTcpServerImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\OneCoreFindSerialPorts.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\WindowsFindSerialPorts.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkFtpClient.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkLog.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkMessageBase.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkMessages.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkNode.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\Semaphore.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkTcpServer.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVehicle.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVehicleImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkConnection.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkConnectionImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVideoStream.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVideoStreamImpl.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\SerialPort.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\SocketInit.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\TcpClientPort.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpClientPort.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\wifi.obj"
  MavLinkCom.vcxproj -> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\lib\Win32\Debug\MavLinkCom.lib
BscMake:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x86\bscmake.exe /nologo /o"C:\Program Files (x86)\Microsoft Visual
   Studio\2019\Community\AirSim\MavLinkCom\lib\Win32\Debug\MavLinkCom.bsc" /n "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavL
  inkCom\Win32\Debug\FileSystem.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\ThreadUtils.sbr" "C:\P
  rogram Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpSocket.sbr" "C:\Program Files (x86)\Microsoft Visual Studio
  \2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpSocketImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp
  \MavLinkCom\Win32\Debug\AdHocConnection.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\AdHocConnect
  ionImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkFtpClientImpl.sbr" "C:\Program Files
  (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkNodeImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\C
  ommunity\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkTcpServerImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp
  \MavLinkCom\Win32\Debug\OneCoreFindSerialPorts.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\Windo
  wsFindSerialPorts.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkFtpClient.sbr" "C:\Program
  Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkLog.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\
  Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkMessageBase.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\
  MavLinkCom\Win32\Debug\MavLinkMessages.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkNode.s
  br" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\Semaphore.sbr" "C:\Program Files (x86)\Microsoft Visu
  al Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkTcpServer.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Mav
  LinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVehicle.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\M
  avLinkVehicleImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkConnection.sbr" "C:\Program
   Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkConnectionImpl.sbr" "C:\Program Files (x86)\Microsoft Visual
  Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkVideoStream.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavL
  inkCom\temp\MavLinkCom\Win32\Debug\MavLinkVideoStreamImpl.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\
  Debug\SerialPort.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\SocketInit.sbr" "C:\Program Files (
  x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\TcpClientPort.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Comm
  unity\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\UdpClientPort.sbr" "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCo
  m\Win32\Debug\wifi.sbr"
CopyFilesToOutputDirectory:
  正在將檔案從 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.pdb" 複製到 "C:\Program Files (x86)\Micros
  oft Visual Studio\2019\Community\AirSim\MavLinkCom\lib\Win32\Debug\MavLinkCom.pdb"。
FinalizeBuildStatus:
  正在刪除檔案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.tlog\unsuccessfulbuild"。
  正在變更時間戳記 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\temp\MavLinkCom\Win32\Debug\MavLinkCom.tlog\MavLinkCom.lastbuildstate"。
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\MavLinkCom\MavLinkCom.vcxproj" (預設目標) 建置完成。

PrepareForBuild:
  正在建立目錄 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\AirLib.tlog\"。
InitializeBuildStatus:
  由於指定了 "AlwaysCreate"，因此正在建立 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\AirLib.tlog\unsuccessfulbuild"。
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\CL.exe /c /Iinclude /Ideps\eigen3 /Ideps\rpclib\include /I"C:\
  Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\..\MavLinkCom\include" /Zi /nologo /W4 /WX /diagnostics:column /O2 /Oi /GL /D NDEBUG /D _SCL_
  SECURE_NO_WARNINGS /D _CRT_SECURE_NO_WARNINGS /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++17 /Fo"C:\
  Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\\" /Fd"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\
  AirSim\AirLib\temp\AirLib\x64\Release\AirLib.pdb" /Gd /TP /FC /errorReport:queue /w34263 /w34266 src\api\RpcLibClientBase.cpp src\api\RpcLibServerBase.cpp src\vehicle
  s\multirotor\api\MultirotorApiBase.cpp src\safety\ObstacleMap.cpp src\safety\SafetyEval.cpp src\common\common_utils\FileSystem.cpp src\vehicles\car\api\CarRpcLibClien
  t.cpp src\vehicles\car\api\CarRpcLibServer.cpp src\vehicles\multirotor\api\MultirotorRpcLibClient.cpp src\vehicles\multirotor\api\MultirotorRpcLibServer.cpp
  RpcLibClientBase.cpp
  RpcLibServerBase.cpp
  MultirotorApiBase.cpp
  ObstacleMap.cpp
  SafetyEval.cpp
  FileSystem.cpp
  CarRpcLibClient.cpp
  CarRpcLibServer.cpp
  MultirotorRpcLibClient.cpp
  MultirotorRpcLibServer.cpp
Lib:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX86\x64\Lib.exe /OUT:"C:\Program Files (x86)\Microsoft Visual Studio\2
  019\Community\AirSim\AirLib\lib\x64\Release\AirLib.lib" rpc.lib /LIBPATH:deps\rpclib\lib\x64\Release /NOLOGO /MACHINE:X64 /LTCG "C:\Program Files (x86)\Microsoft Visu
  al Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\RpcLibClientBase.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\RpcLibServerBase.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\MultirotorApiBase.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\ObstacleMap.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\SafetyEval.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\FileSystem.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\CarRpcLibClient.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\CarRpcLibServer.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\MultirotorRpcLibClient.obj"
  "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\temp\AirLib\x64\Release\MultirotorRpcLibServer.obj"
LINK : fatal error LNK1181: 無法開啟輸入檔 'rpc.lib' [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj]
專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (預設目標) 建置完成 -- 失敗。

專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (預設目標) 建置完成 -- 失敗 。

專案 "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper.sln" (Clean;Build 目標) 建置完成 -- 失敗。


建置失敗。

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper.sln" (Clean;Build 目標) (1) ->
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity\AirLibWrapper\AirsimWrapper\AirsimWrapper.vcxproj.metaproj" (預設目標) (2:2) ->
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj" (預設目標) (3:4) ->
(Lib 目標) ->
  LINK : fatal error LNK1181: 無法開啟輸入檔 'rpc.lib' [C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\AirLib\AirLib.vcxproj]

    0 個警告
    1 個錯誤

經過時間 00:00:58.80

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>if ERRORLEVEL 1 goto :buildfailed

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>echo(


C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>echo #### Build failed - see messages above.  1>&2
#### Build failed - see messages above.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>exit /b 1

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\AirSim\Unity>`

**Comment by ahmed-elsaharti** [comment]
@david9705 It looks to me link the guide you're using misses the step of building Airsim using `build.cmd` __under the Airsim main directory__ (ie: going to the Airsim directory with the developer command prompt and running build.cmd) . Try following [this guide](https://microsoft.github.io/AirSim/Unity/) and see if the problem persists.

**Comment by david9705** [comment]
Hello, @ahmed-elsaharti   [this guide](https://microsoft.github.io/AirSim/Unity/) tell use `build.cmd` in the **AirSim\Unity directory**

**Comment by ahmed-elsaharti** [comment]
Hi @david9705, this is the section i'm refering to:
![image](https://user-images.githubusercontent.com/49626509/104367870-01d45700-54e1-11eb-82dc-1555718804ca.png)

**Comment by ahmed-elsaharti** [comment]
tbh at this point I would recommend just recloning the repo and starting from scratch while following the official guide. I'm trying to figure out what issue your prompt is having with the download_install section but with no luck.

**Comment by david9705** [comment]
@ahmed-elsaharti  Thanks your suggestion. I'll recloning the repo later and report the result in this issue.  I guess the x64 command prompt maybe relevant.

**Comment by david9705** [comment]
I solve the bug and `build.cmd` success now.

Open **AirSim\AirLib\AirLib.vcxproj** in VS2019 and we can see two project .One is **AirLib**  and the other is **AirSimWrapper**.

<br>

_(The follow chinese word I'm not sure those in english. )_


<br><br>

### In AirLib project
You should generate **rpc.lib**  first.
<br>
Right click the AirLib project and click **properties**.
Go to **manifest Tool > General > Additional Dependencies** and add the **rpc.lib** file path.
Finally, rebuild AirLib or use  `build.cmd` in command prompt .


<br>

![rpc](https://user-images.githubusercontent.com/26639927/104561036-b5744d00-5681-11eb-96f6-d2477af3917f.png)

<br>
In AirSimWrapper project has similar problem but only to set the build configurations and platform and rebuild MavLinkCom.lib.

<br><br><br>

Now I open project in Unity2019.4 , and there still have bugs....
If I cannot solve those problem, maybe open a new issue later.
