### ISSUE TITLE
MavLinkCom/include files aren't included in AirLib/include/controllers

### ISSUE THREAD

**Issue by ajberchek** [Microsoft/AirSim#332]
I use ubuntu, and followed the Linux build guide to build AirSim. After building Unreal Engine 4.15, I translated the update_from_git.bat commands to bash, resulting in the Plugins/AirSim and AirLib directories being copied over into the Blocks directory. However, when I go to launch and build it with UnrealFrontend, it errors out saying that it cant find MavLinkConnection.hpp. After I move that over to the Plugins/AirSim/Source/AirLib/include/controllers directory, I tried to build it again, but a new file couldn't be found. After moving all the files over from MavLinkCom/include, everything was built properly. Can a copy of those MavLinkCom/include files to AirLib/include/controllers be added to the build.sh file in order to automate this process and decrease the difficulty of building this to those unfamiliar with bash?

**Comment by sytelus** [comment]
This should be fixed now. Please try out the new build: https://github.com/Microsoft/AirSim/blob/master/docs/linux_build.md
