### ISSUE TITLE
Implementing A3C Reinforcement Learning with Airsim

### ISSUE THREAD

**Issue by Deepakgthomas** [microsoft/AirSim#3327]
### 

I am trying to train my agent using A3C using Airsim API and Unreal as the environment. I found a previous issue https://github.com/microsoft/AirSim/issues/563, that seems to address how to run multiple instances of Airsim.  However, when I tried opening a few Unreal environments and it seemed like they were consuming 100% of my CPU, without even running the algorithm. During execution, A3C will be training 2 neural networks/1 neural network with 2 heads with other minor computations going on in the background.  I am completely fine if I'd have to move to another environment such as Unity to get this task done.

**Comment by ahmed-elsaharti** [comment]
@Deepakgthomas Is each instance a compiled/cooked binary or is all this running through the UE editor?
I just ran a couple of tests and it seems (to my surprise) like running the same environment through the UE editor consumes less CPU power.

**Comment by Deepakgthomas** [comment]
I am not sure what a cooked binary is (I am a newbie to this stuff). I have a Unreal environment that I have integrated with the Airsim API. In order to check how well it works, I opened multiple instances of the Environment (by launching the .uproject file).
Does that answer your question?

**Comment by ahmed-elsaharti** [comment]
No worries. A cooked binary is essentially a compiled 'game' executable. Something like the ones you can download from the [releases section](https://github.com/microsoft/AirSim/releases). But yes, what you just said does answer my question, it seems like you're running the environment within the editor. I'm not sure if moving to unity would improve things drastically (haven't tried Unity yet tbh). Try setting the viewmode in [settings.json](https://microsoft.github.io/AirSim/settings/) to 'NoDisplay' and see if it makes any difference.

**Comment by Deepakgthomas** [comment]
Wow, there definitely seems to be an improvement. But I distinctly another Github post saying that running 'headless' will disable the collision avoidance capabilities. Is that true?

**Comment by Deepakgthomas** [comment]
Here is a comment from the this [post](https://github.com/microsoft/AirSim/issues/563) - "I think you don't want render but you still want all objects in environment and collision detection. Unfortunately Unreal doesn't allow turning off rendering. It might be possible (its open source engine) but I don't know... But in any case, if you turn off rendering then you won't have ability to get screenshots or depth view etc." Do you know if this issue has been resolved?

**Comment by ahmed-elsaharti** [comment]
Hmm..I'm not sure if that's still the case.
I just tried retrieving an RGB image with NoDisplay mode and it worked. Try testing the collision feature using your script to see if that works too.

**Comment by Deepakgthomas** [comment]
I will do that! Thank you very much.
