### ISSUE TITLE
Is there any easy way to use MAVROS?

### ISSUE THREAD

**Issue by Nickvot** [Microsoft/AirSim#333]
Hi, I'm trying to develop a reinforcement learning system using the AirSim as an environment. I need IMU sensor data as the state, so I'm gonna receive it via MAVROS. I found a post in the "Issuses" and I got someone connected the AirSim and the MAVROS. Can someone share the knowledge how to connect them? Of course there is a tutorial about intercepting MavLink messages, however using MAVROS would make it much more easy to use the AirSim as an environment for RL.

**Comment by KeeganVG** [comment]
Did you by chance ever figure this out? I'd be interested if you did.

**Comment by sytelus** [comment]
simple_flight is available now and is default. This eliminates need to setup PX4.

Closing this as dup of https://github.com/Microsoft/AirSim/issues/53
