### ISSUE TITLE
Airsim Crashing When Collecting Images 

### ISSUE THREAD

**Issue by vatsagandhi** [Microsoft/AirSim#334]
I am flying and collecting images in Airsim through Mavros and the new image retrieving API. When the drone is stationary or flying, there are no errors. However, when I start collecting images, Airsim eventually crashes. I have tested this scenario multiple times with the same end result. 

This is the notification I get when Airsim abruptly crashes.

![capture](https://user-images.githubusercontent.com/8853701/28093720-45e30b0a-665e-11e7-97ea-89c950c844e3.PNG)

This is my settings file.

![settings](https://user-images.githubusercontent.com/8853701/28093800-a1d2f9de-665e-11e7-80d7-22352acfc810.PNG)

**Comment by sytelus** [comment]
Are you using latest version? I fixed these crashes yesterday and stress tested it. Try out the new version. You might be also interested in "ComputerVision" mode. See [docs](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md) for more info.
