### ISSUE TITLE
I can't find the UAV in SILT, and how to solve it?

### ISSUE THREAD

**Issue by fanguu** [Microsoft/AirSim#335]
![1](https://user-images.githubusercontent.com/21071524/28100579-8c49f47c-66f5-11e7-9e34-a54218fdd0e8.png)
![2](https://user-images.githubusercontent.com/21071524/28100580-8c4ae544-66f5-11e7-8634-a6d8786d81dd.png)

**Comment by lukaszdworako** [comment]
From the collision counter it looks like it may have been placed in the mountains (meaning it is perhaps halfway in and halfway out of a mountain causing collisions).

**Comment by sytelus** [comment]
Find "Player Start" in your environment in Unreal Editor. The instance of quadrotor is created at the Player Start. If you don't have one then add one in your environment.
