### ISSUE TITLE
Unity Demo Load With Error

### ISSUE THREAD

**Issue by ClarkZha** [microsoft/AirSim#3350]
AirSim Version/#commit: 1.4.0
UE/Unity version: Unity 2019.3.12.f1
autopilot version: - N/A
OS Version: Ubuntu 18.04

### Error Occurred when loading Unity demo. 

When opening the Unity demo following instructions on [https://microsoft.github.io/AirSim/Unity/#usage](url), following errors pop up: 
![image](https://user-images.githubusercontent.com/39609430/106340427-9dd6c000-624e-11eb-92b6-7f351fdf4c31.png)

Detailed message of the error is showing as following:
1.`"Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs(199,76): error CS0103: The name 'fov_degrees' does not exist in the current context"`
2.`Assets/AirSimAssets/Scripts/Vehicles/VehicleCompanion.cs(199,45): error CS1061: 'IVehicleInterface' does not contain a definition for 'SetDistortionParam' and no accessible extension method 'SetDistortionParam' accepting a first argument of type 'IVehicleInterface' could be found (are you missing a using directive or an assembly reference?)`

As a result, the Unity demo won't run after pressing the play button.

No errors were reported during the process of building AirSim and AirsimWrapper Shared Library. SimModeSelector scene is also loaded into the scene hierarchy pane.
![image](https://user-images.githubusercontent.com/39609430/106340831-efcc1580-624f-11eb-8c08-d3949e4d8dc0.png)

Any help or suggestions on how to debugging this is extremely appreciated.

**Comment by rajat2004** [comment]
Maybe try #3343 and see if it fixes the problem. Best to comment on the PR itself regarding the results

**Comment by ClarkZha** [comment]
Thanks Rajat! Your PR fixes the problem perfectly. I am going to close the issue.
