### ISSUE TITLE
Custom and normal drone

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3352]
Hi!

So I know how to get multiple of the same drones flying. But I was curious if there was anyway I could get both a custom and a default drone flying or even 2 custom drones of different type?

Thanks in advance

**Comment by rajat2004** [comment]
I believe the `PawnPath` setting is there for per-vehicle as well, that should work

**Comment by EdwinMeriaux** [comment]
I've been trying to put multiple different drones in the pawnpaths.
But when I spawn the drones how do I specify which drone is which path?

**Comment by rajat2004** [comment]
Something like below I guess -
```json
"Vehicles": {
  "Drone1": {
    ...
    "PawnPath": "Path1"
  },
  "Drone2": {
    ...
    "PawnPath": "Path2"
  }
}
```

**Comment by EdwinMeriaux** [comment]
Perfect Thanks!
