### ISSUE TITLE
EIGEN_ROOT setting problem

### ISSUE THREAD

**Issue by NeverStopMata** [Microsoft/AirSim#336]
![image](https://user-images.githubusercontent.com/20719573/28113927-2d1cb55c-6731-11e7-9fc2-a1750391ad58.png)
After the build completed, I **didn't** have ~/AirSim/eigen. So I downloaded the eigen by myself from the link in the install_eigen.md.
When I have released eigen package, I have no idea which folder shoud be set as EIGEN_ROOT.
The structure of the eigen looks like:
![image](https://user-images.githubusercontent.com/20719573/28114118-02f0af44-6732-11e7-91d0-228563b97ca2.png)

I want to know which folder in the eigen should be **EIGEN_ROOT**.

**Comment by sytelus** [comment]
Are you using build.sh in Linux? Just open up that script and you would see small script code that downloads and installs the eigen (i.e. basically wget).
