### ISSUE TITLE
New Airsim Commit Is Not Building

### ISSUE THREAD

**Issue by exploke** [Microsoft/AirSim#337]
The latest commit of Airsim is giving me errors when I attempt to build the solution. I have reinstalled Airsim several times with the same results. Using the Airsim commit prior to the latest commit is working perfectly for me.

Here are the errors I am receiving.
![errors](https://user-images.githubusercontent.com/25913167/28136661-15e36712-6710-11e7-837b-1b8ae6495352.PNG)

**Comment by lukaszdworako** [comment]
Appears as though their "Fix for Linux" has caused some kind of error for windows. @sytelus can you advise as to what may have gone wrong?

**Comment by sytelus** [comment]
Could you please try the latest code? I just tested in Windows and seems to work fine.
