### ISSUE TITLE
why the captured images not same as the seen image in running window of unreal engine

### ISSUE THREAD

**Issue by lucafei** [microsoft/AirSim#3377]
hi， guys, i'm using airsim to collect scene images in unreal engine. I 'm meeting a problem about images capturing. I want to set different light intensity in unreal engine and meanwhile capture scene image with different light intensity. But i find the captured images don't indicate the cooresponding light intensity. I use AirSim 1.3 installed by pip command and windows 10 plattform. 
the picture in running window of unreal engine
![Capture](https://user-images.githubusercontent.com/29920326/107996917-dcf06980-6fe1-11eb-8f80-5556f59e457c.PNG)
a example of captured images:
![0073](https://user-images.githubusercontent.com/29920326/107996988-0f01cb80-6fe2-11eb-9caa-ab5338c4b063.png)
As you see, the light condition seems like not being captured, Do you guys have any idea for that? Thank you in advance

**Comment by jonyMarino** [comment]
dup of #3501

**Comment by jonyMarino** [comment]
@lucafei, can you try with [this](https://github.com/microsoft/AirSim/issues/387#issuecomment-932607229) solution?
