### ISSUE TITLE
Simple Flight & MAVLinkCom

### ISSUE THREAD

**Issue by RodgerLuo** [Microsoft/AirSim#339]
This is a follow-up of issue 331([https://github.com/Microsoft/AirSim/issues/331](url)). Will Simple Flight controller still use MAVLinkCom for communication? We intend to dive into MAVLinkCom to make PC inject remote controller.

**Comment by sytelus** [comment]
No, SimpleFlight works in-process and so it can directly communicate using C++ class APIs, no MavLink layer is needed or desirable. The idea is that you use RPC API to talk to drone, not MavLink. If your controller is PX4 then RPC API will translate everything to MavLink. If its simple_flight then it will just use direct C++ layer.
