### ISSUE TITLE
Windows 10 Anniversary Update Bash installs Ubuntu 14.04 by default

### ISSUE THREAD

**Issue by DanWilson00** [Microsoft/AirSim#34]
When installing the Windows Bash in Windows 10 Anniversary Update, Ubuntu 14.04 is installed instead of 16.04. This means an older CMake is installed and CMake fails when building PX4 SITL.

Workaround is here - https://www.howtogeek.com/278152/how-to-update-the-windows-bash-shell/

**Comment by lovettchris** [comment]
Yep.  The [Linux build ](https://github.com/Microsoft/AirSim/blob/master/docs/linux_build.md) instructions show how to update cmake.
