### ISSUE TITLE
Can I have more than one client when using API?

### ISSUE THREAD

**Issue by ShukuiZhang** [Microsoft/AirSim#340]
I'm trying to get scene and depth images with high synchronization quality, but for now, it still seems to be an [issue](https://github.com/Microsoft/AirSim/issues/244) . 
Previously I was able to get scene image and depth image with very close time stamps using windows function and multiprocessing, but this method does not give the time instant images are generated. So I was thinking to use multiprocessing with AirSim APIs, e.g. using two processes to run simGetImages(), with scene and depth image request respectively. But it looks that the code can only take one client at a time. So I was wondering if there is any way that I can have more than one client in a program. If yes, how to do that? Thank you!

**Comment by sytelus** [comment]
You shouldn't face synchronization issue as images are generated in same tick. Currently multiple clients are not supported (the client API follows same model as ROS action server). Also, even if it did I'm not sure how that would solve synchronization issue.
