### ISSUE TITLE
How to control UAV in SILT?

### ISSUE THREAD

**Issue by fanguu** [Microsoft/AirSim#341]
I follow the guide and want to control the UAV in SILT. My coumpter is win10 ,i7-6700k and gtx1080.  The setting is
![1](https://user-images.githubusercontent.com/21071524/28149499-9d8f1304-67c0-11e7-8895-b5c5d3d34fb5.png)
When I enter the play button, the pix4 gives the information as follow.
![2](https://user-images.githubusercontent.com/21071524/28149545-0ebccff8-67c1-11e7-84ba-89ef2ae11b94.png)
Moreover, the UAV can't move in the UE4.15 as shown follow.
![3](https://user-images.githubusercontent.com/21071524/28149599-83804356-67c1-11e7-9387-d6bf3d51967c.png)
So I want to ask how to take off or move the UAV.

**Comment by exploke** [comment]
I moved the the LocalHostIP line to above the LogViewerHostIP. That seemed to work for me.

![image error](https://user-images.githubusercontent.com/25913167/28176803-559fe2aa-67be-11e7-9986-3842848baa16.PNG)

**Comment by fanguu** [comment]
I changed the LogViewerHostIP, but the UAV also can't mvoe. 
![qq 20170714141441](https://user-images.githubusercontent.com/21071524/28200541-5b072d48-689f-11e7-9fad-920733d724cb.png)
The gps setting is error??

**Comment by fanguu** [comment]
I find my qusetions and restart the UAV program. Now I can control the UAV in Droneshell, but the command is tedious. Can we control the UAV by keboard?

**Comment by AndrewEj** [comment]
Hello, how do you solve the problem ?
