### ISSUE TITLE
Mac OS libc++ library 

### ISSUE THREAD

**Issue by AndrewEj** [Microsoft/AirSim#342]
I was trying to build without doing this: 
![image](https://user-images.githubusercontent.com/22722252/28165386-6c367a50-6788-11e7-9c6d-c700b52ba308.png)
Then there is a error: Cannot find the settting.cpp file; So I deleted it, and the build went through. But the plugin apparently has some troubles. The airsim cannot be compiled. So I returned to the previous step and tried to do bash getlibcxx.sh; But there is a new trouble coming out, shown below: 
![image](https://user-images.githubusercontent.com/22722252/28165359-57222a38-6788-11e7-8e26-63d00480eb9d.png)

**Comment by AndrewEj** [comment]
I did some modification on getlibcxx.sh and solved the problem. I  commented out the install--.. line. I don't know whether it gonna affects my other procedure or not.

**Comment by sytelus** [comment]
Can you try please latest version. Settings.cpp was deleted some time ago but unfortunately CMakeLists wasn't updated which is why you were getting error.

I think you are mixing up two different thing, compiling AirSim and getlibcxx.sh. The later one is independent library.
