### ISSUE TITLE
How to change AirSim standart drone mesh to my drone or standart car to my car

### ISSUE THREAD

**Issue by Supaple-x** [microsoft/AirSim#3424]
### I have tried to find the actor of standart AirSimDrone and change it in ue. But I didn't find.
Do someone have any tutorial how to perform this customization?

Thanks

**Comment by ahmed-elsaharti** [comment]
Hi @Supaple-x , to change the drone/car mesh in AirSim you'd have to modify the AirSim uasset for the vehicle or create a similar one. To do so, have a look at #3190, [this guide](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#pawnpaths) and this video:
https://drive.google.com/file/d/1-iOfJ8zO3YA4Mzc0ZkKwTM3L4--4RFtt/view?usp=sharing

**Comment by Supaple-x** [comment]
Hi @ahmed-elsaharti ,
Thank you! This tutorial compleatly meets my targets.
Very detailed and accurate.
All the best!
