### ISSUE TITLE
i am able to import my customized coaxial octacopter model into the blocks environment,but i am unaware of what has to be changed in the physics part for the drone so i require a proper assistance to complete my sitl

### ISSUE THREAD

**Issue by airsimdevdd** [microsoft/AirSim#3429]
i am able to import my customized coaxial octacopter model into the blocks environment,but i am unaware of what has to be changed in the physics part for the drone so i require a proper assistance to complete my sitl

**Comment by jonyMarino** [comment]
Hi @airsimdevdd! And welcome! I see you have opened discussion #3426  regarding this. So let's keep continue there.
