### ISSUE TITLE
Data stream in AirSim 

### ISSUE THREAD

**Issue by RichardM678** [Microsoft/AirSim#343]
Hey our research group is trying to use AirSim to stream the position data of drones.
Our current set-up is that, we have a Vicon camera system that can output the live position data in Matlab form and in Excel. We are interested in inputing the live data stream into AirSim, but the information we found is very limited in doing that. So I am wondering if it is possible to input the data stream into AirSim?

**Comment by sytelus** [comment]
Its fairly easy to do. Just use [simSetPose() API](https://github.com/Microsoft/AirSim/blob/master/Examples/StereoImageGenerator.hpp#L88).
