### ISSUE TITLE
Lost python files when call python API

### ISSUE THREAD

**Issue by AlexanderZ3** [microsoft/AirSim#3442]
### What's your question? 
Could anyone tell me where to get the lost files: character_control.py, DQNdrone.py? 
 
When I call the python API in VS2019, it pops up below errors:

![image](https://user-images.githubusercontent.com/29619650/109955544-9313bd00-7d1d-11eb-89e6-21b8e0f2878d.png)

Furthermore, I found the "DQNdrone.py" is also lost in the multirotor file. I follow the tutorial  https://airsim-fork.readthedocs.io/en/docs/apis.html#python-quickstart   
Actually, DQNcar.py and legacy_hello_car.py are also missed in the car file.  So could anyone know why this problem happens and how to solve it? Thanks a lot!
![image](https://user-images.githubusercontent.com/29619650/109955865-edad1900-7d1d-11eb-86d5-b99882a81908.png)

#### Context details

win10, Airsim 1.4,
UE 2.5, Python 3.6.12

**Comment by ahmed-elsaharti** [comment]
Hi @AlexanderZ3 , try following the [updated docs](https://microsoft.github.io/AirSim/apis/#python-quickstart).
The easiest way to run the demo python scripts is (as mentioned in the docs) to run `python scriptName` in your terminal (with python installed and the airsim and msgpack-rpc-python packages installed ofcourse) like:
`python hello_car.py` for example.

Nonetheless, the inclusion of outdated scripts that no longer exist will probably need to be corrected for in [PythonClient.pyproj](https://github.com/microsoft/AirSim/blob/master/PythonClient/PythonClient.pyproj)

**Comment by AlexanderZ3** [comment]
Hi @ahmed-elsaharti ， thanks for your reply! Problems are solved! This comment can be closed.
