### ISSUE TITLE
cv capture: RGB Image has no lights

### ISSUE THREAD

**Issue by tsaizhenling** [microsoft/AirSim#3471]
### What's your question?

why does image API capture image without lights? (no shadows are casted)

![3_0](https://user-images.githubusercontent.com/1062331/111256543-4781dd00-8654-11eb-9d2b-30ccca491441.png)
![Screenshot 2021-03-16 123715](https://user-images.githubusercontent.com/1062331/111256594-62545180-8654-11eb-953f-a484b3eae4de.png)

#### Context details

goal: trying to use airsim to capture depth and rgb for deeplearning

OS Windows 10
Unreal engine 4.25.4

set up a custom unreal environment with a scene from marketplace
clicked on play
ran a slightly modified cv_capture.py from examples provided
```
# In settings.json first activate computer vision mode: 
# https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#computer-vision-mode

import setup_path 
import airsim

import pprint
import tempfile
import os
import time

pp = pprint.PrettyPrinter(indent=4)

client = airsim.VehicleClient()

airsim.wait_key('Press any key to get camera parameters')
for camera_id in range(3):
    camera_info = client.simGetCameraInfo(str(camera_id))
    print("CameraInfo %d: %s" % (camera_id, pp.pprint(camera_info)))

airsim.wait_key('Press any key to get images')
tmp_dir = os.path.join("/mnt/c/Users/tsaiz/depthData", "airsim_drone")
print ("Saving images to %s" % tmp_dir)
try:
    for n in range(3):
        os.makedirs(os.path.join(tmp_dir, str(n)))
except OSError:
    if not os.path.isdir(tmp_dir):
        raise

pos = [
        [-2, -1],
        [-2, -2],
        [-2, -3],
        [-2, -4],
        ]
for x in range(len(pos)): # do few times
    #xn = 1 + x*5  # some random number
    client.simSetVehiclePose(airsim.Pose(airsim.Vector3r(pos[x][0], pos[x][1], -1), airsim.to_quaternion(0, 0, 2)), True)
    time.sleep(0.1)

    responses = client.simGetImages([
        airsim.ImageRequest("0", airsim.ImageType.Scene),
        airsim.ImageRequest("1", airsim.ImageType.Scene),
        airsim.ImageRequest("2", airsim.ImageType.Scene)])

    for i, response in enumerate(responses):
        if response.pixels_as_float:
            print("Type %d, size %d, pos %s" % (response.image_type, len(response.image_data_float), pprint.pformat(response.camera_position)))
            airsim.write_pfm(os.path.normpath(os.path.join(tmp_dir, str(x) + "_" + str(i) + '.pfm')), airsim.get_pfm_array(response))
        else:
            print("Type %d, size %d, pos %s" % (response.image_type, len(response.image_data_uint8), pprint.pformat(response.camera_position)))
            airsim.write_file(os.path.normpath(os.path.join(tmp_dir, str(i), str(x) + "_" + str(i) + '.png')), response.image_data_uint8)

    pose = client.simGetVehiclePose()
    pp.pprint(pose)

    time.sleep(3)

# currently reset() doesn't work in CV mode. Below is the workaround
client.simSetVehiclePose(airsim.Pose(airsim.Vector3r(0, 0, 0), airsim.to_quaternion(0, 0, 0)), True)
```

please find unreal project here:
https://drive.google.com/file/d/1Pdoax-zGxH_DZ2DNn8Ps-7u-hS_ZmKMo/view?usp=sharing

### Include details of what you already did to find answers

played with exposure and gamma settings in camera, no improvement

update:
rendering looks wrong in subwindow too

![Screenshot 2021-03-16 130516](https://user-images.githubusercontent.com/1062331/111258731-82860f80-8658-11eb-88d3-1e41508642e9.png)

**Comment by saihv** [comment]
@tsaizhenling Just FYI, this particular environment you are using uses real time ray tracing, which is an advanced feature that might be causing problems with the airsim cameras. Could you perhaps try with another sample environment from the marketplace to see if the same issue persists?

**Comment by kestrelm** [comment]
> @tsaizhenling Just FYI, this particular environment you are using uses real time ray tracing, which is an advanced feature that might be causing problems with the airsim cameras. Could you perhaps try with another sample environment from the marketplace to see if the same issue persists?

Hello,
Thanks for the answer. Is real-time ray-tracing not supported for AirSim cameras? Or is there some other way to get around it?

Thanks

**Comment by tsaizhenling** [comment]
tried landscapeMountains and it seems to be okay,

also tried turning off raytracing and now we got the scene and camera capture to match. the quality is a lot lower though :(

![Screenshot 2021-03-16 174736](https://user-images.githubusercontent.com/1062331/111290575-40bd8f00-8681-11eb-8650-3bf39348ca81.png)

is this a bug?

**Comment by tsaizhenling** [comment]
adding
r.RayTracing.SceneCaptures=True to DefaultEngine.ini fixed this issue
