### ISSUE TITLE
How to set imu noise while using python api

### ISSUE THREAD

**Issue by Chanchanhan** [microsoft/AirSim#3485]
### Include context on what you are trying to achieve
Hello everyone. 
The issue  [3293](https://github.com/microsoft/AirSim/issues/3293) shows the way to get imu noise params. So when I want is set my own imu noise params, I can change paramters in  [ImuSimpleParams](https://github.com/microsoft/AirSim/blob/master/AirLib/include/sensors/imu/ImuSimpleParams.hpp) and rebuild the airsim projects.
However, It's only useful for C++ api, how to get and set the same prameters while using python api?
### Include details of what you already did to find answers

I have read the code in [PythonClient](https://github.com/microsoft/AirSim/tree/master/PythonClient), but failed to find the code about add noise to imu data.

Thanks for your time!

**Comment by jonyMarino** [comment]
Hi @Chanchanhan! I have converted that issue into a discussion (#3523), so continue there, please.
I see that it is client code. So this is a matter of passing that C++ code to python
