### ISSUE TITLE
Problem Linking in Visual Studio

### ISSUE THREAD

**Issue by drdorianwhite** [Microsoft/AirSim#349]
I was unable to link during my build of the Unreal Project:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'C:\Program Files\Epic Games\UE_4.15\Engine\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-AirSim.lib'	LandscapeMountains	

Is this an issue on my end? If so, what was missed?

**Comment by sytelus** [comment]
Please make sure build is set to "DebugGameEditor" and not "Development". Also you might want to try clean so,union in VS from build menu.
