### ISSUE TITLE
Unable to make PX4 1.5.5 on Mac

### ISSUE THREAD

**Issue by AndrewEj** [Microsoft/AirSim#350]
My setup :
System: MacOS
i5 CPU @2.00 GHz
8GB RAM
SSD harddrive
RC : No RC
Flight controller : SITL
UE 4 Version: 4.15.3

When I use PX 1.5.5, I got this compile error. 
![image](https://user-images.githubusercontent.com/22722252/28297825-d7e33fa0-6b24-11e7-87d5-c2bc4095d1f2.png)

When I use the latest version of the PX, I can set up everything. 
![image](https://user-images.githubusercontent.com/22722252/28298442-2de5eeea-6b28-11e7-92dd-9bd0cedc2d78.png)
![image](https://user-images.githubusercontent.com/22722252/28298448-36df58ec-6b28-11e7-9e22-8af5c4a76ea2.png)
![image](https://user-images.githubusercontent.com/22722252/28298464-44433224-6b28-11e7-85da-7eaf9c575f5c.png)

However, I cannot control my drone. 

Please help.

**Comment by sytelus** [comment]
I think few people have reported this issue. The root cause is that AirSim is not able to connect to SITL. If you are familiar with QGroundControl, first try it out if you can connect with it.

**Comment by AndrewEj** [comment]
I think QGroundControl has already connected, but I don't know why there is no reaction inside UE4?  One stupid question is do you need a joystick or not ?

**Comment by sytelus** [comment]
Joystick is not required. I am wondering if this is related to crash I see on Linux. I will try to debug this tomorrow.

**Comment by AndrewEj** [comment]
Okay !  I don't know what's the problem with PX4 1.5.5;

**Comment by sifengyang** [comment]
@AndrewEj  Have you solve the problem？ my problem is "not receiving any message from HIL, please restart your HIL node and try again".

**Comment by AndrewEj** [comment]
@sifengyang not yet.. Yeah I have the same problem..

**Comment by sytelus** [comment]
First thing to try is make sure your PX4 setup is working with QGroundControl. That is, you should be able to arm, take off etc from QGC. If you can't then you have problem with PX4 setup and you probably want to report this to PX4 forums or Github issues at https://github.com/PX4/Firmware/issues.
