### ISSUE TITLE
Segmentation Image bug when running headless

### ISSUE THREAD

**Issue by KristofferFogh04** [microsoft/AirSim#3504]
## Bug report 
- AirSim Version/#commit: 1.4
- UE/Unity version: 4.25
- autopilot version:
- OS Version: tested on Ubuntu 18.04 and MacOS

### What's the issue you encountered?
This issue is a duplicate of #1724, but since it seems like it hasn't been resolved I want to know if anyone has found a solution. The problem happens when trying to grab segmentation images using the PythonClient API while running airsim in headless mode (ViewMode: "NoDisplay"). When doing this the returned image is a kind of color-distorted rgb image of the entire scene. No segmentations at all. I am using the simGetImages() for grabbing segmentation images.

This is what i want (recorded with ViewMode: Fpv):
<img width="501" alt="Skærmbillede 2021-03-22 kl  16 53 48" src="https://user-images.githubusercontent.com/56437299/112018992-532b4300-8b2f-11eb-934c-5022ca391d28.png">

This is what i get (recorded with ViewMode: NoDisplay):
<img width="502" alt="Skærmbillede 2021-03-22 kl  16 53 12" src="https://user-images.githubusercontent.com/56437299/112019049-5e7e6e80-8b2f-11eb-9c7a-f91be56ab204.png">

I hope someone can point me in the right direction for a fix. Thank you in advance!

**Comment by Zartris** [comment]
Did not solve this issue today, but we found a workaround.
The problem is when you use the default camera "0" to get the segmentation from.
An alternative (workaround) is to create your own front camera:
```
{
	"SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
	"SettingsVersion": 1.2,
	"SimMode": "Multirotor",
	"ClockSpeed": 1,
	"ViewMode": "NoDisplay",
	"Vehicles": {
		"SimpleFlight": {
			"VehicleType": "SimpleFlight",
			"DefaultVehicleState": "Armed",
			"AutoCreate": true,
			"PawnPath": "",
			"EnableCollisionPassthrogh": false,
			"EnableCollisions": true,
			"AllowAPIAlways": true,
			"RC": {
				"RemoteControlID": 0,
				"AllowAPIWhenDisconnected": false
			},
			"Cameras": {
				"cam": {
					"CaptureSettings": [
						{
							"ImageType": 0,
							"Width": 240,
							"Height": 180,
							"FOV_Degrees": 90,
							"AutoExposureSpeed": 100,
							"AutoExposureBias": 0,
							"AutoExposureMaxBrightness": 1,
							"AutoExposureMinBrightness": 1,
							"MotionBlurAmount": 0,
							"TargetGamma": 1.5
						},
						{
							"ImageType": 5,
							"Width": 240,
							"Height": 180,
							"FOV_Degrees": 90,
							"AutoExposureSpeed": 100,
							"AutoExposureBias": 0,
							"AutoExposureMaxBrightness": 1,
							"AutoExposureMinBrightness": 1,
							"MotionBlurAmount": 0,
							"TargetGamma": 1.5
						}
					],
					"X": 0.4,
					"Y": 0.0,
					"Z": 0.0,
					"Pitch": 0.0,
					"Roll": 0.0,
					"Yaw": 0.0
				}
			}
		}
	}
}
```
Then request the images from this camera instead of the "0".
`response = client.simGetImages([airsim.ImageRequest(
    "cam", airsim.ImageType.Segmentation, False, False)])[0]`
This should work in both "NoDisplay" and other modes.
