### ISSUE TITLE
DroneCommand Code Structure

### ISSUE THREAD

**Issue by fmzhu** [Microsoft/AirSim#353]
Hello, could anyone explain that, how  the "Control Command"  are sent to the PX4,  since the sensordata are sent through the "sendHILSensor " based on MAVLinkmessage, so how the "Control Command" works, is it a MAVLinkmessage too? Thank you very much!

**Comment by sytelus** [comment]
Can you elaborate what you mean by Control Command? All communication with PX4 are through MavLink messages.

**Comment by fmzhu** [comment]
@sytelus I mean the DroneShell Command, how are the Command sent to the PX4, because I want to make Networkfaultinjection between AirSim and PX4. Thank you very much for your attention!

**Comment by sytelus** [comment]
DroneShell talks to AirSim via RPC. The RPC call on AirSim side is handled by DroneControllerBase which in case of PX4 will translate the RPC command to MavLink command.

**Comment by fmzhu** [comment]
@sytelus thank you very much for your help! so would you please explain how are the RPC commands translated to the Mavlink commands. Thank you very much for your attention!

**Comment by lovettchris** [comment]
A picture helps:
![image](https://user-images.githubusercontent.com/18707114/28430997-7aa41ae8-6d37-11e7-896d-a71a23b6661e.png)

**Comment by fmzhu** [comment]
@lovettchris Thank you very much for your help, that's will be very helpful!
