### ISSUE TITLE
Python simGetImages: Attribute 'to_msgpack' missing

### ISSUE THREAD

**Issue by tkazik** [microsoft/AirSim#3533]
## Bug report 

- AirSim Version/#commit: latest / 6d20663e0818448613be0332009b02bd6341589e
- UE/Unity version:  4.26.1
- OS Version: Ubuntu 18.04 **and** 20.04

### What's the issue you encountered?

Running the superbasic tutorial `python3 hello_drone.py`: The script crashes while getting the images.

![airsim_image](https://user-images.githubusercontent.com/15689124/112650668-e88a4800-8e4b-11eb-8365-c582c5c099c0.png)

### Settings

=> default (installed `pip install msgpack-rpc-python`)

### How can the issue be reproduced?

every time on Ubuntu 18.04 and 20.04

### Include full error message in text form

```shell
    sock.send_message(message, callback)
  File "/home/xxx/anaconda3/envs/myCVLpy3/lib/python3.8/site-packages/msgpackrpc/transport/tcp.py", line 19, in send_message
    self._stream.write(self._packer.pack(message), callback=callback)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 263, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 277, in msgpack._packer.Packer._pack
  File "/home/xxx/anaconda3/envs/myCVLpy3/lib/python3.8/site-packages/msgpackrpc/transport/tcp.py", line 12, in <lambda>
    self._packer = msgpack.Packer(encoding=encodings[0], default=lambda x: x.to_msgpack())
AttributeError: 'function' object has no attribute 'to_msgpack'
```
Thx!

**Comment by hpsauce82** [comment]
I get the same error on Windows 10 running hello_car.py

**Comment by tkazik** [comment]
This is likely related to an issue with [msgpack-rpc-python](https://github.com/msgpack-rpc/msgpack-rpc-python), which is kind of old and does not work with tornado >= v5 (the current tornado version is 6.1). Probably because the msgpack-rpc-python package is not really maintained anymore, see https://github.com/msgpack-rpc/msgpack-rpc-python/issues/16. Anyone else has another take?

**Comment by mmorphew** [comment]
The solution suggested in #3553 fixed this error for me. To reiterate that fix, navigate to `AirSim/PythonClient/airsim/types.py`, and within that file, comment out both the entire `_ImageType` class, as well as the redefinition of the `ImageType` class that immediately comes after it. This reverts `ImageType` to use its first definition, in which each image type maps to an integer. After this step is completed, replace the instances of `ImageType` referenced in `hello_drone.py` with their corresponding integers for each `ImageRequest`. (For example, `airsim.ImageRequest("0", 0)`. The script should run successfully and output the images to the specified directory in the script. I have tested this with all image types on Ubuntu 20.04 and have been able to get successful outputs for all of them.

**Comment by Roopesh-Bharatwaj-K-R** [comment]
Hi guys , how you all managed to connect with Python Environment , i tried a lot but i could not able to connect it

**Comment by ahmed-elsaharti** [comment]
@Roopesh-Bharatwaj-K-R [This guide](https://microsoft.github.io/AirSim/apis/) could be a good place to start

**Comment by ahmed-elsaharti** [comment]
Also, can you guys try the solution suggested in [this comment](https://github.com/microsoft/AirSim/issues/3553#issuecomment-812933387) to see if its an issue with the python modules installed
