### ISSUE TITLE
Recording camera video.

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3558]
Hello!

So I was playing around with the camera system of the default airsim drone.
I know there are multiple cameras on the drone.
Is there any way to store the data from one specific cameras in a video format?

Thanks in advance!

**Comment by alonfaraj** [comment]
@EdwinMeriaux 
Do you mean record the stream itself in Unreal? I'm not familiar with any way to this.
Otherwise, you can create a video file from the images you grab with the python API - `getImage()`

**Comment by EdwinMeriaux** [comment]
@alonfaraj
Ok! thanks. I saw the pictures I was just curious is a straight up video could be recording. This makes sense! Thanks!
