### ISSUE TITLE
ExponentialHeightFog

### ISSUE THREAD

**Issue by icisneros** [microsoft/AirSim#3585]
- AirSim Version/#commit: 46a9b3a53811175e198e3608316fa4c983f7c53c
- UE/Unity version: Unreal Engine 4.25.4
- autopilot version: n/a
- OS Version: Ubuntu 18.04.5

Is there a way to prevent Airsim from spawning this element in Unreal Engine?  Currently, I have to manually reduce the Fog level to 0 (or disable its Visibility parameter) every time I start a new session, but this is cumbersome, prone to forgetting,  and prevents automating my workflow.  The python script that I run does not make any calls to simEnableWeather, so I don't know why Airsim spawns this element at all.

![Screenshot from 2021-04-12 17-20-34](https://user-images.githubusercontent.com/5514700/114466010-e519ef00-9bb5-11eb-8dbd-198b6cdf00b2.png)

**Comment by zimmy87** [comment]
Hi @icisneros, thanks for opening this issue. The ExponentialHeightFog actor is spawned inside the BeginPlay event of Blueprint'/AirSim/Weather/WeatherFX/WeatherActor.WeatherActor'. You can either prevent this actor from spawning by disconnecting the call to SpawnActor there or you can apply #3666 which will set this actor to be invisible until a weather parameter is set.

**Comment by icisneros** [comment]
Thanks for the response!  

I am somewhat new to this, and I haven't previously made changes to plugin files.  I have copied your versions of WeatherLib.cpp and WeatherLib.h from #3666 into my "MyCustomProject/Plugins/Airsim/Source/Weather/" directory, but now I am not sure how to compile this so that the changes take effect.  Should I have instead copied them into my local repo clone in "Airsim/Unreal/Plugins/Airsim/Source/Weather/" and run ./setup.sh and ./build.sh ?  I am working in Ubuntu.
