### ISSUE TITLE
SimpleFlightQuadX

### ISSUE THREAD

**Issue by EdwinMeriaux** [microsoft/AirSim#3591]
Hi! is the Simpleflightquadx moved?
I cannot find it anymore in the most recent version of Airsim Installed.

**Comment by ahmed-elsaharti** [comment]
Yup, the structure has changed since v1.1.0.
Currently, you would have to look at [Multirotorparams.hpp](https://github.com/microsoft/AirSim/blob/master/AirLib/include/vehicles/multirotor/MultiRotorParams.hpp) to change parameters like the mass, etc

**Comment by EdwinMeriaux** [comment]
@ahmed-elsaharti Sweet! thanks!

So same process as before: https://github.com/microsoft/AirSim/issues/3311

just new file where it all happens right?

**Comment by ahmed-elsaharti** [comment]
Precisely

**Comment by EdwinMeriaux** [comment]
Thank you so much!
