### ISSUE TITLE
Setting GPS origin

### ISSUE THREAD

**Issue by sifengyang** [Microsoft/AirSim#364]
I want to run  takeoff.py .  so I have to install TISL by sitl.md. I have completed the step ,"Software-In-Loop Simulation (SITL)". When I faced “Setting GPS origin”，I do not know how i do it.
![1](https://user-images.githubusercontent.com/22024525/28516280-3a2a4aa0-7093-11e7-8257-2a157f234373.png)

**Comment by fountainYuan** [comment]
Input these command in SITL console

**Comment by sifengyang** [comment]
@fountainYuan I use ubuntu system . how to I can find SITL console. thanks

**Comment by fountainYuan** [comment]
./build_posix_sitl_default/src/firmware/posix/px4 ./posix-configs/SITL/init/ekf2/iris


after connect AirSim 


press enter 


you will see




then input param set command




At 2017-07-24 17:20:11, "sifengyang" <notifications@github.com> wrote:


@fountainYuan I use ubuntu system . how to I can find SITL console. thanks

**Comment by sifengyang** [comment]
I can't do it by your way. I can't input the command under normal circumstances. Am I doing it wrong? however I find another problem on unreal. the message is "not receiving any message from HIL, please restart your HIL node and try again ".
![2](https://user-images.githubusercontent.com/22024525/28527878-8a5c8210-70be-11e7-96b9-d91be617913a.png)

**Comment by lukaszdworako** [comment]
That message only occurs when you are not using a pixhawk hardware controller, this is not an issue and should be nothing to worry about. What do you mean by "can't input under normal circumstances"?

**Comment by sifengyang** [comment]
@lukaszdworako  I am so sorry . it mean  is that I press  enter, then  input param set command, but SITL console prints 
"WARN  [lib__ecl] EKF baro hgt timeout - reset to baro
WARN  [lib__ecl] EKF baro hgt timeout - reset to baro
INFO  [commander] Landing detected
INFO  [commander] Takeoff detected
INFO  [commander] Freefall detected
INFO  [commander] Landing detected
INFO  [commander] Takeoff detected
INFO  [commander] Freefall detected
" Constantly. 
![3](https://user-images.githubusercontent.com/22024525/28551521-0fcb5654-711b-11e7-83ed-7c683843a21c.png)

**Comment by fountainYuan** [comment]
you can pause the Unreal block project  then output will pause,you can input command .
Or you can copy command to console then press enter to excute command







At 2017-07-25 09:24:56, "sifengyang" <notifications@github.com> wrote:


@lukaszdworako I am so sorry . it mean is that I press enter, then input param set command, but SITL console prints
"WARN [lib__ecl] EKF baro hgt timeout - reset to baro
WARN [lib__ecl] EKF baro hgt timeout - reset to baro
INFO [commander] Landing detected
INFO [commander] Takeoff detected
INFO [commander] Freefall detected
INFO [commander] Landing detected
INFO [commander] Takeoff detected
INFO [commander] Freefall detected
" Constantly.
