### ISSUE TITLE
Travis auto test

### ISSUE THREAD

**Issue by lukaszdworako** [Microsoft/AirSim#365]
Not sure if you guys noticed but currently the Travis CI auto test has been failing for the past almost 20 build tests. All of them have an error on clang++ and libc++. @sytelus

**Comment by Missyinvisible** [comment]
I have noticed, however, I had no problems with this new update.

**Comment by lukaszdworako** [comment]
You won't notice any issues on your end its just that the auto tester will never detect a build issue because every build will fail.

**Comment by sytelus** [comment]
This has been fixed.
