### ISSUE TITLE
AirSim with Cesium for Unreal Engine

### ISSUE THREAD

**Issue by petergerten** [microsoft/AirSim#3663]
Did anyone else try to use AirSim with [Cesium for Unreal Engine](https://github.com/CesiumGS/cesium-unreal)?

I have it working in principle, but there seem to be some strange effects:
- After takeoff (I use PX4 SITL) at the correct location, Cesium suddenly jumps to a location 1000's of kilometers away. This is reproducible and very strange. My GPS location is just a few meters off the takeoff point.
- When I move my camera off the default direction, the tile renderer does not notice that and won't load new tiles.

Eventually I fall into space ;-)
![2021-05-06-120741_3065x1683_scrot](https://user-images.githubusercontent.com/17756065/117240574-b5cc6a00-ae63-11eb-8669-3f72a7ada3db.png)

**Comment by petergerten** [comment]
=> disable 'keep origin near' seems to help

**Comment by Rick-Weng** [comment]
i have the same question of u, which made me sooooooo sad!
May i get the information about where i can find the " keep orign near'?
please~

**Comment by darkcherryx3** [comment]
You can find it under the CesiumGeoreference Instance you created.
