### ISSUE TITLE
Unable to control the Drone on Mac OS

### ISSUE THREAD

**Issue by AndrewEj** [Microsoft/AirSim#367]
My setup :
System: MacOS
i5 CPU @2.00 GHz
8GB RAM
SSD harddrive
RC : No RC
Flight controller : SITL
UE 4 Version: 4.15.3

I update Airsim and PX4 to the latest version and got everything set up. But I cannot control the drone in UE4. I don't think there is any issues with PX4, because it can communicate with QGroundControl. 

This is what I got from UE4. 

![image](https://user-images.githubusercontent.com/22722252/28552321-8cd11a4a-70a2-11e7-9bce-58bb9bf1ba18.png)

This is the result from PX4 when I typed "commander status"
![image](https://user-images.githubusercontent.com/22722252/28552153-98588480-70a1-11e7-9d54-cd555310fb9b.png)

I cannot find the reason..
Please help .

**Comment by AndrewEj** [comment]
This is what I got from  DroneShell. 

![image](https://user-images.githubusercontent.com/22722252/28552528-c3852260-70a3-11e7-9dca-6c8357775a5b.png)

**Comment by AndrewEj** [comment]
I try to setup Airsim on windows7. I used PX4 SITL on Mac to remotely control the drone on win7. Everything seems to be OK. But it repeats hit the ground

**Comment by sytelus** [comment]
First thing to try is make sure your PX4 setup is working with QGroundControl. That is, you should be able to arm, take off etc from QGC. If you can't then you have problem with PX4 setup and you probably want to report this to PX4 forums or Github issues at https://github.com/PX4/Firmware/issues.
