### ISSUE TITLE
API errors, possibly compatibility issue with TF?

### ISSUE THREAD

**Issue by tashahughes** [microsoft/AirSim#3673]
How to fix error code: ValueError: Unknown layer: Functional airsim. Expected 1 tensor but received 2 tensors. 

 I am trying to replicate the Imitation Learning tutorial and I am using the PythonClient APIs to connect a neural network model to the AirSim simulator in Unreal Engine. From the tutorial I was following, I noticed AirSim had updated their documentation, which meant I had to tweak the tutorial method slightly. After doing this I got the error code described in the question. 
Stackoverflow suggests this is due to a Tensorflow compatibility error, but I am unsure which TF version I would need. I am currently running on 2.4. I created the model.h5 file in the same way that the Imitation Learning tutorial shows. All previous tutorial scripts work and I get good results for the predictions, so I don't believe there is an issue in this regard.

Has anybody encountered this issue or does anyone have any suggestions as to what the issue is? Also I am terribly sorry for the formatting, I rarely use github.

Here is the adapted code from the tutorial.
```
import sys
import numpy as np
import glob
import os
from tensorflow.keras.models import load_model

if ('../../PythonClient/' not in sys.path):
    sys.path.insert(0, '../../PythonClient/')
    import airsim

modelpath = None

if(modelpath == None):
    models = glob.glob('model/models/*.h5')
    best = max(models,key = os.path.getctime)
    modelpath = best

model = load_model(modelpath)
client = airsim.CarClient()
client.confirmConnection()
client.enableApiControl(True)
carcontrol = airsim.CarControls()
print("Connected")

carcontrol.steering = 0
carcontrol.throttle = 0
carcontrol.brake = 0

imagebuffer = np.zeros((1,59,255,3))
statebuffer = np.zeros((1,4))

def getimage():
    imagefound = client.simGetImages([airsim.ImageRequest("0", airsim.ImageType.Scene, False, False)])[0]
    image1d = np.frombuffer(imagefound.image_data_uint8, dtype=np.uint8)
    imagergb = image1d.reshape(imagefound.height, imagefound.width,3)

    return imagergb[76:135,0:255,0:3].astype(float)

while (True):
    carstate = client.getCarState()

    if (carstate.speed < 5):
        carcontrol.throttle = 1

    else:
        carcontrol.throttle = 0

    imagebuffer[0]= getimage()
    statebuffer[0] = np.array([carcontrol.steering,carcontrol.throttle,carcontrol.brake,carstate.speed])
    modeloutput = model.predict([imagebuffer,statebuffer])
    carcontrol.steering = round(0.5*float(modeloutput[0][0]),2)

    client.setCarControls((carcontrol))
```

**Comment by jonyMarino** [comment]
> Stackoverflow suggests this is due to a Tensorflow compatibility error, but I am unsure which TF version I would need. 

I am not exactly sure, but I think it will definitely be 1.x, that tutorial was from before tf 2.0 was released

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
