### ISSUE TITLE
  File "E:\AirSim\PythonClient\airsim\utils.py", line 91, in to_quaternion     q = Quaternionr() NameError: name 'Quaternionr' is not defined

### ISSUE THREAD

**Issue by NachoDuL** [microsoft/AirSim#3675]
## Quaternionr not defined

- AirSim Version/#commit: 1.3
- UE/Unity version: 4.26
- autopilot version: ardupilot
- OS Version: Windows 10

### What's the issue you encountered?

I'm trying to move the drone gimbal using the Python API but I'm getting the following error when running gimbal.py file located in the PythonClient folder of AirSim. It says that Quaternionr it's not defined but it's defined in \AirSim\PythonClient\airsim\types.py

Why it doesn't recognize the class if it's defined? I think it could be a problem with the msgpack because I've had some issues using it with jupyter and I've had to reintall it. 
### Settings

{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.3,
  "LogMessagesVisible": true,
  "SimMode": "Multirotor",
  "ViewMode": "Fpv",
  "CameraDefaults": {
    "Gimbal": {
      "Stabilization": 1
    }
  },
  "OriginGeopoint": {
    "Latitude": 43.502228,
    "Longitude": -1.539775,
    "Altitude": 7
  },
  "PawnPaths": {
    "DefaultQuadrotor": { "PawnBP": "Class'/AirSim/Blueprints/BP_MyPawn.BP_MyPawn_C'" }
  },
  "Vehicles": {
    "Copter": {
      "VehicleType": "ArduCopter",
      "UseSerial": false,
      "LocalHostIp": "192.168.88.185",
      "UdpIp": "192.168.88.185",
      "UdpPort": 9003,
      "ControlPort": 9002,
      "AllowAPIAlways": true
    }
  }
}

### Include full error message in text form
(base) E:\AirSim\PythonClient\multirotor>python gimbal.py
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Taking off
Ready
Traceback (most recent call last):
  File "gimbal.py", line 20, in <module>
    camera_pose = airsim.Pose(airsim.Vector3r(0, 0, 0), airsim.to_quaternion(0.5, 0.5, 0.1))
  File "E:\AirSim\PythonClient\airsim\utils.py", line 91, in to_quaternion
    q = Quaternionr()
NameError: name 'Quaternionr' is not defined

**Comment by rajat2004** [comment]
Yeah, likely that it's a problem with msgpack. Maybe try creating a virtual environment and install the packages in that.

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
