### ISSUE TITLE
Location of run.bat script for CityEnviron

### ISSUE THREAD

**Issue by andreasceid** [microsoft/AirSim#3683]
### What's your question?
I read the tip on environment setup in case of inadequate GPU subsystem. The short [tutorial](https://microsoft.github.io/AirSim/use_precompiled/#dont-have-good-gpu) references a script called `run.bat` under the parent folder of each environment. However, I coudn't find it. In case this file lies at an older version, is it safe to use that version? For example, I found the [version](https://github.com/microsoft/AirSim/releases/tag/v1.1.6) that first announced the City Environment and there is a disclaimer ("Note: City environment is under heavy development with more updates coming soon.").

### Include context on what you are trying to achieve
I'm trying to make City Environment run with less FPS, lower resolution (ex. 640x480 like the tutorial), because my GPU doesn't support the default setting. Is there a setting for lower FPS regarding the City Environment?

### System information
AirSim version 1.4
Microsoft Windows 10 Education Version 10.0.19042 Build 19042
Unreal Engine 4.26.1

**Comment by rajat2004** [comment]
Yeah, older script should be fine as well. I think the script actually contains only a single line like `start CityEnviron -ResX=640 -ResY=480 -windowed` or probably without any arguments, for easy launch

**Comment by andreasceid** [comment]
Perfect! This works. Do you have any idea how to _lower FPS_ as well to further decrease the system requirements?

**Comment by rajat2004** [comment]
Haven't tested this, but maybe try the FPS option mentioned in the [UE4 Docs](https://docs.unrealengine.com/en-US/ProductionPipelines/CommandLineArguments/index.html) under Rendering, the description seems a bit strange though

**Comment by andreasceid** [comment]
I think it worked! Thanks!

**Comment by rajat2004** [comment]
Does it really work? Doesn't seem to do anything for me

**Comment by chengleqi** [comment]
It worked!
airsim 1.5.0
Win10

**Comment by andreasceid** [comment]
**Warning**: This hack (`cl.simRunConsoleCommand("t.MaxFPS 10")`) might not work alongside `airsim.ImageRequest()` and `cl.simGetImages()` well. After some 40k loops, `cl.simGetImages()`  it didn't return the expected image.

**Comment by rajat2004** [comment]
Hmm, that's strange. Are you seeing an empty image or something else entirely? Empty image is an occasional problem, and might not be directly connected to this workaround, though could be that it can exacerbate the issue

**Comment by andreasceid** [comment]
Well, I'm running a reinforcement learning algorithm so I cannot tell you based on the traceback error exactly what happened. It definately was an environment error, and it was a simulator's fault since the environment runs the same for every `env.step(action)` routine. This was triggered after 40k loops, and it's a discrete action space (6 discrete actions), so I'm pretty sure that after 40k loops, if the error was in my software it would be triggered sooner. It probably returned an empty image since after `observation = numpy.frombuffer(res[0].image_data_uint8, dtype=numpy.uint8)` and `observation.reshape(res[0].height, res[0].width, 3)`, `observation.shape[0]` returned 0. I'll point out again that this happened after 40k loops (16 hrs).
