### ISSUE TITLE
AirSim Drone is unstable

### ISSUE THREAD

**Issue by SpeedCooper** [Microsoft/AirSim#369]
Hi. I am a student who is using the AirSIm program in Korea. During the use of the AirSim program, the drones are moving at their own discretion. Also use the 'Droneshelle.exe' program to type commands and move them around.
![airsim](https://user-images.githubusercontent.com/30429974/28560216-b72c5644-7154-11e7-84ea-89879ac231da.JPG)

**Comment by fountainYuan** [comment]
you must use PX4 Firmware 1.5.5, Higher is not suit for AirSim

**Comment by SpeedCooper** [comment]
I used nuttx-px4fmu-v2-default.px4 of px4 V.1.4.4. Is not there a problem?

**Comment by SpeedCooper** [comment]
As a result of running px4 version 1.5.5, the drones are strangely working alone.
![default](https://user-images.githubusercontent.com/30429974/28600597-e2ff861c-71ed-11e7-97ae-37373799b827.JPG)

**Comment by fountainYuan** [comment]
According your picture , the GPS of your UAV is lost ,you simulation in SITL　or HITL ?   If is SITL, you can set GPS params with param set command  like "  param set LPE_LAT 47.641468 " "param set LPE_LON -122.140165"  the coord is Microsoft.
You maybe change number. Or you can pause the Unreal Engine for UAV get GPS coord then click Play to Sim.

 





At 2017-07-26 09:33:46, "SpeedCooper" <notifications@github.com> wrote:


As a result of running px4 version 1.5.5, the drones are strangely working alone.

**Comment by SpeedCooper** [comment]
I'm using HITL.

**Comment by SpeedCooper** [comment]
I'm using HITL.

**Comment by SpeedCooper** [comment]
And does it matter if the wings are not fixed on the shaft?
![airsim](https://user-images.githubusercontent.com/30429974/28608607-e9022cb2-721b-11e7-948d-a0cae8f8e6ab.JPG)

**Comment by fountainYuan** [comment]
I found newest AirSim maybe have bugs ,you can try
 git clone --branch VehicleCamera https://github.com/Microsoft/AirSim.git 
this banch can control in QGC.

**Comment by SpeedCooper** [comment]
@fountainYuan 
I tried it, but it's not working. I don't know why....

**Comment by fountainYuan** [comment]
you get any error message? I use PX4 Version 1.5.5 AirSim  banch Vehicle Camera , can use QGC  control flying.







At 2017-07-28 08:23:05, "SpeedCooper" <notifications@github.com> wrote:


@fountainYuan
I tried it, but it's not working. I don't know why....

**Comment by sytelus** [comment]
Hey folks, I can't reproduce this but I have two guesses:

1. Your "Player Start" is too high above ground. This might cause drone to fall off and its initialization/calibration get messed up. So please make sure "Player Start" is just above the ground.

2. Another reason might be removal of ground lock which we did few weeks back. I've just added it back so try out new code as well.

**Comment by SpeedCooper** [comment]
@sytelus 

What new code does it say? PX4? AirSim?

**Comment by sytelus** [comment]
AirSIm. Please follow the build instructions: https://github.com/Microsoft/AirSim/blob/master/docs/build.md

**Comment by SpeedCooper** [comment]
@sytelus 
I installed it as shown on the homepage, but it is the same.....

**Comment by machenxiang** [comment]
I have the same question in HITL. My version of airsim is 1.2.1. I have tried the PX4 firmware 1.4.4,1.5.5and 1.8.2 but the question still exists.
