### ISSUE TITLE
Takeoff, Fall, Unable to control Drone 

### ISSUE THREAD

**Issue by AndrewEj** [Microsoft/AirSim#370]
I try to use px4 on mac to control the drone on win7 remotely. But the following problems repeat. 

![image](https://user-images.githubusercontent.com/22722252/28562688-2cc942cc-70d8-11e7-9afd-ad19e38eebe4.png)

I tried to switch the version of PX4 and Airsim. But I don't know why Mac cannot make px4 1.5.5, and win7 cannot build earlier Airsim version.

**Comment by AndrewEj** [comment]
When I use WIN7 to build this version : 6458eaf44aff5a802d9953457e06b0734f16d6b9 airsim; I can see this error : 
![image](https://user-images.githubusercontent.com/22722252/28563045-7216cc54-70d9-11e7-9af6-fee73994e571.png)

**Comment by AndrewEj** [comment]
When I use Mac to build PX1.5.5, I can see this error : 
![image](https://user-images.githubusercontent.com/22722252/28563100-ac0fafc0-70d9-11e7-9667-0c1ead9ca327.png)

**Comment by AndrewEj** [comment]
It seems the windows7 can compile the latest version, but not the previous one. Every time when I hit the play button, it immediately crashes. However, when I changed the value of the LocalIP, which I deliberately mis-connect the port, I can see the drone. I guess there are issues with the vehicle controller.

**Comment by sytelus** [comment]
Could you please make sure your build config in Visual Studio is set to "DebugGameEditor" and "Win64". Some time its set to "Development" and it will crash.
