### ISSUE TITLE
"OverrideExisting" setting in "SegmentationSettings" has opposite effect

### ISSUE THREAD

**Issue by CarloCloet** [microsoft/AirSim#3710]
## Bug report 

- AirSim Version/#commit: 1.5.0
- UE/Unity version: UE 4.25
- autopilot version: N/A
- OS Version: Windows 10

### What's the issue you encountered?

The "OverrideExisting" setting in "SegmentationSettings" works backwards, i.e. true and false are reversed.

### Settings

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "SubWindows": [
    {"WindowID": 1, "CameraName": "front_left", "ImageType": 5, "VehicleName": "", "Visible": true}
  ],
  "SegmentationSettings": {
    "InitMethod": "",
    "MeshNamingMethod": "OwnerName",
    "OverrideExisting": false
  }
}
```

### How can the issue be reproduced?

1. Build Vanilla 1.5.0 release
2. Open blocks environment in UE 4.25
3. Use above settings.json
4. Hit play. No need to drive the vehicle.
5. Notice how the semantic segmentation color for all blocks in front of the vehicle is the same

![image](https://user-images.githubusercontent.com/74256168/118863437-2bfab300-b8df-11eb-8dbc-371848318962.png)

6. Stop the simulation
7. Pick one of the blocks in front of the vehicle and change its "CustomDepth Stencil Value" property to a different value

![image](https://user-images.githubusercontent.com/74256168/118865274-1090a780-b8e1-11eb-9729-780d8d1f185d.png)

8. Hit play
9. Notice how the color of the block did NOT change and how the stencil value gets reset to the initial value of 241, despite the fact that "OverrideExisting" was set to false 
10. Repeat the above, but set the "OverrideExisting" to true. Now the modified stencil value will NOT change when we run the simulation and the block will have a different color in the semantic segmentation subwindow.

![image](https://user-images.githubusercontent.com/74256168/118866459-4c783c80-b8e2-11eb-9220-e2405f5e7f84.png)

It seems the setting is interpreted incorrectly (boolean opposite).

### How to fix

The believe the problem is in AirBlueprintLib.h, line 217

![image](https://user-images.githubusercontent.com/74256168/118867066-f5bf3280-b8e2-11eb-9c14-85fc5d277841.png)

This should read
```
if(!ignore_existing || ...
```

I tried this fix and it works for me, except for the fact that if you start simulation with the setting set to false, semantic segmentation no longer works. You have to run it first with the setting set to true, and then you can switch between true and false and the behavior is correct. 
Did not check the exact reason yet. Would like to first confirm my interpretation of the expected behavior of "OverrideExisting" is correct.

**What's better than filing an issue? Filing a pull request :).**

**Comment by rajat2004** [comment]
The problem and the expected behaviour seems correct, but the fix proposed doesn't seem like it. I think the problem is here -

https://github.com/microsoft/AirSim/blob/8c17ce4e43069707f0dfae6867a1f7d1f4d3612d/Unreal/Plugins/AirSim/Source/SimMode/SimModeBase.cpp#L181

It sets `ignore_existing` to be opposite of `override_existing`, which doesn't seem right -

Override_Existing: True ---> Ignore_Existing: False   (Nope)

They should be the same IMO, overriding means ignoring the existing values
