### ISSUE TITLE
Do you want to help shape the future of autonomous simulations?

### ISSUE THREAD

**Issue by jonyMarino** [microsoft/AirSim#3711]
We are looking for your feedback to help guide us on what's critical to you for photorealistic physics-based drone and ground vehicles simulations. We want to learn about your interests and how you are using AirSim to help guide our product strategy.

[Survey link](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR4J_69QtqUREtdPd5aLYTsFURDJPQUFSNDI3T0VENzJHUjVQVkpVWlRFNC4u)

**Comment by VibhavTiwari** [comment]
Thank you, Jonathan!
