### ISSUE TITLE
The problem to control the drone flight

### ISSUE THREAD

**Issue by sifengyang** [Microsoft/AirSim#372]
Hi, guys. I have install PX4 and SITL. And I can control the drone flight by takeoff.py script. However, How to I control manually the drone flight without flight controller harware.

**Comment by sytelus** [comment]
If you don't want to use flight controller, take a look at [Computer Vision mode](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md). We are soon also going to enable simple_flight and ROSFlight that runs inside the AirSim.

**Comment by sifengyang** [comment]
@sytelus thanks. I can control the drone flight . But I think that the drone flight normally. Propellers of the drone are  inactive.  
![4](https://user-images.githubusercontent.com/22024525/28604490-8b781e9e-71fd-11e7-8ac5-637f7df1900b.png)
