### ISSUE TITLE
Noise and Offset of BarometerSimple.hpp and MagnetometerSimple.hpp

### ISSUE THREAD

**Issue by fmzhu** [Microsoft/AirSim#373]
Could anyone explain how are the Noise and Offset from Barometer and Magnetometer calculated.  Could you please give me a link or some references, because I want to make some experiment about adding Noise and Offset.  Thank you very much for your attention!

![bar](https://user-images.githubusercontent.com/9269633/28590155-691948d6-7181-11e7-93e6-ae948f033484.PNG)
![mag](https://user-images.githubusercontent.com/9269633/28590156-6920caf2-7181-11e7-863c-deef2bac927c.PNG)

**Comment by sytelus** [comment]
We recently updated this code with some comments so please check it out again. In short, we simulated atmospheric pressure drift using Gaussian Markov process so you may see few meters of drift per hour. Then we add noise as per data sheet of sensor. Please see our paper for more details: https://arxiv.org/abs/1705.05065
