### ISSUE TITLE
What's the meaning of 6 kinematic quantities in getCarState API?

### ISSUE THREAD

**Issue by weigangwen** [microsoft/AirSim#3734]
#### 

###

**Comment by clovett** [comment]
According to [AirSim/PythonClient/airsim/typee.py](https://github.com/microsoft/AirSim/blob/master/PythonClient/airsim/types.py) you have CarState with it's `kinematics_estimated`:

```python
class CarState(MsgpackMixin):
    speed = 0.0
    gear = 0
    rpm = 0.0
    maxrpm = 0.0
    handbrake = False
    collision = CollisionInfo()
    kinematics_estimated = KinematicsState()
    timestamp = np.uint64(0)
```
and this is defined asS:

```python
class KinematicsState(MsgpackMixin):
    position = Vector3r()
    orientation = Quaternionr()
    linear_velocity = Vector3r()
    angular_velocity = Vector3r()
    linear_acceleration = Vector3r()
    angular_acceleration = Vector3r()
```

Where:
- `position` is x,y,z location, in local coordinates (0,0,0) is the home position where vehicle started.  
- `orientation` is a Quaterion describing rotation of drone
- `linear_velocity` is the current speed of the drone in x, y, z
- `angular_velocity` is the speed of rotation in each axis
- `linear_acceleration` is the acceleration of the drone in x, y, z
- `angular_acceleration` is the acceleration of the rotation of the drone in each axis

**Comment by weigangwen** [comment]
@clovett thanks!
