### ISSUE TITLE
Custom pawn type fall through ground

### ISSUE THREAD

**Issue by lukaszdworako** [Microsoft/AirSim#375]
As said in the title, I have created a new custom pawn type however every time I launch it simply falls through the ground. Since a majority of the source has been copy/ pasted to the new pawn type it doesn't make sense to me. Can anyone advise? [Link to the repo](https://github.com/lukaszdworako/GroundSimBlocks.git)

**Comment by sytelus** [comment]
Please point to the code for your custom pawn. Is it derived from AVehiclePwnBase? I have seen above behavior happening if you have physics enabled. So you might want to check settings on your pwn mesh.

**Comment by lukaszdworako** [comment]
Found the problem, did not set the static mesh as the root. Thank you
