### ISSUE TITLE
addtion of human(s) and flood in an airsim environment

### ISSUE THREAD

**Issue by AIKUUM** [microsoft/AirSim#3766]
### What's your question?
I have 2 main questions:-
1) Is it possible to add human(s) in an AirSim environment? If yes, then how?
2) Is it possible to add flood in a small area of an AirSim environment? If yes, then how?

#### Context details
Unreal Engine version 4.26
System: Windows 10 , 64-bit

**Comment by p00uya** [comment]
yes, you can!  there are a lot of components that you can add to the unreal engine, that not related to airsim in other word the capabilities of the unreal engine! you should search:" add human model in unreal engine " or other content as you want
