### ISSUE TITLE
the question to collectting  the flight track

### ISSUE THREAD

**Issue by sifengyang** [Microsoft/AirSim#377]
Hi, guys. I could control the drone flight in the computer vision mode by my keyboard.  And I  could save the depth image after modified the Camera.py script in the PythonClient folder. my purpose is that I can collect the information of the drone flight track after I flight the drone manually. Then the drone is able to flight by the collecting information. thanks.

**Comment by sytelus** [comment]
You can use API `getPosition()` and `getOrientation()` to retrieve pose of drone.
