### ISSUE TITLE
DepthPerspective is binary, DepthPlanar is grayscale.

### ISSUE THREAD

**Issue by h-gokul** [microsoft/AirSim#3776]
### Using AirSimNH to collect scene, depth, segmentation in a mono camera setting. 
I tried using the hello_car.py, cv_mode.py examples, and those also had similar output. 

  

I am sorry if this question is repetitive, I am just few days old in learning AirSim. So can anyone provide the steps clearly on my mistake.

I am using Windows 10, Unreal 4.25.4 

This is my settings.json, PixelsAsFloat is set  to true here.
```
{
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "SpeedUnitFactor": 1,
  "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 0.05,
    "Cameras": [
      {
        "CameraName": "0",
        "ImageType": 0,
        "PixelsAsFloat": false,
        "Compress": true
      },
      {
        "CameraName": "0",
        "ImageType": 2,
        "PixelsAsFloat": true,
        "Compress": true
      },
      {
        "CameraName": "0",
        "ImageType": 5,
        "PixelsAsFloat": true,
        "Compress": true
      }
    ]
  },

  "CameraDefaults": {
    "CaptureSettings": [
      {
        "ImageType": 0,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90,
        "TargetGamma": 2.0
      },
      {
        "ImageType": 2,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90
      },
      {
        "ImageType": 5,
        "Width": 640,
        "Height": 480,
        "FOV_Degrees": 90
      }
    ]
  }
}
```

When I use "DepthPlanar"  by choosing the ImageType: 1, the output looks like grayscale. (Uses blocks environment)

![DepthPlanar](https://user-images.githubusercontent.com/43991028/121360812-5d9cf200-c952-11eb-8caa-67bd16cb1156.PNG)

When I use "DepthPerspective"  by choosing the ImageType: 2, the output looks binary. I checked issues #921 but I am not using python scripts to obtain data, but directly playing the GUI and record 
![depthPerspective](https://user-images.githubusercontent.com/43991028/121360829-6261a600-c952-11eb-89a5-3c3d67b107d6.PNG)

I suspect I am making a mistake in the settings.json file that  is causing this issue, can I get some help for this ?

**Comment by h-gokul** [comment]
UPDATE: 
**For the Depth Perspective Image,** after loading pfm files, I got it sorted after **clipping** the image to get proper visualization as suggested in issue #921. Clipping is required since sky is infinitely far away and the floating point values are of order 10^5. 

DepthPerspective Image after clipping 0,100
![depthPerspective_new](https://user-images.githubusercontent.com/43991028/121541996-5f83b580-ca25-11eb-8f0a-d37f5c330dd1.PNG)

DepthPlanner's gray scale issue stays unresolved.

**Comment by skykim0609** [comment]
From my experience, I think DepthPerspective image looks binary due to infinite depth along free space and the overall depth image is normalized. Actual depth value is okay.
 Depthplanar topic being grayscale image should be fixed quickly. This bug appears since ver > 1.4.0
