### ISSUE TITLE
Unreal Engine Error

### ISSUE THREAD

**Issue by SpeedCooper** [Microsoft/AirSim#378]
I am not sure about this problem. If you press the 'Generate Visual Stduio Project Files' button, an error message like the picture will pop up.
![default](https://user-images.githubusercontent.com/30429974/28658110-c45203aa-72e4-11e7-8d64-e3230db7cfdc.JPG)

**Comment by sytelus** [comment]
We just upgraded AirSim for Unreal 4.16. Please install Unreal 4.16 and [see this doc](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_upgrade.md) on how to upgrade your own Unreal projects.

**Comment by SpeedCooper** [comment]
@sytelus 
oh! Solved it! Thank you!
