### ISSUE TITLE
AirSim\Content\HUDAssets UE4 OptionsMenu.uasset is not loading 

### ISSUE THREAD

**Issue by helloworldunicon** [microsoft/AirSim#3780]
UE4.24 OptionsMenu.uasset is not loading .

**Comment by helloworldunicon** [comment]
airsim 1.31 and 1.50 is not

**Comment by rajat2004** [comment]
Try 4.25

**Comment by helloworldunicon** [comment]
thank you, I will try it&nbsp;



发自我的iPhone


------------------ Original ------------------
From: Rajat Singhal ***@***.***&gt;
Date: Sun,Jun 13,2021 2:32 AM
To: microsoft/AirSim ***@***.***&gt;
Cc: helloworldunicon ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [microsoft/AirSim] AirSim\Content\HUDAssets UE4 OptionsMenu.uasset is not loading  (#3780)





 
Try 4.25
