### ISSUE TITLE
unreachable code

### ISSUE THREAD

**Issue by maddin200** [Microsoft/AirSim#38]
MavLinkCom\MavLinkTest\Commands.cpp line 40

if (subscription == 0) {
		if (subscription != 0) {
			this->vehicle->getConnection()->unsubscribe(subscription);
		}

**Comment by lovettchris** [comment]
what the heck? must have been debugging something, and forgot to remove it.  Good catch thanks. I also fixed some other bugs in the MavLinkTest app so it works again with jMavSim and with AirSim.

[Fixed](https://github.com/Microsoft/AirSim/commit/9dd8d34c0545d02738de3519773b9ea1d728ad1e).
