### ISSUE TITLE
Weather Simulation in LandscapeMap

### ISSUE THREAD

**Issue by fu1199** [microsoft/AirSim#3809]
### How to enable Weather Simulation in Landscape Map?

Hello I am new to Airsim and followed the first steps on https://microsoft.github.io/AirSim/build_windows. I tried the landscape Map but I am not able to set weather conditions in this map nor in the Blocks environment.
 
I am Using Win10 and have built Airsim by source. Everything works exept from the weather simulation.

What am I doing wrong?

Thanks a lot in advance!

![image](https://user-images.githubusercontent.com/82511343/122918530-83b58f80-d35f-11eb-97cc-91c599cba86d.png)

**Comment by thomasTUK** [comment]
Got the same problem....
