### ISSUE TITLE
MacOS check failing

### ISSUE THREAD

**Issue by jonyMarino** [microsoft/AirSim#3813]
It seems that something changed in GitHub actions and what was only throwing warnings previously now throws errors. 
You can see the error here:
https://github.com/microsoft/AirSim/runs/2876995070

We have tried different solutions in this PR:
https://github.com/microsoft/AirSim/pull/3812
but with no luck. 

Does anyone have an idea on how to fix this?

**Comment by rajat2004** [comment]
I've opened #3815 which seems to fix the problem, but additional testing on a macOS system would be for the best. Separate PR since the fix is different from #3812, one can test and compare both separately

**Comment by jonyMarino** [comment]
always outstanding Rajat! I guess @saihv can test it?
Thanks!

**Comment by saihv** [comment]
Thanks for the fix @rajat2004! Setup and build work fine on my Mac.
