### ISSUE TITLE
AirSim Questions

### ISSUE THREAD

**Issue by SpeedCooper** [Microsoft/AirSim#382]
(PX4 over Pxihawk) is a Hardware In the Loop Simulation (HILS) environment.
Do not you need to configure the PX4 on Pixhawk before the simulation?
- What kind of model is the Drone to be running by the PX4 (the quadratic rotor or fixed wing)
- If it is a quadratic rotor, what is the Drone characteristic of the quadratic rotor?
(Even if it is a quadratic rotor type, the characteristics of each model are different, so if you want to simulate a specific model of Drone, you should set the characteristic of the Drone or take it as an environment file.)
- If you load the PX4 / Pixhawk on the actual aircraft, you must also reflect these characteristics in the calibration or tuning of the PX4 parameters before the first flight

**Comment by sytelus** [comment]
See here for setup [steps for PX4](https://github.com/Microsoft/AirSim/blob/master/docs/prereq.md), [SITL](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md), [more on PX4](https://github.com/Microsoft/AirSim/blob/master/docs/px4.md).

Yes, its quadrotor in QuadX config. Look for vehicles folder in code to find drone params.
