### ISSUE TITLE
Problem with AirSim on Ubuntu whith UnrealEngine 4.26

### ISSUE THREAD

**Issue by ale99viv** [microsoft/AirSim#3825]
## Question
I, i'm trying to use AirSim(1.5.0) on Ubuntu with Unreal 4.26 but when I try to launch ther project with terminal by the command "./Engine/Binaries/Linux/UE4Editor pathproject/project.uproject" i have this problem. Anyone can halp me? Whith the same method I'm able to use AirSim but wihth Unreal 4.25

### Include details of what you already did to find answers
![error](https://user-images.githubusercontent.com/70646926/123405191-dd10ff00-d5a9-11eb-842e-8bae38fb3c2d.JPG)

**Comment by ale99viv** [comment]
what's the name of this .sh? Sorry for my level but on Ubuntu is my first time, before I have used airsim only on Windows.

**Comment by jonyMarino** [comment]
It has the name of the environment inside. For Example, for Africa it is Africa_001.sh.
Here you have [the link to the binaries](https://github.com/microsoft/AirSim/releases/tag/v1.5.0-linux)

**Comment by ale99viv** [comment]
Thanks for your fast reply @jonyMarino. Yeah I know this but I'm trying to use my own project

**Comment by jonyMarino** [comment]
Can you run your project without the AirSim plugin?

**Comment by wangzhihui22** [comment]
I also encountered this problem，I cam run my project with the Airsim plugin.

**Comment by wangzhihui22** [comment]
> Can you run your project without the AirSim plugin?

I also encountered this problem，I can run my project with the Airsim plugin.

**Comment by ale99viv** [comment]
I've solved the problem by using a IDE for building the project. I'm current using Ubntu and so I have do this through QtCreators

**Comment by wangzhihui22** [comment]
> Can you run your project without the AirSim plugin?

I also encountered this problem，I can run my project without the Airsim plugin.

**Comment by ale99viv** [comment]
@wangzhihui22  What's the error?

**Comment by jonyMarino** [comment]
Hi, @wangzhihui22 What's the error you are getting?
