### ISSUE TITLE
Is it possible to run multiple drones simultaneously?

### ISSUE THREAD

**Issue by galgyeony** [Microsoft/AirSim#383]
Hello,

In AirSim, is it possible to run multiple drones simultaneously?
For instance, the following scenario is currently acceptable with AirSim?
1) 3 persons in the Internet can access a AirSim server and control and monitor his/her own drone on the same map.
2) They can see each other with his/her own 3D view acquired from the rendering engine run on his/her local computer.

If something is wrong, please correct me.

Thanks in advance.

**Comment by sytelus** [comment]
It can't be done but you would need to write code for it. AirSim supports multiple drones. You can enable Unreal VR related features and game server for multiplayer VR games.
