### ISSUE TITLE
read sensor data in HITL mode and print in Airsim

### ISSUE THREAD

**Issue by p00uya** [microsoft/AirSim#3836]
## Read Sensor in real drone and pring on airsim ?

I can run get  messages from mavlinktest in HITL mode, now i decide to read and print pix4 sensors value in airsim
is it possible to do with Mavlink APIs? i can't found any resourses :( ...

**Comment by jonyMarino** [comment]
Hi @p00uya! I don't understand your question very well.
Do you want to print the sensor values that AirSim sends to PX4? through MavLinkTest?
You can print the values inside AirSim in this place: MavLinkMultirotorApi::sendHILSensor()

**Comment by lovettchris** [comment]
See also [px4 logging](https://github.com/Microsoft/AirSim/blob/master/docs/px4_logging.md).

**Comment by jonyMarino** [comment]
Closed due to inactivity. Please, feel free to ask for it to be reopened if you wish to continue posting.
