### ISSUE TITLE
[BUG] Commit 6ba07d089632f32017460190211b55d59964b3a3 breaks the build - Missing return value in simple_flight::ControlMode::getAllRateMode()

### ISSUE THREAD

**Issue by EliteTUM** [Microsoft/AirSim#388]
The commit 6ba07d089632f32017460190211b55d59964b3a3 seems to break the build since the new method simple_flight::ControlMode::getAllRateMode() does not return a value. I guess commit was not sufficiently reviewed.

**Comment by sytelus** [comment]
Thanks for pointing this out. Its fixed now.
