### ISSUE TITLE
simGetVehiclePose() return wrong NED pose

### ISSUE THREAD

**Issue by alonfaraj** [microsoft/AirSim#3882]
## Bug report 

- AirSim Version/#commit: ccfaa5d402f77e68e26e0591118663dadedd0427
- UE/Unity version: 4.26
- autopilot version: 
- OS Version: Win10

### What's the issue you encountered?

This issue first mentioned here https://github.com/microsoft/AirSim/discussions/3844.
Seems like it's not the intended behavior but better to get a confirmation for this. 
The NED position returned by `simGetVehiclePose()` is relative the the spawn location and not to the origin (PlayerStart pawn).
In the example it should return (8,5,2) but instead it returns (0,0,2).

### Settings

<details>
  <summary>Seetings.json</summary>
  
  ```json
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "Vehicles" : 
  {
    "Car1": 
    {
      "VehicleType": "PhysXCar",
      "X": 8, "Y": 5, "Z": -2
    }
  }
}
  ```
</details>

### How can the issue be reproduced?

1. Run Blocks with above `settings.json`
2. Run the following API code
<details>
  <summary>code</summary>
  
  ```python
import setup_path
import airsim

client = airsim.VehicleClient()
client.confirmConnection()

print(client.simGetVehiclePose("Car1").position)
  ```
</details>

<details>
  <summary>output</summary>
  
  ```python
<Vector3r> {   'x_val': 0.0,
    'y_val': 2.136230477844947e-06,
    'z_val': 2.234570026397705}
  ```
</details>

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

**Comment by zimmy87** [comment]
See my comment [here](https://github.com/microsoft/AirSim/issues/4261#issuecomment-1009877677). I think this is by design, but I will confirm with my team. You can work around this by using the `simGetObjectPose()` API.
