### ISSUE TITLE
How to add my own python api

### ISSUE THREAD

**Issue by hhhhhhhhmh** [microsoft/AirSim#3918]
### What's your question?
Dear all,
I have been added my own blueprint into bp_flyingpawn
And I want to create some new python api. so that i can control all the function through python.
so can anybody tell me how to deal with this problem.

**Comment by rajat2004** [comment]
Please add details about what you've tried and exactly what you need help with. https://microsoft.github.io/AirSim/adding_new_apis/ might be helpful
