### ISSUE TITLE
rcp_error with imagecapture request in cpp

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [microsoft/AirSim#3928]
## Bug report 

- AirSim Version/#commit: 6e2512e25d794c9a17c2f45fa94cb441fbc9262b
- UE/Unity version: Unreal 4.25
- autopilot version: Computer vision mode
- OS Version: Ubuntu 18.04

### What's the issue you encountered?

While it is possible to use the `msr::airlib::MultirotorRpcLibClient` for setting poses with `.simSetVehiclePose()`, when requesting images, it fails with a `rpc_error`
```
Waiting for connection - X
Connected!

Client Ver:1 (Min Req:1), Server Ver:1 (Min Req:1)
terminate called after throwing an instance of 'rpc::rpc_error'
  what():  rpc::rpc_error during call
```

The code snippet I am using for requesting images are as the following
```
    vector<ImageRequest> request = { ImageRequest("0", ImageType::Scene) };
    const vector<ImageResponse>& response = client_.simGetImages(request);  
```
where the types are defined separately
```
typedef msr::airlib::ImageCaptureBase::ImageRequest ImageRequest;
typedef msr::airlib::ImageCaptureBase::ImageResponse ImageResponse;
typedef msr::airlib::ImageCaptureBase::ImageType ImageType;
```
This is running as part as a ROS node

What I don't understand is that since I am able to control the pose, the link between ros node and airsim is valid. However, I am not able to retrieve images from the server

### Settings

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "PhysicsEngineName":"ExternalPhysicsEngine",
  "SimMode": "ComputerVision"
}

```

### How can the issue be reproduced?

1. Try using the image API in cpp?

### Include full error message in text form
```
Waiting for connection - X
Connected!

Client Ver:1 (Min Req:1), Server Ver:1 (Min Req:1)
terminate called after throwing an instance of 'rpc::rpc_error'
  what():  rpc::rpc_error during call
```

**What's better than filing an issue? Filing a pull request :).**

**Comment by Jaeyoung-Lim** [comment]
Also tried using the `HelloDrone` example and fails as the following

```
~/dev/AirSim/HelloDrone/build$ ./HelloDrone 
Waiting for connection - X
Connected!

Client Ver:1 (Min Req:1), Server Ver:1 (Min Req:1)
Press Enter to get FPV image

Exception raised by the API, something went wrong.
rpclib: function 'simGetImages' (called with 3 arg(s)) threw an exception. The exception is not derived from std::exception. No further information available.
```

**Comment by jonyMarino** [comment]
Hi Jaeyoung! You are using the ComputerVision mode but I think what you want is the Multirotor one. Your code should work changing that.

**Comment by Jaeyoung-Lim** [comment]
@jonyMarino Thanks for the reply!

How can I capture images when I am in computer vision mode?

 I am trying to use airlib so that it can orient the camera as it is attached on a gimbal, and capture the images through mavlink. Would there be a better way to achieve this without using computer vision mode?

**Comment by zimmy87** [comment]
Hi @Jaeyoung-Lim, for capturing images in computer vision mode, I think you'll want to use AirSim's RpcLibClientBase instead of MultirotorRpcLibClient. Your call to simGetImages() should be fine, I think you're just using the wrong client.

**Comment by jonyMarino** [comment]
But if you want to use the ROS wrapper, maybe it is better to use the ExternalPhysicsEngine in Multirotor mode. If you have problems with that, let us know.

**Comment by Jaeyoung-Lim** [comment]
@zimmy87 Thanks for the inputs, 

I tried using `RpcLibClientBase` as the client, but the `simGetImages()` and `simGetImage()` are both failing with the same errors

```
Waiting for connection - X
Connected!

Client Ver:1 (Min Req:1), Server Ver:1 (Min Req:1)
terminate called after throwing an instance of 'rpc::rpc_error'
  what():  rpc::rpc_error during call
```

Not sure what I am missing here. What I am basically trying to do using airlib. 
 - Set an arbitrary pose of the camera
 - Get the image out of the camera

**Comment by jonyMarino** [comment]
Jaeyoung. Neither Zimmy nor I were able to reproduce your issue. Are you using the same AirSim version for the airsim client (HelloDrone) and server (your UE AirSim project)?

**Comment by Jaeyoung-Lim** [comment]
@jonyMarino Oh, I forgot to mention this. I built my airlib with gcc-8 and using a landscape mountains binary 1.5.0-linux release.

Do you think this might be causing the issue? Since I am building my package with gcc and linking airlib I thought this was what I should do

**Comment by Jaeyoung-Lim** [comment]
By repackaging the latest Airsim on linux solved the problem. (See the image captured below)

![1628178294650435000](https://user-images.githubusercontent.com/5248102/128380297-f799f615-2155-44e8-8477-0c5cdbcd2e37.png)

This means that the `1.5.0-linux` release is not compatible anymore with the latest Airsim.

Since I am interested in using the gcc compiled Airlib I tried to build `1.5.0` on gcc-8 but the build script caused a lot of problems.

@jonyMarino @zimmy87 Since my problems were caused by a regression on the airlib API, it would be very helpful if there can be a new linux release, so other people do not need to repackage their Airsim with UE4. Would this be something possible?

Thanks!

**Comment by jonyMarino** [comment]
@Jaeyoung-Lim That is in our plans. @saihv is  solving one more issue and then we will start the new release.

**Comment by Jaeyoung-Lim** [comment]
@jonyMarino @saihv Any chance of a ETA? would be quite helpful to plan my work :smile:

**Comment by rajat2004** [comment]
@Jaeyoung-Lim Re the RPC error with 1.5.0 binary and latest master for compiling the client code, that's mostly due to https://github.com/microsoft/AirSim/pull/3320, I should have thought about and mentioned in the PR at least that it would break binary compatibility with the releases, sorry for that, and something to note at least in the future

**Comment by jonyMarino** [comment]
> @jonyMarino @saihv Any chance of a ETA? would be quite helpful to plan my work 😄

This month!
