### ISSUE TITLE
Drones of other models

### ISSUE THREAD

**Issue by SpeedCooper** [Microsoft/AirSim#394]
I would like to use AirSim to apply the drones of other models than the basic drones, but is it possible?

**Comment by sytelus** [comment]
Yes, as long as you can implement DroneControllerBase for your target drone, it should be possible.

**Comment by SpeedCooper** [comment]
@sytelus 

How does it apply?

**Comment by sytelus** [comment]
Could you please elaborate? What do you mean by "apply"? More details, the better.
