### ISSUE TITLE
Value of Vehicle Cross-Section

### ISSUE THREAD

**Issue by AbdullahK047** [microsoft/AirSim#3942]
### Discussed in https://github.com/microsoft/AirSim/discussions/3941

<div type='discussions-op-text'>

<sup>Originally posted by **AbdullahK047** August  8, 2021</sup>
Hi,

According to the [AirSim paper](https://microsoft.github.io/AirSim/paper/main.pdf), the drag force is calculated as:

<img src="https://render.githubusercontent.com/render/math?math=|\mathbf{F_d}| = \frac{1}{2}\rho|\mathbf{v}|^2 C_{lin}A">

I have been able to track down values of all the constants from the code except _A_:

- <img src="https://render.githubusercontent.com/render/math?math=\rho = 1.225"> 
- <img src="https://render.githubusercontent.com/render/math?math=C_{lin} = 0.325"> 

So, what is the value of the constant _A_ being used here?

Thanks in advance!</div>

**Comment by jonyMarino** [comment]
tracked in discussions
