### ISSUE TITLE
Segmentation image color vs StencilID

### ISSUE THREAD

**Issue by gawela** [Microsoft/AirSim#395]
Hello all,

I am using the ComputeVision mode to generate Segmentataion images with AirSim. I was experimenting with setting custom StencilIDs (0 - 255) in the Unreal Editor, but now I am wondering about the association between the StencilIDs and the colors AirSim spits out in the end. Is there a color map between these?

I tried using the [`seg_color_pallet.uasset`](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Content/HUDAssets/seg_color_pallet.uasset) by converting it to a png file and using this with openCv. However, the colors I receive when saving the segmentation images don't comply with the colors in the pallet. Is there a known solution to this?

**Comment by sytelus** [comment]
You might want to try out this png which was used to generate the uasset:
https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Content/HUDAssets/seg_color_pallet.png

I'll also try to get the code that was used to generate this in repo soon.
