### ISSUE TITLE
GazeboDrone and External API/Sensors

### ISSUE THREAD

**Issue by nikitabeebe** [microsoft/AirSim#3957]
### Discussed in https://github.com/microsoft/AirSim/discussions/3954

<div type='discussions-op-text'>

<sup>Originally posted by **nikitabeebe** August 11, 2021</sup>
I know the GazeboDrone project prevents other kinematic functions, like setting position, ect. But does it disable the use of IMU, GPS, and Image sensors as well?

I have a script I'm trying to run to log the IMU, GPS, and Image data to a .log file (running separately in a python script while running GazeboDrone with the build command). Should all the sensors still run as expected despite using a external physics engine?</div>

To add to this, since the GazeboDrone declares that "GazeboDrone allows connecting a gazebo drone to the AirSim drone, using the gazebo drone as a flight dynamic model (FDM) and AirSim to generate environmental sensor data." I'm more confident I'm simply not calling the commands correct.

For instance, inside main.cpp I have added 
`        if (i == 0) {
            msr::airlib::Vector3r p(x, -y, -z);
            msr::airlib::Quaternionr o(ow, ox, -oy, -oz);

            client.simSetVehiclePose(Pose(p, o), true);
            auto gps = client.getGpsData();
            std::cout << "GPS Velocity " << gps.gnss.velocity << std::end;
        }`

But throughout a flight (using QGC and Gazebo) the velocity values never change from {0,0,0}.

With this as my settings.json
`
{
	"SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
	"SettingsVersion": 1.2,
	"SimMode": "Multirotor",
	"PhysicsEngineName": "ExternalPhysicsEngine",
	"CameraDefaults": {
	  "CaptureSettings": [
		{
		  "ImageType": 0,
		  "Width": 512,
		  "Height": 384,
		  "FOV_Degrees": 70,
		  "AutoExposureSpeed": 100,
		  "AutoExposureBias": 0,
		  "AutoExposureMaxBrightness": 0.64,
		  "AutoExposureMinBrightness": 0.03,
		  "MotionBlurAmount": 0,
		  "TargetGamma": 1.0,
		  "ProjectionMode": "",
		  "OrthoWidth": 5.12
		}
	  ]
	},
	"OriginGeopoint": {
	  "Latitude": 33.32687,
	  "Longitude": -114.37043,
	  "Altitude": 345.520128
	},
	"DefaultSensors": {
	  "Barometer": {
		"SensorType": 1,
		"Enabled": true,
		"PressureFactorSigma": 0.001825,
		"PressureFactorTau": 3600,
		"UncorrelatedNoiseSigma": 2.7,
		"UpdateLatency": 0,
		"UpdateFrequency": 100,
		"StartupDelay": 0
	  },
	  "Imu": {
		"SensorType": 2,
		"Enabled": true,
		"AngularRandomWalk": 0.3,
		"GyroBiasStabilityTau": 500,
		"GyroBiasStability": 4.6,
		"VelocityRandomWalk": 0.24,
		"AccelBiasStabilityTau": 800,
		"AccelBiasStability": 36
	  },
	  "Gps": {
		"SensorType": 3,
		"Enabled": true,
		"EphTimeConstant": 0.9,
		"EpvTimeConstant": 0.9,
		"EphInitial": 0,
		"EpvInitial": 0,
		"EphFinal": 0,
		"EpvFinal": 0,
		"EphMin3d": 3,
		"EphMin2d": 4,
		"UpdateLatency": 0,
		"UpdateFrequency": 100,
		"StartupDelay": 0
	  },
	  "Magnetometer": {
		"SensorType": 4,
		"Enabled": true,
		"NoiseSigma": 0.005,
		"ScaleFactor": 1,
		"NoiseBias": 0,
		"UpdateLatency": 0,
		"UpdateFrequency": 100,
		"StartupDelay": 0
	  }
	},
	"SubWindows": [
	  {
		"WindowID": 0,
		"CameraName": "0",
		"ImageType": 0,
		"VehicleName": "",
		"Visible": true,
		"External": false
	  },
	  {
		"WindowID": 1,
		"CameraName": "3",
		"ImageType": 0,
		"VehicleName": "",
		"Visible": true,
		"External": false
	  }
	]
  }
`

**Comment by jonyMarino** [comment]
Already answered in discussions. Let's continue there.
