### ISSUE TITLE
Unable to connect to SITL

### ISSUE THREAD

**Issue by DanWilson00** [Microsoft/AirSim#40]
I have successfully built and run PX4 SITL in Windows 10 Bash and get:
`INFO  [simulator] Waiting for initial data on UDP port 14560. Please start the flight simulator to proceed..`
TCPView confirms that PX4 is connected to localhost and port 14560

I have then done the following:
- Downloaded/installed UE4
- Downloaded/built the dependencies
- Downloaded/built Airsim in VS2015
- Created a new project, added an environment, copied the Airsim plugin files to the project, enabled the plugin
- Modified settings.json to not use serial
- Ran the UE4 project in VS2015 and changed to SimGameMode
- Pressed play

The simulator doesn't connect to the SITL and UE4 hangs until I stop running the project from VS2015 (see below)

![ue4 hang](https://cloud.githubusercontent.com/assets/4743950/23184891/4e508aa6-f836-11e6-89ea-2a3be80e9e32.png)

Am I missing something?

**Comment by sirluzelot** [comment]
Modify LocalHostIp to something different than 127.0.0.1, for example 127.0.0.2, that worked for me. Matching IPs makes it use connectLocalUdp which actually starts a server instead of listening, therefore the bind error if the PX4 firmware is already running

**Comment by DanWilson00** [comment]
That worked, thanks sirluzelot!
