### ISSUE TITLE
[HILS-HelloDrone] The Drone goes into failsafe mode after it takes off

### ISSUE THREAD

**Issue by sooyoungmoon** [Microsoft/AirSim#400]
Hello, I am testing the HelloDrone project in AirSim solution using HILS and have a problem in making the drone move. The current goal is to make my own project (similar to HelloDrone) to move drone by using moveToPosition command and save log (position, orientation and some other values)

Here is the screenshot.

![airsim error - failsafe after taking off](https://user-images.githubusercontent.com/9283741/28961676-1ea9fbe6-793e-11e7-9477-e98f902106ac.png)

Summary for my system settings.

1) PX4 version: 1.6.5
2) Airframe type (configured in QGC): HIL Quadcopter X
3) No radio setup since I don't use RC to control the drone.

When I connect the Pixhawk to the PC, the main LED is blinking red (fast) and doesn't change during the execution of AirSim. When I start the AirSim and HelloDrone, they work well until the taking-off.

However, the drone goes into failsafe mode right after it takes off and I cannot control the movement of the drone. (It immediately lands).

Could you give me any comment or tip to solve the problem?

Maybe I have to change some parameters related to the failsafe mode, but I have no idea about it.

Thank you in advance for your help.

**Comment by saihv** [comment]
Can you try setting the parameters NAV_RCL_ACT and NAV_DLL_ACT to 0 (disabled) in QGroundControl? If the problem persists even after setting these to 0, then it's the same as the issue I'm having.

**Comment by sooyoungmoon** [comment]
Thank you so much @saihv, I have set the parameters NAV_RCL_ACT (RC loss failsafe mode) and NAV_DLL_ACT (data link loss failsafe mode) to 'disabled' and could move the drone by using moveByVelocityZ() function. Still, the drone frequently goes into failsafe mode (ex. failsafe: no local position) and some runtime exceptions occur when moveByVelocityZ() is called (a timeout exception while RPC function is being executed) 
![airsim arming](https://user-images.githubusercontent.com/9283741/29170082-f3e0d92e-7e11-11e7-8f35-8c37982d5cc2.JPG)
![airsim exception](https://user-images.githubusercontent.com/9283741/29170080-f3df3614-7e11-11e7-979a-25714db241fa.JPG)
![airsim movebyposition](https://user-images.githubusercontent.com/9283741/29170081-f3e0431a-7e11-11e7-8321-7d9b85efb599.JPG)

I hope your issue to be solved soon. Thank you!

**Comment by vxgu86** [comment]
> 
> 
> Thank you so much @saihv, I have set the parameters NAV_RCL_ACT (RC loss failsafe mode) and NAV_DLL_ACT (data link loss failsafe mode) to 'disabled' and could move the drone by using moveByVelocityZ() function. Still, the drone frequently goes into failsafe mode (ex. failsafe: no local position) and some runtime exceptions occur when moveByVelocityZ() is called (a timeout exception while RPC function is being executed)
> ![airsim arming](https://user-images.githubusercontent.com/9283741/29170082-f3e0d92e-7e11-11e7-8f35-8c37982d5cc2.JPG)
> ![airsim exception](https://user-images.githubusercontent.com/9283741/29170080-f3df3614-7e11-11e7-979a-25714db241fa.JPG)
> 
> I hope your issue to be solved soon. Thank you!

did you solve your problem?
I am having the same problem even after two years!!
