### ISSUE TITLE
Weather widget not working when pressing F10

### ISSUE THREAD

**Issue by Tomakko** [microsoft/AirSim#4029]
## Bug report 

- AirSim commit: 213bbd6
- UE/Unity version: 4.25
- autopilot version: N/A
- OS Version: Ubuntu 20.04

### What's the issue you encountered?

I tried with the multiple Environments from v1.6 to open up the weather menu by pressing F10. Menu does not pop up. 

### Settings

default settings

### How can the issue be reproduced?

1. Start Africa Environment `sh ./Africa_001.sh -windowed`
2. Press F10

### Include full error message in text form

Error messages are:
`
Error: Couldn't find file for package /AirSim/HUDAssets/OptionsMenu requested by async loading code. NameToLoad: /AirSim/HUDAssets/OptionsMenu
`
`
Error: Found 0 dependent packages...
`
`
Warning: Warning, WeatherAPI could not load weather widget!
`

**Comment by zimmy87** [comment]
This is due to assets being passed over during packaging because there is no existing references to them in the maps included in builds. #4063 should fix this in the Blocks environment, and the next release should include these missing assets.
