### ISSUE TITLE
How to get the float16 depth with Python API

### ISSUE THREAD

**Issue by changwenkai101** [Microsoft/AirSim#403]
hi,  AirSim is a great project, according to my understanding : the depth image processing pipeline is :

a)  "Unreal generates the ground truth perspective depth image" (range: 0---2^24-1), 
b) AirSim limits depth into 0---100m and normalizes into float16 (range: 0---1) for output depth image
c) the function "simGetImage" convert the 0---1 to  uint8 (range : 0--255)

so, the 0---100m in virtual environment is converted to 0--255 (the uint8 image)?
I noticed the function " simGetImages" in C++ can grab the float16 depth value, I wonder is there a corresponding python API？

any suggestions are welcome, thx

**Comment by sytelus** [comment]
We have cleaned up lots of related things in latest version.

[The meaning of depth image pixels](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#what-does-pixel-values-mean-in-different-image-types)

[New Python example](https://github.com/Microsoft/AirSim/blob/master/docs/python.md#getting-started) shows how to get float images using Python.
