### ISSUE TITLE
What is the camera name of the one that displays its view in the default Unreal viewport?

### ISSUE THREAD

**Issue by Octavian-Zhang** [microsoft/AirSim#4073]
### What's your question?
I'm using the simGetCameraInfo & simSetCameraPose image API described in [Image APIs](https://microsoft.github.io/AirSim/image_apis/) doc page. While both functions require camera_name as their argument, I don't know what is the camera name associated with the one that displays its view in the default Unreal viewport. Does anybody know this?
![image](https://user-images.githubusercontent.com/21289147/136767954-7d13edab-0db5-4edd-91f7-fd6e7052ca9c.png)

### Include context on what you are trying to achieve
I want to change this big Unreal default viewport view using the described image API simSetCameraPose on [Image APIs](https://microsoft.github.io/AirSim/image_apis/), e.x., change it to look at a different vehicle that's been spawned during runtime by the simAddVehicle API listed on [this](https://microsoft.github.io/AirSim/adding_new_apis/) doc page. This newly spawned vehicle doesn't exist yet at Unreal start.

### Include details of what you already did to find answers
I'm already aware of the "Available Cameras" section on the [Image APIs](https://microsoft.github.io/AirSim/image_apis/) doc page. But there are only vehicle-attached cameras listed. The "FlyWithMe" "ViewMode" camera (see ViewMode section on [AirSim Settings](https://microsoft.github.io/AirSim/settings/)) is, however, not mentioned.

Screenshot of  the "Available Cameras" section on the [Image APIs](https://microsoft.github.io/AirSim/image_apis/) doc page:
![image](https://user-images.githubusercontent.com/21289147/136769698-7d34c46f-691f-46ab-a5cc-e0bb3bad6f63.png)

**Comment by jonyMarino** [comment]
No, it doesn't mean that, but currently, it is that way. You can't change the "FlyWithMe" camera target at runtime.

**Comment by sandilyasg** [comment]
@Octavian-Zhang @jonyMarino just to confirm, to change the pose of the camera attached to the drone at runtime, are you using the simSetCameraPose API with computer vision mode, or multirotor mode in settings.json?

**Comment by taeseongkr** [comment]
Hello. I need to retrieve raw data frame from FlyWithMe camera but I have no idea how to that because changing camera setting in setting.json doesnt help at all. Is there anyway to get access to FlyWithMe camera and get raw image from it? 
I appreciate all your help!

**Comment by ssaigarimella** [comment]
@taeseongkr As far as I understand it,[ FlyWithMe](https://microsoft.github.io/AirSim/settings/#:~:text=FlyWithMe%3A%20Chase%20the%20vehicle%20from%20behind%20with%206%20degrees%20of%20freedom) is an external camera that is actually a ViewMode and not a camera itself attached to the AirSim drone in either Unreal or Unity. Due to this, changing settings.json will not give you any camera result from the FlyWithMe perspective because there is no camera.

Instead, what you could try is to add a new camera in your Unreal Engine editor and settings.json: Configure a camera at a fixed offset behind the vehicle to mimic the FlyWithMe view. Something like this:

```
"Cameras": {
    "ChaseCam": {
        "X": -10,
        "Y": 0,
        "Z": 5,
        "Pitch": -10,
        "Roll": 0,
        "Yaw": 0
    }
}
```
Then use the custom camera (e.g., "ChaseCam") via `simGetImage()` or `simGetImages()`.

**Comment by taeseongkr** [comment]
> [@taeseongkr](https://github.com/taeseongkr) As far as I understand it,[ FlyWithMe](https://microsoft.github.io/AirSim/settings/#:~:text=FlyWithMe%3A%20Chase%20the%20vehicle%20from%20behind%20with%206%20degrees%20of%20freedom) is an external camera that is actually a ViewMode and not a camera itself attached to the AirSim drone in either Unreal or Unity. Due to this, changing settings.json will not give you any camera result from the FlyWithMe perspective because there is no camera.
> 
> Instead, what you could try is to add a new camera in your Unreal Engine editor and settings.json: Configure a camera at a fixed offset behind the vehicle to mimic the FlyWithMe view. Something like this:
> 
> ```
> "Cameras": {
>     "ChaseCam": {
>         "X": -10,
>         "Y": 0,
>         "Z": 5,
>         "Pitch": -10,
>         "Roll": 0,
>         "Yaw": 0
>     }
> }
> ```
> 
> Then use the custom camera (e.g., "ChaseCam") via `simGetImage()` or `simGetImages()`.

Thank you. My purpose is streaming the whole environment including the vehicle, not just only the drone's camera as first perspective. I find it very easy to set up camera anywhere in CARLA, but I have no idea to do it in AirSim. I don't know how to access to get the image of viewport.

**Comment by ssaigarimella** [comment]
@taeseongkr I understand what you mean, you want a camera that gives you a third-person-view like FlyWithMe does. You have to create another camera in the Unreal Editor/Unity editor that has a parent frame as the drone but fix it away from the body of the drone so you have this kind of view. Using this you will have a body-fixed frame camera but it will capture the environment including the drone.

**Comment by taeseongkr** [comment]
@ssaigarimella Thank you. As far as I investigated, I found some cpp and header files in Plugin folder. Would you mind giving me a direction how to create a camera or any keyword or tutorial that I can research. I appreciate that.
