### ISSUE TITLE
Packaging issues（windows to Linux packaging）

### ISSUE THREAD

**Issue by Hijiongfeng** [microsoft/AirSim#4078]
### What's your question?

![Snipaste_2021-10-13_14-17-04](https://user-images.githubusercontent.com/73459904/137077769-171dbbdc-e80c-466e-ba2b-6e476e870f68.png)
I am using the windows platform to package to the linux platform and want to generate a file that can be executed under linux. I followed the above figure to operate, but the following problems occurred.
What should i do？

![Snipaste_2021-10-13_14-23-07](https://user-images.githubusercontent.com/73459904/137078315-c5f44e45-031e-47c8-ac02-58c1c60d7ef1.png)
![Snipaste_2021-10-13_14-23-16](https://user-images.githubusercontent.com/73459904/137078320-399c3680-d728-49ca-b3a6-ed2dce5a8dbd.png)

**Comment by jonyMarino** [comment]
Hi @Hijiongfeng! I've never done that, but I'm going to try to help you. What I see is that it doesn't find the libraries that are compiled when working on Linux. Can you compile AirSim inside a WSL environment and copy the .a files missing for the packaging?

**Comment by Hijiongfeng** [comment]
> Hi @Hijiongfeng! I've never done that, but I'm going to try to help you. What I see is that it doesn't find the libraries that are compiled when working on Linux. Can you compile AirSim inside a WSL environment and copy the .a files missing for the packaging?

Hi, thank you for your help. I previously compiled AirSim successfully on Ubuntu, I copied the missing .a file to the corresponding directory, and then packaged it successfully. I want to know if I can not use this copy method, it is too cumbersome, can I directly use a cross-compilation method to operate. If so, what should I do?

**Comment by jonyMarino** [comment]
You can use WSL2 inside windows as an alternative.
