### ISSUE TITLE
Replace common mavlink message set with ardupilotmega mavlink message set

### ISSUE THREAD

**Issue by auturgy** [Microsoft/AirSim#409]
The ardupilotmega mavlink dialect is a superset: it includes common, uavionix and it's own custom messages.  Replacing mavlink common with ardupilotmega opens the use of AirSim to a user base that is an order of magnitude (or more) larger than restricting to common, whilst maintaining complete compatibility with the px4 codebase.
For example QGroundControl uses the ardupilotmega dialect for exactly the reason I have articulated above.
Noting the issues you have had with px4, it makes sense to do this!

**Comment by sytelus** [comment]
That's great idea. Unfortunately I'm not familiar with ardupilotmega's version of MavLink. However if you have any experience with it, we had love to get pull request :).

**Comment by auturgy** [comment]
Lol. Ok. I can do that, but it's as simple as switching common.xml for Ardupilotmega.xml. Good to know you're open to it though 

Regards,

James

**Comment by sytelus** [comment]
@lovettchris might be interested in this.
