### ISSUE TITLE
Compliation problem:I encountered a problem with vscode

### ISSUE THREAD

**Issue by Hijiongfeng** [microsoft/AirSim#4090]
### What's your question?

I do not used python, I want to use AirSim's C++ API .The environment I use is uBuntu 16.04+ vscode.I wrote a Car.cpp and copied the offical hellocar.cpp. I wrote the code of launch.json and task.json ,and added the directores and corresponding files containing the library and the link library.When I press F5,I cannot compile through. What do I do?

The cpp file I wrote:
![Screenshot from 2021-10-19 17-06-47](https://user-images.githubusercontent.com/73459904/137881673-52d526ee-ea6f-4a35-afce-d9a651b52f89.png)
Two json files:
![Screenshot from 2021-10-19 17-07-07](https://user-images.githubusercontent.com/73459904/137882018-fded3348-ab77-4ba8-84c4-8cf54f9f965c.png)
![Screenshot from 2021-10-19 17-07-22](https://user-images.githubusercontent.com/73459904/137882026-63d71683-42b1-4efa-a613-c2ba23cdce6d.png)
The problem i encountered：
![Screenshot from 2021-10-19 17-03-54](https://user-images.githubusercontent.com/73459904/137882114-0d98e94b-0456-4912-9790-b9b3024e50a1.png)
![Screenshot from 2021-10-19 17-04-28](https://user-images.githubusercontent.com/73459904/137882125-ccdf8d39-ff04-4871-a49d-208509d3efb9.png)

 I have searched on Google for a long time, I don't know why this happens, what should I do?

**Comment by Hijiongfeng** [comment]
I saw in the file area of vscode that the executable file was generated at the beginning, but immediately disappeared. I don't know why this happened! what should I do?

**Comment by Hijiongfeng** [comment]
> Hi @Hijiongfeng! You should use vscode together with [the cmake plugin](https://code.visualstudio.com/docs/cpp/cmake-linux)

Can you provide me with a written CMakeLists.txt? I don't understand that it should contain directories and link directories, as well as libraries that need to be linked! Thank you very much, this problem has troubled me for a long time!

**Comment by Hijiongfeng** [comment]
finished

**Comment by sandilyasg** [comment]
@Hijiongfeng Can you please provide the CMakeLists.txt file you used in your VSCode project? I am looking at [Using C++ APIs for AirSim](https://microsoft.github.io/AirSim/apis_cpp/), specifically on what to add to CMakeLists.txt with the CMake extension, but I am confused with the References: Reference AirLib part.

**Comment by Hijiongfeng** [comment]
Hello, the attachment is my CMakelistts.txt file at that time. Due to time reasons, I did not find the source code (.cpp) at that time. These files are for reference only.





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/AirSim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月18日(星期三) 凌晨4:17
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/AirSim] Compliation problem:I encountered a problem with vscode (Issue #4090)





 
@Hijiongfeng Can you please provide the CMakeLists.txt file you used in your VSCode project? I am looking at Using C++ APIs for AirSim, specifically on what to add to CMakeLists.txt with the CMake extension, but I am confused with the References: Reference AirLib part.

**Comment by sandilyasg** [comment]
Hi, thanks for your reply. Can you please send the attachment again? It
looks like there was no CMakeLists.txt attachment to your email.
