### ISSUE TITLE
Spawning multiple "ComputerVision" pawns results in actor name conflict.

### ISSUE THREAD

**Issue by Octavian-Zhang** [microsoft/AirSim#4092]
## Bug report 
- AirSim Version/#commit: [f1ccd2d109073e2b16506a5ed31240ffad92d815](https://github.com/microsoft/AirSim/commit/f1ccd2d109073e2b16506a5ed31240ffad92d815)
- UE/Unity version: UE4.27
- autopilot version: N/A
- OS Version: Windows 10 21H1

### What's the issue you encountered?
I'm trying to spawn multiple "ComputerVision" pawns using the following settings.json content:
`{
  "SettingsVersion": 1.2,
  "SimMode": "ComputerVision",
  "Vehicles": {
    "Cam1": {
      "VehicleType": "ComputerVision",
      "X": 26,
      "Y": -1,
      "Z": -10
    },
    "Cam2": {
      "VehicleType": "ComputerVision",
      "X": 26,
      "Y": -2,
      "Z": -20
    }
  }
}`
The compiled Unreal executable fails to start with the following error prompt:
![image](https://user-images.githubusercontent.com/21289147/137910390-a564ad6c-c16b-41be-8195-6e39750f9a32.png)

### Settings
The settings.json is as such short as possible:
`{
  "SettingsVersion": 1.2,
  "SimMode": "ComputerVision",
  "Vehicles": {
    "Cam1": {
      "VehicleType": "ComputerVision",
      "X": 26,
      "Y": -1,
      "Z": -10
    },
    "Cam2": {
      "VehicleType": "ComputerVision",
      "X": 26,
      "Y": -2,
      "Z": -20
    }
  }
}`
If only one instead of two "ComputerVision" pawn is to be spawned at Unreal start, the error above disappears. Try to delete "Cam2" content from this settings.json content to see the effect.

### How can the issue be reproduced?
1. Place the settings.json file above under Documents\AirSim.
2. Down and run any precompiled [Unreal binary executable](https://github.com/Microsoft/AirSim/releases).

### Include full error message in text form
An actor of name 'camera_front_center' already exists in level 'Level/Game/Maps/LandscapeMap.LandscapeMap:PersistentLevel'.

**Comment by jonyMarino** [comment]
I confirm the bug. I tried version 1.2.2, and it didn't happen. Is it suitable for you?

**Comment by Octavian-Zhang** [comment]
> I confirm the bug. I tried version 1.2.2, and it didn't happen. Is it suitable for you?

Sure, @jonyMarino, thanks for providing the workaround. It solves my problem. Cheers!
