### ISSUE TITLE
Trig function error in PythonClient.py toEulerian 

### ISSUE THREAD

**Issue by gmgremillion** [Microsoft/AirSim#411]
The function relating quaterions to pitch angle in PythonClient.py should be arcsine rather than sine.

**Comment by sytelus** [comment]
Thanks for pointing this out. Looks like there were more than one issue with that part of code. I've checked-in the fix here: https://github.com/Microsoft/AirSim/commit/3aa4195367eaab6bf1992d853daad8432de93215#diff-2f1d68eceb91891441035e0ceb45c2e8
