### ISSUE TITLE
Parameter color_rgba of simSetTraceLine, Changing transparency does not take effect

### ISSUE THREAD

**Issue by xw1518** [microsoft/AirSim#4118]
### Discussed in https://github.com/microsoft/AirSim/discussions/4115

<div type='discussions-op-text'>

<sup>Originally posted by **xw1518** October 25, 2021</sup>
I tried to change the transparency of the lines，adopt  Parameter color_rgba, use different value,but Transparency cannot be change
the example like
![pic002](https://user-images.githubusercontent.com/78134152/138649258-9bd33772-4b24-46f7-941f-43b66b3217fa.png)
![pic001](https://user-images.githubusercontent.com/78134152/138649250-5da4b214-5f8e-4d21-9fd9-94575cb5d7a4.png)

</div>

**Comment by rajat2004** [comment]
This looks like an issue in UE4 itself, the Alpha values are ignored according to https://answers.unrealengine.com/questions/929967/view.html and the linked issue which has a similar comment in March 2021, so likely not fixed. Search in the UE4 PRs as well but didn't find anything

**Comment by xw1518** [comment]
> This looks like an issue in UE4 itself, the Alpha values are ignored according to https://answers.unrealengine.com/questions/929967/view.html and the linked issue which has a similar comment in March 2021, so likely not fixed. Search in the UE4 PRs as well but didn't find anything

I see . Thank you for your reply
