### ISSUE TITLE
"Computer Vision" Mode problem

### ISSUE THREAD

**Issue by lxgen** [Microsoft/AirSim#414]
When I use "computer vision" mode and press "up", "down","left" and "right" buttons, the drone can just move along four fixed directions on the horizontal plane， no matter how the drone's direction changes  .  How can I move it in other horizontal directions?

**Comment by Robin-Wong** [comment]
Please try the buttons w, a, s, d.

**Comment by sytelus** [comment]
I see... When you switch to FPV mode ("[" key), the vehicle doesn't move in forward direction when press forward arrow key. I just fixed this. Please try out the latest code.
