### ISSUE TITLE
airsim hardware resources requirement

### ISSUE THREAD

**Issue by Flautdn** [microsoft/AirSim#4143]
### What's your question?

Should I require a gpu (Nvidia's or else) to execute airsim with unreal 4 support 
on AWS ec2 t2 micro ubuntu 18.04 instance

I am installing airsim with the following approach:

pip3 install scikit-build
pip3 install install msgpack-rpc-python
pip3 install numpy	 
pip3 install airsim

I got the city environment asset folder as below

wget https://github.com/microsoft/AirSim/releases/download/v1.6.0-linux/AirSimNH.zip

when I unzipped and ran the below command to start the city environment in the aws ubuntu 18.04 t2.micro instance 
./AirSimNH -windowed

Ubuntu 18.04, AirSim 1.6 Python 3 Unreal 4, Aws ec2 instance , t2.xlarge

**Comment by jonyMarino** [comment]
There is an azure environment ready for use with AirSim:
https://microsoft.github.io/AirSim/azure/

dup of #4148
