### ISSUE TITLE
DroneShell error

### ISSUE THREAD

**Issue by akshaysw** [Microsoft/AirSim#416]
![capture](https://user-images.githubusercontent.com/22980149/29262747-85aa5aae-80f3-11e7-8d1e-85b3c05e9e5b.PNG)
can anyone tell me why am i getting this error

**Comment by akshaysw** [comment]
![screenshot 6](https://user-images.githubusercontent.com/22980149/29270375-1c1c4004-8114-11e7-9044-dbeb3095359c.png)
this is my setting file.

**Comment by akshaysw** [comment]
I thought i made some mistake while installing airsim because keyboard keys were not working, so I deleted the entire airsim directory and again cloned it from git and followed this instructions [https://github.com/Microsoft/AirSim/blob/master/docs/build.md](url) then I created new project made following changes in settings.json as shown in the following picture. now in computer vision mode is active and keyboard keys are also working but when I'm trying to use DroneShell it's giving different error as shown in the following picture. @sytelus thanks in advance
![screenshot 10](https://user-images.githubusercontent.com/22980149/29272287-febf27b6-811c-11e7-9899-bcd0df293416.png)
![screenshot 11](https://user-images.githubusercontent.com/22980149/29272288-fec7f30a-811c-11e7-8e3b-1519f8b6a3a1.png)
![screenshot 9](https://user-images.githubusercontent.com/22980149/29272289-fecbaf86-811c-11e7-874a-29ba609196b1.png)

**Comment by sytelus** [comment]
Commands that require physics are not supported in CV mode. I guess we should document this better. In CV mode, you don't have drone, you just have cameras. It is supposed to be used with APIs simSetPose to set pose for camera and simGetImages to get images. Nothing else is expected to be functional.

We are soon planning to release simple_flight firmware which will have full drone functionality but without needing PX4.
