### ISSUE TITLE
Simulate a wind disturbance

### ISSUE THREAD

**Issue by smishraasu** [Microsoft/AirSim#417]
Hi,

I am using AirSim to test HIL with my quadcopter. I wanted to know if there is any method to simulate wind as disturbance in AirSim for some disturbance rejection algorithm testing ? 

Thanks.
Shatadal

**Comment by Timebutt** [comment]
I'm subscribing to this topic, as I too would like to find out how this can be done!

**Comment by Timebutt** [comment]
I just noticed this is a duplicate issue: a topic already exists here #284.

**Comment by sytelus** [comment]
I'll close this. Let's keep #284  open.
