### ISSUE TITLE
Wrong timestamp when using small `ClockSpeed` 

### ISSUE THREAD

**Issue by rhalaly** [microsoft/AirSim#4232]
## Bug report 

- AirSim Version/#commit: 3.1
- UE/Unity version: 4.18
- autopilot version:
- OS Version: Windows 11

### What's the issue you encountered?
It seems that `getCarState().timestamp` isn't affected by the `ClockSpeed` settings. 

Running a simulation for 10 seconds under ClockSpeed of 0.5 - which means that the actual simulation time should be 5 seconds, doesn't affect the `timestamp` since it still thinks it runs for 10 seconds. 

### Settings
```json
{
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "ClockSpeed": 0.5
}
```

### How can the issue be reproduced?

1. Set the `ClockSpeed` to `0.5` (or any value <1)
2. Run the simulation for 10 seconds
3. Read the value from `getCarState().timestamp`
4. The value will be about 10 seconds instead of 5 seconds (10 * 0.5)

### Include full error message in text form
No error message

**Comment by zimmy87** [comment]
Hi @rhalaly, I've put out #4305 for fixing this behavior, please test with the PR applied and let me know if you have any issues

**Comment by rhalaly** [comment]
@zimmy87 thank you so much for the fix! Currently, I have some issues with compiling AirSim from source, so I probably can't test it soon... 😞
