### ISSUE TITLE
No instance of VS Error.

### ISSUE THREAD

**Issue by Mohamed-Omran** [microsoft/AirSim#4235]
### What's your question?

I cannot build AirSim with VS 2022.

### Include context on what you are trying to achieve

When executing `build.cmd` I get the following error:
```
CMake Error:
  Generator

    Visual Studio 16 2019

  could not find any instance of Visual Studio.
```
#### Context details

Win 10
VS 17.0 
UE 4.27.2

### Include details of what you already did to find answers
N/A

**Comment by alonfaraj** [comment]
AirSim currently support VS 2019.
You can try change this line in `build.cmd`:
`cmake -G"Visual Studio 16 2019" ..`
to:
`cmake -G"Visual Studio 17 2022" ..`
but I'm not sure it's going to work

**Comment by Mohamed-Omran** [comment]
Thank you @alonfaraj.
I tried the version this amazing person @elevir forked and it worked fine on VS 2022

**Comment by rhalaly** [comment]
@Mohamed-Omran can you share more info on how to build it with VS 2022? Which fork did you use?

**Comment by Mohamed-Omran** [comment]
@rhalaly  https://github.com/elevir/AirSim
