### ISSUE TITLE
Free Unreal Engine Environments 

### ISSUE THREAD

**Issue by robotvin** [Microsoft/AirSim#424]
Please provide me links where i can get free unreal engine environments.
Where i can get the environment shown in Manual Flight Demo section.

**Comment by Timebutt** [comment]
The excellent [step-by-step tutorial](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md) describes in detail how you can get AirSim running with the free LandscapeMountains environment.

**Comment by themmer** [comment]
@robotvin Looks like Epic Zen Garden is free as well. You should pry close this issue.

**Comment by sytelus** [comment]
Look in to the Learn tab of Epic Game Launcher. You might find environments that you can add to project or full ready made projects (in which case delete any startup matinee stuff).

Also, here's tutorial on how to import 3rd party environments from TurboSquid.com or cgitrader.com: https://www.youtube.com/watch?v=y09VbdQWvQY

![image](https://user-images.githubusercontent.com/2096835/32757776-15d2ff0c-c896-11e7-9973-d6ca8e63e984.png)

**Comment by chris-aeviator** [comment]
Where can I get the environments supplied in the Windows (& now exp. ubuntu builds) e.g. the city environment?
