### ISSUE TITLE
help on how to use my car instead of default car in airsim

### ISSUE THREAD

**Issue by dellhuyongcai** [microsoft/AirSim#4242]
### What's your question?

I just want to learn how to use  my car in airsim, no documents can be referred,just come here to find materials,hope someone give steps as clearly as possible,thanks a lot!!

**Comment by Sabrin0** [comment]
Are you using Unreal? In this case first of all you need to declare the pawn path in the `setting.json`. For example:

```
"PawnPaths": {
    "MyVehicle": { "PawnBP": "Class'/Game/path/to/BP_MyVehicle.BP_MyVehicle_C'" }
  },
```
Then  for the vehicle setting:

```
"Vehicles": {

    "MyVehicle": {
      .
      .
      "PawnPath": "MainDrone",
      .
      .
      },
      }
```
I did so and It works properly. Of course you must have your car BP properly configured in UE (e.g. mesh, material, actuators...)

**Comment by dellhuyongcai** [comment]
thanks a lot,Successfully solved this problem!
