### ISSUE TITLE
Trajectory Evaluation 

### ISSUE THREAD

**Issue by fmzhu** [Microsoft/AirSim#427]
hello,
I have some questions about the paper: https://arxiv.org/pdf/1705.05065.pdf 
For the Part 4- Experiments, there are two figures, namely, figure 4 and figure 5. How to observe the sensor data like this way in figure 4 and 5. It seems not like LogViewer.
![unbenannt](https://user-images.githubusercontent.com/9269633/29499058-0059cf9a-8609-11e7-9097-10facb6f1cb3.PNG)
![unbenannt1](https://user-images.githubusercontent.com/9269633/29499059-005b7994-8609-11e7-9016-67ce512c15f6.PNG)
Thank you very much for your help!

**Comment by sytelus** [comment]
First plot was generated from raw data log and second was generated from estimated position vs simulation ground truth position. LogViewer only shows MavLink messages.
