### ISSUE TITLE
Line	Suppression State Error	LNK1104	cannot open file 'rpc.lib'	HelloDrone	F:\UAVHIDL\Airsim\Airsim\HelloDrone\LINK	1	

### ISSUE THREAD

**Issue by icydust** [Microsoft/AirSim#428]
when i build the airsim.sln the rpc,lib ,How can i solve this problem?
Waiting for an answer online
sincerely！

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'rpc.lib'	HelloDrone	F:\UAVHIDL\Airsim\Airsim\HelloDrone\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'rpc.lib'	Examples	F:\UAVHIDL\Airsim\Airsim\Examples\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'rpc.lib'	DroneShell	F:\UAVHIDL\Airsim\Airsim\DroneShell\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'rpc.lib'	DroneServer	F:\UAVHIDL\Airsim\Airsim\DroneServer\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'F:\UAVHIDL\Airsim\Airsim\AirLib\lib\x64\Debug\AirLib.lib'	AirLibUnitTests	F:\UAVHIDL\Airsim\Airsim\AirLibUnitTests\LINK	1	
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1181	cannot open input file 'rpc.lib'	AirLib	F:\UAVHIDL\Airsim\Airsim\AirLib\LINK	1	

![17552427645474657](https://user-images.githubusercontent.com/17896857/29501560-fea5363c-865b-11e7-9306-5782a7265167.jpg)
@sverrejoh

**Comment by sytelus** [comment]
Please make sure you are using the latest version have followed the [build doc](https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md) properly.

**Comment by icydust** [comment]
Thank you for your help，i try to dowload the  file with the git clone ,and rebuild it , now i can rebuild it by vs2015,but when i use the "developer command prompt for vs2015,it have an other error.\
like this :
![123](https://user-images.githubusercontent.com/17896857/29824816-15435c0c-8d05-11e7-96c4-49378e07bad1.PNG)
![1234](https://user-images.githubusercontent.com/17896857/29824840-25257358-8d05-11e7-9c6e-2a727288b39e.PNG)
![1235](https://user-images.githubusercontent.com/17896857/29824869-35b3b57c-8d05-11e7-8479-06f91758ca07.PNG)



 @sytelus

**Comment by icydust** [comment]
when i launch myproject with unreal it have this error:
![136](https://user-images.githubusercontent.com/17896857/29825146-0de08470-8d06-11e7-9279-ad16511b4b30.PNG)

How can i solve this problem?
@sytelus
