### ISSUE TITLE
Unity Simulator Crashes When Using External Physics Engine Setting

### ISSUE THREAD

**Issue by ClarkZha** [microsoft/AirSim#4285]
AirSim Version/#commit: 1.7.0
UE/Unity version: Unity 2019.3.12.f1
autopilot version: - N/A
OS Version: Ubuntu 18.04

## Bug report 

Unity simulation will crash if ` "PhysicsEngineName":"ExternalPhysicsEngine"` is set in the settings.json. 

The Unity editor will crash once the drone simulator is chose in the scene selection.
![image](https://user-images.githubusercontent.com/39609430/149241037-6ec4ce71-91dc-4dcd-bb18-b9c8d4b2930b.png)

A quick dig in the code base suggests that the external physics engine option may not be setup properly in the Unity wrapper.
For example, in SimWorldModeBase.cpp for Unity wrapper, the "ExternalPhysicsEngine" will not be parsed and an error will be thrown. 
![image](https://user-images.githubusercontent.com/39609430/149241208-3456efdf-bd8f-4645-913d-3490ff384df9.png)

**Comment by jonyMarino** [comment]
Hi @ClarkZha! you can fix it adding these lines before the last else:
```c++
    else if (physics_engine_name == "ExternalPhysicsEngine") {        
        physics_engine.reset(new msr::airlib::ExternalPhysicsEngine());
    }
```

**Comment by ClarkZha** [comment]
Hi @jonyMarino! Thanks for the response. 

I did a similar hack earlier and it seemed to work. I wasn't sure if this would cause bug in other places in the code so I didn't post it here to avoid distract fellow developers. Glad this was the right approach : )
