### ISSUE TITLE
blocks.sln wrong

### ISSUE THREAD

**Issue by Vampireqyz** [microsoft/AirSim#4288]
## Bug report 

- AirSim Version/#commit:
- UE/Unity version:
- autopilot version:
- OS Version:

### What's the issue you encountered?

![FE0V_RY718%5VW$OK24%KX](https://user-images.githubusercontent.com/96807892/149303499-0c67883f-155c-4f85-803f-747044bacd77.png)

![_%UCK$_L$X_KCK222@U5UBO](https://user-images.githubusercontent.com/96807892/149303151-376e6ee5-0843-4688-bb56-ed38a1138a2a.png)
why can't open this "delayimp.lib"file
### How can the issue be reproduced?

1.
2.

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

**Comment by jonyMarino** [comment]
dup of #4280
