### ISSUE TITLE
takeoff command is not working

### ISSUE THREAD

**Issue by akshaysw** [Microsoft/AirSim#429]
hello, I am trying to use drone shell to control drone but I am getting following error. what should I do?

RPC Error: rpclib: function 'takeoff' (called with 1 arg(s)) threw an exception. The exception contained this information: TakeOff command rejected by drone.
![screenshot 15](https://user-images.githubusercontent.com/22980149/29511869-1aa0d8c4-867e-11e7-931d-7a026465bc35.png)

**Comment by sytelus** [comment]
Looks like PX4 is not allowing you to takeoff. This could be because of many reasons such as RC switches are not down or you have buggy release of PX4.

**Comment by akshaysw** [comment]
hello @sytelus i have followed all the step you mentioned above but now i am getting following error, my setting.json is attached below
![screenshot 19](https://user-images.githubusercontent.com/22980149/29921828-ce41254c-8e70-11e7-824b-79e833199884.png)
![screenshot 20](https://user-images.githubusercontent.com/22980149/29921830-d0580648-8e70-11e7-8ef5-20b032c8f5e5.png)
![screenshot 21](https://user-images.githubusercontent.com/22980149/29921834-d262fa42-8e70-11e7-9b3b-7416d2bbe2f5.png)

**Comment by sytelus** [comment]
Can you see the value of message parameter? You can just continue or comment out that statement. It's just there to let you know there was some error message from flight controller. Also please make sure to use the latest version.  We also have binary release now that you can just simply download and run: [See docs](https://github.com/Microsoft/AirSim/blob/master/docs/use_precompiled.md) for more info.

**Comment by akshaysw** [comment]
hello @sytelus yes binary is working perfectly fine and API's are also working thanks a lot though i could not figure out what was the problem before. can you please tell me how did you make binary?

**Comment by sytelus** [comment]
Binary file is using simple_flight as flight controller instead of PX4. I believe the problem was in PX4 setup before.
