### ISSUE TITLE
how to drive the multirotor rotate on pitch angle and roll angle

### ISSUE THREAD

**Issue by Cming7** [microsoft/AirSim#4304]
### What's your question?

>I want to drive the multirotor rotate on pitch angle and roll angle. Does multirotor support moveByAngleZAsync? What's the TODO meaning in the [Unity APIs](https://microsoft.github.io/AirSim/unity_api_support/)?

### Include context on what you are trying to achieve

>I just find the rotateToYawAsync API to drive the multirotor rorate on yaw angle. And the multirotor pose doesn't change using moveByAngleZAsync API.
```
client.moveByAngleZAsync(0, 0, -2, 30 / 180 * math.pi, 5).join()
```

**Comment by sudo-hello-world-2** [comment]
Hey @Cming7,
I think TODO just means to do. Try using moveByAngleRatesZAsync(roll_rate, pitch_rate, yaw_rate, z, duration, vehicle_name=''). If you need to, check the implemented API page for more details (https://microsoft.github.io/AirSim/api_docs/html/ ).

**Comment by Gastastrophe** [comment]
Are you building Airsim on Unity? If an API says TODO in the Unity APIs, then that means it works in Unreal Engine but not Unity.

**Comment by Cming7** [comment]
> Are you building Airsim on Unity? If an API says TODO in the Unity APIs, then that means it works in Unreal Engine but not Unity.

I build the project on UE4.27.

**Comment by zimmy87** [comment]
Hi @Cming7, the server binding for this API was removed in #2297. You'll want to use the `moveByRollPitchYawZAsync` API instead.

**Comment by zimmy87** [comment]
I put out PR #4338 to fix this.
