### ISSUE TITLE
simContinueForTime doesn't respect ClockSpeed

### ISSUE THREAD

**Issue by rhalaly** [microsoft/AirSim#4307]
## Bug report 

- AirSim Version/#commit: 0becf9148d88c19c3ffd69359ebe1f9c3ae43826
- UE/Unity version: 4.27
- autopilot version:
- OS Version: Windows 11

### What's the issue you encountered?
Wen setting high `ClockSpeed` and using `simContinueForTime` it uses the real world time, not the simulation time, which is faster/slower due to the `ClockSpeed`

### Settings
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "ClockSpeed": 10
}
```

### How can the issue be reproduced?

1. Run an environment with `ClockSpeed` set to `10`.
2. Run `simContinueForTime` for 10 seconds.
3. The simulation will stop after 10 (real life) seconds instead of 1 (real life) second.

### Include full error message in text form
Not relevant

**Comment by jonyMarino** [comment]
Fixed in #4305
