### ISSUE TITLE
ClockSpeed is not linear scale

### ISSUE THREAD

**Issue by rhalaly** [microsoft/AirSim#4308]
## Bug report 

- AirSim Version/#commit: 0becf9148d88c19c3ffd69359ebe1f9c3ae43826
- UE/Unity version: 4.27
- autopilot version:
- OS Version: Windows 11

### What's the issue you encountered?

The ClockSpeed is not a linear scale as I assumed. I would expect that the equation is `sim_time = real_life_time * ClockSpeed` but this is not the case. Simulating 10 (real life) seconds with `ClockSpeed=1` is not the same as simulating 1 (real life) seconds with `ClockSpeed=10`. 

Tested with various values for `ClockSpeed`.

### Settings

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "ClockSpeed": 10
}
```

### How can the issue be reproduced?

1. Run the simulation with `ClockSpeed` set to `1`.
2. Drive with `simContinueForTime` for 10 seconds. 
3. Run the simulation with `ClockSpeed` set to `10`.
4. Drive with `simContinueForTime` for 1 seconds.
5. The car will be in a different position (significantly).

### Include full error message in text form
Not relevant

**Comment by jonyMarino** [comment]
Fixed in #4305
