### ISSUE TITLE
Can't use BP_CameraDirector to chase the drone

### ISSUE THREAD

**Issue by jimchenhub** [microsoft/AirSim#431]
I always use 'Flay with me' View. But when I fly in the forest, the drone will be shaded from the trees and and leaves. So I want to use a fixed view to chase the drone as mentioned in [youtube setup video](https://www.youtube.com/watch?v=1oY8Qu5maQQ&feature=youtu.be) at the end. 

I first made sure there is no `Player Start` in the environment, and added the a BP_FlyingPawn, a BP_PIPCamera and a BP_CameraDirector.

But in the `Details` of BP_CameraDirector as shown below, there is no `target pawn` and `external cameras` .

![notfound](https://user-images.githubusercontent.com/7524808/29518768-42611f70-86ad-11e7-89b6-f42d85e54e88.PNG)

Is there a way to add a chasing camera in this latest version?

**Comment by sytelus** [comment]
These properties were accidentally made private in recent refactoring. We will restore them soon.

**Comment by edithcomas** [comment]
Has this feature been restored? Have you found a workaround for chasing in the meantime?

**Comment by GitWyd** [comment]
@sytelus Could you please let us know which properties they were, and which files are affected? Then we could temporarily fix the code until they are restore.

**Comment by HarrisSym** [comment]
@sytelus is there an update to this problem?

**Comment by jimchenhub** [comment]
Hi @HarrisSym, now it can use manual view mode during the flight. Just click M to toggle it. You can press F1 for more detail.

**Comment by HarrisSym** [comment]
@jimchenhub  I  was refferring to  the issue with the properties of the BP_CameraDirector Blueprint.

**Comment by jonyMarino** [comment]
related to #3050 use case

**Comment by zimmy87** [comment]
This is an old issue. Now things can be configured through settings.json. Closing until someone is interested in having this again.
