### ISSUE TITLE
Get precise detection of objects in global NED frame

### ISSUE THREAD

**Issue by qcsui** [microsoft/AirSim#4318]
### Discussed in https://github.com/microsoft/AirSim/discussions/4298

<div type='discussions-op-text'>

<sup>Originally posted by **qcsui** January 18, 2022</sup>
Hi, right now I am trying to get coordinates of objects in global NED frame. For that, I used 
```py
cylinders = client.simGetDetections(camera_name, image_type)  # relative position in local NED frame
multirotor_state = client.getMultirotorState()  # drone's position in global NED frame
```
then by adding these two, I should get the object's location in the global NED frame. However, due to a time lag between these two actions(I think so), the position of targets that I got is not accurate.
![2022-01-18 112544](https://user-images.githubusercontent.com/40121130/149919477-98f5d83e-eb58-406f-a214-7b4f124d9582.jpg)
The big circle is my trajectory, and the triangles are the observations of targets.
So the questions are:
- Can anyone give me some suggestions on how I can get the exact position of the targets in the global NED frame?
- I noticed that `GeoPoint` is given in `DectionInfo` which should be able to convert into NED frame. Anybody has done that in practice?
</div>

**Comment by chongjeelee** [comment]
i face the same problem ,can not accurate result,in my testing,object is moving by spline.
