### ISSUE TITLE
airsim can not generate accuracy dynamic objects' 2D_box

### ISSUE THREAD

**Issue by chongjeelee** [microsoft/AirSim#4320]
## Bug report 

- AirSim Version/#commit:v1.6
- UE/Unity version:UE4.25
- autopilot version:-
- OS Version:win10

### What's the issue you encountered?

when i set objects moving with blueprint spline,i found it can not detect the accuracy position when object moving on sky.
Just like this below,the BP_airBalloon0 is statical object ,the BP_airBalloon2 is motion object with spline .It is easy to see that,the statical one can get very good bounding box ,but the motion one's result is very bad,sometimes can not get bounding box,sometimes get very big dounding box.
i also find the relative_pose of moving object is still same! this is real incorrect!
https://user-images.githubusercontent.com/30140969/151135810-152fe722-a6f2-42a2-a4b6-fed2bef351af.mp4

### Settings

![image](https://user-images.githubusercontent.com/30140969/151135933-88db5a24-b965-4661-a249-495d2f27254d.png)

### How can the issue be reproduced?

1.i follow the detection.py ,and run it with my environment,and the problem occured.
2.the code below:
![image](https://user-images.githubusercontent.com/30140969/151136419-f5ae6d33-41ed-4d17-8fe7-f4f9da8a6898.png)

### Include full error message in text form

**What's better than filing an issue? Filing a pull request :).**

**Comment by chongjeelee** [comment]
i have solved this problem with blueprint!

**Comment by Seeseallllll** [comment]
> i have solved this problem with blueprint!
Hello, I also encountered the generation problem of 2d bounding box, how do you use the blueprint to solve it? Could you share it in detail? Thanks!

**Comment by bing-zhub** [comment]
> i have solved this problem with blueprint!

Same problem, how do you fix this problem using BluePrint? Could you give us a more detail solution?

Appreciated!
