### ISSUE TITLE
Workflows are referencing vulnerable actions

### ISSUE THREAD

**Issue by igibek** [microsoft/AirSim#4326]
Hello, there! 

As part of the university research we are currently doing regarding the security of Github Actions, we noticed that one or many of the workflows that are part of this repository are referencing vulnerable versions of the third-party actions. As part of a disclosure process, we decided to open issues to notify GitHub Community. 

*Please note that there are could be some false positives in our methodology, thus not all of the open issues could be valid. If that is the case, please let us know, so that we can improve on our approach. You can contact me directly using an email: ikoishy [at] ncsu.edu* 

Thanks in advance
1. The workflow **test_windows.yml** is referencing action **ilammy/msvc-dev-cmd** using references **v1.4.1**. However this reference is missing the commit [74a501b](https://github.com/ilammy/msvc-dev-cmd/commits/74a501b) which may contain fix to the vulnerability.

The vulnerability fix that is missing by actions' versions could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider updating the reference to the action. 

*If you end up updating the reference, please let us know. We need the stats for the paper :-)*

**Comment by jonyMarino** [comment]
Thanks for the warning, @igibek!
