### ISSUE TITLE
How can I get the angular velocity of drone and control the drone by angular velocity?

### ISSUE THREAD

**Issue by lxgen** [Microsoft/AirSim#434]
I have read through the APIs in DroneControllerBase.hpp. However I don't know how to get the current angular velocity of the drone and how to control the drone by angular velocity. How can I get it? Thank you.

**Comment by sytelus** [comment]
Currently `moveByAngles` API allows to control drone by specifying pitch, roll, yaw. I think we will need new API to control drone by angle rates. The angular velocity is currently not exposed as well. We will add in these two new APIs.

**Comment by sytelus** [comment]
Let's continue this thread here: https://github.com/Microsoft/AirSim/issues/487
