### ISSUE TITLE
strange propeller animation

### ISSUE THREAD

**Issue by noahzn** [microsoft/AirSim#4347]
## Question
Strange propeller animation

I tried to replace the default drone with my own drone. I also replaced 4 propellers. But the animation is not correct.

![Media1 00_00_00-00_00_30](https://user-images.githubusercontent.com/8244850/153480220-9a44a93f-5aeb-4b10-a2f6-05fbca3dba79.gif)
### Include context on what you are trying to achieve
 The propellers operate correctly.

#### Context details

The settings.json file should be no problem.

### Include details of what you already did to find answers
N/A

**Comment by noahzn** [comment]
Can someone help?

**Comment by noahzn** [comment]
Hi @jonyMarino , I changed the model according to this video https://www.youtube.com/watch?v=Bp86WiLUC80
The 3d model is in .dae format, and I convert it to .fbx in Blender.

**Comment by jonyMarino** [comment]
@noahzn sorry for the late response. You don't have the center of the blueprint in the center of the propeller.
