### ISSUE TITLE
How to replace the drone to be a camera

### ISSUE THREAD

**Issue by jingleFun** [Microsoft/AirSim#435]
I want to get server images from one position with different orientation, but it seems that the center of rotation is the drone not the camera, am I right? how can I fix it? Actually, I have some positions, I just want to get same images(the depth image and label image) with server fixed orientations,  but The drone sometimes block the camera`s view, So how can I replace the drone with just a camera? Thank you.

**Comment by sytelus** [comment]
Good points. You are correct that center of rotation is drone, not camera. Let me think about how we can change this...

**Comment by jingleFun** [comment]
I`ve figure this out ^-^. I changed the BP_Flaying Pawn in unreal ,set the drone invisible, and set the camera to (0, 0, 0).

**Comment by sytelus** [comment]
The new computer vision mode now exactly does this.
