### ISSUE TITLE
Not working as intended simSwapTextures, simSetObjectMaterial, simSetObjectMaterialFromTexture

### ISSUE THREAD

**Issue by HSC-1** [microsoft/AirSim#4398]
### What's your question?

First
I Failed to use simSwapTextures 
Following the [example](https://microsoft.github.io/AirSim/retexturing/), I returned empty list

```
import airsim 

c = airsim.VehicleClient()
print(c.simSwapTextures("test",0))
```
![tags](https://user-images.githubusercontent.com/76798501/157433572-7725ae62-8ac2-46e8-8e88-ea5d8ccf5f7e.PNG)
![texture_bp](https://user-images.githubusercontent.com/76798501/157433582-c54659be-e8e2-494a-a0d1-ab51bb1a20ea.PNG)
So I'm looking for replacement
find #3992 
I try this API but not working as intended 

```
print(c.simSetObjectMaterialFromTexture("texture", "sample_texture.jpg"))
print(c.simSetObjectMaterial("texture","sample_texture"))
```
This output is True, False  
![image](https://user-images.githubusercontent.com/76798501/157434354-9fd5a013-cb26-4fa6-b52e-566edb408c85.png)

I obviously care about directories 
sample_texture.jpg in my diretory is with python file
Jist in case, I put it all diretory else

**Comment by HSC-1** [comment]
Add Visual Studio log message 
```
LogStreaming: Warning: Failed to read file 'sample_texture.jpg' error.
LogImageUtils: Warning: Error creating texture. sample_texture.jpg could not be found
```
I found Visual Studio log message. 
What settings should UE4 set so that the above errors are not occur?
I'm sure I put the image file in all the directories.

**Comment by HSC-1** [comment]
Sorry path problem and meterial string proble 
But if it's not blueprint, it doesn't work as intended.
The chair is blueprint,Just the table is static mesh actor.
![image](https://user-images.githubusercontent.com/76798501/161225573-d27b582d-d93e-40e1-ad3b-6999061969b3.png)

**Comment by deoliveirajoshua** [comment]
I'm getting a similar error when running the change_texture_example.py script in UE 4.27 version. The jpg is in the working directory of my script. How did you find a workaround?

**Comment by HSC-1** [comment]
Hello, can you try by modifying the full directory of jpg?
ex) "C:./user/Airsim/image.jpg"

**Comment by tmddn833** [comment]
Does 

>```
>print(c.simSetObjectMaterialFromTexture("texture", "sample_texture.jpg"))
>print(c.simSetObjectMaterial("texture","sample_texture"))
>```
>This output is True, False


Have you ever seen simSetObjectMaterial function work well?
Changing texture to simSetObjectMaterialFromTexture at runtime using jpg of absolute path was successful.
However, despite various attempts so far, no reflection has been made using the materials in the asset.
Below are the things I tried.

1) c.simSetObjectMaterial("texture","{absolute path to jpg}") -> False
2) c.simSetObjectMaterial("texture","{path copied from unreal editor by "copy reference"}") -> False
2) c.simSetObjectMaterial("texture","{path copied from unreal editor by "copy file path"}") -> False
![image](https://github.com/microsoft/AirSim/assets/60923926/506aa197-de5d-4918-9d54-85e3fa2fad89)

If there is anyone who know how to change the material with asset in the unreal editor, please leave comment.
Thank you
