### ISSUE TITLE
Unable to connect using Snapdragon Flight with PX4

### ISSUE THREAD

**Issue by duttonator** [Microsoft/AirSim#440]
Has anyone here successfully used Qualcomm's Snapdragon Flight with Airsim + UE4?

I've configured AirSim to connect via UDP, and I've verified the SF has a WiFi connection and an IP address, which is pingable from the Windows machine running AirSim. After running PX4 on the SF, it says it's using UDP external port 14550, which is what I configured AirSim to look for.

However, AirSim reports it cannot connect to the PX4 on that IP:port. Any suggestions?

**Comment by sytelus** [comment]
I would suggest first try out QGroundControl or other tools to make sure there is indeed valid reachable MavLink connection. Generally, if you can connect through QGroundControl then you can also connect through AirSim from same m/c. Also, please do post your settings.json.
