### ISSUE TITLE
Error in takeoff.py script

### ISSUE THREAD

**Issue by AnanasPie** [Microsoft/AirSim#441]
Hi all,

I get the following error when I try to execute takeoff.py script:
"msgpackrpc.error.RPCError:rpclib:server could not find function 'getHomePoint' with argument count 0.".
I hope some one can help me with it.
![whatsapp image 2017-08-28 at 23 25 53](https://user-images.githubusercontent.com/7532861/29793072-38d1c3ee-8c4b-11e7-9932-de80818ffd9f.jpeg)

**Comment by sytelus** [comment]
We have finally added also added simple_flight which eliminates need to set up PX4. Its also the default. So try out the latest version and use it with default settings (just delete settings.json if you have modified it). Also, above script is now renamed as hello_drone.py.
