### ISSUE TITLE
Error in DroneShell

### ISSUE THREAD

**Issue by litexx** [Microsoft/AirSim#442]
When I use the Computer Vision mode and typing the requestControl in DroneShell cmd , the AirSim will hit breakpoint. The breakpoint message shown "RemoteControl switch position disallows API control"

**Comment by sytelus** [comment]
Computer Vision mode does not have drone dynamics. It only has camera. So you don't need requestControl etc. The valid API calls are `simSetPose`, `simGetImage` and `simGetImages`. 

We have finally added also added simple_flight which eliminates need to set up PX4. Its also the default. So if you do need drone dynamics then getting new version and using with default settings (just delete settings.json if you have modified it).
