### ISSUE TITLE
Multirotor: shaky behavior on moveToPositionAsync() after finishing

### ISSUE THREAD

**Issue by rebeccasc** [microsoft/AirSim#4421]
### What's your question?

I want to follow a path and move a drone via python API `MultirotorClient.moveToPositionAsync()`. I'm not using `MultirotorClient.moveOnPathAsync()` because I do not have all the path points at this time. After `MultirotorClient.moveToPositionAsync()` has finished, the drone shakes until it's stabilized. I want to disable this "shaking", so that it looks like the drone flies smoothly on path. Is this possible via python API, settings.json, etc.?

### Include context on what you are trying to achieve

In general I receive the object poses on realtime via network and want to simulate them with using AirSim.

#### Context details

OS: windows 10
AirSim version: tested on 1.5.0 and 1.7.0, both same behavior

### Include details of what you already did to find answers
Basically I tried to set `drivetrain` and `yaw_mode` parameter in `MultirotorClient.moveToPosition()`. My code looks like this:
```python
client = airsim.MultirotorClient()
client.confirmConnection()
client.enableApiControl(True)

client.moveToPositionAsync(10, 10, -40, 5, drivetrain=airsim.DrivetrainType.ForwardOnly, yaw_mode=airsim.YawMode(False, 0)).join()
# here the drone shakes
client.moveToPositionAsync(20, 10, -40, 5, drivetrain=airsim.DrivetrainType.ForwardOnly, yaw_mode=airsim.YawMode(False, 0)).join()
# here the drone shakes
client.moveToPositionAsync(30, 10, -40, 5, drivetrain=airsim.DrivetrainType.ForwardOnly, yaw_mode=airsim.YawMode(False, 0)).join()
# here the drone shakes
client.moveToPositionAsync(40, 10, -40, 5, drivetrain=airsim.DrivetrainType.ForwardOnly, yaw_mode=airsim.YawMode(False, 0)).join()
# here the drone shakes

client.reset()
client.armDisarm(False)
client.enableApiControl(False)
```

I also tried to move the drone using the velocities via `MultirotorClient.moveByVelocittyAsync()` but the same behavior occurred.

I also tried different physic engines in settings.json:
```json
{
   "SeeDocsAt": "...",
   "SettingsVersion": 1.2,
   "SimMode": "Multirotor",
   "PhysicsEngineName": "FastPhysicsEngine"    (-->here I also tried to use "ExternalPhysicsEngine" or default "")
}
```

Thanks in advance!

**Comment by MinnDevelopment** [comment]
Maybe you can try limiting the PID gains:

```py
client.setVelocityControllerGains(
  airsim.VelocityControllerGains(z_gains=airsim.PIDGains(0.1, 0, 0))
)
```

**Comment by rebeccasc** [comment]
> Maybe you can try limiting the PID gains:
> 
> ```python
> client.setVelocityControllerGains(
>   airsim.VelocityControllerGains(z_gains=airsim.PIDGains(0.1, 0, 0))
> )
> ```

Thanks for the help! 
Setting the PID gains made it looks a little better. However, I ended up disabling the phsyics engine via settings.json (["PhysicsEngineName":"ExternalPhysicsEngine"](https://microsoft.github.io/AirSim/settings/#physicsenginename)) and using `MultiRotorClient.setVehiclePose()`.
