### ISSUE TITLE
simLoadLevel does not correctly switch between maps

### ISSUE THREAD

**Issue by talha-opteran** [microsoft/AirSim#4432]
## Bug report 

- AirSim Version/#commit: e692a6f81d9b9bc17a0cea59592d0504c6222575
- UE/Unity version: UE 4.27
- autopilot version: N/A
- OS Version: Ubuntu 20.04

### What's the issue you encountered?

I'm looking to get AirSim working with multiple environments in the same binary. I've followed the tutorials to get custom environments into AirSim and am able to run them through the editor. However, I would like to be able to switch between the environments without restarting AirSim.

I came across `simLoadLevel` which looks like it is supposed to do this but fails to do so. It seems like this is oriented towards streaming levels- so increasing the size of an already loaded persistent level rather than load and replace a currently loaded level.

There is an undocumented param in the settings.json file, "Default environment", which is supposed to be able to allow a specific environment to be loaded on AirSim startup but that does nothing either.

I have also tried calling the `simLoadLevel` function from the python client with the environment name. This works but loads the new environment on top of the current environment- like a streaming level.

### How can the issue be reproduced?

1. Have multiple environments in a single project
2. Attempt to use `simLoadLevel` to load a map that is not yet loaded

### Include full error message in text form
No errors.

**What's better than filing an issue? Filing a pull request :).**

**Comment by br0tda** [comment]
Same issue, any idea?

**Comment by talha-opteran** [comment]
Sorry- forgot to update this. 

I managed to make it work by hacking some changes in AirSim source. Then, in settings.json, add the `"Default Environment": "YourMapName"` pair. The map name corresponds to the map file name in Unreal Editor.

`AirSim/Unreal/Environments/Blocks/Plugins/AirSim/Source/SimHUD/SimHUD.cpp:`

```
#include "Kismet/GameplayStatics.h"

...

void ASimHUD::BeginPlay()
{
    Super::BeginPlay();

    try {
        UAirBlueprintLib::OnBeginPlay();
        // Reorder the two below functions to allow default level change to be picked up from settings
        initializeSettings();
        loadLevel();

        setUnrealEngineSettings();
        createSimMode();
        createMainWidget();
        setupInputBindings();
        if (simmode_)
            simmode_->startApiServer();
    }
    catch (std::exception& ex) {
        UAirBlueprintLib::LogMessageString("Error at startup: ", ex.what(), LogDebugLevel::Failure);
        //FGenericPlatformMisc::PlatformInit();
        //FGenericPlatformMisc::MessageBoxExt(EAppMsgType::Ok, TEXT("Error at Startup"), ANSI_TO_TCHAR(ex.what()));
        UAirBlueprintLib::ShowMessage(EAppMsgType::Ok, std::string("Error at startup: ") + ex.what(), "Error");
    }
}

...

void ASimHUD::loadLevel()
{
    if (AirSimSettings::singleton().level_name != "")
    {
        // Fix for loading in different map 
        auto currMap = GetWorld()->GetMapName();
        currMap.RemoveFromStart(GetWorld()->StreamingLevelsPrefix);
        // Load it only once without getting stuck in infinite loop
        if (!currMap.Equals(FString(AirSimSettings::singleton().level_name.c_str())))
            UAirBlueprintLib::RunCommandOnGameThread([&]() { UGameplayStatics::OpenLevel(this->GetWorld(), FName(AirSimSettings::singleton().level_name.c_str())); }, true);
    } else
        UAirBlueprintLib::RunCommandOnGameThread([&]() { UAirBlueprintLib::loadLevel(this->GetWorld(), FString("Blocks")); }, true);
}
```

For changing levels during runtime, the `else` clause of `loadlevel()` will need to be changed in a similar manner- not yet tested though.
