### ISSUE TITLE
Documentation website is not available (https://microsoft.github.io/AirSim/)

### ISSUE THREAD

**Issue by slowbrain-jaym** [microsoft/AirSim#4434]
I cannot access the documentation website on either my home or work computers, I am getting the following error page:
![image](https://user-images.githubusercontent.com/15910590/160133476-0afb4a5c-fee3-47a0-85bb-8a1e34459363.png)

Apologies if this is not the correct place to report this!

**Comment by ryan-sandzimier** [comment]
Having the same issue here.

**Comment by SaundersJE97** [comment]
Same here

**Comment by ryan-sandzimier** [comment]
For those waiting for a fix, here's an archive of the documentation site. Not all links were archived though.

https://web.archive.org/web/20220309094944/https://microsoft.github.io/AirSim/

**Comment by ryan-sandzimier** [comment]
@jonyMarino The documentation website is down again.

**Comment by REGATTE** [comment]
Yup, its down again. When can we expect it to be up and running again??
