### ISSUE TITLE
Using capture capabilities for non-AirSim projects.

### ISSUE THREAD

**Issue by Levinskis** [Microsoft/AirSim#444]
Could you please describe more precisely how can be capture used in other VR environments (without drone agents).  I see BP_PIPcamera could be integrated into my project for that purposes.

**Comment by sytelus** [comment]
Not sure what you mean. If you want to use UE4 related components in to your project, you will need to copy related .h and .cpp files as well as migrate related .uasset files to your project. Please see Unreal documentation on how to migrate assets between projects.
