### ISSUE TITLE
AirSim tutorial error: 'simGetImage' bad cast, WSAECONNREFUSED

### ISSUE THREAD

**Issue by kutilanak** [microsoft/AirSim#4440]
Hello guys, newbie here. 

### What's your question?

I'm trying to follow this tutorial here 
[https://medium.com/@realderektan/go-dr-ve-yourself-a-self-driving-car-using-end-to-end-deep-learning-and-airsim-84e44e544e48](url) 
with his code here [https://github.com/Microsoft/AutonomousDrivingCookbook/tree/7a412165fcff2bc427ea1498bb3c0ec7b1e0f522/AirSimE2EDeepLearning](url)
and his car model here
[https://github.com/realDerekTan/selfdrivingcar](url)

but there's two kind of error that I got when running the model:
1. When I try to run the code with LandscapeMountains I got from [https://github.com/microsoft/AirSim/releases/](url) I got error bad cast
2. When i try to run the code with LandscapeMountains I got from [https://airsimtutorialdataset.blob.core.windows.net/e2edl/AD_Cookbook_AirSim.7z](url) I got error WSAECONNREFUSED

### Include context on what you are trying to achieve

I just want the model to work well with AirSim just like the tutorial. 

#### Context details

I'm using python 3.6.9
AirSim 1.6.0
VS2019
Tensorflow 1.15
UE 2.4

bad cast error:
> Connection established!
> Traceback (most recent call last):
>   File "g:/Clone Airsim/PythonClient/car/testmodel.py", line 46, in <module>
>     image_buf[0] = get_image()
>   File "g:/Clone Airsim/PythonClient/car/testmodel.py", line 31, in get_image
>     image_response = client.simGetImages([client.simGetImage(0, 0, False, False)])[0]
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\airsim\client.py", line 244, in simGetImage
>     result = self.client.call('simGetImage', camera_name, image_type, vehicle_name, external)
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\msgpackrpc\session.py", line 41, in call
>     return self.send_request(method, args).get()
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\msgpackrpc\future.py", line 45, in get
>     raise error.RPCError(self._error)
> msgpackrpc.error.RPCError: rpclib: function 'simGetImage' (called with 4 arg(s)) threw an exception. The exception contained this information: bad cast.

WSAECONNREFUSED error:

> WARNING:tornado.general:Connect error on fd 388: WSAECONNREFUSED
> WARNING:tornado.general:Connect error on fd 388: WSAECONNREFUSED
> Traceback (most recent call last):
>   File "g:/Clone Airsim/PythonClient/car/testmodel.py", line 17, in <module>
>     client.confirmConnection()
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\airsim\client.py", line 139, in confirmConnection
>     if self.ping():
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\airsim\client.py", line 35, in ping
>     return self.client.call('ping')
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\msgpackrpc\session.py", line 41, in call
>     return self.send_request(method, args).get()
>   File "C:\Users\ekipu\anaconda3\envs\py369\lib\site-packages\msgpackrpc\future.py", line 43, in get
>     raise self._error
> msgpackrpc.error.TransportError: Retry connection over the limit

### Include details of what you already did to find answers
N/A

Thank you!

**Comment by jonyMarino** [comment]
@kutilanak regarding the bad cast, seeing your stack trace, I think you are sending a False as vehicle name.
Regarding the connection refuse, maybe your firewall is preventing it to connect?

**Comment by kutilanak** [comment]
> @kutilanak regarding the bad cast, seeing your stack trace, I think you are sending a False as vehicle name. Regarding the connection refuse, maybe your firewall is preventing it to connect?

How can I solve the False?
Regarding the firewall, I've click the "Allow access" when the notice pop up and tried turning off the firewall but the problems persist. Is it because its the older version of airsim?

thank you for your response.

**Comment by rajat2004** [comment]
The API call you're doing is - `client.simGetImages([client.simGetImage(0, 0, False, False)])`
You cannot combine both `simGetImage` and `simGetImages`, use either of the two. 
Such as `client.simGetImage("camera_name", ImageType)`, or `client.simGetImages([airsim.ImageRequest("camera_name", airsim.ImageType.Scene, False, False)], "vehicle_name")`
There's the [API ref docs](https://microsoft.github.io/AirSim/api_docs/html/#airsim.client.VehicleClient.simGetImage), and various examples in the scripts, please refer to them.

**Comment by kutilanak** [comment]
> The API call you're doing is - `client.simGetImages([client.simGetImage(0, 0, False, False)])` You cannot combine both `simGetImage` and `simGetImages`, use either of the two. Such as `client.simGetImage("camera_name", ImageType)`, or `client.simGetImages([airsim.ImageRequest("camera_name", airsim.ImageType.Scene, False, False)], "vehicle_name")` There's the [API ref docs](https://microsoft.github.io/AirSim/api_docs/html/#airsim.client.VehicleClient.simGetImage), and various examples in the scripts, please refer to them.

It works for me! thank you so much! I'm closing this
