### ISSUE TITLE
Unexpected 'f' Expected '}' Error In Settings When Running AirSim 

### ISSUE THREAD

**Issue by exploke** [Microsoft/AirSim#445]
When I run the latest commit of AirSim, I get an unexpected 'f' expected '}' error in the settings.json file.

![ff error](https://user-images.githubusercontent.com/25913167/29934674-a75cca1e-8e41-11e7-80f7-0c73fd05844c.PNG)

The error in the settings file seems to be with RecordInterval portion.

![settings f](https://user-images.githubusercontent.com/25913167/29934737-e2d77ac6-8e41-11e7-9751-1452e4bd6edc.PNG)

Any help to fix this problem as soon as possible would be appreciated.

**Comment by Robin-Wong** [comment]
Please try to delete the 'f' after all the float value,
like change ""AutoExposureMaxBrightness": 0.64f" to ""AutoExposureMaxBrightness": 0.64".
By the way, add ',' in line 20("ImageType":1,), 35, 43.

**Comment by Robin-Wong** [comment]
Please try to delete the 'f' after all the float value,
like change ""AutoExposureMaxBrightness": 0.64f" to ""AutoExposureMaxBrightness": 0.64".
By the way, add ',' in line 20("ImageType":1,), 35, 43.

**Comment by sytelus** [comment]
Also, if setting is just default value, I would highly recommand not adding it in setting.json. This way if default changes in later releases, you get it without issues.

**Comment by Curry30h** [comment]
I also encountered the same problem. Is there a solution?
