### ISSUE TITLE
Python Path Example Missing Take-off Command

### ISSUE THREAD

**Issue by abe-mart** [Microsoft/AirSim#448]
The example code for path following in Python is missing a take off command.  This leads to the drone bouncing along the ground when it is started, and made me think that my setup was incorrect for a while.

**Comment by sytelus** [comment]
Thanks for pointing this out. This is now [fixed](https://github.com/Microsoft/AirSim/commit/af3635859b6b0c350019d9f653981d4fffd6dcff).
