### ISSUE TITLE
Unity crashes when I hit play for any demo

### ISSUE THREAD

**Issue by Lyccccccccccc** [microsoft/AirSim#4493]
## Bug report 

- AirSim Version/#commit: Latest one. I just clone the latest repo.
- UE/Unity version: I tried both 2019.3.12 and 2020.3.29
- autopilot version: N/A
- OS Version: Windows 10

### What's the issue you encountered?

I followed the instruction to build Airsim on Unity on Windows and I opened the demo project and hit play to start. Unity just crashed with whatever mode. Once I deleted AirsimManager, it worked as normal. If include AirsimManager in any of the scene, Unity will crash when play. In this case, we are not able to start the server for the API client to connect.
![image](https://user-images.githubusercontent.com/90293564/164505408-ef710b27-f3cf-4df0-8d97-4b7d8f2bbb70.png)
![image](https://user-images.githubusercontent.com/90293564/164505545-cde13512-7654-4949-b8fe-49895e625aa5.png)

### Settings

Default setting. Edited: I realized that I was not using the default setting file. In the setting file, I set the mode to be computer vision.

### How can the issue be reproduced?

1. Follow the instruction to build Airsim on Unity on Windows in this link: https://github.com/microsoft/AirSim/blob/master/docs/Unity.md
2. Start the demo project and hit play

### Include full error message in text form
No error message, just crashed.

**What's better than filing an issue? Filing a pull request :).**

**Comment by Lyccccccccccc** [comment]
When I removed the two scripts under AirsimManager, the scene worked fine. I guess the issue is about the server and tick scripts.

**Comment by Lyccccccccccc** [comment]
But I can't see what's going on inside the wrapper. Can't dig further about this issue.

**Comment by X-DDDDD** [comment]
same question😿

**Comment by Lyccccccccccc** [comment]
@zimmy87 I produced the crash again in Unity 2019.3.12. Now I have two log files. The computer vision mode seems not compatible with AirsimManager.

[error.log](https://github.com/microsoft/AirSim/files/8574700/error.log)
[Editor.log](https://github.com/microsoft/AirSim/files/8574701/Editor.log)
