### ISSUE TITLE
Could not find a version that satisfies the requirement airsim

### ISSUE THREAD

**Issue by HonsenZhang** [microsoft/AirSim#4498]
## Bug report 

- AirSim Version/#commit: 1.7.0
- UE/Unity version: N/A
- autopilot version: N/A
- OS Version: ubuntu 20.04

### What's the issue you encountered?

i want to use the version 1.7.0, but when i excute the command `pip install airsim==1.7.0`, there is an error says:
`ERROR: Could not find a version that satisfies the requirement airsim==1.7.0 (from versions: 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 1.5.0, 1.6.0)
ERROR: No matching distribution found for airsim==1.7.0`

### Settings

N/A

### How can the issue be reproduced?

1. pip install airsim==1.7.0

### Include full error message in text form
`ERROR: Could not find a version that satisfies the requirement airsim==1.7.0 (from versions: 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.3.0, 1.5.0, 1.6.0)
ERROR: No matching distribution found for airsim==1.7.0`

**What's better than filing an issue? Filing a pull request :).**
N/A

**Comment by jonyMarino** [comment]
Hi @HonsenZhang, and welcome! The package was recently updated. You can now download it through pip.
