### ISSUE TITLE
Weird little bug in camera director: manual camera control

### ISSUE THREAD

**Issue by saihv** [microsoft/AirSim#451]
When using the manual camera setting feature (by pressing M): there is a strange bug occurring that affects the subwindow layout in the HUD. As soon as M is pressed to enter this mode, the SubWindow0 container is flipped and pushed to the left. This happens even if that container is moved anywhere within the HUD. Doesn't affect any of the other containers/images. (Picture below: top is any of the other modes, bottom is manual camera mode). The layout corrects itself only when this mode is exited.

![1](https://user-images.githubusercontent.com/2274262/29993354-47e69aa8-8f7a-11e7-9d66-a1c72dae056f.PNG)

This seems to be a side effect when the code executes the `enableBindings()` function within ManualPoseController.cpp. If I, say, comment out all those lines in the function, this bug disappears, and manual camera control still works fine.

**Comment by sytelus** [comment]
I can reproduce this as well. I'm still not sure what is the connection with enableBindings(). I guess we need to figure out workaround...

**Comment by rajat2004** [comment]
This doesn't seem to happen any longer, can be closed I think?

**Comment by saihv** [comment]
Fixed in later releases, closing.
