### ISSUE TITLE
How to get depth values in realtime?

### ISSUE THREAD

**Issue by godhj93** [microsoft/AirSim#4525]
### What's your question?

I want to get depth images in realtime. I have tried to solve it but failed. I tried following methods:
- Following [this solution](https://github.com/microsoft/AirSim/issues/2835#issuecomment-658112000):querying floating depth data and converting it. It works well but TOO SLOW(0.4sec/image on RTX2070SUER, Intel I9-10900K, 128GB RAM)
- I found if I query uint8 data, I can run it in realtime(40FPS~)
```
responses = client.simGetImages([ImageRequest(0, AirSimImageType.Segmentation, False, False)])
img1d = np.fromstring(response.image_data_uint8, dtype=np.uint8) #get numpy array
```
But the problem is that It autimatically normalize the depth value from 0~100m*, Its value is almost 0 or 255 because It sees sky(depth is infinity) so it becomes useless value.

- With "NoDisplay" options in settings.json, but it doesn't help to improve the latency.(little improved)
- Lowering Camera resolution to 64*64 but it doesn't help it.(little improved)

So my question is that Is there any method to change maximum value for normalization like 100m*.
I'm happy to get any solution to get depth value in realtime. 

### Include context on what you are trying to achieve

I want to get depth images in realtime.
#### Context details

OS: Ubuntu20.04
Python: 3.9
Unreal: 4.25.4
```
{
    "SeeDocsAt": "https://microsoft.github.io/AirSim/settings/",
    "SettingsVersion": 1.2,
    "ClockSpeed": 3,
    "SimMode": "Multirotor",

  "CameraDefaults": {
    "CaptureSettings": [
      {

	"ImageType": 2,
	"Width": 256,
	"Height": 256,
	"FOV_Degrees": 90
      }

    ]},
     "SubWindows": [
    {"WindowID": 0, "CameraName": "0", "ImageType": 3, "VehicleName": "", "Visible": false, "External": false},
    {"WindowID": 1, "CameraName": "0", "ImageType": 5, "VehicleName": "", "Visible": false, "External": false},
    {"WindowID": 2, "CameraName": "0", "ImageType": 0, "VehicleName": "", "Visible": false, "External": false}
  ]

}
```
### Include details of what you already did to find answers
I described it above.

**Comment by rudeIMB** [comment]
Did you find the answer to this problem please? Im going through the same problem

**Comment by godhj93** [comment]
Hi, I have found the solution for this. 

You have to modify the airsim client source code (at /home/user_name/anaconda3/envs/your_environment/lib/python3.10/site-packages/airsim/client.py) as follows:

```
class VehicleClient:
    def __init__(self, ip = "", port = 41451, timeout_value = 3600):
        if (ip == ""):
            ip = "127.0.0.1"
        # self.client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout = timeout_value, pack_encoding = 'utf-8', unpack_encoding = 'utf-8')
        self.client = msgpackrpc.Client(msgpackrpc.Address(ip, port), timeout = timeout_value)
```
