### ISSUE TITLE
I can't see the API to get the drone's state, such as power state, i think this is important. And i wonder is there a way to get it among client api, or will it be realize in the future?

### ISSUE THREAD

**Issue by AdaJass** [Microsoft/AirSim#454]

**Comment by AdaJass** [comment]
as `DroneShell/src/main.cpp`   and `controllers/DroneControllerBase.hpp` show, there isn't such api yet.

**Comment by sytelus** [comment]
Battery simulation is not yet there and there is also no power API. We do plan to add this in future but it isn't a high priority item for us now. Please feel free to contribute this future if you like.
