### ISSUE TITLE
UE5 - AirSim prevents low-level details crowd and traffic from being drawn

### ISSUE THREAD

**Issue by czero69** [microsoft/AirSim#4555]
### About

With few tweaks, I have added AirSim plugin to UE5 cityscape demo. What I want is to use computer vision mode to save buffers. For some reason, when using AirSimGameMode, it disables drawing for low-level mass ai objects. These objects are still tracked and existing (green squares), just drawing is disabled.

I want to make low-level mass ai objects to be drawn. Do you have some ideas what can be the cause and what should I check in the first place?

### How Has This Been Tested?

Debugging with `MassTraffic.DebugVisualization 1` I concluded that higher level details mass ai objects are drawn as desired (all orange/red squares), but lower level-detail mass ai objects are not drawn at all (green squares).

Compiling AirSim to UE5 was quite straightforward. I just disabled not compatible code in car pawns (I only need computer vision mode). Please let me know, and I will paste the link to my fork here if someone wants to recreate the issue. Also, my settings.json is pretty standard.

### Screenshots (if appropriate):

<img width="953" alt="283280191_740510930317413_877530782886617357_n" src="https://user-images.githubusercontent.com/5120235/171384193-f5878d68-8cf7-4053-967c-74bd1e5a67b7.png">

<img width="949" alt="284644732_451466696785681_4431416551191738305_n" src="https://user-images.githubusercontent.com/5120235/171384248-6e3af0ca-3da9-4c96-bf20-91c1e873f279.png">

**Comment by czero69** [comment]
Ok Solved! 

The issue is related to origin position and/or calling GetWorld()->SetNewWorldOrigin(...) in AirSim. As a fast workaround, commenting SetNewWorldOrigin and setting spawning location same as City Sample Demo (not 0,0,0) solves the issue.

<img width="1111" alt="SOLVED" src="https://user-images.githubusercontent.com/5120235/171500174-88864df0-d489-48a1-94e5-9249a9870577.png">

**Comment by leielyq** [comment]
Compiling AirSim to UE5 was quite straightforward. 

Share it, thank you

**Comment by czero69** [comment]
here you are:

https://github.com/czero69/AirSim/tree/ue5-cv

Let me know if you are interested in City Sample Demo + Airsim. I plan to push additional fixes for that demo later.
