### ISSUE TITLE
Camera Gimbal / Separate Camera and Drone Poses

### ISSUE THREAD

**Issue by abe-mart** [Microsoft/AirSim#456]
I'd like to try using AirSim to simulate UAV mapping/photogrammetry flights.  Is there a way to control the camera pose separately from the vehicle pose?

**Comment by sytelus** [comment]
Currently no but soon we are planning to revamp APIs and this would be a good feature to add. Its actually fairly easy to add as well so please feel free to contribute :).

**Comment by sytelus** [comment]
I just added Gimbal APIs in AirSim. [Here's doc](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#camera-orientation-gimble).

**Comment by abe-mart** [comment]
This is excellent.  However, when I try to use the new command in Python with the latest version of Airsim and the Landscape Mountains binary, I get the following error:

`RPCError: rpclib: server could not find function 'setCameraOrientation' with argument count 2.`

This was with the command copied and pasted from the docs:

`client.setCameraOrientation(0, AirSimClientBase.toQuaternion(0.261799, 0, 0)); #radians`

**Comment by guillem74** [comment]
I get the same error:

RPCError: rpclib: server could not find function 'setCameraOrientation' with argument count 2.

**Comment by sytelus** [comment]
You will need to use latest binaries from release 1.1.10.

**Comment by abe-mart** [comment]
Thanks, works great with the latest binaries.
