### ISSUE TITLE
Can the environments (Africa, LandscapeMountains, etc.) be run windowed (vs. fullscreen)?

### ISSUE THREAD

**Issue by tscizzlebg** [microsoft/AirSim#4582]
### What's your question?
In this repo's releases, there are these custom drone environments offered (Africa, LandscapeMountains, etc.), and we can run the simulation by running the supplied executable (Africa.exe, LandscapeMountains.exe, etc.) However, these simulations run fullscreen and seem to be inflexible on that. Is there a way to make them not run fullscreen, but rather in a movable, resizable, window.

### Include context on what you are trying to achieve
I would like to be able to interact easily with other programs while the drone environment is running (scripts that make API calls to the drone game, display logs, etc.)

#### Context details

Windows 10, Airsim 1.7.0, Python 3.7, Unreal

No settings changes.

### Include details of what you already did to find answers
I have searched this repo and the official documentation for info on fullscreen stuff. I have seen some things talk about running `Airsim.exe -WINDOWED` and other things with settings, but these solutions all appear to be about `Airsim.exe` and not Africa.exe or LandscapeMountains.exe or something, and those solutions have not worked for the executables I'm using.

**Comment by jonyMarino** [comment]
Hi and welcome @tscizzlebg! If you don't need a script, you can use alt+enter on your keyboard.

**Comment by tscizzlebg** [comment]
I don't need a script, so this is fantastic! Appreciate the quick response :D

That said, a script (or option to start the game like this), i.e. not needing the alt-enter shortcut, would definitely be more convenient. But for now, this is awesome.

**Comment by tscizzlebg** [comment]
Ah, makes sense. Thank you very much!
