### ISSUE TITLE
How to get the ground truth depth

### ISSUE THREAD

**Issue by jingleFun** [Microsoft/AirSim#459]
As you said here [https://github.com/Microsoft/AirSim/issues/376](https://github.com/Microsoft/AirSim/issues/376)
 "The value of each pixel is a depth value from 0 to 2^24-1. However as this range is too large, the depth map would end up looking like all white. So we clip the depth at 10,000 cm and then normalize it from 0.0 to 1.0 by dividing it by 10000". Where is the code for clip the depth and dividing it by 10000 ? I have some confusion about the depth ,and hope to see the code to check it, thank you!

**Comment by sytelus** [comment]
This was indeed confusing and so now we have cleaned it up. In latest version, there are two ways to get depth: ImageType = DepthVis and DepthMeters. For DepthMeters, you should request floating point image. For meaning of these image type [please see docs](https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#what-does-pixel-values-mean-in-different-image-types).
