### ISSUE TITLE
How to get continuous sensor readings from the multirotor?

### ISSUE THREAD

**Issue by Mengyuliu0520** [microsoft/AirSim#4618]
### Overview: Can we monitor the model and get a stream of sensor readings through api?
 Maybe it is good to have an api that output sensor readings continuously, since the users do not have to care about the sychronization problems.

### Nature of Request:  

- Addition
- Change
- Removal
  -

**Comment by alonfaraj** [comment]
Maybe it's worth using ros for that purpose?

**Comment by Mengyuliu0520** [comment]
> Maybe it's worth using ros for that purpose? I think rpclib doesn't support pub-sub which is probably the way to implement such feature for python api.

Thanks for the advice! What I'm considering is a MPC-based real-time control using AirSim, to achieve this, first I need to have real-time vehicle states and I also need to access low-level control in real time, I found there are some old issues discussed about the low-level control and I will give it a try.
