### ISSUE TITLE
can't detect the collision information

### ISSUE THREAD

**Issue by Eugene21219** [microsoft/AirSim#4649]
### What's your question?

i'm trying to use the collision info api to get the collision infomation about the multirotor in the UE4. but when the multirotor collided with the floor, the method "has_collided" still returns false.  

#### Context details

   AirSim version: 1.7.0
   python verison: 3.7.0
   Unreal version: 4.26
![image](https://user-images.githubusercontent.com/48636196/182079299-aa83488d-4519-4656-bfe7-8aeb544ee675.png)
![image](https://user-images.githubusercontent.com/48636196/182079430-dc83d20f-0d99-470b-b681-780a6ef70e61.png)

**Comment by ZhangShaungnj** [comment]
hey bro！Have u resolved the problem?
