### ISSUE TITLE
Dronekit Integration

### ISSUE THREAD

**Issue by ZixingLin** [Microsoft/AirSim#465]
Has anyone tried running Dronekit scripts in AirSim? I'm currently facing an issue where DroneKit is unable to detect the GPS of the simulation therefore I do not think I can run offboard commands. Does AirSim send GPS information over to the PX4 firmware?

I am also running PX4 Firmware 1.6.3 via HITL.

Any support is welcomed!

**Comment by sytelus** [comment]
Yes, it sends GPS sensor data to PX4. However 1.6.3 had known issue and that prevented it working in HITL. Please see #3 in [this doc](https://github.com/Microsoft/AirSim/blob/master/docs/px4_setup.md#setting-up-px4-hardware-in-loop). Link to related PX4 issue: https://github.com/PX4/Firmware/issues/7516.
