### ISSUE TITLE
Known good build environment?

### ISSUE THREAD

**Issue by n1ckfg** [Microsoft/AirSim#466]
Having trouble compiling the Unreal plugin everywhere--in Ubuntu 16.04 and Win10, VS 2017 and VS 2015, Unreal 4.16 and 4.17. What's a best-practice build environment (OS, Unreal version, VS version, etc.) to test against so I can figure out what's going wrong?

**Comment by saihv** [comment]
Works great for me on Windows 10, Unreal 4.16.3 and Visual Studio 2015 Community Update 3.

**Comment by sytelus** [comment]
I'm able to compile from scratch on Win 10 as well as Ubuntu 16.04 LTS. What is the issue you are facing? Please post complete error messages and/or log files.

**Comment by n1ckfg** [comment]
Starting with @saihv's recommended environment, build fails with:
```
1>C:\Users\nick\Documents\GitHub\AirSim\Unreal\Environments\Blocks\Plugins\AirSim\Source\PIPCamera.h(6): fatal error C1083: Cannot open include file: 'controllers/VehicleCameraBase.hpp': No such file or directory
1>C:\Users\nick\Documents\GitHub\AirSim\Unreal\Environments\Blocks\Plugins\AirSim\Source\AirBlueprintLib.cpp(11): fatal error C1083: Cannot open include file: 'common/common_utils/Utils.hpp': No such file or directory
1>  Blocks.cpp
1>  [9/12] Link UE4Editor-Blocks.lib
1>     Creating library C:\Users\nick\Documents\GitHub\AirSim\Unreal\Environments\Blocks\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-Blocks.lib and object C:\Users\nick\Documents\GitHub\AirSim\Unreal\Environments\Blocks\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-Blocks.exp
1>ERROR : UBT error : Failed to produce item: C:\Users\nick\Documents\GitHub\AirSim\Unreal\Environments\Blocks\Plugins\AirSim\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor-AirSim.lib
```

**Comment by n1ckfg** [comment]
Also fails with a very similar error in Ubuntu 16.04 with both UE 4.16 and UE 4.17:
ERROR: UBT ERROR: Failed to produce item: ~/Projects/Wise/AirSim/Unreal/Environments/Blocks 4.16/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so

ERROR: UBT ERROR: Failed to produce item: ~/Projects/Wise/AirSim/Unreal/Environments/Blocks 4.17/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so

I must be making the same mistake in all four scenarios (Win10/VS 2015/UE 4.16, Win10/VS 2017, UE 4.17, Ubuntu 16.04/UE 4.16, Ubuntu 16.04/UE 4.17)

**Comment by sytelus** [comment]
Are you following this instructions? https://github.com/Microsoft/AirSim/blob/master/docs/unreal_blocks.md

Specifically step #2, which will copy Plugins/AirSim folder in Blocks project. Above errors seems to indicate you don't have this folder.

**Comment by n1ckfg** [comment]
Turns out I can't complete the pre-build step for rpclib--CMake complains:  
```
No CMAKE_C_COMPILER could be found.
No CMAKE_CXX_COMPILER could be found.
```
Experimented with various configurations for VS 2015, VS 2017, and standalone CMake install as per docs...any suggestions?

**Comment by n1ckfg** [comment]
OK, found the issue: when both VS 2015 and VS 2017 are installed, build.cmd must be run with VS 2017. The Unreal project can still optionally be built with VS 2015. I see the VS 2017 flag for cmake is already provided in build.cmd and commented out; would be great to add an explainer note in the docs. Thanks for the suggestions!

**Comment by spencerh-b** [comment]
So the fix was uncommenting?

**Comment by n1ckfg** [comment]
Yeah afaik if you have both VS 2017 and VS 2015 installed, you _must_ run build.cmd for VS 2017 (by uncommenting the VS 2017 CMake command string and commenting out the VS 2015 one). After you've built the plugin, you can still build your Unreal project with either VS 2015 or VS 2017.

**Comment by n1ckfg** [comment]
I'm still stuck on compiling on Ubuntu for both 4.16 and 4.17.

**Comment by spencerh-b** [comment]
@n1ckfg Sweet I will try this

**Comment by olivia-skydio** [comment]
@n1ckfg Were you ever able to compile on Ubuntu 16.04? Stuck on this same issue now.

**Comment by n1ckfg** [comment]
Yup, for Unreal 4.17. Where does it break for you?

**Comment by olivia-skydio** [comment]
When I run Unreal Engine and try and pick a project it says that Airsim isn't compatible 
![screenshot from 2018-01-24 14-32-28](https://user-images.githubusercontent.com/35615444/35363952-922ea696-0121-11e8-8ae3-a6ef566f5c40.png)

I click No to disabling it and then it says: 
![screenshot from 2018-01-24 14-32-44](https://user-images.githubusercontent.com/35615444/35363972-ad321216-0121-11e8-9579-9d88c5947fc4.png)

Then if I try to rebuild I get 
![image](https://user-images.githubusercontent.com/35615444/35364005-c9ee17a6-0121-11e8-8c97-d74251aa830d.png)

**Comment by n1ckfg** [comment]
So afaik you can't build the AirSim plugin in a new project from UE--you have build it in the AirSim repo first and then copy from the AirSim/Unreal folder to your own project.  Next delete Binaries, Intermediate, and Saved folders from your project (this will all be recreated). Then run GenerateProjectFiles.sh in the UE folder on your new.uproject file. Finally try opening the project in Unreal again and see if it builds.

**Comment by olivia-skydio** [comment]
How do you build  in the AIrSim repo? Is that just running ./build.sh ? Should that create a .so file?

**Comment by n1ckfg** [comment]
First run setup, then build.
