### ISSUE TITLE
Cannot run Blocks.sln with VS2022

### ISSUE THREAD

**Issue by Chen-Haoyan** [microsoft/AirSim#4676]
### Discussed in https://github.com/microsoft/AirSim/discussions/4671

<div type='discussions-op-text'>

<sup>Originally posted by **Chen-Haoyan** August 25, 2022</sup>
AirSim Version/#commit: v1.8.1 - Windows
UE/Unity version: 5.0.3
OS Version: win10

3 error：
error C2672: “common_utils::Utils::isDefinitelyLessThan”: 未找到匹配的重载函数 （No matching overloaded function found）
error C2027: 使用了未定义类型“physx::PxVehicleWheels” （Type not defined）
error C2027: 使用了未定义类型“physx::PxVehicleDrive” （Type not defined）</div>

**Comment by BayMaxBHL** [comment]
我也遇到了同样的问题，您是否有解决办法？

**Comment by Liu616012360** [comment]
哥们解决了么？出个教程吧谢谢
