### ISSUE TITLE
IL mismatch between 'tool1' version 'number1' and 'tool2' version 'number2' when compiling Blocks.sln

### ISSUE THREAD

**Issue by Chen-Haoyan** [microsoft/AirSim#4677]
### What's your question?
IL mismatch between 'tool1' version 'number1' and 'tool2' version 'number2'
![image](https://user-images.githubusercontent.com/62796411/187064419-1c3b9613-d4dd-4c36-8a19-7c14ab91b10e.png)
![image](https://user-images.githubusercontent.com/62796411/187064424-30895446-a063-4743-9e69-e57106866e4b.png)

#### Context details

win10
vs2022
UE4.27.2
AirSim1.8.1-windows

**Comment by Zartris** [comment]
Chen, how did you fix it! 
I cannot seem to find a solution for this
