### ISSUE TITLE
How to run simple_flight in ubuntu16.04+QT?

### ISSUE THREAD

**Issue by fenfeibani** [Microsoft/AirSim#470]
How to run simple_flight in ubuntu16.04+QT?

**Comment by sytelus** [comment]
simple_flight is default and you don't need to do anything extra. Just [follow instructions](https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md). You don't need QT but it is possible to use it as code editor for Unreal project ([some instructions here](https://docs.unrealengine.com/latest/INT/Platforms/Linux/BeginnerLinuxDeveloper/SettingUpAnIDE/index.html) - but I have never got it working). For using QT with Unreal projects, please post your questions in [their forums](https://answers.unrealengine.com).
