### ISSUE TITLE
Step-by-Step HelloDrone

### ISSUE THREAD

**Issue by spencerh-b** [Microsoft/AirSim#472]
Is anyone able to help me just get the hellodrone working, trying to figure out this whole API thing, but I need somewhere to start. I'm always confused about using the DroneServer and DroneShell. Just a quick list of what I need to do would be super helpful. Thank you in advance to anyone who can help me out.

**Comment by sytelus** [comment]
I'm wondering why you are confused? Is there any docs you read?

DroneServer is not required. It's only useful if you want to deploy your code on real vehicle.

DroneShell is not required for API access. It's just client shell-like program that uses APIs.

To use HelloDrone, just download binaries or build. Run the Blocks environment (press Play in UE editor if you are building yourself). Then start another instance of Visual Studio, set PythonClient project as startup project, set hello_drone.py as start script. Hit Run.

**Comment by spencerh-b** [comment]
What would this process look like in linux?
