### ISSUE TITLE
Can't use RC control in latest version

### ISSUE THREAD

**Issue by jimchenhub** [Microsoft/AirSim#473]
I used to use old version Airsim (version about one month ago) in HITL way. When I change to the latest version which use `SimpleFlight` as default, I can't use RC to control the drone any more.

I use the default setting on [https://github.com/Microsoft/AirSim/blob/master/docs/settings.md](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md) and change ImageType to be 0, Here is the log messages at start, it shows that `RC controller on USB not detected`.

![log_message](https://user-images.githubusercontent.com/7524808/30584818-8ce15f1c-9d5d-11e7-9f40-d52e20d1d6dd.PNG)

Should I change some other setting to use RC?

**Comment by sytelus** [comment]
simple_flight is software in loop so it requires RC with USB connectivity. See [this doc](https://github.com/Microsoft/AirSim/blob/master/docs/remote_control.md). For hardware in loop, you will need to use Pixhawk and connect RC directly to it.

**Comment by jimchenhub** [comment]
I changed the 'DefaultVehicleConfig' to 'PX4', then everything is ok.
Thanks a lot.
