### ISSUE TITLE
DepthVis cannot display all 360° (bug)

### ISSUE THREAD

**Issue by Kjell-K** [Microsoft/AirSim#478]
I am using DepthVis for navigation and found a bug.
```
result = client.simGetImage(0, AirSimImageType.DepthVis)
rawImage = np.fromstring(result, np.uint8)
png = cv2.imdecode(rawImage, cv2.IMREAD_UNCHANGED)
gray = cv2.cvtColor(png, cv2.COLOR_BGR2GRAY)
```
While the initial view to the front works fine . . 

![unbenannt](https://user-images.githubusercontent.com/29546195/30698044-193ad7ac-9ee1-11e7-935e-cc492e27047c.PNG)

. . . when I yaw into a direction beyond the initial 180° view . . 

![edge](https://user-images.githubusercontent.com/29546195/30698103-3a6f392c-9ee1-11e7-8171-175e51c68ba1.PNG)

. . . the DepthVis runs into some kind of edge. Past here the values are not distinguishable.

Therefore the navigation with grey scale distance indicators becomes impossible.

![back_view](https://user-images.githubusercontent.com/29546195/30698174-6e22ae5c-9ee1-11e7-81f1-0fe73acc436e.PNG)

**Comment by sytelus** [comment]
Fixed. See https://github.com/Microsoft/AirSim/issues/500
