### ISSUE TITLE
api call was not received entering hover mode for safety

### ISSUE THREAD

**Issue by Shivam-Kataria** [microsoft/AirSim#4781]
### What's your question?
When ran, the drone hovers in spot and the screen reads "API call was not received, entering hover mode for safety"

### Include context on what you are trying to achieve
Hi, I am new to airsim and continuing a project of someone who I am no longer in contact with. When I run the simulation, I can control the drone with an RC, however, not with code. When ran, the screen reads:
https://imgur.com/a/EtbgtFA

I have found one report about this already where a bunch of other people had the same problem  #2992 , but that thread was closed.

I would greatly appreciate any help!

#### Context details
Windows 10, python 3.8,8, airsim 1.6.0, UE 4.26.2

**Comment by danyayoe** [comment]
![image](https://github.com/microsoft/AirSim/assets/14877644/90a6b6a9-4d0a-4084-885d-98391f80bdde)
https://microsoft.github.io/AirSim/simple_flight/
