### ISSUE TITLE
LiDAR Camera mis-projection 

### ISSUE THREAD

**Issue by pravinjaisawal** [microsoft/AirSim#4792]
### What's your question?

For my work, I record multiple camera images and LiDAR data at 10 frames per second. For this purpose, I move the drone at a speed of 5 m/s and have set the clock rate to 0.05.  The whole recording process works without any problems. After recording, I use the camera position and LiDAR position from the settings to calculate the transformation matrix. Based on the settings, the transformation matrix is:

T = [0.0 1.0 0.0 0.0
      0.0 0.0 1.0 -0.4 
      1.0 0.0 0.0 -0.2 
      0.0 0.0 0.0 1.0]
When I use this transformation matrix to project LiDAR point clouds onto camera images, sometimes it works fine, but sometimes it results in misprojections. 
- Example: correctly projected
![correctly projected](https://user-images.githubusercontent.com/76055862/219063577-e9ed4e52-b7cb-4c6b-82f5-905632e15b16.png)

- Example Incorrectly projected
![Incorrect projection example1](https://user-images.githubusercontent.com/76055862/219059849-3b9bff0b-0eae-4cbf-8f2a-1eacc72c82b2.png)

Questions:
 - Does the relative camera - LiDAR poses change during recording? If yes, how to fix their relative poses?
 - Do you have other suggestions to resolve this issue?
#### Context details

- AirSim Version/#commit:1.7
- UE/Unity version:4.27
- autopilot version:
- OS Version: Ubuntu 20
- [airsim_settings](https://gist.github.com/pravinjaisawal/849d244c955b3d0dbebf06b9bc2b51af)

**Comment by sandilyasg** [comment]
@pravinjaisawal I see the issue is closed, can you please share how you fixed it?

**Comment by pravinjaisawal** [comment]
@sandilyasg I recorded the camera and LiDAR pose for every frame, then calculate the transformation matrix. This matrix maps the LiDAR point cloud properly into camera image
