### ISSUE TITLE
Rpc control

### ISSUE THREAD

**Issue by jamuus** [Microsoft/AirSim#48]
I can't seem to get RPC control of the quad. I'm using the SITL method and have gotten manual control working using QGC. The problem I seem to be having is getting the controller into offboard mode; I'm not sure how AirLib handles putting the quad into this mode.

DroneShell times out when performing requestcontrol and when attempting to change in QGC I get "command temporarily rejected".

Anyone have any pointers for debugging this?

**Comment by sytelus** [comment]
I'd seen this error before but can't recall the context yet. Can you confirm if your basic setup works. That is,

1. You have Unreal project working with SITL.
2. You are able to arm and takeoff using QGC.
3. You shutdown QGC, start DroneShell, type Arm and then TakeOff.

See video walkthrough starting here: https://youtu.be/HNWdYrtw3f0?t=506

**Comment by lovettchris** [comment]
And for moveTo* methods you need to use "requestControl" on the DroneShell command line.  Is that the part that is failing?

**Comment by jamuus** [comment]
I've followed the steps above but requestControl is still hanging/timing out. I've managed to get control using dronekit's example px4 script but this seems to put the controller in AUTO mode rather than OFFBOARD.

**Comment by Timebutt** [comment]
Hi @jamuus, are you getting the same behaviour as me? See issue #85. I have the feeling we are experiencing the same problem.

**Comment by jamuus** [comment]
Yeah I expect I am. I haven't managed to get OFFBOARD mode working using SITL.
