### ISSUE TITLE
LandedState Bug on Python 

### ISSUE THREAD

**Issue by RodgerLuo** [Microsoft/AirSim#481]
On PythonClient.py, class LandedState shows that 0 indicates Landed and 1 indicates Flying. 

![image](https://user-images.githubusercontent.com/10570608/30763413-ea27dc48-9f9a-11e7-8e52-60856c5972ef.png)

However, I asked the drone to send a landed state immediately after the takeoff behavior is accomplished, and it returned 0, whereas to my understanding it should return 1.

![image](https://user-images.githubusercontent.com/10570608/30763449-0f3ef20a-9f9b-11e7-9f89-8137e28c73ff.png)
 
![image](https://user-images.githubusercontent.com/10570608/30763557-9d565fba-9f9b-11e7-9a50-e586fb90c1bb.png)

Please let me know if it's a bug or I did something wrong.

**Comment by sytelus** [comment]
@lovettchris might be interested in this.

**Comment by lovettchris** [comment]
I'm seeing the correct behavior here now that this [pull request ](https://github.com/Microsoft/AirSim/pull/670) is merged.  The problem was that the drone thought it was in the air when it should have been on the ground.
