### ISSUE TITLE
"Blocks could not be compile.Try rebuilding from source manually"

### ISSUE THREAD

**Issue by yingjiewx** [microsoft/AirSim#4826]
My Environennt:Airsim v1.2,Unreal4.18.3,Visual Studio2017
Due to the needs of running the project，I didn't use the latest version,
I have seen other discussions, but it seems that none of them can solve my problem.
When I was building Airsim, he popped up an error related to Eigen, which was manually downloaded and placed in/airlib/deps to resolve.
But when I tried to use plugin in other unreal projects, I found that it couldn't load at all, and even caused my project to not run.
So I was wondering if the testing environment for blocks could run, and then the above situation occurred.
And it is normal after I run update-from_git，but there is a display system that cannot find the specified file
![微信图片_20230414150634](https://user-images.githubusercontent.com/82433176/231972069-43b74494-d48a-4412-8d72-f359678b7af4.png)
The following are the issues that occurred when I ran upproject
![微信图片_20230414150456](https://user-images.githubusercontent.com/82433176/231972282-22453c9b-5f05-4c4e-a4e5-412a959ee936.png)
![微信图片_20230414150506](https://user-images.githubusercontent.com/82433176/231972298-e6282c18-6597-43ce-b1b2-10a8af6f0051.png)
Error reported when running blocks from vs
![微信图片_20230414152232](https://user-images.githubusercontent.com/82433176/231972913-0e6ab4f4-73dd-412e-b339-9b9972d256d3.png)
Can someone solve it？thanks！！

**Comment by yingjiewx** [comment]
This error occurred on Win10

**Comment by yingjiewx** [comment]
OH！I think I could end this issue now,The reason for this issue is due to the lack of the eigen library after the initial build.cmd.
It is an error to directly unzip the eigen library on the official website to airlib/deps/. 
Even if you successfully build to use airsim, you will still report errors similar to those in Figure 3.
 In fact, all of those errors are from the eigen file
The correct approach is：
1.Open the build.cmd with vs
2.Search for “eigen” keywords，you could find the powershell command like the following picture.
![微信图片_20230415141135](https://user-images.githubusercontent.com/82433176/232189532-240b5108-a30c-42c7-b3d8-9002a4e925b9.png)
3.You will find that this link has become invalid and cannot download the eigen at all
4.And then You need to replace this link with the corresponding version of the official website's Eigen library link，
for example,If it is version 3.3.2, replace it with (https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.zip).
I have been stuck with this error for a long time, and I hope this issue can be helpful to those who later use the old version of Airsim！

**Comment by Menes00** [comment]
I'm also using UE4.18.3 with VS2017 for a project, I get this error when I build AirSim, I don't quite understand how you solved it.

![1](https://github.com/microsoft/AirSim/assets/131449301/83ad6b72-a828-4d67-920c-6d376e4e11d7) 
@yingjiewx
