### ISSUE TITLE
PX4 crashes the Unreal Engine 5.1.1 without any crash report (from UE)

### ISSUE THREAD

**Issue by srijanpal07** [microsoft/AirSim#4844]
## Bug report 

- AirSim Version/#commit: [Colosseum](https://github.com/CodexLabsLLC/Colosseum)
- UE/Unity version: UE 5.1.1
- autopilot version: v1.12.1
- OS Version: Windows 11/ wsl2 version: Ubuntu-18.04 LTS

### What's the issue you encountered?

I am trying to make PX4 communication for AirSim, but every time I ran the "make px4_sitl_default none_irisG" command in wsl2, its shows the simulator is able to make the connection but after within 30-50 secs the UE project crashes without giving any crash reports and I get 'ERROR [simulator] poll timeout 0, 0' in the terminal in which I am running PX4. I have tried building AirSim and running PX4 both inside the Linux and Windows file systems but the same issue persists. 

![image](https://github.com/microsoft/AirSim/assets/123281965/48381a56-a366-48a8-afc9-206907e4755e)

### Settings
The default settings.json file 
{
    "SettingsVersion": 1.2,
    "SimMode": "Multirotor",
    "ClockType": "SteppableClock",
    "Vehicles": {
        "PX4": {
            "VehicleType": "PX4Multirotor",
            "UseSerial": false,
            "LockStep": true,
            "UseTcp": true,
            "TcpPort": 4560,
            "ControlIp": "remote",
            "ControlPortLocal": 14540,
            "ControlPortRemote": 14580,
            "LocalHostIp": "172.28.0.1",
            "Sensors":{
                "Barometer":{
                    "SensorType": 1,
                    "Enabled": true,
                    "PressureFactorSigma": 0.0001825
                }
            },
            "Parameters": {
                "NAV_RCL_ACT": 0,
                "NAV_DLL_ACT": 0,
                "COM_OBL_ACT": 1,
                "LPE_LAT": 47.641468,
                "LPE_LON": -122.140165
            }
        }
    }
} 

### How can the issue be reproduced?

1. Press Play in the UE environment with the default settings
2. In wsl2, in the PX4-Autopilot directory run: 'make px4_sitl_default none_irisG'

### Include full error message in text form
...
INFO  [ecl/EKF] reset position to GPS
INFO  [ecl/EKF] reset velocity to GPS
INFO  [ecl/EKF] starting GPS fusion
INFO  [tone_alarm] home set
INFO  [tone_alarm] notify negative
ERROR [simulator] poll timeout 0, 0
ERROR [simulator] poll timeout 0, 0
ERROR [simulator] poll timeout 0, 0

**What's better than filing an issue? Filing a pull request :).**

**Comment by doeschbj** [comment]
Hello, do you have any updates on this issue yet? I probably encountered a similar issue, where UE with AirSim crashes within 2 - 60 seconds after starting px4. The more drones I use the earlier it crashes and UE just gives me an access violation error to some 0x0...28 location.

**Comment by srijanpal07** [comment]
> Hello, do you have any updates on this issue yet? I probably encountered a similar issue, where UE with AirSim crashes within 2 - 60 seconds after starting px4. The more drones I use the earlier it crashes and UE just gives me an access violation error to some 0x0...28 location.

I downgraded my system to Windows 10, because last time AirSim was supported, windows 11 did not came out and reinstalled unreal, wsl2, and everything from scratch in windows 10. It is working fine right now!
