### ISSUE TITLE
PhysXVehicles Plugin required for UE5. 

### ISSUE THREAD

**Issue by michael-2509** [microsoft/AirSim#4851]
### What's your question?

How can I make chaosVehicle work with the Airsims plugin?

### Include context on what you are trying to achieve

I created a new unreal project and When I add the airsim plugin to the project and run build, I get the PhysXVehicles plugin missing and I can only use the chaosVehicle plugin for UE5

#### Context details

- UE version: 5.2
- Airsim Version v1.8.1

### Include details of what you already did to find answers
- I've tried to enable the physXVehicle plugin in the .Uproject
![image](https://github.com/microsoft/AirSim/assets/61965542/fb6d674b-39a7-4021-b2af-aafded4c9395)

- I've also tried to edit the build.cs file 
![image](https://github.com/microsoft/AirSim/assets/61965542/6b343ba7-1b94-47ab-b4a3-2b23e06b0c4c)

**Comment by xxEoD2242** [comment]
Microsoft no longer supports or updates this project.

We have UE5 support here: [Colosseum](https://github.com/CodexLabsLLC/Colosseum)
