### ISSUE TITLE
ERROR in DQN drone example: Environment space is not image or dictionary observation space

### ISSUE THREAD

**Issue by kanishkanarch** [microsoft/AirSim#4862]
## Bug report 

- AirSim Version/#commit: AirSimNH binary tag 1.8.1
- UE/Unity version: N/A
- autopilot version: PX4-Autopilot commit `b874eaf5f90`
- OS Version: Ubuntu 20 Kernel 5.15.0-75-generic
- nVidia driver version: `nvidia-driver-525` (525.116.04-0ubuntu0.20.04.1 amd64)

### What's the issue you encountered?

The DQN example in the repository is giving environment gym error saying that the environment space is not an image or a dictionary. Following is the error I am getting:
![image](https://github.com/microsoft/AirSim/assets/52484751/90cdcc37-e344-4921-8785-5b6e0e4ea88f)

### Settings

I am using default settings

### How can the issue be reproduced?

1. Run the [LandscapeMountains simulator](https://github.com/microsoft/AirSim/releases/download/v1.8.1-windows/LandscapeMountains.zip) using `~/LandscapeMountains/LinuxNoEditor/LandscapeMountains.sh -windowed`
2. Run the given DQN example using `python3 ~/AirSim/PythonClient/reinforcement_learning/dqn_drone.py`

### Include full error message in text form
/home/ubuntu20sdd/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:74: UserWarning: The `render_mode` attribute is not defined in your environment. It will be set to None.
  warnings.warn("The `render_mode` attribute is not defined in your environment. It will be set to None.")
Traceback (most recent call last):
  File "dqn_drone.py", line 27, in <module>
    env = VecTransposeImage(env)
  File "/home/ubuntu20sdd/.local/lib/python3.8/site-packages/stable_baselines3/common/vec_env/vec_transpose.py", line 22, in \_\_init\_\_
    assert is_image_space(venv.observation_space) or isinstance(
AssertionError: The observation space must be an image or dictionary observation space

**What's better than filing an issue? Filing a pull request :).**

**Comment by kanishkanarch** [comment]
Thanks, @GioFic95 , following is the difference in your packages and my packages, can you please specify which libraries you downgraded?:
![image](https://github.com/microsoft/AirSim/assets/52484751/aee83790-fe29-41da-a654-a6f0391c9662)
I can't use conda for this particular project (there's a technical reason), so I have installed packages with native pip. Anyhow, I checked and there's no difference in your pip packages and your conda packages, so I don't know what to do with your conda package list:
![image](https://github.com/microsoft/AirSim/assets/52484751/b9cbcfcf-2936-4c35-99c8-8a28aa0de516)

**Comment by kanishkanarch** [comment]
I downgraded only `stable-baselines3` library and now the RL code is working perfectly fine without any errors. 
Thank you so much for your help, @GioFic95 !!

**Comment by wzwb** [comment]
Thanks！！！！
