### ISSUE TITLE
HelloDrone Unable to build

### ISSUE THREAD

**Issue by spencerh-b** [Microsoft/AirSim#488]
Does anyone have a working project on linux they would be willing to throw on onedrive? Trying to get AirSim running and it isn't building currently.

**Comment by rjk2147** [comment]
Did you try running the install_run_all.sh script instead of following the directions here: https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md 

The script worked for me but the directions didnt, probably unreal 4.17 that works better

**Comment by sytelus** [comment]
Could you please post the error. I was able to build it all fine.

**Comment by spencerh-b** [comment]
'spencer@exalabs-OptiPlex-9020:~/AirSim/HelloDrone$ gpp main.cpp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

main.cpp:5: error: Requested include file not found'

**Comment by spencerh-b** [comment]
`_____@e______-OptiPlex-9020:~/AirSim/HelloDrone$ gpp main.cpp
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

main.cpp:5: error: Requested include file not found`

**Comment by SaiVineethJ** [comment]
Did you find a way to remove the error of include file missing??

**Comment by spencerh-b** [comment]
Instead of using gpp you use clang for AirSim, I opted to just move to the python version in the python client folder, it could also mean that your repo didn't build right but I would just try.

```
cd <AirSim Repo>
python PythonClient/hello_drone.py
```

Hopefully this works for you @SaiVineethJ

**Comment by SaiVineethJ** [comment]
Thanks it worked for me..

But the drone is not moving on running the hello_drone.py, the hello_car.py is working properly.
Is your drone showing any changes on running the code?? 
I am using Ubuntu14.

**Comment by SaiVineethJ** [comment]
Thanks it worked. I had to use default settings of AirSim initially.
