### ISSUE TITLE
Unable to run AirSim in Car mode

### ISSUE THREAD

**Issue by kaihuchen** [Microsoft/AirSim#494]
FYI, I have tried to run  AirSim in Car mode without success. I have changed settings.json per the instructions in https://github.com/Microsoft/AirSim/blob/master/docs/using_car.md , but AirSim is still showing a drone after it is restarted.  Running hello_car.py also gives me *Connection refused* message.

I am running the Windows version of AirSim, updated from the master branch just hours ago. My installation runs hello_drone.py perfectly without problem.

**Comment by sytelus** [comment]
Are you using binaries? The binary release isn't updated yet...

**Comment by kaihuchen** [comment]
Ah, I see. Indeed I am using binaries. Thanks for your quick reply!

**Comment by sytelus** [comment]
Just uploaded new [release](https://github.com/Microsoft/AirSim/releases/tag/v1.1%2C0).

**Comment by kaihuchen** [comment]
@sytelus    Works great! Thanks!
