### ISSUE TITLE
What's the most efficient way to get a steady stream of images from the camera?

### ISSUE THREAD

**Issue by kaihuchen** [Microsoft/AirSim#495]
I want to train an autonomous drone to navigate by vision, and for that I'd like to get a steady stream of images from the camera. Aside from calling simGetImage (I am using the Python client) in a tight loop, is there any better way to do this?

**Comment by sytelus** [comment]
Right now the image API model is "pull" model, i.e., you need to make a call when you want images. I don't think this will change. So just have a loop that retrieves images at regular interval. For higher framerate you will need to reduce resolution of the requested images (default is good for high FPS).
