### ISSUE TITLE
opening a project error

### ISSUE THREAD

**Issue by walk4dead** [Microsoft/AirSim#496]
im learning UE4 on linux i tried to create a new project but the editor blocked in 96% loading and the terminal show me this error :
LogMaterial: Missing cached shader map for material M_Metal_Copper, compiling.

**Comment by sytelus** [comment]
I would suggest try to create new blank project without any assets or starter content. You might have slower machine and/or GPU so it might take longer. Please post UE4 related questions here: https://answers.unrealengine.com.
