### ISSUE TITLE
How to get semantic segmentation of images

### ISSUE THREAD

**Issue by jfc43** [Microsoft/AirSim#497]
Now we can only get segmentation of images. The color doesn't correspond to object class. So is it possible to get semantic segmentation?

**Comment by sytelus** [comment]
Please see https://github.com/Microsoft/AirSim/issues/118.

**Comment by sytelus** [comment]
We now also have new APIs for segmentation: https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#segmentation
