### ISSUE TITLE
getting angular velocities through api

### ISSUE THREAD

**Issue by abdelrahman-t** [Microsoft/AirSim#501]
is there anyway to get angular velocities through provided apis ?

thank you 😄

**Comment by Ricardus312** [comment]
Please, see this thread: https://github.com/Microsoft/AirSim/issues/487

**Comment by abdelrahman-t** [comment]
I have made a fork, with added access to angular velocity through the python API, if anyone is interested

**Comment by jpreiss** [comment]
@abdelrahman-t is the implementation in your fork tested/working? I also need this feature. Why don't you submit a pull request to mainline?

**Comment by cangokalp** [comment]
I need this too! - can you guys please make angular velocity exposed in the python API. I actually did it once for an old version- but now some of the interactions has changed in the new version, can't get it to work anymore.

**Comment by sytelus** [comment]
We have added new APIs to get angular velocity (along with other kinematics quantities). Please see https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#getmultirotorstate.
