### ISSUE TITLE
AirSim does not build on Fedora

### ISSUE THREAD

**Issue by aerosuraj** [Microsoft/AirSim#502]
Currently setup.sh only works with Ubuntu. The scripts are not generalized for Fedora

**Comment by sytelus** [comment]
Could you please post build log/error messages etc? We don't use Fedora so it would be great if you can help/test on Fedora :).

**Comment by aerosuraj** [comment]
The issue is with setup.sh script in AirSim. It uses apt-get to install packages wheres in Fedora the command is dnf. I tried to find the dependencies that need to be installed but still had issues. Can you post a list of dependencies for AirSim? Also, need minimum system requirements for running AirSim. It seems my Linux machine with Ubuntu is not adequate either.

**Comment by sytelus** [comment]
Main dependency is cmake and clang 3.9 which is what setup.sh tries to install. If you replace apt-get for those, things should work, I guess.

**Comment by sytelus** [comment]
We would love to get any pull request for doc on how to build AirSim on Fedora :)
