### ISSUE TITLE
HIL PX4 1.6.5 working fine if we reboot using nsh on a serial telemetry port ...

### ISSUE THREAD

**Issue by wifibot78** [Microsoft/AirSim#504]
For a project I am obliged to use HIL PX4 1.6.5, so I tried different thinks  to make it work
I am working on a good gaming pc, so no problem with computer resources.
 
px4 1.5.5 was ok 9/10 time , except that sometime the drone flight crazy time to time, i needed to restart everything.

I focused on 1.6.5 firmware, the one i use on my real drones, some of them are 10kg heavy, so good to test before flying :-)

Almost each time the drone goes crazy, and once a will all it was fine ?

When the drone was disarmed, I had this messages on nsh console (i plugged a usb serial adapter to avoid disturbing and the drone was not falling, I changed the start position):
'Freefall detected'STATUS: sev=6, 'Landing detected'STATUS: sev=6, 'Takeoff detected'STATUS: sev=6, 'Freefall detected' etc .......
and on QGC the attitude estimator was crazy, gps position was ok and altitude and heading was also crazy.

I tried to reboot using nsh console and then restart the 3d simulator (stop and play)
, and all was ok, I was able to flight manual or auto, the drone was stable finally.

I am still having this messages on the ground on nsh console, but evrything is fine during the flight:
'Freefall detected'STATUS: sev=6, 'Landing detected'STATUS: sev=6, 'Takeoff detected'STATUS: sev=6, 'Freefall detected' etc .......
**I saw that the landing detector is not working so perhaps it is just a mater of tuning ?**

**but now I can fly with 1.6.5 firmware and make my tests, need just to perform a nsh reboot ...**

How can we solve this ? it seems that the problem happens when we begin to feed the estimator with 
simulated data at startup ?

**Comment by sytelus** [comment]
I would suggest, first try to repro this in [jMavSim](https://pixhawk.org/dev/hil/jmavsim) and then either post this issue at post this at PX4 forums: http://discuss.px4.io and/or https://github.com/PX4/Firmware/issues. 

Another option is to try out software-in-loop (I have heard that works fine with newer releases). 

Unfortunately we don't have cycles to debug PX4 stack but would love to know any pointers you find that other users can be benefitted from.
