### ISSUE TITLE
Segmentation won't work when building own plugin

### ISSUE THREAD

**Issue by abhay-venkatesh** [Microsoft/AirSim#505]
Segmentation in CV mode using the Python API works fine when I use the NeighborHood pre-built windows binary. However, on building the plugins on my own, segmentation images are basically black. What is going wrong?

**Comment by sytelus** [comment]
Are you building your own environment? In that case you may want to try setting Custom Depth-Stencil as below. This shouldn't be needed but something to try. Also if you can code open (make sure to get latest), then search for `ASimModeBase::setStencilIDs()` function, put breakpoint and see if it gets called how meshes are assigned stencil IDs. These IDs are from 0-255 and each number corresponds to a color in a pallet.


![image](https://user-images.githubusercontent.com/2096835/31108922-3b1af414-a7b1-11e7-9029-88656a691077.png)
