### ISSUE TITLE
Possible inconsistency in documentation about "SimMode" parameter

### ISSUE THREAD

**Issue by saihv** [Microsoft/AirSim#507]
The documentation about settings.json states that SimMode has to be "" or "Multirotor" for simulating a drone, whereas [in the code](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/SimHUD/SimHUD.cpp#L207), looks like the SimMode value is being checked against "Quadrotor".

**Comment by sytelus** [comment]
Thanks. Fixed: https://github.com/Microsoft/AirSim/commit/c9d45cff0215089f6f3017341ede06f32c63727d
