### ISSUE TITLE
Lack certain file, help please!

### ISSUE THREAD

**Issue by billchenxi** [Microsoft/AirSim#510]
I tried to use unreal engine editor to open the project, and this popped up.

![image](https://user-images.githubusercontent.com/986935/31149736-ed694212-a85e-11e7-8954-5a92e47e647e.png)

**Comment by sytelus** [comment]
Just press Yes.

**Comment by billchenxi** [comment]
Not working!!! Do you really think I am that stupid?
![image](https://user-images.githubusercontent.com/986935/31188474-088e996c-a903-11e7-9589-e0c2899904d0.png)
