### ISSUE TITLE
How do I update my Unreal Project with a new AirSim version

### ISSUE THREAD

**Issue by Kjell-K** [Microsoft/AirSim#511]
I modified my environment a lot and do not want to lose progress. Which steps do I have to follow in order to update my Unreal project with a new AirSim version. How do I update .uasset itself?

**Comment by sytelus** [comment]
Very easy. 

1. Build new version of AirSim in some folder.
2. Replace Plugins folder in your Unreal environment project with AirSim\Unreal\Plugins folder .

Also see [this](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md#is-there-easy-way-to-sync-code-in-my-unreal-project-with-code-in-airsim-repo).

**Comment by Kjell-K** [comment]
Thanks. Works perfectly
