### ISSUE TITLE
Downtown env for Multirotor

### ISSUE THREAD

**Issue by Kjell-K** [Microsoft/AirSim#512]
@sytelus It would be great to have the Downtown binaries env fully compatible with the MultirotorClient() as well. 
Also setting up Collisions with buildings as static meshes would be necessary then.

Downtown is a much more attractive environment for Copter than Neighborhood.

**Comment by sytelus** [comment]
This is working fine on my m/c. What do you see?

**Comment by Kjell-K** [comment]
I was just missing the information text on the upper left, but it seems it is removed for all envs?

Therefore the main point is: 

> **Also setting up Collisions with buildings as static meshes would be necessary then.**

**Comment by sytelus** [comment]
Current binaries are in shipping config. I think I should revert them back to Develop config so you can see log messages. I will check out the collisons.

**Comment by sytelus** [comment]
We have newer City environment now. Also all log text should be working in new release.
