### ISSUE TITLE
Recording is giving less pixel images

### ISSUE THREAD

**Issue by exploke** [Microsoft/AirSim#515]
I am trying to get a set of images from Airsim by pressing the record button while flying. The pictures in my folder turn out to be very low pixel density, and almost look like thumbnails. Here is my capture settings in my settings file:
CaptureSettings": [
    {
      "ImageType": -1,
      "Width": 1280,
      "Height": 720, 

Is there something I can do get 720p images?

**Comment by sytelus** [comment]
Change ImageType to 0 above. The default setting of -1 means "not set".

**Comment by oppne** [comment]
What if that doesnt work?
