### ISSUE TITLE
Record Button is not Working

### ISSUE THREAD

**Issue by exploke** [Microsoft/AirSim#521]
I am on the latest commit for AirSim. Whenever I attempt to press the record button, I get this error.
![capture](https://user-images.githubusercontent.com/25913167/31300401-27a0f662-aab9-11e7-86c0-30587806fde7.PNG)

The error seems to be in the RecordingThread.cpp on line 65.
![capture2](https://user-images.githubusercontent.com/25913167/31300442-51de0eb0-aab9-11e7-99c6-45586d1a3829.PNG)

**Comment by sytelus** [comment]
Thanks for reporting. This is now fixed in latest source as well as binaries.
