### ISSUE TITLE
AirSimNeighbourhood not working with RC

### ISSUE THREAD

**Issue by robotvin** [Microsoft/AirSim#524]
hello
I have downloaded AirSimNeighbourhood build files. I am using pixhawk with Spectrum DX7S RC. The quadcopter is not responding to RC commands. Anything i m missing. Please guide,

**Comment by sytelus** [comment]
Are you using hardware in loop? Is RC transmitter connected to Pixhawk. To use RC with Pixhawk, please see related document on Pixhawk/Arducopter websites such as this: http://ardupilot.org/copter/docs/common-pixhawk-and-px4-compatible-rc-transmitter-and-receiver-systems.html

I would also suggest to try out QGroundControl first to try out Pixhawk configuration before you try out AirSim.

**Comment by robotvin** [comment]
Thanks for reply
Yes the RC is connected with pixhawk and its working well with my own created and build environments using Airsim. But its not working with AirSimNeighbourhood builds.

**Comment by mchen0037** [comment]
Hi @robotvin, did you ever find a solution? I'm using a DX8 and having a similar issue.
