### ISSUE TITLE
Enable ROS and Gazebo integration

### ISSUE THREAD

**Issue by JiamingSuen** [microsoft/AirSim#53]
Testing control algorithms with [SITL plugin](https://github.com/erlerobot/ardupilot_sitl_gazebo_plugin) + Gazebo + ROS is now the common way, while Gazebo only provides poor visual simulations which is not realistic enough for Deep Learning/Reinforcement Learning research. Is there any plan for AirSim of such kind of integration with ROS? In specific this would allow us to retrieve state information and camera view etc from AirSim, and we can use tools like [mavros](http://wiki.ros.org/mavros) to send control command to the vehicle.
Thanks for this incredible work!

**Comment by sytelus** [comment]
Yes, we do have plan to enable ROS for AirSim. We have some code that was working with Matrice underROS which we will port to AirSim. This will essentially make possible to call our APIs as ROS services and request publication of sensor data.

I'll change the title of this issue to reflect this and keep this open.

**Comment by AlexandreBorowczyk** [comment]
Have anyone tried to integrate SITL to AirSim?

**Comment by lovettchris** [comment]
Sure, see [https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md](https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md).

**Comment by zaddan** [comment]
Hi,
Is there any update on the ROS integration?

**Comment by sytelus** [comment]
Not yet. We are heads down on making Linux build fully work first and create standalone flight controller for next two weeks or so. After that ROS integration would take priority.

**Comment by togaen** [comment]
@sytelus Are there any examples or readme's you could point to that show the kind of AirSim ROS adapter you mentioned in #333?

**Comment by sytelus** [comment]
Not yet. Basically the plan is to use RpcApi to transmit ROS messages.

**Comment by jokla** [comment]
Hi @sytelus ! Do you have any update on the ROS integration?
Thank you!

**Comment by pdebitetto-tft** [comment]
Hi Guys, just checking back about ROS integration.  I'm just learning about AirSim and compared to the others this has many desirable characteristics.  Really nice work Chris et. al.!  however i would like to drive it using a higher level mission-autonomy computer running ROS.  

Also, i would like to run a SITL version using the PX4 stack.  the sitl.md file recommended above doesn't seem to exist anymore.   
Thanks!
Paul

**Comment by pdebitetto-tft** [comment]
Hi Guys, just checking back about ROS integration. I'm just learning about AirSim and compared to the others this has many desirable characteristics. Really nice work Chris et. al.! however i would like to drive it using a higher level mission-autonomy computer running ROS.

Also, i would like to run a SITL version using the PX4 stack. the sitl.md file recommended above doesn't seem to exist anymore.  If there are anymore recent developments please let know.

Thanks!
Paul

**Comment by HarrisSym** [comment]
Hello, i'm intestred in ROS integration. Is there any update on this matter?

**Comment by ykhedar** [comment]
Hi,This would be a great addition to the simulation environment. Is the pull request number 842 **rosbridge_first_test** the official addition of this feature or a different version being worked on by the AirSim team. Would be great to know the status. Really appreciate the great work being done by the AirSim team :)

Thanks,
ykhedar

**Comment by sytelus** [comment]
rosbridge_first_test is by one of our users and is under review. Please feel free to review/provider feedback for this PR.

**Comment by n1ckfg** [comment]
We're making progress on the bridge. With the new API, is the car coordinate system still NED, or had that changed?

**Comment by sytelus** [comment]
Everything is still NED.

**Comment by MohamedAliRashad** [comment]
Waiting for the ROS integration as well.
 
This simulator looks Damn Good guys, Great Work :+1:

**Comment by wndaiga** [comment]
Very promising work! This would easily blow my other options for a quad simulator out the water (TUM simulator, Hector Quadcoter) but the lacking ROS/MoveIt! integration is my only hold out

**Comment by TritonSailor** [comment]
You can find some simple examples I contributed yesterday for publishing AirSim data in ROS nodes using PythonClient in my PR here:

https://github.com/Microsoft/AirSim/pull/1135

Please try them and let me know if you have any issues running them.  I will be contributing additional examples in the near future. 

Sounds like a complete ROS integration solution is in the works, but in the meantime, these examples should help you get started.

**Comment by wndaiga** [comment]
@TritonSailor Thanks a ton, exactly what I needed!

**Comment by madratman** [comment]
Please see [airsim_ros_pkgs](https://github.com/microsoft/AirSim/tree/master/ros/src/airsim_ros_pkgs) and [airsim_tutorial_pkgs](https://github.com/microsoft/AirSim/tree/master/ros/src/airsim_tutorial_pkgs) for a ros wrapper over the multirotor API

**Comment by xlong0513** [comment]
Interested in ros and mavros integration. Is there any progress yet?
