### ISSUE TITLE
Errors when generating uproject

### ISSUE THREAD

**Issue by cca2016** [Microsoft/AirSim#535]
As I successfully update the latest version of AirSim, I copied the plugins into my project and generate the uproject file. But the problem came as the following shows:

Discovering modules, targets and source code for project...
Messages while compiling D:\Unreal Projects\LandscapeMountains\Intermediate\Build\BuildRules\LandscapeMountainsModuleRules.dll:
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(72,49) : error CS1729: ??UnrealBuildTool.ModuleRules???????????á?1?????????Ĺ??캯??
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(96,20) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(126,41) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(126,90) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(127,46) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Configuration???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Configuration??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(131,20) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(136,27) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
d:\Unreal Projects\LandscapeMountains\Plugins\AirSim\Source\AirSim.Build.cs(136,76) : error CS1061: ??UnrealBuildTool.ReadOnlyTargetRules??????????Platform???Ķ??壬?????Ҳ????ɽ???????Ϊ??UnrealBuildTool.ReadOnlyTargetRules???ĵ?һ??????????չ??????Platform??(?Ƿ?ȱ?? using ָ???????????????)
UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

This is my project's message:
{  
    "FileVersion": 3,  
    "EngineAssociation": "4.15",  
    "Category": "Samples",  
    "Description": "",  
    "Modules": [  
        {  
            "Name": "LandscapeMountains",  
            "Type": "Runtime",  
            "LoadingPhase": "Default",  
            "AdditionalDependencies": [  
                "AirSim"  
            ]  
        }  
    ],  
    "TargetPlatforms": [  
        "MacNoEditor",  
        "WindowsNoEditor"  
    ],  
    "EpicSampleNameHash": "1226740271",  
    "Plugins": [  
        {  
            "Name": "AirSim",  
            "Enabled": true  
        }  
    ]  
}

**Comment by dianzizs** [comment]
Hello, I have encountered the same question. Do you remember how did you fix this?
