### ISSUE TITLE
Is rendering necessary?

### ISSUE THREAD

**Issue by cangokalp** [Microsoft/AirSim#551]
Is there a way to get the data from the simulation without rendering?

**Comment by sytelus** [comment]
Which data? Car or multirotor? For multirotor, you can do simulation without Unreal Engine. In that case you get all the kinematics data (pose, velocity, acceleration) but no images. Here is some examples of how to use AirSim backend without any rendering engine (see StandAlone* files):

https://github.com/Microsoft/AirSim/tree/master/Examples

**Comment by cangokalp** [comment]
For multirotor, yes;

This way it'll behave exactly as how it would behave with the rendering, right? I mean would the physics be there? Also can I do this via python API?

**Comment by sytelus** [comment]
Currently API server runs in Unreal code so you won't be able to use APIs. Related: https://github.com/Microsoft/AirSim/issues/563
