### ISSUE TITLE
Does reset work now?

### ISSUE THREAD

**Issue by cangokalp** [Microsoft/AirSim#553]
I pulled the repo again just now, but reset still won't work.
msgpackrpc.error.RPCError: b"rpclib: server could not find function 'reset' with argument count 0."

**Comment by sytelus** [comment]
yes, it is implemented now and I've tested for car as well as multirotor. Could you please make sure you have latest AirSimClient.py? Above error message means you have older Python client.

**Comment by cangokalp** [comment]
now the reset() works and the multirotor resets from the starting point. However, after the reset I can't control it anymore, it doesn't do anything -say when I do client.moveToZ(-10,5), it just sits there.

**Comment by sytelus** [comment]
Are you using PX4 or simple_flight (default)?

**Comment by zamlz** [comment]
Hi I just pulled today, but I still get the same error. Do I have to recompile my environment for it to work properly?

**Comment by zamlz** [comment]
Alright, it looks like if I compile the unreal project, it works. Any news on when the binaries will be updated. I would really like to use the downtown and neighborhood environment with the reset feature.

**Comment by cangokalp** [comment]
I'm using simple flight @sytelus

**Comment by cangokalp** [comment]
I'm using it in the blocks environment. When I do reset, it resets but I can't control it after that.

**Comment by sytelus** [comment]
Ok... I found the issue. There was a bug that I just pushed the [fix](https://github.com/Microsoft/AirSim/commit/c02dcfd3175647c26dbc5388f5bd8e5be74f22f8). However another thing is that you must call below again after reset() because we reset the complete state.

```
client.enableApiControl(True)
client.armDisarm(True)
```

Below is the sample code I tested:

```
from AirSimClient import *

# connect to the AirSim simulator 
client = MultirotorClient()
client.confirmConnection()
client.enableApiControl(True)
client.armDisarm(True)

AirSimClientBase.wait_key('Press any key to takeoff')
client.takeoff()

AirSimClientBase.wait_key('Press any key to move vehicle to (-10, 10, -10) at 5 m/s')
client.moveToPosition(-10, 10, -10, 5)

AirSimClientBase.wait_key('Press any key to reset to original state')
client.reset()
client.enableApiControl(True)
client.armDisarm(True)

AirSimClientBase.wait_key('Press any key to takeoff')
client.takeoff()

AirSimClientBase.wait_key('Press any key to move vehicle to (-10, 10, -10) at 5 m/s')
client.moveToPosition(-10, 10, -10, 5)
```
