### ISSUE TITLE
controlling via Roll, pitch, yaw, throttle inputs

### ISSUE THREAD

**Issue by cangokalp** [Microsoft/AirSim#555]
Hi, 
I want to use moveByManual basically but instead of RC data I want to give the inputs myself as a four by one vector. I tried to extend the python API and tried to do this with the following function - it's simply the translation of cpp code under the function movebymanual - with rcdata removed. rpyt input is the vector with roll,pitch,yaw,throttle inputs.

```
    def move_drone(self, rpyt, vx_max=10, vy_max=10, z_min=0, drivetrain = DrivetrainType.MaxDegreeOfFreedom, yaw_mode = YawMode()):
        from pyquaternion import Quaternion as quat
        kMaxRCValue = 1.0

        # //freeze the quaternion
        sq = Quaternionr.from_msgpack(self.client.call('getOrientation'))

        vel_world = Vector3r(rpyt[1]*vy_max/kMaxRCValue, rpyt[0]*vx_max/kMaxRCValue, 0)

        sq = quat(sq.w_val, sq.x_val, sq.y_val, sq.z_val)
        conj_sq = sq.conjugate
        vel_body = conj_sq.rotate((vel_world.x_val, vel_world.y_val, vel_world.z_val))
        vel_body = Vector3r(vel_body[0], vel_body[1], vel_body[2])

        # //find yaw as per terrain and remote setting
        adj_yaw_mode = YawMode(yaw_mode.is_rate, yaw_mode.yaw_or_rate)
        adj_yaw_mode.yaw_or_rate += rpyt[2] * 100.0/kMaxRCValue;

        vz = (rpyt[3]/kMaxRCValue) * z_min + self.getPosition().z_val

        self.moveByVelocityZ(vel_body.x_val, vel_body.y_val, vz, adj_yaw_mode)
        # self.client.call('moveByVelocityZ', vel_body.x_val, vel_body.y_val, vz, adj_yaw_mode)
```

when I do this, I get this error:*** msgpackrpc.error.RPCError: b"rpclib: function 'moveByVelocityZ' (called with 6 arg(s)) threw an exception. The exception contained this information: bad cast."

and instead if I call self.client.call('moveByVelocityZ', vx, vy, z, duration, drivetrain, yaw_mode) it doesn't return error but this time I'm unable to just move in Z <= I keep vx,vy and yaw as 0 and change throttle and drone doesn't move.

Any ideas how to implement this. Eventually I want to be able to control the drone with roll,pitch,yaw,throttle inputs

**Comment by sytelus** [comment]
Correct call is `self.client.call('moveByVelocityZ', vx, vy, z, duration, drivetrain, yaw_mode)`. You will need to put breakpoint and see what are the values you are passing to investigate this.
