### ISSUE TITLE
Issue with recording settings

### ISSUE THREAD

**Issue by oppne** [Microsoft/AirSim#561]
I set my recording settings
  },
  "CaptureSettings": [
    {
      "ImageType": 0,
      "Width": 2048,
      "Height": 2048,
      "FOV_Degrees": 90,
      "AutoExposureSpeed": 100,
      "AutoExposureBias": 0,
      "AutoExposureMaxBrightness": 0.64,
      "AutoExposureMinBrightness": 0.03,
      "MotionBlurAmount": 0,
      "TargetGamma": 1.0
    }
  ],

Doesnt really change anything, no matter what settings i change in the settings json, nothing changes in ue4. Recordings always standard settings.

**Comment by oppne** [comment]
Still not working, anyone have a solution?

**Comment by oppne** [comment]
I fixed it.

Now how can i render out different image types at the same time?
TRied adding to array, didint work properly.

**Comment by sytelus** [comment]
Please see this and continue conversation there: https://github.com/Microsoft/AirSim/issues/607

**Comment by Beijingsheng** [comment]
@oppne  How do you fix your problem? I'm facing the same problem right now. No matter what I write in settings.json won't cause any changes.
