### ISSUE TITLE
Block environment : ImageWrapper.h file not found

### ISSUE THREAD

**Issue by jeremyfix** [Microsoft/AirSim#569]
Hi, when loading the Block UE environment you provide, UEditor is compiling it and at some raises an issue :

In file included from /opt/GIT/AirSim/Unreal/Environments/Blocks 4.18/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp:14:
/opt/GIT/AirSim/Unreal/Environments/Blocks 4.18/Plugins/AirSim/Source/AirSimGameMode.cpp:3:10: fatal error: 
      'ImageWrapper.h' file not found
#include "ImageWrapper.h"

I tried to "find . -name  ImageWrapper.h" but nothing is returned neither in AirSim nor in UnrealEngine. What is this missing file coming from ?

**Comment by jeremyfix** [comment]
A follow up of my question. I'm using UnrealEngine **4.18** ; I found that the header where the IImageWrapperModule is defined is actually UnrealEngine/Engine/Source/Runtime/ImageWrapper/Public/IImageWrapperModule.h . There is also a IImageWrapper.h header. 

I might give a try changing the include. Do you agree on this change ?

**Comment by Fred12138** [comment]
I meet the same question as you. How about you now?

**Comment by jeremyfix** [comment]
I actually succeeded this morning to compile the plugin by changing the hearder 

In AirSim/Unreal/Plugins/AirSim/Source/AirSimGameNode.cpp , change

#include "ImageWrapper.h" 

by

#include "IImageWrapperModule.h"

Then adding the plugin to a new project, it compiled and I was able to spawn a drone.

**Comment by jeremyfix** [comment]
I created a pull request #570

**Comment by Fred12138** [comment]
Yeah I tried. your can do it actually!

**Comment by sytelus** [comment]
Thanks for figuring this out. Your PR is now merged!
