### ISSUE TITLE
VR Build

### ISSUE THREAD

**Issue by eanmikale** [Microsoft/AirSim#571]
We would like to test prototypes and build environments with the VR Editor Mode in Unreal, utilizing the HTC Vive and/or the HP Mixed Reality Headset. Is there any support coming soon for this capability? Thank you.

**Comment by sytelus** [comment]
Yes, this is in plan. Its fairly easy to add with Unreal Engine so please feel free to look in to it. We might not get around implementing this for at least next 2 months.

**Comment by eanmikale** [comment]
We have it built. It is quite the experience. Recommendations for future builds. We'd love to be able to utilize the command prompt, in-game for complete immersion. Thanks again.

**Comment by kandai-wata** [comment]
Could you tell us how you managed to build it for VR? 
I am trying to view it with oculus rift.
