### ISSUE TITLE
'msr::airlib::RealMultirotorConnector' is an abstract class

### ISSUE THREAD

**Issue by jeremyfix** [Microsoft/AirSim#572]
When running   build.sh , an error is thrown because 'msr::airlib::RealMultirotorConnector' is an abstract class.   Indeed,  the following two virtual pure methods are not overriden :

virtual bool setSegmentationObjectID(const std::string& mesh_name, int object_id,
				       bool is_name_regex = false) = 0;
  
  virtual int getSegmentationObjectID(const std::string& mesh_name) = 0;

in the file AirSim/AirLib/include/vehicles/multirotor/controllers/RealMultirotorConnector.hpp  and it inherits from AirSim/AirLib/include/controllers/VehicleConnectorBase.hpp

I succeed in building AirSim, by simply defining these two methods in RealMultirotorConnector.hpp with an empty body , but I do not know if this the expected behavior.

**Comment by nwayt001** [comment]
I had the same error, did what you did and it worked for me. I'm not sure what effect this will have though.

**Comment by sytelus** [comment]
Thanks for reporting this. This is now [fixed](https://github.com/Microsoft/AirSim/commit/c85eb438a7b2ad795a75f10f9deccafa447293de).

**Comment by tmericli** [comment]
The problem still seems to persist; this time complaining about the following virtual function that is not implemented in RealMultirotorConnector.hpp:

`virtual void printLogMessage(const std::string& message, std::string message_param = "", unsigned char severity = 0)`

Temporarily adding that function to RealMultirotorConnector.hpp with empty body solves the build problem, but a more principled solution is needed.
