### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by oppne** [Microsoft/AirSim#573]
Getting these when i try building

Build FAILED.

"D:\Marius\AirSim\AirSim-Source Files\AirSim\AirSim.sln" (default target) (1) ->
"D:\Marius\AirSim\AirSim-Source Files\AirSim\DroneServer\DroneServer.vcxproj" (default target) (6) ->
(ClCompile target) ->
  d:\marius\airsim\airsim-source files\airsim\droneserver\main.cpp(80): error C2259: 'msr::airlib::RealMultirotorConnec
tor': cannot instantiate abstract class [D:\Marius\AirSim\AirSim-Source Files\AirSim\DroneServer\DroneServer.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:01:45.82
#### Build failed

**Comment by sytelus** [comment]
Thanks for reporting. This is now [fixed](https://github.com/Microsoft/AirSim/commit/c85eb438a7b2ad795a75f10f9deccafa447293de).
