### ISSUE TITLE
RC Controller on USB not detedcted

### ISSUE THREAD

**Issue by JeongsooHa** [Microsoft/AirSim#574]
OS : Linux(ubuntu)
I have installed 4.16.3 version of Unreal Engine and 66f9635 commit number of AirSim.
I wanted to use remote controller(FS-TH9X) in simulator. So, I also have installed driver of pixhawk4 and Qgroundcontrol. Then, i connected RC with pixhawk4. I could see RC could control Qgroundcontrol. 
when i try to control simulator drone in Blocks project, but It have never worked well.
ERROR
RC Controller on USB not detected  : 18446744073709551615
![error](https://user-images.githubusercontent.com/12974306/32188561-63c82868-bd65-11e7-9718-7b6da00e1db5.png)

**Comment by zergler** [comment]
Did you set up the right [configuration](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md)? It could also be that QGroundControl is taking over the connection. Try running it without QGroundControl.

**Comment by JeongsooHa** [comment]
Hi zergler.
Thank you for answer me. Unfortunately I already checked "settings.json". 
This is my settings.json file.
{ "SettingsVersion": 1, "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md"}
I think it is the right configuration. 
I checked the list of USB using "lsusb"
![image](https://user-images.githubusercontent.com/12974306/32296237-e8a8c638-bf08-11e7-81f3-c21e169a09c6.png)
But I could not see the name of USB(26ac:0011)
(port number "26ac:0011" is for PX4 FMU v2.x)
![image](https://user-images.githubusercontent.com/12974306/32296334-2dff6642-bf09-11e7-9732-2523a6013a9c.png)

So, I am confused now.
I don't know whether the USB(PX4) isn't working well or AirSim can not be getting the PX4 USB ID.
Thanks.

**Comment by JeongsooHa** [comment]
This is SimJoyStick.cpp
![image](https://user-images.githubusercontent.com/12974306/32303863-99590492-bf28-11e7-8b05-016b564735b4.png)
(I am changing this code for checking variable)
 As you can see, devicePath is "/dev/input/js" << index. 

![image](https://user-images.githubusercontent.com/12974306/32303928-e982e8de-bf28-11e7-8fde-e3d91436ebea.png)
However, there is no js* file in "/dev/input/". just event*.

And This is my settings.json

{ "SettingsVersion": 1.0,
"SimpleFlight": {
    "FirmwareName": "SimpleFlight",
    "DefaultVehicleState": "Armed",
    "RC": {
      "RemoteControlID": 14,
      "AllowAPIWhenDisconnected": false,
      "AllowAPIAlways": true
    },
    "ApiServerPort": 41451
  },
"PX4": {
    "FirmwareName": "PX4",
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "SimCompID": 42,
    "SimSysID": 142,
    "SitlIp": "127.0.0.1",
    "SitlPort": 14556,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": true,
    "VehicleCompID": 1,
    "VehicleSysID": 135,
    "ApiServerPort": 41451
  },
"SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md"
}

**Comment by sytelus** [comment]
AirSim currently only detects those joysticks which appears in /dev/input/js. Please see this which might be relevant: http://forum.vectorlinux.com/index.php?topic=18087.0. Please feel free to contribute the enhancement so we can detect wider array of joysticks!

**Comment by JeongsooHa** [comment]
Hi sytelus,
Thank you for your reply. I think there will be a lot of help.
