### ISSUE TITLE
How to run Neighbourhood or city downtown on Linux?

### ISSUE THREAD

**Issue by Arlen0615** [Microsoft/AirSim#578]
Hi, 

I have study **Setup Unreal Environment** part 

and I can run well **Option 1: Built-in Blocks Environment** on my Ubuntu PC

But I have no idea how to change the project to Neighbourhood or City downtown..

Is there any unreal project file on this github of Neighbourhood or City downtown?

Thanks very much.

**Comment by zergler** [comment]
Adding AirSim to custom environments is explained well in this [doc](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md), go take a look. If you are referring to the binaries for the Neighborhood environment from the AirSim release, those are Windows binaries so they wouldn't run on Linux.

The basic procedure is to generate the project files using a Windows PC and then copy them over to your Linux setup. UE4 for Linux is missing the Epic Games Launcher, which is required for this.

**Comment by mickey13** [comment]
Is there a (supported or unsupported) way to generate the appropriate project files on Mac OS, since it has the Epic Games Launcher?

**Comment by zergler** [comment]
It would probably be the same general procedure on a Mac.
