### ISSUE TITLE
Do have plan to develop a AirSim for Unity

### ISSUE THREAD

**Issue by zf223669** [Microsoft/AirSim#58]
Do have a plan to develop a AirSim for Unity?

**Comment by mulysatest** [comment]
Why Unity?

**Comment by zf223669** [comment]
because unity is popular now. :)

**Comment by lovettchris** [comment]
We agree Unity would be nice.  We have designed the AirSim library so that it can be plugged into different rendering engines.  It's just a matter of time and resources, we'd love the AirSim community to try it.
