### ISSUE TITLE
[Question] Is it typical for the installation / running of AirSim to be 25+ gbs?

### ISSUE THREAD

**Issue by rohanpai** [Microsoft/AirSim#580]
Trying to run AirSim on a virtual disk and it keeps taking up 25+ gb of storage -- wondering if this is typical

**Comment by sytelus** [comment]
No. This is my repo with all build binaries and Blocks environment:

![image](https://user-images.githubusercontent.com/2096835/32305991-05090e62-bf79-11e7-93ba-fb83e22ab6b7.png)
