### ISSUE TITLE
new AirSim build error 

### ISSUE THREAD

**Issue by fountainYuan** [Microsoft/AirSim#582]
build new AirSim in Win10 display these message:
airsim\droneserver\main.cpp(80): error C2259: “msr::airlib::RealMultirotorConnector”: can't instance abstract calss [G:\AirSim\DroneSer
ver\DroneServer.vcxproj]

  g:\airsim\droneserver\main.cpp(80): note: :
  g:\airsim\droneserver\main.cpp(80): note: “bool msr::airlib::VehicleConnectorBase::setSegmentationObjectID(const std:
  :string &,int,bool)”: is abstract
  g:\airsim\airlib\include\controllers\vehicleconnectorbase.hpp(31): note: see “msr::airlib::VehicleConnectorBase::setSeg
  mentationObjectID”declaration
  g:\airsim\droneserver\main.cpp(80): note: “int msr::airlib::VehicleConnectorBase::getSegmentationObjectID(const std::
  string &)”:is abstract
Who can tell me reason,thanks!

**Comment by sytelus** [comment]
Thanks for reporting. This is now [fixed](https://github.com/Microsoft/AirSim/commit/c85eb438a7b2ad795a75f10f9deccafa447293de).
