### ISSUE TITLE
Disparity Normalized

### ISSUE THREAD

**Issue by zaddan** [Microsoft/AirSim#583]
ROS messages of the type stereo_msgs/DisparityImage are not normalized. Based on the API description, DisparityNormalized uses the following equation (Xl - Xr)/Xmax for normalization. What is the value of Xmax? 255?

**Comment by sytelus** [comment]
disp = f * b / z where f = w/(2*tan fov), b is distance between cams = 0.25m. We normalize disparity by dividing by width so output is 0 to 1.
