### ISSUE TITLE
I have issue to build also.

### ISSUE THREAD

**Issue by billchenxi** [Microsoft/AirSim#589]
I have VS2015 and VS2017 installed, and I tried to execute the build.cmd from the VS2015,since it doesn't support 2017 yet. But I got this error. Can you help me?

------------------------------------------------------------------------------

               Total    Copied   Skipped  Mismatch    FAILED    Extras
    Dirs :         3         2         1         0         0         0
   Files :         3         3         0         0         0         0
   Bytes :   25.61 m   25.61 m         0         0         0         0
   Times :   0:00:00   0:00:00                       0:00:00   0:00:00

   Speed :           548060040 Bytes/sec.
   Speed :           31360.247 MegaBytes/min.
   Ended : Saturday, November 4, 2017 9:39:53 PM

'msbuild' is not recognized as an internal or external command,
operable program or batch file.

**Comment by sytelus** [comment]
Can you confirm you are running build.cmd from VS2015 x64 Native Command Prompt?
