### ISSUE TITLE
I cannot use python clients

### ISSUE THREAD

**Issue by billchenxi** [Microsoft/AirSim#592]
Can someone help me with this error?

C:\Users\Bill\Documents\GitHub\AirSim\PythonClient>python hello_car.py                                                  WARNING:tornado.general:Connect error on fd 536: WSAECONNREFUSED                                                        WARNING:tornado.general:Connect error on fd 536: WSAECONNREFUSED                                                        WARNING:tornado.general:Connect error on fd 536: WSAECONNREFUSED                                                        WARNING:tornado.general:Connect error on fd 536: WSAECONNREFUSED                                                        WARNING:tornado.general:Connect error on fd 536: WSAECONNREFUSED                                                        Waiting for connection: Traceback (most recent call last):                                                                File "hello_car.py", line 5, in <module>                                                                                  client.confirmConnection()                                                                                            File "C:\Users\Bill\Documents\GitHub\AirSim\PythonClient\AirSimClient.py", line 158, in confirmConnection                 home = self.getHomeGeoPoint()                                                                                         File "C:\Users\Bill\Documents\GitHub\AirSim\PythonClient\AirSimClient.py", line 167, in getHomeGeoPoint                   return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))                                                     File "C:\Users\Bill\Miniconda3\lib\site-packages\msgpackrpc\session.py", line 41, in call                                 return self.send_request(method, args).get()                                                                          File "C:\Users\Bill\Miniconda3\lib\site-packages\msgpackrpc\future.py", line 43, in get                                   raise self._error                                                                                                   msgpackrpc.error.TransportError: Retry connection over the limit

Many thanks,

**Comment by sytelus** [comment]
Are you running AirSim as well? Above error means your Python client code is not able to find AirSim server. This may also happen if you didn't allowed AirSim to open ports (Windows Firewall shows dialog box and you might have pressed Cancel or Escape).

**Comment by maximilianchang** [comment]
I ran into a similar situation. I am just running the out-of-box environment from "Neighborhood" (as downloaded from the link provided. 

Could the second issue you stated still apply? (Windows Firewall shows dialog box). And if so, do you have any pointers on how to resolve this?

**Comment by cseas** [comment]
Can someone please explain how to fix this issue? I'm getting the same and can't figure out a way to make the Python client work. I'm trying to run DQNcar.py with the Neighbourhood binary.

**Comment by ctselas** [comment]
@sytelus Do you have any answer ? Why this issue was closed since there was no answer and the problem still occurs in other persons ?
