### ISSUE TITLE
can AirSim be built with visual studio 2017?

### ISSUE THREAD

**Issue by abc19850508** [Microsoft/AirSim#595]
recently, i found I couldn't download the visual studio 2015 and the update ,can AirSim be built with visual studio 2017 now? and I cant install the .net framework 3.5, dose it have effect on the AirSim?

**Comment by abc19850508** [comment]
not yet

**Comment by sytelus** [comment]
I was just able to compile and run everything in VS2017.

Use "Developer command Prompt for VS 2017" to run build.cmd:

![image](https://user-images.githubusercontent.com/2096835/32762155-872b8118-c8ac-11e7-9284-c2c58a3d6239.png)


Select no upgrade for Platform toolset when opening .sln file:

![image](https://user-images.githubusercontent.com/2096835/32762094-22c421bc-c8ac-11e7-9314-713dc65a861d.png)


That's it.

**Comment by abc19850508** [comment]
@sytelus that‘s great！

**Comment by Jazzinghen** [comment]
I actually had to upgrade the platform toolset in order to build the plugin.

**Comment by sytelus** [comment]
@Jazzinghen which version of Windows are you using?

**Comment by Jazzinghen** [comment]
I am using Windows 10 64-bit

**Comment by n1ckfg** [comment]
You also have to edit build.cmd depending on whether you're using VS 2015 or VS 2017. Afaik if you have both on your system, you must build AirSim with VS 2017.

**Comment by sytelus** [comment]
I have both on my system and I use VS2015 without any change in build.cmd. I'm also able to build VS2017 without any change in build. The only thing is that you have to use "Developer command Prompt for VS 2017".

**Comment by Jazzinghen** [comment]
I have changed build.cmd, retargeted the library using Visual Studio and built from the Developer Command Prompt.
I should try your approach, maybe it would work out of the box.

**Comment by sytelus** [comment]
We will be upgrading to VS2017 in short order.
