### ISSUE TITLE
Reset doesn't work after simSetPose

### ISSUE THREAD

**Issue by younghj** [Microsoft/AirSim#596]
I followed this issue
https://github.com/Microsoft/AirSim/issues/553

But the difference is that in the above issue they execute the `moveToPosition` command, but I want to use the `simSetPose` command on the python client.

**Comment by younghj** [comment]
I may have a realization, but I will keep this issue open because I don't know if my hypothesis is true.

Is it that there are certain commands that are meant for computer vision mode and others for regular mode?

**Comment by sytelus** [comment]
Are you using reset in Computer Vision mode?
