### ISSUE TITLE
3 error in Simple flight Mode

### ISSUE THREAD

**Issue by winszenYoung** [microsoft/AirSim#598]
My Computer Environment Specific
Windows 10
Unreal Engine 4.16.3
Airsim commit a4190ac68764cdfd08ca68cbaf29a840cfc184e3
Json Settings 
"DefaultVehicleConfig": "SimpleFlight",
"PhysicsEngineName": "FastPhysicsEngine",

1.  It is not work ignore_collision in simSetPose.
    I try to  2 environment(One is just SimpleFlight the other is SimpleFlight & computer vision mode)
   My Python command 
  quat = client.getOrientation()
  client.simSetPose(Pose(Vector3r(0,0,4),quat), True)

  Ignore Collision is not work, So  Drone collision and stucks.

2. It is not work DrivetrainType.ForwardOnly option in moveByVelocity.
  I want the drones to move in the direction they camera see.
  So I use moveByVelocity & fowardOnly option.
  I rotate to yaw, And control drone, It move in direction first yaw.
  How do I control move in the direction camera see?

3. moveByVelocity is not work, after simsetpose.
    I try other command( moveByAngle, moveToPosition).
   Also dose not work, after simSetPose

  Python command
  quat = client.getOrientation()
  client.simSetPose(Pose(Vector3r(0,0,4),quat), True)
  client.moveByVelocity(1,0,0,1)

**Comment by olivia-skydio** [comment]
Any updates on this bug? I'm also facing this issue when trying to ignore collisions in computer vision mode.

**Comment by cangokalp** [comment]
Yeah, and I'm facing the the simSetPose issue as well. Once this command is issued, issuing other commands have no affect.

**Comment by saihv** [comment]
I have the same problem with the latest binaries.

**Comment by jonyMarino** [comment]
any update?

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem, and include the following (as requested when opening a bug issue)

*Make sure to write all reproduction steps
*Include full error message in text form
*Search issues for error message before filing an issue
*Attach a screenshot if applicable
*Include code to run if applicable

Thanks!
