### ISSUE TITLE
Place Multiple External Camera's in Environment

### ISSUE THREAD

**Issue by spencerh-b** [Microsoft/AirSim#599]
Is there any way to place an external camera and use it as the default camera. I have 40 drones flying separately and want to view them from an above vantage point. At a minimum I would like them to record what they see.

**Comment by sytelus** [comment]
You can use manual mode (press M). This causes camera to stop moving and you can control camera by arrow, page up/down and asdw keys.

**Comment by spencerh-b** [comment]
Yes, but is there currently a way to place cameras through out an environment and to have them record from there stationary position?

**Comment by spencerh-b** [comment]
Trying to set manual mode to the default in the settings.json triggers a break

**Comment by spencerh-b** [comment]
@sytelus But is there a way to place multiple stationary external camera's within an environment and have them record when the environment is started up?

**Comment by jmariscal-harana** [comment]
Hey, did you fix this in the end? Cheers!

**Comment by spencerh-b** [comment]
@jmariscal-harana I ended up just programing extra drones to stay stationary; however, I would love to see a working solution to stationary cameras. I have since dropped this as a focal point, but could utilize this work in the future.
