### ISSUE TITLE
boolean attribute error in navigate.py

### ISSUE THREAD

**Issue by raymondchua** [Microsoft/AirSim#602]
Hi,
I received this error while running the navigate.py file. 
How can I overcome this? 

I am using Python 3.5.4

woops - we are about to crash, so stopping!
Traceback (most recent call last):
  File "navigate.py", line 56, in <module>
    client.hover().get()
AttributeError: 'bool' object has no attribute 'get'

**Comment by sytelus** [comment]
I've fixed this but please note that this was very experimental script and work for it is in progress. Please feel free to contribute.

**Comment by raymondchua** [comment]
Thanks @sytelus . I will contribute whenever I can.
