### ISSUE TITLE
cannot run build.cmd

### ISSUE THREAD

**Issue by samquatched** [Microsoft/AirSim#604]
I've tried running "build.cmd" on Developer Command Prompt 2015 and VS2015 x64 Native Tools Command Prompt. I am using VS2015, CMake 3.9.5 and Windows 10. However, the build still fails. 

![builderror](https://user-images.githubusercontent.com/33424865/32604879-9442b728-c54f-11e7-82cd-a23e76d79ab3.png)

I've not modified the codes and followed the tutorials provided. Am I missing a file that I need to download or how can I rectify this?

**Comment by raymondchua** [comment]
Can you show the whole log?

**Comment by sytelus** [comment]
Yeah, please post whole build output.

`build > log.txt`

Also make sure you have VS2015 with Update 3.

**Comment by samquatched** [comment]
![error 1](https://user-images.githubusercontent.com/33424865/32648953-64ac6fd2-c5f8-11e7-8002-cb34ef2b3ff5.png)
![error 2](https://user-images.githubusercontent.com/33424865/32648954-64ce2f14-c5f8-11e7-93c2-62c0756aaa17.png)
![error 3](https://user-images.githubusercontent.com/33424865/32648955-64e4753a-c5f8-11e7-8485-95562767f51e.png)

Yes, I have VS2015 with update 3. Is this the log output?

**Comment by raymondchua** [comment]
@samquatched , why did you use screenshots? Can't you copy and paste the text from the log?

**Comment by samquatched** [comment]
@raymondchua  I don't have the log.txt file

**Comment by abc19850508** [comment]
you can try to use CMAKE 3.7
