### ISSUE TITLE
Get 3d Lidar data?

### ISSUE THREAD

**Issue by tejaskhot** [Microsoft/AirSim#605]
It seems like there is support for rgb and rgbd, but I am wondering how to get 3d lidar data.

**Comment by sytelus** [comment]
You can do it by doing ray tracing in Unreal Engine. See https://github.com/Microsoft/AirSim/issues/405#issuecomment-322132846

**Comment by sytelus** [comment]
Duplicate: https://github.com/Microsoft/AirSim/issues/621

**Comment by zhoudacheng6** [comment]
Hello，i want to know to get lidar data.I saw the getLidaData() function on the document, but I don’t know how to run it
