### ISSUE TITLE
msgpackrpc not communicating

### ISSUE THREAD

**Issue by Jaleyhd** [Microsoft/AirSim#609]
System configuration : Ubuntu 16.04, 64 bit. 
I have quoted the exact error log bellow. Any help or a hint would be appreciated.

WARNING:tornado.general:Connect error on fd 6: ECONNREFUSED

  File "camera.py", line 34, in <module>
    client.confirmConnection()
  File "/home/abc/AirSim/PythonClient/AirSimClient.py", line 160, in confirmConnection
    home = self.getHomeGeoPoint()
  File "/home/abc/AirSim/PythonClient/AirSimClient.py", line 169, in getHomeGeoPoint
    return GeoPoint.from_msgpack(self.client.call('getHomeGeoPoint'))
  File "/usr/local/lib/python3.5/dist-packages/msgpackrpc/session.py", line 41, in call
    return self.send_request(method, args).get()
  File "/usr/local/lib/python3.5/dist-packages/msgpackrpc/future.py", line 43, in get
    raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

**Comment by sytelus** [comment]
Are you running AirSim successfully? Looks like either its not running or its not allowed to open TCP/IP ports.

**Comment by Terrywjx** [comment]
I also encountered this problem...

**Comment by nibeh** [comment]
Are you using drone or car mode?

**Comment by Jaleyhd** [comment]
Car mode . I suspect that with Ubuntu, there will be issues. I  will get back to you with more details. For now, I am closing the issue

**Comment by srivatsankrishnan** [comment]
@crazymuse I am seeing the same issue. Did you root cause this issue?

**Comment by husha1993** [comment]
@crazymuse I am seeing the same issue. Did you root cause this issue?

**Comment by TritonSailor** [comment]
I also experienced this issue running PythonClient on ubuntu over ssh with UE4 running on another ubuntu machine.  Running PythonClient locally, or over ssh on a windows machine, the PythonClient worked normally.  

I solved this issue by running `pip install msgpack-rpc-python` on the ubuntu machine running the ssh client. The PythonClient is working over linux ssh for me now.

**Comment by sytelus** [comment]
Also see this: https://github.com/Microsoft/AirSim/issues/1141#issuecomment-399627155
