### ISSUE TITLE
location coordinates in unreal and airsim

### ISSUE THREAD

**Issue by raymondchua** [Microsoft/AirSim#611]
Hi, 
Is there a way to use the location information in Unreal for AirSim? How is the mapping like?
For example, I have a cone in Unreal at position 10,10,10. What values should I use so that my drone goes to the cone (10,10,10)? I have tried directly using 10,10,10 but it did not work.

**Comment by sytelus** [comment]
I have updated the doc here: https://github.com/Microsoft/AirSim/blob/v1.1.5/docs/apis.md#coordinate-system

**Comment by raymondchua** [comment]
@sytelus , Thanks! Works well!

**Comment by lucafei** [comment]
> @sytelus , Thanks! Works well!

Hello, @raymondchua i have also same problem with you, can you show me how to transfer the postion from ue enviroment to airsim api?

**Comment by datonefaridze** [comment]
@lucafei Hi did you mange to solve that? can you please help me?
