### ISSUE TITLE
Is there any way to get IMU data from python client?

### ISSUE THREAD

**Issue by zhukovv** [Microsoft/AirSim#612]
I'm able to get a pose with getPosition() and getOrientation(), but I can't find anything related to acceleration...

**Comment by sytelus** [comment]
We have added new APIs to get angular velocity (along with other kinematics quantities). Please see https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#getmultirotorstate.

For cars, this is available in getCarState API.
