### ISSUE TITLE
Problem : airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A irLib\AirLib.vcxproj]

### ISSUE THREAD

**Issue by tanmoy-sabir** [Microsoft/AirSim#613]
Hello.

I am facing these problem while compiling build.cmd in Visual Studio 2017 Tools Command Prompt.
I have no idea how to solve this problem.

DroneControllerBase.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
MultirotorRpcLibServer.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
MultirotorRpcLibClient.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
CarRpcLibServer.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
CarRpcLibClient.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
SafetyEval.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
ObstacleMap.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
RpcLibServerBase.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]
RpcLibClientBase.cpp
c:\git\airsim\airlib\include\common\vectormath.hpp(12): fatal error C1083: Cann
ot open include file: 'Eigen/Dense': No such file or directory [C:\Git\AirSim\A
irLib\AirLib.vcxproj]

**Comment by lovettchris** [comment]
try using "build.cmd" which will download the Eigen folder for you and put it in the right place.

**Comment by sytelus** [comment]
If you are using VS2017, please use this thread for further discussions: https://github.com/Microsoft/AirSim/issues/595

**Comment by wangshenfeng** [comment]
however， It doesn't work

**Comment by AloshkaD** [comment]
Copying Eigen manually into Airlib/include could help compiling airsim but causes issues later with compiling projects. To solve this issue I installed VS 2015 as a component in my VS 2017. See attached screenshot
![image](https://user-images.githubusercontent.com/10216145/41929558-4e7d99a0-792d-11e8-84e9-5fb3f0d55c4d.png)

**Comment by Nagule8** [comment]
I'am also having this issue pls help me.
![Screenshot (31)](https://user-images.githubusercontent.com/54871837/64217093-94bab580-ced9-11e9-9f4b-5757e4a99093.png)

**Comment by lloydrayner** [comment]
+1

**Comment by lovettchris** [comment]
Did you run "build.cmd" which downloads Eigen from http://bitbucket.org/eigen/eigen/get/3.3.2.zip ?

**Comment by caesar84** [comment]
hi there 
I am having the same problem even though I have tried both 
 x64 Native Tools Command Prompt for VS 2017
and 
Developer Command Prompt for VS 2017
![AirSim](https://user-images.githubusercontent.com/16879951/75302220-0c3c2280-5835-11ea-9da3-0900245adc5a.jpg)

**Comment by lovettchris** [comment]
run `build.cmd` to get Eigen downloaded properly.

**Comment by caesar84** [comment]
I am actually running it because I am following this guide [](https://microsoft.github.io/AirSim/docs/build_windows/)

**Comment by caesar84** [comment]
restarted the pc and it went well this time with build.cmd.

**Comment by yzexeter** [comment]
> Copying Eigen manually into Airlib/include could help compiling airsim but causes issues later with compiling projects. To solve this issue I installed VS 2015 as a component in my VS 2017. See attached screenshot
> ![image](https://user-images.githubusercontent.com/10216145/41929558-4e7d99a0-792d-11e8-84e9-5fb3f0d55c4d.png)

This solves my problem. I am using windows v1.3.1, and the "build.cmd" can not download Eigen from bitbucket. I checked the url provided by @lovettchris , not existing anymore.

To those who have the same trouble, go to Eigen official website and download it manually. Unzip it and copy the Eigen folder(which is located under the eigen-X.X.X, version num, folder) into Airlib/include directory. Done.

**Comment by CSUN1997** [comment]
I got the same issue and I found out that the bitbucket repo for Eigen has been moved to gitlab. Try change the link for Eigen to "https://gitlab.com/libeigen/eigen/-/archive/3.3.2/eigen-3.3.2.zip" and delete the cache and recompile.

**Comment by Shubhamn96** [comment]
So I am also running into this issue. I am installing on the C drive with Visual Studio 2019. It worked on my personal laptop but now that I am trying to install it on to my work machine, it isn't working. I get this error

![image](https://user-images.githubusercontent.com/34661796/114252433-1a82ca80-9973-11eb-99a1-1a254a50fb39.png)

**Comment by clovett** [comment]
Did you run "build.cmd" ?  build.cmd installs Eigen.

**Comment by eherozhao** [comment]
I am using VS2017 and cannot build the Block project successfully. When I run build.cmd, the result is

`Hello there! We just upgraded AirSim to Unreal Engine 4.24 and Visual Studio 2019.
Here are few easy steps for upgrade so everything is new and shiny:
https://github.com/Microsoft/AirSim/blob/master/docs/unreal_upgrade.md`

Looks like it doesn't download libs online. How should I work it with VS 2017?

**Comment by GhazalTajik1998** [comment]
So I had the same problem and was dealing with it for a day.I tried everything which is said here but none of them worked.


Then I used "x64 Native Tools Command Prompt for VS 2019" instead of "Developer Command Prompt for VS 2019" to run build.cmd.
it worked for me.

**Comment by azamkamranian** [comment]
just copy engine3.zip files into ```\AirSim\AirLib\deps\eigen3```

**Comment by Coinstine** [comment]
clear the cache(eigen3),and re-run build.cmd
