### ISSUE TITLE
Segmentation Issue in the Neighbourhood Environment

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#614]
Hey all, 

I have been trying to provide the segmentation labels for the `landscape` and `sky` objects in the Unreal Neighboorhood environment. However, I am unable to set them to distinct colors while using the recent python APIs. I am referring to the [`segmentation.py`](https://github.com/Microsoft/AirSim/blob/master/PythonClient/segmentation.py) to do the same. I suppose the reason for that is these are not static meshes in the environment which might be causing this issue.

It would great if someone could help me out with fixing this problem. Thank you in advance!

**Comment by sytelus** [comment]
This works to set color for sky:

```
found = client.simSetSegmentationObjectID("SkySphere", 42);
print("Done: %r" % (found))
```

**Comment by Mayankm96** [comment]
@sytelus 

Thank you for the assistance for setting the sky color. However, I am still unable give the `Landscape` in the Neighborhood Environment a color. It seems that the `Landscape` is a different kind of [mesh](https://docs.unrealengine.com/latest/INT/Engine/Landscape/Editing/SculptMode/index.html) due to which it appears transparent as shown below:
![issue](https://user-images.githubusercontent.com/12863862/33090702-eca68ef6-cf1a-11e7-8a8e-6a4281efac36.JPG)


For the scene input here:

![000002](https://user-images.githubusercontent.com/12863862/33090293-7b314618-cf19-11e7-8700-6ff0068084e4.png)

The segmented output that I get is:
![000002](https://user-images.githubusercontent.com/12863862/33090313-8b3da470-cf19-11e7-8971-5c83d36a44f2.png)
