### ISSUE TITLE
python program control error

### ISSUE THREAD

**Issue by PantelisKyriakidis** [Microsoft/AirSim#615]
Hello,

I installed msgpackrpc and first i opened airsim. 
Then I tried to run ''hello drone'' and i got this:
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from AirSimClient import *
ModuleNotFoundError: No module named 'AirSimClient'

And i just can't find a solution anywhere so I guess I am missing something.
Anyone who can help ?

**Comment by BrunoXL** [comment]
@PantelisKyriakidis  Have you solved it?

**Comment by PantelisKyriakidis** [comment]
yeah i don't remember exactly but i was missing some .py file because i didn't download it all together

**Comment by BrunoXL** [comment]
From where you downloaded the files? I `git clone` AirSim repository, so cannot be missing a file.

**Comment by PantelisKyriakidis** [comment]
hmm then it's not the same error. I downloaded from the repository too.
