### ISSUE TITLE
AirSim sometimes freezes and stops accepting further commands

### ISSUE THREAD

**Issue by valtsblukis** [Microsoft/AirSim#617]
I'm using API control from the Python client with SimpleFlight to control a drone on Ubuntu 16.04 and Unreal Engine 4.18.

I observe that occasionally (especially if AirSim is running in background) AirSim freezes and the drone stops moving with the following symptoms:
* RPC API calls still return successfully and in my case case SimpleFlightDroneController::commandVelocityZ gets executed successfully with the updated commands.
* Firmware::update inside Firmware.hpp stops being called, which means that the drone stays frozen in place.

As far as I can tell, the only way to recover from this is to restart Unreal. If this happens when running in the editor, then pressing "Stop" causes the editor to stop responding and it has to be sigkilled.

I can reproduce this problem by running "stress --cpu NUMCORES" to stress my CPU. It seems that AirSim not getting enough CPU time is what triggers this. Any ideas how to overcome this? It makes it impossible to leave AirSim running to collect a lot of data.

Edit:
I found the problem. TTimeDelta inside ScheduledExecutor.hpp is defined as a uint64 and line 142 causes integer underflow:
           ` TTimeDelta delay_nanos = period_nanos_ - elapsed_period;`

As a result, the ScheduledExecutor sleeps for a VERY long time.
This is easily fixed by adding the following lines to ScheduledExecutor.hpp:144:
```
            if (period_nanos_ < elapsed_period)
            {
              printf("Warning: ScheduledExecutor missed it's desired interval: %lu", period_nanos_);
              delay_nanos = 0;
            }
```

**Comment by sytelus** [comment]
This is a great bug report and thanks for the fix as well. I've added this fix in referenced commit.
