### ISSUE TITLE
Deep Learning example

### ISSUE THREAD

**Issue by mitchellspryn** [Microsoft/AirSim#620]
We need an example of how to use AirSim to train deep learning models. I already have an working model and dataset; the tutorial needs to be written. 

The PR should be submitted by Monday (11/18).

**Comment by sytelus** [comment]
Thanks for notifying. Looking forward to it.

**Comment by mitchellspryn** [comment]
[PR is up](https://github.com/Microsoft/AirSim/pull/624).

**Comment by mitchellspryn** [comment]
I've updated the PR with your suggestions.
