### ISSUE TITLE
Add ability to teleport car via Python API

### ISSUE THREAD

**Issue by mitchellspryn** [Microsoft/AirSim#623]
I'd like to have the ability to telemport my car via the python API. Something like 

car.move_to(location, velocity, orientation)

Where location and velocity are vector3s and orientation is a quaternion specifying the new location of the car. When called, this api would instantly move the car. For example, this would be useful for extending the RL training so that the car does not always start in the same place.

@sytelus - Does this API or suitable workaround already exist? If not, I will work on it once I resolve [the issue that I am currently working on.](https://github.com/Microsoft/AirSim/issues/620), and you can assign this issue to me.

**Comment by sytelus** [comment]
Yes, there is `simSetPose` API that takes position and orientation and transports the object. There is also reset() API that simply rests to start conditions.
