### ISSUE TITLE
Simulated Indoor environments?

### ISSUE THREAD

**Issue by alejodosr** [Microsoft/AirSim#625]
Hi all,

I've been playing with the AirSim, but I could not found the possibility of quadrotor navigation in an indoor environment, Is is possible to simulate photo-realistic indoor environments? Thanks in advance.

**Comment by sytelus** [comment]
There are bunch of photo-realistic environments available. For example [this one](https://docs.unrealengine.com/latest/INT/Resources/Showcases/RealisticRendering/index.html) is free. Also, look in to Unreal Marketplace.
