### ISSUE TITLE
Cannot get project to recognize plugin

### ISSUE THREAD

**Issue by rohanpai** [Microsoft/AirSim#633]
Hi all -- any idea why I can't build the project after following instructions here: https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md 

Here's the error dialogues that I see:
<img width="289" alt="1" src="https://user-images.githubusercontent.com/2272901/33227329-d999b2ec-d155-11e7-8dde-229fb2c6c4b0.PNG">
<img width="313" alt="2" src="https://user-images.githubusercontent.com/2272901/33227330-d9b2054a-d155-11e7-9b45-00bdb7b6a3d7.PNG">

Thanks!

I'm running Unreal 4.16.3

**Comment by rohanpai** [comment]
The problem is that I wasn't using a C++ project -- closing

**Comment by XinGao2017** [comment]
Hello , I have encountered the same problem , how do you solve this problem , Thanks !
