### ISSUE TITLE
Extending MultirotorClient python API 

### ISSUE THREAD

**Issue by DavidLSmyth** [Microsoft/AirSim#635]
Could I get some advice on how to extend the c++ MultiRotor code and then expose it to the python API? When running a demo I would like to be able to print informational messages to the Unreal viewport (example: moving to destination two). These messages would ideally be sent via the python API. I've modified MultirotorClient to contain the method:
```python
def print_to_viewport(self, message):
    self.client.call('printToViewport', message)
```
Which c++ files would I need to edit in the AirSim project to add the required functionality and register this as a valid API method via RPC? I've taken a look in AirLib/src/api and other folders and it's not clear exactly what needs to be done (I'm not experienced with c++)

**Comment by sytelus** [comment]
I've added this API (albeit with name `simPrintLogMessage`).  You can see documentation here:

https://github.com/Microsoft/AirSim/blob/master/docs/apis.md#common-apis

This commit demonstrates the changes needed to add new APIs:
https://github.com/Microsoft/AirSim/commit/f0e83c29e7685e1021185e3c95bfdaffb6cb85dc
