### ISSUE TITLE
Why it's blank

### ISSUE THREAD

**Issue by Zhao1ming** [Microsoft/AirSim#64]
I follow the steps and why it's blank?
![11](https://cloud.githubusercontent.com/assets/22132384/23378419/19ecfa2c-fd01-11e6-95d4-e2548d9771a1.png)

**Comment by lovettchris** [comment]
Please see my [new video ](https://youtu.be/1oY8Qu5maQQ) that shows the full Unreal setup from scratch.

**Comment by Zhao1ming** [comment]
Thank you @lovettchris . This question is my fault, I installed version 4.15. After uninstall 4.15 and install 4.14, it works. Then I will continue focus on the control problem.
https://github.com/Microsoft/AirSim/issues/71
