### ISSUE TITLE
How to add and control more than one agent

### ISSUE THREAD

**Issue by rajnishti** [microsoft/AirSim#643]
Hi I am doing path planning for multi vehicles using reinforcement learning. Can I add more than one agent in Unreal Engine environment?  If it is possible to add more agents in environment, then what are the changes that I should do.
Thanks

**Comment by sytelus** [comment]
For drones its possible right now (see [this doc](https://github.com/Microsoft/AirSim/blob/master/docs/multi_vehicle.md)). For cars, this is under works.

**Comment by saihv** [comment]
@sytelus Is that doc dated now? Because neither IsFpvVehicle nor VehicleConfigName are available for FlyingPawn

**Comment by DanielLSM** [comment]
@sytelus Any updates on controlling multiple cars?

**Comment by msb336** [comment]
Multiple car control is available as well. At this time, all vehicles in the scene must be the same simmode, but you can control multiple of whichever vehicle you choose.
