### ISSUE TITLE
Can only record from one camera at one view

### ISSUE THREAD

**Issue by tuzzer** [Microsoft/AirSim#644]
There are multiple cameras with multiple views. However, there doesn't seem to be any way to recording images from those other views and cameras.

**Comment by sytelus** [comment]
Yes, this feature is in works and would soon be available.

**Comment by sytelus** [comment]
The feature to record images from multiple cameras simultaneously is now available. You can, for example, record scene and depth images simultaneously. 

Please see the doc: https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#recording
