### ISSUE TITLE
Build FAILED error C2259: 'msr::airlib::RealMultirotorConnector': cannot instantiate abstract class

### ISSUE THREAD

**Issue by tuzzer** [Microsoft/AirSim#645]
Build FAILED.

"C:\Projects\Roadrunner-Project\AirSim\AirSim.sln" (default target) (1) ->
"C:\Projects\Roadrunner-Project\AirSim\DroneServer\DroneServer.vcxproj" (default target) (6) ->
(ClCompile target) ->
  c:\projects\roadrunner-project\airsim\droneserver\main.cpp(80): error C2259: 'msr::airlib::RealMultirotorConnector':
cannot instantiate abstract class [C:\Projects\Roadrunner-Project\AirSim\DroneServer\DroneServer.vcxproj]

**Comment by cangokalp** [comment]
I can't build either, getting the same error

**Comment by XZ616313296** [comment]
I can't perform the behind because of this step either~~I am a novice

**Comment by DavidLSmyth** [comment]
In AirLib/include/vehicles/multirotor/controllers/RealMultirotorConnector.hpp under public add the lines:
virtual void printLogMessage(const std::string& message, std::string message_param = "", unsigned char severity = 0) override
{
}

and then rebuild. See Pull request #638
