### ISSUE TITLE
add ‘\plugins\AirSim’ to UE project, some mistakes happened....  

### ISSUE THREAD

**Issue by XZ616313296** [Microsoft/AirSim#648]
Running G:/1/UE_4.14/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="G:/1/QGroundControl/airsim/airsim.uproject" -game -rocket -progress
Discovering modules, targets and source code for project...
Messages while compiling G:\1\QGroundControl\airsim\Intermediate\Build\BuildRules\airsimModuleRules.dll:
g:\1\QGroundControl\airsim\Plugins\AirSim\Source\AirSim.Build.cs(43,53) : error CS0246: δ???ҵ????ͻ??????ռ????ơ?ReadOnlyTargetRules??(?Ƿ?ȱ?? using ָ???????????????)
g:\1\QGroundControl\airsim\Plugins\AirSim\Source\AirSim.Build.cs(72,19) : error CS0246: δ???ҵ????ͻ??????ռ????ơ?ReadOnlyTargetRules??(?Ƿ?ȱ?? using ָ???????????????)
g:\1\QGroundControl\airsim\Plugins\AirSim\Source\AirSim.Build.cs(94,39) : error CS0246: δ???ҵ????ͻ??????ռ????ơ?ReadOnlyTargetRules??(?Ƿ?ȱ?? using ָ???????????????)
g:\1\QGroundControl\airsim\Plugins\AirSim\Source\AirSim.Build.cs(118,39) : error CS0246: δ???ҵ????ͻ??????ռ????ơ?ReadOnlyTargetRules??(?Ƿ?ȱ?? using ָ???????????????)
g:\1\QGroundControl\airsim\Plugins\AirSim\Source\AirSim.Build.cs(124,87) : error CS0246: δ???ҵ????ͻ??????ռ????ơ?ReadOnlyTargetRules??(?Ƿ?ȱ?? using ָ???????????????)
UnrealBuildTool Exception: ERROR: UnrealBuildTool encountered an error while compiling source files

I used VS2015 community...
Did it happen in the link of compiling?my compiling finished very quickly in the end, and I can't even see the result...  do I need to change the VS ?PS:I have install the "eigen" and "boost" and change the mistake of 'quotation mark'.
willing to take advice.

**Comment by sytelus** [comment]
You are using Unreal 4.14 which we don't support. Please use UE 4.16 and refer to build doc.
