### ISSUE TITLE
RC controller on USB not detected：4294967295

### ISSUE THREAD

**Issue by XZ616313296** [Microsoft/AirSim#651]
After follow the 'readme' ,I set up the Frame type as ‘simulation/HIL Quadrocopter X’ in QGC. T

'Created setting file at C:\...\setting.json
Default config: simple flight
  RC controller on USB not detected：4294967295      
API server started at(default)
collision count :4
...'
show on the engine of Unreal Engine 4.

Is this Caused by the Frame type？What is the meaning of 4294967295？ In this kind of frame type ，I can‘t find the Position and Attitude  calibration in QGC ，and the ESC calibration never work connecting with USB.

PS：I want to change the parameters in PID or another  control algorithm，is there any Matters needing attention?

**Comment by sytelus** [comment]
The "RC controller on USB not detected:" message just means that you don't have remote control connected to USB port ([see doc](https://github.com/Microsoft/AirSim/blob/master/docs/remote_control.md)). If you are using PX4 then don't worry about it.
