### ISSUE TITLE
Frequent Disconnection on MultirotorClient

### ISSUE THREAD

**Issue by maximilianchang** [Microsoft/AirSim#654]
I am running the neighborhood environment in AirSim and having a Multirotor Client do a random walk in the environment. I find that the drone will often stop responding to commands with the requests timing out. I am wondering if anyone else has encountered a similar issue. 

I am running on Windows environment.

**Comment by sytelus** [comment]
Are you using default simple_flight or PX4? Could you please give any script that helps reproduce your issue? I would be also interested in knowing your machine config (GPU, CPU, RAM).

**Comment by maximilianchang** [comment]
I'm using simple_flight and doing a simple random walk (i.e. making calls to _moveToPosition(current_position.x_val + randint(0, 5), current_position.y_val + randint(0, 5), current_position.z_val, 5)_ ). 

I'm using a GPU (NVIDIA Tesla M60) with 8GiB of GPU memory. More specifically, this is the G3 Instance Type offered on AWS.

**Comment by sytelus** [comment]
Please provide full code to reproduce this issue. When running locally, I'm not seeing this issue so I think this might be more related to your AWS setup.
