### ISSUE TITLE
Some questiones about multi-cars controller .

### ISSUE THREAD

**Issue by 18605973470** [Microsoft/AirSim#667]
I want to train my autonomous drving model under a specific scenario in which a car follows a vehicle platoon.
And I have to construct this scenario.
So I want to know if it is easy to control multi-cars in AirSim. ( The last one is controlled by trained model and the platoon is controlled by a simple program whose aim is going straight forward.

Any suggestions would be appreciated !

**Comment by sytelus** [comment]
I think what you want to have is many cars which simply has car meshes (i.e. no physics or simulation). Then you can use vehicle "AI" which is built-in to Unreal to move those cars around ([see here](https://forums.unrealengine.com/community/community-content-tools-and-tutorials/11886-updated-5-16-a-i-templates-bot-car-flying-ai?25073-UPDATED-5-16-A-I-Templates-Bot-Car-amp-Flying-AI=)). There is also something called "spline" that you can draw in environment where vehicle will move on. See below for tutorials:

https://www.youtube.com/watch?v=wR0fH6O9jD8

https://www.youtube.com/watch?v=FVyUVJra3KI
