### ISSUE TITLE
in which frame is reportState reporting?

### ISSUE THREAD

**Issue by abdelrahman-t** [Microsoft/AirSim#671]
reporter.writeValue("Lin-Vel", current_.twist.linear);
        reporter.writeValue("Lin-Accl", current_.accelerations.linear);
        reporter.writeValue("Ang-Vel", current_.twist.angular);
        reporter.writeValue("Ang-Accl", current_.accelerations.angular);

could you please verify which frame are these reported values in?

**Comment by sytelus** [comment]
Linear quantities are in world frame while the angular quantities are in body frame. The coordinate system is NED, all units are SI.

**Comment by abdelrahman-t** [comment]
@sytelus thank you!
