### ISSUE TITLE
get back controls of the car

### ISSUE THREAD

**Issue by Jacquesval** [microsoft/AirSim#682]
Hello,
I wanted to know if it's possible to get back the CarControls() variables (throttle, steering, brake) when the user is controlling the vehicle. I need them to make an imitation learning algorithm.

**Comment by sytelus** [comment]
This is good feature. I've put this in backlog.

**Comment by Jacquesval** [comment]
Hi,
I just wanted to know if you have implemented this option already ?
(By the way, what is backlog, I'm not very familiar with github ?)

**Comment by Beijingsheng** [comment]
Has this problem been solved? I'm also curious about this function, it's truly useful for RL.

**Comment by SoftArch** [comment]
Hi,
This feature is implemented?
Have any info when it will implement?

**Comment by Gaduu** [comment]
Any updates on that?

**Comment by msb336** [comment]
`simGetCarControls` is now implemented.
