### ISSUE TITLE
Hyperlink Broken in "Download Binaries" Documentation

### ISSUE THREAD

**Issue by TalatCikikci** [Microsoft/AirSim#683]
The hyperlink for **"APIs"** is broken in "_AirSim/docs/use_precompiled.md_" file. 

It is currently pointing to _"https://github.com/Microsoft/AirSim/blob/master/docs/docs/apis.md"_ whereas it should actually point to _"https://github.com/Microsoft/AirSim/blob/master/docs/apis.md"_.

**Comment by sytelus** [comment]
Fixed.
