### ISSUE TITLE
AirSim with Qt

### ISSUE THREAD

**Issue by plewastefan** [Microsoft/AirSim#684]
Is there any possibility to generate the project files with qt using the uPro Generator?

https://github.com/nibau/Unreal-Qt-project-generator

I built the AirSim successfully but when I try to "Generate Visual Studio Project Files" , as explained in step 5 of the instrucctions: 
https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md

I receive the error:  "Couln't set association for project. Check the file is writeable".
Neither inside the Unreal Engine nor in qt I am not longer able to open the project.

Configuration:
Windows 7
Unreal Engine 4.16
VS Compiler
Cmake 3.7
Windows SDK 8.1

**Comment by sytelus** [comment]
This is Unreal specific issue. You might want to report it here: https://answers.unrealengine.com/index.html
