### ISSUE TITLE
Error building AirSim with UE-4.18.2, Intermediate/Build/../Development/AirSim folder is empty

### ISSUE THREAD

**Issue by edowson** [Microsoft/AirSim#689]
I get the following error while trying to build the latest version of AirSim with UE-4.18.2 release:

```
@progress 'Compiling C++ source code...' 0%
[2/4] Compile Module.AirSim.gen.cpp
[1/4] Compile Module.AirSim.cpp
clang-5.0: error: no such file or directory: '/project/software/tutorial/airsim/airsim_quadrotor_lm/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.gen.cpp'
clang-5.0: error: no input files
clang-5.0: error: 
no such file or directory: '/project/software/tutorial/airsim/airsim_quadrotor_lm/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp'
clang-5.0: error: no input files
@progress 'Compiling C++ source code...' 20%
@progress 'Compiling C++ source code...' 60%
ERROR: UBT ERROR: Failed to produce item: /project/software/tutorial/airsim/airsim_quadrotor_lm/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so
Total build time: 31.67 seconds (Local executor: 0.00 seconds)
```

I built AirSim on CentOS-7.4 with Clang-5.0.1 normally and copied the plugins to the UE project folder. After trying to run the UE project, it gives the above error. 

The Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim is *empty*. 

What could the reason be?

Update: I reverted back to using UE-4.18.1 release and the directory contains the required files. This appears to be a regression issue with UE-4.18.2.

**Comment by sytelus** [comment]
Thanks for letting us know about UE-4.18.2 issue. We are currently supporting 4.17 officially but planning to upgrade to 4.18 pretty soon.
