### ISSUE TITLE
How to run a AirSim project with UnrealEngine?

### ISSUE THREAD

**Issue by LeonardLee** [Microsoft/AirSim#691]
HI,

I am using Ubuntu16.04.
I have build airsim project with Cmake, Such as "Hello car",
The output binary in cmake/output/bin folder.
When it run, display like this:
Make sure settings.json has "SimMode"="Car" at root. Press Enter to continue.
Waiting for connection - XXXXXXXXX
So, I don`t know how to use it, And I can`t find any tutorial for it, Thank you

**Comment by sytelus** [comment]
Read the docs :)
https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md
