### ISSUE TITLE
Build error on Windows 10

### ISSUE THREAD

**Issue by MeditationG** [Microsoft/AirSim#692]
**
Updating submodules...
Starting cmake...
-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.15063.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    用于 .NET Framework 的 Microsoft (R) 生成引擎版本 15.5.180.51428
    版权所有(C) Microsoft Corporation。保留所有权利。

    生成启动时间为 2017/12/18 23:25:36。
    节点 1 上的项目“C:\Users\DO IT\source\AirSim\external\rpclib\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标)。
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: 无法找到 v140 的生成工具(平台工具集 =“v140”)。若要使用 v140 生成工具进行生成，请安装 v140 生成工具。或者，可以升级到当前 Visual Studio 工具，方式是通过选择“项目”菜单或右键单击该解决方案，然后选择“重定解决方案目标”。 [C:\Users\DO IT\source\AirSim\external\rpclib\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj]
    已完成生成项目“C:\Users\DO IT\source\AirSim\external\rpclib\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标)的操作 - 失败。

    生成失败。

    “C:\Users\DO IT\source\AirSim\external\rpclib\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj”(默认目标) (1) ->
    (PlatformPrepareForBuild 目标) ->
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Platform.targets(57,5): error MSB8020: 无法找到 v140 的生成工具(平台工具集 =“v140”)。若要使用 v140 生成工具进行生成，请安装 v140 生成工具。或者，可以升级到当前 Visual Studio 工具，方式是通过选择“项目”菜单或右键单击该解决方案，然后选择“重定解决方案目标”。 [C:\Users\DO IT\source\AirSim\external\rpclib\build\CMakeFiles\3.10.1\VCTargetsPath.vcxproj]

        0 个警告
        1 个错误

    已用时间 00:00:00.70

  Exit code: 1
**

I'm using VS2017

**Comment by sytelus** [comment]
This is because you are using VS2017 and the cmake is looking for build tools that came with VS2015. The easiest way to solve this is by installing VS2015 Update 3. Other way is by modifieng cmake to use VS2017 build tools. We are also planning to upgrade AirSim to VS2017 anyway very soon.

**Comment by IeiuniumLux** [comment]
I just clone the master repo and I'm still getting the MSB8020 errors, did you update AirSim to VS2017?
