### ISSUE TITLE
Is there a SensorCollection equivalent object for the car?

### ISSUE THREAD

**Issue by rohanpai** [microsoft/AirSim#693]
I've noticed based on the way the project is organized that there the SensorCollection.hpp/MultiRotorParams.hpp files primarily supports the drone -- is there an equivalent file for the car? In other words, if I wanted to add a new sensor for the car, what would the best file to add this code be in?

**Comment by sytelus** [comment]
This is in works right now... hopefully will get it very soon!

**Comment by madratman** [comment]
this was added but issue was not closed
