### ISSUE TITLE
Windows 10 with driver signature enforcement

### ISSUE THREAD

**Issue by Zhao1ming** [Microsoft/AirSim#71]
The driver of PX4 can not work in Win 10

**Comment by lovettchris** [comment]
What error are you seeing?  We are using http://qgroundcontrol.com/ which bundles a px4 driver that works on windows 10.  Can you try qgroundcontrol and see if it will connect to your pixhawk ?

**Comment by Zhao1ming** [comment]
Yeah, I use it ,but when I plug in the pixhawk by USB port, there is nothing happened. It looks like the driver can not work. QGC can not automatically respond to the pixhawk.

**Comment by Zhao1ming** [comment]
![1554709051](https://cloud.githubusercontent.com/assets/22132384/23486577/efb4b07e-feae-11e6-8e08-112d4ca5b7a8.jpg)

**Comment by Zhao1ming** [comment]
![700907177](https://cloud.githubusercontent.com/assets/22132384/23486582/f589ea32-feae-11e6-93c4-4835b3644a08.jpg)

**Comment by lovettchris** [comment]
Hmmm, ok, do you hear USB sounds from Windows saying it recognizes your device? And do you see a new device show up in Device Manager under Ports (COM & LPT), like this?  If you don't hear a sound, try a different USB cable (you might have a power only cable instead of a data cable?).

![devices](https://cloud.githubusercontent.com/assets/18707114/23487891/fc4e595e-fe9d-11e6-95f0-80de324d1c09.png)

**Comment by Zhao1ming** [comment]
![image](https://cloud.githubusercontent.com/assets/22132384/23488123/a2c4e8e2-feb8-11e6-8679-0ad372b37b44.png)

**Comment by Zhao1ming** [comment]
I can hear the voice of the machine, but there is nothing about the system. Looks like no driver

**Comment by lovettchris** [comment]
Interesting.  I have not tried that particular hardware, perhaps it needs to have the firmware flashed.  See the video on this page for initial configuration including [updating the firmware](https://dev.px4.io/starting-initial-config.html).   Now you also will need to install the [PX4 version 1.4.4](https://github.com/PX4/Firmware/releases/tag/v1.4.4).
