### ISSUE TITLE
Low fps with many cameras

### ISSUE THREAD

**Issue by anders-hopland** [Microsoft/AirSim#717]
I am building a simulator which is using 5 cameras. TThe framerate is around 30fps while rendering to screen, but when I´m sending it to the decision making engine, I can only get out 4fps. I think the bottleneck is moving data from GPU to CPU memory. Have someone encountered a similar problem, or have any ideas on how to solve this. 

Thanks for your help!

**Comment by anders-hopland** [comment]
I'm using a GTX1070 on windows in a small environment. The cameras are 720p each.

**Comment by anders-hopland** [comment]
Are you referring to the Airsim API or the in game FPS? Do you know about any "hacky" solutions?

**Comment by sytelus** [comment]
I would suggest first try out 5 cameras with lower resolution (default). If that doesn't work then you have bigger issue. Then try to reduce cameras from 5 to 4 to 3. See which config gives you reasonable FPS. I'm able to use 3 cameras comfortably on TitanX in Blocks environment at default res.

**Comment by sytelus** [comment]
We have some good proposals here: https://github.com/Microsoft/AirSim/issues/796

We'll continue discussion in above thread.
