### ISSUE TITLE
Prebuild Binaries Segmentation

### ISSUE THREAD

**Issue by moritzlbr** [Microsoft/AirSim#718]
My issue is similiar to this question: https://github.com/Microsoft/AirSim/issues/702

I'm trying to get a set of two images ("scene" and "segmentation") from the city environment binaries v1.1.7. I'm using Windows 7 Enterprise and Unreal Engine 4.16.3.
However the segmentation won't change to different colors.

Here's what I get:
![92py-0-20180103-171827](https://user-images.githubusercontent.com/34275904/34528929-bf2d87a2-f0aa-11e7-91a5-031c75a764d3.png)
![93py-5-20180103-171827](https://user-images.githubusercontent.com/34275904/34528930-bf533ef2-f0aa-11e7-8b90-7d1b0078a084.png)

I tried using the following code though nothing changed:
_client.simSetSegmentationObjectID("[\w]*", 0, True)
client.simSetSegmentationObjectID("ground[\w]*", 1, True)
client.simSetSegmentationObjectID("road[\w]*", 2, True)
client.simSetSegmentationObjectID("sky[\w]*", 3, True)
client.simSetSegmentationObjectID("car[\w]*", 4, True)
client.simSetSegmentationObjectID("sign[\w]*", 5, True)_

_images = client.simGetImages([
            ImageRequest(0, AirSimImageType.Scene),
            ImageRequest(0, AirSimImageType.Segmentation)
            ])_

I'm not sure if I got the names of all the meshes' stencils right, that might already be the problem.
Could you publish the stencils' names for the released environments?
Or do you have any idea what else could have gone wrong?

Thanks for your help!

**Comment by sytelus** [comment]
In current beta we had to turn off setting initial object IDs in city environment because of perf issue (the environment is very large). I'm looking in to a workaround and will enable it again soon...

**Comment by moritzlbr** [comment]
Thanks for your answer!
Than I'll patiently wait until you've found a solution.
