### ISSUE TITLE
Px4 unreal  freezes everytime when exiting the simulation

### ISSUE THREAD

**Issue by geevargs** [microsoft/AirSim#719]
It doesn't seem to leave any trace in the terminal as where it fails.
I am not using the sitl but just remote control,it crashes every time I try to stop the simulation and freezes the entire  screen..
OS : Linux 14.04
Unreal version 4.17.2
Latest Airsim version

[PX4.log](https://github.com/Microsoft/AirSim/files/1602328/PX4.log)

**Comment by sytelus** [comment]
This is hard to debug issue and I haven't tried out this specific confi (sitl + RC) on Linux. If possible you might want to switch to Ubuntu 16.04. You might also want to try eliminate as many variables as you can and create a simplest test case to reproduce the issue. For example, does the same thing happen if you use default simple_flight? Does it happen if there is no RC? Does it happen with HITL? Also, look in to Saved folder which might have additional logs. The final way to debug these type of issues is [attach gdb](http://dirac.org/linux/gdb/06-Debugging_A_Running_Process.php) and break to see call stack to figure out where freeze is happening.

**Comment by kjetilkjeka** [comment]
I have the exact same problem on Ubuntu 16.04 LTS and UE version 4.16, 4.17 and 4.18 (Airsim 1.1.7).

**Comment by NihalKarne** [comment]
This issue is similar to : 
Px4 stil crash #634

I am also facing the same problem.

**Comment by sytelus** [comment]
We won't be able to work on PX4 related issues for some time. I would suggest to use above debugging tips and see if you find anything. It would be great to have contribution to fix this issue!

**Comment by geevargs** [comment]
@sytelus  I don’t use the Sitl and RC combo.I use RC using AirSim and send Telemetry data through a separate FDM source to different actors in unreal engine.But even when I stop using FDM it still fails on ending the simulation.
I eliminated everything and just used an empty scenario and put a BP_Flying pawn in there and still cause an error on exit.
This error has happened on multiple systems one 14.04 and the other 16.04.
This error does not occur during Simple_Flight and any other mode.If there is no RC then it deosnt crash.
This error happens in HITL mode with Quadcopter X firmware.
I checked the log files and it abruptly stops logging on exit and crashes completely.

**Comment by gzhang8** [comment]
We can confirm that we have the same issue when using RC + PX4 HITL + Ubuntu 16.04

**Comment by nicovanduijn** [comment]
Same issue here:
PX4 (1.8), SITL, Ubuntu 16.04

**Comment by clovett** [comment]
This [Pull Request](https://github.com/Microsoft/AirSim/pull/1635) fixes the issue.
