### ISSUE TITLE
update_from_git.sh fails.

### ISSUE THREAD

**Issue by ssashir06** [Microsoft/AirSim#723]
The shell script update_from_git.sh in Blocks fails because it says "No such file or directory".
I think rsync has wrong arguments, and fixing it works fine.

The environment I have checked is ubuntu 16.04.  How is it working in another environment?
In addition, on the macOS, rsync creates the missing directory automatically and copies some files in wrong location.

**Comment by sytelus** [comment]
What is the fix you made?

**Comment by ssashir06** [comment]
Currently, the DEST argument of rsync has "AirSim" path. And also, the SOURCE argument has "AirSim" too. This will makes being copied file will be placed in "AirSim/AirSim" if this path exists.

Could you please see a new pull request I created?
Thank you.
