### ISSUE TITLE
memoryerror appeared when running the DQNcar.py

### ISSUE THREAD

**Issue by Mikemraz** [Microsoft/AirSim#725]
when opening the neighborhood environment and running AirSim/PythonClient/DQNcar.py, a memoryerror appeared:
![image](https://user-images.githubusercontent.com/12424274/34691715-7e7e353c-f48b-11e7-8b3d-20b13b29a622.png)

my python's version is 
![image](https://user-images.githubusercontent.com/12424274/34691758-a99b7a22-f48b-11e7-910f-bbc843380856.png)

Can anyone help me out?

**Comment by sytelus** [comment]
There was a runtime error in DQNcar.py because of interface change which I just fixed in reference commit. After this fix, I'm not seeing any memory issues. Do you encounter above issue right away or after sometime? In any case, please try out new version.

**Comment by yujianyuanhaha** [comment]
I met the error again.  

``` bash
/home/jet/anaconda3/envs/py2/lib/python2.7/site-packages/cntk/cntk_py_init.py:47: UserWarning: Unsupported Linux distribution (ubuntu-18.04). CNTK supports Ubuntu 16.04 and above, only.
  warnings.warn('Unsupported Linux distribution (%s-%s). CNTK supports Ubuntu 16.04 and above, only.' % (__my_distro__, __my_distro_ver__))
Connected!
Client Ver:1 (Min Req: 1), Server Ver:1 (Min Req: 1)

Traceback (most recent call last):
  File "DQNcar.py", line 505, in <module>
    agent = DeepQAgent((NumBufferFrames, SizeRows, SizeCols), NumActions, monitor=True)
  File "DQNcar.py", line 270, in __init__
    self._memory = ReplayMemory(memory_size, input_shape[1:], 4)
  File "DQNcar.py", line 35, in __init__
    self._states = np.zeros((size,) + sample_shape, dtype=np.float32)
MemoryError
```

**Comment by Curry30h** [comment]
I also encountered the same problem. Is there a solution?
