### ISSUE TITLE
How can I change the speed of drones in Computer vision mode?

### ISSUE THREAD

**Issue by saihv** [Microsoft/AirSim#729]
In Computer vision mode, the drones can be moved with the same keys as in the manual camera mode: how can I change the speed of this movement?

**Comment by saihv** [comment]
Figured it out, I needed to change the scaling factor (default value 1000) on [line 116 of ManualPoseController.cpp](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/ManualPoseController.cpp#L116)

**Comment by chickenbestlover** [comment]
That's exactly what I was looking for. Thank you very much!

**Comment by rajrana22** [comment]
When I change the speed_scaler value, nothing changes. I'm still moving at the same speed (which is too fast) no matter what I change or how much I change it by.

**Comment by rajrana22** [comment]
What exactly is the "speed_scaler" value measured in? I know that AirSim uses SI units and Unreal Engine uses cm, but neither of those would make sense as values (too large). Is it meters per second? Is it cm per second? Or is it not a speed but an absolute distance moved with each press of the forward button?

**Comment by jonyMarino** [comment]
answered here https://github.com/microsoft/AirSim/issues/3783#issuecomment-875938514
