### ISSUE TITLE
How to get access to one of the video streams

### ISSUE THREAD

**Issue by mrRedDead98** [Microsoft/AirSim#737]
Hey there, is it possible to access the video streams which you can activate on pressing 1, 2 or 3 for example if you want to access the live stream in fpv from an external computer.  I've looked in MavLinkVideoStream.cpp but it is to complicated for me. Hope you can help.

**Comment by saihv** [comment]
You can 'stream' the camera images using code like the one in the [camera example script](https://github.com/Microsoft/AirSim/blob/master/PythonClient/camera.py)

**Comment by mrRedDead98** [comment]
Is there a possibility to transport over the Real Time Streaming Protokoll?

**Comment by sytelus** [comment]
No, we don't support this.
