### ISSUE TITLE
Should AirLib and MavLinkCom be built together with the unreal project?

### ISSUE THREAD

**Issue by kjetilkjeka** [Microsoft/AirSim#740]
If I've understood the building stages correctly MavLinkCom and AirLib is built prior to "copying" the plugin into the project folder. This means that static libraries need to be checked into VC and cross platform development (Win/Linux) require some jumping through hoops.

Would it be possible to build AirLib when the project is built instead?

**Comment by sytelus** [comment]
There are two static libraries you need to build the plugin: (1) MavLinkCom (2) rpclib. It is easy to build MavLinkCom (with appropriate changes in build.cs). However I haven't been able to build rpclib along with Unreal plugin yet. You are welcome to contribute in this area :).
