### ISSUE TITLE
Depth maps extraction

### ISSUE THREAD

**Issue by badabook** [Microsoft/AirSim#743]
Hi everyone, I have a couple of troubles. I premise that I use AirSim after running a prebuilt environment (such as neighborhood), so I don't work "directly" with unreal. 

1_ I know there is now an update that should allow me to record depth map data directly instead of scene images, but when I change the json file (the following) the recording action continues to work by default, and I can't explain why:

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "LocalHostIp": "127.0.0.1",
  "LogMessagesVisible": true,
  "SimpleFlight": {
    "FirmwareName": "SimpleFlight",
    "DefaultVehicleState": "Armed",
    "RC": {
      "RemoteControlID": 0,
      "AllowAPIWhenDisconnected": false,
      "AllowAPIAlways": true
    },
    "ApiServerPort": 41451
  },
  "Recording": {
    "RecordOnMove": false,
    "RecordInterval": 0.05,
    "Cameras": [
		  { "CameraID": 4, "ImageType": 0, "PixelsAsFloat": false, "Compress": true },
		  { "CameraID": 0, "ImageType": 3, "PixelsAsFloat": false, "Compress": true }
	  ]
  },  
  "SubWindows": [
    {"WindowID": 0, "CameraID": 0, "ImageType": 3, "Visible": false},
    {"WindowID": 1, "CameraID": 0, "ImageType": 0, "Visible": false},
    {"WindowID": 2, "CameraID": 0, "ImageType": 5, "Visible": false}    
  ],
  "CaptureSettings": [
    {
      "ImageType": 0,
      "Width": 640,
      "Height": 480
    },

    {
      "ImageType": 1,
      "Width": 640,
      "Height": 480,
	  "FOV_Degrees": 90,
      "AutoExposureSpeed": 100,
      "AutoExposureBias": 0,
      "AutoExposureMaxBrightness": 0.64,
      "AutoExposureMinBrightness": 0.03,
      "MotionBlurAmount": 0,
      "TargetGamma": 1.0
    },

    {
      "ImageType": 2,
      "Width": 640,
      "Height": 480,
	  "FOV_Degrees": 90,
      "AutoExposureSpeed": 100,
      "AutoExposureBias": 0,
      "AutoExposureMaxBrightness": 0.64,
      "AutoExposureMinBrightness": 0.03,
      "MotionBlurAmount": 0,
      "TargetGamma": 1.0
    },
	
	{
      "ImageType": 3,
      "Width": 640,
      "Height": 480,
	  "FOV_Degrees": 90,
      "AutoExposureSpeed": 100,
      "AutoExposureBias": 0,
      "AutoExposureMaxBrightness": 0.64,
      "AutoExposureMinBrightness": 0.03,
      "MotionBlurAmount": 0,
      "TargetGamma": 1.0
    },

    {
      "ImageType": 4,
      "Width": 640,
      "Height": 480
    },

    {
      "ImageType": 5,
      "Width": 640,
      "Height": 480
    },
	
	{
      "ImageType": 6,
      "Width": 640,
      "Height": 480
    }

  ]
}

```

2_ By the way I prefere getting data via APIs.  I work in python, and I would like to extract depth map images like the ones showed when you press "0", but I obtain this kind of picture:

![py1](https://user-images.githubusercontent.com/35538685/35059306-f91f9f98-fbba-11e7-99dd-0537f85e85ea.png)

3_ My last question concerns the three different kinds of depth images (DepthVis - DepthPerspective - DepthPlanner), I have read the documentation, but I still do not know what the difference is between them.

can anyone help me fixing these problems? Thanks in advice

**Comment by sytelus** [comment]
Not sure what 1st question means. Please try out new release.

There is docs, example as well as issues - if you search - that tells you how to retrieve depth image as floats array or RBG. The image you see on screen is depth visualization that you can get by DepthVis. Again please read the docs and search issues for more info.

See this: https://github.com/Microsoft/AirSim/issues/778
