### ISSUE TITLE
Error at startup: Invalid argument: iostream stream error

### ISSUE THREAD

**Issue by AemaH** [Microsoft/AirSim#744]
Hi, I try to create Unreal Environment like the [tutorial doc](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md), but I ran into this error.![](https://ws1.sinaimg.cn/large/005A8OOUly1fnkn9kh6jfj318p0o6jvg.jpg)
OS is win7, and I use the VS2015 update3
How should I solve this problem?
Thanks very much!!

**Comment by mchen0037** [comment]
Did you try some of the suggestions on https://github.com/Microsoft/AirSim/issues/735 ?

**Comment by sytelus** [comment]
I found the issue and its now [fixed](https://github.com/Microsoft/AirSim/commit/065ad2b3312b78350ec252d6842e5d6748e1e7d0) in master branch. The problem was occuring if you already did not have settings.json.

**Comment by asimonov** [comment]
I have this latest change but still see the error. where settings.json should be? and how is it created? I cannot seem to find it

**Comment by SamHS-OCI** [comment]
I am having the same error, but when I try to run from the provided binaries. What am I doing wrong?
