### ISSUE TITLE
Cannot compile latest as well as v1.1.7 release on windows

### ISSUE THREAD

**Issue by SweetShot** [Microsoft/AirSim#748]
Hello, 
I am pretty sure its some small thing but i am constantly getting this specific error while trying to build rpclib.
![capture](https://user-images.githubusercontent.com/9025943/35216586-18a9a9a4-ff8e-11e7-93f2-c23d3c11536d.PNG)

Thanks a lot

**Comment by sytelus** [comment]
I'm thinking you have some sort of mixed code from old and new release. Last week we removed rpclib as submodule and instead we now download it from GitHub releases as part of the build. I've tested this on couple machines and it should be working fine. I would suggest, try running g`it clean -fdx` followed by `git pull` and then `build`.

**Comment by SweetShot** [comment]
Hello,
I re-downloaded entire project now and tried again now, i am getting another error now, I have VS17 installed, will that be the culprit ? should i install VS15 too ?
![capture](https://user-images.githubusercontent.com/9025943/35318386-2442896a-0101-11e8-8082-d3498b289a04.PNG)
Thank you

**Comment by sytelus** [comment]
Could you run `git clean -fdx`, `clean.bat` followed by `build.bat`? As you now have VS2015, please make sure to run this from VS2015 x64 Native Tools Command Prompt.

**Comment by SweetShot** [comment]
Thanks a lot !!
It worked correctly in VS2015 x64 Native Tools Command Prompt. Quite interested in this project :D will have an amazing time with it.
Closing
