### ISSUE TITLE
Makefile:252: recipe for target 'CrashReportClient-Linux-Shipping' failed

### ISSUE THREAD

**Issue by mashrin** [Microsoft/AirSim#750]
Getting this error while executing "make" command.

OS - Ubuntu 17.10
Running Unreal 4.17

**Comment by mashrin** [comment]
Fixed it.
This helped:

$ chown -R user: filepath //mention user and the path to the directory
$ su user
$ make

Do not use 'sudo' or 'root user' while executing make command as it leads to another error where it shows:
"Refusing to run with the root privileges."

Can be closed now.

**Comment by pbasson** [comment]
I can confirm this issue resolves the Unreal Engine make error.

**Comment by XiongDuan** [comment]
”I can confirm this issue resolves the Unreal Engine make error.“
============================================
It happened to me, too. Just resolve it by this case.

**Comment by Curry30h** [comment]
“”user: filepath //mention user and the path to the directory “ What is the specific content of this part?

**Comment by AsherYartsevTech** [comment]
This error still occures @mashrin

**Comment by hipforth** [comment]
$ chown -R yue: /home/yue/UnrealEngine/
$ su user
$ make

It's work for me  
ubuntu18.04 && UE4.24

**Comment by validsyntax1012** [comment]
i get same issue after commands as well

**Comment by lahtis** [comment]
I get a same error when using chown command. What to do?

Using Ubuntu 18.4.5 LTS
