### ISSUE TITLE
Issue trying to use RC on AirSim Quadrotor through UDP

### ISSUE THREAD

**Issue by mchen0037** [Microsoft/AirSim#754]
Hi,
I was able to arm/disarm and fly using my RC (Spektrum DX8) through serial. I'm now trying to pass the MAVLink messages through UDP via MAVProxy (which connects to Pixhawk 2 through serial). When I arm/disarm, it'll show in MAVProxy (or QGroundControl), but the quadroter in AirSim stays unarmed. How am I able to check if the connection is established?

When I'm not running MAVProxy, I'll get errors saying that I'm 'not receiving any messages from HIL/SITL, please restart your HIL/SITL node and try again.'
![image](https://user-images.githubusercontent.com/31076823/35366104-96cc003a-012c-11e8-904a-4de112d4a9e7.png)

When I am running MAVProxy, I'll get the same error, but only for SITL (so it was able to connect the HIL?) 
![image](https://user-images.githubusercontent.com/31076823/35366062-4be9cf02-012c-11e8-951d-ea2aa4f77e0e.png)

Here is my settings.json:
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "DefaultVehicleConfig":"PX4",
  "PX4": {
    "FirmwareName": "PX4",
    "LogViewerHostIp": "127.0.0.1",
    "LogViewerPort": 14388,
    "OffboardCompID": 1,
    "OffboardSysID": 134,
    "QgcHostIp": "127.0.0.1",
    "QgcPort": 14550,
    "SerialBaudRate": 115200,
    "SerialPort": "*",
    "SimCompID": 42,
    "SimSysID": 142,
    "UdpIp": "127.0.0.1",
    "UdpPort": 14560,
    "UseSerial": false,
    "VehicleCompID": 1,
    "VehicleSysID": 135,
    "ApiServerPort": 41451
	}
}

Thanks! (I'm using Win10, master branch, Unreal 4.16.3)

**Comment by sytelus** [comment]
Unfortunately, we are not familiar with MavProxy and debugging its connection issues. If you have found solution, please post it here. I would also suggest to post in Mavproxy related forums for debugging tips.
