### ISSUE TITLE
Camera effects

### ISSUE THREAD

**Issue by eds89** [Microsoft/AirSim#759]
Hello,
Interesting ptoject. Have you developed a way to add post processing effects to the image captured by the camera? For instance, to use it in the adddition or removel of add or edit it as a wayfurtherinformation about the environment in real time? That feature would be useful to train algorithms to detect noise or other unavoidable conditions, which may hinder the behaviour of the car.

**Comment by sytelus** [comment]
Yes, you can certainly do that. It however needs some knowledge of how to build materials (shaders) in Unreal engine and shaders themselves. There are tons of YouTube tutorial on this subject and other docs. For example, I just recently added simulation for [camera noise and interference](https://github.com/Microsoft/AirSim/blob/master/docs/settings.md#image-noise-settings).
