### ISSUE TITLE
Error missing .dll when launching the project

### ISSUE THREAD

**Issue by Haotian-Zhang** [Microsoft/AirSim#760]
Hi All,
I'm facing the same problem with setting up the AirSim Plugins for my project. After I build the AirSim pulled from git successfully. I copied the Plugins folder to my project and edit the .uproject. When I opened the .uproject and it pops out the warning:
![screenshot 2](https://user-images.githubusercontent.com/28856987/35426662-80082cc8-0219-11e8-91cf-b8c51ce353b9.png)

My compile results displayed like this:
![screenshot 4](https://user-images.githubusercontent.com/28856987/35426702-c9d8fb98-0219-11e8-9872-5ce45b09caaf.png)

Plus, I can only see three files in my Plugins folders, 

![screenshot 6](https://user-images.githubusercontent.com/28856987/35426849-d35ab9b2-021a-11e8-895c-54896d9805e2.png)

Can someone please tell me how to solve this issue? Thank you!

Platform: Windows 10 x64 + VS 2015

**Comment by sytelus** [comment]
That's normal message. Just click Yes and keep going.

**Comment by haotiz** [comment]
I used to build the project on Linux, so it's a little bit different in Windows here. Thank you so much! @sytelus
