### ISSUE TITLE
MacOS: build scripts use 'readlink -f'

### ISSUE THREAD

**Issue by asimonov** [Microsoft/AirSim#769]
Hi, while trying to setup.sh/build.sh on MacOS with current master I had to use my own 'myreadlink' script to replace 'readlink -f' behaviour.
I took the code from: https://stackoverflow.com/questions/1055671/how-can-i-get-the-behavior-of-gnus-readlink-f-on-a-mac
And it works.
Would be good to see this incorporated into the codebase so that MacOS build works out of the box.

**Comment by sytelus** [comment]
I've changed both build.sh and setup.sh to support readlink for Mac OS. Please try it out!
