### ISSUE TITLE
Build It on Linux

### ISSUE THREAD

**Issue by IeiuniumLux** [Microsoft/AirSim#770]
The https://github.com/EpicGames/UnrealEngine.git repository doesn't longer exist.  Can you update the instructions to [build on linux](https://github.com/Microsoft/AirSim/blob/master/docs/build_linux.md)?

`git clone -b 4.17 https://github.com/EpicGames/UnrealEngine.git`

**Comment by IeiuniumLux** [comment]
Never mind.  Once you need to add your GitHub account to your Epic Games account, after that you will received an email and get pull access to the repository.

**Comment by imrasp** [comment]
@IeiuniumLux How long will it take after associate github account?, Do I need to click on any link to get an email for pull request.
