### ISSUE TITLE
Unable to debug - DebugGame Editor error

### ISSUE THREAD

**Issue by jjlee1991** [Microsoft/AirSim#780]
Followed the step by step, till pressing for "F5" to debug, when I faced the error:
"The following modules are missing or built with a different engien version:
UE4Editor-LandscapeMountains-Win64-DebugGame.dll
Would you like to rebuild them now?"

Selected yes, and this error occurred:
"LandscapeMountains could not be compiled. Try rebuilding from source Manually".

Please advice
Thank you

**Comment by sytelus** [comment]
Can't reproduce. I'm wondering if your environment is not setup properly.

**Comment by samby707** [comment]
I am also facing the same issue. please help

**Comment by changh95** [comment]
![image](https://user-images.githubusercontent.com/39010111/69605376-472a9080-1063-11ea-9d6e-0437ec67dcd5.png)
Facing the same issue here.
