### ISSUE TITLE
Build Errors while Creating and Setting Up Unreal Environment

### ISSUE THREAD

**Issue by kalpitsmehta** [Microsoft/AirSim#788]
Tried to follow https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md. But I get following errors:

Exected .h file to be first header included

![image](https://user-images.githubusercontent.com/6471047/35786398-f43f2f32-09f4-11e8-88ac-a507272b0aaa.png)

Software Versions:
MS VS 2015 (Update 3)
Unreal Engine 4.16.3

**Comment by sytelus** [comment]
I'm not sure if instructions are properly followed. Looks like your cpp file doesn't have corresponding header include as first line.

**Comment by wujiyoung** [comment]
I have the same problem, have you resolve it?
