### ISSUE TITLE
Build Error : MavLinkCom.vcxproj

### ISSUE THREAD

**Issue by Kim-BongSu** [Microsoft/AirSim#794]
c:\program files (x86)\microsoft visual studio 14.0\vc\include\crtdefs.h(10): fatal error C1083: Cannot open including files 'core
crt.h': No such file or directory [C:\Users\kbs\source\AirSim2\MavLinkCom\MavLinkCom.vcxproj]

**Comment by sytelus** [comment]
I'm guessing your Visual Studio 2015 either doesn't have Update 3 or has only partial VC++ product installed.

**Comment by Isaac45** [comment]
having the same problem, using visual studio 2017
c:\program files (x86)\microsoft visual studio 14.0\vc\include\crtdefs.h(10): fatal error C1083: Cannot open including files 'core
crt.h': No such file or directory [C:\Users\kbs\source\AirSim2\MavLinkCom\MavLinkCom.vcxproj]

**Comment by saihv** [comment]
Confirmed, I have the same problem while trying to build with Visual Studio 2017.
