### ISSUE TITLE
Error running run.bat for city environment 1.16

### ISSUE THREAD

**Issue by josheligoldman** [Microsoft/AirSim#797]
When I try to run run.bat I get the following error: 
Fatal error:
[File:D:\Build\++UE4+Release-4.16-Compile\Sync\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp][Line: 981] GameThread timed out waiting for RenderThread after 30.00 secs

**Comment by sytelus** [comment]
This is fixed now.
