### ISSUE TITLE
Modeling other drone using parameters in SimpleFlightQuadX.hpp

### ISSUE THREAD

**Issue by kayvan61** [Microsoft/AirSim#798]
I was wondering if you can simulate other drones by adjusting the parameters in SimpleFlightQuadX.hpp or if the parameters there are fine tuned for one specific drone. 

Thank you.

**Comment by sytelus** [comment]
SimpleFlightQuadX was modelled after real world drone but you can change parameters there to model some other drone. Feel free to play around!
