### ISSUE TITLE
AirSim crashes after running normally for a while

### ISSUE THREAD

**Issue by zamlz** [Microsoft/AirSim#801]
![image](https://user-images.githubusercontent.com/10750027/35946853-4094c6f4-0c1a-11e8-9097-a7a3688f3f17.png)

Any ideas what could be causing this?
On an Nvidia 1080Ti machine with latest drivers.

**Comment by sytelus** [comment]
Looks like driver issue. You might want to get support from Unreal folks: http://answers.unrealengine.com/
