### ISSUE TITLE
Initial position set of DQNdrone.py

### ISSUE THREAD

**Issue by edimoon777** [Microsoft/AirSim#803]
I tried to simulate DQNdrone.py with 'MountainLandscape' Binary program on windows OS.
The script runs well.
but I can't find the high tension power lines in AirSim.
Can you check the initial position ?
initX = -.55265
initY = -31.9786
initZ = -19.0225

or is it requires any additional objects with MountainLandscape?

**Comment by sytelus** [comment]
Power lines don't exist in default MountainLandscape environment. That is something we added with help of our in-house artists. I'll try to see if I can include this additions in our binaries.

**Comment by sytelus** [comment]
The new mountain environment in releases tab now has power lines.
