### ISSUE TITLE
Run PythonClient scripts--got some errors!

### ISSUE THREAD

**Issue by yumianhuli1** [Microsoft/AirSim#807]
I started UE4 with Car simulation --that is fine.all ok!
When I run point cloud.py, I got some errors...

rawImage = client.simGetImage(0, AirSimImageType.DepthPerspective)

result = self.client.call('simGetImage', camera_id, image_type)

return self.send_request(method, args).get()

raise self._error
msgpackrpc.error.TransportError: Retry connection over the limit

Somebody know the reason?Thank U!

**Comment by sytelus** [comment]
It uses `client = MultirotorClient()`. You need to switch to client = CarClient()`. Also, please note that this code is still work in progress. Use it at your own risk!
