### ISSUE TITLE
Build Tiny Private RaspBerry p2p/http network.

### ISSUE THREAD

**Issue by MrNavette** [Microsoft/AirSim#81]
With only a few we could distribute a lot.

Just select who's gonna have the binaries (make private repo: linux host)

Secured servers with secured private p2p links, that could allow you to control how your binaries are spread.

It could help a lot, thoose who got one of these tiny pc could build up this in an eyebat.

**Comment by lovettchris** [comment]
Did you post this to the right repo?  I don't see what it has to do with AirSim...
