### ISSUE TITLE
How to Use Python APIs with Releases

### ISSUE THREAD

**Issue by josheligoldman** [Microsoft/AirSim#816]
I downloaded Neighbourhood.zip v1.1.6 from https://github.com/Microsoft/AirSim/releases
When I tried to use the instructions at https://github.com/Microsoft/AirSim/blob/master/docs/python.md I couldn't find the PythonClient folder. How do I use python to control the car with the precompiled releases.

**Comment by akshaysw** [comment]
@josheligoldman you will find pythonclient folder in AirSim repo, you have to clone Airsim repo on your local computer to use PythonClient with precompiled binaries.
1. extract Neighbourhood.zip v1.1.6 then run run.exe this will start simulator chose between car or drone.
2. then goto pythonclient folder in cloned Airsim repo you will find hello_drone.py there
