### ISSUE TITLE
Do the 'noise' settings also work for images other than scene?

### ISSUE THREAD

**Issue by saihv** [Microsoft/AirSim#820]
I am trying to examine the effects on disparity etc. by changing ImageType (say, to 4 for disparity) in the noise settings, but the images are still clean and I don't see any noise. 

In contrast, I do see the effect for scene images. How do I apply these noise settings to the other  types of images?

**Comment by sytelus** [comment]
Disparity and depth are ground truth so they are not affected by noise.

**Comment by saihv** [comment]
I see. Is it possible to override it manually through the code? I am trying to use disparity images for training a neural net and would like to see if/how adding noise helps in transferring to real life stereo images.
