### ISSUE TITLE
How can I set VehicleConfigName

### ISSUE THREAD

**Issue by cangokalp** [microsoft/AirSim#821]
I'm trying to get multiple vehicles in the simulation using PX4 as the flight controller. I've gone through the setup documentation, I'm stuck where it says set the VehicleConfigName of the pawns to PX4_1 and PX4_2. Where do I do this? - I'm assuming it's in the Unreal Editor, but couldn't find such setting so far. Does anyone know how to set this.

**Comment by zergler** [comment]
This setting is no longer implemented. Most of the code for setting up multi rotor vehicles happens in [SimModeWorldMultiRotor.cpp](https://github.com/Microsoft/AirSim/blob/e169e65755f4254c29b67617f50502a262e64e63/Unreal/Plugins/AirSim/Source/Multirotor/SimModeWorldMultiRotor.cpp#L194). You can see when a new vehicle is created, the port number in the `settings.json` file is incremented and an RPC server is created for that vehicle at the computed port and address.

As long as you have the `BP_FlyingPawn` actors in your Unreal map, AirSim should find them but I'm unsure as to what order each vehicle in the map is processed through this [for loop](https://github.com/Microsoft/AirSim/blob/e169e65755f4254c29b67617f50502a262e64e63/Unreal/Plugins/AirSim/Source/Multirotor/SimModeWorldMultiRotor.cpp#L116). That might depend on how Unreal finds actors in the environment. Maybe that doesn't matter for your application.

This should get you as far as having multiple vehicles in the environment controlable by individual RPC servers. I'm not sure if getting multiple HILs up is possible yet. Good luck!
