### ISSUE TITLE
Build error when trying to log sensordata

### ISSUE THREAD

**Issue by Swim0n** [Microsoft/AirSim#835]
Hello!

In the SimModeWorldMultiRotor class, I am trying to modify the code in the getLogString()-method so that it can log data from the sensors. I've successfully done something similar before, when logging RCData. My code back then was like this:
```
MultiRotorConnector& mrc = static_cast<MultiRotorConnector&>(*fpv_vehicle_connectors_[0]);
RCData data = mrc.getRCData();
```
and then just appending pitch, roll, yaw and throttle to the string.

I am trying now to do the same thing but with the sensor data like this:
```
SimpleFlightQuadX& mrp = static_cast<SimpleFlightQuadX&>(*vehicle_params_[0]);
SensorCollection s = mrp.getSensors();
```
it doesn't build with the error that I'm attempting to reference a deleted function. The problem seems to appear when assigning mpr.getSensors(); to a variable, because this code:
```
SimpleFlightQuadX& mrp = static_cast<SimpleFlightQuadX&>(*vehicle_params_[0]);
mrp.getSensors();
```
builds without errors.

Any ideas guys? Really thankful in advance for any help.

**Comment by sytelus** [comment]
We are sorry but we can't provide support for custom code modifications. Closing this issue because of its age.
