### ISSUE TITLE
controlling FOV by keyboard

### ISSUE THREAD

**Issue by ngeley** [Microsoft/AirSim#836]
I'm interested in having a setup where I can control the FOV (in the car setup) by configuring the keyboard keys. Ex: if I were to divide my views to be split to 60degrees (left, center, right) and 60degrees in the rear, I want to be able to only see one view at a time at the press of a key. This would be different than the automatic config (which gradually changes the view). I'd also like to prompt the user every x seconds to select a new view. How would I be able to do this using the python api?

**Comment by sytelus** [comment]
One of our user recently submitted pull request for "Front" view which is now activated when pressing I key. We are not planning to work on other features you have described. However, you are welcome to contribute these :).
