### ISSUE TITLE
Controlling Multiple Drones through ROS

### ISSUE THREAD

**Issue by exploke** [Microsoft/AirSim#839]
I want to fly at least 8 drones in my environment through ROS messages each drone individually receives. I have already flown in Airsim using ROS messages with 1 drone, but I am not sure what the easiest way to do it with 8 drones is. I have looked into simworldmultirotor.cpp and swarmcontrol.py (referenced in #560 #664 #706). 

Question 1: Can I pass information to individual drones through ROS in AirSim?

Question 2: Can I use just simpleflight/APIserverport (I have only been able to use SITL/PX4 prior to this) to connect to the drones and ROS?

Question 3: Which script listed above would be best?

Any advice or reference would be appreciated!

**Comment by sytelus** [comment]
Currently AirSim doesn't talk to ROS directly. We need to write ROS adapters. If you know how to do that please feel free to contribute :).

You can continue discussion here: https://github.com/Microsoft/AirSim/issues/53
