### ISSUE TITLE
Possible to add Cameras to the Drone? 

### ISSUE THREAD

**Issue by olivia-skydio** [Microsoft/AirSim#840]
Is it possible to add a camera to the drone? What files would you have to change besides FlyingPawn.cpp? 
Thanks!

**Comment by zergler** [comment]
You will have to modify the BP_FlyingPawn blueprint with the added camera and parameters, and then inside [FlyingPawn.cpp](https://github.com/Microsoft/AirSim/blob/e169e65755f4254c29b67617f50502a262e64e63/Unreal/Plugins/AirSim/Source/Multirotor/FlyingPawn.cpp#L46), add your reference to it, making sure to add it to the [camera list](https://github.com/Microsoft/AirSim/blob/58042d173096ac865c04daf2d9113004a7a23089/Unreal/Plugins/AirSim/Source/Multirotor/FlyingPawn.cpp#L19).

**Comment by olivia-skydio** [comment]
@zergler thanks for the reply back! So I'm currently doing that right now but when I try and do ImageRequest for that camera then my UnrealEngine crashes. Any ideas of things I could be missing?

**Comment by zergler** [comment]
Hmm I'm not sure. You could launch UE4Editor inside gdb and then run `r /path/to/airsim/Unreal/Environments/Blocks/Blocks.uproject` to get a stack track. That might point out the problem.

**Comment by DavidLSmyth** [comment]
I have done this previously, you'll also need to make changes in [FlyingPawn.h](https://github.com/Microsoft/AirSim/blob/58042d173096ac865c04daf2d9113004a7a23089/Unreal/Plugins/AirSim/Source/Multirotor/FlyingPawn.h), [VehicleWrapper.cpp](https://github.com/Microsoft/AirSim/blob/ce85db7008b68316c4685a3990be6c9a032c3e53/Unreal/Plugins/AirSim/Source/VehiclePawnWrapper.cpp). I followed the code starting from [multiRotorAPI](https://github.com/Microsoft/AirSim/blob/ce85db7008b68316c4685a3990be6c9a032c3e53/AirLib/include/vehicles/multirotor/api/MultirotorApi.hpp) simGetImage method. I can outline the specific changes that I made if that isn't enough

**Comment by olivia-skydio** [comment]
@DavidLSmyth thanks for the response! I made changes in FlyingPawn.h to add my camera. What other changes in VehicleWrapper.cpp would I need to add? Thanks so much!

**Comment by olivia-skydio** [comment]
Just got it working I think! Thanks for the help @zergler! @DavidLSmyth  I didn't end up changing anything in VehicleWrapper.cpp was still curious what you changed?

**Comment by sytelus** [comment]
Just curious, why you need additional cameras. We already have 5 cameras on the drone...

**Comment by nnayeer** [comment]
Hi @sytelus , not the OP but might have an answer to your question. Since my team and I would like to duplicate camera rig configurations from real vehicles (we have many) and test new ones, it helps to be able to specify the exact number, position and orientation of each camera, which I'm currently attempting to do similar to the methods discussed on this thread. Even though my use is for the car, I'd imagine there's a similar reason for wanting this option on a drone.

**Comment by sytelus** [comment]
For now you might be able to just change values here: https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/Car/CarPawn.cpp#L123

In long run we want to be able to specify this through json settings.

**Comment by nalinraut** [comment]
@DavidLSmyth, Can you go over the changes or attach files to the comment so I can personally go through the changes? I need multiple stereo cameras on the multirotor. Thank you.

**Comment by nalinraut** [comment]
@DavidLSmyth If I am not wrong, I can use the left and right camera as a stereo pair using the simGetImages API. Thank you!

**Comment by nalinraut** [comment]
@olivia-skydio Did you only make changes to FlyingPawn.h or are there more changes to other scripts? Thank you!

**Comment by madratman** [comment]
hey @nalinraut, see my comment on #1770 here https://github.com/Microsoft/AirSim/issues/1770#issuecomment-462949223
