### ISSUE TITLE
Is it possible to control the airsim with Arduino?

### ISSUE THREAD

**Issue by gitstar12** [microsoft/AirSim#841]
I wanted to know how to control the airsim with the help of Arduino and a gyrosensor

**Comment by lovettchris** [comment]
If Arduino can run python (micropython perhaps) then you could run the PythonClient scripts from an Arduino computer.  I know for sure you can do this from a RaspberryPi.  The only dependency is the msgpack-rpc-python.  So you may need to build that package if it isn't available for your specific board.

**Comment by sytelus** [comment]
BTW, you can also use C++ API ([see here](https://github.com/Microsoft/AirSim/blob/master/HelloCar/main.cpp)). I believe C++ interface for msgpack-rpc is compilable for any platform supporting C++11 compilers.

**Comment by gitstar12** [comment]
I am new to Airsim, so could you Kindly tell me more about this...

**Comment by jonyMarino** [comment]
Closed due to inactivity. Feel free to reopen to ask again. Doc update pending.
