### ISSUE TITLE
build.cmd issue

### ISSUE THREAD

**Issue by gitstar12** [Microsoft/AirSim#847]
<img width="1440" alt="screen shot 2018-02-26 at 4 01 11 pm" src="https://user-images.githubusercontent.com/36403067/36665764-73e95de6-1b0e-11e8-9396-4bc91ad8410a.png">

**Comment by lovettchris** [comment]
Fixed

**Comment by gitstar12** [comment]
no its not fixed how to do it??

**Comment by sytelus** [comment]
Looks like @FireTime fixed this with this PR: https://github.com/Microsoft/AirSim/pull/845

@lovettchris - is there a different fix?

**Comment by FireTime** [comment]
Correct, I submitted that fix for this exact error.

**Comment by gitstar12** [comment]
<img width="1440" alt="screen shot 2018-02-28 at 3 00 17 pm" src="https://user-images.githubusercontent.com/36403067/36781294-776762f4-1c9b-11e8-9e8a-4a04095bceb5.png">

**Comment by sytelus** [comment]
Please do not post screenshots. Take time to look at error messages and see if you can debug this by yourself. We can't reproduce this.
