### ISSUE TITLE
DistanceSimple wrong order of rotation multiplication

### ISSUE THREAD

**Issue by Swim0n** [Microsoft/AirSim#848]
Hello. This is just a headsup for you guys (didn't bother creating a pull request since it's just a single line of code), that the addition of the drone pose and the relative pose when calling getRayLength() is done in the wrong order. Quaternion multiplication is not commutative, which means that it has to be `params_.relative_pose + ground_truth.kinematics->pose`
, instead of the other way around. This caused me a lot of headache so I just wanted to save anyone else the trouble.

Thanks!

**Comment by sytelus** [comment]
Good catch!
