### ISSUE TITLE
How to solve the build error of Airsim on win10

### ISSUE THREAD

**Issue by kdzy** [Microsoft/AirSim#852]
I followed the steps of tutorials in [https://github.com/Microsoft/AirSim/blob/master/docs/build_windows.md] to build AirSim on windows, but when I run the build.cmd, the errors appeared as below:
![1](https://user-images.githubusercontent.com/34563583/36824330-b4d9bfaa-1d3c-11e8-8c31-91696ceeb8e8.PNG)
![2png](https://user-images.githubusercontent.com/34563583/36824290-7d5b8b4e-1d3c-11e8-87f5-e8e7f64e145f.PNG)
![3](https://user-images.githubusercontent.com/34563583/36824333-b7ca576a-1d3c-11e8-93c9-c3d0d245137a.PNG)
![4](https://user-images.githubusercontent.com/34563583/36824336-b9c46b50-1d3c-11e8-9688-0b10cc77e8e0.PNG)
![5](https://user-images.githubusercontent.com/34563583/36824337-bb1ca8e6-1d3c-11e8-82fb-23ac8eb6c82c.PNG)
![6](https://user-images.githubusercontent.com/34563583/36824339-bc93a79c-1d3c-11e8-9f3f-541f49b58e3a.PNG)
![7](https://user-images.githubusercontent.com/34563583/36824341-bdf03f60-1d3c-11e8-9ddd-7edb878d2407.PNG)
![8](https://user-images.githubusercontent.com/34563583/36824345-bf3951d6-1d3c-11e8-9e4b-2768a3931e97.PNG)
![9](https://user-images.githubusercontent.com/34563583/36824346-c06cf666-1d3c-11e8-9fe3-3bec397ea9c8.PNG)

 Is the reason I lack the installation of some library? If yes, what the library is? If not ,could anyone give me some suggestions?Thanks a lot!

**Comment by sytelus** [comment]
Please confirm if you have VC++ included in Visual Studio 2015 Update 3. It looks like your VC++ compiler is of older version.

**Comment by kdzy** [comment]
I have installed Visual Studio 2015 Update 3, and included  VC++. VC ++ version and VS2015 version is the corresponding.
![11](https://user-images.githubusercontent.com/34563583/36835601-ba045d70-1d71-11e8-9fd5-ba4637c2ff31.PNG)

**Comment by kdzy** [comment]
I have solved the problem. The reason is that the VS 2015 was not installed properly.When I uninstalled the VS  that was installed before completely, and installed VS 2015 correctly, especially the VC++ complier,the error disappeared.
