### ISSUE TITLE
initial position of the car

### ISSUE THREAD

**Issue by Jacquesval** [Microsoft/AirSim#854]
Hello,
I'm using the car simulator on airsim, and I want to be able to change the initial position of the car. I guess we can change it in the .json file but I don't find any documentation on how to do it. I'm using the binary file for landscape Mountains.
Thanks
Jacques V

**Comment by mitchellspryn** [comment]
You can call car_client.simSetPose( <vector3R of position>, <quat of heading> ) via the python API to set the pose.

**Comment by coderhh** [comment]
> pose
It's said this api function doesn't exsit
