### ISSUE TITLE
be able to control car by moveOnPath() ?

### ISSUE THREAD

**Issue by ryuk3t** [microsoft/AirSim#855]
Hello,
Is there a way that I can control the car move on path like the drone because I hope to input a trajectory to simulate collision.

**Comment by sytelus** [comment]
Not at present. You can easily do this using existing PID controller infrastructure in AirSim however.

**Comment by Ryuk03** [comment]
Thanks! I will dip into that

**Comment by gut-yu** [comment]
@Ryuk03 
Hello,
Can you tell me where is the PID controller of vehicles?
If I calculate the value of the expected acceleration， how can I get the corresponding throttle input value or the corresponding break input?
