### ISSUE TITLE
Reason for constant in MultiRotorParams.hpp computeInertiaMatrix()

### ISSUE THREAD

**Issue by kayvan61** [Microsoft/AirSim#857]
Hello,

I was nosing through the source for computeInertiaMatrix() and noticed that all the mass values are divided by 12. I looked at the reference provided in the comments and couldn't find out why the masses were divided by 12. Any reason?

Thanks.

**Comment by sytelus** [comment]
Its because vehicle is modeled as box (cuboid) and equation for diagonal elements for cuboid involves diving by 12. See https://en.wikipedia.org/wiki/List_of_moments_of_inertia
