### ISSUE TITLE
Error at startup: ImageType must be >=-1 and < 0

### ISSUE THREAD

**Issue by Mayankm96** [Microsoft/AirSim#861]
While running the AirSim plugin in the simulator I am receiving the error message:
```
Error at startup: ImageType must be >=-1 and < 0
```

I checked my `settings.json` (available [here](https://gist.github.com/Mayankm96/d880d55c32ff2513a92dee6b79673942)) file and couldn't file the error source. 

Any possible reasons for this error at runtime?

**Comment by sytelus** [comment]
Fixed
