### ISSUE TITLE
Pedestrian models

### ISSUE THREAD

**Issue by pmwenzel** [Microsoft/AirSim#862]
Hi,

are there any plans to include a pedestrian model in AirSim?
Thanks.

**Comment by allen9273** [comment]
+1,I also want to

**Comment by sytelus** [comment]
It will be however only in binary form.

**Comment by pmwenzel** [comment]
What exactly do you mean by a binary pedestrian model? What will be the timeline for releasing?

**Comment by sytelus** [comment]
Please check out CityEnviron in our latest release. You will find lots of pedestrians!

https://github.com/Microsoft/AirSim/releases/tag/v1.1.10
