### ISSUE TITLE
Simulated groundtruth in PX4

### ISSUE THREAD

**Issue by Fab7c4** [Microsoft/AirSim#864]
Hello,

I have SITL setup using PX4. Everything works more or less but I have two questions which are not really clear to me from the provided documentation. 
Is the simulated groundtruth data published via MAVlink and ends up in the created logfile by PX4? I browsed the ulog file but could not identify any field which contains this data.
Is there some communication of parameters between Airsim and PX4? Or where does PX4 get its values for example for the IMU scale factors?

Some insights would be appreciated :-)

**Comment by sytelus** [comment]
Ground truth is not published via mavlink (not sure if that's even possible).

There is no communication of parameters between AirSim and PX4. User is supposed to have set this up before using AirSim.
