### ISSUE TITLE
Error while compiling Hello Drone

### ISSUE THREAD

**Issue by m4au3** [Microsoft/AirSim#865]
I compiled main.cpp of HelloDrone using clang++ main.cpp on ubuntu16.04, and I got the following error,
main.cpp:4:10: fatal error: 'common/common_utils/StrictMode.hpp' file not found.
Does anyone know how to solve this?

**Comment by sytelus** [comment]
You need bunch of dependencies which is why we have cmake to compile projects. See files in cmake folder.
