### ISSUE TITLE
Unable to determine which engine version is being used to build AirSim

### ISSUE THREAD

**Issue by mjcorriere** [Microsoft/AirSim#866]
I currently have two versions of the Unreal Engine installed on my Linux machine (Ubuntu 16.04). When building AirSim, how can I determine which version of the engine it used to build?

I ask because every time I create a new project with a custom environment per the tutorials, I am told that the AirSim plugin is incompatible with the engine version. Rebuilding the .so files always fails.

**Comment by sytelus** [comment]
You can,

1. Run Epic Game Launcher. In Library tab set 4.16 as default engine.
2. In .uproject file of your project, check the associated engine version.
