### ISSUE TITLE
step-by-step to record depth

### ISSUE THREAD

**Issue by dehuachen2017** [Microsoft/AirSim#868]
I am new to unreal engine and c++, so please forgive if this question was asked before.
I could not find "EPIPCameraType::PIP_CAMERA_TYPE_SCENE" in RecordingThread.cpp. (#271)
What can I do in order to be able to record depth?
Thanks

**Comment by sytelus** [comment]
Please read https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md
