### ISSUE TITLE
AirSim car invisible - Help

### ISSUE THREAD

**Issue by suvam-bag** [Microsoft/AirSim#875]
Hello,

I have imported a custom unreal environment in AirSim (Linux). I added the AirSim car (through PlayerStart) and have changed the mode to AirSimMode. Everything's working fine regrading the controls and even recording images. 
However the AirSim car is invisible and and I am unable to get around it even after playing around with all the settings in the image api/settings.json. 
Any help would be greatly appreciated.  Thank you.

**Comment by sytelus** [comment]
Try deleting your settings.json. You will be prompted for whether you want car ro drone. Unless you have made code changes in AirSim, things should work...
