### ISSUE TITLE
Accessing the APIs via C#

### ISSUE THREAD

**Issue by henrik94** [microsoft/AirSim#876]
I've tried several methods for calling the API from a Visual C# project, but I just couldn't make it work properly. Could you provide a small example how should you start if you want to access the API via C#? Some more documentation on this would be useful.

**Comment by sytelus** [comment]
You might want to look at https://github.com/yfakariya/msgpack-rpc-cli

**Comment by xuanmung** [comment]
I've the same problem. Have you solved it, @henrik94 ?
Any body could provide a particular API for C# plz?
Thanks in advance~

**Comment by totht91** [comment]
We have made a good progress and we are considering to make it public after some more stabilization.

**Comment by xuanmung** [comment]
Great, @totht91. I am really looking forward to your contribution.

**Comment by NextSim** [comment]
Excited about using this as well.

**Comment by sytelus** [comment]
@NextSim had been looking in to this as well: https://github.com/Microsoft/AirSim/issues/946

Any updates?

**Comment by NextSim** [comment]
I took a look at the quickstart guide 

https://github.com/yfakariya/msgpack-rpc-cli/wiki/Quick-start

but after installing the NuGet package for MsgPack.Cli, it doesn't contain a definition for RpcClientConfiguration. 

Maybe I'm missing something

**Comment by NextSim** [comment]
I finally got communication working over the api with c#.  

I used the MessagePack serializer below

https://github.com/neuecc/MessagePack-CSharp

For the enable api  and set car control I created the classes and helper functions below.

```
using MessagePack;
namespace Simulator
{
    [MessagePackObject]
    public class carControlHelper
    {
        [Key(0)]
        public controlApiParams apiParams { get; set; }
    }

    [MessagePackObject]
    public class enableApiHelper
    {
        [Key(0)]
        public bool val { get; set; } 
    }

    [MessagePackObject]
    public class controlApiParams
    {
        [Key("throttle")]
        public float throttle { get; set; }

        [Key("steering")]
        public float steering { get; set; }

        [Key("brake")]
        public float brake { get; set; }

        [Key("handbrake")]
        public bool handbrake { get; set; }
        [Key("is_manual_gear")]
        public bool is_manual_gear { get; set; }
        [Key("manual_gear")]
        public int manual_gear { get; set; }
        [Key("gear_immediate")]
        public bool gear_immediate { get; set; }
    }

    public static class msgPackRpcHelper
    {
        private static int msgCounter = 0;

        public static byte[] enableApiHelper(int type, bool enable)
        {
            var helperObj = new object[] { type, msgCounter++, "enableApiControl", new enableApiHelper { val = enable } };
            return MessagePackSerializer.Serialize(helperObj);
        }

        public static byte[] setCarControlHelper(int type, float accel, float strAngle, float brake, bool handbrake, bool isManual, int gear, bool gearImmediate)
        {
            var helperObj = new object[] { type, msgCounter++, "setCarControls", new carControlHelper{apiParams = new controlApiParams {
                    throttle = accel,
                    steering = strAngle,
                    brake = brake,
                    handbrake = handbrake,
                    is_manual_gear = isManual,
                    manual_gear = gear,
                    gear_immediate = gearImmediate
                } } };
            return MessagePackSerializer.Serialize(helperObj);
        }
    }
}
```

**Comment by sytelus** [comment]
Very nice! We look forward to your pull request :).

**Comment by NextSim** [comment]
Working on it.  It's incomplete though, since classes have to be made for each api call and response, but there aren't any details on each api call so it is slow developing it.

**Comment by brandtd** [comment]
@NextSim, I've been trying to do something similar, and I've made some progress calling the RPCs from C#. So far, though, I've been focused on the multirotor side of things. If you've got the time, you may want to take a look, specifically at the AirSimRpc and MsgPackRpc projects: https://github.com/brandtd/AirSimApp

**Comment by zimmy87** [comment]
closed to age and lack of activity

**Comment by tank104** [comment]
@NextSim are you able to share the code that sends the message you have above?
I am trying to use MagicOnion (which uses MessagePack) but it keeps crashing AirSim whenever I make an API call.

**Comment by tank104** [comment]
@brandtd @xuanmung  did you manage to get working? any code you can share?

**Comment by tank104** [comment]
For anyone that sees this - I managed to get it working with the following code below.
I went down a bit of rabbit hole with more recent RPC libraries that just weren't compatible (MagicOnion and streamjsonrpc).


[Include https://github.com/yfakariya/msgpack-rpc-cli]

using MsgPack.Rpc.Client;
using MsgPack.Serialization;
using System.Net;

namespace TestConsoleApp
{
  internal class Program
  {
    static void Main(string[] args)
    {
      var configuration = new RpcClientConfiguration();
      var context = new SerializationContext();
      context.SerializationMethod = SerializationMethod.Map;
      using (dynamic proxy = new DynamicRpcProxy(new DnsEndPoint("127.0.0.1", 41451), configuration, context))
      {
        int msgCounter = 0;
        var result = proxy.isApiControlEnabled("");

        var imageResponse = proxy.simGetImages(new ImageRequest[]
        {
          new ImageRequest
          {
            camera_name = "0",
            image_type = 0,
            pixels_as_float = false,
            compress = false
          }
        }, "", false);
      }
    }
  }

  public class ImageRequest
  {
    public string camera_name { get; set; }
    public int image_type { get; set; }
    public bool pixels_as_float { get; set; }
    public bool compress { get; set; }
  }
}
