### ISSUE TITLE
integration with matlab and simulink

### ISSUE THREAD

**Issue by a-mike-foxtrot** [microsoft/AirSim#877]
hey guys is any one sucessful to integrate airsim with matlab/ simulink model ?

**Comment by robinuvic** [comment]
Hi a-mike-foxtrot, 
I am looking for the same information.
Did you find any examples/documents/links related to integration of AirSim with MATLAB. Linking both would be great for deep learning. 

Hi guys,
Please do contribute if you have any information regarding this.

**Comment by jonyMarino** [comment]
I saw many post talking about issues with simulink, so I think a doc update is what is neeeded

**Comment by jonyMarino** [comment]
closed due to inactivity. doc update pending
