### ISSUE TITLE
How to create binaries

### ISSUE THREAD

**Issue by guillemhub** [microsoft/AirSim#884]
Hey, I am playing with deep reinforcement methods on the AirSim scenarios.

I have followed the https://github.com/Microsoft/AirSim/blob/master/docs/unreal_blocks.md instructions but when I have a modified scenario (e.g. the blocks one) how can I generate binaries from it? What do I need to do? I can't find any source information. I need to generate binaries in order to upload and share the environment with other people, so that they can download them, play it as a .exe and test.

Thanks!

**Comment by sytelus** [comment]
See https://docs.unrealengine.com/en-us/Engine/Basics/Projects/Packaging
