### ISSUE TITLE
How to get the real distance

### ISSUE THREAD

**Issue by dehuachen2017** [Microsoft/AirSim#887]
Hey!
I want to know the distance from the drone to the view.
But I do not know how to get the real distance.
Thanks.

**Comment by allen9273** [comment]
I am wondering, too.

**Comment by sytelus** [comment]
What do you mean distance from "the view"? Can you elaborate on your goal?

**Comment by allen9273** [comment]
I'd like to recognize humans in the environment. Upon this, flying to the front of the human and maintain a specific distance from the human. How can I approach this?

**Comment by dehuachen2017** [comment]
for example, , as following depth map
[]([](![img_0_3_10520684179087](https://user-images.githubusercontent.com/29789574/37941646-ce392282-31a1-11e8-820c-9f2bfe19da81.png)))

**Comment by sytelus** [comment]
Please look at HelloDrone.py example that shows how to get depth map as floats 2D numpy array. Each cell value then is distance.

**Comment by dehuachen2017** [comment]
Thank you for your reply.
