### ISSUE TITLE
Face camera downwards

### ISSUE THREAD

**Issue by guillem74** [Microsoft/AirSim#888]
Hey, I am trying to get aerial images from the drone, so I need to face the camera downwards.

I tried this setCameraOrientation method: https://github.com/Microsoft/AirSim/blob/master/docs/image_apis.md#camera-orientation-gimble

client.setCameraOrientation(0, AirSimClientBase.toQuaternion(0.261799, 0, 0)); #radians

But it throws this error to me:

client.setCameraOrientation(0, AirSimClientBase.toQuaternion(0.261799, 0, 0)); #radians

**Comment by aburgm** [comment]
Camera index 3 is already downward facing, so you if you capture images from that one, you don't need to change any camera orientation at all.

**Comment by guillem74** [comment]
Camera index 3 is giving me aerial images but I see the drone in them. I need to get images faced downwards FROM the drone.

**Comment by guillem74** [comment]
@aburgm Thanks, I changed to camera number 2 and it is more or less what I was looking for.  For instance, calling: responses = client.simGetImages([ImageRequest(2, AirSimImageType.Scene)])

Do you know at which rate is the drone getting images? I maybe want to set it to just obtain images 1 per second, and therefore I can process them in the time between. I am trying to get aerial images for image classification using neural networks approach.

**Comment by aburgm** [comment]
Strange, 3 works fine for me for downwards imagery. To obtain 1 image per second, just call the `simGetImages` function once a second.

**Comment by deelakavasura** [comment]
When I use camera 3 without a gimbal if faces downwards. When the gimbal is on it faces forward. I want the downward facing camera with the gimbal effect. How to do this?
