### ISSUE TITLE
Integrating human players to AirSim

### ISSUE THREAD

**Issue by viniciusguigo** [Microsoft/AirSim#889]
Hello, everyone.

What would have to be done in order to integrate a human player (similar to the first-person view Unreal template) together with the quadrotor in some sort of multi-agent scenario? How to contribute to this effort?

Thanks!

**Comment by sytelus** [comment]
There is a manual mode (press M key) which allows you to use arrow keys + AWSD keys to control view manually. Is that what you are thinking about.

**Comment by viniciusguigo** [comment]
Hello, sytelus.

I believe I was not able to enter into Manual mode pressing M. Not even after changing to "ViewMode": "Manual" in the settings file. Am I missing anything?

Does it allow you to control the camera as it was gimballed (attached to the quadrotor) or does it allow to move freely around the map while the quadrotor operates normally with their onboard cameras?

Thanks!

**Comment by sytelus** [comment]
Just tested it and M key works as expected. It controls the external camera (not the camera on drone).
