### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by naveen7v** [Microsoft/AirSim#894]
Hi,

Trying to build AirSim on Ubuntu 16.04 ...following the documentation on building on Linux

When I ran ./setup.sh for AirSim, I got 

/media/nav/AirSim/cmake_build/bin/cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -LIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF -DLIBCXX_INSTALL_EXPERIMENTAL_LIBRARY=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=./output ../llvm-source-39
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/media/nav/AirSim/cmake_build/share/cmake-3.10
CMake Error: Error executing cmake::LoadCache(). Aborting.

My CMake version is 3.5.2

Tried solutions from stackexchange sites but nothing worked out.

Am I doing something wrong ...please help
Thank you

**Comment by sytelus** [comment]
Don't look like AirSim specific issue. You might want to post in Ubuntu or cmake support forums. Also see https://stackoverflow.com/questions/18615451/cmake-missing-modules-directory
