### ISSUE TITLE
update_from_git error

### ISSUE THREAD

**Issue by hyybuaa** [Microsoft/AirSim#895]
Get-ItemProperty : 找不到路径“HKEY_CLASSES_ROOT\Unreal.ProjectFile\shell\rungenproj”，因为该路径不存在。
所在位置 行:1 字符: 6
+ & { (Get-ItemProperty 'Registry::HKEY_CLASSES_ROOT\Unreal.ProjectFile ...
+      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKEY_CLASSES_RO...hell\rungenproj:String) [Get-ItemProperty], ItemNotFo
   undException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemPropertyCommand

**Comment by sytelus** [comment]
Please use regedit to see if following path exist in registry: `HKEY_CLASSES_ROOT\Unreal.ProjectFile\shell\rungenproj`

**Comment by Chunchaie** [comment]
Some issue happened to me. Any updates?

**Comment by hyybuaa** [comment]
@Chunchaie  i didn't follow the official tutorial and given up the steap, i used the vs 2015_enterprise instead of the community,
this is a  feasible tutorial: http://www.cnblogs.com/frankfanxinqi/p/8119931.html

**Comment by Chunchaie** [comment]
@hyybuaa - OK. Thank you.

**Comment by woodenchair** [comment]
i just find a perfect solution for the issue: https://zhuanlan.zhihu.com/p/147660674
