### ISSUE TITLE
Car positions not working well

### ISSUE THREAD

**Issue by guillem74** [Microsoft/AirSim#903]
I need to obtain position values of different houses at the Neighborhood environment, but when I try to access to the position values I get a 0 value in x, y and z. My idea is to move manually to the position, then run the code and get the precise position values. My code is:

from AirSimClient import *

client = CarClient()
client.confirmConnection()
client.enableApiControl(True)
car_controls = CarControls()
car_state = client.getCarState()
print (car_state.position) - > I get <AirSimClient.Vector3r object at 0x0000022E2D8F0940>
print (car_state.position.x_val) - > I get 0
print (car_state.position.y_val) - > I get 0
print (car_state.position.z_val) - > I get 0

**Comment by Yunusbcr** [comment]
If you check CarState class in  **AirSimClient.py**, you will see CarState class does not have position attribute directly. Position values hidden under the KinematicsState class, so 

**car_state.position.x_val**  should be replaced with **car_state.kinematics_true.position.x_val**
