### ISSUE TITLE
Add pedestrians in neighborhood block? 

### ISSUE THREAD

**Issue by allen9273** [microsoft/AirSim#904]
Only the city environment has moving vehicles and pedestrians. Is it possible to add pedestrians in neighborhood environment as well? I need  more moving pedestrians for human detection. thanks

**Comment by allen9273** [comment]
Thanks for your response, but it is work on the binary releases? The binary release: "Neighbourhood" is no pedestrians content.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
