### ISSUE TITLE
Changing max depth range of a depth perspective image

### ISSUE THREAD

**Issue by kshitijgoel007** [Microsoft/AirSim#909]
Hi! I want to control the max range of the depth camera while taking depth perspective image data. Is there an easy way of doing this?

**Comment by sytelus** [comment]
There is a parameter in the shader (material) that is available to do this however you will need to dig in to the code and learn more about material parameters in Unreal.

**Comment by kshitijgoel007** [comment]
Completed this on the ROS side of my codebase. Closing.
