### ISSUE TITLE
Setting different FOV for different CameraIDs

### ISSUE THREAD

**Issue by kshitijgoel007** [microsoft/AirSim#910]
Hi!

I am trying to set different FOV for front center and downward center cameras. However, it seems just using `CameraID` in Capture Settings in the settings.json is not working as expected. Is there a config file that allows this functionality or this has to be treated at the API level?

**Comment by sytelus** [comment]
Please post your settings.json. It should work...

**Comment by Domi47** [comment]
@sytelus so is it possible to set different FOV for different camera IDs? On settings doc https://github.com/Microsoft/AirSim/blob/master/docs/settings.md , it only shows that you can set FOV depending on image type. Maybe this issue is related to #993

**Comment by jonyMarino** [comment]
@Domi47, a camera has an image type and FOV associated with it. Everything working in last version at least.

Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
