### ISSUE TITLE
airsim fails to ./setup.sh

### ISSUE THREAD

**Issue by Hrhythm** [Microsoft/AirSim#917]
when i do airsim's ./setip.sh,when come to the step of receiving objects ,the speed of it is too slow ,only 4kib/s,and after a while ,it crashes,and send the error :
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by sytelus** [comment]
Looks like your Internet connection is very unreliable and/or too slow. If you have time, please look in to setup.sh and see if you can add more robust way to download.
