### ISSUE TITLE
How to set the starting location of the drone?

### ISSUE THREAD

**Issue by yousefab95** [microsoft/AirSim#923]
I've been trying to find a way to set the starting location of the drone, regardless of where PlayerStart is located. I've read [here](https://github.com/Microsoft/AirSim/issues/276) that setSimPosition does that, but all it seems to do is reset the location of the drone back to where PlayerStart is, regardless of what the coordinates I pass to it.
For clarification, my team and I are building a mission planner where the user is able to set the home location on a map. We would like to take the coordinates the user chose for the home location and start the drone simulation from there.

**Comment by mitchellspryn** [comment]
Not sure about the simSetPosition, but I've been using the following pseudocode to successfully set the position of the car:

```python
position = Vector3r(x,y,z)
heading = AirSimClientBase.toQuaternion(roll, pitch, yaw)
pose = Pose(position, heading)
car_client.simSetPose(pose, True)
```

It'd probably work for drones too.

**Comment by yousefab95** [comment]
Thank you @mitchellspryn 
Would this code be placed before or after client.armDisarm?

I'm not quite sure where to put the code. I tried putting it in various places in my script but the simulator keeps crashing whenever client.simSetPose is called.

**Comment by sytelus** [comment]
should be after armDiarm all.

**Comment by showaykerker** [comment]
I modify this to new apis 
```
position = airsim.Vector3r(x,y,z)
heading = airsim.toQuaternion(roll, pitch, yaw)
pose = airsim.Pose(position, heading)
car_client.simSetPose(pose, True)
```
and I get an error that went:
> AttributeError: module 'airsim' has no attribute 'toQuaternion'

**Comment by RVBldr** [comment]
Internal VSTF 7437
