### ISSUE TITLE
Center front view as main view (car)

### ISSUE THREAD

**Issue by henrik94** [Microsoft/AirSim#925]
Is there a way to use the center front camera as the main view instead of the driver camera and the chasing camera like you do here: https://github.com/Microsoft/AirSim/blob/master/docs/images/AirSimCarManual.gif ? We're using the precompiled neighbourhood environment.

If not, then can we expect such feature in the future?

**Comment by sytelus** [comment]
Thanks for your contribution. This is now merged.
