### ISSUE TITLE
Can I use a land vehicle in Airsim rather than a drone ? 

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [Microsoft/AirSim#93]
We are currently doing a project in robotic to train both a land vehicle and a drone. I would like to know is there a possibility of using AirSim for a land vehicle ?

**Comment by sytelus** [comment]
AirSim is design to support any vehicle that can be approximated as rigid body. So one can implement helicopters, airplanes or cars (however no trains or cars with trailers). We have implemented the multi rotor model on this physics engine and we do plan to implement model for car but that's bit lower priority compared to other stuff we want to finish up first. However, if some one in community wants to take stab, we can certainly help meanwhile.
