### ISSUE TITLE
How change report windows position

### ISSUE THREAD

**Issue by pjnet** [Microsoft/AirSim#934]
If you are looking for a new feature or bug fix, fire up your IDE, try playing around with source code and contribute back! 
What's better than filing issue? Filing a pull request :).

How change position of the report windows that appears when you press the ";"?
I use the Blocks codes for drone simulation.

**Comment by lovettchris** [comment]
The report UI is controlled by the AirSim plugin asset called "BP_SimHUD Widget".  If you open this widget in the Unreal Editor you will find an object called ReportContainer which you can move anywhere you want.  The visibility of this widget is controlled by code in ~\Plugins\AirSim\Source\SimHUD\SimHUDWidget.cpp.
