### ISSUE TITLE
Airsim cannot connect with Logitech G29 steering wheel

### ISSUE THREAD

**Issue by BrianN92** [Microsoft/AirSim#939]
Hi all, I found that my Logitech G29 steering wheel cannot connect with Airsim. After trying the x360ce, it still cannot recognize the steering wheel. -- "Control Mode: Keyboard". Did someone successfully use steering wheel to control the car? Thank you!

**Comment by sytelus** [comment]
See this: https://github.com/Microsoft/AirSim/issues/897
