### ISSUE TITLE
Is there a way to use airsim without a pixhawk controller ?

### ISSUE THREAD

**Issue by AdityaPrasadMishra** [Microsoft/AirSim#94]

**Comment by saihv** [comment]
There's SITL support.

https://github.com/Microsoft/AirSim/blob/master/docs/sitl.md

**Comment by sytelus** [comment]
Well, you are in luck but you have to wait just few more days. I'm writing code to integrate firmware directly in AirSim which will eliminate need for explicit HITL/SITL setup. More coming soon....

**Comment by hanfengsunshine** [comment]
how about now？run the demo without HITL/SITL ?
