### ISSUE TITLE
Problems with Logitech Rocker can't move forward？？？

### ISSUE THREAD

**Issue by lenghandou** [Microsoft/AirSim#948]
please help me！   
Rocker model: logitech extreme 3d PRO
In the ue4 simulation, I can only rise vertically, descend vertically, spin, but I cannot move forward and backward

I need to change where the code can solve this problem？
Is the code before compiling or compiled?
Please answer。

**Comment by tea000001** [comment]
Did you solve this problem?
I used Logitech rocker too, and only can rise vertically, descend vertically, can't forward and backward,
I want to know how to solve that,
thank you very much :)

**Comment by jnaor** [comment]
Same issue here. Airsim 1.2.1, Logitech 3D Pro
