### ISSUE TITLE
Two players in one environment 

### ISSUE THREAD

**Issue by lockeregg** [Microsoft/AirSim#953]
Hi, I am new to airsim, and I am working on a project that needs two players control two different vehicles in a same airsim server. Is it possible to make it happened? 
Thanks

**Comment by sytelus** [comment]
Yes, it is possible. We are improving the support for multi vehicle. Meanwhile, check these issues: https://github.com/Microsoft/AirSim/labels/multi-agent

**Comment by JordanWang0223** [comment]
hello, do you succeed in adding another vehicles and controlling them?
