### ISSUE TITLE
How to set time of day for the evening?

### ISSUE THREAD

**Issue by dehuachen2017** [Microsoft/AirSim#956]
I want drones to fly in the evening. In file settings.json, I set

"TimeOfDay": {
"Enabled": true,
"StartDateTime": "%2018-%04-%12 %18:%30:%00"
}

But the drone still flies during the daytime. How to set time of day for the evening? Thanks.

**Comment by sytelus** [comment]
I think you want:

```
"TimeOfDay": {
  "Enabled": true,
  "StartDateTime": "2018-04-12 18:30:00"
}
```

**Comment by dehuachen2017** [comment]
Thank you for your response.  I use  "StartDateTime": "2018-04-12 20:00:00" in file settings.json. The scene does not change. The drone still flies during the daytime. Can you help me? Thanks.

**Comment by sytelus** [comment]
It's working for me:

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "TimeOfDay": {
     "Enabled": true,
     "StartDateTime": "2018-04-12 18:30:00"
  }
}
```


![image](https://user-images.githubusercontent.com/2096835/38713252-1c73f6bc-3e85-11e8-915a-5744c36ebf91.png)

**Comment by fshamshirdar** [comment]
Any update on this? it uses the current time not the StartDateTime.

**Comment by bmalhigh** [comment]
This a bug. Working on fix.

**Comment by bmalhigh** [comment]
This should be fixed now with the pull request 1581
