### ISSUE TITLE
Created an API for gimbal velocity control

### ISSUE THREAD

**Issue by Amigoshan** [Microsoft/AirSim#957]
Anyone who is interested in adding a gimbal velocity control API could find the modified code here: https://github.com/Amigoshan/AirSim.git
The code is under "gimbal_api" branch. 
This is related to my previous post: https://github.com/Microsoft/AirSim/issues/793. 
Currently, only the front centre camera could be controlled.

**Comment by sytelus** [comment]
My comment: https://github.com/Microsoft/AirSim/issues/793#issuecomment-380998573

**Comment by madratman** [comment]
closing as this is old. we'll a doc revamp for all issues labeled with doc-update
