### ISSUE TITLE
Is SimSteering (Steering wheel + Pedals) compatible with AirSim?

### ISSUE THREAD

**Issue by haider04** [microsoft/AirSim#959]
Hi,
I am working on a vehicle simulator for research purposes and it has SimSteering components (Steering wheel + brake, accelerator pedals) integrated within the vehicle simulator. I wanted to know if SimSteering configuration (Advance force feedback system) is compatible with AirSim and car can be controlled without any problems in windows environment? 
Any help in this regard will be highly appreciated. Thanks!

Haider

**Comment by sytelus** [comment]
We unfortunately don't have experience with SimSteering system but it should be possible to interface it with AirSIm. You can look at SimJoyStick folder to see how joystick is interfaced with AirSim.

**Comment by jonyMarino** [comment]
Closing because this is out of the project scope
