### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by haider04** [Microsoft/AirSim#960]
Hi,
I am getting following build errors. Can someone please comment why these errors appeared and how they can be resolved?

"C:\Users\ladmin\Desktop\AirSim\AirSim\AirSim.sln" (default target) (1) ->
"C:\Users\ladmin\Desktop\AirSim\AirSim\DroneShell\DroneShell.vcxproj" (default target) (2) ->
"C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj" (default target) (3) ->
(ClCompile target) ->
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]
  c:\users\ladmin\desktop\airsim\airsim\airlib\include\common\clockbase.hpp(75): error C2220: warning treated as error
- no 'object' file generated [C:\Users\ladmin\Desktop\AirSim\AirSim\AirLib\AirLib.vcxproj]

    28 Warning(s)
    7 Error(s)

Time Elapsed 00:01:14.71

#### Build failed - see messages above.

Haider

**Comment by Pierrolo** [comment]
I do believe this has to do with the update made to ClockSpeed settings for multirotor in Issue #901

**Comment by senakicir** [comment]
Hello! 
I just got around this by putting a msr::airlib:: in front of all the ClockFactory in SimModeWorldMultiRotor.cpp. Hope it fixes your problem too.

**Comment by haider04** [comment]
Hi,
I can't find SimModeWorldMultiRotor.cpp file in Unreal/Plugins/AirSim/Source/SimMode folder. I have only SimModeBase.cpp and SimModeWorldBase.cpp files + their header files. 
Should the MultiRotor file be present in the folder? Because i can't find this specific file anywhere.

**Comment by senakicir** [comment]
It's in the Unreal/Plugins/AirSim/Source/Multirotor folder actually.

**Comment by chiaohaochang** [comment]
Hiya，
I have tried what you've told. It still doesnt work. So sad.

**Comment by haider04** [comment]
I found it, thanks. You mean to say like this in front of all ClockFactory?
msr::airlib::ClockFactory::get ------

**Comment by haider04** [comment]
Hi senakicir,
I tried your way but still build got failed. 

Hi chiaohaochang,
Are you also getting this same error?

**Comment by haider04** [comment]
Could there also a possibility of build errors because i am not using the specified Visual studio as recommended to build it? Currently i am using VS2015 x86 Native Tools Command Prompt instead of x64 version.

**Comment by sytelus** [comment]
This was mistake in my part. Its fixed now. Sorry about that.
