### ISSUE TITLE
Camera ID doesn't work for right and left on multirotor

### ISSUE THREAD

**Issue by Pierrolo** [microsoft/AirSim#961]
Hi, 
I have the followings setting:

    "SubWindows": [
    {"WindowID": 0, "CameraID": 1, "ImageType": 3, "Visible": true},
    {"WindowID": 1, "CameraID": 0, "ImageType": 3, "Visible": true},
    {"WindowID": 2, "CameraID": 2, "ImageType": 3, "Visible": true}
    ]

And this is what I get:

 
![image](https://user-images.githubusercontent.com/23744690/38741846-381f5c4c-3f3b-11e8-8051-43b4ee3c8c01.png)
As you can see, no matter the camera_id, it always give me the front one...

Same goes when I am requesting images throught the python API : Camera_id 0,1 and 2 give the same images, when I actually want one front, one right and one left. 

Also, it seems the depth is calculated on object, not on pixel, in the picture above, if you only look at the depth images, you would think there is a wall in front of me, when really it's just the floor. But the floor 1cm in front of me and the floor 2m away from me, should not give the same depth value.... Or am I missing something?

The `FOV_Degrees` setting doens't work etiher, whatever the value I give it, it also shows only for 90degrees..

Thanks for your help (and thanks a looooot for AirSim in general) :)

**Comment by sytelus** [comment]
Camera 0,1,2 are very close so you might not see lot of difference in images. Their use is mainly for stereo algorithms. Have you tried camera 3,4,5?

FOV setting also works.

This is what I get for below settings:

```
  "SubWindows": [
	{"WindowID": 0, "CameraID": 2, "ImageType": 0, "Visible": true},
	{"WindowID": 1, "CameraID": 3, "ImageType": 1, "Visible": true},
	{"WindowID": 2, "CameraID": 4, "ImageType": 3, "Visible": true}
  ],
  "CaptureSettings": [
    {
      "ImageType": 0,
      "FOV_Degrees": 130
    }
  ]
```

![image](https://user-images.githubusercontent.com/2096835/38762133-d00f8976-3f3d-11e8-96d8-52d2a128ea71.png)

**Comment by suhalvemu** [comment]
E
Sent from my iPhone
Thanks,
Suhal Vemu.
