### ISSUE TITLE
"API call timed out, entering hover mode" when running hello_drone.py

### ISSUE THREAD

**Issue by zhonghankb** [Microsoft/AirSim#963]
I start the UE environment which is AirSimNH v1.1.9 by run.bat.
I run the hello_drone.py with python cmds.
everthing seems to work fine at the beginning until the drone takeoff and print the return of client.getMultirotorState(). Then the up left of the UE window shows "API call timed out, entering hover mode". After this ,cmds like client.moveByAngleZ(0.0, 0.0, -15, 0.1, 10) will raise an error as below.
###############################
Traceback (most recent call last):
  File "hello_drone.py", line 44, in <module>
    client.moveByAngleZ(0.0, 0.0, -15, 0.1, 10)
  File "C:\Users\kobe\Documents\github\projects\airsim\AirSim\PythonClient\AirSimClient.py", line 550, in moveByAngleZ
    return self.client.call('moveByAngleZ', pitch, roll, z, yaw, duration)
  File "C:\ProgramData\Anaconda3\lib\site-packages\msgpackrpc\session.py", line 41, in call
    return self.send_request(method, args).get()
  File "C:\ProgramData\Anaconda3\lib\site-packages\msgpackrpc\future.py", line 45, in get
    raise error.RPCError(self._error)
msgpackrpc.error.RPCError: rpclib: server could not find function 'moveByAngleZ' with argument count 5.
#########################################
I am not sure whether I call the api function in a wrong way or something else goes wrong.
hope someone could help me with this.

**Comment by sytelus** [comment]
This message appears when vehicle stops getting any command for 1 second. Yo can re-enable API by,

```
client.enableApiControl(True)
client.armDisarm(True)
```
