### ISSUE TITLE
Error on compiling my project on Linux

### ISSUE THREAD

**Issue by BrunoXL** [Microsoft/AirSim#967]
I followed the instructions on wiki pages and [here](https://github.com/Microsoft/AirSim/issues/899) but I still cannot compile my project.
On running  myProject.uproject it is prompt the window below, for which I hit 'no`.
![selection_027](https://user-images.githubusercontent.com/11648780/38772175-00c41324-4007-11e8-9ee7-7ead87fffe68.png)
After that it is prompt a second window:

![selection_028](https://user-images.githubusercontent.com/11648780/38772201-828c9dae-4007-11e8-8be8-c4271cdb77f7.png)

And Finally an error window came out:

![selection_029](https://user-images.githubusercontent.com/11648780/38772208-b4efbd30-4007-11e8-9216-78513acbd60d.png)

Running from command line, it shows the log:

     LogPluginManager: Mounting plugin AirSim
	LogInit: Warning: Incompatible or missing module: libUE4Editor-LandscapeMountains.so
	LogInit: Warning: Incompatible or missing module: libUE4Editor-AirSim.so
	STUBBED: FDesktopPlatformLinux::GetNativeFeedbackContext at /home/bruno/repos/UnrealEngine/Engine/Source/Developer/DesktopPlatform/Private/Linux/DesktopPlatformLinux.cpp:269 (GetNativeFeedbackContext)
	Running /home/bruno/repos/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe LandscapeMountains Development Linux -project="/home/bruno/repos/LandscapeMountains/LandscapeMountains.uproject" -editorrecompile -progress -NoHotReloadFromIDE

	Running Mono...

	~/repos/UnrealEngine/Engine ~/repos/UnrealEngine/Engine/Binaries/Linux
	@progress push 5%
	@progress pop
	Performing 4 actions (4 in parallel)
	[1/4] Compile Module.AirSim.gen.cpp
	[2/4] Compile Module.AirSim.cpp
	clang: error: no such file or directory: '/home/bruno/repos/LandscapeMountains/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.gen.cpp'
	clang: error: no input files
	clang: error: no such file or directory: '/home/bruno/repos/LandscapeMountains/Plugins/AirSim/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/AirSim/Module.AirSim.cpp'
	clang: error: no input files
	ERROR: UBT ERROR: Failed to produce item: /home/bruno/repos/LandscapeMountains/Plugins/AirSim/Binaries/Linux/libUE4Editor-AirSim.so
	Total build time: 3.92 seconds (Local executor: 0.00 seconds)
	LogInit: Warning: Still incompatible or missing module: libUE4Editor-LandscapeMountains.so
	LogInit: Warning: Still incompatible or missing module: libUE4Editor-AirSim.so

**Comment by sytelus** [comment]
Please try out the new build. We have upgraded to UE 4.18 so you will need to follow these steps:

https://github.com/Microsoft/AirSim/blob/master/docs/unreal_upgrade.md
