### ISSUE TITLE
settings.json was Writen by default each time I start AirSim for PX4

### ISSUE THREAD

**Issue by XueYuSky** [Microsoft/AirSim#969]
win10 edu.
VS2015 pro3.
UE4.16.3

I set the compile environment, airsim can run with Xbox controler. But After I write the settings.json file to use RC, Each time I start UE4(Airsim), the "settings.json" was writen back to the file when it was created.

"
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0
}
"

**Comment by sytelus** [comment]
I can't reproduce this. You might want to double check file paths and timestamps on files.

**Comment by damilolah** [comment]
I'm having the same issue!!! Help!
