### ISSUE TITLE
Error with buld.cmd  eigen3\eigen\src\core\arch\cuda\half.h : error C2220

### ISSUE THREAD

**Issue by whyscience** [Microsoft/AirSim#97]
error eigen-3.2.2\eigen3\eigen\src\core\arch\cuda\half.h   
warning C4819: 
error C2220:
![image](https://cloud.githubusercontent.com/assets/3918941/23751901/443b201e-050e-11e7-8440-86e94fa5d91b.png)

ignore the Chinese

**Comment by whyscience** [comment]
problem sovled
open eigen3\Eigen\src\Core\arch\CUDA\half.h and save using UTF-8 coding

**Comment by Focke-Wulf** [comment]
666666 Thanks for the Solution!

**Comment by woooha** [comment]
You'd better to save file with UTF-8 with BOM encoding.

**Comment by chhtz** [comment]
FYI: This had been fixed upstream a while ago in Eigen by removing the non-ASCII quotation marks: https://bitbucket.org/eigen/eigen/commits/54f26e677873161213620be9d5f4af22cab94c27

**Comment by qixuxiang** [comment]
I sovled the problem in this way:

![_20180127115408](https://user-images.githubusercontent.com/16591716/35468452-0b3b2c9c-0359-11e8-82c6-9e282dfbcc66.jpg)
