### ISSUE TITLE
How  to set up a camera direction for a car?

### ISSUE THREAD

**Issue by hyybuaa** [microsoft/AirSim#971]
if you need set camera's gimble, the imagetype have to be -1,but there is not additional camear in  car.So we can't set camera direction for a car?

**Comment by Robin-Wong** [comment]
I think we can see the camera direction in BP_FlyingPawn when the UE4 running.
Blocks project->Run->search BP_FlyingPawn in world->View.

**Comment by Beijingsheng** [comment]
@BrianN92   If I want to make the front_center camera of the car turn right, should I change the Yaw in settings.json?
