### ISSUE TITLE
Variable velocity using computer vision mode

### ISSUE THREAD

**Issue by Domi47** [microsoft/AirSim#973]
I'm using airsim to get images from simulation and use them to compute angular velocities based on their changes. For this purpose i want to disable the physics in order to be able to rotate drone as I want, so I started to use Computer vision mode. The problem I have now is I can't change its velocity, it seems APIs such as moveByvelocity only works when FlightController is active. 
Docs say you can still use APIs on this mode but seems only simSetPose works for changing pose. Is there any way to control velocity using Computer Vision mode?

Thanks!

**Comment by msb336** [comment]
Camera vision mode's velocity is constant when being controlled manually. At this time we are not developing velocity controls for CV mode.

You can fake velocity by using `simSetVehiclePose` at some frequency to move your camera around the map.
