### ISSUE TITLE
Steering wheel with Airsim

### ISSUE THREAD

**Issue by BrianN92** [microsoft/AirSim#974]
"PhysXCar" : {
    "RC": {
        "RemoteControlID": 0
    }
}

After adding above settings to the json file, a wired thing happened. I can only control the direction of car by accelerator pedal. The steering angle was -1.25 when I release the pedal, and the value would change with the change of force I gave to the pedal. Besides, there was no value of speed, steering, or throttle in the record file.

Did anyone meet this kind of issue? Thank you!

**Comment by BrianN92** [comment]
BTW, I'm using Logitech G29 as a steering wheel controller.

**Comment by BrianN92** [comment]
Besides, I did put the x360ce exe in the same directory as the AirSim binary.

**Comment by mitchellspryn** [comment]
For the record, we solved the problem in [this issue](https://github.com/Microsoft/AutonomousDrivingCookbook/issues/27). tl;dr: if you're using the x360ce route, make sure the x360ce executable is run from the **same directory** as the binary. This might be nested within subfolders.

**Comment by sytelus** [comment]
FYI - AirSim now has out-of-support for Logitech G920 wheel (i.e. don't put x360ce in folder). We don't have G29 so we haven't tested that one but you can try remove x360ce  and see if that works. If it doesn't, it might be just matter of [extending this code](https://github.com/Microsoft/AirSim/blob/master/Unreal/Plugins/AirSim/Source/SimJoyStick/SimJoyStick.cpp#L68) a little bit.

**Comment by rohjunha** [comment]
I am currently using G29 and code below worked for me with a PS3 setup:
```
joystick_controls_.steering = joystick_state_.left_x;
joystick_controls_.throttle = joystick_state_.left_y;
joystick_controls_.brake = (joystick_state_.left_y < -0.5f) ? 1.0f : 0.0f;
```

**Comment by sytelus** [comment]
Would you mind to get pull request for this?

**Comment by BrianN92** [comment]
Hi @mitchellspryn , did you try to use Thrustmaster in the new released city map? I [failed to do that.](https://github.com/Microsoft/AirSim/issues/1024)

**Comment by mitchellspryn** [comment]
Nope. It was broken for me, too (also for Hawaii). I haven't gotten time to debug it.

**Comment by kuasha** [comment]
I am using the city environment (precompiled windows binary) on windows 10. I am trying to use Logitech G920 with following settings:

```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.0,
  "SimMode": "Car",
  "PhysXCar" : {
    "RC": {
      "RemoteControlID": 0
    }
  }
}
```
I see that the settings file is being picked up by the simulator but it still shows input mode to be keyboard. I can drive with arrow keys. I have downloaded the environment 2 days ago. Device manager shows the controller as Xbox Gaming Device.

**Comment by hrishikeshtawade04** [comment]
I have downloaded the simple maze precompiled binary of airsim. I want to connect the G920 wheel to it. How to do it?

**Comment by hrishikeshtawade04** [comment]
I have Logitech G920 steering wheel and tried connecting it to the blocks environment. I edited the settings.json file and now it looks like this.
{
"SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
"SettingsVersion": 1.2,
"PhysXCar" : {
"RC": {
"RemoteControlID": 0
}
}

}

But when I stop and play the unreal engine I am still getting the control mode as keyboard. Is there something else to be done?

**Comment by sytelus** [comment]
There had been change in settings.json schema. The PhysXCar should be under Vehicles section. Please see settings.md in docs folder.

**Comment by hrishikeshtawade04** [comment]
So if I add the vehicles section in the settings.json file and connect my controller and open the blocks environment it will connect right?

**Comment by hrishikeshtawade04** [comment]
These are my current settings. Are they proper?
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Car",
  "ViewMode": "",
  "Vehicles": {
    "PhysXCar": {
      "VehicleType": "PhysXCar",
      "DefaultVehicleState": "",
      "AutoCreate": true,
      "PawnPath": "",
      "EnableCollisionPassthrogh": false,
      "EnableCollisions": true,
      "RC": {
        "RemoteControlID": 0
      }	     
    }
  }
}

**Comment by tfromb** [comment]
Hi, Im having the same issue. I am using a G920 and followed the instructions however I can't use the pedals to move the vehicle. The simulator picks up on the steering angles. What changes should be made to the setting.json file to enable the steering wheel to fully control the vehicle? Thank you

**Comment by wintersoom** [comment]
> Hi, Im having the same issue. I am using a G920 and followed the instructions however I can't use the pedals to move the vehicle. The simulator picks up on the steering angles. What changes should be made to the setting.json file to enable the steering wheel to fully control the vehicle? Thank you

HI, do you solve the problem? i have the same problem now

**Comment by wintersoom** [comment]
> Hi, Im having the same issue. I am using a G920 and followed the instructions however I can't use the pedals to move the vehicle. The simulator picks up on the steering angles. What changes should be made to the setting.json file to enable the steering wheel to fully control the vehicle? Thank you

HI, do you solve the problem? i have the same problem now

**Comment by wintersoom** [comment]
> I have Logitech G920 steering wheel and tried connecting it to the blocks environment. I edited the settings.json file and now it looks like this.
> {
> "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
> "SettingsVersion": 1.2,
> "PhysXCar" : {
> "RC": {
> "RemoteControlID": 0
> }
> }
> 
> }
> 
> But when I stop and play the unreal engine I am still getting the control mode as keyboard. Is there something else to be done?

HI, do you solve the problem? i have the same problem now

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
