### ISSUE TITLE
Binaries are not working

### ISSUE THREAD

**Issue by Pierrolo** [microsoft/AirSim#977]
Hi I downloaded the NH environment from your binaries, but it doesn't work. 
At the start, I choose multirotor ,so I click "No" and then it displays the following:

![image](https://user-images.githubusercontent.com/23744690/38857597-f5d7b234-4229-11e8-88f0-d676b2bafa89.png)

and then : 
![image](https://user-images.githubusercontent.com/23744690/38857623-05727eb8-422a-11e8-9ff3-d5a1063b779b.png)

I tried launching it on two different computers and I get the same error. I also tried to run the latest ZhangJiaJie, and the same error poped up. Those same error also happen when I try to select the car.
My belief is that, 5 days ago there were a few changes made, clockspeed for example, that made the build and the binaries not work. Then it got fixed for the build, but I don't think the binaries were updated...

Thanks

**Comment by haider04** [comment]
I am having this same problem. But my city environment just worked fine. Having problems with NH and Africa binaries. 
Any solution so far?

**Comment by Pierrolo** [comment]
Hi,
I just downloaded the city env, and got the same problem personnaly.

**Comment by totht91** [comment]
prerelease is broken for us too.

**Comment by allen9273** [comment]
City environment is fine in car mode, but drone mode is broken down.

**Comment by QiyuZ** [comment]
The same question. However the in the previous version, NH can work

**Comment by vinbo** [comment]
@sytelus I still met the similar problem in 1.1.10, with pop up box becoming" error at start up: error creating directiories, hr=5" , how can i solve this, please? 
![error at startup error creating directory hr 5](https://user-images.githubusercontent.com/29434082/41197543-e9ad1568-6c94-11e8-8d2a-a866a1154c5f.png)
and click "OK" and then
![error at startup error creating directory hr 5 png_continued](https://user-images.githubusercontent.com/29434082/41197544-09656c2a-6c95-11e8-8b53-4600d82ac604.png)

**Comment by msb336** [comment]
as @vinbo 's issue is separate from the problem listed in this thread, let's track it in #1150 

The issue in this thread should be solved with the current binary releases.
