### ISSUE TITLE
Can I use part of the built-in environment?

### ISSUE THREAD

**Issue by BrianN92** [Microsoft/AirSim#989]
Hi all, I am doing the E2E deep learning in Autonomous Cooking book. I like the "City" environment because of the urban scenes and some moving cars and people. But it is too large and can not be run smoothly on my PC. So I am wondering if I can use part of it, like fewer streets, buildings or cars, so that it can be run better? Thank you!

**Comment by allen9273** [comment]
I'm looking forward to the neighborhood environment with moving people.

**Comment by allen9273** [comment]
Yes, I try v1.1.10 'city', car mode performs smoothly, but the binary doesn't work in drone mode #977. I hope the bug can be fixed soon, thanks.

**Comment by sytelus** [comment]
It's fixed now.
