### ISSUE TITLE
Adding ROSIntegrationVision as a child actor of my AirSim drone

### ISSUE THREAD

**Issue by gonzaloaguilarjimenez** [microsoft/AirSim#990]
Good afternoon, 

I am contacting you becasue I have spend some time trying to attach ROSIntegrationVision "https://github.com/code-iai/ROSIntegrationVision" as a child actor of the drone but I cannot reach to succeed. 

I wonder if you could help me. 

What I have been doing it to attach the "Vision Actor" from ROSIntegrationVision to my Player Start actor, but it makes no good result.

Is it possible that I get from you some information regarding the way to do it?

Thanks a lot.

Best regards.

**Comment by RVBldr** [comment]
Internal VSTF 7433.

**Comment by jonyMarino** [comment]
Closed due to age.
Please feel free to open a new issue (referring to this one) if you still have this problem.
Thanks!
