### ISSUE TITLE
I want to get the relative position of the vehicle and the obstacle by ultrasonic

### ISSUE THREAD

**Issue by xianshichi** [Microsoft/AirSim#994]
I want to get the relative position of the vehicle and the obstacle by ultrasonic，how should I operate？

**Comment by sytelus** [comment]
Ultrasonic sensor is not implemented yet.

**Comment by GuangTongLiu1** [comment]
> Ultrasonic sensor is not implemented yet.

Hi, How many kind sensors can be used in Airsim ?
