### ISSUE TITLE
PX4 software-in-the loop keeps sending "freefall detected", "landing", "freefall detected"

### ISSUE THREAD

**Issue by zungam** [Microsoft/AirSim#995]
Hello, we are trying to use the PX4 instead of simple-flight, and we are seeing some weird behavior. 

We suspect that when the drone lands on ground, a collision is detected in Unreal Engine. To make the drone not pass through the polygon, Unreal Engine pushes the drone up 1 cm. However, this is 1 cm freefall, so that PX4 thinks is in the air. Once it collide with the ground again, there is a collision, a landing is detected but the same thing happens all over again. 
Evidence for our suspicion:

- When on ground, we observe spikes in MavLink Z-acceleration many times per second, switching between 9.81 m/s2 and 0 m/m2 every tick.
- PX4 Software-In-The-Loop turns state on "freefall detected", "landing", "takeoff", many times per second.
- If we start Unreal Engine without a ground to land on, there is no problem.

This problem makes our drone not able to take-off, as it fools our PX4 Software-In-The-Loop to think it is falling, when it is actually standing still. We are on an AirSim version from December 2017, and need to stay on it due to compatibility issues. Do you know of a quick fix to our problem? 

Sincerely
Magnus

**Comment by sytelus** [comment]
@lovettchris might be interested.

**Comment by lovettchris** [comment]
Things seem to work a lot better with latest AirSim bits and PX4 version v1.8.2.  Here's the mavlink z-acceleration during a simple take off landing.
![image](https://user-images.githubusercontent.com/18707114/50140189-bfd07c80-0258-11e9-809b-8489b06812b4.png)
