### ISSUE TITLE
AirSim Rebuild Fail UE4 

### ISSUE THREAD

**Issue by shriram17** [Microsoft/AirSim#997]
Hey, 
I'm currently using AirSim plugin in my own UE4 project and modified a Show Message string in the existing AirSim code (SimHUD.cpp, Line 256). I also copied the .bat files from AirSim\Unreal\Environments\Blocks as mentioned in the [FAQ section](https://github.com/Microsoft/AirSim/blob/master/docs/unreal_custenv.md#is-there-easy-way-to-sync-code-in-my-unreal-project-with-code-in-airsim-repo).
On building the project through VS I encounter these errors

> [Adaptive unity build] Disabling PCH for excluded files. Set bAdaptiveUnityDisablesPCH to false in BuildConfiguration.xml to change this behavior.
[Adaptive unity build] Excluded from AirSim unity file: SimHUD.cpp
\Plugins\AirSim\Source\SimHUD\SimHUD.cpp(35): error C2653: 'UAirBlueprintLib': is not a class or namespace name
\Plugins\AirSim\Source\SimHUD\SimHUD.cpp(35): error C3861: 'ShowMessage': identifier not found
\Plugins\AirSim\Source\SimHUD\SimHUD.cpp(56): error C2064: term does not evaluate to a function taking 0 arguments

Are there any additional steps to be performed before compiling a modified version of AirSim through VS2017?

**Note**
1.  Same code modification compiled and worked on Blocks and other Unreal projects.
2. My current project contains another UE4 plugin [RunTimeMeshComponent](https://github.com/Koderz/RuntimeMeshComponent).

**Comment by sytelus** [comment]
Unfortunately we have limited bandwidth in debugging custom modifications. You should generate .sln file, load it up in VS and see where the error is occurring and why.

**Comment by sytelus** [comment]
Just encountered these errors and traced back to IWYU mode in UE 4.18. It was just matter of including all needed UE headers. This is now fixed in this commit: https://github.com/Microsoft/AirSim/commit/7bddd5857791f9c164e8eba80c229f199c0babf8 .
