### ISSUE TITLE
source code or binaries-linux  of CityEnviron

### ISSUE THREAD

**Issue by husha1993** [Microsoft/AirSim#998]
Hi,

Will the source code or binaries-linux  of  CityEnviron be released?
Currently I only find the binaries-windows of CityEnviron here:
https://github.com/Microsoft/AirSim/releases

Thanks.

**Comment by sytelus** [comment]
Yes, we are planning to release CityEnviron binaries after we complete upgrade to UE 4.18 - hopefully in couple of weeks.

**Comment by Domi47** [comment]
Hi @sytelus, i need an open environment like this city neighborhood for linux and was thinking about buying it. Do you still plan to release it soon? this environment allows you to fly inside buildings too?
Thanks!

**Comment by sytelus** [comment]
The City Environment binaries are now released for Linux!

https://github.com/Microsoft/AirSim/releases/tag/untagged-a395e93dd037d937537a

**Comment by abinlee** [comment]
I got "Page not fount" when I click "https://github.com/Microsoft/AirSim/releases/tag/untagged-a395e93dd037d937537a".

**Comment by micmarty** [comment]
Could someone refresh that link 🥇 ??? I'm starving here, haha

**Comment by kang235** [comment]
I cannot open the link either. Could you please update it @sytelus? Thanks.
